local AddonName, Addon = ...

local LSM = LibStub("LibSharedMedia-3.0")

function Addon:RegisterLSM()
    --StatusBars
    LSM:Register("statusbar","Atrocity", [[Interface\Addons\AtrocityMedia\StatusBars\Atrocity]])
    LSM:Register("statusbar","Kait", [[Interface\Addons\AtrocityMedia\StatusBars\Kait.tga]])
    --Sounds
    LSM:Register("sound","|cFF7381ffBlade|r", [[Interface\Addons\AtrocityMedia\Sounds\Blade.ogg]])
    LSM:Register("sound","|cFF7381ffBlood|r", [[Interface\Addons\AtrocityMedia\Sounds\Blood.ogg]])
    LSM:Register("sound","|cFF7381ffBuffed|r", [[Interface\Addons\AtrocityMedia\Sounds\Buffed.ogg]])
    LSM:Register("sound","|cFF7381ffBullet|r", [[Interface\Addons\AtrocityMedia\Sounds\Bullet.ogg]])
    LSM:Register("sound","|cFF7381ffInfo|r", [[Interface\Addons\AtrocityMedia\Sounds\Info.ogg]])
    LSM:Register("sound","|cFF7381ffMail|r", [[Interface\Addons\AtrocityMedia\Sounds\Mail.ogg]])
    LSM:Register("sound","|cFF7381ffPositive|r", [[Interface\Addons\AtrocityMedia\Sounds\Positive.ogg]])
    LSM:Register("sound","|cFF7381ffThunder|r", [[Interface\Addons\AtrocityMedia\Sounds\Thunder.ogg]])
    LSM:Register("sound","|cFF7381ffOn You|r", [[Interface\Addons\AtrocityMedia\Sounds\OnYou.ogg]])
    LSM:Register("sound", "|cFF7381ff1|r", [[Interface\Addons\AtrocityMedia\Sounds\1.ogg]])
    LSM:Register("sound", "|cFF7381ff2|r", [[Interface\Addons\AtrocityMedia\Sounds\2.ogg]])
    LSM:Register("sound", "|cFF7381ff3|r", [[Interface\Addons\AtrocityMedia\Sounds\3.ogg]])
    LSM:Register("sound", "|cFF7381ff4|r", [[Interface\Addons\AtrocityMedia\Sounds\4.ogg]])
    LSM:Register("sound", "|cFF7381ff5|r", [[Interface\Addons\AtrocityMedia\Sounds\5.ogg]])
    LSM:Register("sound", "|cFF7381ff6|r", [[Interface\Addons\AtrocityMedia\Sounds\6.ogg]])
    LSM:Register("sound", "|cFF7381ff7|r", [[Interface\Addons\AtrocityMedia\Sounds\7.ogg]])
    LSM:Register("sound", "|cFF7381ff8|r", [[Interface\Addons\AtrocityMedia\Sounds\8.ogg]])
    LSM:Register("sound", "|cFF7381ff9|r", [[Interface\Addons\AtrocityMedia\Sounds\9.ogg]])
    LSM:Register("sound", "|cFF7381ff10|r", [[Interface\Addons\AtrocityMedia\Sounds\10.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\AtrocityMedia\Sounds\01.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\AtrocityMedia\Sounds\02.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\AtrocityMedia\Sounds\03.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\AtrocityMedia\Sounds\04.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\AtrocityMedia\Sounds\05.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\AtrocityMedia\Sounds\06.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\AtrocityMedia\Sounds\07.ogg]])
    LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\AtrocityMedia\Sounds\08.ogg]])
    LSM:Register("sound", "|cFF7381ffAdd|r", [[Interface\Addons\AtrocityMedia\Sounds\Add.ogg]])
    LSM:Register("sound", "|cFF7381ffAdds|r", [[Interface\Addons\AtrocityMedia\Sounds\Adds.ogg]])
    LSM:Register("sound", "|cFF7381ffAffix|r", [[Interface\Addons\AtrocityMedia\Sounds\Affix.ogg]])
    LSM:Register("sound", "|cFF7381ffAoE|r", [[Interface\Addons\AtrocityMedia\Sounds\AoE.ogg]])
    LSM:Register("sound", "|cFF7381ffAssist|r", [[Interface\Addons\AtrocityMedia\Sounds\Assist.ogg]])
    LSM:Register("sound", "|cFF7381ffAvoid|r", [[Interface\Addons\AtrocityMedia\Sounds\Avoid.ogg]])
    LSM:Register("sound", "|cFF7381ffBack|r", [[Interface\Addons\AtrocityMedia\Sounds\Back.ogg]])
    LSM:Register("sound", "|cFF7381ffBackup|r", [[Interface\Addons\AtrocityMedia\Sounds\Backup.ogg]])
    LSM:Register("sound", "|cFF7381ffBait|r", [[Interface\Addons\AtrocityMedia\Sounds\Bait.ogg]])
    LSM:Register("sound", "|cFF7381ffBeam|r", [[Interface\Addons\AtrocityMedia\Sounds\Beam.ogg]])
    LSM:Register("sound", "|cFF7381ffBloodlust|r", [[Interface\Addons\AtrocityMedia\Sounds\Bloodlust.ogg]])
    LSM:Register("sound", "|cFF7381ffBlue|r", [[Interface\Addons\AtrocityMedia\Sounds\Blue.ogg]])
    LSM:Register("sound", "|cFF7381ffBoss|r", [[Interface\Addons\AtrocityMedia\Sounds\Boss.ogg]])
    LSM:Register("sound", "|cFF7381ffBreak|r", [[Interface\Addons\AtrocityMedia\Sounds\Break.ogg]])
    LSM:Register("sound", "|cFF7381ffBuff|r", [[Interface\Addons\AtrocityMedia\Sounds\Buff.ogg]])
    LSM:Register("sound", "|cFF7381ffCC|r", [[Interface\Addons\AtrocityMedia\Sounds\CC.ogg]])
    LSM:Register("sound", "|cFF7381ffCD|r", [[Interface\Addons\AtrocityMedia\Sounds\CD.ogg]])
    LSM:Register("sound", "|cFF7381ffCenter|r", [[Interface\Addons\AtrocityMedia\Sounds\Center.ogg]])
    LSM:Register("sound", "|cFF7381ffChain|r", [[Interface\Addons\AtrocityMedia\Sounds\Chain.ogg]])
    LSM:Register("sound", "|cFF7381ffCharge|r", [[Interface\Addons\AtrocityMedia\Sounds\Charge.ogg]])
    LSM:Register("sound", "|cFF7381ffClear|r", [[Interface\Addons\AtrocityMedia\Sounds\Clear.ogg]])
    LSM:Register("sound", "|cFF7381ffCollect|r", [[Interface\Addons\AtrocityMedia\Sounds\Collect.ogg]])
    LSM:Register("sound", "|cFF7381ffDance|r", [[Interface\Addons\AtrocityMedia\Sounds\Dance.ogg]])
    LSM:Register("sound", "|cFF7381ffDebuff|r", [[Interface\Addons\AtrocityMedia\Sounds\Debuff.ogg]])
    LSM:Register("sound", "|cFF7381ffDispell|r", [[Interface\Addons\AtrocityMedia\Sounds\Dispell.ogg]])
    LSM:Register("sound", "|cFF7381ffDodge|r", [[Interface\Addons\AtrocityMedia\Sounds\Dodge.ogg]])
    LSM:Register("sound", "|cFF7381ffDont Move|r", [[Interface\Addons\AtrocityMedia\Sounds\Dont Move.ogg]])
    LSM:Register("sound", "|cFF7381ffDot|r", [[Interface\Addons\AtrocityMedia\Sounds\Dot.ogg]])
    LSM:Register("sound", "|cFF7381ffDrop|r", [[Interface\Addons\AtrocityMedia\Sounds\Drop.ogg]])
    LSM:Register("sound", "|cFF7381ffEnter|r", [[Interface\Addons\AtrocityMedia\Sounds\Enter.ogg]])
    LSM:Register("sound", "|cFF7381ffEscort|r", [[Interface\Addons\AtrocityMedia\Sounds\Escort.ogg]])
    LSM:Register("sound", "|cFF7381ffExit|r", [[Interface\Addons\AtrocityMedia\Sounds\Exit.ogg]])
    LSM:Register("sound", "|cFF7381ffFixate|r", [[Interface\Addons\AtrocityMedia\Sounds\Fixate.ogg]])
    LSM:Register("sound", "|cFF7381ffFront|r", [[Interface\Addons\AtrocityMedia\Sounds\Front.ogg]])
    LSM:Register("sound", "|cFF7381ffGate|r", [[Interface\Addons\AtrocityMedia\Sounds\Gate.ogg]])
    LSM:Register("sound", "|cFF7381ffGather|r", [[Interface\Addons\AtrocityMedia\Sounds\Gather.ogg]])
    LSM:Register("sound", "|cFF7381ffGreen|r", [[Interface\Addons\AtrocityMedia\Sounds\Green.ogg]])
    LSM:Register("sound", "|cFF7381ffHealcd|r", [[Interface\Addons\AtrocityMedia\Sounds\Healcd.ogg]])
    LSM:Register("sound", "|cFF7381ffHide|r", [[Interface\Addons\AtrocityMedia\Sounds\Hide.ogg]])
    LSM:Register("sound", "|cFF7381ffHigh Energy|r", [[Interface\Addons\AtrocityMedia\Sounds\High Energy.ogg]])
    LSM:Register("sound", "|cFF7381ffHigh Stacks|r", [[Interface\Addons\AtrocityMedia\Sounds\High Stacks.ogg]])
    LSM:Register("sound", "|cFF7381ffImmunity|r", [[Interface\Addons\AtrocityMedia\Sounds\Immunity.ogg]])
    LSM:Register("sound", "|cFF7381ffIn|r", [[Interface\Addons\AtrocityMedia\Sounds\In.ogg]])
    LSM:Register("sound", "|cFF7381ffInterrupt|r", [[Interface\Addons\AtrocityMedia\Sounds\Interrupt.ogg]])
    LSM:Register("sound", "|cFF7381ffIntermission|r", [[Interface\Addons\AtrocityMedia\Sounds\Intermission.ogg]])
    LSM:Register("sound", "|cFF7381ffInvisibility|r", [[Interface\Addons\AtrocityMedia\Sounds\Invisibility.ogg]])
    LSM:Register("sound", "|cFF7381ffJump|r", [[Interface\Addons\AtrocityMedia\Sounds\Jump.ogg]])
    LSM:Register("sound", "|cFF7381ffKick|r", [[Interface\Addons\AtrocityMedia\Sounds\Kick.ogg]])
    LSM:Register("sound", "|cFF7381ffKnock|r", [[Interface\Addons\AtrocityMedia\Sounds\Knock.ogg]])
    LSM:Register("sound", "|cFF7381ffLeft|r", [[Interface\Addons\AtrocityMedia\Sounds\Left.ogg]])
    LSM:Register("sound", "|cFF7381ffLinked|r", [[Interface\Addons\AtrocityMedia\Sounds\Linked.ogg]])
    LSM:Register("sound", "|cFF7381ffLoS|r", [[Interface\Addons\AtrocityMedia\Sounds\LoS.ogg]])
    LSM:Register("sound", "|cFF7381ffMelee|r", [[Interface\Addons\AtrocityMedia\Sounds\Melee.ogg]])
    LSM:Register("sound", "|cFF7381ffMove|r", [[Interface\Addons\AtrocityMedia\Sounds\Move.ogg]])
    LSM:Register("sound", "|cFF7381ffNext|r", [[Interface\Addons\AtrocityMedia\Sounds\Next.ogg]])
    LSM:Register("sound", "|cFF7381ffNuke|r", [[Interface\Addons\AtrocityMedia\Sounds\Nuke.ogg]])
    LSM:Register("sound", "|cFF7381ffOrange|r", [[Interface\Addons\AtrocityMedia\Sounds\Orange.ogg]])
    LSM:Register("sound", "|cFF7381ffOrb|r", [[Interface\Addons\AtrocityMedia\Sounds\Orb.ogg]])
    LSM:Register("sound", "|cFF7381ffOut|r", [[Interface\Addons\AtrocityMedia\Sounds\Out.ogg]])
    LSM:Register("sound", "|cFF7381ffOverlap|r", [[Interface\Addons\AtrocityMedia\Sounds\Overlap.ogg]])
    LSM:Register("sound", "|cFF7381ffPhase2|r", [[Interface\Addons\AtrocityMedia\Sounds\Phase2.ogg]])
    LSM:Register("sound", "|cFF7381ffPhase3|r", [[Interface\Addons\AtrocityMedia\Sounds\Phase3.ogg]])
    LSM:Register("sound", "|cFF7381ffPots|r", [[Interface\Addons\AtrocityMedia\Sounds\Pots.ogg]])
    LSM:Register("sound", "|cFF7381ffPull|r", [[Interface\Addons\AtrocityMedia\Sounds\Pull.ogg]])
    LSM:Register("sound", "|cFF7381ffPurple|r", [[Interface\Addons\AtrocityMedia\Sounds\Purple.ogg]])
    LSM:Register("sound", "|cFF7381ffPush|r", [[Interface\Addons\AtrocityMedia\Sounds\Push.ogg]])
    LSM:Register("sound", "|cFF7381ffRange|r", [[Interface\Addons\AtrocityMedia\Sounds\Range.ogg]])
    LSM:Register("sound", "|cFF7381ffReady|r", [[Interface\Addons\AtrocityMedia\Sounds\Ready.ogg]])
    LSM:Register("sound", "|cFF7381ffRed|r", [[Interface\Addons\AtrocityMedia\Sounds\Red.ogg]])
    LSM:Register("sound", "|cFF7381ffReflect|r", [[Interface\Addons\AtrocityMedia\Sounds\Reflect.ogg]])
    LSM:Register("sound", "|cFF7381ffRight|r", [[Interface\Addons\AtrocityMedia\Sounds\Right.ogg]])
    LSM:Register("sound", "|cFF7381ffRoot|r", [[Interface\Addons\AtrocityMedia\Sounds\Root.ogg]])
    LSM:Register("sound", "|cFF7381ffSeed|r", [[Interface\Addons\AtrocityMedia\Sounds\Seed.ogg]])
    LSM:Register("sound", "|cFF7381ffSentry|r", [[Interface\Addons\AtrocityMedia\Sounds\Sentry.ogg]])
    LSM:Register("sound", "|cFF7381ffSelfcd|r", [[Interface\Addons\AtrocityMedia\Sounds\Selfcd.ogg]])
    LSM:Register("sound", "|cFF7381ffShield|r", [[Interface\Addons\AtrocityMedia\Sounds\Shield.ogg]])
    LSM:Register("sound", "|cFF7381ffSoak|r", [[Interface\Addons\AtrocityMedia\Sounds\Soak.ogg]])
    LSM:Register("sound", "|cFF7381ffSoon|r", [[Interface\Addons\AtrocityMedia\Sounds\Soon.ogg]])
    LSM:Register("sound", "|cFF7381ffSpawn|r", [[Interface\Addons\AtrocityMedia\Sounds\Spawn.ogg]])
    LSM:Register("sound", "|cFF7381ffSpellsteal|r", [[Interface\Addons\AtrocityMedia\Sounds\Spellsteal.ogg]])
    LSM:Register("sound", "|cFF7381ffSplit|r", [[Interface\Addons\AtrocityMedia\Sounds\Split.ogg]])
    LSM:Register("sound", "|cFF7381ffSpread|r", [[Interface\Addons\AtrocityMedia\Sounds\Spread.ogg]])
    LSM:Register("sound", "|cFF7381ffStack|r", [[Interface\Addons\AtrocityMedia\Sounds\Stack.ogg]])
    LSM:Register("sound", "|cFF7381ffStop|r", [[Interface\Addons\AtrocityMedia\Sounds\Stop.ogg]])
    LSM:Register("sound", "|cFF7381ffStopcast|r", [[Interface\Addons\AtrocityMedia\Sounds\Stopcast.ogg]])
    LSM:Register("sound", "|cFF7381ffSwitch|r", [[Interface\Addons\AtrocityMedia\Sounds\Switch.ogg]])
    LSM:Register("sound", "|cFF7381ffTargeted|r", [[Interface\Addons\AtrocityMedia\Sounds\Targeted.ogg]])
    LSM:Register("sound", "|cFF7381ffTaunt|r", [[Interface\Addons\AtrocityMedia\Sounds\Taunt.ogg]])
    LSM:Register("sound", "|cFF7381ffTotem|r", [[Interface\Addons\AtrocityMedia\Sounds\Totem.ogg]])
    LSM:Register("sound", "|cFF7381ffTransition|r", [[Interface\Addons\AtrocityMedia\Sounds\Transition.ogg]])
    LSM:Register("sound", "|cFF7381ffTrap|r", [[Interface\Addons\AtrocityMedia\Sounds\Trap.ogg]])
    LSM:Register("sound", "|cFF7381ffTurn|r", [[Interface\Addons\AtrocityMedia\Sounds\Turn.ogg]])
    LSM:Register("sound", "|cFF7381ffWave|r", [[Interface\Addons\AtrocityMedia\Sounds\Wave.ogg]])
    LSM:Register("sound", "|cFF7381ffWinds|r", [[Interface\Addons\AtrocityMedia\Sounds\Winds.ogg]])
    LSM:Register("sound", "|cFF7381ffYellow|r", [[Interface\Addons\AtrocityMedia\Sounds\Yellow.ogg]])
    LSM:Register("sound", "|cFF7381ffZone|r", [[Interface\Addons\AtrocityMedia\Sounds\Zone.ogg]])
    LSM:Register("sound", "|cFF7381ffKick|r", [[Interface\Addons\AtrocityMedia\Sounds\Kick.ogg]])
    LSM:Register("sound", "|cFF7381ffFrontal|r", [[Interface\Addons\AtrocityMedia\Sounds\Frontal.ogg]])
    -- M+ Sounds --
    LSM:Register("sound", "|cFF7381ffSuccessful|r", [[Interface\Addons\AtrocityMedia\Sounds\Successful.ogg]])
    -- M+ TTS --
LSM:Register("sound","|cfff900ffAbsorb|r", [[Interface\Addons\AtrocityMedia\Sounds\Absorb.ogg]])
LSM:Register("sound","|cfff900ffAbsorbs|r", [[Interface\Addons\AtrocityMedia\Sounds\Absorbs.ogg]])
LSM:Register("sound","|cfff900ffAdd Frontal|r", [[Interface\Addons\AtrocityMedia\Sounds\Add Frontal.ogg]])
LSM:Register("sound","|cfff900ffAdds Buffed|r", [[Interface\Addons\AtrocityMedia\Sounds\Adds Buffed.ogg]])
LSM:Register("sound","|cfff900ffAdds|r", [[Interface\Addons\AtrocityMedia\Sounds\Adds.ogg]])
LSM:Register("sound","|cfff900ffAffix Complete|r", [[Interface\Addons\AtrocityMedia\Sounds\Affix Complete.ogg]])
LSM:Register("sound","|cfff900ffAffix|r", [[Interface\Addons\AtrocityMedia\Sounds\Affix.ogg]])
LSM:Register("sound","|cfff900ffAim Charge|r", [[Interface\Addons\AtrocityMedia\Sounds\Aim Charge.ogg]])
LSM:Register("sound","|cfff900ffAoe And Dance|r", [[Interface\Addons\AtrocityMedia\Sounds\Aoe And Dance.ogg]])
LSM:Register("sound","|cfff900ffAoe|r", [[Interface\Addons\AtrocityMedia\Sounds\Aoe.ogg]])
LSM:Register("sound","|cfff900ffAvoid Tank|r", [[Interface\Addons\AtrocityMedia\Sounds\Avoid Tank.ogg]])
LSM:Register("sound","|cfff900ffAvoid|r", [[Interface\Addons\AtrocityMedia\Sounds\Avoid.ogg]])
LSM:Register("sound","|cfff900ffBait|r", [[Interface\Addons\AtrocityMedia\Sounds\Bait.ogg]])
LSM:Register("sound","|cfff900ffBalls Charging|r", [[Interface\Addons\AtrocityMedia\Sounds\Balls Charging.ogg]])
LSM:Register("sound","|cfff900ffBeam|r", [[Interface\Addons\AtrocityMedia\Sounds\Beam.ogg]])
LSM:Register("sound","|cfff900ffBeams|r", [[Interface\Addons\AtrocityMedia\Sounds\Beams.ogg]])
LSM:Register("sound","|cfff900ffBlade|r", [[Interface\Addons\AtrocityMedia\Sounds\Blade.ogg]])
LSM:Register("sound","|cfff900ffBlades|r", [[Interface\Addons\AtrocityMedia\Sounds\Blades.ogg]])
LSM:Register("sound","|cfff900ffBlast|r", [[Interface\Addons\AtrocityMedia\Sounds\Blast.ogg]])
LSM:Register("sound","|cfff900ffBombs Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Bombs Incoming.ogg]])
LSM:Register("sound","|cfff900ffBombs|r", [[Interface\Addons\AtrocityMedia\Sounds\Bombs.ogg]])
LSM:Register("sound","|cfff900ffBoss Buffed|r", [[Interface\Addons\AtrocityMedia\Sounds\Boss Buffed.ogg]])
LSM:Register("sound","|cfff900ffBoss Position|r", [[Interface\Addons\AtrocityMedia\Sounds\Boss Position.ogg]])
LSM:Register("sound","|cfff900ffBoss Shielded|r", [[Interface\Addons\AtrocityMedia\Sounds\Boss Shielded.ogg]])
LSM:Register("sound","|cfff900ffBox Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Box Incoming.ogg]])
LSM:Register("sound","|cfff900ffBuffing Add|r", [[Interface\Addons\AtrocityMedia\Sounds\Buffing Add.ogg]])
LSM:Register("sound","|cfff900ffCharge|r", [[Interface\Addons\AtrocityMedia\Sounds\Charge.ogg]])
LSM:Register("sound","|cfff900ffCharges Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Charges Incoming.ogg]])
LSM:Register("sound","|cfff900ffCoin Magnet|r", [[Interface\Addons\AtrocityMedia\Sounds\Coin Magnet.ogg]])
LSM:Register("sound","|cfff900ffCoin Pull|r", [[Interface\Addons\AtrocityMedia\Sounds\Coin Pull.ogg]])
LSM:Register("sound","|cfff900ffCurse|r", [[Interface\Addons\AtrocityMedia\Sounds\Curse.ogg]])
LSM:Register("sound","|cfff900ffDance|r", [[Interface\Addons\AtrocityMedia\Sounds\Dance.ogg]])
LSM:Register("sound","|cfff900ffDebuff|r", [[Interface\Addons\AtrocityMedia\Sounds\Debuff.ogg]])
LSM:Register("sound","|cfff900ffDebuffs|r", [[Interface\Addons\AtrocityMedia\Sounds\Debuffs.ogg]])
LSM:Register("sound","|cfff900ffDecurse|r", [[Interface\Addons\AtrocityMedia\Sounds\Decurse.ogg]])
LSM:Register("sound","|cfff900ffDispel Tank|r", [[Interface\Addons\AtrocityMedia\Sounds\Dispel Tank.ogg]])
LSM:Register("sound","|cfff900ffDmg Amp|r", [[Interface\Addons\AtrocityMedia\Sounds\Dmg Amp.ogg]])
LSM:Register("sound","|cfff900ffDodge Together|r", [[Interface\Addons\AtrocityMedia\Sounds\Dodge Together.ogg]])
LSM:Register("sound","|cfff900ffDodge|r", [[Interface\Addons\AtrocityMedia\Sounds\Dodge.ogg]])
LSM:Register("sound","|cfff900ffFear|r", [[Interface\Addons\AtrocityMedia\Sounds\Fear.ogg]])
LSM:Register("sound","|cfff900ffFind Safespot|r", [[Interface\Addons\AtrocityMedia\Sounds\Find Safespot.ogg]])
LSM:Register("sound","|cfff900ffFixate Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Fixate Incoming.ogg]])
LSM:Register("sound","|cfff900ffFixate|r", [[Interface\Addons\AtrocityMedia\Sounds\Fixate.ogg]])
LSM:Register("sound","|cfff900ffFlipper|r", [[Interface\Addons\AtrocityMedia\Sounds\Flipper.ogg]])
LSM:Register("sound","|cfff900ffFrontal|r", [[Interface\Addons\AtrocityMedia\Sounds\Frontal.ogg]])
LSM:Register("sound","|cfff900ffGet Dispelled|r", [[Interface\Addons\AtrocityMedia\Sounds\Get Dispelled.ogg]])
LSM:Register("sound","|cfff900ffHeadlock Stun|r", [[Interface\Addons\AtrocityMedia\Sounds\Headlock Stun.ogg]])
LSM:Register("sound","|cfff900ffHigh Energy|r", [[Interface\Addons\AtrocityMedia\Sounds\High Energy.ogg]])
LSM:Register("sound","|cfff900ffHooks Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Hooks Incoming.ogg]])
LSM:Register("sound","|cfff900ffIntermission Over|r", [[Interface\Addons\AtrocityMedia\Sounds\Intermission Over.ogg]])
LSM:Register("sound","|cfff900ffIntermission|r", [[Interface\Addons\AtrocityMedia\Sounds\Intermission.ogg]])
LSM:Register("sound","|cfff900ffKick|r", [[Interface\Addons\AtrocityMedia\Sounds\Kick.ogg]])
LSM:Register("sound","|cfff900ffKnock|r", [[Interface\Addons\AtrocityMedia\Sounds\Knock.ogg]])
LSM:Register("sound","|cfff900ffKnockback|r", [[Interface\Addons\AtrocityMedia\Sounds\Knockback.ogg]])
LSM:Register("sound","|cfff900ffLeap|r", [[Interface\Addons\AtrocityMedia\Sounds\Leap.ogg]])
LSM:Register("sound","|cfff900ffLinked|r", [[Interface\Addons\AtrocityMedia\Sounds\Linked.ogg]])
LSM:Register("sound","|cfff900ffLinks Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Links Incoming.ogg]])
LSM:Register("sound","|cfff900ffLook Away|r", [[Interface\Addons\AtrocityMedia\Sounds\Look Away.ogg]])
LSM:Register("sound","|cfff900ffMaul|r", [[Interface\Addons\AtrocityMedia\Sounds\Maul.ogg]])
LSM:Register("sound","|cfff900ffMax Dmg Amp|r", [[Interface\Addons\AtrocityMedia\Sounds\Max Dmg Amp.ogg]])
LSM:Register("sound","|cfff900ffMines|r", [[Interface\Addons\AtrocityMedia\Sounds\Mines.ogg]])
LSM:Register("sound","|cfff900ffMiniboss Buffed|r", [[Interface\Addons\AtrocityMedia\Sounds\Miniboss Buffed.ogg]])
LSM:Register("sound","|cfff900ffMissile|r", [[Interface\Addons\AtrocityMedia\Sounds\Missile.ogg]])
LSM:Register("sound","|cfff900ffMove|r", [[Interface\Addons\AtrocityMedia\Sounds\Move.ogg]])
LSM:Register("sound","|cfff900ffNew Add|r", [[Interface\Addons\AtrocityMedia\Sounds\New Add.ogg]])
LSM:Register("sound","|cfff900ffOrb|r", [[Interface\Addons\AtrocityMedia\Sounds\Orb.ogg]])
LSM:Register("sound","|cfff900ffOrbs|r", [[Interface\Addons\AtrocityMedia\Sounds\Orbs.ogg]])
LSM:Register("sound","|cfff900ffPhasing|r", [[Interface\Addons\AtrocityMedia\Sounds\Phasing.ogg]])
LSM:Register("sound","|cfff900ffPickaxe|r", [[Interface\Addons\AtrocityMedia\Sounds\Pickaxe.ogg]])
LSM:Register("sound","|cfff900ffPools|r", [[Interface\Addons\AtrocityMedia\Sounds\Pools.ogg]])
LSM:Register("sound","|cfff900ffPre-Move Inc|r", [[Interface\Addons\AtrocityMedia\Sounds\Pre-Move Inc.ogg]])
LSM:Register("sound","|cfff900ffPre-Move|r", [[Interface\Addons\AtrocityMedia\Sounds\Pre-Move.ogg]])
LSM:Register("sound","|cfff900ffPre-Spread|r", [[Interface\Addons\AtrocityMedia\Sounds\Pre-Spread.ogg]])
LSM:Register("sound","|cfff900ffPull|r", [[Interface\Addons\AtrocityMedia\Sounds\Pull.ogg]])
LSM:Register("sound","|cfff900ffPvP Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\PvP Incoming.ogg]])
LSM:Register("sound","|cfff900ffRemove Plating|r", [[Interface\Addons\AtrocityMedia\Sounds\Remove Plating.ogg]])
LSM:Register("sound","|cfff900ffRicochet|r", [[Interface\Addons\AtrocityMedia\Sounds\Ricochet.ogg]])
LSM:Register("sound","|cfff900ffRun out|r", [[Interface\Addons\AtrocityMedia\Sounds\Run out.ogg]])
LSM:Register("sound","|cfff900ffSawblade Incoming|r", [[Interface\Addons\AtrocityMedia\Sounds\Sawblade Incoming.ogg]])
LSM:Register("sound","|cfff900ffShield|r", [[Interface\Addons\AtrocityMedia\Sounds\Shield.ogg]])
LSM:Register("sound","|cfff900ffSmash|r", [[Interface\Addons\AtrocityMedia\Sounds\Smash.ogg]])
LSM:Register("sound","|cfff900ffSmashing|r", [[Interface\Addons\AtrocityMedia\Sounds\Smashing.ogg]])
LSM:Register("sound","|cfff900ffSoak|r", [[Interface\Addons\AtrocityMedia\Sounds\Soak.ogg]])
LSM:Register("sound","|cfff900ffSoaks|r", [[Interface\Addons\AtrocityMedia\Sounds\Soaks.ogg]])
LSM:Register("sound","|cfff900ffSparks|r", [[Interface\Addons\AtrocityMedia\Sounds\Sparks.ogg]])
LSM:Register("sound","|cfff900ffSpread|r", [[Interface\Addons\AtrocityMedia\Sounds\Spread.ogg]])
LSM:Register("sound","|cfff900ffStack|r", [[Interface\Addons\AtrocityMedia\Sounds\Stack.ogg]])
LSM:Register("sound","|cfff900ffStatues|r", [[Interface\Addons\AtrocityMedia\Sounds\Statues.ogg]])
LSM:Register("sound","|cfff900ffStop Casting|r", [[Interface\Addons\AtrocityMedia\Sounds\Stop Casting.ogg]])
LSM:Register("sound","|cfff900ffStun|r", [[Interface\Addons\AtrocityMedia\Sounds\Stun.ogg]])
LSM:Register("sound","|cfff900ffStunned|r", [[Interface\Addons\AtrocityMedia\Sounds\Stunned.ogg]])
LSM:Register("sound","|cfff900ffSwap|r", [[Interface\Addons\AtrocityMedia\Sounds\Swap.ogg]])
LSM:Register("sound","|cfff900ffSwitch|r", [[Interface\Addons\AtrocityMedia\Sounds\Switch.ogg]])
LSM:Register("sound","|cfff900ffTank-Frontal|r", [[Interface\Addons\AtrocityMedia\Sounds\Tank-Frontal.ogg]])
LSM:Register("sound","|cfff900ffTornadoes|r", [[Interface\Addons\AtrocityMedia\Sounds\Tornadoes.ogg]])
LSM:Register("sound","|cfff900ffTotem|r", [[Interface\Addons\AtrocityMedia\Sounds\Totem.ogg]])
LSM:Register("sound","|cfff900ffTransition|r", [[Interface\Addons\AtrocityMedia\Sounds\Transition.ogg]])
LSM:Register("sound","|cfff900ffUppercut|r", [[Interface\Addons\AtrocityMedia\Sounds\Uppercut.ogg]])
    --Fonts
    LSM:Register("font","Expressway", [[Interface\Addons\AtrocityMedia\Fonts\Expressway.TTF]])
end

function Addon:RegisterElvUITags()
    if not ElvUI then
      return
    end
  
    local E = unpack(ElvUI)
  
    for namelength = 1, 20 do
      local nametag = format('name:length%d', namelength)
      E:AddTag(nametag, 'UNIT_NAME_UPDATE INSTANCE_ENCOUNTER_ENGAGE_UNIT', function(unit)
        local name = UnitName(unit)
        if name then
          return E:ShortenString(name, namelength)
        end
      end)
      E:AddTagInfo(nametag, "AtrocityMedia", format("Unit name shortened to length %d.", namelength))
    end
  
    if not (ElvUF and ElvUF.Tags and ElvUF.Tags.Methods["nickname"]) then
      for nicknamelength = 1, 20 do
        local nicknametag = format('nickname-len%d', nicknamelength)
        E:AddTag(nicknametag, 'UNIT_NAME_UPDATE INSTANCE_ENCOUNTER_ENGAGE_UNIT', function(unit)
          local name = UnitName(unit)
          if name then
            return E:ShortenString(name, nicknamelength)
          end
        end)
        E:AddTagInfo(nicknametag, "AtrocityMedia", format("Unit name shortened to length %d.", nicknamelength))
      end
    end
  end

function Addon:Init()
    self:RegisterLSM()

    self.frame = CreateFrame("Frame", "AtrocityMediaFrame")
    self.frame:RegisterEvent("PLAYER_LOGIN")
    self.frame:SetScript("OnEvent", function(self, event, ...)
        local handler = Addon[event]
        if handler then
            handler(Addon, ...)
        end
    end)
end

function Addon:PLAYER_LOGIN()
    self:RegisterElvUITags()
end

Addon:Init()
