local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Rogue-Assassination','Rogue-Subtlety','Druid-Restoration','Druid-Balance','Unknown-Unknown','Evoker-Devastation','Evoker-Augmentation','Mage-Arcane','Monk-Windwalker','Priest-Holy','Shaman-Restoration','Priest-Shadow','Paladin-Retribution','Hunter-BeastMastery','Warlock-Affliction','Warlock-Destruction','Warlock-Demonology','Monk-Brewmaster','Hunter-Marksmanship','DeathKnight-Frost','DeathKnight-Blood','Warrior-Protection','Shaman-Elemental','Paladin-Holy','Druid-Feral','Priest-Discipline','Evoker-Preservation','Rogue-Outlaw','DemonHunter-Havoc','Druid-Guardian','Warrior-Fury','Warrior-Arms','Paladin-Protection','DemonHunter-Vengeance','Mage-Frost','Mage-Fire','DeathKnight-Unholy','Shaman-Enhancement','Monk-Mistweaver',}; local provider = {region='EU',realm='Shadowsong',name='EU',type='weekly',zone=44,date='2025-09-22',data={Ad='Adikia:BAAALAAECgIIAgAAAA==.',Ae='Aelik:BAAALAADCggICQAAAA==.Aelynthi:BAACLAAFFIETAAMBAAYI7BhsAAA8AgABAAYI7BhsAAA8AgACAAIIOwdoDwCEAAAsAAQKgSAAAwEACAiMInsKANcCAAEACAjOIXsKANcCAAIABAgfGugkADcBAAAA.Aeoneye:BAAALAAECggIEgAAAA==.Aeowén:BAAALAADCggICwAAAA==.Aevorn:BAABLAAECoEiAAMDAAgIHAsySwBzAQADAAgIHAsySwBzAQAEAAgIyQk1QgBxAQAAAA==.Aexxo:BAAALAAECgcICQAAAA==.',Ag='Agate:BAAALAAECgMIAwAAAA==.Agility:BAAALAAECgYIDgAAAA==.',Ai='Aiilon:BAAALAAECggICAAAAA==.',Aj='Ajinpal:BAAALAADCggICAAAAA==.',Ak='Akasukí:BAAALAADCgEIAQABLAAECgYIDAAFAAAAAA==.Akyone:BAAALAADCgYIBgAAAA==.Akzydeath:BAAALAAECggICAAAAA==.',Al='Aldaniti:BAAALAAECgMIBQAAAA==.Alegosa:BAACLAAFFIEEAAIGAAII6he8EACdAAAGAAII6he8EACdAAAsAAQKgSgAAwYACAj7HVgPAKcCAAYACAj7HVgPAKcCAAcABghWFC4JAKABAAAA.Allanbulic:BAAALAAECgYIDAAAAA==.Alvirae:BAABLAAECoEoAAIEAAgIZB9MDQDlAgAEAAgIZB9MDQDlAgAAAA==.Alysium:BAAALAADCgIIAgAAAA==.',Am='Amerisa:BAAALAAECgQICAAAAA==.Amicalucina:BAAALAAECgIIAgAAAA==.Ammiana:BAAALAAECgYIDAAAAQ==.',An='Anaesthetise:BAAALAAECgMIAwABLAAECgcIEAAFAAAAAA==.Angelictuna:BAAALAADCgQIBgABLAAECgYICgAFAAAAAA==.Anikara:BAAALAADCgcIDgAAAA==.Anisado:BAAALAAECgcIBwABLAAECggIJAAIADwcAA==.Anisleaf:BAAALAAECgQIBAABLAAECggIJAAIADwcAA==.Aniz:BAABLAAECoEgAAIJAAgINBy/DQCZAgAJAAgINBy/DQCZAgAAAA==.',Aq='Aquilegia:BAAALAAECgMIBQAAAA==.',Ar='Arcaneislol:BAAALAAECgUIBQAAAA==.Aredheal:BAABLAAECoEaAAIKAAcIPSJgFACoAgAKAAcIPSJgFACoAgAAAA==.Arrowmark:BAAALAAECgIIAwAAAA==.Artae:BAAALAADCgUICQAAAA==.Artaelion:BAABLAAECoEYAAILAAcIDhyvLgAtAgALAAcIDhyvLgAtAgAAAA==.Arthiel:BAAALAAECgEIAQAAAA==.Arúgál:BAAALAAECgQICgAAAA==.',As='Astaraell:BAAALAADCggIFAABLAAFFAIIBQAMAOUPAA==.Astrakhan:BAAALAAECgIIAgAAAA==.Asuyomi:BAAALAAECgYIBgAAAA==.',At='Atomiinus:BAAALAADCggICQABLAAECgUICQAFAAAAAA==.',Au='Au:BAAALAAECgcICAABLAAECggIGAAMAOsiAA==.Aurium:BAAALAAECgQIBAABLAAECgcIFAAJAD0dAA==.',Av='Avesk:BAABLAAECoEiAAINAAgI7x8hIADMAgANAAgI7x8hIADMAgAAAA==.Aviael:BAABLAAECoEfAAIOAAgI+yDJHwCfAgAOAAgI+yDJHwCfAgABLAAFFAIIAgAFAAAAAA==.',Aw='Awakes:BAAALAAECgYIBgAAAA==.',Ay='Ayuascha:BAAALAADCggICAAAAA==.',Az='Azur:BAABLAAECoEqAAIPAAgIsSKDAQAsAwAPAAgIsSKDAQAsAwAAAA==.',['Aí']='Aíthína:BAABLAAECoEeAAIOAAcI7xwcNQA9AgAOAAcI7xwcNQA9AgAAAA==.',Ba='Badshot:BAAALAAECgYIDAAAAA==.Bagius:BAAALAADCgcIGAAAAA==.Baldraek:BAAALAAECgEIAQAAAA==.Balione:BAAALAAECggIDQAAAA==.Bastalion:BAAALAAECgcIDQAAAA==.',Be='Bearie:BAAALAADCgEIAQABLAAECgYIDgAFAAAAAA==.Bearmittens:BAAALAAECgQIBwAAAA==.Beatnik:BAAALAADCgcIBwAAAA==.Becquin:BAAALAAECgIIAgAAAA==.Beedrill:BAAALAADCggIGAABLAADCggIGgAFAAAAAA==.Beefie:BAAALAAECggICAAAAA==.Beliall:BAABLAAECoEiAAMQAAgIrAy3UgC+AQAQAAgIYQy3UgC+AQARAAYI5wbMRwAnAQAAAA==.Bellowmane:BAAALAAECgQICAAAAA==.Bellowsham:BAAALAADCgEIAQABLAAECgQICAAFAAAAAA==.Bentoxvi:BAABLAAECoEhAAIKAAgIcR70EQC8AgAKAAgIcR70EQC8AgAAAA==.',Bi='Bigdiel:BAABLAAECoEUAAISAAYIHRAOJQAoAQASAAYIHRAOJQAoAQAAAA==.Bigmonkworth:BAABLAAECoEUAAMSAAgI5BotDgBDAgASAAYIRiEtDgBDAgAJAAgIrwrdJgCRAQAAAA==.Bismarck:BAAALAAECgYIEgAAAA==.',Bl='Blackmarsh:BAAALAAFFAIIAgAAAA==.Blastinc:BAAALAAECggIEQAAAA==.Bling:BAAALAADCggICAAAAA==.',Bo='Boyar:BAABLAAECoEZAAITAAcIkB2+JAAqAgATAAcIkB2+JAAqAgAAAA==.Boye:BAAALAADCgQIBAAAAA==.',Br='Bram:BAAALAAECgcIDwABLAAECggIIwAUALoaAA==.Branchy:BAABLAAECoEnAAIDAAgIoCNbBAAzAwADAAgIoCNbBAAzAwAAAA==.Brent:BAAALAAECgIIBAAAAA==.Brioche:BAABLAAECoEUAAMJAAcIPR2LEwBMAgAJAAcIPR2LEwBMAgASAAEI7RMYPgA6AAAAAA==.Bronix:BAAALAADCgYICwAAAA==.',Bu='Bubbsielocks:BAAALAADCgYIBgAAAA==.Bubitz:BAABLAAECoEqAAMTAAgIvRqrJgAeAgAOAAgIeRZkPQAeAgATAAgIjxerJgAeAgAAAA==.Buffunholy:BAAALAAECgEIAQAAAA==.Bulldan:BAAALAAECgUIBQAAAA==.Bumlebien:BAAALAAECgYICQAAAA==.',Ca='Caevornai:BAAALAAECggIDwAAAA==.Calipse:BAABLAAECoEWAAMQAAgIpBoFLgBUAgAQAAgIpBoFLgBUAgARAAQIAhYGUAABAQAAAA==.Camooflage:BAAALAAECgcIBwAAAA==.Candifloss:BAAALAAECgcICAAAAA==.Cathela:BAAALAAECgQIBgAAAA==.Caélia:BAAALAAECgIIAgAAAA==.',Ce='Centavo:BAAALAAECgUICQAAAA==.',Ch='Chayse:BAAALAADCgMIAwAAAA==.Cheath:BAABLAAFFIEIAAIVAAMIwBY5BQD3AAAVAAMIwBY5BQD3AAAAAA==.Chiaka:BAAALAADCggIDQAAAA==.Chilli:BAAALAADCgcIBwAAAA==.Chitose:BAAALAAECgIIBAAAAA==.Christymack:BAAALAADCgQIBAAAAA==.Chulainn:BAABLAAECoEUAAIDAAYIKRe5RQCIAQADAAYIKRe5RQCIAQAAAA==.',Ci='Citrine:BAAALAAFFAEIAQAAAA==.',Ck='Ckoffè:BAAALAADCgcIBwAAAA==.',Cl='Cleopatra:BAAALAADCggIEAABLAAECggILQATACkgAA==.',Co='Coffè:BAACLAAFFIEFAAIOAAII5B2tGgCtAAAOAAII5B2tGgCtAAAsAAQKgSoAAg4ACAiWJDQIADoDAA4ACAiWJDQIADoDAAAA.Correctus:BAAALAADCgcIBwAAAA==.',Cr='Creatorr:BAABLAAECoEbAAIWAAgIVRybFQBRAgAWAAgIVRybFQBRAgABLAAFFAMICAAVAMAWAA==.Cromach:BAAALAADCggICAAAAA==.Crona:BAAALAAECgYICQAAAA==.Cryxor:BAAALAAECgYIBgABLAAECgYIFQAUAHcfAA==.',Da='Daamed:BAAALAAECggICAAAAA==.Daglop:BAAALAAECgEIAQAAAA==.Daktilo:BAAALAADCggICAAAAA==.Dalyana:BAAALAADCgUIBQAAAA==.Danielle:BAABLAAECoEXAAIQAAYI8A50cABmAQAQAAYI8A50cABmAQABLAAECggIHgAUAG4jAA==.Daranthian:BAAALAADCggICAAAAA==.Darkmender:BAABLAAECoEfAAIRAAgIghefEQBPAgARAAgIghefEQBPAgAAAA==.Darkshard:BAAALAAECgMIBQAAAA==.Darksky:BAAALAAECgIIAgAAAA==.Darkys:BAAALAAECgIIAwAAAA==.Darthanian:BAAALAADCggICAAAAA==.Darugga:BAAALAAECgcICAAAAA==.Dasshøl:BAAALAADCggICAABLAAECgYICwAFAAAAAA==.Dav:BAAALAAECgYIDAABLAAECggIGwAXAI8lAA==.',De='Deathberry:BAAALAAECgYIDgAAAA==.Deluriand:BAAALAAECgYIBgABLAAECggIFwAIAPgYAA==.Demoned:BAAALAADCgUIBQAAAA==.Demonella:BAAALAADCgMIAwAAAA==.Demonicà:BAAALAADCgMIAwAAAA==.Demoserval:BAAALAAECgIIAgAAAA==.Dens:BAAALAADCgIIAgAAAA==.Deobelix:BAAALAAECgMIBQAAAA==.Derkit:BAAALAAECgUIBQABLAAECgYIDgAFAAAAAA==.Destorm:BAAALAADCgcIBwAAAA==.Destructo:BAAALAADCggICAAAAA==.Destyke:BAAALAAECgYIBgAAAA==.',Di='Diamondheart:BAAALAAECgcIDgAAAA==.Dionysia:BAAALAADCggIDwAAAA==.',Dj='Djennaa:BAAALAAECgcIEgAAAA==.',Do='Dooiekoe:BAAALAAECgQIBAAAAA==.Dora:BAAALAAECgcIEAAAAA==.',Dr='Dracalid:BAAALAAECgYIEgABLAAECggIJwAMAGkjAA==.Dracsussy:BAAALAADCggIGwAAAA==.Dractoby:BAAALAAECgQIBAAAAA==.Draecariss:BAAALAADCgcIBwAAAA==.Drakot:BAABLAAECoEVAAIUAAYIdx+ubgDdAQAUAAYIdx+ubgDdAQAAAA==.Dreamàh:BAAALAAECgEIAQAAAA==.Driptide:BAAALAADCgQIBAAAAA==.Droneth:BAAALAADCggIEwAAAA==.Drool:BAAALAAECggICAAAAA==.',Du='Duckula:BAAALAADCgQIBAAAAA==.',Dy='Dyarte:BAABLAAECoEVAAIYAAgI7QoKLgCBAQAYAAgI7QoKLgCBAQAAAA==.Dyendra:BAAALAADCggIEQAAAA==.',Dz='Dzzigels:BAAALAAECggICAAAAA==.',['Dä']='Däni:BAAALAADCggIEAAAAA==.',Eb='Ebit:BAABLAAECoEUAAIZAAgI3xTYEgD5AQAZAAgI3xTYEgD5AQAAAA==.Eblino:BAAALAAECgIIAgAAAA==.',Ed='Edgydragon:BAAALAAECgYIBgAAAA==.Edgypriest:BAABLAAECoEeAAMKAAgIzBCWOQDKAQAKAAgIzBCWOQDKAQAMAAEIfwYSjgAjAAAAAA==.',Ee='Eef:BAACLAAFFIEGAAMKAAIIUQ+jIQCSAAAKAAIIUQ+jIQCSAAAMAAEILQVEIwA6AAAsAAQKgSEABAwACAjUEps8AKQBAAwABwinEJs8AKQBABoABwiLC/IRAEwBAAoABQhIC+dwAPsAAAAA.Eefoker:BAAALAAECgUIDQABLAAFFAIIBgAKAFEPAA==.',Ef='Efie:BAABLAAECoEZAAIDAAgIABDMTQBpAQADAAgIABDMTQBpAQAAAA==.',El='Elcandy:BAAALAAECgYIEQAAAA==.Eldritchcat:BAAALAAECgcIBwAAAA==.Elementuss:BAAALAAECggIEwAAAA==.Elléndruil:BAAALAAECggIEAAAAA==.Elnightshade:BAAALAAECgYIBgAAAA==.Eloen:BAABLAAECoEUAAMGAAYIagm2PAAqAQAGAAYIagm2PAAqAQAbAAMIyAQQMQBnAAAAAA==.Eluidess:BAAALAADCgcIBwAAAA==.Elément:BAAALAADCgQIBAABLAAECggIIQATALwfAA==.',Es='Esmeraud:BAAALAAECgYIDQAAAQ==.',Et='Ethaan:BAAALAAECgYIDAAAAA==.',Ev='Evanesce:BAAALAAECgQIBgAAAA==.Evkr:BAAALAADCggIDQAAAA==.',Ex='Exitium:BAAALAAECgQICgAAAA==.Exonym:BAABLAAECoEnAAILAAgI4hTpOwD9AQALAAgI4hTpOwD9AQAAAA==.Ext:BAAALAAECgIIBgAAAA==.Exterminans:BAABLAAECoEfAAIOAAgIESFmJwB3AgAOAAgIESFmJwB3AgAAAA==.',Fa='Fakelock:BAAALAAECgcICwAAAA==.Fanný:BAABLAAECoEtAAITAAgIKSC2DQDnAgATAAgIKSC2DQDnAgAAAA==.Fategw:BAAALAADCgcIBwAAAA==.',Fe='Fee:BAAALAAECgMIAwABLAAFFAIIBgAKAFEPAA==.Felseagal:BAAALAAECgMIAwABLAAFFAYIDwATAMYjAA==.Fenchurch:BAABLAAECoETAAIcAAYIqxviBwD0AQAcAAYIqxviBwD0AQAAAA==.Feyrra:BAAALAAECgMIBAAAAA==.',Fj='Fjas:BAAALAADCgcIBwAAAA==.Fjekkik:BAAALAAECgEIAQABLAAFFAIIBgAYACkUAA==.',Fl='Flamé:BAAALAAFFAEIAgAAAA==.Flokii:BAAALAAECgYICQAAAA==.Floorpov:BAABLAAECoEnAAIdAAgIhxyGJwCXAgAdAAgIhxyGJwCXAgAAAA==.',Fo='Fomeen:BAACLAAFFIEFAAIeAAIIEByaAgCnAAAeAAIIEByaAgCnAAAsAAQKgSgAAh4ACAg6IAEDAO0CAB4ACAg6IAEDAO0CAAAA.Fomevoker:BAABLAAECoEeAAMHAAcIQR7bAwBwAgAHAAcIQR7bAwBwAgAGAAII/BluTgCGAAABLAAFFAIIBQAeABAcAA==.Formaggio:BAAALAADCgEIAQAAAA==.Foxish:BAAALAAECgcIDwAAAA==.',Fr='Frankard:BAAALAADCggIDgABLAAECgYIDQAFAAAAAQ==.Frankkie:BAAALAADCgQIBAABLAAECgYIDQAFAAAAAQ==.Frozenella:BAAALAAECgMIBQAAAA==.Frugtplukker:BAAALAAECgYICQAAAA==.Frygaa:BAABLAAECoEWAAINAAcI0wb3tgBMAQANAAcI0wb3tgBMAQABLAAECgcIGAATACUkAA==.',Fu='Fujikawa:BAAALAAECgIIAgAAAA==.',['Fú']='Fúry:BAAALAAECgIIAwABLAAECggIIQATALwfAA==.',Ga='Gameover:BAAALAADCgcIDAAAAA==.Ganar:BAAALAAECggICgABLAAFFAMIBwAfANsZAA==.Gandrayda:BAABLAAECoEZAAIYAAgIWhNZGAAaAgAYAAgIWhNZGAAaAgAAAA==.',Ge='Gentildonna:BAAALAAECgIIAgABLAAECgYIDwAFAAAAAA==.Geogar:BAAALAAECgYIBgABLAAECgYICgAFAAAAAA==.Geolun:BAAALAAECgYICgAAAA==.',Gh='Ghøstøf:BAABLAAECoEfAAQWAAgILRF3MACFAQAWAAgILRF3MACFAQAgAAYI8QnRGQAkAQAfAAQIEwXLqACYAAAAAA==.',Gi='Girlkisser:BAAALAAECgEIAQAAAA==.',Gn='Gnomié:BAABLAAECoEXAAIIAAgI+BgHMQBjAgAIAAgI+BgHMQBjAgAAAA==.',Go='Goldenlight:BAAALAAECgIIAgAAAA==.Gonkius:BAAALAADCgQIBAAAAA==.',Gr='Graume:BAAALAAECgQICQAAAA==.Grexsa:BAAALAADCgQIBAAAAA==.Greyworg:BAAALAAECgQICQAAAA==.Grimaldor:BAAALAADCgYIFwAAAA==.Grimdark:BAAALAAECgcIDgAAAA==.Grimreapers:BAAALAAECgYICQAAAA==.Gríndan:BAABLAAECoEfAAINAAgIkxB9ZgDnAQANAAgIkxB9ZgDnAQAAAA==.',Gu='Guinnevere:BAAALAAECgMIAwAAAA==.Gumbo:BAAALAAECgMIAwAAAA==.',Gw='Gwarchodwr:BAAALAADCgcIBwABLAAECggIHQAMAPMOAA==.Gwýn:BAABLAAECoEZAAIIAAYIkSEEOABFAgAIAAYIkSEEOABFAgAAAA==.',Ha='Halucyna:BAAALAAECgUIBQAAAA==.',He='Healtralala:BAAALAADCgMIAwABLAAFFAIIBgAYACkUAA==.Healyourself:BAAALAAECgUICAAAAA==.Hejtsphere:BAABLAAECoEdAAIQAAcIQRbERQDsAQAQAAcIQRbERQDsAQAAAA==.Hematite:BAAALAADCgYIDAAAAA==.Henna:BAABLAAECoEUAAIOAAYI/hwHWwDHAQAOAAYI/hwHWwDHAQAAAA==.',Hi='Higgz:BAABLAAECoEUAAIhAAYIDxPfKgBgAQAhAAYIDxPfKgBgAQAAAA==.',Ho='Hodini:BAAALAADCggICAABLAAECgcIHQAiAAYlAA==.Hokath:BAABLAAECoEaAAQjAAcI9xrmHQABAgAjAAYI2B3mHQABAgAkAAUIuBAwCwBNAQAIAAMIpwWTwAB/AAAAAA==.Holey:BAAALAADCgEIAQAAAA==.Holylíght:BAAALAAECgUIBQAAAA==.Homer:BAAALAAECgIIAgAAAA==.',Hu='Hunira:BAAALAADCggICAAAAA==.Hurtzogud:BAAALAAECgYIDAAAAA==.',Hy='Hymne:BAAALAAECgQICgAAAA==.',['Hö']='Hörny:BAAALAADCgIIAgAAAA==.',Il='Ilthalas:BAAALAADCggIEwAAAA==.',Im='Imsoocunning:BAABLAAFFIEIAAIEAAMICQ2UCwDVAAAEAAMICQ2UCwDVAAAAAA==.Imsooscaley:BAAALAADCggIDAAAAA==.Imsootwisted:BAAALAADCgQIBAABLAAFFAMICAAEAAkNAA==.Imtoohot:BAACLAAFFIEHAAIDAAIIkCJgDwDIAAADAAIIkCJgDwDIAAAsAAQKgSkAAgMACAg9JMoDADsDAAMACAg9JMoDADsDAAAA.',In='Inkotron:BAABLAAECoEWAAMZAAcIpwaDJQAqAQAZAAcIJgaDJQAqAQAeAAQI3gXIIQCaAAAAAA==.',Is='Isane:BAAALAADCggICAAAAA==.Isilmë:BAABLAAECoEiAAIeAAgIbx+AAwDWAgAeAAgIbx+AAwDWAgAAAA==.Islandstone:BAAALAAECgYICwAAAA==.',It='Itea:BAAALAADCggIEwAAAA==.',Iv='Ivoxe:BAAALAADCggIFQAAAA==.',Iz='Izere:BAAALAADCggIDgAAAA==.',Ja='Jaqenn:BAAALAAECgYICQABLAAECgYIDgAFAAAAAA==.Jasdeepti:BAAALAAECgEIAgAAAA==.Jasmoon:BAAALAAECgYICgAAAA==.Jathbean:BAAALAAECgMIBQAAAA==.',Je='Jedhunter:BAAALAAECgMIBwAAAA==.Jenni:BAAALAADCggICgAAAA==.Jerrod:BAAALAADCggICAAAAA==.Jezpadoo:BAAALAADCggICAAAAA==.',Jj='Jjake:BAAALAAECgMIAwABLAAECgYIDgAFAAAAAA==.',Jo='Joyquils:BAAALAADCggIEAAAAA==.',Jt='Jtod:BAAALAADCgEIAQAAAA==.',Ka='Kaira:BAAALAAECgEIAQAAAA==.Kaistra:BAAALAADCggICQAAAA==.Kalnesh:BAAALAADCgUIBQAAAA==.Kamakrazee:BAAALAADCgcICQAAAA==.Kaos:BAAALAAECgYIBgAAAA==.Karboz:BAAALAADCggIFgAAAA==.Karny:BAAALAADCggICAAAAA==.Karog:BAAALAADCgcIAQAAAA==.Karza:BAAALAADCgcIEAAAAA==.Katayas:BAAALAAECggIDgAAAA==.Kazaria:BAABLAAECoEfAAIfAAcIuQTZiQAPAQAfAAcIuQTZiQAPAQAAAA==.Kazgaroth:BAAALAADCgcIBwAAAA==.Kazmilurshul:BAABLAAECoEUAAIQAAYIeAkjgwA1AQAQAAYIeAkjgwA1AQAAAA==.',Ke='Keflá:BAAALAAECgMIBwAAAA==.Keirasky:BAAALAAECgMIBQAAAA==.Kekimir:BAABLAAECoEaAAIOAAYINxtkXQDBAQAOAAYINxtkXQDBAQAAAA==.Kelestra:BAAALAADCgIIAgAAAA==.Kendwa:BAAALAADCgcIDwAAAA==.Ketsuri:BAAALAAECgMIAwAAAA==.',Kh='Khatara:BAAALAAECgYICgAAAA==.',Ki='Killshot:BAABLAAECoEYAAMTAAcIJxltLQD1AQATAAcIUBhtLQD1AQAOAAQIoRDcxgDRAAAAAA==.Kilzzor:BAABLAAECoEYAAIfAAgIziMxCgA4AwAfAAgIziMxCgA4AwAAAA==.Kimowisdk:BAAALAADCgYIBgAAAA==.',Kl='Klaster:BAAALAAECgMIBwAAAA==.Klein:BAAALAAECgYIEAAAAA==.Kleinmage:BAAALAADCggICAABLAAECggIFwAXAMohAA==.',Ko='Kortväxt:BAAALAAECgYICQAAAA==.Koshu:BAABLAAECoEoAAMEAAgIgQxSOQCbAQAEAAgIgQxSOQCbAQADAAYI4wMuiAC1AAAAAA==.Kovelok:BAABLAAECoEXAAIMAAcI1RkkKwADAgAMAAcI1RkkKwADAgAAAA==.',Kr='Kraky:BAABLAAECoEgAAMJAAcIQh/xDwB7AgAJAAcIQh/xDwB7AgASAAUItBDuJwANAQAAAA==.Kraumdekay:BAABLAAECoEpAAMUAAgIjCSSCQBEAwAUAAgIQySSCQBEAwAlAAMISCSwMQAaAQAAAA==.Kreetol:BAABLAAECoEhAAIEAAgIPiKqEgCqAgAEAAgIPiKqEgCqAgAAAA==.Krizulgrimm:BAABLAAECoElAAIiAAcIBR9YDQBWAgAiAAcIBR9YDQBWAgABLAAECggIHwANAJMQAA==.Krriz:BAAALAAECgcIEAABLAAECggIHwANAJMQAA==.Krtol:BAAALAAECgYIDAAAAA==.Krullet:BAABLAAECoEbAAIYAAgIARcFFQA5AgAYAAgIARcFFQA5AgAAAA==.',Ky='Kyomag:BAAALAAECgYIBQAAAA==.Kyoshi:BAAALAAECgYIBgAAAA==.',La='Lantex:BAACLAAFFIEFAAIVAAIIkgz1CwB6AAAVAAIIkgz1CwB6AAAsAAQKgRwAAhUACAiZFg8UANABABUACAiZFg8UANABAAAA.Lantexbrew:BAAALAAECgcIBwABLAAFFAIIBQAVAJIMAA==.Lantexdr:BAAALAAECgcIBwABLAAFFAIIBQAVAJIMAA==.Lawrence:BAAALAAECgIIAgAAAA==.Laz:BAABLAAECoErAAIlAAgIziHvBQDqAgAlAAgIziHvBQDqAgAAAA==.',Le='Lea:BAAALAAECgQIBQABLAAECgYICAAFAAAAAA==.Lech:BAABLAAECoEUAAIcAAcINwjzDQBWAQAcAAcINwjzDQBWAQAAAA==.Lethora:BAACLAAFFIEFAAIhAAIIYBMBDQCFAAAhAAIIYBMBDQCFAAAsAAQKgSoAAiEACAjJIQQFABQDACEACAjJIQQFABQDAAAA.Letsbeatit:BAAALAADCgcIBwAAAA==.Leuka:BAABLAAECoEZAAMKAAcIQRElRACbAQAKAAcIQRElRACbAQAMAAYIqwyeUABHAQAAAA==.Levander:BAAALAAECgIIAgAAAA==.Levantah:BAAALAADCgcICgAAAA==.Lexà:BAAALAAECgUIBgABLAAECgcIDAAFAAAAAA==.',Li='Lightjumper:BAABLAAECoEdAAIXAAgIixdoKABHAgAXAAgIixdoKABHAgAAAA==.Linzy:BAAALAADCggICAAAAA==.Liquidsnake:BAAALAADCggICAAAAA==.Litencognac:BAAALAAECgQIBAAAAA==.Littlewolf:BAAALAADCgQIBAAAAA==.',Lo='Lolabug:BAAALAADCggICAAAAA==.Lomb:BAAALAAECgEIAQAAAA==.Lortto:BAAALAAECgYIEAAAAA==.Lotharlight:BAAALAADCggIDQAAAA==.',Lu='Lucíd:BAAALAADCggICAAAAA==.Lukastrasz:BAACLAAFFIEFAAIbAAIIcweuDwCJAAAbAAIIcweuDwCJAAAsAAQKgScABBsACAg1FVMNACQCABsACAg1FVMNACQCAAcAAQiZEpkWACoAAAYAAQiWB6FcACgAAAAA.Luresa:BAABLAAECoEYAAMXAAcIPSG/GQCqAgAXAAcIPSG/GQCqAgALAAIIHhpj2gCHAAAAAA==.Lutherlight:BAAALAADCggIIgAAAA==.Luxie:BAAALAAECgIIAgABLAAECgcIGwAOAOQaAA==.',Ly='Lyxet:BAAALAAECgYIDQAAAA==.',['Lí']='Líght:BAAALAAECgYIDwABLAAECggIIQATALwfAA==.',Ma='Magnusson:BAAALAAECgIIAgAAAA==.Maid:BAAALAAECggICAAAAA==.Makariorc:BAACLAAFFIEFAAIXAAIIQAa5IwCCAAAXAAIIQAa5IwCCAAAsAAQKgSkAAhcACAgdGaUgAHcCABcACAgdGaUgAHcCAAAA.Makusa:BAAALAAECgcICAAAAA==.Malania:BAABLAAECoEfAAMOAAgImhgkPgAcAgAOAAgIwBUkPgAcAgATAAgIaRQGLAD9AQAAAA==.Maldram:BAAALAAECgMIAwAAAA==.Mambo:BAAALAADCggIDQABLAAECgYIDwAFAAAAAA==.Marwell:BAAALAAECgUICQAAAA==.Maryvonne:BAABLAAECoEUAAIhAAYItx16GAD3AQAhAAYItx16GAD3AQAAAA==.',Mc='Mcfishy:BAAALAAECgMIBAAAAA==.Mctha:BAAALAAECgMIAwAAAA==.',Me='Meddyg:BAABLAAECoEdAAQMAAgI8w4DNADQAQAMAAgI8w4DNADQAQAaAAUIDxJaFQAdAQAKAAEIwANdpgAlAAAAAA==.Medunatia:BAAALAAECggIDwAAAA==.Meradah:BAABLAAECoEiAAIOAAgIoxwFKwBnAgAOAAgIoxwFKwBnAgAAAA==.Methea:BAAALAADCgIIAgAAAA==.',Mi='Milva:BAAALAAECgIIAgABLAAFFAMIBwAfANsZAA==.Mimikyu:BAAALAADCggIGgAAAA==.Minihelland:BAABLAAECoEoAAIgAAgI+yFJAgAcAwAgAAgI+yFJAgAcAwAAAA==.Mirable:BAAALAAECgQIBQAAAA==.Mistreskarai:BAAALAAECgYIDQAAAA==.',Mo='Moirraine:BAAALAADCggIDQAAAA==.Mojoverse:BAAALAAECgYIBgAAAA==.Mono:BAABLAAECoEqAAIGAAgI/B82CgDpAgAGAAgI/B82CgDpAgAAAA==.Monsterbaby:BAAALAAECgIIAgAAAA==.Moolow:BAAALAADCgIIAgAAAA==.Mormonk:BAAALAAECgEIAQAAAA==.Morphdem:BAABLAAECoEgAAISAAcITx4FDQBXAgASAAcITx4FDQBXAgAAAA==.Mozzihn:BAAALAAECgIIAgAAAA==.',Mu='Mucka:BAAALAAECggIEAAAAA==.Mulberry:BAACLAAFFIEFAAILAAIIswnvOABvAAALAAIIswnvOABvAAAsAAQKgSEAAgsACAgMHAUsADcCAAsACAgMHAUsADcCAAAA.Mulgor:BAAALAAECgQIBwAAAA==.Mundis:BAAALAADCgEIAQAAAA==.Muonspeed:BAAALAADCggIDAAAAA==.',['Má']='Mánimal:BAABLAAECoEhAAITAAgIvB8sEQDHAgATAAgIvB8sEQDHAgAAAA==.',Na='Nagur:BAAALAAECgMIBQAAAA==.Nagz:BAAALAAECgQICgAAAA==.Nahoras:BAABLAAECoEXAAMXAAgIyiHvCwAcAwAXAAgIyiHvCwAcAwALAAYIxx+mMAAlAgAAAA==.Nalona:BAABLAAECoEiAAMEAAgIxhUwJQALAgAEAAgIxhUwJQALAgADAAIItQpeqwBIAAAAAA==.Namedrop:BAACLAAFFIENAAIWAAMIKxy1BgAGAQAWAAMIKxy1BgAGAQAsAAQKgTAAAhYACAhUJRYCAGYDABYACAhUJRYCAGYDAAAA.Namedropped:BAAALAADCggIDQABLAAFFAMIDQAWACscAA==.Narria:BAAALAADCgcIBwAAAA==.Nazkerban:BAAALAAECgQICAAAAA==.',Ne='Nemesisx:BAAALAAECggICAAAAA==.Nentia:BAABLAAECoEWAAMaAAgIFhk8CwDDAQAKAAgIxxPxLAALAgAaAAcI5xU8CwDDAQAAAA==.Neosmoke:BAAALAADCggICQAAAA==.Neshi:BAABLAAECoEVAAINAAgIXBfTWgABAgANAAgIXBfTWgABAgAAAA==.Netheron:BAACLAAFFIEFAAIRAAIIoQiOEwCRAAARAAIIoQiOEwCRAAAsAAQKgRgAAxEACAjmEiAgAOABABEABwiWEyAgAOABABAABQi5Cg6VAP8AAAAA.Nevaeh:BAAALAAECgIIAgAAAA==.',Ni='Nickï:BAAALAAECgYIBwAAAA==.Nidriel:BAABLAAECoEUAAIEAAYIAhdHOgCWAQAEAAYIAhdHOgCWAQAAAA==.Nienionienio:BAAALAADCgYIBgAAAA==.Nightdark:BAAALAAECgMIAwAAAA==.Ninaeliel:BAAALAADCggICgAAAA==.Nivarys:BAABLAAECoEcAAIYAAcIQxjtGwD9AQAYAAcIQxjtGwD9AQAAAA==.',Nj='Njûl:BAAALAAECgYIBgABLAAFFAEIAQAFAAAAAA==.',No='Nokron:BAAALAADCggIEgAAAA==.Nomilian:BAAALAADCggIFwAAAA==.Nommy:BAAALAADCggIGwAAAA==.Nooneknownme:BAABLAAECoEZAAIeAAcI5A2QFABCAQAeAAcI5A2QFABCAQAAAA==.',Nu='Nuhlvaldriel:BAAALAAECggICAAAAA==.Numidia:BAAALAAECgQIBwAAAA==.',Nx='Nx:BAABLAAECoEYAAMMAAgI6yIADAADAwAMAAgI6yIADAADAwAKAAEI8RDJnwAzAAAAAA==.',Ny='Nyshu:BAABLAAECoEgAAIdAAgIbCRBDwAgAwAdAAgIbCRBDwAgAwAAAA==.Nyshú:BAABLAAECoEUAAMOAAYIkCI0PgAbAgAOAAYIkCI0PgAbAgATAAEInwhYtAAmAAABLAAECggIIAAdAGwkAA==.',['Nà']='Nàmedrop:BAAALAADCggICAABLAAFFAMIDQAWACscAA==.',['Ná']='Nádja:BAAALAADCgcIBwABLAAECgQIBAAFAAAAAA==.',['Nè']='Nèko:BAAALAADCggIJwAAAA==.',['Nó']='Nózomi:BAAALAADCggIFQABLAAECgcIGgAhACQdAA==.',Of='Off:BAABLAAECoEiAAMmAAgInhtdCgAmAgAmAAcIzRxdCgAmAgAXAAgIlg+OPgDXAQAAAA==.',Oj='Ojobe:BAAALAAECgEIAQAAAA==.',Ol='Oliminus:BAAALAAECggIEgAAAA==.',Om='Omgetosnakey:BAAALAADCggIEAAAAA==.',On='Oneshock:BAABLAAECoEaAAIEAAcItxaFKwDjAQAEAAcItxaFKwDjAQAAAA==.Onimu:BAABLAAECoEeAAIjAAgINQjSNgBsAQAjAAgINQjSNgBsAQAAAA==.Onlybrews:BAABLAAECoElAAIJAAcIQR1FFABEAgAJAAcIQR1FFABEAgAAAA==.',Or='Orbxin:BAAALAADCggIBwAAAA==.Oredos:BAABLAAECoEUAAMLAAYI2xV1aQB2AQALAAYI2xV1aQB2AQAXAAQIEQf4hQC3AAAAAA==.',Pa='Paindk:BAAALAAECgEIAQAAAA==.Painpaladin:BAAALAADCggIDgAAAA==.Palaisakern:BAAALAAECgMIBAAAAA==.Palkei:BAAALAAECgMIBwAAAA==.Pandabuffel:BAABLAAECoEUAAIJAAgIFhY0FwAhAgAJAAgIFhY0FwAhAgAAAA==.',Pe='Peloa:BAAALAADCggICAAAAA==.Perfectdark:BAAALAAECgYIBQAAAA==.',Pi='Pinda:BAAALAADCggICAAAAA==.',Pn='Pnepnepne:BAAALAAECgIIAwAAAA==.',Po='Portalgeist:BAABLAAECoEeAAMjAAgIVQyNMwB9AQAjAAgIVQyNMwB9AQAIAAQIwQLzwwB0AAAAAA==.',Pr='Price:BAAALAAECggIEAAAAA==.Prillan:BAAALAAECgIIAgAAAA==.Prisna:BAAALAADCggIDwAAAA==.',Ql='Qloosanka:BAAALAADCgEIAQAAAA==.',Qu='Quilchex:BAAALAAECgMIBAAAAA==.',Ra='Rack:BAAALAAECggIDwAAAA==.Rammlied:BAAALAAECgcIEAAAAA==.Raptorgodx:BAAALAAECggICAABLAAECggIDwAFAAAAAA==.Rayce:BAAALAAECgYICQAAAA==.',Re='Redeemed:BAAALAADCggIDgAAAA==.Refrigerated:BAAALAADCgQIBAAAAA==.Reiyou:BAACLAAFFIEFAAIMAAII5Q9/FwCQAAAMAAII5Q9/FwCQAAAsAAQKgSgAAgwACAgJH7IQANQCAAwACAgJH7IQANQCAAAA.Rellia:BAAALAAECgMIAwAAAA==.Rephaim:BAAALAAECgYICwAAAA==.Retbully:BAAALAAECgYIEAAAAA==.',Rh='Rhino:BAAALAADCgUIBAABLAAECggIIQATALwfAA==.',Ri='Rigtze:BAABLAAECoEqAAIjAAgIdBe2GAAsAgAjAAgIdBe2GAAsAgAAAA==.Ririzuha:BAABLAAECoEfAAIjAAgIbSS/AwBHAwAjAAgIbSS/AwBHAwAAAA==.Rissmien:BAAALAAECgQICAAAAA==.',Ro='Rogueflax:BAABLAAECoEcAAIBAAgIOxndEgB1AgABAAgIOxndEgB1AgAAAA==.Romeomo:BAAALAADCggICgAAAA==.',Ru='Ruth:BAACLAAFFIEFAAMRAAIIcQZTIwBKAAARAAEIUAhTIwBKAAAQAAEIkgQrQwA8AAAsAAQKgSgAAxAACAhGGDo+AAkCABAACAhmEzo+AAkCABEABQipGcMuAJABAAAA.Ruud:BAAALAADCgcIBwAAAA==.',Rv='Rvck:BAAALAAECgQIAwAAAA==.',['Rú']='Rúkia:BAABLAAECoEaAAMhAAcIJB0HFQAZAgAhAAcIJB0HFQAZAgAYAAYIuhpnIgDMAQAAAA==.',Sa='Sadammo:BAABLAAECoEZAAMiAAgIMhXXHACVAQAiAAgIMhXXHACVAQAdAAYIpwtvpgBBAQAAAA==.Saman:BAABLAAECoEmAAQQAAgIvhgUKgBpAgAQAAgIvhgUKgBpAgARAAUIBwclVQDqAAAPAAIIEAFCMgBRAAAAAA==.Sarshá:BAAALAADCgMIAwAAAA==.',Se='Segath:BAABLAAECoEcAAIlAAcI3QP8LAA8AQAlAAcI3QP8LAA8AQAAAA==.Seleen:BAAALAAECgMIBAAAAA==.Selenias:BAAALAADCgUIBQAAAA==.Selila:BAAALAAECgEIAQAAAA==.Serathon:BAAALAADCgYIBgAAAA==.Setupp:BAAALAAECgEIAQAAAA==.',Sh='Shailu:BAAALAAECgQIBAAAAA==.Shakdan:BAABLAAECoEZAAMEAAcIPRh2LgDTAQAEAAcIPRh2LgDTAQADAAIIUhGDpwBSAAAAAA==.Shamsham:BAABLAAECoEcAAImAAcIhBolCgAqAgAmAAcIhBolCgAqAgAAAA==.Shayadin:BAAALAAECgIIAgAAAA==.Sheinam:BAAALAAECgUICQAAAA==.Shironi:BAABLAAECoEWAAMXAAcIKg5zSgCnAQAXAAcIKg5zSgCnAQALAAIIoQQZCAErAAABLAAECggIHQAMAPMOAA==.Shooker:BAABLAAECoEYAAITAAcIJSScDgDfAgATAAcIJSScDgDfAgAAAA==.Shoorka:BAAALAADCgMIAwAAAA==.Shortcakes:BAAALAADCggIDgAAAA==.Shrando:BAABLAAECoEYAAIRAAcIwhmpFQAqAgARAAcIwhmpFQAqAgAAAA==.Shylanai:BAAALAADCgQIBAAAAA==.',Si='Siegrain:BAAALAADCgMIAwAAAA==.Sikkertlunar:BAAALAAECgYIBwABLAAECggIHgAIAGMfAA==.Sikstis:BAAALAADCgcICAAAAA==.',Sj='Sjöjohan:BAAALAADCggICQAAAA==.',Sk='Skridtspark:BAABLAAECoEiAAILAAgIxxWKPgD0AQALAAgIxxWKPgD0AQAAAA==.Skêlar:BAABLAAECoEaAAIMAAgIDhPmKgAEAgAMAAgIDhPmKgAEAgAAAA==.',Sl='Slaphead:BAAALAAECgUIBgAAAA==.Slayallmonks:BAAALAAECgYICgAAAA==.Slayforfun:BAAALAADCggICAAAAA==.Slaythedudu:BAABLAAECoEZAAIDAAgICRL6NwDCAQADAAgICRL6NwDCAQAAAA==.Slaythepala:BAAALAAECggICAAAAA==.Slaytheprest:BAAALAAECgUIBQAAAA==.Slaytheshamy:BAAALAAECgYICwAAAA==.',Sn='Snabbchaos:BAABLAAECoEqAAQQAAgIyRv2KQBqAgAQAAgIlxn2KQBqAgARAAcIvRl0GwD+AQAPAAIIFAKHMQBVAAAAAA==.Snabbexecute:BAABLAAECoEpAAIfAAgInCHqFADmAgAfAAgInCHqFADmAgAAAA==.Snabbjeavel:BAAALAADCggIFQAAAA==.Snaccthyr:BAAALAAECgYICQAAAA==.Sneakysnakey:BAAALAAECgYICgAAAA==.Snorlaxlover:BAAALAADCgEIAgAAAA==.',So='Soak:BAABLAAECoEfAAIIAAgI7R4VJwCUAgAIAAgI7R4VJwCUAgAAAA==.Sofera:BAAALAAECgYIEgAAAA==.Solniaz:BAAALAADCgcIDQAAAA==.Sonos:BAABLAAECoEjAAMXAAgIehSoLgAjAgAXAAgIehSoLgAjAgAmAAMI8QXVHwB6AAAAAA==.Sooto:BAAALAADCgcIBwAAAA==.Sootú:BAABLAAECoEXAAIKAAcIhCBjGACKAgAKAAcIhCBjGACKAgAAAA==.Soulreaper:BAAALAAECgYIBgAAAA==.',Sp='Spiro:BAAALAADCgEIAQAAAA==.Spleehunter:BAAALAAECgQIBAAAAA==.Spritney:BAAALAADCggIFwABLAAECggILQATACkgAA==.',St='Stennup:BAACLAAFFIEJAAIfAAMIpRUeDwAAAQAfAAMIpRUeDwAAAQAsAAQKgS0AAx8ACAjOIHMUAOoCAB8ACAjOIHMUAOoCACAABAhoGlMXAEQBAAAA.Stickytoffee:BAAALAADCggICAAAAA==.Stormchrome:BAAALAADCggIDgABLAAECggICAAFAAAAAA==.Stryk:BAABLAAECoEoAAIWAAgI/xt2EQB8AgAWAAgI/xt2EQB8AgAAAA==.Stuntress:BAABLAAECoEZAAITAAcInBeFLwDoAQATAAcInBeFLwDoAQAAAA==.Stur:BAAALAADCgYIBwAAAA==.',Su='Sukíe:BAAALAAECggICAAAAA==.Sulphuria:BAAALAADCggIDwAAAA==.Sunderthighs:BAAALAAECgYIBgABLAAECggIFwAIAPgYAA==.Sunzi:BAAALAAECgEIAQAAAA==.Surelîa:BAAALAADCgYIBgAAAA==.Survivor:BAAALAADCgcIBwABLAAECgYIFQAJAK4UAA==.Sushy:BAACLAAFFIEIAAILAAMIAx1VDAD9AAALAAMIAx1VDAD9AAAsAAQKgR0AAwsACAg5JGAFACkDAAsACAg5JGAFACkDABcABQhWFctiAFMBAAAA.',Sy='Sylveria:BAAALAAECgMIBQAAAA==.Syraxx:BAABLAAECoEaAAIGAAgIUg7GJQDHAQAGAAgIUg7GJQDHAQAAAA==.',Ta='Taivokershan:BAAALAAECgYIDAAAAA==.Talevane:BAAALAAECgMIAwAAAA==.Talzin:BAAALAAECgEIAgAAAA==.Tansari:BAAALAAECgYIEwAAAA==.Tawny:BAAALAAECgcIBwAAAA==.',Te='Tehmoshi:BAAALAADCggIFAAAAA==.Tellusia:BAAALAAECgYICgAAAA==.Terribletim:BAAALAAECgYICQAAAA==.Terzal:BAABLAAECoEiAAIdAAgIgBr6MABrAgAdAAgIgBr6MABrAgAAAA==.',Th='Tharain:BAAALAADCgQIBgAAAA==.Thecream:BAAALAADCgMIAwAAAA==.Theryandh:BAABLAAECoEgAAMdAAgIOiU1BwBVAwAdAAgIryQ1BwBVAwAiAAYItyWACgCDAgAAAA==.Theserpent:BAAALAAECgYIDAAAAA==.This:BAAALAAECgMIBQABLAAECggIIgAmAJ4bAA==.Thriela:BAABLAAECoEYAAIEAAgI0xe0KQDvAQAEAAgI0xe0KQDvAQAAAA==.Thrilmi:BAAALAAECgMIAwAAAA==.Thrilos:BAAALAADCgIIAwAAAA==.Thumert:BAAALAAECgEIAQAAAA==.Thunderbonk:BAABLAAECoEcAAIIAAgIpyENGADhAgAIAAgIpyENGADhAgAAAA==.Thunk:BAECLAAFFIEFAAIfAAII+RTpGQCrAAAfAAII+RTpGQCrAAAsAAQKgSoAAx8ACAg1I0YKADcDAB8ACAgfI0YKADcDACAAAwgOF1ofANgAAAAA.',Ti='Tidess:BAAALAAECgQIBAAAAA==.Tidex:BAAALAADCggIFwAAAA==.Tiffania:BAAALAAECgEIAQAAAA==.Time:BAAALAAECgIIAgABLAAECggIIQATALwfAA==.Timedwalker:BAAALAADCggIDgAAAA==.',To='Tondar:BAAALAAECgcIEgAAAA==.Torwen:BAAALAAECggICAAAAA==.Toxsin:BAACLAAFFIEIAAIQAAIIuyAlHQDAAAAQAAIIuyAlHQDAAAAsAAQKgRgAAhAACAioJOgGAFADABAACAioJOgGAFADAAEsAAUUBggZABAA6B8A.',Tr='Treehug:BAAALAAECgMIAgAAAA==.Trippeex:BAAALAADCggICQAAAA==.Trollaren:BAAALAAECgUICAAAAA==.Truenaro:BAAALAAECgYIBwAAAA==.',Tu='Tuern:BAAALAAECgMIBQAAAA==.Tulehaamer:BAAALAADCgQIBAABLAAFFAMICgAfAGMYAA==.Turinel:BAAALAADCgQICQAAAA==.',Tw='Twijg:BAAALAAECgMIAwABLAAECggIIQADACkSAA==.',Us='Uski:BAAALAAECgYIBgAAAA==.Usucka:BAAALAAECgUIDgAAAA==.',Va='Vaelion:BAAALAADCgIIAgAAAA==.Vaevorn:BAAALAADCggICAABLAAECggIIgADABwLAA==.Valarrow:BAABLAAECoErAAITAAgINx71EwCuAgATAAgINx71EwCuAgABLAAECggIKAAEAGQfAA==.Valdraugr:BAAALAAECgYIBgABLAAECggIKAAEAGQfAA==.Valentijne:BAAALAAECgMIBAAAAA==.Valgus:BAAALAADCgEIAQAAAA==.Valinn:BAAALAADCgcIBwAAAA==.Valskuggis:BAAALAAECgcIDgABLAAECggIKAAEAGQfAA==.Valtharon:BAAALAAECgEIAQAAAA==.Valzan:BAACLAAFFIEHAAMfAAMI2xlvGQCtAAAfAAIIkRZvGQCtAAAgAAEIbiBhBQBiAAAsAAQKgRUAAx8ACAjlI5AaAMACAB8ACAjRI5AaAMACACAAAghpJKYhALsAAAAA.Vanator:BAAALAAECgMIBAAAAA==.Vanderley:BAAALAAECgYICgAAAA==.Vansinne:BAAALAADCgYIDAAAAA==.Variety:BAAALAADCgMIAgAAAA==.',Ve='Vegapunk:BAAALAADCgIIAgAAAA==.',Vi='Vinca:BAABLAAECoEVAAMmAAgIKxU6DgDXAQAmAAgIXBM6DgDXAQAXAAYIbg+RYABbAQAAAA==.Vindicus:BAAALAAECgIIBAAAAA==.',Vo='Voidine:BAAALAAECgYIBgABLAAECggILQATACkgAA==.Vonadin:BAABLAAECoEYAAIYAAgILRTXGQAOAgAYAAgILRTXGQAOAgAAAA==.',Wa='Waka:BAAALAAECgYICQAAAA==.Waltz:BAAALAADCgUIBQAAAA==.Warpíg:BAAALAADCgcIBwAAAA==.Washini:BAAALAAECggIDAAAAA==.',We='Weehaggis:BAAALAAFFAEIAQABLAAECgYIBQAFAAAAAA==.Weriess:BAAALAAECgYIEAAAAA==.',Wi='Wiggzz:BAABLAAECoEYAAIgAAcIgBDYEAChAQAgAAcIgBDYEAChAQAAAA==.Wizesson:BAAALAADCgcIBwAAAA==.',Wo='Wojski:BAAALAAECgcIBwAAAA==.Wombatt:BAAALAAECgIIAgAAAA==.',Wt='Wtypestuff:BAABLAAECoEXAAInAAgIBRAGIABxAQAnAAgIBRAGIABxAQAAAA==.',Wy='Wyneris:BAAALAADCgUIBQAAAA==.',['Wî']='Wîccan:BAAALAAECgYIDgAAAA==.',Xa='Xaivi:BAAALAADCgIIAgAAAA==.',Xe='Xenil:BAAALAADCgUIBQAAAA==.',Xi='Xibron:BAAALAAECgEIAQAAAA==.',Xy='Xylaripper:BAAALAADCggICAAAAA==.Xyrien:BAABLAAECoEbAAIXAAgIjyX4EQDnAgAXAAgIjyX4EQDnAgAAAA==.',Ya='Yarl:BAAALAAECgUIBQAAAA==.Yasukí:BAAALAADCggICAAAAA==.',Ye='Yeule:BAABLAAECoElAAIUAAgIRya+AQCCAwAUAAgIRya+AQCCAwAAAA==.',Yi='Yilae:BAAALAADCggIDwABLAAECggIGAAMAOsiAA==.',Yl='Ylwenah:BAAALAAECgIIAwAAAA==.',Yo='Yondan:BAABLAAECoEcAAISAAgI6QtOHQB2AQASAAgI6QtOHQB2AQAAAA==.Yorghul:BAAALAADCggIEgAAAA==.Yorù:BAAALAADCgcIDwAAAA==.',Yu='Yuelral:BAAALAADCgQIBAAAAA==.Yuka:BAABLAAECoEaAAIVAAcIBSFJCgCCAgAVAAcIBSFJCgCCAgAAAA==.',Za='Zagga:BAAALAAECgEIAQABLAAECggIIwAIAAkkAA==.Zahhak:BAAALAAECgIIAgAAAA==.Zakhaev:BAAALAAECgYIBgABLAAECggIEAAFAAAAAA==.Zamadrax:BAACLAAFFIEHAAIiAAMIYhyPAgALAQAiAAMIYhyPAgALAQAsAAQKgSEAAiIACAj4H14IAK4CACIACAj4H14IAK4CAAAA.Zanarkand:BAABLAAECoEdAAIKAAgI7BFJOADRAQAKAAgI7BFJOADRAQAAAA==.Zanechan:BAAALAAECggIEAAAAA==.Zas:BAABLAAECoEjAAIUAAgIuhohOABrAgAUAAgIuhohOABrAgAAAA==.',Ze='Zehír:BAAALAADCgIIAgAAAA==.Zenpiggy:BAAALAADCggICwAAAA==.Zenryo:BAABLAAECoEcAAIDAAgIpB7rDwCyAgADAAgIpB7rDwCyAgAAAA==.Zetix:BAABLAAECoEYAAIDAAcI+x2aHQBNAgADAAcI+x2aHQBNAgAAAA==.',Zh='Zhaneel:BAABLAAECoEUAAIfAAYIERy+QQDxAQAfAAYIERy+QQDxAQABLAAFFAIIBAAGAOoXAA==.',Zo='Zobwak:BAAALAADCgEIAQAAAA==.',Zu='Zuleun:BAAALAAECgcIDwAAAA==.',Zv='Zvijer:BAABLAAECoEpAAMfAAgIDh1PIQCRAgAfAAgIDh1PIQCRAgAWAAYIahgsKQC0AQAAAA==.',['Án']='Ánorx:BAAALAAECggIEwAAAA==.',['Çy']='Çyph:BAABLAAECoEiAAIBAAgIByPvBAAjAwABAAgIByPvBAAjAwAAAA==.',['Øl']='Ølglass:BAABLAAECoEeAAIXAAgIpRnNHwB8AgAXAAgIpRnNHwB8AgAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end