local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Paladin-Retribution','Paladin-Protection','Paladin-Holy','Priest-Shadow','Druid-Restoration','DeathKnight-Unholy','Unknown-Unknown','Priest-Holy','Hunter-Marksmanship','Hunter-BeastMastery','Mage-Frost','Mage-Arcane','Evoker-Devastation','Evoker-Preservation','Druid-Balance','DeathKnight-Blood','Warlock-Destruction','Warlock-Demonology','Warrior-Protection','Monk-Mistweaver','Shaman-Restoration','Shaman-Elemental','Monk-Windwalker','Monk-Brewmaster','Warlock-Affliction','DemonHunter-Havoc','Druid-Guardian','DeathKnight-Frost','Priest-Discipline','DemonHunter-Vengeance','Mage-Fire','Warrior-Fury','Evoker-Augmentation',}; local provider = {region='EU',realm='TwistingNether',name='EU',type='subscribers',zone=44,date='2025-09-25',data={Ar='Arhontas:BAECLAAFFIEPAAQBAAYI8B8xAgAqAgY5DAAAAgBjADsMAAAEAF0AOgwAAAEAFgA8DAAABABjADIMAAABAFEAPQwAAAMAXQABAAUIliQxAgAqAgU5DAAAAQBjADsMAAACAF0APAwAAAQAYwAyDAAAAQBRAD0MAAADAF0AAgADCHcO8QcAuwADOQwAAAEAHQA7DAAAAQA7ADoMAAABABYAAwABCIMiTR0AXQABOwwAAAEAWAAsAAQKgSwAAwEACAjqJmsAAJ8DAAEACAjqJmsAAJ8DAAMACAg+GTwWADgCAAAA.',Av='Avelain:BAEALAAFFAIIBAABLAAFFAUIDQAEAMIVAA==.',Ax='Ax:BAECLAAFFIEKAAIFAAIIcSIMFAC2AAI5DAAABQBhADoMAAAFAE8ABQACCHEiDBQAtgACOQwAAAUAYQA6DAAABQBPACwABAqBKwACBQAICDAk6QQAMQMABQAICDAk6QQAMQMAAAA=.',Ay='Aythia:BAEBLAAFFIEKAAIGAAQIMxW5AQB6AQQ5DAAABABMADsMAAABAB4AOgwAAAQAXQA9DAAAAQAQAAYABAgzFbkBAHoBBDkMAAAEAEwAOwwAAAEAHgA6DAAABABdAD0MAAABABAAASwABRQFCA0ABADCFQA=.',Ba='Bababouey:BAEALAADCgMIAwABLAAFFAIIAgAHAAAAAA==.',Be='Beatrixa:BAEALAAECgQIBAABLAAFFAUIFgAIAIYUAA==.',Bm='Bmbaclart:BAECLAAFFIEOAAIJAAMIThvHDADoAAM5DAAABQBBADsMAAAEAEQAOgwAAAUASwAJAAMIThvHDADoAAM5DAAABQBBADsMAAAEAEQAOgwAAAUASwAsAAQKgSkAAwkACAiEJHwEAEQDAAkACAiEJHwEAEQDAAoAAQjOBWUvARkAAAAA.',Ch='Chastityman:BAEALAAECgYIBgABLAAFFAMICgADAJsfAA==.',De='Deoos:BAEBLAAECoEYAAMLAAgILBoXGgArAgg5DAAAAwBiADsMAAAGAF8AOgwAAAQAYAA8DAAAAwBZADIMAAADAE0APQwAAAMASQA+DAAAAQACAD8MAAABAAEACwAICKMWFxoAKwIIOQwAAAIAYgA7DAAAAwBfADoMAAACAFEAPAwAAAIAWQAyDAAAAQATAD0MAAACAEkAPgwAAAEAAgA/DAAAAQABAAwABghqGldYAN4BBjkMAAABAEwAOwwAAAMAUgA6DAAAAgBgADwMAAABAB0AMgwAAAIATQA9DAAAAQAqAAAA.',Dr='Drakoncho:BAECLAAFFIEIAAMNAAYIxxVTAwD3AQY5DAAAAgBTADsMAAABADAAOgwAAAIARAA8DAAAAQAcADIMAAABAEYAPQwAAAEAIwANAAYIxxVTAwD3AQY5DAAAAQBTADsMAAABADAAOgwAAAEARAA8DAAAAQAcADIMAAABAEYAPQwAAAEAIwAOAAIIxxPbDQCTAAI5DAAAAQAxADoMAAABADQALAAECoEcAAINAAgIviTgAgBZAwANAAgIviTgAgBZAwABLAAFFAUIBgAPANkKAA==.',Du='Duskers:BAEALAAECggICwABLAAFFAcIGgAQALYlAA==.',Em='Empathý:BAECLAAFFIEMAAIBAAYImBq5AgAZAgY5DAAAAgBbADsMAAABAD8AOgwAAAIARgA8DAAAAwBMAD0MAAADAFEAPgwAAAEAGQABAAYImBq5AgAZAgY5DAAAAgBbADsMAAABAD8AOgwAAAIARgA8DAAAAwBMAD0MAAADAFEAPgwAAAEAGQAsAAQKgTAAAgEACAh3JgsEAHYDAAEACAh3JgsEAHYDAAAA.',Ev='Everia:BAEALAAECgYIDAABLAAFFAYIDAABAJgaAA==.',Fa='Faelksud:BAEALAADCggICAABLAAFFAcIGgAQALYlAA==.',Fe='Fendros:BAEBLAAECoEXAAMRAAgI2iC2FgDnAgg5DAAABABdADsMAAADAF8AOgwAAAMAVwA8DAAAAwBQADIMAAADAEoAPQwAAAIAUgA+DAAAAwBQAD8MAAACAE0AEQAICNogthYA5wIIOQwAAAMAXQA7DAAAAwBfADoMAAADAFcAPAwAAAMAUAAyDAAAAwBKAD0MAAACAFIAPgwAAAMAUAA/DAAAAgBNABIAAQhvC6aMADAAATkMAAABAB0AASwABRQHCBYABgAQIgA=.Fentality:BAEALAAECggIDQABLAAFFAYIIQATADYhAA==.Fenyo:BAECLAAFFIEhAAITAAYINiFIAQBKAgY5DAAABwBgADsMAAAGAE4AOgwAAAYAXwA8DAAABQBKADIMAAAEAEoAPQwAAAUAWgATAAYINiFIAQBKAgY5DAAABwBgADsMAAAGAE4AOgwAAAYAXwA8DAAABQBKADIMAAAEAEoAPQwAAAUAWgAsAAQKgR4AAhMACAjqJawDAEoDABMACAjqJawDAEoDAAAA.',Fl='Flinsy:BAECLAAFFIEKAAIDAAMImx8NCAAfAQM5DAAABABEADsMAAACAFgAOgwAAAQAVQADAAMImx8NCAAfAQM5DAAABABEADsMAAACAFgAOgwAAAQAVQAsAAQKgSAAAwMACAhaGpwRAGQCAAMACAhaGpwRAGQCAAEABghYDYfZAB4BAAAA.Flöjtist:BAEALAAECgEIAgABLAAFFAIIAgAHAAAAAA==.',Fo='Forgordog:BAEALAADCggICAABLAAFFAYIHQABAIsjAA==.',Ga='Gaelbas:BAEBLAAECoEeAAIUAAgIOBe5EQAsAgg5DAAABABBADsMAAAEAFAAOgwAAAQARgA8DAAABABEADIMAAAEADgAPQwAAAQAFAA+DAAAAwA6AD8MAAADADYAFAAICDgXuREALAIIOQwAAAQAQQA7DAAABABQADoMAAAEAEYAPAwAAAQARAAyDAAABAA4AD0MAAAEABQAPgwAAAMAOgA/DAAAAwA2AAEsAAUUBwgaAAUAMRsA.',Go='Gordog:BAECLAAFFIEdAAIBAAYIiyPIAAB+AgY5DAAABwBjADsMAAAGAF4AOgwAAAcAYQA8DAAAAwBXADIMAAACAEwAPQwAAAQAWgABAAYIiyPIAAB+AgY5DAAABwBjADsMAAAGAF4AOgwAAAcAYQA8DAAAAwBXADIMAAACAEwAPQwAAAQAWgAsAAQKgSYAAgEACAjiJuwAAJYDAAEACAjiJuwAAJYDAAAA.',['Hë']='Hënning:BAEALAAECgMIAwAAAA==.',If='Ifeelfreenow:BAEALAAFFAIIAgAAAA==.',In='Inekshamân:BAECLAAFFIESAAIVAAYIshxFAgAQAgY5DAAABABKADsMAAADAFIAOgwAAAQATAA8DAAAAwA7ADIMAAABAFMAPQwAAAMAQAAVAAYIshxFAgAQAgY5DAAABABKADsMAAADAFIAOgwAAAQATAA8DAAAAwA7ADIMAAABAFMAPQwAAAMAQAAsAAQKgSYAAxUACAgaIf0QAM8CABUACAgaIf0QAM8CABYABgicDiNqAE4BAAAA.',Ja='Japanexport:BAEALAAFFAIIAgABLAAFFAIIBAAHAAAAAA==.Japanimport:BAECLAAFFIEMAAIRAAQIxRj+EQBLAQQ5DAAABABaADsMAAADAEcAOgwAAAMAOwA8DAAAAgAfABEABAjFGP4RAEsBBDkMAAAEAFoAOwwAAAMARwA6DAAAAwA7ADwMAAACAB8ALAAECoEYAAIRAAgIoSXtCQA9AwARAAgIoSXtCQA9AwABLAAFFAIIBAAHAAAAAA==.',Jo='Jorar:BAEBLAAECoElAAMEAAgIUSbDAgBuAwg5DAAABQBhADsMAAAFAGMAOgwAAAUAYQA8DAAABQBfADIMAAAFAGIAPQwAAAMAYQA+DAAABABjAD8MAAAFAGIABAAICFEmwwIAbgMIOQwAAAUAYQA7DAAABQBjADoMAAAFAGEAPAwAAAUAXwAyDAAABQBiAD0MAAADAGEAPgwAAAQAYwA/DAAABABiAAgAAQgiHQAAAAAAAT8MAAABAEoAASwABAoICDYAFACBJgA=.Jowaww:BAEBLAAECoE2AAMUAAgIgSY9AACJAwg5DAAABgBhADsMAAAGAGMAOgwAAAYAYwA8DAAABgBeADIMAAAGAGIAPQwAAAgAYwA+DAAABQBjAD8MAAALAGMAFAAICIEmPQAAiQMIOQwAAAUAYQA7DAAABQBjADoMAAAFAGMAPAwAAAYAXgAyDAAABQBiAD0MAAAHAGMAPgwAAAUAYwA/DAAACwBjABcABQgEHhItAHEBBTkMAAABAFAAOwwAAAEARQA6DAAAAQBLADIMAAABAFAAPQwAAAEATQAAAA==.',Ju='Junipear:BAECLAAFFIEIAAIYAAMIoBR9CADhAAM5DAAAAwBPADsMAAACACUAOgwAAAMAKQAYAAMIoBR9CADhAAM5DAAAAwBPADsMAAACACUAOgwAAAMAKQAsAAQKgRgAAhgACAgpH/IJAKACABgACAgpH/IJAKACAAEsAAUUBwgaABAAtiUA.',Ka='Kaldeak:BAEALAAFFAIIBAABLAAFFAcIFgARAEEbAA==.Kaldeakw:BAECLAAFFIEWAAMRAAcIQRv4AQCIAgc5DAAABABcADsMAAAEAGEAOgwAAAQAVgA8DAAAAwA0ADIMAAADADMAPQwAAAMAVwA+DAAAAQATABEABwhBG/gBAIgCBzkMAAADAFwAOwwAAAQAYQA6DAAAAwBWADwMAAADADQAMgwAAAMAMwA9DAAAAwBXAD4MAAABABMAEgACCEoQ5REAmQACOQwAAAEAMQA6DAAAAQAiACwABAqBJQAEEQAICNIlEgcAUgMAEQAICNIlEgcAUgMAEgAGCG4d3C4AlgEAGQABCAIlkzEAWgAAAAA=.Kaldh:BAEALAADCgYIBQABLAAFFAcIFgARAEEbAA==.Kapowdh:BAEBLAAECoElAAIaAAgIKh9+IgC9Agg5DAAABgBTADsMAAAHAE4AOgwAAAUAXgA8DAAABQBSADIMAAAGAFoAPQwAAAQAUQA+DAAAAgBHAD8MAAACADcAGgAICCoffiIAvQIIOQwAAAYAUwA7DAAABwBOADoMAAAFAF4APAwAAAUAUgAyDAAABgBaAD0MAAAEAFEAPgwAAAIARwA/DAAAAgA3AAAA.Kardioklefti:BAEBLAAECoEZAAQPAAgI6yFpCgANAwg5DAAAAwBfADsMAAAFAGEAOgwAAAQAYQA8DAAABABeADIMAAAEAEwAPQwAAAMAVQA+DAAAAQBXAD8MAAABADsADwAICOshaQoADQMIOQwAAAEAXwA7DAAAAwBhADoMAAADAGEAPAwAAAMAXgAyDAAAAwBMAD0MAAABAFUAPgwAAAEAVwA/DAAAAQA7AAUABghNIQMrAA8CBjkMAAACAFAAOwwAAAIAVAA6DAAAAQBHADwMAAABAGAAMgwAAAEAVwA9DAAAAQBaABsAAQg5IcgoAGAAAT0MAAABAFUAASwABRQGCA8AAQDwHwA=.',Ke='Kerfluffle:BAEALAADCgMIAwABLAAFFAcIGAAFAJMaAA==.',Ki='Kiljacken:BAECLAAFFIEaAAIFAAcIMRtpAACQAgc5DAAABQBiADsMAAAFAFAAOgwAAAUAYAA8DAAABABUADIMAAADADsAPQwAAAMAPQA+DAAAAQAFAAUABwgxG2kAAJACBzkMAAAFAGIAOwwAAAUAUAA6DAAABQBgADwMAAAEAFQAMgwAAAMAOwA9DAAAAwA9AD4MAAABAAUALAAECoEkAAIFAAgI3yUuAgBaAwAFAAgI3yUuAgBaAwAAAA==.Kittengirlx:BAECLAAFFIEXAAITAAcIIiM+AADkAgc5DAAABQBjADsMAAAEAGIAOgwAAAUAXQA8DAAAAwBfADIMAAACAE4APQwAAAMAYQA+DAAAAQBCABMABwgiIz4AAOQCBzkMAAAFAGMAOwwAAAQAYgA6DAAABQBdADwMAAADAF8AMgwAAAIATgA9DAAAAwBhAD4MAAABAEIALAAECoEiAAITAAgIkSYoAQB9AwATAAgIkSYoAQB9AwAAAA==.',Kr='Kruae:BAEALAAECggIDgAAAA==.',Kw='Kwigga:BAEALAAECgUIBgABLAAFFAYIHAAFACAmAA==.',Li='Lilgaychi:BAECLAAFFIEOAAIUAAYIaRsbAQAtAgY5DAAAAwBhADsMAAADAF8AOgwAAAMAYQA8DAAAAgApADIMAAABAEcAPQwAAAIAEgAUAAYIaRsbAQAtAgY5DAAAAwBhADsMAAADAF8AOgwAAAMAYQA8DAAAAgApADIMAAABAEcAPQwAAAIAEgAsAAQKgRgAAhQACAhLJl0BAFgDABQACAhLJl0BAFgDAAAA.',Lu='Luchthonn:BAEALAADCgcIBwABLAAFFAMICgADAJsfAA==.',Ma='Makiavella:BAEALAAECgcIDQABLAAFFAYIDwABAPAfAA==.Mande:BAECLAAFFIELAAIOAAYI+BlTAQA5AgY5DAAAAQBcADsMAAADAFkAOgwAAAMAYwAyDAAAAQAYAD0MAAACAB0APgwAAAEAPwAOAAYI+BlTAQA5AgY5DAAAAQBcADsMAAADAFkAOgwAAAMAYwAyDAAAAQAYAD0MAAACAB0APgwAAAEAPwAsAAQKgScAAg4ACAiBI2EBAEoDAA4ACAiBI2EBAEoDAAAA.Masan:BAEALAAECgUIBgABLAAFFAUIEAAKADolAA==.',Me='Melicand:BAEBLAAECoEcAAQFAAYIHBEVaAAjAQY5DAAABQBbADsMAAAFADsAOgwAAAUAJwA8DAAABQAEADIMAAAEAAkAPQwAAAQAOgAFAAUIdBEVaAAjAQU5DAAAAQBbADsMAAACADsAPAwAAAEABAAyDAAAAQAJAD0MAAABADoADwAGCM0TqF8AAwEGOQwAAAMAMAA7DAAAAwBKADoMAAAFADQAPAwAAAQAOQAyDAAAAwAgAD0MAAACACYAGwACCBAJfCsASAACOQwAAAEAJQA9DAAAAQAJAAEsAAUUBggLAA4A+BkA.',Mi='Mikhepls:BAECLAAFFIEXAAIEAAYI0yThAACcAgY5DAAABABhADsMAAAEAF8AOgwAAAQAYQA8DAAABQBjADIMAAACAF8APQwAAAQATwAEAAYI0yThAACcAgY5DAAABABhADsMAAAEAF8AOgwAAAQAYQA8DAAABQBjADIMAAACAF8APQwAAAQATwAsAAQKgSoAAgQACAjMJo4AAJUDAAQACAjMJo4AAJUDAAAA.Misstraz:BAECLAAFFIEJAAIBAAMI2w09EgDpAAM5DAAABAAbADsMAAACACwAOgwAAAMAIgABAAMI2w09EgDpAAM5DAAABAAbADsMAAACACwAOgwAAAMAIgAsAAQKgRsAAwEACAhzHdIpAKoCAAEACAhTHNIpAKoCAAIABghUFoQ2ACkBAAAA.',['Mâ']='Mâsân:BAECLAAFFIEQAAIKAAUIOiWJAgAbAgU5DAAABABhADsMAAAEAGMAOgwAAAUAXwA8DAAAAgBhAD0MAAABAFUACgAFCDoliQIAGwIFOQwAAAQAYQA7DAAABABjADoMAAAFAF8APAwAAAIAYQA9DAAAAQBVACwABAqBMgACCgAICLomqwIAcgMACgAICLomqwIAcgMAAAA=.',Na='Nadriethiël:BAECLAAFFIEWAAMGAAcIECIVAACOAgc5DAAABQBhADsMAAACAGIAOgwAAAUAYQA8DAAABQBeADIMAAABADgAPQwAAAMAXwA+DAAAAQBGAAYABggmIxUAAI4CBjkMAAAFAGEAOwwAAAIAYgA6DAAABQBhADwMAAAFAF4AMgwAAAEAOAA9DAAAAwBfABwAAQiQG4NnAGUAAT4MAAABAEYALAAECoEyAAMGAAgI4iYRAACjAwAGAAgI4iYRAACjAwAcAAEIxyBlPwFcAAAAAA==.Navira:BAECLAAFFIENAAIEAAUIwhVGBwCdAQU5DAAABABcADsMAAACADIAOgwAAAQAQQA8DAAAAgA6AD0MAAABAAoABAAFCMIVRgcAnQEFOQwAAAQAXAA7DAAAAgAyADoMAAAEAEEAPAwAAAIAOgA9DAAAAQAKACwABAqBGgADBAAICK4iZw4A8wIABAAICK4iZw4A8wIAHQAHCJYRWA0ApgEAAAA=.',Ni='Nippix:BAEALAADCgIIAgABLAAECggIFQAMAOoaAA==.',Pe='Petgorawr:BAEALAADCggIDgABLAAECggINgAUAIEmAA==.',Pi='Pipidal:BAEBLAAECoEfAAILAAgIkBmOFQBVAgg5DAAABQBaADsMAAAFAFQAOgwAAAQARwA8DAAABQA/ADIMAAAFAEgAPQwAAAQARAA+DAAAAgAmAD8MAAABACEACwAICJAZjhUAVQIIOQwAAAUAWgA7DAAABQBUADoMAAAEAEcAPAwAAAUAPwAyDAAABQBIAD0MAAAEAEQAPgwAAAIAJgA/DAAAAQAhAAAA.Pipiyel:BAEALAADCgEIAQABLAAECggIHwALAJAZAA==.',Pr='Promi:BAECLAAFFIEHAAIKAAUIIyTHHAC4AAU5DAAAAgBcADsMAAABAGEAOgwAAAIAVwA8DAAAAQBXAD0MAAABAGIACgAFCCMkxxwAuAAFOQwAAAIAXAA7DAAAAQBhADoMAAACAFcAPAwAAAEAVwA9DAAAAQBiACwABAqBFAACCgAICIgfQhcA3AIACgAICIgfQhcA3AIAASwABRQCCAQABwAAAAA=.',Pu='Puberty:BAECLAAFFIEGAAIbAAII4CZoAQDqAAI5DAAAAwBjADoMAAADAGMAGwACCOAmaAEA6gACOQwAAAMAYwA6DAAAAwBjACwABAqBIQACGwAICGomYQAAiQMAGwAICGomYQAAiQMAASwABRQHCBcAEwAiIwA=.',Ra='Rainism:BAEBLAAFFIEMAAMKAAYIfx9GBADsAQY5DAAAAgBhADsMAAACAF0AOgwAAAIAYQA8DAAAAgBFADIMAAACACkAPQwAAAIAVAAKAAUIkSJGBADsAQU5DAAAAgBhADsMAAACAF0AOgwAAAIAYQA8DAAAAgBFAD0MAAACAFQACQABCCQQeSsATwABMgwAAAIAKQAAAA==.Rainmakêr:BAEBLAAECoEaAAIDAAgI9harFgAzAgg5DAAABAA1ADsMAAAEAEsAOgwAAAUASAA8DAAABABGADIMAAAEAE8APQwAAAMARgA+DAAAAQAgAD8MAAABAA4AAwAICPYWqxYAMwIIOQwAAAQANQA7DAAABABLADoMAAAFAEgAPAwAAAQARgAyDAAABABPAD0MAAADAEYAPgwAAAEAIAA/DAAAAQAOAAEsAAUUBggSABUAshwA.Ratdog:BAEALAAFFAIIBAABLAAFFAYIHQABAIsjAA==.',Sc='Scribbles:BAECLAAFFIESAAIIAAUIPR5LAwD6AQU5DAAABgBjADsMAAAEAF0AOgwAAAYAYQA8DAAAAQBLAD0MAAABABQACAAFCD0eSwMA+gEFOQwAAAYAYwA7DAAABABdADoMAAAGAGEAPAwAAAEASwA9DAAAAQAUACwABAqBFAACCAAICKkkAAoACwMACAAICKkkAAoACwMAASwABRQHCBgABQCTGgA=.',Sh='Shammande:BAEALAADCggICAABLAAFFAYICwAOAPgZAA==.Shankyernan:BAEALAAECgYIBgABLAAECggICAAHAAAAAA==.',Sl='Slapdudu:BAEALAAECgQICAABLAAFFAMIBAAHAAAAAA==.Slapew:BAEALAAFFAMIBAAAAA==.Slapglaive:BAECLAAFFIEGAAIeAAIIsSGbBQC9AAI5DAAAAwBSADoMAAADAFoAHgACCLEhmwUAvQACOQwAAAMAUgA6DAAAAwBaACwABAqBGgACHgAHCBolaAcA0QIAHgAHCBolaAcA0QIAASwABRQDCAQABwAAAAA=.Slapret:BAEBLAAFFIEGAAMCAAII0yGTBwDAAAI5DAAAAwBcADoMAAADAFEAAgACCNMhkwcAwAACOQwAAAIAXAA6DAAAAgBRAAEAAggXB/9AAIIAAjkMAAABAAUAOgwAAAEAHgABLAAFFAMIBAAHAAAAAA==.',So='Sooth:BAECLAAFFIEWAAMMAAcI0iV2AADmAgc5DAAAAgBjADsMAAAEAF0AOgwAAAQAYwA8DAAABABhADIMAAADAGAAPQwAAAQAYAA+DAAAAQBfAAwABwjRJXYAAOYCBzkMAAACAGMAOwwAAAQAXQA6DAAABABjADwMAAAEAGEAMgwAAAEAYAA9DAAABABgAD4MAAABAF8AHwABCLAlRwYAZgABMgwAAAIAYAAsAAQKgSMAAwwACAi6JhgCAHoDAAwACAi6JhgCAHoDAB8AAQhBJpgWAGcAAAAA.Soothjr:BAEBLAAECoEdAAMMAAgIJiY4CQA/Awg5DAAAAwBjADsMAAAEAGMAOgwAAAMAWwA8DAAABABjADIMAAAEAGEAPQwAAAQAYgA+DAAABABiAD8MAAADAF8ADAAICCYmOAkAPwMIOQwAAAMAYwA7DAAAAwBjADoMAAADAFsAPAwAAAMAYwAyDAAAAwBhAD0MAAADAGIAPgwAAAMAYgA/DAAAAgBfAAsABgghAAAAAAAABjsMAAABAAAAPAwAAAEAAAAyDAAAAQAAAD0MAAABAAEAPgwAAAEAAAA/DAAAAQABAAEsAAUUBwgWAAwA0iUA.',Sp='Spacecowben:BAEBLAAECoEaAAIBAAgIkxwAMgCJAgg5DAAABABGADsMAAAEAFYAOgwAAAMAQwA8DAAAAwBAADIMAAADAFAAPQwAAAMATAA+DAAAAwBHAD8MAAADAEMAAQAICJMcADIAiQIIOQwAAAQARgA7DAAABABWADoMAAADAEMAPAwAAAMAQAAyDAAAAwBQAD0MAAADAEwAPgwAAAMARwA/DAAAAwBDAAAA.',Sq='Sqish:BAECLAAFFIEOAAIVAAQIzBSYCgAwAQQ5DAAABABCADsMAAAEADMAOgwAAAUAVAA8DAAAAQAKABUABAjMFJgKADABBDkMAAAEAEIAOwwAAAQAMwA6DAAABQBUADwMAAABAAoALAAECoFLAAIVAAgIXyXuAwBAAwAVAAgIXyXuAwBAAwAAAA==.',St='Stabbydk:BAEBLAAECoEtAAQGAAgIKB8FBgDuAgg5DAAABwBSADsMAAAHAF0AOgwAAAcATAA8DAAABQBZADIMAAAGAFQAPQwAAAUAVAA+DAAABAA7AD8MAAAEAEQABgAICJ0eBQYA7gIIOQwAAAQAUgA7DAAABABdADoMAAAFAEwAPAwAAAMAWQAyDAAABABUAD0MAAADAFQAPgwAAAIAMAA/DAAAAgBEABAACAh0FAAWAMUBCDkMAAACAD0AOwwAAAMANwA6DAAAAgAbADwMAAACADMAMgwAAAIANwA9DAAAAgA7AD4MAAACADsAPwwAAAIALwAcAAEIyQfiXwEoAAE5DAAAAQATAAAA.Stabbylock:BAEALAAECgYICgABLAAECggILQAGACgfAA==.Stabbywar:BAEALAADCgIIAgABLAAECggILQAGACgfAA==.Straìly:BAEALAAECgcIEwABLAAFFAUIBgAPANkKAA==.Straíly:BAECLAAFFIEGAAMPAAUI2QrsCQAFAQU5DAAAAQAKADsMAAABAAMAOgwAAAEAVAA8DAAAAgAjAD4MAAABAAQADwAECBgN7AkABQEEOQwAAAEACgA7DAAAAQADADoMAAABAFQAPAwAAAIAIwAFAAEIewCDNQBMAAE+DAAAAQABACwABAqBLQAEDwAICKUllAMAYAMADwAICKUllAMAYAMABQAICDkemRIApwIAGwAICIMZBQgARgIAAAA=.Streìly:BAECLAAFFIEIAAMYAAIIEBWrDQCPAAI5DAAABABIADoMAAAEACMAGAACCLQUqw0AjwACOQwAAAMASAA6DAAAAwAhABcAAgiNB84SAGMAAjkMAAABAAMAOgwAAAEAIwAsAAQKgRoAAhgACAi9GZQNAFsCABgACAi9GZQNAFsCAAEsAAUUBQgGAA8A2QoA.Stràily:BAEBLAAFFIEFAAIgAAMIEhWdEAABAQM5DAAAAgBNADsMAAABABgAOgwAAAIAOwAgAAMIEhWdEAABAQM5DAAAAgBNADsMAAABABgAOgwAAAIAOwABLAAFFAUIBgAPANkKAA==.',Sw='Swiga:BAECLAAFFIEcAAIFAAYIICZCAACsAgY5DAAABgBjADsMAAAGAGIAOgwAAAYAYwA8DAAABABbADIMAAACAGEAPQwAAAQAZAAFAAYIICZCAACsAgY5DAAABgBjADsMAAAGAGIAOgwAAAYAYwA8DAAABABbADIMAAACAGEAPQwAAAQAZAAsAAQKgSAAAwUACAheJFwKAPICAAUACAheJFwKAPICAA8ABQiFIkk3ALMBAAAA.',Ta='Tarritni:BAEALAAECgQIBAABLAAECgYIBgAHAAAAAA==.',Tr='Traptinus:BAEALAAECggICAABLAAFFAYIEAAIABgaAA==.',Ts='Tsubàki:BAECLAAFFIEfAAMWAAYIVSAeBAAQAgY5DAAABgBgADsMAAAFAFoAOgwAAAYAXwA8DAAABQBXADIMAAAEAB4APQwAAAUAYAAWAAUIbiQeBAAQAgU5DAAABgBgADsMAAAFAFoAOgwAAAYAXwA8DAAABQBXAD0MAAAFAGAAFQABCJMCoVIAOwABMgwAAAQABgAsAAQKgR4AAhYACAjkI8URAPECABYACAjkI8URAPECAAAA.',Tw='Twiga:BAEBLAAECoEbAAIDAAgIQRV1HgD3AQg5DAAABABIADsMAAAFAFIAOgwAAAQAJAA8DAAABABiADIMAAAEAEoAPQwAAAMAFgA+DAAAAgArAD8MAAABAAUAAwAICEEVdR4A9wEIOQwAAAQASAA7DAAABQBSADoMAAAEACQAPAwAAAQAYgAyDAAABABKAD0MAAADABYAPgwAAAIAKwA/DAAAAQAFAAEsAAUUBggcAAUAICYA.Twirps:BAEALAAFFAIIBAABLAAFFAcIGAAFAJMaAA==.',Ua='Ualizardhary:BAEALAAECgYIDAABLAAFFAQIDgAVAMwUAA==.',Vo='Vodoc:BAECLAAFFIEcAAIWAAcIHSGfAADHAgc5DAAABQBdADsMAAAFAGEAOgwAAAYAXgA8DAAABAA5ADIMAAADAFoAPQwAAAQAWgA+DAAAAQBGABYABwgdIZ8AAMcCBzkMAAAFAF0AOwwAAAUAYQA6DAAABgBeADwMAAAEADkAMgwAAAMAWgA9DAAABABaAD4MAAABAEYALAAECoEgAAIWAAgIRybgAgB3AwAWAAgIRybgAgB3AwAAAA==.',We='Weece:BAEBLAAECoEsAAQIAAgIKB3ZFgCdAgg5DAAABwBbADsMAAAGAGAAOgwAAAcAYwA8DAAABwBGADIMAAAHAGIAPQwAAAgANwA+DAAAAQAzAD8MAAABACIACAAICPIc2RYAnQIIOQwAAAMAWwA7DAAAAwBgADoMAAADAF8APAwAAAQARgAyDAAABABiAD0MAAADADcAPgwAAAEAMwA/DAAAAQAiAAQABggRH8YnACMCBjkMAAADAFYAOwwAAAMAWAA6DAAAAwA7ADwMAAADAFYAMgwAAAMAUgA9DAAABQBKAB0AAgjVJFodANEAAjkMAAABAFkAOgwAAAEAYwABLAAFFAYICwAOAPgZAA==.',Xa='Xarxaloulis:BAEALAADCggICAABLAAFFAYIDwABAPAfAA==.',Xi='Xippì:BAEBLAAECoEVAAIMAAgI6hrEKwCGAgg5DAAAAwBPADsMAAADAFEAOgwAAAMAPwA8DAAAAwBDADIMAAAEAEgAPQwAAAMAUwA+DAAAAQArAD8MAAABADsADAAICOoaxCsAhgIIOQwAAAMATwA7DAAAAwBRADoMAAADAD8APAwAAAMAQwAyDAAABABIAD0MAAADAFMAPgwAAAEAKwA/DAAAAQA7AAAA.',['Xî']='Xîppi:BAEALAAFFAIIAgABLAAECggIFQAMAOoaAA==.',Ye='Yechstree:BAECLAAFFIETAAIPAAUIDSGMAwDlAQU5DAAABQBgADsMAAAFAF0AOgwAAAYAXAA8DAAAAgBFAD0MAAABAEYADwAFCA0hjAMA5QEFOQwAAAUAYAA7DAAABQBdADoMAAAGAFwAPAwAAAIARQA9DAAAAQBGACwABAqBJAADDwAICDImGw0A8AIADwAHCIUmGw0A8AIABQADCPkVDoUA0wAAAAA=.',Yz='Yzaxz:BAECLAAFFIEZAAMNAAYIkiGOAQBFAgY5DAAAAwBiADsMAAAGAF8AOgwAAAYAXgA8DAAAAwAsADIMAAAEAF8APQwAAAMAVgANAAYIsh6OAQBFAgY5DAAAAwBiADsMAAAEAF8AOgwAAAQAXgA8DAAAAwAsADIMAAABADkAPQwAAAIAUAAhAAQIPST2AQCgAQQ7DAAAAgBeADoMAAACAF4AMgwAAAMAXwA9DAAAAQBWACwABAqBHAADDQAICA4lWwoA7AIADQAICFkjWwoA7AIAIQADCNYlNA0ASgEAAAA=.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end