local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Rogue-Outlaw','Mage-Frost','Shaman-Restoration','Warlock-Demonology','Unknown-Unknown','Hunter-Survival','Paladin-Retribution','Druid-Guardian','Monk-Mistweaver','DeathKnight-Frost','Priest-Holy','Priest-Shadow','Priest-Discipline','Evoker-Augmentation','Hunter-BeastMastery','Hunter-Marksmanship','Warlock-Destruction','Rogue-Assassination','Warrior-Protection','Warrior-Fury','Shaman-Enhancement','Shaman-Elemental','Warlock-Affliction','Druid-Restoration','Druid-Balance','DemonHunter-Havoc','Monk-Windwalker','Monk-Brewmaster','Mage-Arcane','Mage-Fire','Rogue-Subtlety','DeathKnight-Unholy','DeathKnight-Blood','Paladin-Holy','Evoker-Devastation','Druid-Feral','Evoker-Preservation','Paladin-Protection','Warrior-Arms','DemonHunter-Vengeance',}; local provider = {region='EU',realm='Kargath',name='EU',type='weekly',zone=44,date='2025-09-24',data={Ad='Addyator:BAABLAAECoEqAAIBAAgIhhddBwAKAgABAAgIhhddBwAKAgAAAA==.',Ae='Aemon:BAAALAAECgIIAgABLAAECggIHQACAMYXAA==.Aerîthrîa:BAAALAAECgIIAwABLAAFFAIICAADANELAA==.',Ah='Ahrigato:BAAALAAECgYICgAAAA==.',Ai='Aisle:BAAALAAECggICAAAAA==.Aisá:BAAALAADCgcIBwAAAA==.Aithusa:BAAALAAECgIIAgAAAA==.',Ak='Aktaíon:BAAALAAECgYIAgAAAA==.',Al='Alahador:BAAALAAECgMIBAAAAA==.Aleriah:BAAALAADCgcIBgAAAA==.Allmight:BAAALAADCgcIBwAAAA==.Aluná:BAAALAAECgMIAwAAAA==.Alunâ:BAAALAAECggIEAAAAA==.Alysara:BAAALAADCggIGAABLAAECggIJwAEAHUiAA==.Alysià:BAAALAADCgYIBgAAAA==.Alysîa:BAAALAADCgcIBwAAAA==.',Am='Ameliea:BAAALAADCgcICAAAAA==.Amphiera:BAAALAAECgIIAgAAAA==.',An='Andromaeda:BAAALAADCggIIAABLAAECgYICwAFAAAAAA==.Andulina:BAAALAAECgYIEgAAAA==.Anduryoni:BAAALAAECgMIBAAAAA==.Anessar:BAABLAAECoEcAAIGAAgIAhSrCAAFAgAGAAgIAhSrCAAFAgAAAA==.Anhayinn:BAABLAAECoEfAAIHAAgIDxZTZwDsAQAHAAgIDxZTZwDsAQAAAA==.Animalus:BAABLAAECoEjAAIIAAcIxRbmDQDAAQAIAAcIxRbmDQDAAQAAAA==.Aniri:BAAALAADCgIIAgAAAA==.Anthorra:BAAALAADCgYIBgAAAA==.Aníko:BAAALAADCggICAAAAA==.',Ap='Apheliona:BAAALAADCgUIBQABLAAECgcIIgAJAGcQAA==.Aphroditona:BAAALAAECgcIDQAAAA==.',Ar='Arcogul:BAABLAAECoEgAAIKAAgItSWMBABoAwAKAAgItSWMBABoAwAAAA==.Arima:BAABLAAECoEfAAQLAAYIXxqXSQCKAQALAAYIXxqXSQCKAQAMAAII4Q0MeQB2AAANAAEIAAkZNQAsAAAAAA==.Arueris:BAAALAADCggIDAAAAA==.Arîmaa:BAAALAAECggICAAAAA==.',As='Asray:BAABLAAECoEgAAIOAAgISRUQCADPAQAOAAgISRUQCADPAQAAAA==.Astenia:BAABLAAECoEWAAMPAAYIcxrbZAC6AQAPAAYIcxrbZAC6AQAQAAEI3gIUvQAeAAAAAA==.Astraeá:BAABLAAECoEWAAIRAAYIkxNEaQCDAQARAAYIkxNEaQCDAQAAAA==.',At='Athalein:BAAALAAECgYIEAAAAA==.',Ay='Ayarina:BAAALAAECggICgAAAA==.',Az='Azanni:BAABLAAECoEdAAISAAcIZx+tEgB8AgASAAcIZx+tEgB8AgAAAA==.Azem:BAAALAADCgYIBgABLAAECgcIIgAJAGcQAA==.Aznam:BAAALAAECggIEAAAAA==.',Ba='Babatu:BAAALAAECgYIBgAAAA==.Bané:BAAALAADCggICAAAAA==.Bargitto:BAABLAAECoEeAAIHAAYIGBzVdADQAQAHAAYIGBzVdADQAQAAAA==.Bashíra:BAAALAADCgMIAgAAAA==.Baymáx:BAABLAAECoEgAAITAAgIgBZ3HQASAgATAAgIgBZ3HQASAgAAAA==.',Be='Bearofc:BAAALAADCggICAAAAA==.Benben:BAAALAAECggICAAAAA==.',Bi='Bingas:BAAALAAECgYIBwAAAA==.',Bl='Blebon:BAABLAAECoE1AAIUAAgIQSMuGADXAgAUAAgIQSMuGADXAgAAAA==.Blutssensed:BAAALAAECgMIAwAAAA==.Blyaná:BAAALAAECgMIAwAAAA==.Blâckbûll:BAAALAADCgcIAwAAAA==.',Bo='Boneprime:BAAALAADCgMIAwAAAA==.',Br='Brustpresse:BAAALAADCgcIDQABLAAECgMIBAAFAAAAAA==.Brülldozer:BAAALAAECgEIAQAAAA==.',Bu='Buja:BAAALAAECgIIAgAAAA==.',By='Byorn:BAABLAAECoElAAMVAAgIKBkeCgAxAgAVAAgIKBkeCgAxAgAWAAEI6wQAAAAAAAAAAA==.',['Bä']='Bärty:BAAALAADCgIIAgAAAA==.',['Bó']='Bó:BAAALAAECggIAQAAAA==.',Ca='Calîgula:BAACLAAFFIEKAAIRAAIIcR5TJACmAAARAAIIcR5TJACmAAAsAAQKgTMABBEACAjCJJ0NACADABEACAgBJJ0NACADAAQABQgkIzQmAMABABcAAQjLJMEvAGIAAAAA.Camurai:BAACLAAFFIEGAAIPAAII3we8OgB4AAAPAAII3we8OgB4AAAsAAQKgTMAAw8ACAi5GXBQAO8BAA8ACAi5GXBQAO8BABAAAQgfFAAAAAAAAAAA.Carly:BAAALAAECgYIEQAAAA==.Carnatac:BAAALAAECggIBQAAAA==.Castivar:BAABLAAECoEjAAIKAAgIJREQbwDjAQAKAAgIJREQbwDjAQAAAA==.Casua:BAAALAADCgMIAwAAAA==.',Ce='Cenartyr:BAACLAAFFIEKAAIYAAMIzRGnDADfAAAYAAMIzRGnDADfAAAsAAQKgSIAAxkACAjZGS8mAA0CABkABwgVGS8mAA0CABgACAjQGHArAAgCAAAA.Cerathica:BAAALAAECgUIDQAAAA==.',Ch='Champloo:BAAALAAECgcIEwAAAA==.Chaozdh:BAABLAAECoEUAAIaAAgItxnwOgBMAgAaAAgItxnwOgBMAgAAAA==.Charlylein:BAAALAADCgcIBwAAAA==.Cheeky:BAABLAAECoEVAAICAAYIlQxPQgBAAQACAAYIlQxPQgBAAQAAAA==.Chenzen:BAABLAAECoEUAAQJAAYIJw+1KAAnAQAJAAYIJw+1KAAnAQAbAAUI3QulPAAAAQAcAAIIvwlrPABTAAAAAA==.Chijo:BAAALAAECggIDAAAAA==.Chimäraa:BAABLAAECoEWAAIdAAcIxh1iPQA2AgAdAAcIxh1iPQA2AgAAAA==.Chirouge:BAAALAADCggICAABLAAECggIFwADAAoZAA==.Chrissmith:BAAALAADCgIIAgABLAADCgYIBgAFAAAAAA==.',Ci='Cimmerias:BAAALAADCgcICgABLAADCgcICgAFAAAAAA==.',Co='Condrassil:BAABLAAECoERAAIdAAYI9hU0ZQC1AQAdAAYI9hU0ZQC1AQAAAA==.',Cp='Cptn:BAAALAAECgIIAgAAAA==.',Cr='Crilon:BAABLAAECoEUAAIeAAYIXgdkDQAcAQAeAAYIXgdkDQAcAQAAAA==.Crispyrogue:BAABLAAECoEZAAIfAAcIFhz1EgDqAQAfAAcIFhz1EgDqAQABLAAFFAUIFQAgAG0iAA==.Crispyy:BAABLAAECoEVAAIVAAcIvR95BgCTAgAVAAcIvR95BgCTAgABLAAFFAUIFQAgAG0iAA==.Crîtdk:BAAALAADCgIIAgABLAAECgUICAAFAAAAAA==.',Cu='Cugath:BAABLAAECoEgAAIUAAgIMxl5LwBKAgAUAAgIMxl5LwBKAgAAAA==.Cuia:BAABLAAECoEVAAILAAYIFSMhIgBOAgALAAYIFSMhIgBOAgABLAAFFAQICwAQAAEhAA==.',['Cé']='Cécílíá:BAAALAAECggICAAAAA==.',Da='Daena:BAAALAADCgQIBAABLAAECggIHQACAMYXAA==.Daganzandre:BAAALAADCgcIBwAAAA==.Daislon:BAAALAAECgQICgAAAA==.Daléron:BAAALAADCgcIBwAAAA==.Danig:BAAALAAECgEIAQAAAA==.Dannyywhy:BAAALAAECgUIBQAAAA==.Dannyywhyy:BAAALAAECgYIBgAAAA==.Darkleaf:BAAALAAECgYIDQAAAA==.Darkmon:BAAALAADCgYICgAAAA==.Darksideofme:BAABLAAECoEWAAMRAAYIuQ19ewBSAQARAAYIuQ19ewBSAQAXAAEIiwU+QAAqAAAAAA==.Daywin:BAAALAADCggICAAAAA==.Daènerys:BAABLAAECoElAAMPAAgI5RRBcwCYAQAPAAcI5RZBcwCYAQAQAAgIrQ0lUQBYAQAAAA==.',De='Deadschami:BAAALAADCgcIDAAAAA==.Decay:BAABLAAECoEjAAQhAAgIuiMOAwA7AwAhAAgIKyMOAwA7AwAKAAcIEx90TwArAgAgAAMICRqvOQDeAAAAAA==.Dekathlon:BAAALAAECgYIBgAAAA==.Demonsteaks:BAAALAAECgMIAwAAAA==.Demontar:BAAALAADCgEIAQAAAA==.Denrîa:BAAALAADCgUIBQAAAA==.Desmonica:BAABLAAECoEhAAMJAAcIkxm2EwANAgAJAAcIkxm2EwANAgAbAAEIIwjsXAApAAAAAA==.Desura:BAACLAAFFIESAAIWAAQIdSF5CQCFAQAWAAQIdSF5CQCFAQAsAAQKgTUAAhYACAgRJhcDAHQDABYACAgRJhcDAHQDAAAA.',Dh='Dhofc:BAAALAADCgcIDwAAAA==.',Di='Dianaria:BAAALAADCgcIDQAAAA==.Dieschöne:BAAALAADCgcIBwAAAA==.Dintalath:BAAALAAECgYIEAAAAA==.Dionysós:BAAALAAECgYIEAAAAA==.',Dk='Dkayofc:BAABLAAECoENAAIKAAYIaRqYngCLAQAKAAYIaRqYngCLAQAAAA==.',Do='Dobbymobby:BAAALAADCgEIAQAAAA==.Dodiri:BAAALAAECgEIAQAAAA==.Dohan:BAAALAAECgMIBAAAAA==.Doncochones:BAAALAADCgYIDAAAAA==.Doneras:BAABLAAECoEdAAMHAAcItAxHmgCJAQAHAAcItAxHmgCJAQAiAAMI5gSTXABuAAAAAA==.Donroeschen:BAABLAAECoEtAAQWAAgIrSNPEQDxAgAWAAgIMiNPEQDxAgADAAEIOxAjDQEyAAAVAAEIYyUAAAAAAAAAAA==.Dontel:BAAALAAECggIEAABLAAECggIGwAbAJEaAA==.Doublejump:BAAALAAECgYICgAAAA==.',Dr='Drachenesel:BAAALAAECgIIAgAAAA==.Draknor:BAAALAAECgIIAgAAAA==.Dranoi:BAACLAAFFIESAAIUAAQICCOGCQCCAQAUAAQICCOGCQCCAQAsAAQKgTUAAhQACAguJmYFAGADABQACAguJmYFAGADAAAA.Dranolide:BAAALAAECggICAAAAA==.Drogol:BAABLAAECoEWAAQEAAYIfBKbMQCGAQAEAAYIfBKbMQCGAQARAAQIQAk2qQDIAAAXAAEIPAj1PgAwAAAAAA==.Druie:BAAALAAECgMIBQAAAA==.',Du='Dudú:BAAALAAECgQIBgAAAA==.Dunras:BAAALAAFFAIIAgAAAA==.',Dw='Dwaladin:BAAALAAECgEIAQAAAA==.Dwonk:BAAALAADCggIDgAAAA==.',Dy='Dyorn:BAAALAAECgYIBgABLAAECggIJQAVACgZAA==.Dysthymia:BAAALAAECgcICAABLAAECggIIQALAAQkAA==.',Ed='Edga:BAABLAAECoEiAAIYAAgIsxtQFwB+AgAYAAgIsxtQFwB+AgAAAA==.',Eg='Eglath:BAABLAAECoEUAAIhAAYIBA4EJAAdAQAhAAYIBA4EJAAdAQAAAA==.',Ei='Eirmage:BAABLAAECoEYAAMdAAcIVhSUXwDFAQAdAAcIVhSUXwDFAQACAAQIfglnZACWAAABLAAFFAQIEgANAJklAA==.Eirpriest:BAACLAAFFIESAAMNAAQImSU1AACjAQANAAQImSU1AACjAQALAAEI8BnWMwBOAAAsAAQKgToABA0ACAjJJUwAAHADAA0ACAjJJUwAAHADAAwAAgjFFrJyAJcAAAsAAQjrJOGVAGcAAAAA.Eirshaman:BAAALAAFFAIIAgABLAAFFAQIEgANAJklAA==.Eisenengel:BAAALAADCgQIBAAAAA==.',El='Eldiablo:BAAALAADCgIIAgAAAA==.Elinia:BAABLAAECoEnAAMEAAgIdSLrBAAGAwAEAAgIdSLrBAAGAwARAAIIog4zvQCDAAAAAA==.Ellesmára:BAABLAAECoEbAAIgAAcIfxkyFAAQAgAgAAcIfxkyFAAQAgAAAA==.Ellnora:BAAALAADCgUIBQAAAA==.Elorin:BAAALAAECggICAABLAAECggIHQACAMYXAA==.Elorà:BAABLAAECoEOAAQRAAcIixHehwAzAQARAAYI5A3ehwAzAQAEAAMITQzuZACsAAAXAAEIFh6GMQBYAAAAAA==.Elunara:BAAALAADCgcIBwAAAA==.',Em='Emerellé:BAABLAAECoEZAAIYAAcIlxf9NgDQAQAYAAcIlxf9NgDQAQAAAA==.Emilari:BAABLAAECoEnAAIUAAgIYiBPEwD5AgAUAAgIYiBPEwD5AgABLAAECggINQAUAEEjAA==.',En='Endo:BAAALAAECgYIBgABLAAFFAQIDgAgAK0cAA==.Endô:BAACLAAFFIEOAAMgAAQIrRzPCQC0AAAgAAIIkBfPCQC0AAAKAAQIrRzoKgCsAAAsAAQKgTgAAwoACAjRJQQFAGQDAAoACAjRJQQFAGQDACAAAwgsJlcuADcBAAAA.Eniales:BAACLAAFFIEVAAMgAAUIbSIuAQCeAQAgAAQItCEuAQCeAQAKAAIIXCGqHwDKAAAsAAQKgTYAAyAACAjeJokCADsDACAACAgaJYkCADsDAAoACAj/HxUkAL4CAAAA.Enmâ:BAAALAAECgUICQABLAAFFAIICgARAHEeAA==.',Es='Essenzlemmiy:BAAALAADCgQIBAAAAA==.Estellia:BAAALAAECggICAAAAA==.',Eu='Eupi:BAABLAAECoEYAAIaAAcIvAygiwCBAQAaAAcIvAygiwCBAQAAAA==.',Ev='Evila:BAABLAAECoEiAAIZAAgIuQ/yPACSAQAZAAgIuQ/yPACSAQAAAA==.',Ex='Exalia:BAAALAAECggICAAAAA==.Exina:BAACLAAFFIEQAAMPAAUItSDeBwCZAQAPAAQIbyDeBwCZAQAQAAQIfCDYBgBjAQAsAAQKgSMAAw8ACAiEJd0HAEEDAA8ACAhpJd0HAEEDABAACAjbIaQQANACAAAA.',Fa='Fairytaley:BAAALAADCggICAAAAA==.',Fe='Federkleid:BAAALAAECgIIAgAAAA==.Fengschwie:BAAALAAECgQIDAAAAA==.Feride:BAABLAAFFIEJAAIjAAUIrB5yAwDpAQAjAAUIrB5yAwDpAQAAAA==.',Fi='Fioná:BAAALAAFFAIIAgAAAA==.',Fr='Freakman:BAAALAAECggICAAAAA==.Freyda:BAAALAAECgQIBgAAAA==.Frickeline:BAAALAAECgUIBQABLAAECggIHQACAMYXAA==.Friede:BAABLAAECoEVAAMiAAcIESFtGgAQAgAiAAcIESFtGgAQAgAHAAMImBPkEgGIAAAAAA==.Frob:BAABLAAECoEUAAIDAAcITCGtGwCJAgADAAcITCGtGwCJAgAAAA==.Frostyflakes:BAABLAAECoEVAAICAAYIiA17QABIAQACAAYIiA17QABIAQAAAA==.',Fu='Fujo:BAAALAAECggIDgAAAA==.Funky:BAAALAAECggIBAAAAA==.',Ga='Gaael:BAAALAAECgYIEQAAAA==.Galarian:BAACLAAFFIELAAIQAAQIASETBgB/AQAQAAQIASETBgB/AQAsAAQKgTUAAhAACAiBJt8BAGgDABAACAiBJt8BAGgDAAAA.Galbu:BAAALAAECgIIAwAAAA==.Garthel:BAAALAADCgYIBgABLAAFFAQIBgAFAAAAAQ==.Gavril:BAAALAAECgUIDgAAAA==.',Ge='Genedk:BAAALAAECggIDgAAAA==.Genetík:BAAALAADCgcIBwAAAA==.',Gh='Ghorgoth:BAAALAADCgMIAwAAAA==.',Gi='Gimmbly:BAAALAAECgUICAAAAA==.Gizmooh:BAAALAAECgcIDgAAAA==.',Gl='Glexina:BAAALAAECgYICAAAAA==.',Go='Goldregen:BAACLAAFFIEIAAILAAMIMAWuFQDFAAALAAMIMAWuFQDFAAAsAAQKgS0AAgsACAhEG3YjAEYCAAsACAhEG3YjAEYCAAAA.Gormli:BAAALAADCgYIBgAAAA==.Gorogh:BAACLAAFFIEGAAIHAAIIKyDIGQC8AAAHAAIIKyDIGQC8AAAsAAQKgSYAAgcACAhSIaUYAPgCAAcACAhSIaUYAPgCAAAA.',Gr='Grasysigirl:BAAALAAECgYIDAAAAA==.Grawndor:BAAALAADCgEIAgAAAA==.Gregpipe:BAAALAAECgYIEQAAAA==.Gregspipe:BAABLAAECoEUAAIdAAYIax1xXQDMAQAdAAYIax1xXQDMAQAAAA==.Gretelchen:BAACLAAFFIEHAAMfAAQI/wwYDwCOAAAfAAIIiQkYDwCOAAASAAIIdRCuHgAyAAAsAAQKgSQAAx8ACAgCIqUNADQCAB8ABwj3H6UNADQCABIABAjTIps6AF0BAAAA.Gronu:BAAALAAECggICgAAAA==.',Gu='Guglhupfl:BAAALAAECgMIBAAAAA==.Gungrâve:BAAALAADCgMIAwAAAA==.',Gy='Gyzana:BAAALAAECgYIEwAAAA==.',['Gú']='Gúts:BAAALAADCgYIBgABLAAECggICAAFAAAAAA==.',Ha='Hadéz:BAABLAAECoEgAAMkAAcIjyCQCgCGAgAkAAcIjyCQCgCGAgAYAAEIGAh3wAAlAAAAAA==.Hagon:BAAALAAECggICgAAAA==.Halandor:BAAALAAECgcICQAAAA==.Halx:BAAALAAECgYICgAAAA==.Harbard:BAABLAAECoEdAAMCAAgIxhcaGgAlAgACAAgIxhcaGgAlAgAdAAEIMQ1J3QA5AAAAAA==.Hatsumí:BAAALAAECgcIEQAAAA==.Hazzard:BAAALAAECgIIAgAAAA==.',He='Heilboy:BAAALAAECgMIAwAAAA==.Heimdallr:BAAALAADCggICAABLAAECgcIIAAkAI8gAA==.Heinoleinche:BAAALAAECgQIBgAAAA==.Heinrich:BAAALAADCgcIBwAAAA==.Henno:BAAALAAECgQICQAAAA==.Hetja:BAABLAAECoEcAAIPAAgIYAetrgAiAQAPAAgIYAetrgAiAQAAAA==.Hetneoder:BAAALAAECgIIAgAAAA==.',Ho='Hochwürgen:BAAALAAECggIBgAAAA==.Hogherr:BAAALAADCggICAABLAAECggIFwADAAoZAA==.Holyreq:BAABLAAECoEeAAIiAAgItxmnDwB1AgAiAAgItxmnDwB1AgAAAA==.',Hu='Hunterofc:BAAALAAECgYIDgAAAA==.',['Hò']='Hòrùs:BAABLAAECoEeAAIPAAYInQ32pAA1AQAPAAYInQ32pAA1AQAAAA==.',['Hø']='Høudini:BAAALAADCgUIBQAAAA==.',['Hú']='Húnter:BAAALAAECggICQAAAA==.',Id='Id:BAAALAADCggICAAAAA==.',Ig='Igneél:BAAALAADCgEIAQAAAA==.',Im='Imaní:BAABLAAECoEaAAMbAAgIjyE6DgCXAgAbAAgIhyE6DgCXAgAcAAYINh+rEAAkAgABLAAFFAIIAgAFAAAAAA==.Immortuos:BAAALAAECgYIBgAAAA==.Imøgen:BAAALAADCgYIBgABLAAECgcIFwAKAEIgAA==.',In='Innervateboy:BAACLAAFFIESAAIZAAQI1h7HBgBdAQAZAAQI1h7HBgBdAQAsAAQKgTUAAxkACAgLJgsEAFkDABkACAgLJgsEAFkDAAgABAgpEzkgAL8AAAAA.',Ip='Ipati:BAABLAAECoEeAAIHAAcI2hoBWgAKAgAHAAcI2hoBWgAKAgAAAA==.Ipoxoql:BAABLAAECoEeAAMCAAgI7BIKHwD+AQACAAgI7BIKHwD+AQAdAAUIjAjsqQDqAAAAAA==.',Iq='Iq:BAAALAADCggICAABLAAECggIIgAcAAofAA==.',Ir='Irispallida:BAAALAAECgYIEgAAAA==.Irokan:BAABLAAECoEZAAIaAAgIXhteLwB6AgAaAAgIXhteLwB6AgAAAA==.Irîna:BAABLAAECoEUAAMNAAYIayO1BABkAgANAAYIayO1BABkAgAMAAMIwxAgbwCrAAAAAA==.',Is='Isaria:BAACLAAFFIEIAAICAAIIYhVjCwCXAAACAAIIYhVjCwCXAAAsAAQKgTQAAgIACAhgIhsLAM4CAAIACAhgIhsLAM4CAAAA.Isaymoomoo:BAAALAAECgMIAwABLAAECgYICgAFAAAAAA==.Islanzadía:BAAALAADCgIIAgAAAA==.',It='Itzamná:BAAALAAECgQIBQAAAA==.',Iv='Ivaldi:BAAALAAECgEIAQABLAAECggIHQACAMYXAA==.',Ja='Jamamiro:BAAALAADCgUIBQAAAA==.Jan:BAABLAAECoEtAAIKAAgIaBtOPQBfAgAKAAgIaBtOPQBfAgAAAA==.Jansy:BAAALAAECggIBQAAAA==.Jasonbourne:BAAALAAECggICAAAAA==.Jaydeekay:BAAALAAECgcIBwAAAA==.Jaydeerogue:BAAALAADCgYIBgAAAA==.',Je='Jeeper:BAABLAAECoEgAAIKAAgI4yFKFAALAwAKAAgI4yFKFAALAwAAAA==.Jeeze:BAABLAAECoEfAAIDAAcI+RSPXQCgAQADAAcI+RSPXQCgAQAAAA==.Jensky:BAABLAAECoEVAAIYAAYICiTxGQBrAgAYAAYICiTxGQBrAgAAAA==.Jexî:BAAALAADCgYIBgAAAA==.',Ji='Jinah:BAAALAADCgcIBwAAAA==.Jioras:BAAALAADCgIIAgAAAA==.',Jo='Jolnack:BAAALAADCggIDwAAAA==.Jonesie:BAAALAADCgMIAwAAAA==.',['Jä']='Jägermaster:BAAALAAECggICgAAAA==.',Ka='Kaidô:BAAALAAECgQICAABLAAFFAQIDgAgAK0cAA==.Kaliandra:BAAALAAECgYIDQAAAA==.Kanisha:BAAALAADCgYICwAAAA==.Kaoru:BAAALAAECgYIEQAAAA==.Karirio:BAAALAAECggIDwAAAA==.Karita:BAAALAAECgQIBAABLAAFFAQIBgAFAAAAAQ==.Kathleena:BAAALAAECgMIBAAAAA==.Katlystria:BAABLAAECoEdAAIXAAcICBpSCAAfAgAXAAcICBpSCAAfAgAAAA==.Katü:BAAALAADCggICAAAAA==.Kazmerps:BAAALAAECgcIBwAAAA==.Kazukamisamâ:BAACLAAFFIERAAIlAAUISRMRBACRAQAlAAUISRMRBACRAQAsAAQKgTYABCUACAjGJAIBAFcDACUACAjGJAIBAFcDACMABQgfFWA8ADQBAA4AAQisDzkWADsAAAAA.Kazuro:BAAALAADCggIEAAAAA==.',Ke='Keluna:BAAALAADCgYIBgAAAA==.Kelyth:BAAALAADCggIDgAAAA==.Kenny:BAAALAAECgMICQAAAA==.Keolanya:BAAALAAECgYIEwAAAA==.Keolina:BAAALAAECgYIDgAAAA==.Kerby:BAACLAAFFIEOAAMZAAQIER0vCQAKAQAZAAQIER0vCQAKAQAkAAIINgTSDQBoAAAsAAQKgTUAAxkACAiMJnkBAH8DABkACAiMJnkBAH8DACQABwgpHbMTAPMBAAAA.',Ki='Kimzy:BAAALAADCggICAAAAA==.Kiralin:BAAALAADCgUIBQABLAADCggIFAAFAAAAAA==.Kiralîn:BAAALAADCggIBAABLAADCggIFAAFAAAAAA==.Kitamia:BAAALAADCgcIBwABLAAFFAQIEgARAKMgAA==.Kitâmia:BAACLAAFFIESAAIRAAQIoyAfDgCKAQARAAQIoyAfDgCKAQAsAAQKgTYABBEACAjVI8sJADsDABEACAjVI8sJADsDAAQAAgidDqJ3AGIAABcAAQh5B0s9ADUAAAAA.',Kn='Knetdolch:BAAALAADCgcIBQAAAA==.',Ko='Koester:BAAALAADCgcIBwAAAA==.Koihime:BAAALAAFFAQIBgAAAQ==.Korash:BAAALAAECgYIDAABLAAFFAYIFgAHAN8kAA==.Korashdk:BAACLAAFFIELAAMKAAMIKiUQDwBAAQAKAAMIKiUQDwBAAQAgAAII6h1aCgCwAAAsAAQKgScAAwoACAhdJvoBAH8DAAoACAhdJvoBAH8DACAABwhlIsANAGICAAEsAAUUBggWAAcA3yQA.Korashpal:BAACLAAFFIEWAAIHAAYI3yRhAACeAgAHAAYI3yRhAACeAgAsAAQKgTAAAgcACAjhJuECAH4DAAcACAjhJuECAH4DAAAA.Kori:BAAALAADCggIEAAAAA==.Koriantha:BAAALAADCggICgAAAA==.Korius:BAAALAAECgQIBAAAAA==.',Kr='Kratôs:BAAALAAECgEIAQAAAA==.Kraven:BAAALAAECgMIBgAAAA==.Krelian:BAAALAAECgcICwAAAA==.Kripke:BAAALAAECgUIBwABLAAFFAQIBgAFAAAAAQ==.Krossel:BAAALAADCggIJQAAAA==.Kruegar:BAABLAAECoEgAAICAAYIKw7PRAA3AQACAAYIKw7PRAA3AQAAAA==.Kruege:BAAALAADCggICAABLAAECgYIIAACACsOAA==.',Ku='Kuorne:BAAALAADCggICAAAAA==.',Ky='Kyrak:BAAALAAECgYICwAAAA==.Kyrax:BAABLAAECoEhAAIPAAcIthvJRAARAgAPAAcIthvJRAARAgAAAA==.Kyrân:BAAALAADCggICAAAAA==.',['Kà']='Kàsh:BAAALAAECgUIBQAAAA==.',['Kü']='Kücükenistee:BAAALAAECgYIEwAAAA==.',La='Lahzakos:BAAALAAECgUIBQAAAA==.Lamaentchen:BAAALAAECgMIBAAAAA==.Lanek:BAAALAAECggIEQAAAA==.Lapadro:BAAALAADCgYIBgAAAA==.',Le='Leichenwagen:BAAALAAECgYICAAAAA==.Lenti:BAAALAADCgUIBQAAAA==.Leonpardonk:BAACLAAFFIESAAIJAAQILw6MBQAtAQAJAAQILw6MBQAtAQAsAAQKgTgAAwkACAjTG2kNAGoCAAkACAjTG2kNAGoCABwAAgiHBnM/ADsAAAAA.Lesnar:BAAALAADCgcIEgAAAA==.Lexer:BAAALAADCgMIAwABLAAFFAUIDgAKAHoUAA==.',Li='Lightdo:BAAALAAECggIDgABLAAFFAQIDgAgAK0cAA==.Lillit:BAAALAAECgIIAgAAAA==.Limetté:BAAALAAECgEIAQAAAA==.Littlelight:BAABLAAECoEfAAIHAAcIzwxLoAB+AQAHAAcIzwxLoAB+AQAAAA==.',Lo='Loniel:BAAALAAECgMIAwABLAAECggIFAADAEwhAA==.Loui:BAAALAAECgMIBgAAAA==.',Lu='Lucantara:BAAALAAECggICAAAAA==.Lunaticc:BAAALAADCggICAAAAA==.Luzifon:BAABLAAECoEkAAITAAgIdRDwKwCqAQATAAgIdRDwKwCqAQAAAA==.',Ly='Lya:BAABLAAECoEbAAIMAAYIySB0JAA1AgAMAAYIySB0JAA1AgAAAA==.',['Lé']='Léø:BAAALAADCgMIAwAAAA==.',['Lø']='Løoki:BAAALAADCgYIBgAAAA==.',['Lú']='Lúx:BAAALAADCggICAAAAA==.',Ma='Maccon:BAABLAAECoEbAAIZAAcIkB0UHQBNAgAZAAcIkB0UHQBNAgAAAA==.Madras:BAABLAAECoEaAAMHAAgI1QWE8ADeAAAHAAgIdASE8ADeAAAmAAEIRwyRXwAyAAAAAA==.Mafidk:BAAALAADCggIFgABLAAECgYICgAFAAAAAA==.Mafî:BAAALAADCggIAwABLAAECgYICgAFAAAAAA==.Mageofc:BAAALAADCggIEAAAAA==.Magono:BAAALAADCgIIAgAAAA==.Maikj:BAAALAADCgYIBgAAAA==.Mailín:BAABLAAECoEiAAIDAAgI5BVOWQCsAQADAAgI5BVOWQCsAQAAAA==.Majlena:BAAALAAECggIBQAAAA==.Manajunkî:BAAALAADCgYIBgAAAA==.',Me='Melanna:BAAALAADCgcIGgAAAA==.Melficepimp:BAAALAAECgQIBAAAAA==.Melonno:BAABLAAECoEVAAIaAAYIJQUJzgDzAAAaAAYIJQUJzgDzAAAAAA==.Melonnopries:BAAALAADCggIDQAAAA==.Meredias:BAAALAADCggIGAABLAAECgMIBAAFAAAAAA==.Merkato:BAACLAAFFIEKAAIiAAUINRIFBQCUAQAiAAUINRIFBQCUAQAsAAQKgR0AAiIACAgcHDUNAI8CACIACAgcHDUNAI8CAAAA.Metis:BAAALAADCgYIBgABLAAECgQIAwAFAAAAAA==.',Mi='Midar:BAABLAAECoEfAAIZAAgIZiAcDAD3AgAZAAgIZiAcDAD3AgAAAA==.Mika:BAAALAAECgYIBgABLAAECggIHwAZAGYgAA==.Miktas:BAAALAADCgcIDQABLAAECgMIBAAFAAAAAA==.Milunà:BAAALAADCggICAAAAA==.Mindraz:BAAALAAECgIIAgAAAA==.Misfire:BAABLAAECoEUAAMPAAcI6CG2IwCUAgAPAAcI6CG2IwCUAgAGAAMIzBkEFwDcAAAAAA==.Miágona:BAABLAAECoEdAAQLAAYIBhYWRwCUAQALAAYIBhYWRwCUAQAMAAUIsAdsZgDgAAANAAEIARqJLQBMAAAAAA==.',Mo='Mobbi:BAAALAAECgMIAwAAAA==.Mondscheîn:BAABLAAECoEsAAIJAAgIyReBDwBKAgAJAAgIyReBDwBKAgAAAA==.Morgâna:BAAALAAECgYIEgAAAA==.Mornië:BAAALAADCggICAAAAA==.Moti:BAACLAAFFIEVAAIMAAcIPRvYAACZAgAMAAcIPRvYAACZAgAsAAQKgR8AAwwACAhiJMsNAPYCAAwACAhiJMsNAPYCAAsABgiVBoiAAMcAAAAA.Mousy:BAABLAAECoEbAAIPAAYIPiHUQAAeAgAPAAYIPiHUQAAeAgAAAA==.',Mu='Muhfasa:BAAALAADCgQIBAAAAA==.Murdogg:BAAALAAECgIIAgAAAA==.',['Mâ']='Mâmmôn:BAACLAAFFIEIAAIKAAIIhQTIXAB8AAAKAAIIhQTIXAB8AAAsAAQKgTEAAgoACAhHGDJLADYCAAoACAhHGDJLADYCAAAA.',['Mä']='Mägni:BAABLAAECoEVAAIWAAYI2hhiQgDPAQAWAAYI2hhiQgDPAQAAAA==.',['Mé']='Médíc:BAAALAAECgYIEAAAAA==.',['Mê']='Mêppo:BAAALAAECgYIEgAAAA==.',['Mí']='Mínasu:BAAALAAECgYIBgABLAAECggIJwAJAHoVAA==.',['Mö']='Möller:BAABLAAFFIEGAAMgAAII3Bx6BwDJAAAgAAII3Bx6BwDJAAAhAAEIughFEQA6AAAAAA==.Möw:BAABLAAECoEXAAIaAAgIsB5OLACHAgAaAAgIsB5OLACHAgABLAAFFAcIFQAaAIUXAA==.Möwe:BAACLAAFFIEVAAIaAAcIhRcCAwBEAgAaAAcIhRcCAwBEAgAsAAQKgSwAAhoACAi0JkEFAGUDABoACAi0JkEFAGUDAAAA.',Na='Nalnig:BAAALAAECgUIBwAAAA==.Namo:BAACLAAFFIEGAAIDAAIIyxKlLwB9AAADAAIIyxKlLwB9AAAsAAQKgSEAAwMACAiXH6EUALQCAAMACAiXH6EUALQCABYABQiLBrGCAN0AAAAA.Naroschima:BAABLAAECoEUAAIDAAcIjiDIJwBPAgADAAcIjiDIJwBPAgAAAA==.Nashoba:BAABLAAECoEXAAMDAAgIChkGKQBKAgADAAgIChkGKQBKAgAWAAUIChIegADrAAAAAA==.Nataku:BAABLAAECoEcAAIGAAYIPRNwDgCUAQAGAAYIPRNwDgCUAQAAAA==.Naunet:BAABLAAECoEiAAIJAAcIZxD1IABvAQAJAAcIZxD1IABvAQAAAA==.Nayela:BAAALAAECgYIDQAAAA==.Nazguul:BAAALAADCgYICwABLAAECgcICAAFAAAAAA==.',Ne='Neevi:BAACLAAFFIELAAMPAAQICh4vDQApAQAPAAQICh4vDQApAQAQAAEIvwClMQAjAAAsAAQKgS8AAg8ACAg6Jl4GAE0DAA8ACAg6Jl4GAE0DAAAA.Neischa:BAACLAAFFIEFAAIhAAIIjRfiCQCTAAAhAAIIjRfiCQCTAAAsAAQKgSkAAiEACAi2IEQGAOgCACEACAi2IEQGAOgCAAEsAAUUBAgSABkA1h4A.Nerîen:BAACLAAFFIEFAAMgAAMIqxK9CwCoAAAgAAIIvA69CwCoAAAKAAII8BYDRACTAAAsAAQKgTQAAwoACAiQIz8cAOICAAoACAjDIj8cAOICACAAAwhgI44tADwBAAAA.Nesoy:BAAALAAECgYICwAAAA==.Nexrithar:BAAALAAECgYICwABLAAFFAIIBAAFAAAAAA==.Nexxo:BAAALAAECgcICAAAAA==.',Ni='Nilanjá:BAABLAAECoEXAAIPAAYIsA4YogA7AQAPAAYIsA4YogA7AQAAAA==.Nima:BAAALAAECgIIAgAAAA==.Nimmermehr:BAABLAAECoEWAAIPAAYIYyOrMgBRAgAPAAYIYyOrMgBRAgAAAA==.',No='Nofcksgiven:BAAALAADCgcIBwAAAA==.Nogrâd:BAAALAADCgcIDQABLAAECggIEAAFAAAAAA==.Noknok:BAAALAADCggIKwAAAA==.Nonamed:BAAALAADCgEIAQAAAA==.Noobyd:BAABLAAECoEfAAMnAAgIyxpnBgCCAgAnAAgIyxpnBgCCAgATAAIIyQjbcQBNAAAAAA==.Noom:BAAALAADCggICAAAAA==.Norge:BAAALAAECgMIBAAAAA==.Norsî:BAAALAAECgMIBAAAAA==.',Nr='Nroyb:BAAALAADCgcIBwAAAA==.',Nu='Numee:BAACLAAFFIEIAAIHAAII/hewIwCpAAAHAAII/hewIwCpAAAsAAQKgTQAAgcACAh5I2QRACADAAcACAh5I2QRACADAAAA.',Ny='Nylaná:BAAALAAECggICAABLAAECggILAAdACYdAA==.Nyssa:BAAALAADCggIFQABLAAECgcIIAAlACMeAA==.',['Ná']='Nádeshà:BAAALAAECgYICgAAAA==.',['Nâ']='Nârôn:BAACLAAFFIEIAAIWAAQIvxbNCgBTAQAWAAQIvxbNCgBTAQAsAAQKgR8AAhYACAiAIhQPAAUDABYACAiAIhQPAAUDAAAA.',['Nê']='Nêx:BAABLAAECoEWAAIPAAcIFRqKpgAyAQAPAAcIFRqKpgAyAQAAAA==.',['Ní']='Níní:BAAALAAECgYIEAAAAA==.',Ob='Oberstaber:BAAALAAECgUIBwAAAA==.',Oe='Oeten:BAAALAAECgYICwAAAA==.',Og='Ognom:BAAALAADCgYIBgAAAA==.',Ol='Olendo:BAAALAADCgUIBQAAAA==.',Om='Omegá:BAAALAADCgcICgAAAA==.',Or='Orelin:BAAALAADCgcIBwAAAA==.Orthanc:BAAALAAECgUIBQAAAA==.',Os='Oscara:BAAALAADCggIGAAAAA==.',Ow='Owly:BAAALAAECgMIBgAAAA==.',Pa='Pacum:BAAALAAECgYICwAAAA==.Padraig:BAAALAADCggIEwAAAA==.Paltor:BAAALAADCgcIDAAAAA==.Palá:BAAALAAECgMIBgAAAA==.Papalegba:BAAALAADCggIIgAAAA==.Paradisia:BAAALAAECgYICgABLAAECgcIIQAJAJMZAA==.Parinea:BAABLAAECoEoAAILAAgIAiHaEQDCAgALAAgIAiHaEQDCAgAAAA==.Pat:BAABLAAECoEWAAMNAAYIgRtnCgDbAQANAAYIgRtnCgDbAQALAAYI7g7aXQA/AQAAAA==.',Pe='Pelzcifer:BAAALAAECgIIAgAAAA==.Perathun:BAABLAAECoEXAAIPAAYIVArwrAAmAQAPAAYIVArwrAAmAQAAAA==.Petuny:BAAALAADCgUIBQAAAA==.',Ph='Phoenixx:BAAALAADCggICQABLAAECgYIEwAFAAAAAA==.Phyrra:BAAALAADCggIDQAAAA==.',Pi='Picklerick:BAAALAAECgUIBQAAAA==.Pilzfúß:BAAALAAECggICAAAAA==.Piron:BAAALAADCgcIBwAAAA==.Pittêy:BAAALAAECgIIAgAAAA==.Piølock:BAABLAAECoEgAAQRAAgI5haiNgAzAgARAAgI3BaiNgAzAgAXAAQIDQ8uHQDsAAAEAAII0wusewBTAAAAAA==.',Pl='Planyy:BAAALAADCgcIBwAAAA==.',Pr='Prinzpipi:BAAALAADCgYIBgAAAA==.',Ps='Psychôsocial:BAAALAADCgcIBwAAAA==.',Pu='Puhzilla:BAABLAAECoEdAAIbAAYIEhOzLQBmAQAbAAYIEhOzLQBmAQAAAA==.',['Pî']='Pîper:BAAALAAECgMICAAAAA==.Pîttey:BAAALAAECgMIBAAAAA==.',Qi='Qi:BAABLAAECoEiAAIcAAgICh+ZCQCkAgAcAAgICh+ZCQCkAgAAAA==.',Qu='Quallina:BAABLAAECoEbAAMHAAcInw5ZkgCXAQAHAAcI0A1ZkgCXAQAmAAYIeQ1bUwBmAAAAAA==.Quandorin:BAAALAADCgYIBgAAAA==.Quent:BAAALAAECgMIBAAAAA==.Qul:BAAALAADCgUIBQAAAA==.Quälerin:BAAALAAECgIIAwAAAA==.Quèénkloede:BAABLAAECoEkAAIHAAgIzCUtBQBrAwAHAAgIzCUtBQBrAwAAAA==.',['Qé']='Qéra:BAAALAAECgIIAgAAAA==.',Ra='Raagnaar:BAAALAAECgYIEAAAAA==.Rachla:BAAALAADCggIDAAAAA==.Radovin:BAAALAAECggICgAAAA==.Ragmar:BAAALAADCgcIBwAAAA==.Rainmaker:BAAALAADCggICAAAAA==.Ralasmafi:BAAALAAECgYICgAAAA==.Randor:BAAALAAECgQIDAAAAA==.Ranox:BAAALAAECggIDwAAAA==.',Re='Rec:BAAALAAECgMIAwAAAA==.Reinold:BAAALAADCggICAAAAA==.Resort:BAACLAAFFIEJAAIMAAQIIxPVCgAdAQAMAAQIIxPVCgAdAQAsAAQKgS0AAgwACAgGI/gOAOoCAAwACAgGI/gOAOoCAAAA.Revetha:BAAALAAECgQICQABLAAECgcIFwAKAEIgAA==.Revn:BAAALAAFFAIIBAABLAAFFAMIBQAKAKQYAA==.',Rh='Rhayn:BAAALAADCgcICQABLAAECgIIAgAFAAAAAA==.',Ri='Ribblor:BAAALAAECgYICAAAAA==.Rickyspanish:BAAALAAECgYIDAABLAAECggIHgAPAL4aAA==.Ridu:BAAALAADCgMIAwAAAA==.Rina:BAAALAAECgQIBAAAAA==.',Ro='Roal:BAABLAAECoEaAAIQAAgIJh4BFgCgAgAQAAgIJh4BFgCgAgAAAA==.Rodnay:BAABLAAECoEgAAMmAAgIzh3mCwCQAgAmAAgIzh3mCwCQAgAHAAYIhQlY4AAFAQAAAA==.Roguedrian:BAABLAAECoEdAAISAAgIYxBMHwAHAgASAAgIYxBMHwAHAgAAAA==.Rotschwinge:BAAALAADCggICAABLAAECgQIBAAFAAAAAA==.',['Rá']='Rázia:BAAALAADCggICAAAAA==.',Sa='Sabbersimon:BAAALAAECgcIBwABLAAECgcIIAAkAI8gAA==.Saedelaere:BAAALAADCggICAAAAA==.Salazâr:BAAALAADCgIIAgAAAA==.Saldrias:BAAALAAECgMIAwABLAAECgcICAAFAAAAAA==.Samra:BAAALAADCgYICQAAAA==.Sandaîme:BAAALAAECgYIEgAAAA==.Sansoga:BAAALAAECgYIDgAAAA==.Sansogogo:BAAALAADCgcIBwAAAA==.Sartaríus:BAAALAAECgMIBgAAAA==.Sathanael:BAABLAAECoEhAAMKAAcIiBNWwQBSAQAKAAYI7RBWwQBSAQAgAAQIcxX5PADDAAAAAA==.Saurfang:BAAALAADCggICAAAAA==.Sayorí:BAAALAAECgYIEwAAAA==.',Sc='Scantrax:BAACLAAFFIEIAAIHAAUIVxfrBQC3AQAHAAUIVxfrBQC3AQAsAAQKgSYAAgcACAg+JQoLAEUDAAcACAg+JQoLAEUDAAAA.Schadoprist:BAAALAAECgEIAQAAAA==.Schnukelchen:BAAALAAECggIDQAAAA==.Schádow:BAABLAAECoEXAAMCAAcIMQ7qOQBkAQACAAYIIxDqOQBkAQAdAAcI8wT2mAAlAQAAAA==.',Se='Sephîra:BAACLAAFFIEFAAIZAAMIKRFJCwDmAAAZAAMIKRFJCwDmAAAsAAQKgSIAAhkACAiEIroLAPsCABkACAiEIroLAPsCAAAA.Sethur:BAAALAADCggIEAAAAA==.Sevra:BAAALAAECgMIAwABLAAECggIFAADAEwhAA==.',Sh='Shadowahn:BAAALAADCggIEAAAAA==.Shalíen:BAAALAADCgcIDAAAAA==.Shamigaael:BAAALAAECgYICAAAAA==.Shamxter:BAAALAADCggIDwABLAAECggICAAFAAAAAA==.Shanaya:BAAALAAECggICAAAAA==.Shaolin:BAACLAAFFIEKAAIfAAIIYhuKCQC0AAAfAAIIYhuKCQC0AAAsAAQKgSIAAx8ABwhBIKIIAJcCAB8ABwhBIKIIAJcCABIABgiPIeMiAO0BAAEsAAUUAwgJAAoAIhgA.Shaox:BAACLAAFFIEJAAIKAAMIIhhgHQDUAAAKAAMIIhhgHQDUAAAsAAQKgScAAgoACAjOI8gUAAgDAAoACAjOI8gUAAgDAAAA.Shatin:BAABLAAECoErAAIaAAgIvR9uIgC4AgAaAAgIvR9uIgC4AgAAAA==.Shayi:BAABLAAECoEUAAMDAAYIcw3cnwADAQADAAYIcw3cnwADAQAWAAUIdQYzgQDlAAAAAA==.Shinoakuma:BAABLAAECoEiAAIhAAgI+hmeEQABAgAhAAgI+hmeEQABAgAAAA==.Shirox:BAAALAAECgYIDAAAAA==.Shìrø:BAAALAAFFAIIBAAAAA==.Shírox:BAAALAADCggICAAAAA==.Shîrøx:BAAALAAFFAIIBAAAAA==.',Si='Siiene:BAAALAAECgMIBQAAAA==.Sikudhani:BAACLAAFFIEJAAIPAAQIQBPKEQDwAAAPAAQIQBPKEQDwAAAsAAQKgTMAAg8ACAjFI8IYANECAA8ACAjFI8IYANECAAAA.Sikudhanius:BAAALAADCgEIAQAAAA==.Silax:BAABLAAECoEZAAISAAcIVRb4IQD0AQASAAcIVRb4IQD0AQAAAA==.Simiie:BAACLAAFFIESAAMHAAQIERpwCABcAQAHAAQIERpwCABcAQAiAAMI3AIAAAAAAAAsAAQKgTUAAwcACAjDI/oNADMDAAcACAjDI/oNADMDACIACAiHBgAAAAAAAAAA.',Sk='Skearo:BAAALAAECgIIAgABLAAECgcIFAAdAOAdAA==.',Sl='Slo:BAABLAAECoEUAAILAAYI8AhPbgAKAQALAAYI8AhPbgAKAQAAAA==.',Sm='Smashsuu:BAACLAAFFIEHAAITAAMIgg3ECwC7AAATAAMIgg3ECwC7AAAsAAQKgSgAAhMACAgKGwgVAF4CABMACAgKGwgVAF4CAAAA.Smôkey:BAAALAADCgEIAQABLAAECgYICgAFAAAAAA==.',Sn='Snackfist:BAAALAAECgEIAQAAAA==.Snowflame:BAAALAAECgYIDAABLAAECgcIIAAlACMeAA==.',So='Soulreâver:BAAALAAECgYIEAAAAA==.Southpark:BAAALAAECgYIBgAAAA==.',St='Stace:BAAALAADCgYIBwAAAA==.Stallknecht:BAAALAAECggICwAAAA==.Starmönch:BAAALAAECgYICQAAAA==.Steppenhund:BAABLAAECoESAAIQAAYIIAkVbgD2AAAQAAYIIAkVbgD2AAAAAA==.Sternwind:BAAALAAECgYIDAAAAA==.Stumpi:BAAALAAECggICgAAAA==.',Su='Suro:BAAALAADCgcIBwAAAA==.Suì:BAAALAADCgYIEQAAAA==.',Sy='Synturia:BAAALAADCggIKwAAAA==.',['Sâ']='Sâlixx:BAABLAAECoEZAAIjAAgI9Q0qLACeAQAjAAgI9Q0qLACeAQAAAA==.Sânâ:BAAALAAECgQIBgABLAAFFAQIBgAFAAAAAQ==.',['Sí']='Sívo:BAAALAADCgcIBwAAAA==.',['Sî']='Sîvan:BAAALAAECgcIDwAAAA==.',['Sø']='Søphíá:BAAALAADCgMIAwAAAA==.',['Sý']='Sýlvanas:BAAALAADCggICAAAAA==.',Ta='Taleyra:BAAALAADCggICAABLAAECgIIAgAFAAAAAA==.Taurîn:BAAALAADCggIEgAAAA==.',Te='Teddy:BAAALAADCgYIDQAAAA==.Telnamir:BAAALAAECgYIEAAAAA==.Temptation:BAAALAAECgEIAQAAAA==.Temári:BAAALAADCggICAAAAA==.Tentagon:BAABLAAECoEbAAIYAAcIExnRXwA1AQAYAAcIExnRXwA1AQAAAA==.Terraria:BAACLAAFFIESAAIJAAQI9B8cBACEAQAJAAQI9B8cBACEAQAsAAQKgTUAAgkACAhQJLYDAB0DAAkACAhQJLYDAB0DAAAA.Terrodar:BAACLAAFFIEQAAMSAAUIpRkTBABzAQASAAQIZBcTBABzAQAfAAIIKxS0CwCgAAAsAAQKgSsAAxIACAjVI0MGABIDABIACAhVI0MGABIDAB8ACAgpHm4IAJoCAAAA.Tetrapackk:BAAALAADCgYIBwAAAA==.',Th='Thalgrimm:BAAALAAECgMIBwAAAA==.Thaloria:BAAALAAECgYICwABLAAECgcIIQAJAJMZAA==.Thalorianni:BAAALAAECgYICQABLAAECgcIIQAJAJMZAA==.Tharon:BAABLAAECoEXAAIKAAcIQiAFMwCBAgAKAAcIQiAFMwCBAgAAAA==.Thorent:BAAALAADCggICAABLAAFFAMIBQAZACkRAA==.Thorvie:BAABLAAECoEZAAIHAAcIvwuhyAA2AQAHAAcIvwuhyAA2AQAAAA==.Thorêx:BAAALAADCggIFAAAAA==.Thrymur:BAAALAADCgYIEAABLAAECgcIGwAgAH8ZAA==.Thráìn:BAABLAAECoEsAAIhAAgI8CMhBAAfAwAhAAgI8CMhBAAfAwAAAA==.Thurna:BAAALAAECgYIDQAAAA==.Thyphòón:BAAALAAECgYIDwABLAAECggIIgAPAH8cAA==.Thánâtos:BAAALAAECgQIBAAAAA==.',Ti='Tiane:BAAALAAECgYIEQABLAAFFAIIAgAFAAAAAA==.Tido:BAAALAAECgEIAQAAAA==.Tiirii:BAABLAAECoEWAAMgAAYIoSBcEAA9AgAgAAYIoSBcEAA9AgAhAAIIvxZ0NgBoAAAAAA==.Timasia:BAAALAAECgIIAgAAAA==.Tissaia:BAABLAAECoEbAAMdAAcIwAvUdwCBAQAdAAcIkQvUdwCBAQACAAMIbw1wZgCMAAAAAA==.',To='Todesrudini:BAAALAADCggICAAAAA==.Toukachi:BAACLAAFFIEIAAIJAAIIsR6OCgCxAAAJAAIIsR6OCgCxAAAsAAQKgTgAAwkACAgsIRoHANwCAAkACAgsIRoHANwCABwAAQi0EYBAADQAAAAA.',Tr='Trilo:BAAALAAECgIIAgAAAA==.Trockeneis:BAAALAADCggICAABLAAECggILQAWAK0jAA==.Tryx:BAAALAADCggICAABLAAFFAUIEAASAKUZAA==.',Ts='Tsunadè:BAABLAAECoEjAAILAAcI0x3WHQBrAgALAAcI0x3WHQBrAgAAAA==.',Tu='Tulakort:BAAALAAECgYICQABLAAECgcIFAATABUPAA==.Tulii:BAABLAAECoEUAAITAAcIFQ/5OABfAQATAAcIFQ/5OABfAQAAAA==.Turinturamba:BAACLAAFFIENAAILAAMIJgpSEwDVAAALAAMIJgpSEwDVAAAsAAQKgTMAAgsACAggFZcvAAMCAAsACAggFZcvAAMCAAAA.Turox:BAABLAAECoEfAAIPAAgIQCGsGQDLAgAPAAgIQCGsGQDLAgAAAA==.',Tw='Twice:BAAALAAECgYIDQAAAA==.',['Tâ']='Târâ:BAABLAAECoEfAAIYAAYIog3TcgD+AAAYAAYIog3TcgD+AAAAAA==.',['Tí']='Tínkabell:BAABLAAECoEaAAIYAAcIPR2uIgA2AgAYAAcIPR2uIgA2AgAAAA==.',['Tî']='Tîlda:BAAALAAECgEIAQAAAA==.',['Tó']='Tónks:BAABLAAECoEdAAIgAAcI6A9fHgCwAQAgAAcI6A9fHgCwAQAAAA==.',['Tö']='Tötedich:BAAALAADCggIEAAAAA==.',['Tü']='Tüüp:BAAALAAECgQIBAAAAA==.',Ul='Ulmen:BAAALAADCggIDgABLAAECggIFAADAEwhAA==.',Un='Unreality:BAAALAADCggICAAAAA==.',Ur='Urulóki:BAAALAADCgEIAQABLAAECggIFwADAAoZAA==.',Va='Vaghortar:BAAALAAECgUICgAAAA==.Valandriel:BAAALAAECgUIDQAAAA==.Valioná:BAAALAADCgUIBQAAAA==.Valy:BAAALAAECgYIBgABLAAECggIJQAVACgZAA==.',Vd='Vdh:BAAALAADCgUIBQAAAA==.',Ve='Veganiah:BAABLAAECoEUAAIZAAYIZxrrLwDTAQAZAAYIZxrrLwDTAQAAAA==.Venatras:BAABLAAECoEiAAIQAAgIxhUpMgDfAQAQAAgIxhUpMgDfAQAAAA==.',Vi='Vicjess:BAABLAAECoEZAAISAAYIUxr2JADfAQASAAYIUxr2JADfAQAAAA==.Viluna:BAAALAAECgEIAQAAAA==.Violanta:BAAALAAECgYIDgAAAA==.Virin:BAAALAADCggIDgABLAAECgMIBAAFAAAAAA==.',Vu='Vulweska:BAAALAAECgYIDwAAAA==.',['Væ']='Væssel:BAAALAAECgUIDAAAAA==.',Wa='Wacrafting:BAACLAAFFIESAAIIAAQIsiGLAACTAQAIAAQIsiGLAACTAQAsAAQKgTQAAggACAiIJlwAAIoDAAgACAiIJlwAAIoDAAAA.Walsungen:BAABLAAECoEUAAIHAAYIbAiN0AAmAQAHAAYIbAiN0AAmAQAAAA==.Warriorofc:BAAALAADCggICAAAAA==.',Wh='Whiteshade:BAACLAAFFIEFAAIYAAIIqQNiMABrAAAYAAIIqQNiMABrAAAsAAQKgSkAAhgACAgOE0U2ANMBABgACAgOE0U2ANMBAAAA.Whitéblade:BAAALAAECgcIEwABLAAECggILQAMAK0WAA==.Whitémoon:BAABLAAECoEtAAMMAAgIrRZhIgBDAgAMAAgIrRZhIgBDAgALAAgIRBhHLAAVAgAAAA==.',Wi='Widlu:BAABLAAECoEbAAIbAAgIkRo0EQBwAgAbAAgIkRo0EQBwAgAAAA==.',['Wî']='Wîngbow:BAABLAAECoEbAAMPAAcIJw+BggB4AQAPAAcIJw+BggB4AQAQAAUI5AgWegDJAAAAAA==.',Xa='Xaayah:BAABLAAECoEUAAMQAAgIxQd1kwByAAAQAAgITQJ1kwByAAAPAAgIBAd6LQECAAAAAA==.Xatari:BAAALAAECgYIBgABLAAECgYIHgAHABgcAA==.',Xi='Xiana:BAAALAAECggICAABLAAECggIEAAFAAAAAA==.Xineard:BAABLAAECoEUAAIhAAYITA04JQARAQAhAAYITA04JQARAQAAAA==.',Xu='Xurî:BAAALAAECgYIBQAAAA==.',Xy='Xyrena:BAAALAADCgUIBAAAAA==.',['Xâ']='Xârdes:BAABLAAECoEeAAMPAAgIvhrGPwAiAgAPAAgIvhrGPwAiAgAGAAEIIBjlHQBOAAAAAA==.',['Xê']='Xênyâ:BAAALAAECgYIEwAAAA==.',Ya='Yakura:BAAALAADCggICAAAAA==.Yaschida:BAABLAAECoEUAAIYAAYI/wljcwD8AAAYAAYI/wljcwD8AAAAAA==.',Yg='Ygthrasir:BAABLAAECoEdAAIYAAcIlibRBgAVAwAYAAcIlibRBgAVAwAAAA==.',Yu='Yubaba:BAAALAAECgYIEQAAAA==.Yuleen:BAAALAADCgcICAAAAA==.Yunales:BAAALAAECgYIEwAAAA==.Yunã:BAABLAAECoEWAAMbAAcI0wrNOgAOAQAbAAYIBgrNOgAOAQAJAAcICAhXOACsAAAAAA==.',Za='Zalandoheart:BAAALAADCggIEwAAAA==.Zandos:BAABLAAECoEgAAImAAYIqQ6TNgAeAQAmAAYIqQ6TNgAeAQAAAA==.Zazel:BAABLAAECoEvAAIRAAgIWgpAZQCNAQARAAgIWgpAZQCNAQAAAA==.',Zb='Zbank:BAAALAADCgQIBAAAAA==.',Ze='Zekulrakkas:BAACLAAFFIESAAMKAAUI+xp+CADFAQAKAAUI+xp+CADFAQAgAAEIOgN+FQBYAAAsAAQKgS4AAgoACAjGJBALADwDAAoACAjGJBALADwDAAAA.Zelagorr:BAABLAAECoEoAAIoAAgIwCQaAgBTAwAoAAgIwCQaAgBTAwAAAA==.Zeyphox:BAAALAADCggICAAAAA==.',Zh='Zhihui:BAAALAADCggIBgAAAA==.',Zn='Znage:BAAALAAECgQIAwAAAA==.',Zo='Zo:BAAALAAECgMIAwABLAAECggIIgAcAAofAA==.',Zw='Zwaegwynn:BAAALAAECgYIEQAAAA==.Zwuckella:BAAALAADCgIIAgABLAAECgYIEQAFAAAAAA==.',Zy='Zyankhalî:BAAALAADCgcIDgAAAA==.Zycanis:BAAALAAECgYIDAAAAA==.Zylen:BAAALAADCgcIDAAAAA==.Zyrallas:BAAALAADCggICAAAAA==.Zyras:BAAALAAECgcIEQAAAA==.',['Zä']='Zäroius:BAAALAADCgUIBQAAAA==.',['Zô']='Zôydbêrg:BAAALAAECgMIBAAAAA==.',['Áe']='Áebola:BAAALAAECgYICwAAAA==.',['Âb']='Âbaddon:BAABLAAECoEZAAIMAAcI3B2+IABQAgAMAAcI3B2+IABQAgAAAA==.',['Âl']='Âlbedo:BAAALAADCggIDwAAAA==.',['Âs']='Âsûnâ:BAAALAADCggICAABLAAFFAQIEgAZANYeAA==.',['Äx']='Äxadudu:BAAALAAFFAIIAgABLAAFFAUIEAAPALUgAA==.',['Æo']='Æon:BAAALAAECgcICAAAAA==.',['Æp']='Æp:BAABLAAECoEgAAIhAAYIlRAAIABFAQAhAAYIlRAAIABFAQAAAA==.',['Ær']='Ærik:BAAALAAECggICwAAAA==.',['Öt']='Öthendris:BAAALAADCggIDgAAAA==.',['Øl']='Øldskool:BAAALAADCggIDwAAAA==.',['Úl']='Úlfur:BAABLAAECoEhAAIIAAgIdh/JAwDTAgAIAAgIdh/JAwDTAgAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end