local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Mage-Arcane','Paladin-Protection','Priest-Shadow','Druid-Restoration','Hunter-Survival','Evoker-Devastation','Evoker-Preservation','Unknown-Unknown','DeathKnight-Blood','DemonHunter-Havoc','Warrior-Arms','Warrior-Protection','Druid-Balance','Hunter-BeastMastery','Hunter-Marksmanship','Monk-Brewmaster','Shaman-Restoration','Paladin-Holy','Warrior-Fury','Rogue-Subtlety','Rogue-Assassination','Monk-Windwalker','Monk-Mistweaver','Mage-Frost','DeathKnight-Frost','Shaman-Elemental','Warlock-Destruction','DemonHunter-Vengeance','Priest-Holy','Paladin-Retribution','Druid-Feral','Shaman-Enhancement','Warlock-Demonology','Druid-Guardian','DeathKnight-Unholy','Evoker-Augmentation','Mage-Fire','Priest-Discipline',}; local provider = {region='EU',realm='Lordaeron',name='EU',type='weekly',zone=44,date='2025-09-24',data={Aa='Aarøn:BAAALAADCgcIBwAAAA==.',Ab='Abegeh:BAABLAAECoEVAAIBAAcIRyKvIgCvAgABAAcIRyKvIgCvAgAAAA==.Abgsh:BAAALAADCggICAAAAA==.',Ad='Adalfuchs:BAAALAAECgUIBQAAAA==.Adalgrip:BAAALAADCgIIAQAAAA==.Adalwyn:BAABLAAECoEhAAICAAgIMByTDACHAgACAAgIMByTDACHAgAAAA==.Adanox:BAAALAADCggICAAAAA==.Addblockerin:BAAALAADCgYIBgAAAA==.Adeliná:BAAALAADCgcICgAAAA==.',Ae='Aeliora:BAAALAADCggIDgAAAA==.Aerdaras:BAAALAAECgMIAwABLAAECggIGwADAKwYAA==.Aerion:BAAALAAECgIIBgAAAA==.',Ag='Agura:BAABLAAECoEXAAIEAAcImx1jHgBQAgAEAAcImx1jHgBQAgAAAA==.',Ak='Akamee:BAAALAADCggIDAAAAA==.Akrinara:BAABLAAECoEgAAIFAAgIoBVnBgBBAgAFAAgIoBVnBgBBAgAAAA==.',Al='Alamea:BAABLAAECoEZAAICAAcIXSQ+CADWAgACAAcIXSQ+CADWAgAAAA==.Alegrion:BAABLAAECoEkAAMGAAgIryTHAgBaAwAGAAgIryTHAgBaAwAHAAEI1BbGNwA3AAAAAA==.Alicyâ:BAAALAAECgMIAwABLAAECgcICgAIAAAAAA==.Alinya:BAAALAADCgYIBgAAAA==.Alosa:BAAALAAECgYIDAAAAA==.Alythia:BAABLAAECoEYAAIJAAcIySN4BgDjAgAJAAcIySN4BgDjAgAAAA==.',Ao='Aowe:BAAALAADCggICAAAAA==.Aowê:BAAALAAECgcIEgAAAA==.',Ar='Arcaneo:BAAALAAECgIIAgABLAAFFAQIDgAKAF0gAA==.Arilyana:BAAALAAECgIIAgAAAA==.Arkturus:BAAALAADCgcIBwAAAA==.Armes:BAAALAAECgMIBAAAAA==.Arombolosch:BAAALAADCgEIAQAAAA==.Arrgonaut:BAACLAAFFIENAAMLAAMI1BQRAQD2AAALAAMI1BQRAQD2AAAMAAEIqwTPIgAxAAAsAAQKgS4AAgsACAgXJa4AAG0DAAsACAgXJa4AAG0DAAAA.Arti:BAAALAADCgcICgAAAA==.Artimos:BAAALAAECgYIBwAAAA==.',As='Asgardt:BAABLAAECoEiAAINAAYIIhf+OgCcAQANAAYIIhf+OgCcAQABLAAFFAQIDQAGAIsMAA==.Ashàyà:BAABLAAECoEnAAMOAAgIjx6UNQBGAgAOAAgIeh6UNQBGAgAPAAYI2RXvVQBGAQAAAA==.Asmodk:BAAALAADCgcIDQABLAAECgcIIQAQAHMhAA==.Asmonk:BAABLAAECoEhAAIQAAcIcyF/CgCQAgAQAAcIcyF/CgCQAgAAAA==.Asmorg:BAAALAADCggIDwABLAAECgcIIQAQAHMhAA==.Asmosh:BAAALAAECgMIAwABLAAECgcIIQAQAHMhAA==.Asthon:BAAALAADCggICAABLAAFFAIICAARAB8lAA==.Astraja:BAAALAAECggICAAAAA==.',At='Atenuiel:BAAALAAECggICQAAAA==.Atterian:BAAALAAECgMIBgAAAA==.',Au='Augustinos:BAAALAAECgYIDAAAAA==.Aurok:BAAALAADCggIIAAAAA==.',Av='Avana:BAAALAADCgQIBAAAAA==.Avariss:BAAALAAECgQIBQAAAA==.Avonia:BAAALAAECgcIDgAAAA==.',Ay='Aylira:BAAALAADCggIBgAAAA==.',Az='Azâzêl:BAABLAAECoEZAAIKAAcI9gxpngBcAQAKAAcI9gxpngBcAQAAAA==.',['Aá']='Aáyla:BAAALAADCggIFwABLAAECgIIAwAIAAAAAA==.',Ba='Backtrack:BAAALAAECgYICAAAAA==.Baecon:BAAALAAECggICwAAAA==.Bauchstich:BAAALAAECgQIBAAAAA==.',Be='Begur:BAAALAADCggIFgAAAA==.Beldan:BAAALAAECgMIBgAAAA==.Belesh:BAAALAAECgIIAgAAAA==.',Bi='Bimm:BAAALAADCggIIAABLAAECgcIHgASADMbAA==.',Bl='Blaueslicht:BAAALAAECgQIBAAAAA==.Bloodhammer:BAAALAAECgYICgABLAAFFAQIDgAKAF0gAA==.Bluekay:BAAALAAECgQICQAAAA==.Blutmacht:BAABLAAECoEdAAITAAgI0xUsOgAaAgATAAgI0xUsOgAaAgAAAA==.Bláckearth:BAAALAAECgcIEAAAAA==.Blâine:BAAALAADCgIIAgABLAAECgIIBAAIAAAAAA==.',Bo='Boogy:BAAALAAECgUICgAAAA==.Borkar:BAAALAAECgYIEQAAAA==.',Br='Bralrus:BAAALAADCgcIBwAAAA==.Bryndis:BAAALAAECgYIBgAAAA==.Brítneyfears:BAAALAADCgYICQAAAA==.',Bu='Bullwark:BAAALAAECgYIBgAAAA==.',Ca='Caraniera:BAAALAAECggIDgAAAA==.Cardos:BAAALAAECgMIAwABLAAFFAQICgAPAOwVAA==.Carramba:BAAALAAECgcIEAAAAA==.Cazh:BAAALAAECgMIBAAAAA==.',Ce='Ceabela:BAAALAAECgIIAwAAAA==.Celîna:BAAALAAECgcICAAAAA==.Ceylse:BAAALAADCggICAAAAA==.',Ch='Chade:BAABLAAECoEWAAMUAAgIYhxqDgApAgAUAAgISxVqDgApAgAVAAYI1B9VIQD4AQABLAAFFAMIBgABALkWAA==.Cheeseman:BAAALAAECgQIBgAAAA==.Chester:BAAALAADCggICAAAAA==.Chinni:BAABLAAECoEdAAMWAAcIKhYoIQDFAQAWAAcIKhYoIQDFAQAXAAMIQAbhQABhAAAAAA==.Chiuvana:BAAALAAECgMIBwAAAA==.Chizue:BAAALAADCggICAAAAA==.Cholai:BAAALAADCgUIBQABLAAECggIJAAOABcgAA==.Chrisvôltiâ:BAAALAAECgcICwAAAA==.Chryathan:BAAALAAECggICAAAAA==.',Ci='Ciilay:BAABLAAECoEnAAIOAAgIRxYAYQDEAQAOAAgIRxYAYQDEAQAAAA==.Cila:BAAALAAECgMIBwAAAA==.Ciryon:BAACLAAFFIEGAAIBAAMIuRZNHADpAAABAAMIuRZNHADpAAAsAAQKgSAAAgEACAitJP8NACADAAEACAitJP8NACADAAAA.',Cl='Cleganer:BAAALAADCgQIBAAAAA==.Cleganex:BAAALAAECgEIAQAAAA==.',Co='Coolibri:BAABLAAECoElAAMBAAgIpB4WHwDBAgABAAgIpB4WHwDBAgAYAAEI9xaRgAAzAAAAAA==.Corkie:BAAALAADCggIDQAAAA==.',Cr='Crazyspirit:BAABLAAECoEiAAISAAcInxnKJgC1AQASAAcInxnKJgC1AQAAAA==.Crewel:BAAALAAECgMIBAAAAA==.Cristine:BAAALAADCggICgAAAA==.Crowdy:BAAALAAFFAIIAgAAAA==.',Cy='Cyress:BAAALAAECgYICwAAAA==.',['Câ']='Câlista:BAAALAAECgQIBQAAAA==.',Da='Dagor:BAACLAAFFIEHAAINAAII2RX8EwCYAAANAAII2RX8EwCYAAAsAAQKgSsAAg0ACAhvIQ8MAPcCAA0ACAhvIQ8MAPcCAAAA.Dakotá:BAACLAAFFIEKAAIOAAIIwxWaKQCSAAAOAAIIwxWaKQCSAAAsAAQKgR4AAg4ABgh4Irk2AEECAA4ABgh4Irk2AEECAAAA.Daliasis:BAABLAAECoEXAAMYAAgIrwcPPgBSAQAYAAgIogcPPgBSAQABAAcInQNnogAGAQAAAA==.Damocles:BAABLAAECoEUAAMYAAcIqAi2SAAlAQAYAAYIiwm2SAAlAQABAAYIWgKSvAChAAAAAA==.Daramuur:BAAALAAECgYICAAAAA==.Darcii:BAAALAAECgYIBgAAAA==.Darkfury:BAAALAADCgcIBwAAAA==.Datari:BAAALAADCggIDQABLAAECgYIFAAGAIQHAA==.',De='Death:BAAALAAECgEIAQAAAA==.Dekkel:BAABLAAECoEUAAIZAAgImhROXQAJAgAZAAgImhROXQAJAgAAAA==.Desdemonía:BAAALAADCggIDwAAAA==.Devoto:BAAALAAECggIBwAAAA==.',Di='Diridari:BAAALAAECgYIDwAAAA==.',Dk='Dkayo:BAAALAAECgcIDgAAAA==.',Dn='Dna:BAACLAAFFIEKAAIaAAII+AswIQCQAAAaAAII+AswIQCQAAAsAAQKgRgAAhoABgh8Gw8/AN0BABoABgh8Gw8/AN0BAAAA.Dnaidkit:BAAALAADCgIIAgAAAA==.Dnalock:BAACLAAFFIEIAAIbAAIInRWoKACeAAAbAAIInRWoKACeAAAsAAQKgSgAAhsACAgsILQUAPACABsACAgsILQUAPACAAAA.',Do='Dopeleler:BAACLAAFFIEJAAMPAAMIMyXmCAAlAQAPAAMIzCDmCAAlAQAOAAEI7iRyQABhAAAsAAQKgSkAAw8ACAhtJUUDAFMDAA8ACAhtJUUDAFMDAA4AAQgpGCANAUEAAAAA.Dotliin:BAAALAAECgQIBAABLAAECggIGQAEAEcZAA==.Dowjoens:BAABLAAECoEXAAIZAAYIFRRpowCDAQAZAAYIFRRpowCDAQAAAA==.Doyavexony:BAAALAAECgQIBQAAAA==.',Dr='Draag:BAAALAAECgUIBwAAAA==.Dracar:BAAALAADCggIDwAAAA==.Dracosi:BAAALAADCggIFwAAAA==.Dragondarcy:BAAALAAECgYIEwABLAAFFAMICgAYAAIbAA==.Dragusha:BAAALAADCggIBgAAAA==.',Ds='Dsync:BAAALAADCgIIAwAAAA==.',Du='Dubur:BAAALAAECggICAAAAA==.Dunkoro:BAAALAADCggIFwABLAAECggIKAAPADAhAA==.',['Dâ']='Dârkrevenge:BAAALAAECgQIBQAAAA==.',Ed='Edvin:BAAALAADCgQIBAAAAA==.',El='Eledeath:BAAALAADCgEIAQABLAAECgYIBwAIAAAAAQ==.Eledor:BAAALAAECgUICgAAAA==.Elfigos:BAABLAAECoEcAAIWAAgIcx8QDAC4AgAWAAgIcx8QDAC4AgAAAA==.Eligos:BAAALAADCgYICAAAAA==.Elung:BAAALAADCggICgABLAAECgIIAwAIAAAAAA==.Elysîon:BAAALAAECgMIAwAAAA==.',Em='Emriss:BAAALAAECgUIBwAAAA==.',En='Entertaîn:BAACLAAFFIEOAAIKAAQIXSAgDwAWAQAKAAQIXSAgDwAWAQAsAAQKgS0AAwoACAhGJKoKAEADAAoACAhGJKoKAEADABwACAjQIEYGAOgCAAAA.Envinya:BAABLAAECoEmAAIdAAgIHRR/NADqAQAdAAgIHRR/NADqAQAAAA==.',Ep='Ephistod:BAAALAADCgcIBwAAAA==.',Ev='Even:BAAALAADCgIIAgAAAA==.Eventide:BAAALAAECgYICQAAAA==.Evokadó:BAAALAAFFAEIAQABLAAFFAIIBgAZAO8hAA==.',Fa='Fabio:BAABLAAECoEYAAITAAYIMQ9CcgBmAQATAAYIMQ9CcgBmAQAAAA==.Fairie:BAAALAAECgYIEwAAAA==.Fantabrise:BAAALAADCggICAAAAA==.',Fe='Feelya:BAAALAADCgcIFgAAAA==.Feeni:BAABLAAECoEXAAMaAAgITxSpLwAmAgAaAAgITxSpLwAmAgARAAcILw1wjgAoAQAAAA==.Feini:BAACLAAFFIEGAAIDAAMIVR3sCwAFAQADAAMIVR3sCwAFAQAsAAQKgScAAgMACAhmJf4DAFwDAAMACAhmJf4DAFwDAAEsAAUUBggVAB4ASBwA.Felay:BAAALAAECgUICQABLAAECggIHgARADEXAA==.Felipa:BAACLAAFFIEIAAIfAAMInAlKBgC8AAAfAAMInAlKBgC8AAAsAAQKgR4AAh8ACAiWGU0OAEQCAB8ACAiWGU0OAEQCAAAA.Femdomlover:BAAALAAECgEIAQAAAA==.Fentura:BAAALAAECggIEwAAAA==.Feryv:BAAALAADCgUIBQAAAA==.',Fi='Fibiane:BAABLAAECoEVAAIfAAYIrRV2HgB5AQAfAAYIrRV2HgB5AQAAAA==.Fireball:BAABLAAECoEZAAIgAAYIex9SCwAaAgAgAAYIex9SCwAaAgABLAAECggIKQACAP4iAA==.',Fl='Flocke:BAAALAAECgcICgAAAA==.Floristika:BAAALAAECgMIAwAAAA==.Flows:BAAALAAECgYICAAAAA==.Flócke:BAAALAAECgYIBgAAAA==.',Fo='Formops:BAAALAADCgcIBgAAAA==.Forreel:BAAALAAECgIIAwAAAA==.Forrockz:BAAALAADCgcICwAAAA==.',Fr='Frey:BAAALAAECgUICAAAAA==.',Fu='Fugurus:BAAALAAECgEIAQAAAA==.Fusselrolle:BAAALAADCgYIBgAAAA==.',Ga='Gamakichi:BAAALAADCgIIAgAAAA==.Ganara:BAAALAAECggICAAAAA==.Gaël:BAAALAADCgcIBwABLAADCggICAAIAAAAAA==.',Ge='George:BAAALAADCgYIBgABLAAFFAUIFQAGAKwgAA==.',Gh='Ghostbladé:BAABLAAECoEbAAIhAAcIBhFfJgC/AQAhAAcIBhFfJgC/AQAAAA==.',Gi='Ginkoro:BAABLAAECoEZAAIRAAcIhQr8lwATAQARAAcIhQr8lwATAQAAAA==.',Gl='Gloym:BAAALAADCggICAABLAAECgcIFgARADkOAA==.',Go='Goodnìght:BAAALAAECgMIBQAAAA==.Gorgasch:BAAALAADCgYIBgAAAA==.Gorlox:BAAALAAECgEIAgAAAA==.Goukai:BAABLAAECoEkAAIbAAgIfxrxLQBdAgAbAAgIfxrxLQBdAgAAAA==.',Gr='Gramor:BAABLAAECoEZAAITAAcIFxbPRQDtAQATAAcIFxbPRQDtAQAAAA==.Grinds:BAABLAAECoEnAAIKAAgIShk5RgAlAgAKAAgIShk5RgAlAgAAAA==.',Ha='Haniel:BAAALAADCgYIBgAAAA==.Harmony:BAAALAADCgcIBwAAAA==.Harok:BAAALAADCggIHAAAAA==.Hatori:BAABLAAECoEaAAIBAAcICxk1UgDuAQABAAcICxk1UgDuAQAAAA==.',He='Healomo:BAABLAAECoEhAAINAAgIzRi+IAAxAgANAAgIzRi+IAAxAgAAAA==.Heiler:BAAALAADCggIEAAAAA==.Heiligerbimm:BAABLAAECoEeAAISAAcIMxtyGgAPAgASAAcIMxtyGgAPAgAAAA==.Hepatitís:BAAALAAECgYIDwAAAA==.Hexoduz:BAAALAAECgYICgAAAA==.Heyo:BAAALAAECgYIBgAAAA==.',Hi='Highmane:BAAALAADCgMIAwABLAAECgYIDAAIAAAAAA==.',Ho='Hogri:BAABLAAECoEVAAIVAAYIxQ/WNgByAQAVAAYIxQ/WNgByAQAAAA==.Holyrose:BAABLAAECoEhAAIeAAgIQw2IogB6AQAeAAgIQw2IogB6AQAAAA==.',Hu='Hunting:BAAALAADCgMIAwAAAA==.',Hy='Hyolmyr:BAAALAADCggICAAAAA==.',['Hä']='Hänk:BAAALAADCgYIBgAAAA==.',['Hö']='Hörmeline:BAAALAADCggICAAAAA==.',Ik='Ikke:BAAALAAECggICAAAAA==.',Il='Ilell:BAABLAAECoEoAAIiAAgIDB9XBAC7AgAiAAgIDB9XBAC7AgAAAA==.Illidana:BAABLAAECoEbAAIKAAgIoBZ4QwAuAgAKAAgIoBZ4QwAuAgAAAA==.Ilyndra:BAAALAAECgYICAAAAA==.Ilyrae:BAAALAAECggIEAAAAA==.',Im='Immortâl:BAABLAAECoEpAAICAAgI/iIoBgABAwACAAgI/iIoBgABAwAAAA==.',In='Innovindils:BAACLAAFFIEOAAITAAQIWh1xCQCHAQATAAQIWh1xCQCHAQAsAAQKgSoAAhMACAjyIXgaAMgCABMACAjyIXgaAMgCAAAA.Insidias:BAAALAADCggICAABLAAECggIKAAPADAhAA==.',Iq='Iqo:BAAALAAECgYIDAAAAA==.',Ir='Irvíne:BAABLAAECoEoAAMPAAgIMCElEADUAgAPAAgIMCElEADUAgAOAAEISxTFEQE5AAAAAA==.',It='Itsuki:BAAALAADCgcIBwAAAA==.',Ja='Jannâ:BAABLAAECoEhAAIGAAgIUR9dEACgAgAGAAgIUR9dEACgAgAAAA==.',Ji='Jikme:BAAALAADCggICAAAAA==.',Jo='Joachim:BAAALAADCgcIBwABLAAECggIJQABAKQeAA==.Jormungandr:BAAALAAECgYIEAAAAA==.Jormungåndr:BAAALAADCgcIBwAAAA==.',Ju='Juani:BAAALAAECgQIBAAAAA==.Julién:BAABLAAECoEiAAIEAAgIaByiFQCKAgAEAAgIaByiFQCKAgAAAA==.Junii:BAAALAAECgYIDAAAAA==.Juniimond:BAAALAADCggICAAAAA==.Junischnee:BAAALAAECgEIAQAAAA==.',['Jâ']='Jâîná:BAAALAAECgYIBgAAAA==.',Ka='Kaboohm:BAAALAAECgIIAgAAAA==.Kalachakra:BAAALAAFFAEIAQAAAA==.Kaliana:BAABLAAECoEdAAMEAAcI5CHFEQCqAgAEAAcI5CHFEQCqAgANAAMIuQoZdQCPAAABLAAECggIJwAOAI8eAA==.Kaltara:BAAALAADCgcIBwAAAA==.Kalvara:BAABLAAECoEoAAIKAAgI0xvxKgCOAgAKAAgI0xvxKgCOAgAAAA==.Karamnor:BAABLAAECoEWAAITAAYIlBxtQQD9AQATAAYIlBxtQQD9AQAAAA==.Karolina:BAAALAAECggIDQAAAA==.Karrazz:BAAALAAECgcIEwAAAA==.Kary:BAAALAAECgUICgAAAA==.',Ke='Kerah:BAAALAAECgQIBQAAAA==.Kerimi:BAABLAAECoEfAAIdAAgIZhCJRACfAQAdAAgIZhCJRACfAQAAAA==.Kerotek:BAABLAAECoEmAAIDAAgIsBf+JgAjAgADAAgIsBf+JgAjAgAAAA==.',Kh='Khartok:BAABLAAECoEWAAINAAgIgBMgKAAAAgANAAgIgBMgKAAAAgAAAA==.Khorag:BAABLAAECoEtAAMZAAgIKyMTMgCEAgAZAAgIrSETMgCEAgAjAAYIJiJSEAA9AgAAAA==.Khron:BAAALAAECgQIBAAAAA==.',Ki='Kianna:BAAALAADCgYIBQAAAA==.Kinki:BAAALAADCgMIAwAAAA==.Kire:BAABLAAECoEYAAIKAAcIYSCQMAB1AgAKAAcIYSCQMAB1AgAAAA==.',Kl='Klokra:BAAALAAECgUICQAAAA==.',Kn='Kneffus:BAAALAADCgcIDQAAAA==.',Ko='Kotalkahn:BAAALAADCgcICgAAAA==.',Kr='Kratanius:BAAALAAECgIIAgAAAA==.Kravok:BAAALAADCgcIBwAAAA==.Kremer:BAABLAAECoEaAAMPAAgISgniXQAqAQAPAAgIqgjiXQAqAQAOAAQIBwsQ2wC4AAAAAA==.Krilon:BAAALAADCgYIBgAAAA==.Krisiz:BAAALAADCgcIBwAAAA==.Kritikel:BAAALAAECggICAAAAA==.Krytonisbff:BAAALAADCgEIAQAAAA==.Krümelkeks:BAAALAAECgYIDwAAAA==.',Ky='Kyuuvoker:BAAALAAECgMIBQAAAA==.',['Kâ']='Kâiros:BAAALAADCgcIBwAAAA==.',La='Lanadelslay:BAABLAAECoEkAAIXAAgIZg2THQCSAQAXAAgIZg2THQCSAQAAAA==.Laney:BAAALAAECgYIBgAAAA==.Lavinia:BAABLAAECoEkAAIEAAcIoh1AIABEAgAEAAcIoh1AIABEAgAAAA==.',Le='Leeviatan:BAACLAAFFIENAAIGAAQIiww+CQAgAQAGAAQIiww+CQAgAQAsAAQKgTgABCQACAjqGw4FADwCAAYACAiMGIkXAFACACQABwiDGg4FADwCAAcABAhLEYcmAOwAAAAA.Leilianne:BAAALAADCgcIDAAAAA==.Leni:BAAALAAECgEIAQAAAA==.Lerasol:BAAALAAECgYIBgAAAA==.Lessaya:BAAALAADCgcIBwAAAA==.',Lh='Lheylhu:BAAALAAFFAMIAwAAAA==.',Li='Lightanddead:BAAALAADCgcIBwAAAA==.Lilypierce:BAAALAAECgIIAgAAAA==.Lisanda:BAAALAAECggIBgAAAA==.',Lo='Lockout:BAAALAAFFAIIAgABLAAFFAcIHwAeAG0aAA==.Lophelia:BAACLAAFFIEIAAIEAAIISiLQEQDAAAAEAAIISiLQEQDAAAAsAAQKgRkAAwQACAimICEJAPsCAAQACAimICEJAPsCAA0AAQh+CM+VACYAAAAA.Loti:BAAALAAECgIIAgABLAAECgcIFQAPAHkHAA==.Lotî:BAAALAAECgIIAgABLAAECgcIFQAPAHkHAA==.Lovewithin:BAAALAADCgYICwAAAA==.',Lu='Luanari:BAAALAAECgEIAQAAAA==.Luccia:BAABLAAECoEWAAIaAAgIHBRwMgAYAgAaAAgIHBRwMgAYAgABLAAFFAIIBgAfADkcAA==.Luccifera:BAACLAAFFIEKAAIYAAMIAhsmAwAMAQAYAAMIAhsmAwAMAQAsAAQKgSoAAxgACAiUIA4RAHwCABgABwiEIQ4RAHwCAAEACAixGTJSAO4BAAAA.Luiquinnade:BAABLAAECoEdAAIKAAcItRxHPwA9AgAKAAcItRxHPwA9AgAAAA==.Lunelunae:BAAALAADCggIEAAAAA==.',Ly='Lycanroc:BAAALAADCgYIBgAAAA==.Lythia:BAAALAADCgcIHQAAAA==.',Ma='Madrasdh:BAAALAADCgEIAQAAAA==.Maellé:BAAALAAECggICAAAAA==.Maggimagnus:BAAALAADCggICAAAAA==.Makkarroni:BAABLAAECoEdAAMZAAgI4hgeVwAXAgAZAAcIwRseVwAXAgAjAAgIzwmHJgBvAQAAAA==.Malgorr:BAACLAAFFIERAAIOAAUInBf7BwCXAQAOAAUInBf7BwCXAQAsAAQKgTYAAg4ACAh0JtgHAEEDAA4ACAh0JtgHAEEDAAAA.Malo:BAAALAADCggICgAAAA==.Manatan:BAAALAAECgIIAgAAAA==.Marco:BAAALAAECgYIBQABLAAECggIKAAPADAhAA==.Marcosbg:BAAALAAECggIDAAAAA==.Marz:BAAALAAECgMIBgAAAA==.',Mc='Mcmatyss:BAAALAAECgEIAQAAAA==.',Me='Meldøver:BAAALAAECggICwAAAA==.Menphina:BAAALAADCggICQAAAA==.Merieke:BAABLAAECoElAAIDAAgIfw8EMwDdAQADAAgIfw8EMwDdAQAAAA==.Merlinx:BAAALAAECgIIBQAAAA==.',Mh='Mhystery:BAAALAADCggICAAAAA==.',Mi='Middgardt:BAAALAADCgUIAwABLAAFFAQIDQAGAIsMAA==.Mightydk:BAABLAAECoEYAAMZAAgIlQ231QAwAQAZAAgIWwy31QAwAQAJAAEIxCNcOgBOAAAAAA==.Minato:BAAALAAECgYIDAAAAA==.Mirandis:BAAALAAECgYIBQAAAA==.Miwou:BAAALAADCgYIBgAAAA==.',Mo='Mochi:BAAALAAECgYICwAAAA==.Monihunt:BAAALAAECgYIBwAAAA==.Motorpsycho:BAAALAAECgQIBQAAAA==.',Mu='Muffelkopf:BAAALAADCgYIBgAAAA==.Mulingor:BAABLAAECoEZAAIEAAcI6SEFEgCoAgAEAAcI6SEFEgCoAgAAAA==.Mulingus:BAAALAADCgYIBgABLAAECgcIGQAEAOkhAA==.Munyoth:BAAALAADCggIHgAAAA==.',My='Mylento:BAAALAAECgYIEwAAAA==.Myrâgè:BAAALAAECgcICgAAAA==.Myrågé:BAAALAAECgUIBQAAAA==.Mysteria:BAAALAAFFAEIAQAAAA==.Mysthariel:BAAALAADCggIIAABLAAECgcIGAAJAMkjAA==.Myzea:BAABLAAECoEUAAIZAAcIGhR1eQDOAQAZAAcIGhR1eQDOAQAAAA==.',['Má']='Málefitz:BAAALAADCggICAAAAA==.',['Mí']='Mídna:BAAALAAECgYIEgABLAAECggIGgAWADEUAA==.',Na='Nachtshatten:BAAALAAECgYIEAAAAA==.Nacra:BAAALAAECgcIBwAAAA==.Nados:BAABLAAECoEaAAMQAAcIlR0BEAAvAgAQAAcIlR0BEAAvAgAXAAEIEwTgSQAkAAAAAA==.Nafarian:BAAALAAECgYIBgAAAA==.Nanami:BAAALAADCggIDwAAAA==.Nanuk:BAAALAAECggICAAAAA==.Nargana:BAACLAAFFIEOAAIEAAQIuheHBgBQAQAEAAQIuheHBgBQAQAsAAQKgTQAAgQACAj4In4HAA0DAAQACAj4In4HAA0DAAAA.Nathrael:BAAALAAECgcIEwAAAA==.Navyfree:BAAALAAECgYICwABLAAECgcIIgADAO8SAA==.',Ne='Neh:BAAALAADCggICAAAAA==.Nelebrián:BAAALAAECgIIBAAAAA==.Nelory:BAAALAAECgMIBQAAAA==.Nertika:BAAALAADCggIBgABLAAECggIHwAdAGYQAA==.Neseria:BAABLAAECoErAAIOAAgIAhnJQAAeAgAOAAgIAhnJQAAeAgAAAA==.Neutro:BAACLAAFFIEKAAIPAAQI7BU5CgALAQAPAAQI7BU5CgALAQAsAAQKgSoAAg8ACAj9JT8BAHQDAA8ACAj9JT8BAHQDAAAA.Nezukó:BAAALAADCgIIAgAAAA==.',Ni='Nightydk:BAACLAAFFIEGAAMZAAII+SBQSQCPAAAZAAIIRhdQSQCPAAAjAAEIISNeFABcAAAsAAQKgR8AAxkACAhkJDhAAFYCABkABwigIzhAAFYCACMABQh+INccALwBAAAA.Nijamo:BAAALAAECgUIAwAAAA==.Nimoria:BAAALAAECgYIBwAAAA==.Ninehavefun:BAAALAADCggICAAAAA==.Nippi:BAAALAADCgIIAgAAAA==.',No='Noceon:BAAALAADCgcIBwAAAA==.Noniel:BAABLAAECoEZAAIKAAcIESNQIwCzAgAKAAcIESNQIwCzAgAAAA==.Nooe:BAAALAADCggICAAAAA==.Norsir:BAAALAADCggIBgAAAA==.Notal:BAAALAAECgUICgAAAA==.',Ny='Nysha:BAAALAAECgYIBgAAAA==.',['Nî']='Nîmue:BAAALAADCgMIAwAAAA==.',['Nï']='Nïhtøræ:BAACLAAFFIEGAAIKAAMIyiXcCwBSAQAKAAMIyiXcCwBSAQAsAAQKgRYAAgoACAilJNMJAEUDAAoACAilJNMJAEUDAAAA.',['Nô']='Nômi:BAAALAAECgYIBgAAAA==.Nôva:BAAALAAECgIIAgAAAA==.',['Nõ']='Nõmi:BAABLAAECoEcAAIRAAgIbRuqJQBZAgARAAgIbRuqJQBZAgAAAA==.',['Nú']='Núri:BAACLAAFFIEGAAIfAAIIORyoBwCoAAAfAAIIORyoBwCoAAAsAAQKgSsAAh8ACAhkIFYGAOACAB8ACAhkIFYGAOACAAAA.',['Nû']='Nûrag:BAAALAAECggIEAAAAA==.',Ob='Obdachloser:BAAALAADCggICAAAAA==.',Oj='Ojaoja:BAAALAAECgMIBAAAAA==.Ojiisan:BAAALAAECgYIBwAAAA==.',Ok='Okiku:BAABLAAECoEUAAMZAAcIkxmTVwAWAgAZAAcIkxmTVwAWAgAJAAEIwxb/PQA5AAAAAA==.Oktalius:BAAALAADCggIDAAAAA==.',Oo='Oogway:BAABLAAECoEbAAIdAAgIPiXiAQBpAwAdAAgIPiXiAQBpAwAAAA==.',Or='Or:BAAALAADCgEIAQAAAA==.Orb:BAAALAAECgQIBgAAAA==.Ortel:BAAALAADCgIIAgAAAA==.Ortl:BAACLAAFFIEIAAIdAAMITw1EEgDcAAAdAAMITw1EEgDcAAAsAAQKgSAAAh0ACAjLGpUeAGYCAB0ACAjLGpUeAGYCAAAA.Orweynâ:BAAALAAECgcIBwAAAA==.',Ou='Outlock:BAAALAAECgIIAgABLAAFFAcIHwAeAG0aAA==.',Pa='Pacx:BAAALAAECgMIAwABLAAFFAIICAARAB8lAA==.Paleria:BAAALAAECgYIDwAAAA==.Pandahao:BAABLAAECoElAAIZAAgIGhrQQgBOAgAZAAgIGhrQQgBOAgAAAA==.Paulina:BAAALAADCggICAAAAA==.',Pe='Pepperminz:BAAALAAECgQIBQAAAA==.Perilia:BAABLAAECoEgAAIYAAYItxBdOgBiAQAYAAYItxBdOgBiAQAAAA==.Perodeath:BAAALAADCggICAAAAA==.',Po='Pockpockdown:BAAALAAECgMIBQAAAA==.Popelklaus:BAACLAAFFIEFAAIgAAQIzBiCAQBUAQAgAAQIzBiCAQBUAQAsAAQKgR8AAiAACAhsJnkAAHEDACAACAhsJnkAAHEDAAAA.Popelpaul:BAAALAAECgYIBgAAAA==.',Pr='Praliene:BAACLAAFFIEVAAMeAAYISBzRAwDsAQAeAAUIcx7RAwDsAQACAAYILBG3AQDGAQAsAAQKgSYAAx4ACAhAJu0GAF8DAB4ACAhAJu0GAF8DAAIAAwh/IB44ABUBAAAA.Prenomix:BAAALAAECgIIAgAAAA==.Priestreeth:BAABLAAECoElAAIdAAgImh0YGgCDAgAdAAgImh0YGgCDAgABLAAFFAYIJwARADkYAA==.',Ps='Psybeast:BAAALAADCggIBgAAAA==.',Pu='Purplefox:BAAALAAECgMIAwAAAA==.',['Pú']='Púg:BAACLAAFFIEIAAIDAAIIJA6EGQCNAAADAAIIJA6EGQCNAAAsAAQKgScAAgMACAiuGo0bAHgCAAMACAiuGo0bAHgCAAEsAAUUAggKAA4AwxUA.',['Pû']='Pûg:BAABLAAECoEZAAINAAYIWRKmRwBhAQANAAYIWRKmRwBhAQABLAAFFAIICgAOAMMVAA==.',Qa='Qawin:BAAALAADCgIIAgAAAA==.',Qu='Quin:BAAALAADCggIDgAAAA==.',Ra='Raaz:BAAALAAECgcIBwAAAA==.Ragnarök:BAAALAAECgYIBwAAAA==.Rajina:BAABLAAECoEbAAMdAAgIPxJlPQC+AQAdAAgIPxJlPQC+AQADAAcIAw83QQCVAQAAAA==.Ranrika:BAAALAADCggICAAAAA==.Rasputín:BAAALAAECgUICgAAAA==.Raycah:BAAALAAECgMICAAAAA==.Razz:BAAALAAECggIBQAAAA==.',Re='Recâsa:BAABLAAECoEYAAIbAAcINxqVQwD9AQAbAAcINxqVQwD9AQAAAA==.Relagon:BAAALAADCgYIBgAAAA==.Revo:BAACLAAFFIEOAAMlAAQI/CB1AQAOAQABAAQIBB9MFAAlAQAlAAMI5B91AQAOAQAsAAQKgS8AAyUACAjsJAUBAC0DAAEACAi0I10LAC8DACUACAiuJAUBAC0DAAAA.',Rh='Rheá:BAAALAAECgYIEwAAAA==.',Rm='Rmx:BAAALAAECggIEgAAAA==.',Ro='Ronleut:BAAALAAECgIIBwAAAA==.',Rw='Rwz:BAAALAAECgIIAgAAAA==.',Rx='Rxr:BAAALAAECgYICwAAAA==.',Ry='Ryhok:BAAALAADCgMIAwAAAA==.Ryyuu:BAAALAADCggICAABLAAFFAIIBgAKANwdAA==.',['Rá']='Ráyzer:BAABLAAECoEcAAIYAAcIOiTsCwDBAgAYAAcIOiTsCwDBAgAAAA==.',['Rî']='Rîvers:BAAALAADCgcIBwABLAADCggICAAIAAAAAA==.',['Rò']='Rògolan:BAAALAADCggIFwAAAA==.',Sa='Safrix:BAAALAAECgMIAwAAAA==.Saintnavy:BAABLAAECoEiAAMDAAcI7xLePwCbAQADAAcI7xLePwCbAQAdAAYIehPCUABvAQAAAA==.Sake:BAABLAAECoEUAAIUAAcIsgWsLQDrAAAUAAcIsgWsLQDrAAAAAA==.Salamipizza:BAAALAADCgQIBAAAAA==.Salazar:BAAALAAECgMIAwABLAAECgYIDAAIAAAAAA==.Salobir:BAAALAADCggIDwAAAA==.Sanatores:BAAALAADCgMIAwAAAA==.Saryana:BAAALAAECgMIBQAAAA==.',Sc='Schmamane:BAAALAADCgMIAwAAAA==.Schurie:BAAALAAECgMIBAAAAA==.Scofiéld:BAAALAAECggICAAAAA==.',Se='Selira:BAAALAADCgYICwABLAAECggIJAAOABcgAA==.Seluna:BAABLAAECoEaAAIdAAgIsBKROQDQAQAdAAgIsBKROQDQAQAAAA==.Selyndra:BAAALAADCgYIBgAAAA==.Semtaxxdk:BAAALAAECgIIAgAAAA==.Sereney:BAAALAADCggIEAAAAA==.Seriousbob:BAAALAADCgUIAQAAAA==.Serã:BAABLAAECoEZAAIbAAcI4w05aQCDAQAbAAcI4w05aQCDAQAAAA==.',Sh='Shalill:BAAALAAECgQIBQAAAA==.Shamonireeth:BAACLAAFFIEnAAIRAAYIORidBAC6AQARAAYIORidBAC6AQAsAAQKgUoAAhEACAipJJUFACsDABEACAipJJUFACsDAAAA.Shaolin:BAAALAADCggIDwAAAA==.Shellie:BAAALAADCgMIAwAAAA==.Shiaf:BAABLAAECoEbAAIcAAcIeSRJCAC3AgAcAAcIeSRJCAC3AgAAAA==.Shyn:BAAALAAECgYICAAAAA==.Shyrez:BAAALAADCggICAAAAA==.Shârox:BAAALAAECgYIBgABLAAFFAIICQAMABgTAA==.Shòckwãve:BAABLAAECoEYAAIaAAgIhw8vRADIAQAaAAgIhw8vRADIAQAAAA==.',Si='Sickomode:BAAALAAECgcICQAAAA==.Siirlocker:BAAALAADCggICAAAAA==.Silwardagah:BAAALAAECgIIAgAAAA==.Sinistea:BAAALAAECgcIBwABLAAECgcIEwAIAAAAAA==.',Sk='Skoogage:BAAALAAECgIIBAAAAA==.Skrash:BAABLAAECoEeAAMRAAgIMRdiPwD5AQARAAgIMRdiPwD5AQAaAAMIowgdjwChAAAAAA==.Skøgtrøll:BAAALAADCggICAAAAA==.',Sl='Slimak:BAACLAAFFIEGAAMVAAIIgRucGABsAAAVAAEIJCScGABsAAAUAAEI3hK3FQBIAAAsAAQKgUAAAxUACAjsIAYXAE8CABUABghkIwYXAE8CABQABwjtF0QQAA8CAAAA.',Sm='Smiite:BAABLAAECoEfAAMeAAgI4BdBPwBTAgAeAAgI4BdBPwBTAgASAAcIGhH9KwCUAQAAAA==.',Sn='Snoozydk:BAACLAAFFIELAAMZAAUIgR53DQBZAQAZAAQI4x13DQBZAQAjAAMI3hpDBQAGAQAsAAQKgSYAAxkACAgXJYYZAPACABkACAhjIIYZAPACACMACAgyJCcHANcCAAAA.Snyeez:BAAALAADCggIDwAAAA==.',So='Soju:BAABLAAECoEUAAIBAAcIFANNtgC4AAABAAcIFANNtgC4AAAAAA==.Sokràtes:BAABLAAECoEeAAIBAAgImBFySgAIAgABAAgImBFySgAIAgAAAA==.Sonêa:BAAALAADCggICAAAAA==.Soraní:BAABLAAECoEZAAICAAcIqhiMHADcAQACAAcIqhiMHADcAQAAAA==.',Sp='Speedy:BAAALAAECgcIEAAAAA==.',St='Starboy:BAAALAAFFAIIBAABLAAFFAIICAARAB8lAA==.',Su='Suîcune:BAAALAAECgIIAgAAAA==.',Sy='Syd:BAAALAAECgEIAQAAAA==.Sydneya:BAAALAAECgMIAwABLAAECgcIGAAJAMkjAA==.Synestra:BAAALAAECgEIAQAAAA==.Syren:BAAALAADCggIIwABLAAECggIJwAKAEoZAA==.',['Sâ']='Sâmìrá:BAAALAAECgMIAwAAAA==.',['Sì']='Sìq:BAAALAAECgcIEgAAAA==.',['Sî']='Sîlad:BAAALAAECggICQAAAA==.',Ta='Taelisa:BAAALAADCggIDwAAAA==.Tagharr:BAABLAAECoEYAAICAAcIKBbjIgCnAQACAAcIKBbjIgCnAQAAAA==.Takanashidh:BAACLAAFFIEIAAIKAAIIgxrZJACgAAAKAAIIgxrZJACgAAAsAAQKgR8AAgoACAisH9AcANYCAAoACAisH9AcANYCAAAA.Takanashidk:BAAALAAECgYICQABLAAFFAIICAAKAIMaAA==.Tamila:BAAALAAECggICAAAAA==.Tandorin:BAAALAADCgIIAgAAAA==.Tarvog:BAAALAAECgUIBgAAAA==.Tarâk:BAAALAADCggIBgAAAA==.Taufine:BAAALAADCggICAAAAA==.Tawii:BAAALAAECgYICQABLAAFFAMICAAOAOgdAA==.',Te='Teddybärle:BAAALAAECggICAAAAA==.Teddybärly:BAAALAAECggICgAAAA==.Teliâ:BAABLAAECoEkAAMOAAgIFyAsHwCsAgAOAAgIFyAsHwCsAgAPAAEI6AecuAAlAAAAAA==.Teostra:BAAALAAECgcIEwAAAA==.',Th='Thalandriel:BAACLAAFFIEIAAIcAAIIQB2OBgCqAAAcAAIIQB2OBgCqAAAsAAQKgRsAAhwABwhdHacSABQCABwABwhdHacSABQCAAAA.Tharalina:BAAALAAECgcIEQAAAA==.Tharissan:BAAALAADCgEIAQAAAA==.Thaurelia:BAABLAAECoEnAAQmAAgIgyR2AgDIAgAdAAgI9CAxDAD1AgAmAAcIIiR2AgDIAgADAAQIgxcWWwAfAQAAAA==.Thaurelius:BAAALAAECgcICQABLAAECggIJwAmAIMkAA==.Theadore:BAABLAAECoEZAAMUAAgIGg9RJQA6AQAVAAYI2gvYPgBEAQAUAAYIxgxRJQA6AQAAAA==.Theyna:BAAALAADCgMIAwAAAA==.Thondrar:BAAALAAECggICAAAAA==.Thorosar:BAAALAAECgYIBgAAAA==.Thørys:BAAALAAECgYIBgABLAAECgcIHAAYADokAA==.',Ti='Tienti:BAAALAAECgMIBwAAAA==.Tigerchen:BAACLAAFFIEIAAIEAAII8huOFgCnAAAEAAII8huOFgCnAAAsAAQKgRkAAgQABwgAIGwfAEkCAAQABwgAIGwfAEkCAAAA.Tigergirl:BAABLAAECoEVAAIPAAcIeQfKaQADAQAPAAcIeQfKaQADAQAAAA==.Timurion:BAAALAAECgMIBwAAAA==.Tinck:BAAALAAECgYIEwAAAA==.Titanix:BAAALAADCgcIBwAAAA==.Titañ:BAAALAADCggICAAAAA==.Tixa:BAAALAADCgYIBgABLAAECggIKAAPADAhAA==.Tiérra:BAAALAAECgUICgAAAA==.',Tk='Tkoda:BAAALAAECgEIAQAAAA==.',To='Tohuwabohu:BAABLAAECoElAAIRAAcIuxmiRADnAQARAAcIuxmiRADnAQAAAA==.Tomoe:BAAALAADCgEIAQAAAA==.Tonar:BAABLAAECoEZAAIOAAcICBhzWQDWAQAOAAcICBhzWQDWAQAAAA==.Torokk:BAAALAADCggICAAAAA==.Toxxiie:BAAALAADCggICQAAAA==.',Tr='Trashroguex:BAAALAADCgYICQAAAA==.Trez:BAABLAAECoEUAAMZAAcIGhs1aADxAQAZAAcIGhs1aADxAQAJAAIIHhIAAAAAAAAAAA==.Trixia:BAAALAAECgMIAwAAAA==.Trudï:BAAALAAECggICAAAAA==.',Tu='Turmann:BAAALAAECgMIAwAAAA==.Turtôk:BAACLAAFFIEFAAMNAAMIGRjtCQD6AAANAAMIGRjtCQD6AAAfAAIIUAIVDgBbAAAsAAQKgSwABB8ACAipH7sLAHECAB8ACAgYG7sLAHECAA0ACAgnG9skABUCACIAAQgBJo4mAG8AAAAA.',Ty='Tyridon:BAABLAAECoEjAAISAAgIng9vJADGAQASAAgIng9vJADGAQAAAA==.Tyskie:BAAALAAECggIDQAAAA==.Tyxa:BAACLAAFFIEMAAIjAAMIZhD0BQD0AAAjAAMIZhD0BQD0AAAsAAQKgRwAAiMACAgYGsUOAFMCACMACAgYGsUOAFMCAAAA.',['Té']='Télebrian:BAAALAAECgIIAgAAAA==.',['Tï']='Tïara:BAAALAADCgMIAwAAAA==.',Ul='Ularia:BAAALAADCgUIBwAAAA==.Ultrícis:BAAALAAECgIIAgAAAA==.',Um='Umbrêon:BAEALAADCgcIBwABLAAFFAUIEwAKADMSAA==.',Un='Unicorn:BAAALAAECggIEAAAAA==.Unvershaman:BAAALAADCgcIBwAAAA==.',Va='Valkohr:BAABLAAECoEXAAIMAAgIRRyUEwBrAgAMAAgIRRyUEwBrAgAAAA==.',Ve='Veasna:BAAALAAECgIIAgAAAA==.Veldo:BAAALAAECgYIBQAAAA==.Veluneth:BAAALAAECgYIBgAAAA==.Velína:BAAALAADCggICAAAAA==.',Vi='Viehtreiber:BAAALAAECgIIBAAAAA==.Viktor:BAAALAAECgcIDgAAAA==.Vilso:BAAALAADCgcIBgABLAAECggIKAAPADAhAA==.Vivianne:BAABLAAECoEWAAIDAAYI1Bp4NADVAQADAAYI1Bp4NADVAQABLAAFFAMIDwAKACgaAA==.',Vo='Voxdeii:BAACLAAFFIELAAIYAAQILRjSAQBXAQAYAAQILRjSAQBXAQAsAAQKgTMAAhgACAgaI/AEADQDABgACAgaI/AEADQDAAAA.',Wa='Waldfried:BAAALAADCggICAAAAA==.Walli:BAAALAADCggIEAAAAA==.Warpspeed:BAAALAADCgcICwAAAA==.Watchmeblock:BAAALAAFFAIIAgABLAAFFAIICAARAB8lAA==.Watchmegrip:BAAALAADCgYIBgABLAAFFAIICAARAB8lAA==.Watchmeshock:BAACLAAFFIEIAAIRAAIIHyW5EQDaAAARAAIIHyW5EQDaAAAsAAQKgR4AAhEACAisJZECAFADABEACAisJZECAFADAAAA.Watchmetrapp:BAAALAADCgYIBgABLAAFFAIICAARAB8lAA==.Watchyoback:BAAALAADCgcIBwAAAA==.',We='Weisserwolf:BAAALAAECgQIBQAAAA==.',Wh='Whysoserious:BAAALAADCggICAAAAA==.Whysoseríous:BAAALAAECgUIBgAAAA==.',Wi='Wisperwind:BAAALAAECgUIBQAAAA==.',Wo='Woltan:BAAALAAECgQIBAAAAA==.Woozywow:BAAALAADCgQIBAAAAA==.',Wr='Wrian:BAAALAAECgYIEAAAAA==.',Xa='Xabi:BAAALAAECgcIBwABLAAECggIHwAdAGYQAA==.Xayah:BAAALAAECgcIEwAAAA==.',Xe='Xerog:BAAALAADCggICwAAAA==.',Xo='Xoxlena:BAAALAAECgYIDwAAAA==.',Xt='Xtc:BAAALAAECgYIBgAAAA==.',Xu='Xuanyu:BAACLAAFFIEGAAIGAAII0iF6DgDAAAAGAAII0iF6DgDAAAAsAAQKgTIAAwYACAgaJWQEAD8DAAYACAgaJWQEAD8DAAcABQizHwsTAM8BAAAA.',Xx='Xxholic:BAABLAAECoEbAAIOAAgI+RQ8UgDqAQAOAAgI+RQ8UgDqAQAAAA==.',Ya='Yadi:BAAALAAECgcICQAAAA==.',Yi='Yinlin:BAABLAAECoEaAAIDAAcI8hdYLQD9AQADAAcI8hdYLQD9AQAAAA==.',Ys='Yséré:BAAALAADCgYIBgABLAAECgcIGQAhAM0WAA==.',Za='Zakary:BAABLAAECoEbAAIDAAgIrBhxKAAbAgADAAgIrBhxKAAbAgAAAA==.Zanlock:BAABLAAECoEZAAIbAAcIVw8FaQCDAQAbAAcIVw8FaQCDAQAAAA==.Zappyboi:BAABLAAECoEoAAIaAAgIrBp4IQB4AgAaAAgIrBp4IQB4AgAAAA==.',Ze='Zenitsu:BAAALAAECggICAAAAA==.Zerplatscher:BAAALAADCgcIBQAAAA==.Zeyphira:BAAALAADCgcICAAAAA==.',Zi='Zinodin:BAAALAADCggICAAAAA==.',Zo='Zorlog:BAABLAAECoEvAAIOAAgIniBVHQC2AgAOAAgIniBVHQC2AgAAAA==.',Zu='Zunder:BAABLAAECoEjAAIeAAgI6R8bIwDDAgAeAAgI6R8bIwDDAgAAAA==.',Zw='Zworg:BAAALAAECgEIAQAAAA==.',['Zê']='Zêlda:BAAALAAECgMIBgAAAA==.',['Àr']='Àrwèn:BAABLAAECoEZAAICAAgIzxrIEQBFAgACAAgIzxrIEQBFAgAAAA==.',['Âl']='Âlitá:BAAALAADCgIIAgAAAA==.',['Ân']='Ânyu:BAACLAAFFIEKAAIdAAII0iOvFADMAAAdAAII0iOvFADMAAAsAAQKgS8AAh0ACAieJcgBAGsDAB0ACAieJcgBAGsDAAAA.',['Æc']='Æceu:BAABLAAECoEeAAIRAAgITx+dHACFAgARAAgITx+dHACFAgAAAA==.',['Ên']='Êngelchên:BAAALAAECgUICgAAAA==.',['Îc']='Îcke:BAAALAAECgMIBAAAAA==.',['Ðr']='Ðripex:BAAALAADCgEIAQAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end