local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Druid-Restoration','Druid-Guardian','Warlock-Destruction','Mage-Arcane','Priest-Holy','Priest-Shadow','Priest-Discipline','Paladin-Protection','Paladin-Retribution','Paladin-Holy','Monk-Brewmaster','Hunter-Marksmanship','Shaman-Restoration','Unknown-Unknown','Warlock-Demonology','Warlock-Affliction','Monk-Windwalker','Hunter-BeastMastery','Druid-Balance','Hunter-Survival','Warrior-Fury','Shaman-Elemental','Evoker-Preservation','Monk-Mistweaver','Warrior-Protection','DemonHunter-Havoc','Mage-Fire','Mage-Frost','Druid-Feral','Warrior-Arms','Shaman-Enhancement','DeathKnight-Blood','Rogue-Assassination','DeathKnight-Frost','Evoker-Devastation','Evoker-Augmentation','DemonHunter-Vengeance','DeathKnight-Unholy','Rogue-Subtlety',}; local provider = {region='EU',realm='Garrosh',name='EU',type='weekly',zone=44,date='2025-09-24',data={Ab='Abgrundhexer:BAAALAAECgYIDwAAAA==.Absol:BAAALAADCgMIAwAAAA==.Abýz:BAACLAAFFIEHAAIBAAMIUhx9CgD5AAABAAMIUhx9CgD5AAAsAAQKgS0AAwEABwhyI3oQALUCAAEABwhyI3oQALUCAAIABgiXGwAAAAAAAAAA.',Ac='Acidera:BAAALAAECgQIBgABLAAFFAUIBwADACMZAA==.',Ad='Adéén:BAAALAAECggIEgABLAAFFAUIDQAEAI0gAA==.',Ag='Aggrofix:BAAALAADCgMIAwAAAA==.Aggroflummi:BAAALAAECggICAAAAA==.',Ah='Ahristasa:BAAALAADCggICAAAAA==.',Aj='Ajakis:BAAALAADCggIDwAAAA==.',Ak='Akané:BAAALAAECggICAAAAA==.',Al='Alariah:BAABLAAECoEgAAQFAAgI+RfcKgAcAgAFAAgIChbcKgAcAgAGAAIIwBB5eAB5AAAHAAEI5B9gKgBbAAAAAA==.Aleshane:BAAALAAECgEIAQAAAA==.Alexader:BAAALAAECgIIAgAAAA==.Alun:BAAALAAECgEIAQAAAA==.',Am='Amallia:BAAALAAECgQIBgAAAA==.Amandine:BAAALAAECgIIAgAAAA==.Amh:BAABLAAECoEYAAQIAAYIQhYVLgBWAQAIAAYIQhYVLgBWAQAJAAQIMQx5+gDEAAAKAAYIBARAUADDAAAAAA==.Aminara:BAAALAADCggICAAAAA==.',An='Andària:BAAALAAECgIIAwAAAA==.Annaa:BAACLAAFFIEKAAIKAAQIxBg1BgBUAQAKAAQIxBg1BgBUAQAsAAQKgSsAAgoACAjMHWwKALICAAoACAjMHWwKALICAAAA.Annekuzen:BAAALAAECgIIAgAAAA==.Annsarah:BAAALAAECgYIDAAAAA==.Anonymous:BAAALAADCgUICgAAAA==.Ansaguin:BAAALAADCgIIAgABLAAECgcIIwALADUTAA==.Anthenius:BAAALAAECgEIAQAAAA==.Anticron:BAAALAAECggIAQAAAA==.',Ar='Aragir:BAAALAAECgIIAgAAAA==.Armadie:BAAALAADCgcIBwAAAA==.Armadíe:BAAALAAECgYIDwAAAA==.Armorgeddon:BAAALAAECgYIDgAAAA==.Arwell:BAAALAAECgYICAAAAA==.Arístokrat:BAAALAAECgMICQAAAA==.',As='Ashamane:BAABLAAECoEZAAIMAAcIfg3eUABZAQAMAAcIfg3eUABZAQAAAA==.Astralixia:BAABLAAECoEWAAINAAYIWhqEUgC+AQANAAYIWhqEUgC+AQAAAA==.',At='Athail:BAAALAAECgYIDAABLAAFFAQICgAKAMQYAA==.Atzatharg:BAAALAAECggIEwAAAA==.',Aw='Awesomelulz:BAAALAAECgEIAQABLAAECgYIDAAOAAAAAA==.',Ax='Axolotlupi:BAAALAADCgUIBQAAAA==.',Ay='Aylena:BAAALAADCggICAAAAA==.',Az='Azeotropina:BAAALAAECgEIAQAAAA==.Azraelîan:BAAALAAECgIIAgAAAA==.',Ba='Baarandur:BAAALAADCgQIBgAAAA==.Baeer:BAAALAAECgEIAQAAAA==.Balouhblind:BAAALAADCgYIBgABLAAECgYIDwAOAAAAAA==.Balouuh:BAAALAAECgYIDwAAAA==.Balze:BAAALAADCgMIAQABLAAECggICQAOAAAAAA==.Bamo:BAAALAADCggIFwAAAA==.Bargan:BAAALAADCgcIBwAAAA==.Batmán:BAAALAAECgYIBgABLAAECgcIIgANANoTAA==.Bayura:BAAALAAECggIGQAAAQ==.',Be='Beefex:BAAALAADCggIFAAAAA==.Beefzy:BAABLAAECoEgAAINAAcIGiBcHQCAAgANAAcIGiBcHQCAAgAAAA==.Begu:BAAALAAECgYICQAAAA==.Bertie:BAAALAAECgIIAgAAAA==.Betox:BAAALAADCgcIBwAAAA==.',Bl='Blackdoom:BAAALAAECgIIAgAAAA==.Bladjoke:BAAALAADCgcIDgAAAA==.Blasterina:BAAALAADCgEIAQAAAA==.Blobfîsh:BAACLAAFFIEFAAIDAAII2hjjJQCjAAADAAII2hjjJQCjAAAsAAQKgSYABAMACAiyGxghAKMCAAMACAiyGxghAKMCAA8ABgjrATtwAHwAABAAAQg7AZpAACgAAAAA.Blockie:BAABLAAECoEZAAMPAAcIcBPdIQDYAQAPAAcIcBPdIQDYAQAQAAEISQ5YOwA6AAAAAA==.Bloodyhex:BAAALAAECgMIAwAAAA==.Bloodymäry:BAAALAAECgEIAgAAAA==.Blummí:BAAALAADCggIDQAAAA==.Blázee:BAAALAAECggICQAAAA==.',Bo='Bobderbär:BAEBLAAECoEbAAIRAAgI2hReFwAlAgARAAgI2hReFwAlAgAAAA==.Boggy:BAAALAADCgYICQAAAA==.Bonecrusher:BAAALAAECgEIAQAAAA==.Bonecrushy:BAAALAADCggICAAAAA==.Bonnechance:BAAALAADCgUIBQAAAA==.',Br='Brainhunter:BAABLAAECoEUAAMSAAgIAR9mJACQAgASAAgIVhtmJACQAgAMAAYIOSC3JQApAgABLAAECggIGQAGACogAA==.Brainingbad:BAABLAAECoEZAAMGAAgIKiBSEwC/AgAGAAgIKiBSEwC/AgAFAAMI1QkfjgCJAAAAAA==.Brainlock:BAAALAADCggICAABLAAECggIGQAGACogAA==.Brizz:BAAALAADCgQIBAAAAA==.Brokentusk:BAAALAAECgYIEwAAAA==.Bryismad:BAAALAAECgYICgAAAA==.Brøutus:BAAALAADCgYIBwAAAA==.',Bu='Bumbumweg:BAABLAAECoEUAAMSAAYIEhMNuAAPAQASAAUIeRMNuAAPAQAMAAIIjAt3nwBTAAAAAA==.',['Bâ']='Bârbare:BAAALAAECgUIBQAAAA==.Bâêrnig:BAAALAAECggIEQAAAA==.',['Bä']='Bärtank:BAAALAADCgIIAwAAAA==.',['Bí']='Bíerwanz:BAAALAAECgYIDAAAAA==.Bíllow:BAAALAAECgYIFwABLAAFFAIIBAAOAAAAAQ==.',['Bø']='Bøngøbøng:BAAALAAECgMIAQAAAA==.',Ca='Cade:BAABLAAFFIEFAAIFAAMIuAcQFQDJAAAFAAMIuAcQFQDJAAAAAA==.Cadidh:BAAALAAECgYICwAAAA==.Cake:BAAALAADCggIGQAAAA==.Calturion:BAAALAAECgIIAgAAAA==.Camorili:BAAALAADCggICAAAAA==.Carefree:BAAALAADCggIDgAAAA==.Carlomc:BAAALAAECgIIAgAAAA==.Carnitin:BAAALAADCgYIBgAAAA==.Casual:BAABLAAECoEqAAICAAgIRCTMAQA1AwACAAgIRCTMAQA1AwAAAA==.Cañuma:BAAALAAECgYIBwAAAA==.',Ce='Cecilian:BAAALAADCggICAAAAA==.Celestriá:BAAALAAECgMIAwAAAA==.Ceyli:BAAALAADCggIDwAAAA==.Ceyxe:BAAALAADCgIIAgAAAA==.',Ch='Chaosdeath:BAAALAAECggICgABLAAFFAIIBgAGAAcZAA==.Chaosgaia:BAAALAAECgYIDQAAAA==.Chaoslight:BAAALAAECggIDQABLAAFFAIIBgAGAAcZAA==.Chaosshadow:BAACLAAFFIEGAAIGAAIIBxkiFACgAAAGAAIIBxkiFACgAAAsAAQKgScAAgYACAg/ISsNAPwCAAYACAg/ISsNAPwCAAAA.Charlena:BAAALAADCggIEAAAAA==.Chelay:BAAALAAECgcIEgAAAA==.Chimaron:BAAALAAECgIIAgAAAA==.Chrispy:BAAALAAECgEIAQAAAA==.Chrowok:BAAALAAECgMIBgAAAA==.Chubbylumkin:BAAALAAECggICAAAAA==.',Co='Coimbra:BAAALAAECgYIDgAAAA==.Coll:BAAALAAECgMIAwAAAA==.Coraliné:BAABLAAECoEZAAIFAAcIERpQJwAuAgAFAAcIERpQJwAuAgABLAAFFAMIBgAFABgFAA==.Covén:BAAALAAECgIIBAAAAA==.',Cr='Critalya:BAAALAAECgcIBwAAAA==.Crybaby:BAABLAAECoEXAAITAAcI4RZpQwB1AQATAAcI4RZpQwB1AQABLAAECggIJAAUADklAA==.Crânki:BAAALAADCgcICAAAAA==.',Cu='Culprit:BAAALAAECgcIEAAAAA==.Cutout:BAAALAAECggICAAAAA==.',Cy='Cynoga:BAAALAAECgUIBQAAAA==.Cyreen:BAAALAADCgMIBAAAAA==.',Da='Dadreki:BAAALAAECgYIEQAAAA==.Dafóx:BAAALAAECgIIBAAAAA==.Dagobertha:BAAALAADCgcICwAAAA==.Dajimmy:BAAALAADCgcIBwAAAA==.Dakazu:BAAALAAECgQIBwAAAA==.Dalans:BAAALAADCggIGwAAAA==.Dalrima:BAABLAAECoEdAAIBAAcIJxFKRwCLAQABAAcIJxFKRwCLAQAAAA==.Danielá:BAABLAAECoEdAAIVAAgIkwZeiwAdAQAVAAgIkwZeiwAdAQAAAA==.Dar:BAAALAAECgcIBwABLAAECgcIFwASACQbAA==.Darkbow:BAAALAAECgIIBAAAAA==.Darkflash:BAAALAADCggICAAAAA==.Darksmarargd:BAAALAADCgYIEQAAAA==.Darthmuh:BAAALAAECgQIBAABLAAECgQIBwAOAAAAAA==.',De='Deltâ:BAAALAAECgUIBQAAAA==.Delørix:BAAALAADCgcIDQAAAA==.Demonslay:BAAALAADCgcIBwAAAA==.Demônhûnter:BAAALAAECgYICAABLAAFFAMIBQAJAF4TAA==.Dentalentes:BAAALAAECggICwAAAA==.Derzerp:BAAALAADCgMIAwAAAA==.Derzerpa:BAAALAAECgYIEAAAAA==.Dexymage:BAAALAAECgYIBgAAAA==.',Di='Dianty:BAABLAAECoEjAAILAAcINRMbHQCBAQALAAcINRMbHQCBAQAAAA==.',Do='Docgobby:BAAALAAECgMIBAAAAA==.Doktore:BAAALAADCgEIAQAAAA==.Dollyburster:BAAALAAECggICAAAAA==.Donnerschlag:BAAALAADCggIJAAAAA==.Doragan:BAAALAADCggIEAAAAA==.Dorino:BAAALAADCggIFwAAAA==.Dorkifan:BAAALAADCgcIDQABLAAECgEIAQAOAAAAAA==.',Dr='Drachentüri:BAAALAADCgEIAQAAAA==.Draggrozwerk:BAABLAAECoEgAAISAAgIpBb9TwDwAQASAAgIpBb9TwDwAQAAAA==.Drakzon:BAAALAAECgYIEgAAAA==.Drawâ:BAAALAADCggICAAAAA==.Drogul:BAAALAAECgYIBQAAAA==.Drâggrô:BAAALAADCggICAAAAA==.Drædful:BAAALAADCggICAAAAA==.',Du='Dudee:BAAALAAECggIEwAAAA==.Duplina:BAACLAAFFIEFAAIJAAMIXhNVDgABAQAJAAMIXhNVDgABAQAsAAQKgSgAAgkACAgiI+kPACcDAAkACAgiI+kPACcDAAAA.Durbomir:BAAALAAECgYIDQAAAA==.',['Dä']='Dämonenfluse:BAAALAADCgcIBwAAAA==.Dämonenhérz:BAAALAAECgIIBAAAAA==.',['Dé']='Désteny:BAAALAAECgQIBgAAAA==.',['Dó']='Dón:BAABLAAECoEbAAISAAcImRRzegCJAQASAAcImRRzegCJAQAAAA==.',['Dö']='Dödliknödli:BAAALAAECgcIEQAAAA==.',['Dü']='Düsendrieb:BAAALAADCgEIAQAAAA==.',Ef='Efey:BAABLAAECoEdAAIVAAgI+BzZHwCkAgAVAAgI+BzZHwCkAgABLAAFFAMIBQAJAF4TAA==.',Ei='Eikinskjaldi:BAAALAAECgIIAwAAAA==.Einszweidrei:BAABLAAECoEWAAIVAAYInSHQNgAoAgAVAAYInSHQNgAoAgAAAA==.',El='Eleanorá:BAAALAADCgYIBgAAAA==.Elendír:BAAALAADCgcICwAAAA==.Eleonoré:BAAALAADCggICQAAAA==.Elfríedé:BAAALAADCgYIBgAAAA==.Elyon:BAAALAADCgQIBAAAAA==.',Em='Eminemxx:BAAALAADCggICwAAAA==.Emprosia:BAAALAADCgIIAgABLAAECgcIFgAWAE8WAA==.',Eo='Eonara:BAAALAADCgIIAgAAAA==.',Eq='Eqedqe:BAABLAAECoEWAAIBAAcIeyTODQDNAgABAAcIeyTODQDNAgAAAA==.Equitis:BAAALAADCggICAAAAA==.',Er='Erytheia:BAABLAAECoEdAAIXAAcI2hfUEADzAQAXAAcI2hfUEADzAQAAAA==.Erza:BAAALAAECgIIAgAAAA==.',Es='Escalîa:BAAALAAECgMIBgAAAA==.Espaja:BAAALAADCgcICAAAAA==.Espajo:BAAALAAECgYIBgAAAA==.Espresso:BAAALAAECggIDgABLAAFFAIIBgAEAL4fAA==.Estaria:BAAALAAECggICAAAAA==.Estrîâ:BAAALAAECgYIBgAAAA==.',Eu='Euterlyptus:BAAALAADCgcIFAAAAA==.',Ev='Evingolis:BAAALAAFFAIIAgAAAA==.Evoz:BAAALAAECgIIAwABLAAECggIIAAFAPkXAA==.',Ex='Exelsíus:BAAALAADCgQIBQAAAA==.',Ey='Eycha:BAABLAAECoEnAAMJAAgItSLYEQAdAwAJAAgItSLYEQAdAwAKAAcIixNkKACrAQAAAA==.Eysangel:BAAALAADCgcIBwAAAA==.',Fa='Fadril:BAAALAAECgIIAgAAAA==.Fandaerin:BAAALAAECgYICAAAAA==.Fanji:BAAALAAECgYIEgAAAA==.Faronea:BAAALAAECgEIAQAAAA==.Fayence:BAABLAAECoEmAAITAAgI/hJgNwCuAQATAAgI/hJgNwCuAQAAAA==.',Fe='Felnea:BAAALAAECggICAAAAA==.Feyz:BAAALAAECggIDgAAAA==.',Fi='Finaliin:BAAALAAECgcIEQAAAA==.Finstermann:BAABLAAECoEfAAIWAAgItBKnRADGAQAWAAgItBKnRADGAQAAAA==.',Fl='Flatcko:BAABLAAECoEbAAIDAAgIRggcewBTAQADAAgIRggcewBTAQAAAA==.Fleischie:BAABLAAECoEXAAMTAAgIAwrpSgBTAQATAAgIAwrpSgBTAQABAAYIYww2bAARAQAAAA==.Fleischíe:BAAALAADCggIDAABLAAECggIFwATAAMKAA==.Flirá:BAABLAAECoEUAAISAAYIPBFnkABdAQASAAYIPBFnkABdAQAAAA==.Flunkey:BAAALAADCgIIAgAAAA==.',Fr='Freudidh:BAAALAAECgQIBAABLAAECgQIBgAOAAAAAA==.Fruitdude:BAAALAAECgUIBQAAAA==.Fréúdii:BAAALAAECgQIBgAAAA==.',Fu='Fuchsgeist:BAABLAAECoEdAAILAAgIfRMgFQDkAQALAAgIfRMgFQDkAQAAAA==.Fuchslein:BAABLAAECoEZAAIYAAgIKw7UHwB6AQAYAAgIKw7UHwB6AQAAAA==.Furchenbeere:BAAALAADCggICAAAAA==.',Ga='Gandarel:BAAALAAECgIIAgABLAAECgQICQAOAAAAAA==.Gandarwa:BAAALAAECgQICQAAAA==.Gargamelh:BAAALAAECgUIBQAAAA==.Gasbo:BAAALAADCggICAAAAA==.',Ge='Geddes:BAAALAADCggICAAAAA==.Gezmo:BAAALAADCgYIBQABLAAECgYIBwAOAAAAAA==.',Gh='Ghostbuzz:BAAALAADCgUIBQAAAA==.',Gi='Giggety:BAAALAAECggICAAAAA==.Gingayce:BAAALAAECgEIAQAAAA==.',Go='Golgary:BAACLAAFFIEGAAIZAAIIfx8PDAC5AAAZAAIIfx8PDAC5AAAsAAQKgSUAAhkACAjWIhgGACADABkACAjWIhgGACADAAAA.Golgoth:BAAALAAECgEIAQAAAA==.Gondalf:BAAALAAECgYIDwAAAA==.',Gr='Grantelbear:BAAALAAECggICgABLAAFFAMICwADAA4iAA==.Grauschimmer:BAABLAAECoEnAAMJAAcIYxfXXgD+AQAJAAcIYxfXXgD+AQAIAAYIAwwAAAAAAAAAAA==.Greenarrów:BAAALAADCgcIEAABLAAECgcIIgANANoTAA==.Grimbo:BAAALAAECgEIAQAAAA==.Gripinho:BAAALAAECggIDwABLAAFFAUIDAALAKMdAA==.Groom:BAAALAAECgEIAQAAAA==.Großváter:BAAALAADCgcIEAAAAA==.Grönerotto:BAAALAADCggIDgAAAA==.',Gu='Gulashman:BAAALAAFFAIIAgAAAA==.Gurukk:BAAALAADCggICAAAAA==.Gustavogusto:BAAALAADCggICAAAAA==.',Gw='Gwiltor:BAABLAAECoEWAAIWAAYItxKtVgCFAQAWAAYItxKtVgCFAQAAAA==.Gwismo:BAAALAADCggICQABLAAECgYIBwAOAAAAAA==.',['Gâ']='Gâladriel:BAAALAAECgcIDwAAAA==.',['Gö']='Gönrgy:BAABLAAECoEYAAMMAAYIkCPkHgBYAgAMAAYI3CLkHgBYAgASAAEIhCG0/gBgAAABLAAFFAIIBAAOAAAAAA==.',['Gø']='Gøangár:BAAALAADCgcIBwAAAA==.',['Gû']='Gûnther:BAAALAADCggIBgAAAA==.',Ha='Hado:BAAALAAECgEIAQAAAA==.Haifer:BAAALAADCggIFQAAAA==.Hakuk:BAAALAADCgQIBQAAAA==.Harmony:BAAALAADCggICAAAAA==.',He='Healduin:BAAALAAECgQIDQABLAAECgcIIwALADUTAA==.Hearth:BAABLAAECoEbAAIWAAgIkhrwKQBGAgAWAAgIkhrwKQBGAgAAAA==.Helmbert:BAAALAADCgcICQAAAA==.Hexeramus:BAAALAADCggIEAAAAA==.Heyimdirk:BAAALAADCgcIBwAAAA==.',Hl='Hlifar:BAAALAADCggICAAAAA==.',Ho='Holdagur:BAAALAADCggIDgAAAA==.Holyhollow:BAAALAADCgYIBgAAAA==.Holythunder:BAAALAADCggIFgAAAA==.Holzkern:BAAALAAECggIEQAAAA==.Homba:BAAALAAECgUIBQAAAA==.Horith:BAAALAADCggIDgABLAAECgYIBwAOAAAAAA==.Horstbert:BAAALAADCgUIBQAAAA==.',Hu='Hugin:BAAALAAECgMIBgAAAA==.',Hy='Hybrian:BAAALAAECggIEAAAAA==.Hyperaktiv:BAAALAADCgQIBAAAAA==.',['Hí']='Híghlandèr:BAAALAAECgMIBAAAAA==.',Il='Ilaser:BAABLAAECoEXAAIaAAgIoRnaNgBbAgAaAAgIoRnaNgBbAgAAAA==.Illysanna:BAAALAADCgIIAgABLAAFFAQICgAKAMQYAA==.',In='Incôrrectx:BAAALAADCgUIBQABLAAFFAUIDAARAPAVAA==.Infamous:BAAALAAECgIIBgAAAA==.Ingomage:BAABLAAECoEUAAQbAAgIuRjRCgBgAQAEAAgILBOlVgDgAQAbAAUIjBfRCgBgAQAcAAEIRxCzggAuAAAAAA==.Inrï:BAAALAAECgQICAAAAA==.Inura:BAAALAAECgEIAQAAAA==.',Ir='Irellya:BAAALAADCgYICwAAAA==.',Is='Isigard:BAAALAADCggIHQAAAA==.Isummer:BAABLAAECoEuAAIGAAgI5iHXCgARAwAGAAgI5iHXCgARAwAAAA==.',Ix='Ixania:BAAALAADCggICAAAAA==.',Ja='Jahar:BAABLAAECoEXAAISAAcIJBsvQgAZAgASAAcIJBsvQgAZAgAAAA==.Jaluni:BAABLAAECoEWAAMNAAgIUhrkWQCqAQANAAYIfxvkWQCqAQAWAAUI4QmjiwCxAAAAAA==.Jaquénto:BAABLAAECoEWAAISAAYI3RusXwDHAQASAAYI3RusXwDHAQAAAA==.Jatayu:BAAALAADCggIDAAAAA==.Jazmín:BAAALAADCggICAABLAAFFAIIBgAEAL4fAA==.',Je='Jenni:BAABLAAECoEfAAMBAAgIcSEHCwDoAgABAAgIcSEHCwDoAgAdAAEIOArcPwA1AAAAAA==.',Jh='Jhinn:BAABLAAECoEWAAIaAAgIaRpHLwB6AgAaAAgIaRpHLwB6AgAAAA==.',Jo='Jogia:BAAALAADCgcICQABLAAECgIIAgAOAAAAAA==.Joglyce:BAAALAAECgMIBwAAAA==.Joki:BAAALAADCgcIDwABLAAECgIIAgAOAAAAAA==.Jolany:BAAALAAECgYIBgAAAA==.Jolién:BAAALAADCgYIDgAAAA==.Jollo:BAAALAADCgcIBwAAAA==.Jongo:BAAALAADCggIDQAAAA==.Joulie:BAAALAAECgQIBQAAAA==.',Ju='Judo:BAABLAAECoEgAAIJAAgIwCOZDQA1AwAJAAgIwCOZDQA1AwAAAA==.Junji:BAAALAAECgYIBgAAAA==.Juwie:BAAALAADCgcIEQABLAAECgIIAgAOAAAAAA==.',['Jó']='Jóna:BAAALAAECgYICQAAAA==.',Ka='Kaeldrisia:BAAALAADCggIDgAAAA==.Kaeyghi:BAAALAAECgIIBAAAAA==.Kaliraz:BAAALAAECgYIBgAAAA==.Kallor:BAAALAADCgYIBgAAAA==.Kampfeuter:BAAALAAECgYIDgAAAA==.Kangul:BAAALAAECgYIDwAAAA==.Kantha:BAAALAAECggIAgAAAA==.Karamelli:BAABLAAECoFBAAMLAAgIUiLmBQD5AgALAAgI/iHmBQD5AgARAAcIQCDuDgCOAgAAAA==.Karnak:BAAALAADCgcIDwAAAA==.Karîon:BAAALAADCgcIFAAAAA==.Katerine:BAAALAADCgMIAwAAAA==.',Ke='Keldashdalan:BAABLAAECoEXAAIaAAgIRRQmTgANAgAaAAgIRRQmTgANAgAAAA==.',Kh='Khardir:BAAALAAECgIIAgAAAA==.',Ki='Kikø:BAAALAADCggIDwAAAA==.Kill:BAACLAAFFIEIAAMeAAQIdQyfAAAtAQAeAAQIVQyfAAAtAQAVAAEInwrLNgBLAAAsAAQKgSoAAx4ACAiBIvwBACkDAB4ACAiBIvwBACkDABUAAQi/Gl3GAE8AAAAA.Killerkaio:BAABLAAECoEYAAIEAAcIYB/GQAAqAgAEAAcIYB/GQAAqAgAAAA==.Killerkaió:BAAALAADCggICAABLAAECgcIGAAEAGAfAA==.Kinderbueno:BAAALAAECgUICgABLAAFFAYIFgAEAHMgAA==.Kiralia:BAAALAADCgcIBwAAAA==.Kissme:BAABLAAECoEjAAIfAAgIBgoyEAC9AQAfAAgIBgoyEAC9AQAAAA==.',Kn='Knochenluda:BAAALAAECgMIBgAAAA==.Knödlidödli:BAAALAADCgcICwABLAAECgcIFwASACQbAA==.',Ko='Koboldfee:BAAALAAECgYIBgAAAA==.Kowaki:BAAALAAECgYIBgAAAA==.',Kr='Kraxion:BAAALAAECgIIAgAAAA==.Krieg:BAAALAAECggICgAAAA==.Krumm:BAAALAADCggICAAAAA==.Kruppe:BAAALAADCgQIBAAAAA==.',Ks='Ksderbozz:BAAALAAECgYICAAAAA==.',Ku='Kuhmuckl:BAAALAAECggIDQAAAA==.Kurschd:BAABLAAECoEbAAIJAAcIUh/YRABDAgAJAAcIUh/YRABDAgAAAA==.Kuschelbräu:BAAALAADCgUIBQAAAA==.Kuzii:BAABLAAECoEnAAMPAAgIugWgVwDmAAADAAgIKQWFnQDyAAAPAAgIhQOgVwDmAAAAAA==.',Ky='Kyreya:BAAALAADCggIGQABLAAECgYIHAANALsUAA==.Kyriae:BAABLAAECoEcAAINAAYIuxRWiQAzAQANAAYIuxRWiQAzAQAAAA==.',['Ká']='Kálim:BAABLAAECoEWAAIJAAcIIBhnYwD0AQAJAAcIIBhnYwD0AQAAAA==.',['Ké']='Kénpachi:BAAALAADCgEIAQAAAA==.',La='Lacyina:BAAALAAECgUIEAAAAA==.Larry:BAAALAAECgUICAAAAA==.Laysana:BAAALAAECggICAAAAA==.',Le='Learra:BAAALAAECgYIBgAAAA==.Lehana:BAAALAADCgMIAwAAAA==.Leilanni:BAAALAAECgMIAwAAAA==.Leilla:BAAALAADCggIHwAAAA==.Leisha:BAAALAAECgMIBAAAAA==.Lelani:BAABLAAECoEZAAMBAAgI3B6EEAC1AgABAAgI3B6EEAC1AgATAAYILgwwUwAxAQAAAA==.',Li='Linna:BAAALAADCgQIBAAAAA==.Linstren:BAAALAAECggICAAAAA==.Lipovitan:BAAALAAECggIEgAAAA==.Littelbird:BAAALAAECgUIBwAAAA==.',Lo='Loa:BAAALAADCgQIAwAAAA==.Lolle:BAAALAADCggICAAAAA==.Lombardis:BAAALAADCggICAAAAA==.Loonix:BAAALAADCgUIBQAAAA==.Loordurion:BAAALAAECgIIAgAAAA==.Loraxis:BAAALAADCgUIBQAAAA==.Lorena:BAAALAAECgcIBwAAAA==.Louiscypher:BAABLAAECoEcAAIgAAcIfx7iDQBAAgAgAAcIfx7iDQBAAgAAAA==.',Lu='Lucalappen:BAAALAADCgcIBwABLAAFFAMICgATACobAA==.Lucyari:BAAALAADCgYIBgAAAA==.Lukani:BAAALAAECggICgAAAA==.Lukrezîa:BAABLAAECoEdAAIEAAgINQdFgwBkAQAEAAgINQdFgwBkAQAAAA==.Lusarios:BAAALAAECgYIBwAAAA==.Lustknochen:BAAALAAECgYIBgAAAA==.',Ly='Lyfel:BAAALAADCgYICgAAAA==.Lykanion:BAAALAADCgUIBQAAAA==.Lynnsham:BAAALAADCggICAAAAA==.Lyrandis:BAAALAADCgMIAwAAAA==.',['Lí']='Líá:BAAALAADCgMIAwAAAA==.',['Lú']='Lútzi:BAAALAADCgcIBwAAAA==.',Ma='Macpower:BAAALAAECgcICQAAAA==.Maggow:BAAALAAFFAIIBAAAAQ==.Magicnursê:BAAALAADCggICAAAAA==.Majar:BAAALAADCggICAAAAA==.Makima:BAAALAAECgIIAgAAAA==.Maldiria:BAAALAAECgYIBwAAAA==.Mandoliene:BAAALAADCgYIEQAAAA==.Manninator:BAAALAAECggIDgAAAA==.Maníss:BAAALAAECgYICAAAAA==.Maphi:BAAALAADCgYIBgAAAA==.Marciey:BAAALAAECgMIAgAAAA==.Mariton:BAABLAAECoEmAAIZAAgIcCQeAwBUAwAZAAgIcCQeAwBUAwAAAA==.Maryora:BAAALAADCgMIAwAAAA==.Masataka:BAABLAAECoEkAAIUAAgIOSVvAAByAwAUAAgIOSVvAAByAwAAAA==.Massá:BAAALAAECgYIEAAAAA==.Mausefalle:BAACLAAFFIEUAAIWAAYIfhlnAwAgAgAWAAYIfhlnAwAgAgAsAAQKgSsAAhYACAilJpoAAJgDABYACAilJpoAAJgDAAAA.',Me='Meixiu:BAAALAAECgUIBwAAAA==.Melandry:BAAALAADCggIDwAAAA==.Melódias:BAAALAAECgIIAgABLAAFFAMICwADAA4iAA==.Meowz:BAAALAADCggIEAAAAA==.Merlinmage:BAAALAAECgQIBAAAAA==.Meryn:BAABLAAECoEkAAIhAAgIexyMDgCpAgAhAAgIexyMDgCpAgAAAA==.Metrexa:BAABLAAECoEfAAIDAAgISA16VgC6AQADAAgISA16VgC6AQAAAA==.Metze:BAAALAADCgcIBwAAAA==.Meuchelmichi:BAAALAAECgQIBwAAAA==.',Mh='Mhaardi:BAAALAAECgEIAQAAAA==.',Mi='Miimic:BAAALAADCgcIBwAAAA==.Miralee:BAAALAAECgYIBgAAAA==.',Mo='Mochirogue:BAAALAADCgIIAgAAAA==.Mohlturm:BAAALAAECgYIDgABLAAECgYIFAAiAA8dAA==.Monkinho:BAACLAAFFIEMAAMLAAUIox0YAwDPAQALAAUIox0YAwDPAQARAAEIugNYFAA6AAAsAAQKgSoAAgsACAjaJT0BAG8DAAsACAjaJT0BAG8DAAAA.Monokumá:BAAALAADCgcIEwABLAAECgIIBgAOAAAAAA==.Monuria:BAAALAAECgYIBgABLAAFFAIIBgAEAL4fAA==.Moralos:BAAALAADCggIGAAAAA==.Morse:BAAALAAECgIIAgAAAA==.Mortality:BAABLAAECoEUAAIJAAgIQAw/jQChAQAJAAgIQAw/jQChAQAAAA==.Mortalmorti:BAAALAADCgcIBwAAAA==.Mostreta:BAAALAAECggICQAAAA==.',Mu='Mubøn:BAAALAADCggIEQAAAA==.Muhffelig:BAAALAAECgIIAwABLAAECgYIDAAOAAAAAA==.Musambani:BAAALAADCgIIAgABLAAECggIFAAbALkYAA==.Musclemán:BAAALAAECgUIBwAAAA==.',My='Mysticelfe:BAAALAAECgYICQAAAA==.',['Mà']='Màldiria:BAAALAADCggIJwAAAA==.Màylin:BAAALAAECgcICAAAAA==.',['Má']='Máríéé:BAAALAAECgEIAQAAAA==.',['Mí']='Mídgárd:BAAALAAECggICAAAAA==.',['Mî']='Mîcah:BAAALAADCgcIBwAAAA==.',['Mü']='Mühelos:BAAALAADCggICAAAAA==.Müllgesicht:BAAALAADCggIDAAAAA==.',Na='Naehla:BAAALAADCggICAAAAA==.Nafia:BAAALAAECgYIDAAAAA==.Nagsôr:BAAALAAECggIAQAAAA==.Nailo:BAAALAAECggIEQAAAA==.Nakira:BAAALAAECggICAAAAA==.Nastý:BAAALAADCgIIAgAAAA==.Nayama:BAAALAADCggIDwAAAA==.Naìla:BAAALAADCggIEQAAAA==.',Ne='Near:BAACLAAFFIELAAMjAAUIEhy6BAC4AQAjAAUIEhy6BAC4AQAXAAEIpQr+EwBDAAAsAAQKgS0ABCMACAhyIv4FACYDACMACAhyIv4FACYDACQAAwilEo0SAI4AABcAAQhmC5M3ADkAAAAA.Nearm:BAAALAAECgIIAgABLAAFFAUICwAjABIcAA==.Nebra:BAAALAAECgQIBwAAAA==.Neklishe:BAAALAADCgIIAgABLAAECggICQAOAAAAAA==.Nepharox:BAABLAAECoEYAAIfAAgIORakCABYAgAfAAgIORakCABYAgAAAA==.Neroonia:BAAALAADCgcIBwABLAADCggICwAOAAAAAA==.Nerup:BAAALAADCggIDAABLAAFFAIIAgAOAAAAAA==.Nerò:BAAALAADCggIDwAAAA==.Nerôôîâ:BAAALAADCggICwAAAA==.Nexgenaddy:BAABLAAECoEUAAMcAAcIAhE2KQC7AQAcAAcIAhE2KQC7AQAEAAMIJgNh0gBXAAAAAA==.',Ni='Nichtdiemama:BAAALAAECgUIBwAAAA==.Niemánd:BAACLAAFFIEGAAIFAAMIGAWNGACxAAAFAAMIGAWNGACxAAAsAAQKgTsAAgUACAjVFxYkAEMCAAUACAjVFxYkAEMCAAAA.Nightshamen:BAABLAAECoExAAINAAgIZBqAJQBaAgANAAgIZBqAJQBaAgAAAA==.Nimbia:BAAALAAECgQIAgAAAA==.Nindel:BAAALAADCgcIBwAAAA==.Nipsy:BAAALAADCggIDwAAAA==.',No='Noiram:BAAALAAECgQIBAAAAA==.',Nu='Nutzlos:BAABLAAECoElAAITAAgINRkTHABWAgATAAgINRkTHABWAgAAAA==.',Nv='Nvstyy:BAAALAADCgIIAgAAAA==.',Ny='Nynthara:BAAALAAECgMIAwAAAA==.Nysothunwë:BAAALAAECggICAAAAA==.Nyted:BAAALAAECgYICQAAAA==.',['Nê']='Nêbrà:BAAALAADCgMIAwABLAAECgQIBwAOAAAAAA==.',['Nî']='Nîfune:BAAALAADCgYIDAAAAA==.',['Nô']='Nôbody:BAAALAAECgQIBAAAAA==.',Oh='Ohnoi:BAABLAAECoEXAAMFAAcIeSGhFQCjAgAFAAcIeSGhFQCjAgAGAAQIkBgcWQApAQAAAA==.',Ol='Olirasa:BAABLAAECoEiAAIXAAgIrRLUEQDiAQAXAAgIrRLUEQDiAQAAAA==.',Oo='Oorastve:BAAALAADCgcIBwAAAA==.',Or='Orkania:BAAALAAECgIIAgAAAA==.Orlin:BAAALAADCgIIAQAAAA==.',Pa='Paladumia:BAAALAADCggICAAAAA==.Pandaduda:BAAALAAECggIDwABLAAFFAMICwADAA4iAA==.Pandemius:BAAALAADCgcIBwAAAA==.Pandîa:BAAALAAECgIIAgAAAA==.Panem:BAABLAAECoEdAAMJAAcICiQeKQCnAgAJAAcICiQeKQCnAgAKAAcIdxp2GAAgAgAAAA==.Pani:BAAALAADCgcIBwAAAA==.Panker:BAAALAAECgcICgAAAA==.Pantalaimon:BAABLAAECoEXAAIiAAYISwpR1AAzAQAiAAYISwpR1AAzAQAAAA==.Paruc:BAABLAAECoEYAAIeAAgI+QMLKACAAAAeAAgI+QMLKACAAAAAAA==.Paruuk:BAABLAAECoEbAAITAAcIZA26VAArAQATAAcIZA26VAArAQAAAA==.Pastori:BAAALAADCgcICwAAAA==.',Pe='Pentra:BAAALAADCgYIBgABLAAECgcIFgAWAE8WAA==.Pepperdyne:BAABLAAECoEiAAINAAcI2hO4YgCSAQANAAcI2hO4YgCSAQAAAA==.Peronia:BAAALAADCggIEAAAAA==.',Ph='Phorix:BAAALAADCggIBQAAAA==.Phôsy:BAAALAAECgYIBgAAAA==.',Pl='Planiox:BAAALAAECgEIAgAAAA==.Plonic:BAAALAAECggIEAAAAA==.',Pr='Pre:BAABLAAECoEYAAIeAAYIExRCEwCBAQAeAAYIExRCEwCBAQAAAA==.',Py='Pytthia:BAAALAAECgQIBAABLAAECggIHwABAHEhAA==.',Pz='Pzudemlanlos:BAABLAAECoEaAAIaAAgInyDzFQD9AgAaAAgInyDzFQD9AgABLAAECggIKgACAEQkAA==.',Qu='Quely:BAAALAADCggIDQAAAA==.Quendo:BAABLAAECoEUAAIlAAYIIhysFwDYAQAlAAYIIhysFwDYAQAAAA==.Quincy:BAAALAAECgYIDgAAAA==.',Ra='Raeny:BAAALAAECgQICAAAAA==.Raenyres:BAABLAAECoEhAAIaAAcIpSTIHwDGAgAaAAcIpSTIHwDGAgAAAA==.Raflaria:BAAALAADCggICAAAAA==.Rahkua:BAAALAAECgYICwAAAA==.Rakanot:BAAALAADCgUIBQABLAADCggIEQAOAAAAAA==.Rakhalár:BAAALAAECggICAAAAA==.Ranish:BAABLAAECoEUAAIPAAgIkRL1GwD9AQAPAAgIkRL1GwD9AQAAAA==.Rastinaa:BAAALAADCgcICgAAAA==.Ratos:BAAALAADCggIDwAAAA==.Ravaan:BAABLAAECoEgAAMQAAgIIgyZEQB8AQAQAAgIIgyZEQB8AQADAAEI5QFc5AAgAAAAAA==.Ravé:BAAALAADCggICAAAAA==.Raysham:BAABLAAECoEkAAIWAAgINx6BFgDJAgAWAAgINx6BFgDJAgAAAA==.Raysome:BAAALAADCgcIBwAAAA==.Razkul:BAABLAAECoEZAAIDAAYIZBiDVQC9AQADAAYIZBiDVQC9AQAAAA==.Razorxy:BAABLAAECoEXAAMJAAYIVCAzWAAOAgAJAAYIPB4zWAAOAgAIAAYI5BnHIAC5AQAAAA==.',Re='Reavz:BAAALAADCgQIBAABLAAECgUIBQAOAAAAAA==.Reddraenei:BAAALAADCggIGwABLAAECgIIAgAOAAAAAA==.Reigam:BAAALAADCgMIAwAAAA==.Reshala:BAAALAAECggICgAAAA==.Respire:BAABLAAECoEnAAIWAAgINhceLwApAgAWAAgINhceLwApAgAAAA==.Rexlo:BAAALAAECgQIBAAAAA==.',Ri='Riddler:BAAALAADCgEIAQABLAAECgcIIgANANoTAA==.Ringix:BAAALAAECgMIBwAAAA==.Ripjerry:BAAALAADCggICAAAAA==.Rishka:BAAALAAECgYIAwAAAA==.Rixda:BAAALAADCgcIDAAAAA==.',Ro='Rocknock:BAAALAADCgcIDQAAAA==.Roksa:BAAALAAECgYIDwAAAA==.Rosenritter:BAAALAAECgMIAwAAAA==.',Ru='Rubert:BAAALAAECgEIAQABLAAECgcIIwALADUTAA==.Runes:BAAALAAECgIIBgAAAA==.',Ry='Ryzy:BAAALAAECggIAwAAAA==.',['Rì']='Rìck:BAAALAAECgMICQAAAA==.',['Rí']='Rípeyes:BAACLAAFFIELAAIDAAMIDiLQEwAiAQADAAMIDiLQEwAiAQAsAAQKgSQAAwMACAinHrccAL4CAAMACAinHrccAL4CAA8AAQiLHyx7AFUAAAAA.Rípeyesmama:BAAALAAECgQIBAAAAA==.',Sa='Saamari:BAAALAAECgYIDAAAAA==.Sackbeisser:BAAALAADCggIHwAAAA==.Sahrrama:BAABLAAECoEgAAMQAAgIfxkHCAAnAgAPAAgI+RdTEgBMAgAQAAgIwBMHCAAnAgAAAA==.Sajety:BAAALAAECgQIBAAAAA==.Saltica:BAAALAAECgMIAgAAAA==.Samclap:BAAALAAECgYIBgABLAAECgYIDAAOAAAAAA==.Samántha:BAAALAAECgMICQAAAA==.Sanrylar:BAAALAAECgYIEQAAAA==.Sansebastian:BAAALAAECggIDQAAAA==.Saphixe:BAAALAAECggIEAAAAA==.Sapinho:BAAALAAECggIDwABLAAFFAUIDAALAKMdAA==.Sarani:BAAALAADCggICAABLAAECgcIFgAWAE8WAA==.Sashinho:BAAALAAECgcIEQABLAAFFAUIDAALAKMdAA==.Savada:BAAALAADCggIDQAAAA==.Saydie:BAAALAAECgMIBAAAAA==.Sayge:BAAALAADCgIIAgAAAA==.',Sc='Schattenriss:BAAALAADCggIHwAAAA==.Schaumkrone:BAAALAAECgYIDwAAAA==.Schmona:BAAALAADCggICAAAAA==.Schmug:BAAALAADCgUICQAAAA==.Schnakkami:BAAALAAECgEIAQAAAA==.Schnakkili:BAAALAAECgUIBQAAAA==.Schneeflockè:BAAALAADCgcIBwAAAA==.Schokocrossi:BAAALAAECgIIAgAAAA==.Schrotkäppch:BAAALAAECgQICwAAAA==.Scârlêtt:BAAALAAECgUIBQAAAA==.',Se='Sebine:BAABLAAECoEXAAMJAAYIVBc+hACyAQAJAAYIVBc+hACyAQAKAAQIyBRuSQDwAAAAAA==.Seelass:BAAALAAECgUICwAAAA==.Seelenpein:BAAALAADCggICAAAAA==.Senista:BAAALAADCggIEAAAAA==.Sepsia:BAAALAADCgcIBwAAAA==.Serafíen:BAAALAADCgYIBgAAAA==.Seranava:BAABLAAECoEXAAIKAAcIVB8iEQBlAgAKAAcIVB8iEQBlAgAAAA==.Sergra:BAABLAAECoEgAAMiAAcI0A3rxgBJAQAiAAcI0A3rxgBJAQAgAAYIwQgWKQDtAAAAAA==.Sertosu:BAAALAADCgcIBwAAAA==.',Sh='Shamu:BAAALAADCgMIAwAAAA==.Shanlana:BAABLAAECoEWAAMWAAcITxaWRQDDAQAWAAcIzxKWRQDDAQAfAAYIXBU8EwCLAQAAAA==.Shanuq:BAAALAAECggICAAAAA==.Sheele:BAAALAAECgMIAwAAAA==.Shendo:BAAALAADCggICAAAAA==.Sheyleen:BAAALAADCggICAABLAAECgMIBAAOAAAAAA==.Shungy:BAAALAADCggIBwAAAA==.Shâdôw:BAABLAAECoEXAAIlAAcItRkhFwDeAQAlAAcItRkhFwDeAQAAAA==.Shírana:BAABLAAECoEkAAMFAAgI8hfoMgDyAQAFAAgI8hfoMgDyAQAGAAYIdBJJRwB3AQAAAA==.',Si='Sierah:BAAALAADCgcIBwAAAA==.Silverharley:BAAALAAECgMICQAAAA==.Simaliá:BAAALAAECgcIDQAAAA==.Sinclairsthx:BAAALAAECgMIBQABLAAECggIFQAZAOEfAA==.Sindragose:BAABLAAECoEWAAISAAYIYASW1gDEAAASAAYIYASW1gDEAAAAAA==.Sitandra:BAAALAAECgMIBAAAAA==.',Sk='Skeeb:BAAALAAECgcIDwABLAAECgcIHAAJALkcAA==.Skidiwidi:BAABLAAECoEcAAQJAAcIuRxiQgBKAgAJAAcIuRxiQgBKAgAKAAYI5w/ROABKAQAIAAMI/Qr3UAB0AAAAAA==.Skylara:BAAALAADCggIEAAAAA==.Skywálker:BAAALAAECgIIAwABLAAECgcIIgANANoTAA==.',Sl='Slark:BAAALAADCggICAABLAAECgcIFwAJAH8jAA==.Sliwowitz:BAAALAAECggIDwAAAA==.',Sm='Smixy:BAAALAAECgcIDwAAAA==.Smoxox:BAAALAADCgIIAgABLAAECgcIFwASACQbAA==.Smârte:BAAALAAECggIDAAAAA==.Smìlla:BAAALAAECgQIBAABLAAECggIEQAOAAAAAA==.',So='Solunaria:BAABLAAFFIEGAAIEAAIIvh86IwC8AAAEAAIIvh86IwC8AAAAAA==.Sorichronos:BAAALAAECgYIEAAAAA==.Soylentgriin:BAAALAAECggIAwAAAA==.',Sp='Spekulatius:BAACLAAFFIEWAAIEAAYIcyBWAgBaAgAEAAYIcyBWAgBaAgAsAAQKgTAAAgQACAhQJm4CAHcDAAQACAhQJm4CAHcDAAAA.',St='Stachelbeere:BAAALAAECgYICwABLAAECggIQQALAFIiAA==.Stjpafist:BAACLAAFFIETAAMRAAYIaB7nAAA5AgARAAYIaB7nAAA5AgALAAIIZgQxFABcAAAsAAQKgSEAAhEACAg8JtcBAGgDABEACAg8JtcBAGgDAAAA.Stockbrot:BAABLAAECoEVAAIBAAgIvQ8lQwCcAQABAAgIvQ8lQwCcAQAAAA==.Stopschíld:BAABLAAECoEVAAIZAAgI4R8QCgDkAgAZAAgI4R8QCgDkAgAAAA==.Stringsing:BAAALAADCggIDgAAAA==.',Su='Suicidetotem:BAAALAADCggICAAAAA==.Surely:BAAALAADCggIDwABLAAECggICAAOAAAAAA==.Suzz:BAAALAADCggICAAAAA==.',Sy='Sykran:BAAALAADCgUIBQAAAA==.Syno:BAAALAADCgMIAwAAAA==.Synoxi:BAAALAADCggIDgAAAA==.',['Sâ']='Sâchiko:BAAALAADCggICAAAAA==.Sâlvâtore:BAAALAADCgMIAwAAAA==.',['Sæ']='Sæmí:BAABLAAECoEYAAINAAYInxIffQBOAQANAAYInxIffQBOAQAAAA==.',['Sê']='Sêcrêts:BAAALAAFFAMIAwABLAAFFAUIDAARAPAVAA==.',['Sì']='Sìlvanas:BAAALAADCgYIBgAAAA==.',['Sí']='Sínclâîr:BAAALAADCgQIBAAAAA==.',['Sî']='Sînclair:BAABLAAECoEWAAMVAAgI5yAhEQAIAwAVAAgI5yAhEQAIAwAZAAQI1RW2WADEAAAAAA==.',Ta='Taicuno:BAAALAADCgEIAQABLAADCgcIBwAOAAAAAA==.Taiyô:BAAALAAECgIIAwABLAAECgYIHAANALsUAA==.Takkan:BAAALAAECgcIBwAAAA==.Talagar:BAAALAAECgYIEgAAAA==.Talande:BAAALAAECgMIAgAAAA==.Talasha:BAABLAAECoEUAAIcAAcIoRg6IAD1AQAcAAcIoRg6IAD1AQAAAA==.Talgat:BAAALAAECgYIDgAAAA==.Tankoraidkey:BAAALAADCgUIBgAAAA==.Tarkatov:BAABLAAECoEvAAIWAAgI6RYpLwApAgAWAAgI6RYpLwApAgAAAA==.Tarokk:BAABLAAECoEpAAIVAAgIjxxOJgB8AgAVAAgIjxxOJgB8AgAAAA==.Taxx:BAACLAAFFIEQAAIgAAUIDxtdAgDTAQAgAAUIDxtdAgDTAQAsAAQKgS8AAyIACAgmJgYDAHQDACIACAgmJgYDAHQDACAACAinImIIALQCAAAA.',Te='Telazura:BAAALAADCgcICgABLAAECggIGQAOAAAAAA==.Tepaartos:BAABLAAECoEWAAIJAAcIdRweSwAxAgAJAAcIdRweSwAxAgAAAA==.Teraldin:BAAALAAECgYIBgAAAA==.Tereina:BAAALAADCggIEAAAAA==.Teril:BAAALAAECgEIAQAAAA==.Tertialumen:BAAALAAECgMIAwABLAAECggIFQAZAOEfAA==.Teys:BAAALAAECgYIDAABLAAECgcIHQABACcRAA==.',Th='Thalanjo:BAAALAADCgIIAgAAAA==.Tharkzu:BAAALAAECggICAAAAA==.Tholag:BAAALAAECgYICAAAAA==.Thorhammer:BAAALAAECgcIEgAAAA==.Thorînu:BAAALAADCggICAAAAA==.Thrahl:BAAALAAECgcIDwAAAA==.Thunderforce:BAAALAAECggIDgAAAA==.Thunderine:BAABLAAECoEUAAIaAAcICRE0ewChAQAaAAcICRE0ewChAQAAAA==.Thyrianá:BAAALAAECgYICQAAAA==.Thôrîn:BAABLAAECoEYAAIIAAcIKBSVIwCiAQAIAAcIKBSVIwCiAQAAAA==.',Ti='Tingelchan:BAAALAADCggICAAAAA==.Tirkan:BAAALAAECgYIBgAAAA==.',To='Todeskeks:BAAALAAECgYIDgAAAA==.Tohrulos:BAAALAAECggIEgAAAA==.Tomtod:BAAALAAECgYIDwAAAA==.Tongaro:BAABLAAECoEbAAIeAAYIVhxIDAD0AQAeAAYIVhxIDAD0AQAAAA==.Tonnó:BAAALAADCgcIBwAAAA==.Tosaz:BAABLAAECoEeAAIIAAcIjgheQADgAAAIAAcIjgheQADgAAAAAA==.Tosmani:BAABLAAECoEUAAMiAAYIDx2JggC9AQAiAAYIWhyJggC9AQAgAAYIUxrkHgBSAQAAAA==.',Tr='Treibs:BAAALAADCgcIGwAAAA==.Trelliva:BAAALAAECgMIBQAAAA==.Triffhuf:BAAALAADCgcIBwAAAA==.',Ts='Tsuria:BAAALAADCggIDAAAAA==.',Tu='Turahk:BAAALAADCggIFQAAAA==.Tutníx:BAAALAAECgYICAAAAA==.',Ty='Tymara:BAAALAADCggIDwAAAA==.Tyrandê:BAAALAADCgEIAQAAAA==.Tyrankernas:BAABLAAECoEfAAIJAAgInAqonACFAQAJAAgInAqonACFAQAAAA==.Tyres:BAAALAAECgYIBgAAAA==.Tyrândê:BAAALAAECgYIDAAAAA==.',Tz='Tz:BAAALAAECgYICQABLAAFFAUIDAARAPAVAA==.Tzedakah:BAAALAADCggICAABLAAECgMIAwAOAAAAAA==.',['Tö']='Tölpel:BAAALAADCgYIBQABLAAECgcIHAAJALkcAA==.',Ub='Ubitza:BAAALAADCgQICgABLAAECgYICAAOAAAAAA==.',Ul='Ulquiorra:BAAALAAECggICAAAAA==.',Un='Unah:BAABLAAECoEgAAMmAAgI1w9WFwDtAQAmAAgI1w9WFwDtAQAiAAEIjwO+WQEmAAAAAA==.Unholymilk:BAAALAADCgcIFAAAAA==.Untoucháble:BAAALAADCgcIDAAAAA==.',Up='Upperraccoon:BAAALAADCggICAAAAA==.Upsipupsi:BAAALAAECgEIAQAAAA==.',Ur='Urleyn:BAABLAAECoEUAAIJAAYIRx+mTwAlAgAJAAYIRx+mTwAlAgAAAA==.Urukhei:BAAALAAECgMIBwAAAA==.',Va='Vaeroth:BAAALAAECgEIAQAAAA==.Valerien:BAAALAADCggICAAAAA==.Vanhennig:BAAALAADCgUIBQABLAADCgcIDgAOAAAAAA==.Vantur:BAAALAADCgYIBgAAAA==.',Ve='Velva:BAAALAAECgcIEwABLAAECggICAAOAAAAAA==.Velü:BAAALAADCggICAAAAA==.Veronix:BAAALAADCggICAABLAAECggIJAAUADklAA==.Verurteilt:BAABLAAECoEfAAIaAAcI/SGIOABUAgAaAAcI/SGIOABUAgAAAA==.',Vi='Vitalies:BAAALAADCggIIQAAAA==.Vivien:BAAALAADCggICAAAAA==.',Vo='Vonhelgi:BAAALAAECggICAAAAA==.Vorheez:BAAALAADCgcIBwAAAA==.',['Vô']='Vôlji:BAAALAADCgQIBAAAAA==.',Wa='Wachterin:BAAALAAECgIIAgAAAA==.Walky:BAABLAAECoEZAAIVAAcIcxuBNAAzAgAVAAcIcxuBNAAzAgAAAA==.Warriow:BAAALAAECgcIBwABLAAFFAIIBAAOAAAAAQ==.Warsic:BAABLAAECoEiAAIZAAgIRyHfCAD2AgAZAAgIRyHfCAD2AgAAAA==.',We='Welerik:BAAALAAECgYICQABLAAFFAMIBQAJAF4TAA==.Werthers:BAAALAAECgcIBwABLAAFFAYIFgAEAHMgAA==.',Wh='Whiskas:BAAALAADCgQIAwABLAAECgcIGQABAMEkAA==.',Wo='Worgenblitz:BAAALAADCggIEAAAAA==.Worgina:BAAALAAECgEIAQAAAA==.',Wu='Wulferion:BAAALAADCgUIAwAAAA==.',Wy='Wyver:BAAALAAECgMIAwAAAA==.',['Wá']='Wáchterin:BAAALAADCggIFwAAAA==.',['Wí']='Wítchkíng:BAAALAAECgYIDwABLAAECgcIIgANANoTAA==.',Xa='Xalatoph:BAAALAADCggICAAAAA==.Xalatroth:BAAALAAECgYIDQAAAA==.Xaltûs:BAAALAAECgMIAwAAAA==.Xarínah:BAAALAAECgYIDQAAAA==.',Xy='Xyldrâk:BAAALAAECgEIAQAAAA==.',['Xà']='Xàrdàs:BAAALAADCggIHwAAAA==.',['Xá']='Xárion:BAABLAAECoEYAAIWAAgIChyYIAB+AgAWAAgIChyYIAB+AgAAAA==.',['Xô']='Xôn:BAAALAAECgEIAQAAAA==.',Ya='Yamazaka:BAAALAADCggIEAAAAA==.',Ye='Yerek:BAAALAADCgIIAgABLAAECgYIHAANALsUAA==.',Yg='Yggirana:BAABLAAECoEoAAILAAgIJyWtAgBGAwALAAgIJyWtAgBGAwAAAA==.',Yi='Yiesera:BAAALAAECgYIDQABLAAECggIJAAUADklAA==.',Yo='Yokk:BAAALAADCgYIBgAAAA==.',Ys='Ysalie:BAAALAAECgIIAgAAAA==.',Yv='Yvô:BAAALAADCggICAAAAA==.',Za='Zangil:BAAALAADCgcIFQAAAA==.Zanza:BAABLAAECoEjAAIEAAgI+gQykQA8AQAEAAgI+gQykQA8AQAAAA==.',Ze='Zedh:BAAALAADCggICAABLAAECggIHwAhAI0WAA==.Zedho:BAAALAADCggIEAABLAAECggIHwAhAI0WAA==.Zedy:BAABLAAECoEfAAMhAAgIjRa5GQA3AgAhAAgIqhW5GQA3AgAnAAUI0A0nKgAQAQAAAA==.Zenober:BAAALAADCgYIDQAAAA==.Zerandor:BAAALAAECgEIAQAAAA==.Zerobit:BAAALAAECgYIDgAAAA==.Zeronas:BAAALAADCggIBwAAAA==.Zethy:BAAALAAECgYIEAAAAA==.',Zo='Zoes:BAAALAAECgYIDQAAAA==.Zoraca:BAAALAAECgIIAQAAAA==.',Zu='Zuckermaus:BAAALAAECgQIBAAAAA==.Zugzugorc:BAAALAADCgcIBwAAAA==.Zulann:BAABLAAECoEVAAMWAAgIGxUUVgCHAQAWAAYIOBMUVgCHAQANAAgIZSFXvQDLAAABLAAFFAQICgAKAMQYAA==.',Zy='Zylor:BAABLAAECoEdAAIaAAcIvyBDKQCWAgAaAAcIvyBDKQCWAgAAAA==.Zyydrea:BAAALAADCgMIAwABLAAECgYIBwAOAAAAAA==.',['Àd']='Àdeen:BAACLAAFFIENAAIEAAUIjSC1BgD8AQAEAAUIjSC1BgD8AQAsAAQKgSUAAgQACAiOJcYNACEDAAQACAiOJcYNACEDAAAA.',['În']='Înaste:BAABLAAECoEZAAICAAcIQhHrEgBqAQACAAcIQhHrEgBqAQAAAA==.',['Ðu']='Ðude:BAAALAADCggIEgAAAA==.',['Õk']='Õkami:BAABLAAECoEZAAMRAAgIRR9ZDQClAgARAAgInxxZDQClAgALAAcIgx1+EAAnAgAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end