local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'DeathKnight-Frost','Unknown-Unknown','Hunter-BeastMastery','Hunter-Marksmanship','Priest-Holy','Priest-Shadow','Paladin-Retribution','Warlock-Destruction','Warlock-Demonology','Monk-Brewmaster','Rogue-Subtlety','Warlock-Affliction','Druid-Balance','DemonHunter-Havoc','Paladin-Holy','Shaman-Enhancement','Mage-Frost','Mage-Arcane','Mage-Fire','Shaman-Elemental','Evoker-Devastation','Evoker-Preservation','Warrior-Protection','DemonHunter-Vengeance','Warrior-Fury','Shaman-Restoration','Hunter-Survival','Paladin-Protection','Druid-Restoration','Rogue-Assassination','Druid-Feral','Druid-Guardian','DeathKnight-Unholy','Warrior-Arms','Evoker-Augmentation','Monk-Windwalker','DeathKnight-Blood','Rogue-Outlaw','Monk-Mistweaver',}; local provider = {region='EU',realm='Darksorrow',name='EU',type='weekly',zone=44,date='2025-09-22',data={Ac='Acedìa:BAAALAAECgYIDAAAAA==.Acserus:BAAALAAECgEIAQAAAA==.',Ad='Adeliné:BAAALAAECgMIAQAAAA==.Adrastia:BAAALAAECgUIBgAAAA==.',Ae='Aeeshma:BAAALAAECgYICAAAAA==.Aelara:BAAALAADCgEIAQAAAA==.',Ag='Agynoth:BAAALAADCgcIBwAAAA==.',Al='Alamisa:BAAALAADCggICAAAAA==.Alenah:BAAALAAECgIIAgAAAA==.Alenowyn:BAABLAAECoEbAAIBAAcI7SIjKgCfAgABAAcI7SIjKgCfAgAAAA==.Alethar:BAAALAADCggICAAAAA==.Alko:BAAALAADCggICAAAAA==.Allandin:BAAALAAECgYIBgABLAAFFAIIBAACAAAAAA==.Alledría:BAAALAADCggICAABLAAECgcIIQADAFEiAA==.Allisius:BAAALAAECgYIDwAAAA==.',Am='Amazona:BAAALAAECgYIEwAAAA==.Amixx:BAAALAAECgMIBAAAAA==.',An='Anoril:BAAALAADCggIEgAAAA==.',Ar='Arafon:BAABLAAECoEUAAIDAAcI9Qf2nQA0AQADAAcI9Qf2nQA0AQAAAA==.Arasinya:BAAALAAECgYIBgAAAA==.Arcanna:BAAALAAECgYIBwAAAA==.Ardeth:BAABLAAECoEhAAIDAAgIbhxKJACGAgADAAgIbhxKJACGAgAAAA==.Armpit:BAAALAAECgYIDgAAAA==.Arthozs:BAABLAAFFIEKAAIBAAQIehvnCQCFAQABAAQIehvnCQCFAQAAAA==.',As='Asacshreder:BAAALAADCgcIDAAAAA==.Asiliath:BAAALAAECgUIBQAAAA==.',At='Atheenaa:BAAALAADCggIDQAAAA==.',Au='Auraria:BAAALAAECgYICQAAAA==.Aurea:BAAALAADCggICAABLAAECgYICQACAAAAAA==.',Av='Avisage:BAAALAADCggIDgAAAA==.',Aw='Awellex:BAAALAADCgcIBwAAAA==.',Ba='Barkley:BAAALAADCggICAAAAA==.',Bb='Bbdr:BAAALAAECgEIAQABLAAFFAIIBgADAJUhAA==.Bbh:BAACLAAFFIEGAAMDAAIIlSFyGQCzAAADAAIIlSFyGQCzAAAEAAIIrQeLIwBzAAAsAAQKgSUAAwMACAguItASAO4CAAMACAguItASAO4CAAQABwjeFSA9AKQBAAAA.',Be='Beagelli:BAAALAAECgYIEQAAAA==.Beefstar:BAAALAADCgYIBgABLAADCggIEAACAAAAAA==.Beelzebul:BAAALAAECgEIAQAAAA==.Beelzébub:BAABLAAECoEcAAMFAAgI4RETOQDNAQAFAAgI4RETOQDNAQAGAAcIcAr0RgByAQAAAA==.Beffpumper:BAABLAAECoEbAAIHAAgITxP7aQDfAQAHAAgITxP7aQDfAQAAAA==.Bergstrom:BAAALAAECgMIBQAAAA==.',Bi='Bigearn:BAACLAAFFIEJAAIIAAMITQ7vGADpAAAIAAMITQ7vGADpAAAsAAQKgRUAAwkACAiZIFYoALIBAAkABQjuIFYoALIBAAgABAjmHr1rAHMBAAAA.Biggershoe:BAAALAADCggICAAAAA==.Bigs:BAAALAADCgcIBwAAAA==.Bigsnus:BAAALAAECggIDgAAAA==.Bigtroll:BAAALAADCgUIBQAAAA==.Biksu:BAABLAAECoEbAAIKAAcIiSNoCAC8AgAKAAcIiSNoCAC8AgAAAA==.Bili:BAAALAAECgYICwAAAA==.',Bl='Blackghost:BAABLAAECoEZAAMDAAgImRAcYgC1AQADAAgImRAcYgC1AQAEAAIIPwj0oQBEAAAAAA==.Blackwitch:BAAALAADCgQIBAAAAA==.Blindvold:BAAALAADCggIDgAAAA==.Bludy:BAABLAAECoEUAAILAAcIEQ81GACmAQALAAcIEQ81GACmAQAAAA==.Blurryxx:BAAALAADCggIDQAAAA==.Blïzp:BAAALAAECgIIAgAAAA==.',Bo='Bodytypeonex:BAAALAADCggIEAAAAA==.Bonkd:BAAALAADCggICAAAAA==.Boon:BAAALAAECgEIAQAAAA==.Bornevil:BAAALAAECgcIBwAAAA==.Bornevíl:BAAALAADCgEIAQAAAA==.',Br='Bracomaniacu:BAAALAADCgYIBgAAAA==.Bradias:BAAALAAECggICAAAAA==.Bravehèarth:BAAALAAECgIIAgABLAAECggIJwAMAMsbAA==.Breanan:BAABLAAECoEeAAIDAAgISB3AKABxAgADAAgISB3AKABxAgAAAA==.Brezax:BAAALAAECgQIAgAAAA==.Brorkanin:BAAALAADCggIEAAAAA==.Brudonna:BAABLAAECoEoAAINAAgInQ9DMwC6AQANAAgInQ9DMwC6AQAAAA==.Bruik:BAAALAADCgUIBQAAAA==.',Bu='Bubbels:BAAALAAECgEIAQABLAAECgYIHQAOAO4fAA==.Bue:BAAALAAECgcIBwABLAAECgcIGwAPAKQZAA==.Bugabuser:BAAALAAECgYIDQAAAA==.Bulkers:BAAALAAECgIIAgAAAA==.',['Bä']='Bälsk:BAAALAAECggICAAAAA==.',Ca='Caelix:BAAALAADCggICAABLAAECggIJQADABYiAA==.Caiera:BAAALAAECgYIDAAAAA==.Caldaru:BAAALAADCggICAABLAAECgQICgACAAAAAA==.Calisso:BAAALAAECgYICQAAAA==.Carthadras:BAAALAADCggIDwABLAAECgcIEQACAAAAAA==.Cayla:BAAALAADCggIEAAAAA==.',Ce='Ceaseless:BAAALAAECggICAAAAA==.',Ch='Chappee:BAAALAADCggIBQAAAA==.Charred:BAAALAAFFAIIBAABLAAFFAIIBgAQAF4bAA==.Cheryl:BAABLAAECoEdAAMFAAgICRMpLwD/AQAFAAgICRMpLwD/AQAGAAEI2gRfigAtAAAAAA==.Chihuahuá:BAABLAAECoEWAAIHAAgIsRPXWAAGAgAHAAgIsRPXWAAGAgAAAA==.Chronic:BAAALAADCgQICAABLAAECgcICQACAAAAAA==.Chronicza:BAAALAAECgcICQAAAA==.Chuma:BAAALAADCgMIAwAAAA==.Chánchú:BAAALAAECgYIDwAAAA==.',Ci='Cicatrice:BAAALAAECgYIBAAAAA==.Citrusdödarn:BAAALAAECgUIBwAAAA==.',Cl='Clh:BAAALAADCgcIBwAAAA==.',Co='Coolmagician:BAAALAADCggIDwAAAA==.Coolreformed:BAAALAAECgYICwAAAA==.Cor:BAAALAADCggICAAAAA==.Corilith:BAABLAAECoEdAAQRAAgIKh1EEQBzAgARAAgIKh1EEQBzAgASAAUIvAl7nAAMAQATAAEIQQkWHgA1AAAAAA==.Corx:BAAALAADCgYIBgAAAA==.Corxial:BAAALAAECgYIBwAAAA==.Cowpatrol:BAAALAAECgcIEAABLAAECgcIGgAUAEUTAA==.',Cr='Crusade:BAAALAAECgcIEgAAAA==.Cruxlol:BAAALAADCggIFQAAAA==.Cryovex:BAAALAAECgYIBgAAAA==.',Cu='Cutesy:BAAALAADCggIEAABLAAFFAIIBgAEAP8QAA==.',Cx='Cxl:BAAALAADCgQIBAAAAA==.',Cy='Cyanidegecko:BAABLAAECoEiAAMVAAgIUSPvBgAVAwAVAAgIUSPvBgAVAwAWAAEINgZPOAApAAAAAA==.Cyclonis:BAAALAAECgEIAQAAAA==.Cylian:BAABLAAECoEVAAIHAAYIqSBNSQAwAgAHAAYIqSBNSQAwAgAAAA==.',Da='Daathly:BAAALAADCggICAAAAA==.Dagdromer:BAABLAAECoEVAAIJAAgIchzMDQB5AgAJAAgIchzMDQB5AgAAAA==.Damodre:BAABLAAECoEbAAIBAAYIKx6ZWwAHAgABAAYIKx6ZWwAHAgAAAA==.Dane:BAABLAAECoEUAAIIAAcI/Bw8LQBZAgAIAAcI/Bw8LQBZAgAAAA==.Dargel:BAAALAAECgMIBQAAAA==.Darrellgee:BAAALAAFFAIIAgAAAA==.Darrellwar:BAACLAAFFIEKAAIXAAMIRBq6BgAFAQAXAAMIRBq6BgAFAQAsAAQKgRoAAhcACAjbIL8KANQCABcACAjbIL8KANQCAAAA.Darutan:BAAALAADCggICwAAAA==.',De='Deadecho:BAAALAADCggIDwAAAA==.Deathangél:BAAALAAECgYIEQAAAA==.Defiance:BAABLAAECoEUAAIHAAcIyRDDrgBbAQAHAAcIyRDDrgBbAQAAAA==.Demone:BAAALAADCggICAABLAAECgYIDgACAAAAAA==.Demonlina:BAABLAAECoEWAAMYAAgIUB2ECQCXAgAYAAgIUB2ECQCXAgAOAAYIDAczvQAOAQABLAAFFAMICgAZAKMZAA==.Destíní:BAABLAAECoEbAAMaAAgIZAIRygCoAAAaAAgIZAIRygCoAAAUAAEIcwILswAQAAAAAA==.',Di='Diidel:BAAALAAECgYIDgABLAAECggICAACAAAAAA==.Dimmu:BAAALAAECgcIBwAAAA==.Dinahn:BAABLAAECoEUAAIIAAcIrw/SWgCkAQAIAAcIrw/SWgCkAQAAAA==.Dippendots:BAABLAAECoEnAAQMAAgIyxvTBQBiAgAMAAgIsRnTBQBiAgAIAAcIVRucMwA5AgAJAAUICQlSUQD8AAAAAA==.Dixsie:BAAALAAECggIEwAAAA==.',Dj='Djape:BAAALAAECgYIEQAAAA==.',Dm='Dmonico:BAAALAADCgYIBwAAAA==.',Do='Dodona:BAAALAAECgYICAAAAA==.Domythic:BAAALAAECgYIDQAAAA==.Donxe:BAACLAAFFIEIAAIXAAIIuRiqDQChAAAXAAIIuRiqDQChAAAsAAQKgScAAhcACAiHJJQDAEkDABcACAiHJJQDAEkDAAAA.Donzen:BAAALAADCgIIAgAAAA==.Dopeshot:BAAALAADCgUIBQAAAA==.Dorvax:BAABLAAECoEcAAMJAAcIMiAQEABfAgAJAAcIMiAQEABfAgAIAAEIHxvozABCAAAAAA==.Dotsnohots:BAAALAADCggICAAAAA==.',Dr='Dragonpet:BAAALAADCggIGAAAAA==.Drakkreb:BAAALAAECgYICQAAAA==.Dreamingdare:BAAALAAECgMIBgAAAA==.',Dw='Dwarfey:BAAALAAECggIEAAAAA==.',Ef='Effy:BAACLAAFFIENAAIGAAYILxgjAwAKAgAGAAYILxgjAwAKAgAsAAQKgS4AAgYACAhOJicCAHQDAAYACAhOJicCAHQDAAAA.',Eh='Ehterem:BAABLAAECoEVAAIKAAYIrxbaGgCQAQAKAAYIrxbaGgCQAQAAAA==.',Ei='Eiwýn:BAABLAAECoEbAAIbAAYIehq3CQDlAQAbAAYIehq3CQDlAQABLAAECgcIIQADAFEiAA==.',Ek='Ekke:BAAALAADCggIKgAAAA==.',El='Elique:BAABLAAECoEhAAIcAAgIdCM9AwBBAwAcAAgIdCM9AwBBAwAAAA==.Elvadin:BAAALAAECgcIDQAAAA==.Elvin:BAAALAAECggIEwAAAA==.Elycia:BAAALAAECgIIAgAAAA==.',Em='Emilla:BAABLAAECoEcAAIcAAcIyRUoIACzAQAcAAcIyRUoIACzAQAAAA==.Emoflash:BAAALAADCgYIBgAAAA==.Emofrog:BAAALAAECggIEwAAAA==.Empire:BAAALAAECgYIDgAAAA==.Empyreal:BAAALAADCgYIBgAAAA==.',En='End:BAAALAADCgUIBwAAAA==.Enys:BAABLAAECoEpAAIRAAgIPCTvAwBEAwARAAgIPCTvAwBEAwAAAA==.',Eo='Eonnico:BAAALAAECgYIBgAAAA==.',Er='Ernor:BAAALAAECgEIAQAAAA==.Eruco:BAACLAAFFIENAAMFAAUIsgkHBwBuAQAFAAUIsgkHBwBuAQAGAAQItAl8CwABAQAsAAQKgSMAAwYACAjRHhwQANoCAAYACAjRHhwQANoCAAUAAQhaDJqeADcAAAAA.',Es='Esaty:BAAALAAECggICAAAAA==.',Et='Ettan:BAAALAADCggICAAAAA==.',Ex='Exya:BAACLAAFFIEHAAIdAAQISA4CCAAVAQAdAAQISA4CCAAVAQAsAAQKgSwAAh0ACAhHI78HAAUDAB0ACAhHI78HAAUDAAAA.',['Eò']='Eòh:BAAALAAECgIIAgAAAA==.',Fa='Farastall:BAABLAAECoEeAAMaAAgIdiS4AwA+AwAaAAgIdiS4AwA+AwAUAAEI0wkNpAA7AAAAAA==.Fatliz:BAAALAAECgUICAAAAA==.',Fe='Fearthepleb:BAAALAAECgQIBAAAAA==.Fefo:BAAALAAECgYICgAAAA==.Felmm:BAABLAAECoEeAAIHAAgInxlYSwArAgAHAAgInxlYSwArAgAAAA==.Ferallan:BAABLAAECoEfAAIdAAgIWib0AAByAwAdAAgIWib0AAByAwAAAA==.',Fi='Fireballan:BAAALAADCgIIAgABLAAFFAIIBAACAAAAAA==.Fistmedaddÿ:BAAALAADCggICAABLAAFFAIIBgAEAP8QAA==.',Fl='Flax:BAAALAADCggIFQAAAA==.',Fo='Foemp:BAABLAAECoEhAAIGAAgICByDGACMAgAGAAgICByDGACMAgAAAA==.Fondence:BAAALAAECgIIAgAAAA==.Fowls:BAAALAAECggICgAAAA==.Fowlz:BAAALAAECggIDgAAAA==.',Fr='Frostburst:BAAALAAECggIDwAAAA==.Fráze:BAAALAADCggICAAAAA==.',Fu='Furrific:BAAALAADCgYIBgAAAA==.',['Fê']='Fêlfinger:BAAALAAECggICAAAAA==.',['Fø']='Føgl:BAABLAAECoEbAAIUAAcI4Rr+LAAsAgAUAAcI4Rr+LAAsAgAAAA==.',Ga='Gathilian:BAAALAAECgcIEAAAAA==.',Ge='Geggweckets:BAAALAAECgMIAwAAAA==.Gerlit:BAAALAAECgIIAgAAAA==.',Gi='Gibbon:BAAALAADCggICAABLAAECgYIHQAOAO4fAA==.',Go='Gobbash:BAAALAAECgYIDAAAAA==.Gothec:BAAALAAFFAEIAQAAAA==.',Gr='Grétà:BAABLAAECoEhAAMEAAgIkCTSBQA1AwAEAAgItiPSBQA1AwADAAgIdSHTDQAPAwAAAA==.',Gu='Gudgrun:BAABLAAECoEUAAIdAAcIthU9OADBAQAdAAcIthU9OADBAQAAAA==.Gudzeal:BAAALAADCgUIBQAAAA==.',Gz='Gzrt:BAABLAAECoEaAAMIAAgIexhAOgAaAgAIAAgIcBdAOgAaAgAJAAYIkg63TAAQAQAAAA==.',['Gî']='Gîlly:BAAALAAECgcIEgAAAA==.',Ha='Halesgrim:BAABLAAECoElAAMZAAgIGyONDQAdAwAZAAgIGyONDQAdAwAXAAEIFg6EeQAkAAAAAA==.Halk:BAAALAADCggIDAAAAA==.Halvthorn:BAABLAAECoEbAAIOAAcINQx3iAB+AQAOAAcINQx3iAB+AQAAAA==.',He='Healyoouup:BAAALAAECggICAAAAA==.Heerria:BAAALAAECgcIBwAAAA==.Helladiin:BAABLAAECoEbAAIPAAcIpBloGAAaAgAPAAcIpBloGAAaAgAAAA==.Heltspak:BAAALAAECggICAAAAA==.Henriete:BAAALAAECggIEAAAAA==.Henry:BAAALAADCggICwAAAA==.',Hi='Hiigaran:BAAALAADCgcIBwAAAA==.Hildor:BAAALAAECgYIDQAAAA==.Hiyaldi:BAAALAAECgYICQAAAA==.',Ho='Holina:BAAALAADCgcIBwAAAA==.Hopeasuoli:BAABLAAECoEpAAMXAAgILCO9BwACAwAXAAgIHCK9BwACAwAZAAgIqiCxHwCbAgAAAA==.Howlbourne:BAAALAADCggIDwAAAA==.',Hu='Humble:BAACLAAFFIEKAAIZAAMIziAKCwAvAQAZAAMIziAKCwAvAQAsAAQKgSQAAhkACAh3JUMFAF8DABkACAh3JUMFAF8DAAAA.Hunds:BAAALAADCggIEAABLAAECgYIDgACAAAAAA==.Huntlyfe:BAACLAAFFIENAAMDAAUIoh1eCABvAQADAAUIoh1eCABvAQAEAAIIvxPRGgCJAAAsAAQKgSYAAwMACAj+JSIQAAADAAMACAj+JSIQAAADAAQACAhdIA0SAL8CAAAA.Hustlerr:BAAALAADCgQIBAABLAAECgcIHgAGAHshAA==.',Hy='Hydrate:BAAALAAECggICAAAAA==.',['Há']='Hálibel:BAABLAAECoEmAAIDAAgI1yAwGgDAAgADAAgI1yAwGgDAAgAAAA==.',Ic='Icedlatte:BAAALAADCgYIBgAAAA==.',Il='Iliyatheares:BAAALAAECgMIBQAAAA==.Illisa:BAAALAADCgcIBgAAAA==.Illislan:BAABLAAECoEnAAIYAAgITh3QCgB9AgAYAAgITh3QCgB9AgAAAA==.Ilmentymä:BAAALAAECgYIDgAAAA==.',Im='Imbalover:BAAALAAECgEIAgAAAA==.Immoonen:BAABLAAECoEmAAIZAAgIfRPJTgDCAQAZAAgIfRPJTgDCAQAAAA==.',Ir='Iriediana:BAAALAADCggIDAAAAA==.Ironbender:BAAALAADCggICAAAAA==.',Is='Isklar:BAAALAAECgYICAAAAA==.Istvan:BAAALAADCggIKQAAAA==.',Iv='Ivelinwe:BAAALAAECgEIAQAAAA==.',Ja='Jaana:BAAALAADCggIGAAAAA==.Jammú:BAAALAAECgYIBgABLAAFFAUIDwAIAFYjAA==.Jarush:BAABLAAECoEeAAIeAAgIWh2HFABkAgAeAAgIWh2HFABkAgAAAA==.',Je='Jegerpurløg:BAAALAAECgMIBgAAAA==.Jerngnomen:BAABLAAECoEUAAIZAAcI+R3CJgBwAgAZAAcI+R3CJgBwAgAAAA==.',Jo='Jorkingpeen:BAAALAAECgEIAQAAAA==.Joshps:BAAALAADCgEIAQAAAA==.',Ju='Juicebox:BAAALAAECgcIDQAAAA==.',['Já']='Jáppe:BAAALAAECgYIBgABLAAFFAUIDwAIAFYjAA==.',Ka='Kaalesh:BAAALAAECgMIAwAAAA==.Kabayan:BAABLAAFFIEGAAMJAAIIXA0qEwCTAAAJAAIIIwkqEwCTAAAIAAIIKQuQMACLAAABLAAFFAIIBgAQAF4bAA==.Kaheer:BAAALAADCgQIBAABLAAECggIHgAaAHYkAA==.Karitapio:BAAALAAECggIEgAAAA==.Karkara:BAABLAAECoEWAAINAAgIHwLYcACTAAANAAgIHwLYcACTAAAAAA==.Karnaisleet:BAAALAAECgUICQABLAAFFAUIDwAUABQPAA==.Karrin:BAAALAAECgUIDQAAAA==.Karrypto:BAABLAAECoEdAAIaAAYIrSE4KgA/AgAaAAYIrSE4KgA/AgAAAA==.Kasuhira:BAABLAAECoEWAAIOAAgIqgh0ngBSAQAOAAgIqgh0ngBSAQAAAA==.Kayotick:BAABLAAECoEhAAIfAAgImR4lCQCeAgAfAAgImR4lCQCeAgAAAA==.',Ke='Keerena:BAAALAAECgIIAgAAAA==.Kellagh:BAAALAAECgIIAgAAAA==.Kermít:BAAALAADCggICAABLAAECgYIEwACAAAAAA==.',Ki='Kickazsham:BAABLAAECoEaAAIQAAYIuSLVBwBkAgAQAAYIuSLVBwBkAgABLAAECggIIwAIAEEhAA==.Kickzsh:BAABLAAECoEaAAIUAAYIIyAOLAAyAgAUAAYIIyAOLAAyAgABLAAECggIIwAIAEEhAA==.Kimjongbill:BAAALAAECgIIAgABLAAECgMIBQACAAAAAA==.Kiresa:BAAALAAECgMIBAAAAA==.Kironi:BAABLAAECoEeAAIdAAgIXgyqUQBbAQAdAAgIXgyqUQBbAQAAAA==.Kittkatt:BAABLAAECoEmAAIHAAgI1yE0EgAYAwAHAAgI1yE0EgAYAwAAAA==.',Kj='Kjakan:BAAALAADCggICAAAAA==.',Kl='Klammekalle:BAABLAAECoEeAAMGAAcIeyHHFACtAgAGAAcIeyHHFACtAgAFAAYI9xZuRwCOAQAAAA==.',Kn='Knekten:BAAALAADCggIFwAAAA==.',Ko='Konrad:BAAALAAFFAIIAgAAAA==.Kostok:BAAALAAFFAIIAgAAAA==.Koubaros:BAAALAADCgIIAgAAAA==.',Kr='Krnellion:BAACLAAFFIEIAAIBAAMIahJtFwDnAAABAAMIahJtFwDnAAAsAAQKgTIAAgEACAitIp8QABwDAAEACAitIp8QABwDAAAA.Krom:BAAALAAECgcIDQABLAAFFAIIBgAHAJ4jAA==.',Ku='Kudödarn:BAAALAAECgYIBgAAAA==.Kusgan:BAACLAAFFIEGAAMQAAIIXhuPAwC0AAAQAAIIXhuPAwC0AAAUAAII1AkwIQCLAAAsAAQKgRoABBQACAh9GSZCAMcBABQABwi4FSZCAMcBABAABAgJG/8VAFYBABoAAghyEgXpAGcAAAAA.Kusinen:BAAALAADCgEIAQAAAA==.',La='Lahlaan:BAABLAAECoEVAAIgAAcIaSPaAwDGAgAgAAcIaSPaAwDGAgAAAA==.Lassudan:BAABLAAECoEaAAIOAAgITyGiEQASAwAOAAgITyGiEQASAwAAAA==.Lazerkylling:BAAALAADCgIIAgAAAA==.',Li='Lifelike:BAAALAADCgcIBwAAAA==.Lightmatra:BAAALAAECgIIAgAAAA==.Likeice:BAAALAAECgIIAgAAAA==.Limonelle:BAAALAAECgYICQAAAA==.Littlesir:BAACLAAFFIEGAAMIAAIILhxuIACtAAAIAAIILhxuIACtAAAJAAEI6RACIABQAAAsAAQKgSAABAgABghoIUo2ACwCAAgABghoIUo2ACwCAAwABAiMEJ8dAOMAAAkAAwhVHG5bAMwAAAAA.Livet:BAAALAAECgQIBAAAAA==.',Ll='Lleania:BAAALAADCggIGAABLAAECggIJQAZABsjAA==.',Lo='Lockbate:BAAALAAECggIEAAAAA==.Lockè:BAABLAAECoEoAAIVAAgIfgt+KACyAQAVAAgIfgt+KACyAQAAAA==.Lonemagrethe:BAAALAAECggIEgABLAAECggIDgACAAAAAA==.Loratrage:BAABLAAECoEdAAIOAAYI7h9vSwANAgAOAAYI7h9vSwANAgAAAA==.',Ly='Lycal:BAACLAAFFIEGAAIDAAII2AL0OABkAAADAAII2AL0OABkAAAsAAQKgSwAAwMACAgUFDlIAPsBAAMACAgUFDlIAPsBAAQAAQg6A4+5AB0AAAAA.',Ma='Maaskantje:BAACLAAFFIEGAAIbAAMIaAkpAQDpAAAbAAMIaAkpAQDpAAAsAAQKgSUAAhsACAhHH8MCANICABsACAhHH8MCANICAAAA.Madamada:BAAALAAECgYIBgAAAA==.Maestaff:BAAALAAECgEIAQAAAA==.Maestrof:BAAALAADCggIDgAAAA==.Maggicer:BAAALAADCgcICAABLAAECgYIGAAdAIQLAA==.Magikerhulv:BAACLAAFFIEFAAISAAMIKxCTGgDmAAASAAMIKxCTGgDmAAAsAAQKgRQAAhIACAifH+YWAOkCABIACAifH+YWAOkCAAAA.Magnhild:BAAALAAECggIEwAAAA==.Magnüs:BAABLAAECoEZAAISAAgIExATWwDLAQASAAgIExATWwDLAQAAAA==.Malex:BAAALAAECgcIDQAAAA==.Malie:BAAALAAECgIIAgAAAA==.Mam:BAAALAADCgMIAwABLAAFFAMIDAAIAIIdAA==.Mamet:BAAALAADCgYICgAAAA==.Manadar:BAACLAAFFIEGAAIHAAIIniOuFgDAAAAHAAIIniOuFgDAAAAsAAQKgScAAgcACAg0JnACAIIDAAcACAg0JnACAIIDAAAA.Manis:BAABLAAECoEZAAMHAAcIyQhQzQAgAQAHAAYIDQdQzQAgAQAPAAUIsgWsTgC/AAAAAA==.Marcules:BAAALAADCgUIBQAAAA==.Marksmallan:BAAALAADCgIIAgABLAAFFAIIBAACAAAAAA==.',Mc='Mcmoe:BAAALAADCggIDgAAAA==.',Me='Mediumshoe:BAAALAADCggICAAAAA==.Melian:BAABLAAECoEZAAIHAAcIHhQYmwB/AQAHAAcIHhQYmwB/AQAAAA==.Melpomeni:BAACLAAFFIEFAAIhAAIIvxlnCgCtAAAhAAIIvxlnCgCtAAAsAAQKgR0AAiEACAgnH54FAPACACEACAgnH54FAPACAAEsAAEKBAgEAAIAAAAA.Mentadruid:BAAALAADCgMIAwAAAA==.Mentashaman:BAAALAADCggICAAAAA==.Mephìsto:BAACLAAFFIEFAAIdAAII1BliFgCgAAAdAAII1BliFgCgAAAsAAQKgR8AAh0ABgiWIiYfAEMCAB0ABgiWIiYfAEMCAAAA.',Mi='Midriff:BAAALAAECgIIAgAAAA==.Mikká:BAAALAAECgYIDQAAAA==.Mikromus:BAAALAAECgcIDwAAAA==.Misanthrope:BAAALAAECgYICwAAAA==.Misspain:BAAALAAECgIIAgAAAA==.Mizeet:BAAALAADCgMIAwAAAA==.',Mo='Mokkapala:BAAALAADCgEIAQAAAA==.Moko:BAAALAADCgcIBwAAAA==.Monkboom:BAAALAAECgYIDAAAAA==.Morgore:BAABLAAECoEzAAQJAAgI0R2RCgCfAgAJAAcIHyGRCgCfAgAIAAgITwlYXwCWAQAMAAEIrw6DNgBEAAAAAA==.Morgoth:BAAALAAECgYICgAAAA==.Morska:BAAALAAECgMIBgAAAA==.Morwen:BAAALAADCgYICgAAAA==.Mourbyd:BAAALAADCgUIAwABLAADCggIDwACAAAAAA==.Mourbydpal:BAAALAADCggIDwAAAA==.',Mq='Mqq:BAAALAADCgcIBwABLAADCggIEAACAAAAAA==.',Mu='Muste:BAAALAADCgMIAwAAAA==.Mutsuko:BAAALAADCgcIDAAAAA==.',My='Mynni:BAACLAAFFIEOAAIXAAMIhBpgBwD0AAAXAAMIhBpgBwD0AAAsAAQKgRkAAxcABwjvIFsQAIkCABcABwjvIFsQAIkCACIABgiNBf4gAMQAAAEsAAUUBwgSAAMA8wwA.Myuoh:BAABLAAECoEVAAIdAAgIzyStAgBNAwAdAAgIzyStAgBNAwAAAA==.',['Mä']='Mättökone:BAAALAAECgYICgAAAA==.',['Mø']='Møadin:BAAALAADCgMIAwABLAAECgcIGwAPAKQZAA==.Mørtem:BAAALAADCggICAAAAA==.',Na='Nacataar:BAABLAAECoEUAAIdAAYImQ9mYgAkAQAdAAYImQ9mYgAkAQAAAA==.Nacattar:BAAALAAECgYIDAABLAAECgYIFAAdAJkPAA==.Naryui:BAAALAAECgYICwAAAA==.',Ne='Necrophious:BAAALAAECgcIBwAAAA==.Nejnej:BAAALAADCgEIAQAAAA==.Nektar:BAAALAAECgYIEAAAAA==.Nenu:BAAALAADCgcIBwAAAA==.Nescalz:BAAALAAECgYIBgABLAAECgcICAACAAAAAA==.',Ni='Nioramy:BAAALAADCgIIAQAAAA==.',No='Nocticula:BAAALAAECgcICAABLAAFFAIIBgABAMccAA==.',Nu='Nutcrackr:BAAALAADCgIIAwAAAA==.Nuuska:BAAALAAECgMIBgAAAA==.',['Nö']='Nöxíe:BAABLAAECoEVAAIRAAcI5A0jMgCEAQARAAcI5A0jMgCEAQAAAA==.',Oo='Ooberness:BAAALAAECgUICgABLAAECggIJgAcABgiAA==.',Op='Opaber:BAAALAADCgQIBAAAAA==.',Os='Ossý:BAAALAAECgYIEwAAAA==.',Ov='Oversightx:BAAALAAECgIIAgAAAA==.',Pa='Pacquiao:BAAALAADCggICAAAAA==.Paintrainz:BAAALAAECgcICAAAAA==.Pakkaskarhu:BAAALAADCgcICQAAAA==.Pakoputki:BAAALAAECgcICQAAAA==.Pandabro:BAAALAADCgMIAwAAAA==.Pandabroski:BAABLAAECoEWAAINAAgIBwxwTABDAQANAAgIBwxwTABDAQAAAA==.Parkzicht:BAAALAAECgQIAQAAAA==.Partatuke:BAAALAADCgcIBwAAAA==.Paxdrood:BAAALAADCggICAAAAA==.',Pe='Peachpie:BAAALAADCgIIAgAAAA==.Peccifighter:BAAALAAECgYIDgABLAAECgYIDwACAAAAAA==.Peccilight:BAAALAAECgYIDAABLAAECgYIDwACAAAAAA==.Pewuid:BAACLAAFFIEIAAINAAMIhg1wCwDWAAANAAMIhg1wCwDWAAAsAAQKgSgABA0ACAinGDAcAE0CAA0ACAinGDAcAE0CACAAAwjXCVQlAG0AAB8AAQheAoRAACoAAAAA.',Pi='Pinkley:BAABLAAECoEhAAIHAAgIWiJOEAAjAwAHAAgIWiJOEAAjAwAAAA==.',Pl='Plub:BAABLAAECoEgAAMjAAcINxs1BwDdAQAVAAcIUBpnHwD8AQAjAAYIvho1BwDdAQAAAA==.',Po='Porrib:BAAALAAECgYIDQAAAA==.',Pr='Prestababbe:BAAALAADCggIBQAAAA==.Prutwuzzel:BAABLAAECoEaAAMUAAcIRRPjPQDaAQAUAAcIRRPjPQDaAQAaAAYIixQDdABbAQAAAA==.',Ps='Psyeh:BAAALAAECgMIAQAAAA==.Psyfer:BAAALAADCgcIBwAAAA==.',Pu='Puffrider:BAAALAAECgEIAQABLAAECgcIHgAGAHshAA==.',Py='Pyrosham:BAAALAADCggICAAAAA==.Pyrò:BAABLAAECoEeAAIHAAgITSEpGQDyAgAHAAgITSEpGQDyAgAAAA==.Pyrô:BAAALAADCgYIBgABLAAECggIHgAHAE0hAA==.',['Pà']='Pàrts:BAAALAAECgcIDAAAAA==.',['Pí']='Pímu:BAABLAAECoEiAAIBAAgI/B/+HQDWAgABAAgI/B/+HQDWAgAAAA==.',Ql='Qllix:BAABLAAECoEiAAIRAAgIiiLhBgANAwARAAgIiiLhBgANAwAAAA==.Qllixlol:BAAALAAECggICAAAAA==.',Qr='Qruhp:BAAALAAECgQIBAAAAA==.',Qu='Quatier:BAAALAADCggICAAAAA==.',Ra='Rafnagud:BAAALAADCgcIDQAAAA==.Ragoya:BAAALAAECgMIAwAAAA==.Raise:BAAALAAECgMIBAABLAAFFAMIBgALAF8HAA==.',Re='Reactjs:BAAALAAECgQICgAAAA==.Rege:BAABLAAECoEVAAMHAAgISRmmRAA9AgAHAAgISRmmRAA9AgAcAAEIjwwPXQAuAAAAAA==.Regelol:BAAALAADCggICAAAAA==.Regera:BAAALAAECggIDgAAAA==.Regor:BAAALAAECgIIAgAAAA==.Retnak:BAAALAAECgQIBQABLAAFFAIIBQABAGEiAA==.Rewindwalker:BAABLAAECoEaAAIkAAgIgxCCHgDXAQAkAAgIgxCCHgDXAQAAAA==.',Ri='Rio:BAAALAADCgcIBwAAAA==.Rippan:BAAALAAECggICAAAAA==.',Ro='Roguenak:BAAALAAECgYIDwABLAAFFAIIBQABAGEiAA==.',Ru='Runardenvite:BAAALAAECgUIBQABLAAECggIIQAEAJAkAA==.Runhar:BAAALAADCggIEQAAAA==.Ruuvii:BAAALAAECgcIEQAAAA==.Ruzyo:BAAALAADCggIEAABLAAECggIIQAcAHQjAA==.',Ry='Rykunamatata:BAABLAAECoEbAAMBAAgIcB3wNQByAgABAAgIcB3wNQByAgAlAAEIsxSWOwA7AAAAAA==.',['Rá']='Rámpagè:BAAALAADCggIEAAAAA==.',['Ré']='Régnak:BAACLAAFFIEFAAIBAAIIYSKlHQDHAAABAAIIYSKlHQDHAAAsAAQKgRUAAgEACAjvIN0eANICAAEACAjvIN0eANICAAAA.',Sa='Safcejo:BAAALAAECggIEQABLAAFFAMIBgALAF8HAA==.Safcer:BAACLAAFFIEGAAMLAAMIXweVCgChAAALAAMIXwSVCgChAAAmAAIImwgQBACQAAAsAAQKgRYAAyYACAjCGV8FAEsCACYACAg9F18FAEsCAAsABgiaGjMTAN8BAAAA.Safces:BAAALAADCggICAABLAAFFAMIBgALAF8HAA==.Sagaroth:BAABLAAECoEyAAMdAAgI0yNZBAAzAwAdAAgI0yNZBAAzAwANAAYIFhvDMgC8AQAAAA==.Sakya:BAAALAAECggIEgAAAA==.Samcredible:BAAALAAECgMIBgAAAA==.Samosa:BAAALAADCgIIAgAAAA==.Samsil:BAAALAAECggICAAAAA==.Sanjikun:BAABLAAECoEVAAInAAYIxA1zKAAhAQAnAAYIxA1zKAAhAQAAAA==.',Se='Secdruid:BAAALAAECgEIAQAAAA==.Sergenthull:BAAALAAECgcIEAAAAA==.Serrith:BAAALAAECgcIEAAAAA==.',Sh='Shadowm:BAABLAAECoEWAAInAAgIphUhFwDXAQAnAAgIphUhFwDXAQABLAAFFAUICwAdAFEOAA==.Shadowoluf:BAACLAAFFIELAAIdAAUIUQ41BwAkAQAdAAUIUQ41BwAkAQAsAAQKgRsAAx0ACAgwHIgUAIwCAB0ACAgwHIgUAIwCAA0ABggaD3VNAD4BAAAA.Shadylady:BAAALAADCgYIBgAAAA==.Shalaren:BAAALAAECgYIBgABLAAECgYIHQAOAO4fAA==.Shamallann:BAAALAAFFAIIBAAAAA==.Shamnex:BAABLAAECoEWAAMUAAcIQQcPYgBWAQAUAAcIQQcPYgBWAQAQAAYIogPGGgDzAAAAAA==.Shaoiboy:BAAALAAECgYIDQAAAA==.Shogun:BAAALAAECgcIDgAAAA==.Shviker:BAAALAAECgYIEAAAAA==.',Si='Sierrammy:BAABLAAECoEWAAIaAAcI9wvYiQAoAQAaAAcI9wvYiQAoAQAAAA==.Sikiz:BAABLAAECoEmAAIFAAgIeyTsAwBKAwAFAAgIeyTsAwBKAwAAAA==.Sinclaire:BAAALAAECgYIEgABLAAFFAIIBgABAMccAA==.Sinyx:BAAALAAECgQICQAAAA==.Sithmaster:BAAALAADCggIJQAAAA==.',Sk='Skiller:BAAALAAECgcICQAAAA==.Skilltotem:BAAALAAECgEIAQAAAA==.Skrrt:BAAALAAECgIIAgAAAA==.Skumskumskum:BAAALAAECgEIAQAAAA==.Skyrimdrake:BAAALAADCggIEAAAAA==.',Sl='Slackbolt:BAAALAAECgcICQAAAA==.Slambulance:BAAALAADCggIGQABLAAECgMIBQACAAAAAA==.Sleazebag:BAAALAAECgYIBgAAAA==.Slembt:BAAALAADCggICAAAAA==.',Sm='Smitealicius:BAAALAADCggIGgAAAA==.Smorcish:BAAALAAECgYIEAAAAA==.',Sn='Snilleulf:BAABLAAECoEbAAMGAAcIVxc1NADPAQAGAAcIVxc1NADPAQAFAAYIzwg1aQAWAQAAAA==.Snokarn:BAAALAADCgcIBwAAAA==.',So='Sojuyakult:BAAALAAECgcICwAAAA==.Sowwy:BAAALAAECgIIAgAAAA==.',Sp='Sparke:BAAALAADCgIIAgAAAA==.Spineshooter:BAAALAADCggIEAAAAA==.Spyderman:BAABLAAECoEZAAIiAAgIOBzuBQCLAgAiAAgIOBzuBQCLAgAAAA==.Spydruid:BAAALAADCggICQAAAA==.Spylock:BAAALAADCggICwAAAA==.Spymonk:BAAALAADCggIDgAAAA==.',Sq='Squertn:BAAALAAECgYIBgAAAA==.',St='Stan:BAAALAADCgUICgABLAAECgcIEgACAAAAAA==.Stardust:BAAALAADCgEIAQAAAA==.Stawky:BAAALAADCgQIBAABLAAECgcIGwAKAIkjAA==.Steelfeel:BAAALAADCggICwAAAA==.Steffebatan:BAAALAADCgEIAgABLAAECgcIBwACAAAAAA==.Stg:BAAALAAECgIIAgAAAA==.Stopher:BAAALAADCgcIBwAAAA==.Styxiia:BAAALAAECgUIAgAAAA==.Stælnisse:BAAALAADCggICAAAAA==.',Su='Sulfúr:BAAALAAECgQIAgAAAA==.Supafkd:BAAALAADCgcIEAAAAA==.Superbirb:BAAALAADCgYIBgAAAA==.',Sv='Sveinarild:BAAALAADCggIEwABLAADCggIFwACAAAAAA==.Svártskägg:BAAALAAECggIEwAAAA==.',Sy='Sylvannawind:BAAALAAECgcIEAAAAA==.',['Sá']='Sáber:BAAALAADCgcIEAAAAA==.',['Sú']='Súnsun:BAAALAADCgcIDAABLAAECggIJgADANcgAA==.',Ta='Takeursoul:BAAALAADCgcIBwAAAA==.Talshara:BAAALAAECgcIBwAAAA==.Tambor:BAAALAADCggIDwAAAA==.Tapanikansa:BAACLAAFFIELAAIGAAUIOBOwBgCOAQAGAAUIOBOwBgCOAQAsAAQKgSAAAwYACAi/I5UKABEDAAYACAi/I5UKABEDAAUAAgh5GyWIAJQAAAAA.Taydera:BAAALAAECgYICwAAAA==.',Te='Terenes:BAABLAAECoEhAAIBAAgI5BtNLwCLAgABAAgI5BtNLwCLAgAAAA==.',Th='Thanos:BAAALAAECggIDgAAAA==.Thargrim:BAAALAAECgIIAgABLAADCggIKQACAAAAAA==.Thelastvulva:BAAALAADCggIEQAAAA==.Theurho:BAACLAAFFIEFAAIHAAMIyghyEwDNAAAHAAMIyghyEwDNAAAsAAQKgSEAAgcACAgHHmcoAKUCAAcACAgHHmcoAKUCAAAA.Thoms:BAAALAAECgEIAQAAAA==.Thorodinson:BAAALAADCggIEgAAAA==.Thunderbud:BAAALAAECgUIBQAAAA==.',Ti='Timbah:BAAALAADCggICAABLAAFFAcIIAALAFchAA==.Tiné:BAAALAAECgYIDwAAAA==.Tismagi:BAACLAAFFIEIAAISAAIINCAmIgC3AAASAAIINCAmIgC3AAAsAAQKgSYAAhIACAgmJTYEAGQDABIACAgmJTYEAGQDAAAA.Tissikeisari:BAABLAAECoEbAAIMAAYIUQ7LEgBsAQAMAAYIUQ7LEgBsAQAAAA==.',To='Tompanda:BAAALAADCgcIBwAAAA==.Tonin:BAABLAAECoEhAAMcAAgI0A7TMQAvAQAcAAYI5xLTMQAvAQAHAAcISQiPzQAgAQAAAA==.Tonitio:BAAALAAECggIEwAAAA==.Torsdagsöl:BAAALAADCgIIAgAAAA==.Totastic:BAAALAAECgcIDgAAAA==.Toulouse:BAABLAAECoElAAIdAAgI7BmOIgAvAgAdAAgI7BmOIgAvAgAAAA==.Tozza:BAEALAADCgQIBAABLAAFFAIIAwACAAAAAA==.',Tr='Trifecta:BAAALAADCggICAABLAAFFAIIBgABAMccAA==.Trollsk:BAAALAADCgYIBgABLAADCggIFwACAAAAAA==.Trustfall:BAABLAAECoEhAAIFAAgI5A41QgCkAQAFAAgI5A41QgCkAQABLAAECggIJwAMAMsbAA==.Trylord:BAAALAADCgYIBgAAAA==.Tryx:BAABLAAECoEUAAIEAAYI6RyVLwDoAQAEAAYI6RyVLwDoAQAAAA==.Trønderstorm:BAAALAADCgYICAABLAAECggIGAAEADIbAA==.',Ts='Tsuran:BAAALAAECgYICQAAAA==.',Tu='Tuffgrabb:BAABLAAECoEfAAQNAAcImB/mFgB8AgANAAcImB/mFgB8AgAgAAIIsw31JgBbAAAdAAEI3RfBrABFAAABLAAFFAMICgAZAKMZAA==.Tulu:BAABLAAECoEXAAIZAAgIUyOnFgDbAgAZAAgIUyOnFgDbAgAAAA==.Tulua:BAABLAAFFIEGAAIaAAIIBiJtFQDDAAAaAAIIBiJtFQDDAAAAAA==.',Ty='Tyrael:BAABLAAECoEfAAIHAAgIgw+lfAC5AQAHAAgIgw+lfAC5AQAAAA==.Tyyppi:BAACLAAFFIEFAAIRAAIIbh+FBgC3AAARAAIIbh+FBgC3AAAsAAQKgSgAAhEABwgDJmQGABYDABEABwgDJmQGABYDAAAA.',Ub='Ubos:BAAALAADCggIEgABLAAECgcIEgACAAAAAA==.',Uf='Uflaks:BAAALAADCgcIAgAAAA==.',Uk='Ukulele:BAAALAAECgYIBgAAAA==.',Ul='Ullasven:BAABLAAECoEWAAMVAAcIFRKVKQCqAQAVAAcIFRKVKQCqAQAWAAEI4AY6OAAqAAAAAA==.',Um='Umbra:BAAALAADCggIBgAAAA==.',Un='Unholyfinger:BAAALAAECggICAAAAA==.Unlocky:BAABLAAECoEVAAIMAAcINghREgByAQAMAAcINghREgByAQAAAA==.',Ur='Urgatt:BAAALAAECgEIAQAAAA==.Uruzgan:BAAALAADCgIIAgAAAA==.',Va='Vadåvoldsomt:BAABLAAECoEZAAIDAAcI3Bw+MQBNAgADAAcI3Bw+MQBNAgAAAA==.Vandemerwe:BAAALAADCgMIAwABLAAECgcICQACAAAAAA==.Vanetia:BAACLAAFFIEGAAIBAAIIxxyhLACjAAABAAIIxxyhLACjAAAsAAQKgR4AAgEACAg+IK0pAKECAAEACAg+IK0pAKECAAAA.Varon:BAAALAADCgEIAQAAAA==.Vaseera:BAAALAADCggICAAAAA==.Vazov:BAAALAAECgcIEQAAAA==.',Ve='Velastra:BAAALAAECgEIAQAAAA==.Velmu:BAABLAAECoEgAAMdAAgIyxYsKgAGAgAdAAgIyxYsKgAGAgANAAgI4ww4OQCbAQAAAA==.Veno:BAAALAAECgUICAABLAAECggIHgAaAHYkAA==.Venoar:BAAALAADCgcIDAABLAAECggIHgAaAHYkAA==.',Vh='Vhayne:BAABLAAECoEUAAIOAAYIix7STgAEAgAOAAYIix7STgAEAgAAAA==.',Vi='Vivina:BAAALAADCggIKAAAAA==.',Vo='Voetto:BAAALAADCggIDwABLAAECgcIHAAkAFwfAA==.Volsung:BAAALAAECgYIEQAAAA==.',['Vå']='Våpen:BAAALAADCggICAAAAA==.',Wa='Warriuden:BAAALAADCggIEAAAAA==.Warrmax:BAAALAAECgEIAQAAAA==.',We='Weaverix:BAAALAADCgYIBgAAAA==.',Wi='Wienermunkki:BAACLAAFFIEHAAMnAAMI5BOlDACXAAAnAAIIlRGlDACXAAAkAAEIfQTSEgBDAAAsAAQKgScAAycACAjpH9sGANsCACcACAjpH9sGANsCACQABAgOFuI5AAoBAAAA.Wiippa:BAABLAAECoEXAAMJAAYIIgZ0VgDkAAAJAAUIogR0VgDkAAAIAAYIIgZKpgDAAAAAAA==.Wildflame:BAAALAADCggIGwAAAA==.Wimzy:BAABLAAECoEiAAIEAAgI6B84EwC0AgAEAAgI6B84EwC0AgAAAA==.Winntie:BAABLAAECoEoAAMPAAgItxQBHAD9AQAPAAgItxQBHAD9AQAHAAIInhKODwF9AAAAAA==.Wish:BAAALAADCggIDAAAAA==.',Wm='Wma:BAAALAAECggICAAAAA==.',Wq='Wqeqwewqe:BAAALAADCggIFAAAAA==.',Xi='Xinna:BAAALAADCggIFgAAAA==.',Xy='Xymbie:BAAALAADCgYICAABLAAECggIKAAPALcUAA==.',Ya='Yagata:BAABLAAECoEVAAIUAAcIxxiELwAfAgAUAAcIxxiELwAfAgAAAA==.',Yi='Yinxx:BAABLAAECoEgAAIfAAgItx/RBQDnAgAfAAgItx/RBQDnAgAAAA==.',Yo='Yogghurt:BAAALAADCggICAAAAA==.Yojab:BAAALAAECgYIDAAAAA==.Yopotato:BAACLAAFFIEFAAIIAAIIEhEYKgCXAAAIAAIIEhEYKgCXAAAsAAQKgRcAAggACAiEF5UuAFICAAgACAiEF5UuAFICAAAA.',Yu='Yuumienjoyer:BAAALAADCggICAABLAAFFAYIHAASAD4lAA==.',Za='Zabroz:BAAALAAFFAIIAgABLAAFFAIIBgAQAF4bAA==.Zalathor:BAAALAAECgcIEQAAAA==.Zandox:BAAALAADCgcIBwAAAA==.Zarra:BAAALAAECgcIDgAAAA==.',Ze='Zealvoker:BAAALAADCgcIBwAAAA==.Zetonex:BAEALAAECgIIAwABLAAFFAIIAwACAAAAAA==.Zetx:BAEALAAECgYICgABLAAFFAIIAwACAAAAAA==.Zeuhs:BAAALAAECgYIDAABLAAECggIEgACAAAAAA==.Zeuuss:BAAALAADCggICAAAAA==.',Zh='Zhaili:BAAALAADCgcIBwAAAA==.Zhen:BAABLAAECoEdAAIBAAYI9hoCfgC/AQABAAYI9hoCfgC/AQAAAA==.Zhhoop:BAAALAADCggIDwABLAAECggIJQAZABsjAA==.',Zi='Ziagon:BAAALAAECgYIEAAAAA==.Zibol:BAAALAAECgYIEAAAAA==.Zios:BAAALAADCggICAAAAA==.',Zk='Zku:BAABLAAECoEfAAMUAAgILRWkLAAvAgAUAAgILRWkLAAvAgAaAAQImgrizgCfAAAAAA==.',Zo='Zordiak:BAACLAAFFIEKAAIZAAMIbRu9CwAjAQAZAAMIbRu9CwAjAQAsAAQKgR4AAhkACAhMIKQZAMYCABkACAhMIKQZAMYCAAAA.Zorrillo:BAAALAADCgcIBwAAAA==.',Zr='Zravis:BAABLAAECoEYAAQIAAgIPhqzSgDZAQAIAAcIzBazSgDZAQAMAAMI0SHfGAAeAQAJAAEI6QNTigArAAAAAA==.',Zu='Zuperp:BAAALAAFFAIIAgABLAAFFAIICAASADQgAA==.',Zw='Zwietracht:BAAALAAECgYIBwAAAA==.',Zy='Zyborgagain:BAABLAAECoEmAAMcAAgIGCIuBwDlAgAcAAgImSAuBwDlAgAHAAgIbR+MHgDUAgAAAA==.',Zz='Zzloud:BAAALAADCgIIAgAAAA==.',['Zé']='Zét:BAEALAAFFAIIAwAAAA==.',['Ån']='Ånnas:BAAALAADCggIEAABLAAECgcIGwAKAIkjAA==.',['Éi']='Éiwyn:BAABLAAECoEhAAIDAAcIUSKWHQCrAgADAAcIUSKWHQCrAgAAAA==.',['Øl']='Ølmann:BAABLAAECoEdAAIZAAcIKBoHOQAVAgAZAAcIKBoHOQAVAgAAAA==.',['ßl']='ßlïzp:BAAALAAECgcIBwAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end