local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Monk-Windwalker','Hunter-BeastMastery','Hunter-Marksmanship','Paladin-Retribution','DeathKnight-Frost','Druid-Balance','Druid-Guardian','Mage-Arcane','Paladin-Holy','Mage-Frost','DemonHunter-Havoc','Unknown-Unknown','Shaman-Restoration','Priest-Holy','Priest-Discipline','Warrior-Fury','Warrior-Protection','Warrior-Arms','DeathKnight-Unholy','Shaman-Enhancement','Druid-Restoration','Shaman-Elemental','Monk-Mistweaver','Warlock-Affliction','DemonHunter-Vengeance','Warlock-Destruction','Rogue-Assassination','Evoker-Augmentation','Evoker-Devastation','Warlock-Demonology','Evoker-Preservation','DeathKnight-Blood','Mage-Fire','Monk-Brewmaster','Paladin-Protection','Rogue-Subtlety','Priest-Shadow','Hunter-Survival','Druid-Feral',}; local provider = {region='EU',realm='Thunderhorn',name='EU',type='weekly',zone=44,date='2025-09-23',data={Ab='Abdulsalam:BAACLAAFFIETAAIBAAYIdRyZAABbAgABAAYIdRyZAABbAgAsAAQKgSgAAgEACAg4JREDAFEDAAEACAg4JREDAFEDAAAA.Abufahunt:BAABLAAECoEjAAMCAAcIIyFxJQCEAgACAAcIIyFxJQCEAgADAAYIMBxjMQDgAQAAAA==.',Ae='Aerlis:BAAALAAECggIDwAAAA==.',Ag='Agoniac:BAAALAAECgcIEwAAAA==.',Ah='Ahaiyuto:BAABLAAECoEfAAICAAgIqwz0dACOAQACAAgIqwz0dACOAQAAAA==.',Ak='Akcope:BAAALAADCgYIBgAAAA==.Akilin:BAABLAAECoEfAAIEAAgIlhxRJwCtAgAEAAgIlhxRJwCtAgAAAA==.',Al='Alarite:BAAALAAECgMIBAAAAA==.Alassien:BAAALAAECgYIEQAAAA==.Alhu:BAAALAAECgEIAQAAAA==.Alithrielle:BAABLAAECoEXAAIFAAgIgyNMDwAlAwAFAAgIgyNMDwAlAwAAAA==.Altáriel:BAABLAAECoElAAIGAAgIPRngHABKAgAGAAgIPRngHABKAgAAAA==.Alympia:BAAALAAECgcIEQAAAA==.',Am='Ambrusik:BAACLAAFFIEJAAIHAAMIgRgmAQD4AAAHAAMIgRgmAQD4AAAsAAQKgSwAAgcACAieIu8BACoDAAcACAieIu8BACoDAAAA.Ammag:BAABLAAECoElAAIIAAgIuyLqDQAeAwAIAAgIuyLqDQAeAwAAAA==.Amun:BAAALAADCgUIAgAAAA==.',An='Andromede:BAABLAAECoEfAAIJAAgIWBqsEABoAgAJAAgIWBqsEABoAgAAAA==.Angoran:BAABLAAECoEYAAMKAAgIohTuIgDfAQAKAAcIOBbuIgDfAQAIAAcIhw4GbQCaAQAAAA==.Angrygoose:BAAALAADCgcIBwAAAA==.Anticlimaxs:BAAALAADCgIIAQABLAAECggIGwALAN4fAA==.',Ap='Apoly:BAAALAAECgYICAAAAA==.Aporita:BAAALAAECgYIEQAAAA==.',Ar='Aravel:BAAALAAECgQIBgAAAA==.Arcanight:BAAALAAECgYIDQAAAA==.Arcipopicis:BAAALAADCggIGAABLAAECggICAAMAAAAAA==.Ardegos:BAAALAAECgYIBgAAAA==.Arduo:BAAALAAECgMIAwAAAA==.Arenu:BAAALAADCggIEAAAAA==.Arganelement:BAABLAAECoEUAAINAAcIFg9TfwBEAQANAAcIFg9TfwBEAQAAAA==.Ariviel:BAABLAAECoEjAAMOAAgIiRZvKAAmAgAOAAgIiRZvKAAmAgAPAAIIxBQoJgByAAAAAA==.Arkamedes:BAAALAADCgcIDwAAAA==.Arkannay:BAAALAAFFAIIBAABLAAFFAMICwALAG0gAA==.Arowsong:BAAALAAECgIIAgAAAA==.',As='Asinikdy:BAAALAADCgYIBgAAAA==.Asta:BAACLAAFFIEFAAMQAAMIdBS+DwD+AAAQAAMIdBS+DwD+AAARAAII5AwTFwB4AAAsAAQKgRcAAxAABwiCHIosAFICABAABwiCHIosAFICABIABAgLCMMmAIgAAAAA.Astalda:BAAALAAECgMIBQAAAA==.',At='Athi:BAABLAAFFIEGAAIEAAIIZRw5GwC2AAAEAAIIZRw5GwC2AAAAAA==.Athian:BAACLAAFFIEGAAMTAAIIUxNaDAClAAATAAIIUxNaDAClAAAFAAEIUgMSawA6AAAsAAQKgSgAAxMACAj6GuoNAFwCABMABwgcHOoNAFwCAAUACAgVD6+dAIgBAAEsAAUUAggGAAQAZRwA.Athiu:BAAALAAECgYIBgABLAAFFAIIBgAEAGUcAA==.Athéh:BAAALAAECgIIBAAAAA==.',Av='Avacrusa:BAAALAAECgMIBQAAAA==.',Aw='Aw:BAAALAADCggICAABLAAECggIIAAFAMAbAA==.',Ba='Bakterius:BAAALAAECgYICgAAAA==.Bakterka:BAAALAADCggICAAAAA==.Bakulka:BAAALAAECgEIAQAAAA==.Baladir:BAAALAAECgIIAQAAAA==.Balos:BAACLAAFFIEGAAIOAAIILg9MIgCTAAAOAAIILg9MIgCTAAAsAAQKgSMAAg4ACAgzGp8fAFsCAA4ACAgzGp8fAFsCAAAA.Balzakhaar:BAABLAAECoEMAAIKAAYIew5NPQBSAQAKAAYIew5NPQBSAQABLAAFFAIIBQAUANUdAA==.Barroth:BAAALAAECgYIBgAAAA==.',Be='Bearbehemoth:BAAALAAECgMIBwAAAA==.Beastrr:BAAALAAECgYICAAAAA==.Beefgrinder:BAABLAAECoEiAAIVAAgIqCBdDgDEAgAVAAgIqCBdDgDEAgAAAA==.Belanor:BAAALAADCggICAAAAA==.Beleren:BAACLAAFFIEHAAIIAAMIeyAZFgAKAQAIAAMIeyAZFgAKAQAsAAQKgS4AAggACAggJVsKADMDAAgACAggJVsKADMDAAAA.Benihime:BAAALAAECgMIBAABLAAECgcIEwAMAAAAAA==.Benju:BAABLAAECoEVAAIEAAYIcA0uswBYAQAEAAYIcA0uswBYAQAAAA==.',Bi='Bigfoot:BAAALAAECgYIBgABLAAFFAIIBgAWAD4JAA==.',Bl='Blacklit:BAAALAAECggIDAAAAA==.Bladdy:BAAALAAECgIIAgAAAA==.Bllastoderm:BAAALAADCggICAABLAAFFAIIBgAWAD4JAA==.Bloodragnar:BAAALAAECgYICAAAAA==.Bloodwork:BAAALAADCgIIAgAAAA==.Blubbergutz:BAAALAADCggIEQAAAA==.Blády:BAACLAAFFIEGAAITAAII2B7zBwDCAAATAAII2B7zBwDCAAAsAAQKgSYAAhMACAirI9YBAE0DABMACAirI9YBAE0DAAAA.',Bo='Bobhilde:BAABLAAECoEcAAIIAAcIMRsjQAAnAgAIAAcIMRsjQAAnAgAAAA==.Bobkotvurce:BAAALAAECgEIAQAAAA==.Bondye:BAACLAAFFIEHAAMWAAMIewswEgDbAAAWAAMIewswEgDbAAANAAEIuAIiUAAtAAAsAAQKgSwAAhYACAixGF8iAG8CABYACAixGF8iAG8CAAAA.Boogthyr:BAAALAADCggIDQAAAA==.Boomheadshot:BAAALAAECggIDAAAAA==.Bosacik:BAAALAAECgYICAAAAA==.',Br='Brisdk:BAAALAAECgYIBgABLAAFFAMIBQAIAMUYAA==.',Bu='Bubletrouble:BAAALAADCgUIBQAAAA==.Buckler:BAAALAADCgcICQAAAA==.Budabudaa:BAAALAAECgYICgAAAA==.Buldozer:BAAALAADCgcICAAAAA==.Bunnie:BAABLAAECoEZAAIVAAgIpRSHLgD0AQAVAAgIpRSHLgD0AQAAAA==.',['Bé']='Bééfcakés:BAABLAAECoEhAAIFAAgIRRcCSwA0AgAFAAgIRRcCSwA0AgAAAA==.',['Bú']='Búh:BAAALAADCggIGAAAAA==.',Ca='Cajnekis:BAAALAAECgIIAgABLAAECggICgAMAAAAAA==.Caleya:BAAALAAECgcIEAAAAA==.Calsonis:BAAALAAECggIBgAAAA==.Camarr:BAAALAAECgUIBAAAAA==.Cassyndria:BAAALAAECgUIBQAAAA==.Castro:BAAALAAECgIIBAAAAA==.Cazian:BAABLAAECoEeAAICAAcIugn3lQBLAQACAAcIugn3lQBLAQAAAA==.',Ce='Cenerae:BAAALAAECgYICgAAAA==.Cerridwen:BAAALAAECggIEQAAAA==.Cerrsham:BAABLAAECoEdAAINAAcIdxQVWwCiAQANAAcIdxQVWwCiAQAAAA==.Certansia:BAAALAAECgMIAwAAAA==.',Ch='Chainpala:BAAALAAECgYIBgAAAA==.Charrizard:BAAALAADCggICAAAAA==.Cheater:BAAALAADCggICAAAAA==.Chibsbawz:BAAALAAECgEIAQAAAA==.Chompa:BAAALAADCggICAAAAA==.Chrisblast:BAAALAAECgYIDgAAAA==.Chriszugzug:BAAALAAECgYIEgAAAA==.Chronomancer:BAAALAAECgQIBAAAAA==.Chrysopelea:BAAALAADCgMIBAAAAA==.Chrysta:BAAALAAECgcIEwABLAAECgcIGQAXAKkVAA==.Chrystamist:BAABLAAECoEZAAIXAAcIqRWyGADHAQAXAAcIqRWyGADHAQAAAA==.',Ci='Cid:BAABLAAECoEfAAIYAAgI2RXKBgBIAgAYAAgI2RXKBgBIAgAAAA==.Cinek:BAAALAAECggICgAAAA==.Cineks:BAAALAAECgYICQAAAA==.Cinerous:BAAALAAECgMIAwABLAAECgcIGQAXAKkVAA==.Cirillá:BAABLAAECoElAAIZAAgIVRX9FQDmAQAZAAgIVRX9FQDmAQAAAA==.',Cl='Clarendon:BAAALAADCggIGAABLAAECgYICAAMAAAAAA==.',Co='Coalmaiden:BAAALAAECgIIAwAAAA==.Cognak:BAAALAADCggICwAAAA==.Condatis:BAAALAADCggICAAAAA==.Copy:BAAALAADCggIEQAAAA==.',Cr='Crazednight:BAAALAADCgIIAgABLAAECgcIIgAaAFQeAA==.Crazy:BAAALAADCggICAAAAA==.Crungle:BAABLAAECoEcAAIbAAgIGh0qDwCgAgAbAAgIGh0qDwCgAgAAAA==.Crush:BAAALAAECgYIBgAAAA==.Crustysock:BAABLAAECoEcAAIKAAgIoB0cDgCdAgAKAAgIoB0cDgCdAgAAAA==.',Da='Dancia:BAAALAAECgcIDQAAAA==.Dargrath:BAAALAAECgUIBQAAAA==.Darkertrixer:BAAALAADCgYIEAABLAAECgYICAAMAAAAAA==.Darkragnar:BAAALAAECgQIBAAAAA==.Davyjoanes:BAAALAADCgYIBgAAAA==.Daxtrila:BAABLAAECoEdAAIUAAgI9BSeCgAkAgAUAAgI9BSeCgAkAgAAAA==.',De='Deadfrost:BAABLAAECoEnAAMTAAgI/CJBBAAQAwATAAgI/CJBBAAQAwAFAAYI8xZ1hwCvAQAAAA==.Deagan:BAAALAADCgMIAwABLAADCggICAAMAAAAAA==.Deathbaron:BAAALAAECgYIEQAAAA==.Deathdesmo:BAAALAADCgMIAwAAAA==.Deathnienna:BAAALAAECggICAAAAA==.Deathofchi:BAAALAAECggICgAAAA==.Deceptacona:BAAALAAECgYICwAAAA==.Deemoan:BAAALAADCgUIBQAAAA==.Deepfell:BAAALAAECgcIDAAAAA==.Defective:BAAALAAECgcICgABLAAFFAMIDAACADMRAA==.Denebalgedi:BAABLAAECoEmAAMYAAgIshR3CgD1AQAYAAcIkRV3CgD1AQAaAAII0g4vvAB8AAAAAA==.Dessa:BAAALAAECgYIDgAAAA==.',Di='Diabolist:BAABLAAECoEeAAIWAAYIbRlZQwDGAQAWAAYIbRlZQwDGAQAAAA==.Diabolisto:BAABLAAECoEbAAIaAAYIOR6LRQDxAQAaAAYIOR6LRQDxAQAAAA==.Digimonic:BAABLAAECoEXAAMEAAgIrR+0VwAMAgAEAAYIoh+0VwAMAgAJAAgIqQ5AIQDWAQAAAA==.Dinozo:BAABLAAECoEkAAMVAAgIuh6CEACxAgAVAAgIuh6CEACxAgAHAAUIfgiTHgDKAAAAAA==.Divi:BAAALAAECgcIDQAAAA==.Divinestorm:BAAALAAECgYICwAAAA==.',Dn='Dnny:BAAALAADCggIEAABLAAFFAMIBQALAFgQAA==.',Do='Doloxene:BAABLAAECoEVAAICAAcI0BSrZgCvAQACAAcI0BSrZgCvAQAAAA==.Dot:BAABLAAECoEcAAMaAAgIOB4oIACkAgAaAAgIbR0oIACkAgAYAAMI7CBEGwADAQAAAA==.',Dr='Dracalu:BAABLAAECoEmAAIcAAgIuhfrBAA8AgAcAAgIuhfrBAA8AgAAAA==.Dragontear:BAAALAAECgYIBgAAAA==.Drakek:BAAALAAECgUIBQAAAA==.Drakestalker:BAAALAADCgcIBwAAAA==.Drens:BAAALAAECgUIBAAAAA==.Drexxyl:BAAALAADCgUIBQAAAA==.Drgonzoo:BAAALAAECggIEAAAAA==.Driztdourden:BAAALAADCggICAAAAA==.Droderog:BAAALAAECgcIEQABLAAECggIIwAOAIkWAA==.Druffy:BAABLAAECoEmAAICAAgIBiJDGADPAgACAAgIBiJDGADPAgAAAA==.Druidzor:BAAALAAECgcIDAAAAA==.',Du='Dualshock:BAAALAAECgYICAAAAA==.Duffthyr:BAAALAAECgYIBwABLAAECggIJgACAAYiAA==.Durinko:BAABLAAECoEjAAIOAAgIMxW2LQAKAgAOAAgIMxW2LQAKAgAAAA==.Durzik:BAAALAAECgYICQAAAA==.',Dv='Dvnny:BAAALAAECggIEAABLAAFFAMIBQALAFgQAA==.',Ed='Edgerlol:BAAALAAECgMIAwAAAA==.Edwar:BAAALAAECgYICQAAAA==.',Ef='Efearus:BAAALAAECgMIAwAAAA==.',Ei='Eifah:BAAALAADCggICAAAAA==.Eiffah:BAAALAADCggIFwAAAA==.',El='Eldracono:BAABLAAECoEZAAMdAAgIwRPNHQANAgAdAAgIwRPNHQANAgAcAAEIiwlmFwAiAAAAAA==.Eldris:BAAALAADCgIIAgAAAA==.Electricss:BAABLAAECoEeAAMUAAgIEB3EBADBAgAUAAgIEB3EBADBAgAWAAEIXAYRsAAnAAAAAA==.Elfina:BAAALAAECgYICAAAAA==.Elimerebus:BAAALAADCgQIAgAAAA==.Elimkarsus:BAAALAAECgYIBgAAAA==.Elpatron:BAACLAAFFIEGAAIQAAIIEhFEIwCaAAAQAAIIEhFEIwCaAAAsAAQKgSIAAhAACAjnHSIuAEoCABAACAjnHSIuAEoCAAAA.',Em='Emberwing:BAAALAAECgYICgAAAA==.Emphasized:BAAALAADCgcIEAABLAAFFAIIBQAUANUdAA==.',En='Enduras:BAABLAAECoEYAAINAAgIlBjYLwArAgANAAgIlBjYLwArAgAAAA==.',Er='Eryteis:BAABLAAECoEjAAMeAAgIzBilEABbAgAeAAgIzBilEABbAgAaAAIIgA2wwQBsAAAAAA==.',Et='Eternuter:BAAALAAECgYIBwAAAA==.Etex:BAABLAAECoEfAAICAAgIyyCpFQDfAgACAAgIyyCpFQDfAgAAAA==.',Ev='Evhuuker:BAABLAAECoEUAAIcAAcI6w1DCgCCAQAcAAcI6w1DCgCCAQAAAA==.Evin:BAAALAADCgcIDQAAAA==.',Ez='Ezomic:BAABLAAECoEhAAMUAAgIcCFRAgAbAwAUAAgIcCFRAgAbAwANAAYIkhSEcABoAQABLAAFFAIIBQAUANUdAA==.Ezran:BAAALAADCgYIBgAAAA==.',Fa='Fadewyn:BAAALAAECgQIBAABLAAFFAMICwALAG0gAA==.Faerin:BAAALAAECgQIBAAAAA==.Faith:BAAALAAECggICAAAAA==.Falcorr:BAABLAAECoETAAMfAAYICQlSJAD8AAAfAAYICQlSJAD8AAAdAAMIYAq6UAB4AAABLAAECggIHAALALQTAA==.Farqon:BAAALAAECggIEwAAAA==.',Fe='Fennixx:BAEBLAAECoEkAAIJAAgI6xDjIADZAQAJAAgI6xDjIADZAQAAAA==.Ferdinan:BAAALAADCggICAAAAA==.',Fi='Fiddyon:BAAALAAECggICAAAAA==.',Fl='Flákotka:BAAALAAECgMIAwAAAA==.',Fo='Fornixa:BAABLAAECoEfAAICAAgILgqjhQBrAQACAAgILgqjhQBrAQAAAA==.Foxilego:BAABLAAECoEkAAIgAAgIBSLvBAAJAwAgAAgIBSLvBAAJAwAAAA==.',Fr='Frankíee:BAABLAAECoEcAAIRAAcI5RX5JwC+AQARAAcI5RX5JwC+AQAAAA==.Frimtha:BAAALAAECgYIDgAAAA==.Frostblade:BAAALAAECgYIEAAAAA==.',Fu='Fuldaftrix:BAABLAAECoEjAAIhAAgIzyVJAAB4AwAhAAgIzyVJAAB4AwAAAA==.Fuzzyvendra:BAAALAAECgEIAQAAAA==.',['Fä']='Fäith:BAAALAAECgYICAAAAA==.',Ga='Gaalkaa:BAAALAAECgYIDAAAAA==.Garrakelim:BAAALAAECgYICAAAAA==.',Ge='Gendra:BAAALAADCgYIBgAAAA==.',Gg='Gg:BAAALAADCggICwABLAAECgIIAwAMAAAAAA==.',Gh='Ghostdin:BAAALAAECgYIBgAAAA==.Ghostid:BAABLAAECoEfAAMGAAgIMRrwOACgAQAGAAYIyhjwOACgAQAVAAgI1A+sRACQAQABLAAECgYIBgAMAAAAAA==.Ghostmourne:BAAALAADCggIEwABLAAECgYIBgAMAAAAAA==.',Gi='Gildedbeard:BAAALAAECgYICQAAAA==.Gimdalf:BAACLAAFFIEOAAIEAAQIByS/BQCxAQAEAAQIByS/BQCxAQAsAAQKgS4AAgQACAiaJt4AAJUDAAQACAiaJt4AAJUDAAAA.Gine:BAAALAADCgUICgABLAAECggIIAAFAMAbAA==.',Gn='Gnoliska:BAAALAADCggICAAAAA==.',Go='Golzik:BAAALAAECgcIDQAAAA==.Gotts:BAABLAAECoEbAAIQAAgIixVdMgA2AgAQAAgIixVdMgA2AgAAAA==.',Gr='Grifel:BAAALAAECgYIBgABLAAECggIFQAUAK0eAA==.Grimmo:BAABLAAECoEYAAMPAAcIWh9gBQBJAgAPAAYIhCJgBQBJAgAOAAcI8RGvQwCgAQAAAA==.Grimous:BAAALAADCgcIBwAAAA==.Grisling:BAAALAAECgcIBwAAAA==.Groosome:BAAALAAECgYICgAAAA==.Gryf:BAAALAADCggIFwAAAA==.Gryph:BAABLAAECoEfAAMBAAgIkhhjFgAtAgABAAgIihZjFgAtAgAiAAcIvBekGACwAQAAAA==.',Gu='Gufr:BAAALAAECgYICwAAAA==.Gugulina:BAAALAAECgEIAQAAAA==.Guttenworgen:BAABLAAECoEfAAQYAAcIwA9yDgCvAQAYAAcI2w5yDgCvAQAaAAcI4wwdZgCHAQAeAAQIPgzNVgDmAAAAAA==.',Ha='Haert:BAAALAADCggICAAAAA==.Hajò:BAAALAADCgUIBQAAAA==.Hajø:BAACLAAFFIEJAAILAAMIOBBQEwDtAAALAAMIOBBQEwDtAAAsAAQKgSsAAwsACAh0IiUQABwDAAsACAh0IiUQABwDABkABgivEp0pAC0BAAAA.Hakmetoodeth:BAAALAAECgUIBAAAAA==.Hatok:BAAALAAECgYIBgAAAA==.Havi:BAACLAAFFIEGAAITAAIIzyIiBwDLAAATAAIIzyIiBwDLAAAsAAQKgSMAAhMACAjLHR4IAMICABMACAjLHR4IAMICAAAA.',Hd='Hdh:BAABLAAECoEcAAILAAYI4SFwPgA6AgALAAYI4SFwPgA6AgAAAA==.',He='Headshot:BAABLAAECoEYAAICAAgI5BZ6SAD/AQACAAgI5BZ6SAD/AQAAAA==.Healga:BAAALAADCggIDgAAAA==.Helldrool:BAABLAAECoEeAAILAAgIrhooMAByAgALAAgIrhooMAByAgAAAA==.Helltear:BAAALAAECgcIBwAAAA==.Henke:BAABLAAECoEcAAMYAAgIQgrSDgCoAQAYAAgIognSDgCoAQAaAAYIzgbekAASAQAAAA==.',Hi='Hiduken:BAABLAAECoEeAAIRAAgIaCF8CQDoAgARAAgIaCF8CQDoAgAAAA==.Hildari:BAABLAAECoEbAAILAAgI3h+2HwDCAgALAAgI3h+2HwDCAgAAAA==.',Ho='Hoblajs:BAAALAADCggICAAAAA==.Holy:BAAALAAECgQIBAAAAA==.Holycambria:BAABLAAECoEsAAMjAAgIixf6GgDlAQAjAAgI7BP6GgDlAQAEAAcIWxd9egDBAQAAAA==.Holymoli:BAAALAAECgYIEQAAAA==.Holywolf:BAAALAAECgcICQAAAA==.Hondra:BAAALAAECgYIDAABLAAFFAIIAgAMAAAAAA==.Honilsom:BAABLAAECoEZAAIDAAYIoQ6NWgAzAQADAAYIoQ6NWgAzAQAAAA==.',Hr='Hrok:BAAALAADCgEIAQAAAA==.',Hu='Hurn:BAAALAAECgcIDQAAAA==.',Ic='Ictaria:BAAALAAECgYICAABLAAECggIIAAjAG4jAA==.',Ig='Ignitis:BAABLAAECoELAAIIAAYIJhXUdACEAQAIAAYIJhXUdACEAQAAAA==.',Il='Ilidary:BAAALAAECgIIAgAAAA==.Iloet:BAAALAAECggICQAAAA==.',Im='Imogine:BAEBLAAECoEoAAMbAAgINyETCAD3AgAbAAgINyETCAD3AgAkAAYIcA4RIwBKAQABLAAFFAMIBQAFAHwTAA==.',In='Indiyo:BAAALAAECgYIBgABLAAECggIHAALALQTAA==.',Io='Iona:BAABLAAECoElAAIiAAgI4Rk5DQBXAgAiAAgI4Rk5DQBXAgAAAA==.Ioness:BAAALAAECgUIBQAAAA==.',Ir='Iridak:BAAALAAECggIDgABLAAFFAQICgAFAHYTAA==.Ironside:BAABLAAECoEsAAIQAAgIvxbCLwBDAgAQAAgIvxbCLwBDAgAAAA==.',Is='Issis:BAAALAAECgUIBAAAAA==.',It='Italbuffino:BAABLAAECoEXAAIFAAgI2BvONwBuAgAFAAgI2BvONwBuAgAAAA==.Ithiriel:BAABLAAECoEWAAITAAgIthIiEQAxAgATAAgIthIiEQAxAgAAAA==.Ithlinne:BAAALAADCggIFAAAAA==.',Iy='Iyzebel:BAABLAAECoEaAAIYAAcIewsrEACTAQAYAAcIewsrEACTAQAAAA==.',Iz='Izë:BAAALAAECggICAAAAA==.',Ja='Jaksel:BAAALAAFFAEIAQABLAAECggIIQAJAGAaAA==.Jazrinka:BAABLAAECoEXAAINAAgIfg9kagB4AQANAAgIfg9kagB4AQAAAA==.Jazzfusion:BAAALAAECggIDgABLAAFFAIIAgAMAAAAAA==.',Je='Jeezu:BAABLAAECoEfAAIZAAgILhhaEgATAgAZAAgILhhaEgATAgAAAA==.Jeremiah:BAAALAADCggICAAAAA==.',Jo='Joli:BAABLAAECoElAAIaAAgIWBQHOAAoAgAaAAgIWBQHOAAoAgAAAA==.Jonky:BAAALAADCgUIBgAAAA==.Jonyblaze:BAAALAAECgYIBgAAAA==.',Ju='Juistyna:BAAALAAECgEIAgAAAA==.',['Jä']='Jäähis:BAAALAADCggIEAAAAA==.',['Jé']='Jésý:BAAALAAFFAIIAgAAAA==.',Ka='Kacoper:BAECLAAFFIEFAAIFAAMIfBNDFgD2AAAFAAMIfBNDFgD2AAAsAAQKgRsAAgUACAjqILoWAPwCAAUACAjqILoWAPwCAAAA.Kahlen:BAAALAADCgUIBQAAAA==.Kaito:BAAALAAECgYIDwAAAA==.Kamelie:BAAALAADCgUIBQAAAA==.Kaméllie:BAABLAAECoEdAAMfAAcItRUeEgDZAQAfAAcItRUeEgDZAQAcAAEIlAc7FwAlAAAAAA==.Karoliinka:BAAALAAECgcICAAAAA==.Karolinkalw:BAABLAAECoEdAAIGAAcIWgs2RwBdAQAGAAcIWgs2RwBdAQAAAA==.',Ke='Keepup:BAAALAADCggIAgAAAA==.Kenlee:BAAALAAECgcIEAAAAA==.Kentán:BAABLAAECoEiAAIVAAYI6iJdHQBRAgAVAAYI6iJdHQBRAgAAAA==.',Kh='Khazos:BAAALAADCgcIDQAAAA==.',Ki='Kidlil:BAAALAAECgYIEwAAAA==.Kiilshot:BAAALAAECggICAAAAA==.Kiloru:BAAALAAECgMIAwABLAAECggIJAACAIEgAA==.Kiree:BAABLAAECoEdAAICAAcIRgtGkwBQAQACAAcIRgtGkwBQAQAAAA==.',Kl='Klarion:BAAALAADCggICAAAAA==.Klerdinia:BAABLAAECoEgAAIjAAgIbiM3AwBDAwAjAAgIbiM3AwBDAwAAAA==.',Kn='Knatchlocker:BAABLAAECoEUAAIeAAYInSFVFgAnAgAeAAYInSFVFgAnAgAAAA==.',Ko='Kocovina:BAAALAAECgMIAwAAAA==.Kodariah:BAABLAAECoEfAAMTAAgIKhyzEQAqAgATAAcIZR6zEQAqAgAFAAgI+RShZQDzAQAAAA==.Kodarisah:BAAALAADCgYIBgABLAAECggIHwATACocAA==.Kongfoo:BAAALAAECgUIBAAAAA==.Konsu:BAAALAAECgYIEAAAAA==.',Kr='Kragira:BAABLAAECoEgAAIIAAgIGhlmMgBgAgAIAAgIGhlmMgBgAgAAAA==.Krisoc:BAABLAAECoEbAAIZAAgItRwfCwB7AgAZAAgItRwfCwB7AgAAAA==.Krystalle:BAAALAADCgcIBwAAAA==.',Ky='Kyhulla:BAABLAAECoEjAAIVAAcIJiFrEwCYAgAVAAcIJiFrEwCYAgAAAA==.Kylaara:BAAALAADCggIEgABLAAECgcIEQAMAAAAAA==.',['Kí']='Kíla:BAAALAAECggIEAAAAA==.',['Kû']='Kûky:BAABLAAECoEfAAIKAAYIiBk0JgDKAQAKAAYIiBk0JgDKAQABLAAECgcIIgAVAOoiAA==.',La='Laday:BAAALAADCgIIAgAAAA==.Laivin:BAAALAAECggIDgAAAA==.Lambrusco:BAAALAADCgcICAAAAA==.Landoria:BAAALAADCggICgAAAA==.Landoría:BAABLAAECoEeAAMlAAgIIxNoKQAQAgAlAAgIIxNoKQAQAgAOAAEIYgNXqgAfAAAAAA==.',Lb='Lbjdru:BAAALAADCgYIBgAAAA==.',Le='Leaa:BAACLAAFFIEHAAMaAAMIYwqYGwDdAAAaAAMIYwqYGwDdAAAeAAII6wb3FACNAAAsAAQKgS0AAx4ACAj5F3wVAC4CABoACAh2Fn4zAD0CAB4ACAhhFnwVAC4CAAAA.Lelith:BAAALAADCggIDAAAAA==.Lesie:BAACLAAFFIEFAAIIAAMIMRcKGAD7AAAIAAMIMRcKGAD7AAAsAAQKgSEAAggACAgaHkMjAKkCAAgACAgaHkMjAKkCAAAA.Lesk:BAAALAAECgYIEQAAAA==.Lesong:BAAALAAECgYIDgAAAA==.Leyona:BAAALAAECgYIEAAAAA==.',Li='Lichdevil:BAABLAAECoEgAAIFAAgIAhaKTAAwAgAFAAgIAhaKTAAwAgAAAA==.Lillydan:BAACLAAFFIELAAILAAMIbSAUDgAcAQALAAMIbSAUDgAcAQAsAAQKgSoAAwsACAhGJtUEAGgDAAsACAjOJdUEAGgDABkABggQJZcLAHQCAAAA.Linocka:BAACLAAFFIEGAAINAAIIZAXzQQBmAAANAAIIZAXzQQBmAAAsAAQKgSoAAg0ACAjdHD8aAI4CAA0ACAjdHD8aAI4CAAAA.Liora:BAAALAAECgYICQAAAA==.Littlbits:BAAALAADCggIEAAAAA==.Lizix:BAABLAAECoEmAAICAAgIQSEWEgD1AgACAAgIQSEWEgD1AgAAAA==.',Lo='Lobster:BAAALAAFFAIIAgAAAA==.Lokkis:BAAALAADCgcIBgAAAA==.Lorhaen:BAAALAADCgcICAAAAA==.Lotara:BAAALAAECgQIBAAAAA==.Lothical:BAAALAADCggICAAAAA==.Lowbros:BAAALAAECgEIAQAAAA==.Lowrider:BAAALAAECgUICQAAAA==.Lowshot:BAAALAAECgMIAwAAAA==.',Lu='Lua:BAAALAAECggICAAAAA==.Lumikìssa:BAABLAAECoElAAICAAgI1BwZLwBaAgACAAgI1BwZLwBaAgAAAA==.Lunarflare:BAAALAADCggICAABLAAECggIGAANAJQYAA==.Lunatoriana:BAAALAAECgIIAgAAAA==.Lusi:BAABLAAECoErAAMYAAgIFBr1BQBgAgAYAAgIdRj1BQBgAgAaAAgImRZ5NQA0AgAAAA==.',Ly='Lycona:BAAALAADCgcIBwAAAA==.Lydor:BAAALAADCgIIAgAAAA==.',['Lò']='Lòthical:BAABLAAECoEVAAIHAAYIoAvGGAANAQAHAAYIoAvGGAANAQAAAA==.',['Ló']='Lóthical:BAAALAADCgIIAgAAAA==.',Ma='Maahes:BAAALAAECgcICAAAAA==.Made:BAAALAADCgYIBAAAAA==.Mageby:BAABLAAECoEVAAIIAAgI/RD4VQDdAQAIAAgI/RD4VQDdAQAAAA==.Maidmarians:BAAALAAECggIEQAAAA==.Malchior:BAAALAAFFAEIAQAAAA==.Mandrell:BAAALAADCgEIAQAAAA==.Manke:BAAALAAECgcIDgAAAA==.Markita:BAABLAAECoEaAAIOAAcIQhqCLAAQAgAOAAcIQhqCLAAQAgAAAA==.Masaakry:BAABLAAECoEMAAIKAAYIuxXsLQCeAQAKAAYIuxXsLQCeAQAAAA==.Masakkry:BAACLAAFFIEGAAIBAAIIDR+JCAC6AAABAAIIDR+JCAC6AAAsAAQKgRkAAwEABgimI6IQAHQCAAEABgimI6IQAHQCABcAAwjUGkMwAOcAAAAA.Masakry:BAACLAAFFIEJAAIBAAMIAhXeBQD+AAABAAMIAhXeBQD+AAAsAAQKgScAAwEACAiKInwHAAIDAAEACAiKInwHAAIDACIABgixFMIgAFUBAAAA.Mathrin:BAAALAADCgcIDgAAAA==.Maydalena:BAAALAAECgcICAAAAA==.',Mc='Mcslashy:BAAALAADCggICAAAAA==.',Me='Meeleys:BAACLAAFFIEGAAIdAAII6xeOEACgAAAdAAII6xeOEACgAAAsAAQKgRgAAh0ACAisHXIQAJwCAB0ACAisHXIQAJwCAAAA.Mekkazap:BAABLAAECoEcAAMWAAcIohhcNQAFAgAWAAcIohhcNQAFAgANAAMIpAYm8wBaAAAAAA==.Meruem:BAAALAAECgcIEwAAAA==.',Mi='Mikerino:BAAALAADCgcICAAAAA==.Mikki:BAABLAAECoEYAAIaAAgI7A3UTgDPAQAaAAgI7A3UTgDPAQAAAA==.Milkacsoki:BAAALAADCgIIAgAAAA==.Milkmage:BAAALAADCggIDAAAAA==.Mint:BAAALAAECggICAAAAA==.Minysek:BAAALAAECgEIAQAAAA==.',Mo='Mootz:BAABLAAECoEgAAMHAAgIdh/YAwDLAgAHAAgIdh/YAwDLAgAVAAQIDQHjuQArAAAAAA==.Mortalbeam:BAAALAADCggIDQAAAA==.Mosler:BAABLAAECoEdAAMWAAcIwxn0LQArAgAWAAcIwxn0LQArAgANAAEIagp2DwElAAAAAA==.Moúntaindew:BAAALAAECgEIAQAAAA==.',Mu='Muridon:BAAALAAECgUIBAAAAA==.Musk:BAAALAADCgcICwAAAA==.',My='Myczlalka:BAAALAAECgcIDAAAAA==.Mynim:BAAALAAECgQIBAAAAA==.Mynimb:BAABLAAECoEXAAMdAAgIWBIFHwACAgAdAAgIWBIFHwACAgAfAAEI1Ay/NgA3AAAAAA==.Mynimd:BAAALAADCgIIAgAAAA==.Mynimdh:BAAALAADCgcICQAAAA==.Myrscilka:BAABLAAECoEmAAICAAgI/xtoLgBdAgACAAgI/xtoLgBdAgAAAA==.',['Má']='Mákárá:BAACLAAFFIELAAIlAAMI2Q5EDgDiAAAlAAMI2Q5EDgDiAAAsAAQKgRoAAiUACAiSG/UcAGkCACUACAiSG/UcAGkCAAAA.',['Mé']='Mélfina:BAAALAAECgcICwAAAA==.',['Mü']='Müchomurka:BAABLAAECoEfAAIhAAcIxAelCgBcAQAhAAcIxAelCgBcAQAAAA==.',Na='Nacatta:BAAALAAECgUIBAAAAA==.Naleno:BAABLAAECoEfAAMRAAgIIyFHDAC+AgARAAgIIyFHDAC+AgAQAAUI0hPqdwBOAQAAAA==.Narak:BAACLAAFFIEFAAILAAMIJwpZFQDdAAALAAMIJwpZFQDdAAAsAAQKgSkAAgsACAgSHkkfAMUCAAsACAgSHkkfAMUCAAAA.Natanek:BAACLAAFFIEGAAIVAAII6RiJFgCjAAAVAAII6RiJFgCjAAAsAAQKgSsAAxUACAhSJekBAFwDABUACAhSJekBAFwDAAYAAQikESGLADYAAAAA.Naturelolxdb:BAAALAAECgIIAgAAAA==.Natylienacz:BAACLAAFFIEGAAINAAII5CDtFgDAAAANAAII5CDtFgDAAAAsAAQKgSEAAg0ACAjNIvkLAO4CAA0ACAjNIvkLAO4CAAAA.',Ne='Neferkhepri:BAAALAAECgMIBAAAAA==.Neirdae:BAABLAAECoEZAAMWAAgI8QylQgDJAQAWAAgI8QylQgDJAQANAAMIlQlR6wBpAAAAAA==.Neirin:BAAALAADCggICAABLAAECggIGAANAJQYAA==.Nes:BAACLAAFFIENAAMEAAUIRB4TAwD4AQAEAAUIRB4TAwD4AQAjAAIIZCLBBwC4AAAsAAQKgScAAwQACAgmJasTABEDAAQACAgOJasTABEDACMACAgCI8QGAPACAAAA.',Ni='Niobê:BAABLAAECoEcAAMCAAcIqRZgWgDOAQACAAcIqRZgWgDOAQAmAAIInAUjHQBTAAAAAA==.Niveann:BAAALAAECgYIEAAAAA==.Nixxar:BAAALAAECgYIEgABLAAFFAMICQAEAG4cAA==.',No='Noevee:BAAALAAFFAIIAgAAAA==.Noitatohtori:BAABLAAECoEqAAINAAgI6iRVBAA4AwANAAgI6iRVBAA4AwAAAA==.',Nu='Nuggies:BAAALAADCgIIAgAAAA==.',Nw='Nwal:BAAALAADCggIDgAAAA==.',Ny='Nyala:BAAALAADCggICAAAAA==.Nysahj:BAABLAAECoEjAAIOAAcIuiADHAB0AgAOAAcIuiADHAB0AgAAAA==.',['Ní']='Níghtfáll:BAAALAADCgYIBgAAAA==.',['Nö']='Nöxim:BAABLAAECoEsAAIBAAgIQSADCQDnAgABAAgIQSADCQDnAgAAAA==.',['Ný']='Nýxx:BAAALAAECggIAgAAAA==.',Oc='Oco:BAAALAADCgMIAwAAAA==.Oct:BAAALAADCgQIBAAAAA==.',Ov='Ovee:BAAALAAECgYIEwAAAA==.',Pa='Paawjoe:BAAALAAECgYIBAAAAA==.Padlo:BAAALAAECgMIAwABLAAECgYIEAAMAAAAAA==.Padlova:BAAALAAECgYIEAAAAA==.Pampík:BAAALAAECggICAAAAA==.Panfiluta:BAAALAAECgUIDAAAAA==.Papajoe:BAAALAADCgQIBAABLAAECggIIAAFAMAbAA==.Patty:BAABLAAECoEYAAIHAAgI/Bh3BwBMAgAHAAgI/Bh3BwBMAgAAAA==.',Pe='Peepo:BAAALAAECggIEAAAAA==.Peterplys:BAAALAADCggIBwABLAAECgMIAwAMAAAAAA==.',Pi='Pig:BAABLAAECoEVAAMHAAgIkxdMCgAFAgAHAAcI0xhMCgAFAgAnAAgIVg7tFwC9AQAAAA==.Pikydk:BAABLAAECoEbAAIFAAgIsxqfPQBbAgAFAAgIsxqfPQBbAgAAAA==.Pikywarr:BAAALAAECgIIAgAAAA==.Pinkypong:BAABLAAECoEgAAIBAAgI4w81IADKAQABAAgI4w81IADKAQAAAA==.Pivik:BAABLAAECoEeAAMeAAgIxhjZDgBvAgAeAAgIxhjZDgBvAgAaAAEINBED1QA4AAAAAA==.Pivo:BAAALAAECgMIAwAAAA==.',Pl='Plechovej:BAABLAAECoEqAAMJAAgIkSFrBAAKAwAJAAgIkSFrBAAKAwAEAAQIuA/Z7wDVAAAAAA==.',Po='Pomohaci:BAABLAAECoEZAAMJAAgIRhfsIgDLAQAJAAcIlxXsIgDLAQAEAAcIDA1elgCMAQABLAAFFAQIDwAfABIdAA==.Ponderin:BAAALAADCggICAAAAA==.Poranek:BAABLAAECoEeAAIVAAcIoBGnRwCFAQAVAAcIoBGnRwCFAQAAAA==.Poro:BAAALAAECgIIAgAAAA==.',Pr='Prak:BAAALAADCgcIBwAAAA==.Prciina:BAAALAAECggIEwABLAAFFAIIBgAWAD4JAA==.Prednizon:BAABLAAECoEeAAICAAgI3RlVMwBIAgACAAgI3RlVMwBIAgAAAA==.Proenitus:BAAALAAECgcIEwAAAA==.Proklety:BAAALAAECgYICAAAAA==.Promice:BAAALAAECgMIAwAAAA==.Prompal:BAACLAAFFIEJAAIEAAMInAwvEQDkAAAEAAMInAwvEQDkAAAsAAQKgScAAgQACAgUHnolALUCAAQACAgUHnolALUCAAAA.Proteboss:BAAALAAECgUICAAAAA==.Protgryph:BAAALAAECgUIBQABLAAECggIHwABAJIYAA==.',Ps='Psychopomp:BAAALAAFFAIIAgAAAA==.',Px='Pxlclap:BAAALAAECggIEgABLAAFFAIIBAAMAAAAAA==.',['Pà']='Pàz:BAABLAAECoEUAAIVAAcIZhHjSwB1AQAVAAcIZhHjSwB1AQAAAA==.',Qa='Qaelrin:BAAALAAECgIIAgAAAA==.',Qu='Quantummyth:BAAALAADCgIIAgAAAA==.Quash:BAAALAAECgQIBAAAAA==.Quazigeorge:BAAALAAECgQIAwAAAA==.',Qw='Qw:BAAALAAECgYICQABLAAECggIIAAFAMAbAA==.',Ra='Raarmas:BAABLAAECoEWAAIEAAYIKxgrgwCwAQAEAAYIKxgrgwCwAQAAAA==.Rafe:BAABLAAECoEcAAICAAcIcAsziwBgAQACAAcIcAsziwBgAQAAAA==.Ragebar:BAAALAAECgIIAgAAAA==.Rainbows:BAABLAAFFIEFAAILAAMIWBBhEgDzAAALAAMIWBBhEgDzAAAAAA==.',Re='Redexice:BAAALAAECggIEwAAAA==.Remaqe:BAAALAADCggICQABLAAECggIKgACAEImAA==.Remuku:BAAALAADCgEIAQAAAA==.Rezz:BAAALAAECgYICAAAAA==.',Rh='Rhaalph:BAABLAAECoEeAAMNAAgI6yEmCwD1AgANAAgI6yEmCwD1AgAWAAcIRBBwSQCvAQAAAA==.',Ri='Rihox:BAACLAAFFIEGAAMEAAIImRl0HwCtAAAEAAIImRl0HwCtAAAJAAEIaApxHABIAAAsAAQKgSEABAQACAhGH2gfANICAAQACAhGH2gfANICAAkABgjgF3IoAKYBACMAAwjzEqNMAIUAAAAA.Riwex:BAAALAADCgIIAgAAAA==.Rize:BAAALAAECgYIDQAAAA==.',Ro='Robik:BAABLAAECoEpAAIOAAgI7RX2KwATAgAOAAgI7RX2KwATAgAAAA==.',Rs='Rsoul:BAAALAAECggIDgAAAA==.',Ry='Ryaz:BAAALAAECgYIDwAAAA==.',Sa='Saff:BAAALAADCgYIBgAAAA==.Sailock:BAAALAAECgYIBgABLAAECgcIFgAKABsOAA==.Saimage:BAABLAAECoEWAAMKAAcIGw73MACOAQAKAAcIGw73MACOAQAIAAMI+QUryABvAAAAAA==.Saintneen:BAAALAAECgcICAAAAA==.Saleh:BAAALAAECggIDAAAAA==.Saley:BAAALAADCgcIEAAAAA==.Sandshrew:BAAALAAECgYIDAAAAA==.Sanguestraz:BAAALAAFFAIIBAAAAA==.Sazzlay:BAAALAADCgUIBQAAAA==.Sazzlles:BAAALAADCggIFAAAAA==.',Sc='Scenotaph:BAAALAAECggICAAAAA==.Scoobacca:BAAALAAECgMICAAAAA==.Scrappydoo:BAAALAADCgcIBwAAAA==.Scullptor:BAAALAAECggIDwAAAA==.',Se='Seanie:BAAALAAECgEIAQABLAAFFAEIAQAMAAAAAA==.Sectator:BAABLAAECoEnAAICAAgIFSBSGgDDAgACAAgIFSBSGgDDAgAAAA==.Selenaja:BAAALAADCggICAAAAA==.Selentia:BAAALAADCggICAAAAA==.Senron:BAAALAAECgIIAgAAAA==.Sergen:BAAALAAFFAEIAgAAAA==.Sergendh:BAAALAADCggICAABLAAFFAEIAgAMAAAAAA==.Serina:BAAALAADCgcICAAAAA==.Serratus:BAAALAAECggIDQAAAA==.Serza:BAABLAAECoEaAAIZAAgIEx+CCQCbAgAZAAgIEx+CCQCbAgABLAAFFAEIAgAMAAAAAA==.Setartucus:BAAALAADCgQIBAAAAA==.Sevilla:BAAALAADCgMIAwAAAA==.Sevispook:BAAALAAECgYIEwAAAA==.',Sh='Shadepunk:BAAALAAECgYIEwAAAA==.Shadprincess:BAABLAAECoEfAAMBAAgIMxFzJQCfAQABAAcIjRJzJQCfAQAXAAUIMg2oMQDdAAAAAA==.Shagorsemst:BAAALAADCgEIAQAAAA==.Shammy:BAAALAAECgQIBQAAAA==.Shammyami:BAAALAAECgEIAQABLAAECgcIGQACAEgYAA==.Shankyernan:BAAALAAECgQIBgAAAA==.Shares:BAAALAADCggICAAAAA==.Shexye:BAAALAAECggIEgAAAA==.Shigi:BAABLAAECoEVAAIOAAcI3Ai0XQA+AQAOAAcI3Ai0XQA+AQAAAA==.Shimy:BAAALAADCgYICAAAAA==.Shiz:BAAALAAECgUIBAAAAA==.Shlongshanks:BAAALAADCggIDgAAAA==.Shootfire:BAAALAAECggIEAAAAA==.Shortpala:BAAALAADCgUICAAAAA==.',Si='Siarie:BAAALAADCgcIBwAAAA==.Siko:BAAALAADCgMIAwAAAA==.Silentshot:BAACLAAFFIEFAAIDAAIIyxQBGgCNAAADAAIIyxQBGgCNAAAsAAQKgSMAAgMABghqJbMZAH8CAAMABghqJbMZAH8CAAEsAAUUAwgHAAsAUSEA.Simonthedk:BAABLAAECoEZAAQgAAgIURywCgB8AgAgAAgIURywCgB8AgATAAUI2w1WNAAIAQAFAAEI3wNfVgEiAAAAAA==.Simplord:BAAALAADCgcIBwAAAA==.Simurgh:BAABLAAECoEaAAICAAcIew8qggByAQACAAcIew8qggByAQAAAA==.Sin:BAAALAAECgYIBgAAAA==.Sincara:BAAALAAECgYIBgAAAA==.Sisar:BAAALAADCggIHwAAAA==.Sixs:BAAALAADCggIBwAAAA==.',Sk='Skelendi:BAAALAADCgQIBwAAAA==.Skorina:BAABLAAECoEYAAICAAgIfws4egCDAQACAAgIfws4egCDAQAAAA==.Skridlama:BAAALAAECgcIBwAAAA==.',Sl='Sleepyjoe:BAAALAADCgcIBwAAAA==.Sloe:BAABLAAECoElAAIbAAgIGhXhGQAzAgAbAAgIGhXhGQAzAgAAAA==.Sluchátka:BAAALAAECgYIBgAAAA==.',Sm='Smolneen:BAAALAAECgYIDQAAAA==.Smrtacek:BAAALAAECgUIDAABLAAECgYIBwAMAAAAAA==.',Sn='Snowey:BAACLAAFFIEFAAIFAAQIUhoADABmAQAFAAQIUhoADABmAQAsAAQKgSUAAwUACAgWJHkSABMDAAUACAgWJHkSABMDABMAAgjwHqhCAJQAAAAA.Snuam:BAACLAAFFIEJAAIfAAMIYRLHBwDwAAAfAAMIYRLHBwDwAAAsAAQKgSwAAh8ACAgMJAwCADADAB8ACAgMJAwCADADAAAA.Snèáky:BAAALAAECgYIDAAAAA==.',So='Solan:BAAALAADCgIIAgAAAA==.Solaria:BAAALAADCgcIBwAAAA==.',Sp='Spagetak:BAAALAAECgYIDwAAAA==.Spherikal:BAAALAAECgYIDQABLAAECgYIEgAMAAAAAA==.Sprite:BAABLAAECoEfAAIZAAgIox+1BwDAAgAZAAgIox+1BwDAAgAAAA==.Spudclot:BAAALAAECgQIBwABLAAECgcIHAABAN8hAA==.Spudmonk:BAABLAAECoEcAAMBAAcI3yG0DQCbAgABAAcI3yG0DQCbAgAXAAQIxQvQNwCqAAAAAA==.',Sq='Squànchy:BAABLAAECoEUAAMDAAcIsBggPACrAQADAAYItRogPACrAQACAAMImQrm5gCHAAAAAA==.',St='Stebbs:BAAALAAECgEIAgAAAA==.Stormgrim:BAAALAADCgYIBgAAAA==.Stormpooper:BAACLAAFFIEGAAICAAMIPQ5kFwDEAAACAAMIPQ5kFwDEAAAsAAQKgSYAAgIACAjJIcQhAJgCAAIACAjJIcQhAJgCAAAA.Stulin:BAAALAAECgYIBgAAAA==.Stítch:BAAALAAECgMIAwAAAA==.',Su='Sudentähti:BAAALAADCggICAABLAAECgcIEQAMAAAAAA==.Suei:BAAALAADCgcIBwAAAA==.Sundaysangel:BAAALAAECgYICAAAAA==.Sundaysb:BAAALAAECgYIDQAAAA==.',Sv='Svelto:BAAALAAECgYIEAAAAA==.',Sw='Swell:BAAALAAECgcIDQAAAA==.',Sy='Sylesarin:BAABLAAECoEPAAMIAAYIqRkufgBrAQAIAAUIcBgufgBrAQAKAAEIyx+0cABeAAAAAA==.',['Sí']='Símurg:BAAALAAECgYICgAAAA==.',Ta='Tacolimey:BAAALAAECggIEQAAAA==.Tambari:BAAALAADCggIFgAAAA==.Taraskova:BAABLAAECoEbAAMEAAcIYA72kgCSAQAEAAcIYA72kgCSAQAJAAEIXwCrawANAAAAAA==.Tarasova:BAAALAADCgUIBQAAAA==.Tarasque:BAAALAADCggICAAAAA==.Tatuksa:BAAALAAECggICAAAAA==.Tauros:BAAALAAECgYIBgAAAA==.Tayem:BAABLAAECoElAAIGAAgI0BufFgCCAgAGAAgI0BufFgCCAgAAAA==.',Te='Tenebris:BAAALAADCgMIAwAAAA==.Terhenwizzle:BAABLAAECoEUAAIJAAgIBx5gCQC9AgAJAAgIBx5gCQC9AgAAAA==.Tesara:BAABLAAECoEVAAIEAAcIORt/SgAwAgAEAAcIORt/SgAwAgAAAA==.',Th='Thenightelf:BAAALAADCgQIBAAAAA==.Thenoob:BAAALAAECgEIAQAAAA==.Thergurn:BAAALAAECgMIAwAAAA==.Thisbee:BAAALAAECgYIDQAAAA==.Thoorstein:BAAALAAECgcIEgAAAA==.Thordeath:BAAALAAECgIIAgAAAA==.Thorguna:BAAALAADCggIDgAAAA==.Thrond:BAAALAADCggICgAAAA==.Thunderbolt:BAACLAAFFIEMAAICAAMIMxGNFQDNAAACAAMIMxGNFQDNAAAsAAQKgScAAgIACAhyHz0mAIECAAIACAhyHz0mAIECAAAA.Thundering:BAABLAAECoEbAAIEAAgIBBX+UAAdAgAEAAgIBBX+UAAdAgABLAAFFAMIDAACADMRAA==.',Ti='Tiazi:BAAALAADCggICAAAAA==.Timeismoney:BAAALAADCggIDAAAAA==.',To='Toftewolfe:BAAALAADCgQIBAAAAA==.Tokelau:BAAALAADCgMIAwAAAA==.Tooawesome:BAAALAADCgMIBAAAAA==.Torangon:BAABLAAECoEqAAMEAAgIsCPqFAALAwAEAAgIsCPqFAALAwAJAAQIAwtwUAC5AAAAAA==.Tori:BAAALAADCggICAAAAA==.',Tr='Trabantdh:BAAALAAECgIIAgAAAA==.Trueaim:BAAALAAECgIIAwAAAA==.Trynite:BAABLAAECoEfAAIiAAgIPRpwDQBTAgAiAAgIPRpwDQBTAgAAAA==.',Tw='Twin:BAAALAAECgcIDQABLAAFFAUICgACAMQdAA==.',Ty='Tylan:BAACLAAFFIEGAAIEAAIIGRCZLQCdAAAEAAIIGRCZLQCdAAAsAAQKgSoAAwQACAhNH6okALgCAAQACAhNH6okALgCACMABAgIGj9GAK4AAAAA.Tyrodar:BAABLAAECoEdAAICAAgIBAb9oAA1AQACAAgIBAb9oAA1AQAAAA==.',Ug='Ugugaga:BAABLAAECoEbAAMOAAgI+hzqFQCfAgAOAAgI+hzqFQCfAgAlAAcIJRuwIwA2AgAAAA==.',Ul='Ulgy:BAABLAAECoEWAAIQAAcIZRT2UgC5AQAQAAcIZRT2UgC5AQAAAA==.',Un='Uneducated:BAAALAAECgEIAQAAAA==.',Up='Uppity:BAABLAAECoEgAAINAAcIwxUbTADMAQANAAcIwxUbTADMAQAAAA==.',Va='Valchyna:BAAALAAECgYIEAAAAA==.Valkýra:BAABLAAECoEVAAIlAAcIPBc1KwAFAgAlAAcIPBc1KwAFAgAAAA==.Valontuoja:BAAALAADCgUICQABLAAECggIJQACANQcAA==.Valuna:BAABLAAECoEdAAIVAAgIYR3bEgCcAgAVAAgIYR3bEgCcAgAAAA==.Varjó:BAAALAAECgYIBgAAAA==.',Ve='Velaru:BAAALAADCgMIAwAAAA==.Velepytel:BAABLAAECoEVAAIgAAgIfhtpCwBtAgAgAAgIfhtpCwBtAgAAAA==.Velinia:BAABLAAECoEgAAIaAAgI/hjhKwBjAgAaAAgI/hjhKwBjAgAAAA==.Veliria:BAAALAAECggIDgAAAA==.Velkyprcek:BAACLAAFFIEGAAIWAAIIPgngIQCLAAAWAAIIPgngIQCLAAAsAAQKgRYAAxYACAgFG1sdAJACABYACAgFG1sdAJACABQABQiIFhkXAEYBAAAA.Velure:BAABLAAECoEjAAIgAAgI5hjRDQA9AgAgAAgI5hjRDQA9AgAAAA==.Velurien:BAAALAADCgUIBQAAAA==.Veranka:BAABLAAECoEfAAMiAAgIbA1cJQAqAQAiAAYItRFcJQAqAQABAAIIkgA/XwAQAAAAAA==.Vezire:BAAALAAECgYIEwAAAA==.',Vi='Vispi:BAAALAADCgIIAgABLAAFFAIICAANAGUhAA==.Vitally:BAAALAAECgYIEwAAAA==.',Vl='Vlczak:BAACLAAFFIEGAAIBAAIIkhmECgCiAAABAAIIkhmECgCiAAAsAAQKgSwAAgEACAjiI+8EAC4DAAEACAjiI+8EAC4DAAAA.',Vo='Voidria:BAABLAAECoEfAAIKAAgIDiRrAwBNAwAKAAgIDiRrAwBNAwAAAA==.Vojthino:BAACLAAFFIEGAAIkAAII4BIODQCWAAAkAAII4BIODQCWAAAsAAQKgSEAAiQACAiGG60LAFQCACQACAiGG60LAFQCAAAA.',Vr='Vrana:BAAALAAECgYIDQAAAA==.',Wa='Walys:BAAALAADCggIDwAAAA==.Warbarbie:BAAALAADCggIFgAAAA==.Wayen:BAAALAAECgYIBgABLAAECggIHwABAJIYAA==.',Wc='Wcranee:BAAALAAECgMIAwABLAAFFAUIDwABAL8cAA==.',We='Weatherwitch:BAAALAAECgQIBwAAAA==.Welrion:BAACLAAFFIEGAAIeAAIIWB97BwC4AAAeAAIIWB97BwC4AAAsAAQKgRUAAx4ACAgzJIgCAEMDAB4ACAgzJIgCAEMDABoAAQhDGM7MAEoAAAAA.Wenron:BAAALAADCggIFAAAAA==.',Wh='Whorgen:BAAALAADCggIGAAAAA==.',Wi='Wilczur:BAABLAAECoEeAAIHAAcIHBVADgCyAQAHAAcIHBVADgCyAQAAAA==.Wilke:BAABLAAECoEgAAIQAAgI7xNcPAALAgAQAAgI7xNcPAALAgAAAA==.Wixxyz:BAABLAAECoEWAAIGAAcIVSL2HgA4AgAGAAcIVSL2HgA4AgABLAAFFAcIGAAlAIQeAA==.',Wo='Woottoot:BAAALAADCggIJgAAAA==.Wordlesspie:BAABLAAECoEkAAILAAgI6x/QFwDuAgALAAgI6x/QFwDuAgAAAA==.',Wr='Wrathchild:BAAALAAECgUIBAAAAA==.',Xe='Xempo:BAABLAAECoEkAAMLAAgILB/1IAC8AgALAAgILB/1IAC8AgAZAAcIbRCKJgBDAQAAAA==.',Xr='Xrathis:BAAALAAECgYIBgAAAA==.',['Xá']='Xánder:BAAALAADCgQIBAAAAA==.',Ya='Yasmíne:BAAALAADCggICAAAAA==.',Yb='Ybolga:BAABLAAECoEfAAIJAAgISxL8IADYAQAJAAgISxL8IADYAQAAAA==.',Ye='Yersimr:BAABLAAECoEWAAIdAAcIRwqgMgBtAQAdAAcIRwqgMgBtAQAAAA==.',Ys='Ysja:BAAALAADCggIDwAAAA==.Ysæra:BAAALAADCgYIBgAAAA==.',Za='Zalira:BAAALAADCgQIAgAAAA==.Zarabro:BAAALAADCggICAAAAA==.Zatry:BAAALAADCggIDQAAAA==.Zatrý:BAABLAAECoEfAAMWAAgIWh/RFwC7AgAWAAgIWh/RFwC7AgANAAMI6hCi0AChAAAAAA==.Zatrýý:BAAALAADCgcIBwAAAA==.Zatterz:BAAALAAECgcIDQAAAA==.',Ze='Zediac:BAAALAAECgIIAgAAAA==.Zeeld:BAABLAAECoEXAAMiAAgIVRq+DABgAgAiAAgIVRq+DABgAgABAAcIqBNTJACoAQAAAA==.Zenwalker:BAAALAADCgcIDgAAAA==.Zerges:BAAALAAECgcIEAAAAA==.Zeryk:BAAALAAECgcICwAAAA==.Zevron:BAAALAAECgcIDQAAAA==.',Zi='Zifro:BAAALAAECgEIAQAAAA==.Zindanrish:BAABLAAECoEbAAMYAAgIvh0JBACmAgAYAAgIPh0JBACmAgAaAAUIKg/LkAATAQAAAA==.Zirka:BAACLAAFFIEJAAIOAAMICwaKFADIAAAOAAMICwaKFADIAAAsAAQKgSwAAg4ACAhQFlEpACICAA4ACAhQFlEpACICAAAA.',Zu='Zuellusek:BAAALAAECgUIBQAAAA==.Zulul:BAAALAADCgEIAQAAAA==.',['Ún']='Úniq:BAAALAADCgEIAgAAAA==.',['ßi']='ßishop:BAAALAAECgUIBAAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end