local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Druid-Restoration','Druid-Balance','Mage-Arcane','Warlock-Destruction','Unknown-Unknown','DeathKnight-Unholy','Rogue-Subtlety','Priest-Holy','Priest-Shadow','Priest-Discipline','Hunter-BeastMastery','Paladin-Holy','Warlock-Demonology','Monk-Brewmaster','DeathKnight-Blood','Evoker-Devastation','Evoker-Augmentation','DemonHunter-Havoc','Warrior-Fury','Paladin-Retribution','Rogue-Outlaw','Evoker-Preservation','Mage-Fire','DeathKnight-Frost','Mage-Frost','Warlock-Affliction','Shaman-Elemental',}; local provider = {region='EU',realm='Blackmoore',name='EU',type='subscribers',zone=44,date='2025-09-25',data={Ah='Ahawi:BAEBLAAECoEfAAMBAAgIQh04FgCKAgg5DAAABQA/ADsMAAAFAFEAOgwAAAQASwA8DAAABABRADIMAAAEAEsAPQwAAAQAVAA+DAAABABVAD8MAAABADIAAQAICEIdOBYAigIIOQwAAAQAPwA7DAAABABRADoMAAADAEsAPAwAAAMAUQAyDAAAAwBLAD0MAAADAFQAPgwAAAQAVQA/DAAAAQAyAAIABghnCwAAAAAABjkMAAABACUAOwwAAAEAHgA6DAAAAQATADwMAAABABMAMgwAAAEAKQA9DAAAAQAaAAAA.',Al='Alaeath:BAEALAADCgEIAQAAAA==.Alìna:BAECLAAFFIEFAAIDAAIIKCHVJAC7AAI5DAAAAwBcADoMAAACAEwAAwACCCgh1SQAuwACOQwAAAMAXAA6DAAAAgBMACwABAqBKgACAwAICKck9AYATwMAAwAICKck9AYATwMAAAA=.',Ar='Arff:BAEBLAAECoEdAAIDAAgIYCCZGwDUAgg5DAAABgBbADsMAAAFAE4AOgwAAAQAYgA8DAAABABZADIMAAAEAFwAPQwAAAMAWAA+DAAAAgA2AD8MAAABAEUAAwAICGAgmRsA1AIIOQwAAAYAWwA7DAAABQBOADoMAAAEAGIAPAwAAAQAWQAyDAAABABcAD0MAAADAFgAPgwAAAIANgA/DAAAAQBFAAEsAAUUBggWAAEA+BcA.',As='Ashlu:BAEALAAECgYIEQABLAAFFAIIBgABAMIMAA==.',Be='Benqtidracy:BAEALAAECgEIAQABLAAECggIGAAEAP8PAA==.Berryzona:BAEALAADCggICAABLAAECgYICgAFAAAAAA==.',Ch='Charlydk:BAECLAAFFIEOAAIGAAUI5BAUAQC3AQU5DAAABABRADsMAAAEACsAOgwAAAMAKgA8DAAAAgAoAD0MAAABAAgABgAFCOQQFAEAtwEFOQwAAAQAUQA7DAAABAArADoMAAADACoAPAwAAAIAKAA9DAAAAQAIACwABAqBHAACBgAICBUbJA4AYAIABgAICBUbJA4AYAIAASwABRQGCB4ABwDVIAA=.Chîeld:BAECLAAFFIEPAAMIAAQIbyKVCQBMAQQ5DAAABQBjADsMAAAEAF0AOgwAAAQAYQA8DAAAAgA+AAgAAwi9JZUJAEwBAzkMAAAFAGMAOwwAAAMAXQA6DAAABABhAAkAAgjCFIUiAE8AAjsMAAABADkAPAwAAAIAMAAsAAQKgTUABAgACAhwJrYAAIIDAAgACAhRJrYAAIIDAAkABwjPI6IQANwCAAoABwgqIqQDAJcCAAAA.',Cr='Crabkey:BAEALAADCggIDwABLAAECggIIwALAN0bAA==.',Cy='Cyndija:BAEALAAFFAIIAgABLAAFFAUIDwAGAJIXAA==.Cyndira:BAEBLAAECoEdAAIMAAcIrx2aEQBlAgc5DAAABQBgADsMAAAFAFsAOgwAAAUASwA8DAAABABhADIMAAAFAFUAPQwAAAQAVQA+DAAAAQAAAAwABwivHZoRAGUCBzkMAAAFAGAAOwwAAAUAWwA6DAAABQBLADwMAAAEAGEAMgwAAAUAVQA9DAAABABVAD4MAAABAAAAASwABRQFCA8ABgCSFwA=.Cyndrag:BAEALAADCgIIAgABLAAFFAUIDwAGAJIXAA==.Cyndraka:BAEALAADCgYIBgABLAAFFAUIDwAGAJIXAA==.',['Cé']='Célìne:BAEALAADCggICAABLAAFFAIIBQADACghAA==.',Da='Dakarria:BAECLAAFFIEGAAINAAIIbhxjCAC1AAI5DAAAAwBRADoMAAADAD8ADQACCG4cYwgAtQACOQwAAAMAUQA6DAAAAwA/ACwABAqBLwACDQAICOwkSQIASwMADQAICOwkSQIASwMAAAA=.',De='Deathmôl:BAEALAAECggIDgABLAAFFAQIDwAIAG8iAA==.Destinybrew:BAECLAAFFIENAAIOAAUIvxVDBACgAQU5DAAABABSADsMAAADAD4AOgwAAAQARwA8DAAAAQApAD0MAAABABQADgAFCL8VQwQAoAEFOQwAAAQAUgA7DAAAAwA+ADoMAAAEAEcAPAwAAAEAKQA9DAAAAQAUACwABAqBLQACDgAICI8jZgMANgMADgAICI8jZgMANgMAASwABRQGCB0ADwAFJQA=.Destinygrip:BAECLAAFFIEdAAIPAAYIBSVSAACcAgY5DAAABwBiADsMAAAGAGIAOgwAAAYAYwA8DAAABABbADIMAAACAF4APQwAAAQAVgAPAAYIBSVSAACcAgY5DAAABwBiADsMAAAGAGIAOgwAAAYAYwA8DAAABABbADIMAAACAF4APQwAAAQAVgAsAAQKgR4AAg8ACAhsJnYAAIwDAA8ACAhsJnYAAIwDAAAA.Destinymage:BAEALAADCggICAABLAAFFAYIHQAPAAUlAA==.Destinypal:BAEALAAFFAIIAgABLAAFFAYIHQAPAAUlAA==.Destinysham:BAEALAAFFAIIBAABLAAFFAYIHQAPAAUlAA==.Destinyw:BAEALAAECggICAABLAAFFAYIHQAPAAUlAA==.',Dr='Drakelo:BAECLAAFFIEPAAIQAAUIjByXBADGAQU5DAAABQBcADsMAAADAEIAOgwAAAUAVAA8DAAAAQAgAD0MAAABAFkAEAAFCIwclwQAxgEFOQwAAAUAXAA7DAAAAwBCADoMAAAFAFQAPAwAAAEAIAA9DAAAAQBZACwABAqBLwADEAAICPUk0AIAWgMAEAAICPUk0AIAWgMAEQACCNsh2BEAtwAAAAA=.',El='Ellýclutch:BAEALAAECgIIAgABLAAFFAIIBQADACghAA==.',Em='Emíly:BAEALAAECgYIDAABLAAFFAIIBQADACghAA==.',Ev='Eviefrye:BAEALAAECgUIBQABLAAFFAUIFAAHAAcgAA==.Evyior:BAEBLAAECoEdAAIQAAgIMyH2CAD/Agg5DAAABABaADsMAAAEAF8AOgwAAAQAVgA8DAAABABYADIMAAAEAFAAPQwAAAQAYgA+DAAAAwBEAD8MAAACAEcAEAAICDMh9ggA/wIIOQwAAAQAWgA7DAAABABfADoMAAAEAFYAPAwAAAQAWAAyDAAABABQAD0MAAAEAGIAPgwAAAMARAA/DAAAAgBHAAEsAAUUAwgKABIAHxcA.',Ga='Gabb:BAECLAAFFIEWAAIBAAYI+BfgAgDoAQY5DAAABQBbADsMAAAEAEAAOgwAAAYAVwA8DAAAAwBCADIMAAABAA0APQwAAAMALQABAAYI+BfgAgDoAQY5DAAABQBbADsMAAAEAEAAOgwAAAYAVwA8DAAAAwBCADIMAAABAA0APQwAAAMALQAsAAQKgSwAAgEACAiJJF4EADgDAAEACAiJJF4EADgDAAAA.Gabbaladin:BAEALAAECggIEwABLAAFFAYIFgABAPgXAA==.',Gr='Grimrex:BAEBLAAECoEUAAITAAcIuRtoTwDTAQc5DAAABABSADsMAAAGAFgAOgwAAAMANwA8DAAAAgBAADIMAAACAEQAPQwAAAIAVwA+DAAAAQAxABMABwi5G2hPANMBBzkMAAAEAFIAOwwAAAYAWAA6DAAAAwA3ADwMAAACAEAAMgwAAAIARAA9DAAAAgBXAD4MAAABADEAASwABAoICCMACwDdGwA=.',Gu='Gubbu:BAEALAADCggIDwABLAAFFAYIFgABAPgXAA==.',Ha='Hawktuar:BAEALAAECggIDgABLAAFFAMICgASAB8XAA==.',Ho='Hooloofoo:BAEBLAAECoEvAAIUAAgIbiAlHADqAgg5DAAABgBhADsMAAAHAFMAOgwAAAcAWgA8DAAABgA6ADIMAAAGAFEAPQwAAAYAYAA+DAAABQBTAD8MAAAEAEgAFAAICG4gJRwA6gIIOQwAAAYAYQA7DAAABwBTADoMAAAHAFoAPAwAAAYAOgAyDAAABgBRAD0MAAAGAGAAPgwAAAUAUwA/DAAABABIAAAA.',Ik='Ikonokarr:BAEALAAECgcIDAABLAAFFAQIDgAOALccAA==.Ikonôkarr:BAECLAAFFIEOAAIOAAQItxwrBQBxAQQ5DAAABQBbADsMAAADAEkAOgwAAAUAVwA8DAAAAQApAA4ABAi3HCsFAHEBBDkMAAAFAFsAOwwAAAMASQA6DAAABQBXADwMAAABACkALAAECoE0AAIOAAgIySQoAgBVAwAOAAgIySQoAgBVAwAAAA==.',Ka='Kaeltre:BAEALAADCgQIBAABLAAFFAMIDAAPAAgbAA==.Kaeltrix:BAECLAAFFIEMAAIPAAMICBsuBgDuAAM5DAAABQBBADsMAAADADsAOgwAAAQAUwAPAAMICBsuBgDuAAM5DAAABQBBADsMAAADADsAOgwAAAQAUwAsAAQKgTcAAg8ACAgmJE0FAAUDAA8ACAgmJE0FAAUDAAAA.Kazbrekker:BAECLAAFFIEeAAMHAAYI1SD2AABfAgY5DAAABgBgADsMAAAGAFoAOgwAAAYASAA8DAAABQBaADIMAAADAFAAPQwAAAQASwAHAAYI1SD2AABfAgY5DAAAAwBgADsMAAADAFoAOgwAAAIASAA8DAAAAwBaADIMAAADAFAAPQwAAAMASwAVAAUIcxa6AACzAQU5DAAAAwBYADsMAAADAFQAOgwAAAQANgA8DAAAAgA6AD0MAAABAAAALAAECoErAAMVAAgIfiNZAgDuAgAVAAgInCJZAgDuAgAHAAcIDCJ6CACeAgAAAA==.',Ke='Kealdk:BAEALAADCgYIBgABLAAFFAMIDAAPAAgbAA==.Kealmonk:BAEALAAECgYIDAABLAAFFAMIDAAPAAgbAA==.',Ko='Koenari:BAEALAADCggIDAABLAAECgYIGQAKANEgAA==.Koezoey:BAEBLAAECoEZAAIKAAYI0SBTBgA3AgY5DAAABQBeADsMAAADAFEAOgwAAAQAUgA8DAAAAwBSADIMAAAFAEoAPQwAAAUAWAAKAAYI0SBTBgA3AgY5DAAABQBeADsMAAADAFEAOgwAAAQAUgA8DAAAAwBSADIMAAAFAEoAPQwAAAUAWAAAAA==.',Kr='Krebvoker:BAECLAAFFIEXAAIWAAYIDhg2AgAAAgY5DAAABQBFADsMAAADADYAOgwAAAYATAA8DAAABAA/ADIMAAABACwAPQwAAAQAPQAWAAYIDhg2AgAAAgY5DAAABQBFADsMAAADADYAOgwAAAYATAA8DAAABAA/ADIMAAABACwAPQwAAAQAPQAsAAQKgSwABBYACAhXG5EIAIsCABYACAhXG5EIAIsCABAACAhHF/kbACgCABEACAiNDiIJALsBAAAA.Kruemelkotze:BAEALAAECgMIAwABLAAFFAYIFgABAPgXAA==.Kréb:BAEALAADCggICAABLAAFFAYIFwAWAA4YAA==.',La='Latî:BAECLAAFFIEPAAMGAAUIkhcyAgBZAQU5DAAABABMADsMAAACAE0AOgwAAAUANAA8DAAAAgAtAD0MAAACADEABgAFCJIXMgIAWQEFOQwAAAIATAA7DAAAAgBNADoMAAACADQAPAwAAAIALQA9DAAAAQAxAA8AAwiSCuwHAL4AAzkMAAACACEAOgwAAAMAJQA9DAAAAQAKACwABAqBIgADBgAICJ4k8wIAMwMABgAICJ4k8wIAMwMADwACCP8VwzQAgAAAAAA=.',Lo='Lokomotive:BAEALAAECggIDQABLAAFFAMIDAAPAAgbAA==.',Ly='Lyior:BAECLAAFFIEKAAISAAMIHxe3EgD8AAM5DAAABQBMADsMAAABAB4AOgwAAAQARgASAAMIHxe3EgD8AAM5DAAABQBMADsMAAABAB4AOgwAAAQARgAsAAQKgSMAAhIACAhKJKkIAE4DABIACAhKJKkIAE4DAAAA.',Ma='Makelo:BAEBLAAECoEeAAMDAAgIYRckNQBcAgg5DAAABABUADsMAAAEAE0AOgwAAAQAMQA8DAAABAAlADIMAAAFADcAPQwAAAQAQwA+DAAABABVAD8MAAABABYAAwAICGEXJDUAXAIIOQwAAAQAVAA7DAAABABNADoMAAADADEAPAwAAAMAJQAyDAAABAA3AD0MAAAEAEMAPgwAAAQAVQA/DAAAAQAWABcAAwijBbgUAH4AAzoMAAABAA8APAwAAAEAEQAyDAAAAQAJAAEsAAUUBQgPABAAjBwA.',Me='Merânov:BAEALAAECggICAAAAA==.',My='Myrianne:BAEALAAECgQIBAABLAAECgYIGQAKANEgAA==.',Ni='Nippøn:BAEALAAECgYIDAABLAAECggIIwALAN0bAA==.',Pa='Palatiinee:BAEALAAECgUIAwAAAA==.',Pe='Persês:BAECLAAFFIEVAAIYAAYITh9GAgBfAgY5DAAABgBcADsMAAAEAGIAOgwAAAQAYgA8DAAAAwBDADIMAAABADsAPQwAAAMAPgAYAAYITh9GAgBfAgY5DAAABgBcADsMAAAEAGIAOgwAAAQAYgA8DAAAAwBDADIMAAABADsAPQwAAAMAPgAsAAQKgSYAAhgACAg0JRQNADIDABgACAg0JRQNADIDAAAA.',Qi='Qinzey:BAECLAAFFIETAAIJAAUIFxdwBgC1AQU5DAAABABPADsMAAAFADcAOgwAAAYAXAA8DAAAAwAyAD0MAAABABEACQAFCBcXcAYAtQEFOQwAAAQATwA7DAAABQA3ADoMAAAGAFwAPAwAAAMAMgA9DAAAAQARACwABAqBLQACCQAICMAj/AYAOgMACQAICMAj/AYAOgMAAAA=.Qinzeyhunts:BAEALAAECggICAABLAAFFAUIEwAJABcXAA==.Qinzeysham:BAEALAAECggIEAABLAAFFAUIEwAJABcXAA==.',Qt='Qtpriest:BAECLAAFFIELAAIIAAMIbA6tEgDeAAM5DAAABQAvADsMAAACAAgAOgwAAAQANgAIAAMIbA6tEgDeAAM5DAAABQAvADsMAAACAAgAOgwAAAQANgAsAAQKgSUAAggACAivHJEcAHcCAAgACAivHJEcAHcCAAAA.',Qu='Quijaha:BAECLAAFFIEgAAIIAAcIzCMMAAANAwc5DAAABgBkADsMAAAFAGMAOgwAAAYAYwA8DAAABQBcADIMAAAEAGEAPQwAAAQAYwA+DAAAAgA1AAgABwjMIwwAAA0DBzkMAAAGAGQAOwwAAAUAYwA6DAAABgBjADwMAAAFAFwAMgwAAAQAYQA9DAAABABjAD4MAAACADUALAAECoEoAAIIAAgIqSapAACDAwAIAAgIqSapAACDAwAAAA==.',Ri='Ricardowl:BAEBLAAECoEgAAMEAAgI1yXPBABmAwg5DAAABABhADsMAAAEAGMAOgwAAAQAXgA8DAAABABiADIMAAAEAGEAPQwAAAQAXwA+DAAABABgAD8MAAAEAF4ABAAICHslzwQAZgMIOQwAAAEAWwA7DAAAAgBiADoMAAACAF4APAwAAAIAYgAyDAAABABhAD0MAAACAF8APgwAAAMAYAA/DAAABABeAA0ABghtJYkNAIMCBjkMAAADAGEAOwwAAAIAYwA6DAAAAgBcADwMAAACAFwAPQwAAAIAXwA+DAAAAQBgAAEsAAUUBggfAAQAUyYA.Ricardowltwo:BAEBLAAECoEgAAMEAAgILCYLAgCCAwg5DAAABABhADsMAAAEAGMAOgwAAAQAYQA8DAAABABgADIMAAAEAGIAPQwAAAQAYQA+DAAABABiAD8MAAAEAF8ABAAICBAmCwIAggMIOQwAAAIAYQA7DAAAAgBiADoMAAACAGEAPAwAAAIAXwAyDAAABABiAD0MAAACAGEAPgwAAAIAYgA/DAAABABfAA0ABgguJXAOAHoCBjkMAAACAGEAOwwAAAIAYwA6DAAAAgBbADwMAAACAGAAPQwAAAIAXgA+DAAAAgBbAAEsAAUUBggfAAQAUyYA.Richardwl:BAEALAAECggIDwABLAAFFAYIHwAEAFMmAA==.',Sh='Shalyná:BAEBLAAECoEpAAIZAAgIOSX4AQBtAwg5DAAABgBiADsMAAAGAGAAOgwAAAYAYgA8DAAABgBWADIMAAAGAGEAPQwAAAUAXgA+DAAABABdAD8MAAACAGAAGQAICDkl+AEAbQMIOQwAAAYAYgA7DAAABgBgADoMAAAGAGIAPAwAAAYAVgAyDAAABgBhAD0MAAAFAF4APgwAAAQAXQA/DAAAAgBgAAAA.',So='Sourcefour:BAEALAAECggIEAABLAAFFAYIHwAEAFMmAA==.Sourcemagic:BAEALAAECggIEAABLAAFFAYIHwAEAFMmAA==.Sourcemâgic:BAEALAADCggIDQABLAAFFAYIHwAEAFMmAA==.Sourcethree:BAECLAAFFIEfAAMEAAYIUyZDAQCpAgY5DAAABwBjADsMAAAGAGMAOgwAAAcAYQA8DAAABABhADIMAAADAGEAPQwAAAQAYQAEAAYIUyZDAQCpAgY5DAAAAwBjADsMAAAGAGMAOgwAAAQAYQA8DAAABABhADIMAAADAGEAPQwAAAQAYQANAAIIFCVKBQDJAAI5DAAABABhADoMAAADAFsALAAECoEvAAQNAAgI/SZ9AACGAwAEAAgI2CbcAACTAwANAAgIwSZ9AACGAwAaAAIIQB+mIwCvAAAAAA==.Sourcetwo:BAEBLAAECoEgAAMEAAgIXCV4BgBXAwg5DAAABABjADsMAAAEAGMAOgwAAAQAYgA8DAAABABhADIMAAAEAGEAPQwAAAQAWwA+DAAABABXAD8MAAAEAF4ABAAICJYkeAYAVwMIOQwAAAIAXwA7DAAAAgBfADoMAAADAGIAPAwAAAMAXAAyDAAABABhAD0MAAADAFkAPgwAAAMAVwA/DAAABABeAA0ABgidJF8QAGQCBjkMAAACAGMAOwwAAAIAYwA6DAAAAQBeADwMAAABAGEAPQwAAAEAWwA+DAAAAQBPAAEsAAUUBggfAAQAUyYA.',Ta='Tariim:BAEALAAECgcIEwABLAAFFAcIEgAFAAAAAQ==.Tariimblue:BAEALAAFFAcIEgAAAQ==.Tariimdk:BAEALAAECgYIDAABLAAFFAcIEgAFAAAAAQ==.Tariimdruid:BAEALAADCggICAABLAAFFAcIEgAFAAAAAQ==.',Te='Temz:BAEBLAAECoEfAAMGAAcI0iM0DAB+Agc5DAAABgBfADsMAAAGAF8AOgwAAAUAXgA8DAAABABjADIMAAAEAGIAPQwAAAQAVwA+DAAAAgBHAAYABwjSIzQMAH4CBzkMAAAGAF8AOwwAAAYAXwA6DAAABABeADwMAAADAGMAMgwAAAQAYgA9DAAABABXAD4MAAACAEcAGAACCD8KYEIBVgACOgwAAAEAJQA8DAAAAQAOAAAA.',Tr='Trampel:BAEALAAECggICAABLAAFFAMICgASAB8XAA==.Trikkizwar:BAEALAAECgYIBgAAAA==.',Ts='Tsajan:BAEALAAECggIBgAAAA==.Tsajandh:BAEALAAECggIDgABLAAECggIBgAFAAAAAA==.Tsajandruid:BAEALAAECggICAABLAAECggIBgAFAAAAAA==.Tsajanhunter:BAEALAAECggIDAABLAAECggIBgAFAAAAAA==.Tsajanpriest:BAEALAAECggIDQABLAAECggIBgAFAAAAAA==.Tsajans:BAEALAAECggICAABLAAECggIBgAFAAAAAA==.Tsajanw:BAEBLAAECoElAAQaAAgIABm3BQBrAgg5DAAABQBWADsMAAAFAFkAOgwAAAQAPQA8DAAABQAqADIMAAAFAEEAPQwAAAQAUAA+DAAABQA8AD8MAAAEABgAGgAICAAZtwUAawIIOQwAAAIAVgA7DAAAAgBZADoMAAACAD0APAwAAAIAKgAyDAAAAgBBAD0MAAABAFAAPgwAAAIAPAA/DAAAAQAYAA0ABAgmEW9RAAUBBDkMAAABAEEAOwwAAAEANwA8DAAAAQAZAD0MAAABABwABAAICDEM5Z8A9gAIOQwAAAIAOgA7DAAAAgAzADoMAAACAAkAPAwAAAIAFQAyDAAAAwAZAD0MAAACABkAPgwAAAMAJQA/DAAAAwAUAAEsAAQKCAgGAAUAAAAA.Tsajanwa:BAEALAAECggICAABLAAECggIBgAFAAAAAA==.Tsurî:BAECLAAFFIEOAAISAAUI5RXuCAC+AQU5DAAABABUADsMAAADADcAOgwAAAMAYQA8DAAAAgAQAD0MAAACABoAEgAFCOUV7ggAvgEFOQwAAAQAVAA7DAAAAwA3ADoMAAADAGEAPAwAAAIAEAA9DAAAAgAaACwABAqBGAACEgAICEckkA0AMAMAEgAICEckkA0AMAMAAAA=.Tsurîî:BAEALAAECgYIDgABLAAFFAUIDgASAOUVAA==.',Va='Vanhìnten:BAEBLAAECoEWAAIbAAcI+Rj8NQANAgc5DAAABAA7ADsMAAAEADgAOgwAAAQAUwA8DAAAAwBSADIMAAADAEAAPQwAAAMAKwA+DAAAAQA5ABsABwj5GPw1AA0CBzkMAAAEADsAOwwAAAQAOAA6DAAABABTADwMAAADAFIAMgwAAAMAQAA9DAAAAwArAD4MAAABADkAAAA=.',Wo='Wolfsblùt:BAEBLAAECoEjAAILAAgI3RtENgBKAgg5DAAABgBRADsMAAAFAFEAOgwAAAUATwA8DAAABQBAADIMAAAFAEkAPQwAAAYATQA+DAAAAgA6AD8MAAABADYACwAICN0bRDYASgIIOQwAAAYAUQA7DAAABQBRADoMAAAFAE8APAwAAAUAQAAyDAAABQBJAD0MAAAGAE0APgwAAAIAOgA/DAAAAQA2AAAA.',Xi='Xinuhdk:BAEALAAECggIBgABLAAFFAUIEgATAGcXAA==.Xinuhwar:BAECLAAFFIESAAITAAUIZxe0BwDKAQU5DAAABABRADsMAAAFADMAOgwAAAYAXAA8DAAAAgAiAD0MAAABACgAEwAFCGcXtAcAygEFOQwAAAQAUQA7DAAABQAzADoMAAAGAFwAPAwAAAIAIgA9DAAAAQAoACwABAqBNwACEwAICB0lSgUAYgMAEwAICB0lSgUAYgMAAAA=.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end