local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Shaman-Restoration','Priest-Holy','Priest-Discipline','Warlock-Affliction','Druid-Restoration','Druid-Feral','Druid-Balance','Unknown-Unknown','Priest-Shadow','Evoker-Devastation','Evoker-Augmentation','DemonHunter-Havoc','Rogue-Assassination','DeathKnight-Blood','Paladin-Retribution','Monk-Windwalker','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Elemental','DeathKnight-Unholy','Warrior-Fury','Druid-Guardian','Warrior-Arms','Mage-Frost','Warlock-Destruction','Rogue-Subtlety','Paladin-Protection','Shaman-Enhancement','Warlock-Demonology','DemonHunter-Vengeance','Warrior-Protection','Monk-Mistweaver','Hunter-Survival','Paladin-Holy','DeathKnight-Frost','Monk-Brewmaster','Mage-Arcane',}; local provider = {region='EU',realm='Cho’gall',name='EU',type='weekly',zone=44,date='2025-09-23',data={Ad='Adoz:BAAALAADCggICAAAAA==.Adrishaman:BAACLAAFFIEKAAIBAAMIBRWODgDpAAABAAMIBRWODgDpAAAsAAQKgRgAAgEABwhtIWEYAJoCAAEABwhtIWEYAJoCAAAA.',Af='Affulgens:BAAALAADCggICAAAAA==.',Ag='Aggralan:BAAALAADCggIDwAAAA==.',Ai='Airelem:BAAALAAECgYIBgAAAA==.Aiyanna:BAABLAAECoEYAAIBAAcIwQhMpgDxAAABAAcIwQhMpgDxAAAAAA==.',Ak='Akame:BAABLAAECoEUAAMCAAgImgoPTwBzAQACAAgImgoPTwBzAQADAAUIKgSDIQCaAAAAAA==.Akonit:BAAALAADCgcIBwAAAA==.Akîra:BAAALAADCggIEAAAAA==.',Al='Alexa:BAAALAADCggICAAAAA==.Alliyah:BAACLAAFFIEHAAIEAAMI2xjoAAASAQAEAAMI2xjoAAASAQAsAAQKgSgAAgQACAg1Ji0AAI4DAAQACAg1Ji0AAI4DAAAA.Aløa:BAABLAAECoEcAAQFAAgI8A+pXAA6AQAFAAYIvRGpXAA6AQAGAAMI4RS7LQDUAAAHAAYIuwaFawCzAAAAAA==.Alû:BAAALAAECgcIEgABLAAECggICAAIAAAAAA==.',Am='Ama:BAAALAADCgIIAgAAAA==.Amalgham:BAABLAAECoEeAAMJAAgIFRrxGwBxAgAJAAgIFRrxGwBxAgACAAEIhwGFrAASAAAAAA==.Amandinã:BAAALAADCggICAAAAA==.Amoxapir:BAAALAADCgMIBAAAAA==.',An='Andaeriel:BAACLAAFFIEHAAICAAMI8QpKFADKAAACAAMI8QpKFADKAAAsAAQKgR4AAwIACAj4FIwtAAsCAAIACAj4FIwtAAsCAAkABQhGCWljAOoAAAAA.Andrõmède:BAAALAAECgYIBwAAAA==.Angahrän:BAAALAADCgQIBAAAAA==.Angëleyes:BAAALAAECgYICwAAAA==.Anlya:BAABLAAECoEfAAMKAAgICiErCgDrAgAKAAgICiErCgDrAgALAAEIwRo+FABTAAAAAA==.Ansteal:BAAALAAECgcICAAAAA==.Anthop:BAAALAADCgQIBAAAAA==.Antòn:BAABLAAECoEZAAIMAAYIwBv7WADrAQAMAAYIwBv7WADrAQABLAAECggIHAANAFgaAA==.Anîs:BAAALAADCggICAAAAA==.',Ap='Apia:BAAALAADCggIBgAAAA==.Apollòn:BAAALAADCggICgAAAA==.',Aq='Aquïlinîus:BAAALAAECggIDAAAAA==.',Ar='Arhès:BAABLAAECoEfAAIOAAgITBfXDwAYAgAOAAgITBfXDwAYAgAAAA==.',As='Asakurâ:BAAALAADCgcIBwAAAA==.Ascendance:BAAALAAECgcIEwAAAA==.Asgath:BAAALAADCgEIAQAAAA==.Asmodélia:BAAALAADCggIEAAAAA==.Aspirine:BAACLAAFFIEGAAIJAAIIUh7jEgClAAAJAAIIUh7jEgClAAAsAAQKgRoAAgkACAgIIGAPAOMCAAkACAgIIGAPAOMCAAEsAAUUAggGAA8AxCUA.Astrønef:BAAALAAECgYIDAAAAA==.',At='Atalânte:BAAALAADCgcIBwAAAA==.Atnas:BAAALAADCggIDQAAAA==.Atøme:BAABLAAECoEbAAIPAAcINBtdSwAtAgAPAAcINBtdSwAtAgAAAA==.',Au='Augustik:BAAALAADCggIDwAAAA==.',Az='Azahell:BAAALAADCgYIBgAAAA==.Azakeal:BAAALAADCggICQAAAA==.Azaraks:BAAALAADCgQIBgAAAA==.Azastoch:BAAALAADCggIDAAAAA==.Azendra:BAAALAAECggIAQAAAA==.Azhall:BAABLAAECoEVAAIQAAYI2SEqFABHAgAQAAYI2SEqFABHAgAAAA==.Azkis:BAAALAAECgYIEAAAAA==.Azorhan:BAAALAADCgYIBgAAAA==.',['Aì']='Aìfé:BAAALAADCggIEgAAAA==.',Ba='Bab:BAAALAAECgYICgAAAA==.Babaganoush:BAAALAADCgIIAgAAAA==.Babouliao:BAAALAAECgYIBgAAAA==.Bakhaw:BAAALAADCgQIBgAAAA==.Balisto:BAAALAAECgIIAgAAAA==.Banwav:BAAALAAFFAIIAgAAAA==.Barabell:BAABLAAECoEdAAIQAAgIWyCvCgDMAgAQAAgIWyCvCgDMAgAAAA==.Baratiddy:BAAALAAECgMIBgAAAA==.',Be='Beerawecka:BAAALAAECgYIBgAAAA==.Belenos:BAAALAADCgcICwAAAA==.Berta:BAAALAADCgcIBwAAAA==.Beurkk:BAAALAAECgcIDgAAAA==.Beurkkmonk:BAAALAAECgIIAgAAAA==.',Bi='Bibilol:BAAALAADCggIEQAAAA==.Bigornôt:BAAALAADCggICAAAAA==.',Bl='Blyoux:BAAALAADCgUIBgAAAA==.',Bo='Bochek:BAAALAAECgQIBAABLAAFFAIIBgAHAHYTAA==.',Br='Brawlslayer:BAAALAADCgIIAgAAAA==.',Bs='Bsb:BAAALAADCgUIBQAAAA==.',Bu='Bulkilol:BAAALAAECgEIAQAAAA==.Bussa:BAAALAAECgYIDAAAAA==.',Bv='Bvlgary:BAAALAAECgIIAgAAAA==.',Ca='Cadvingtetun:BAABLAAECoEdAAIRAAcIkw8+fQB8AQARAAcIkw8+fQB8AQAAAA==.Calebv:BAACLAAFFIEHAAISAAMIRBmNCgAAAQASAAMIRBmNCgAAAQAsAAQKgSAAAhIABwgLJF0PANoCABIABwgLJF0PANoCAAAA.Calfouette:BAAALAAECgYIEAAAAA==.Cambreezex:BAAALAADCgcICwAAAA==.Catniss:BAAALAAECgcIBwAAAA==.Cazomir:BAAALAADCgYIBgAAAA==.',Ce='Cecibrr:BAAALAAECgcIDQAAAA==.Cecirae:BAABLAAECoEWAAICAAcIeQ1yUABuAQACAAcIeQ1yUABuAQAAAA==.Cerwyn:BAABLAAECoEfAAIJAAgIYRz/FQCjAgAJAAgIYRz/FQCjAgAAAA==.Cetirizine:BAAALAADCgUIBQAAAA==.',Ch='Chamynoob:BAABLAAECoEYAAMBAAgIRhDfYACSAQABAAgIRhDfYACSAQATAAMIbAXLkACOAAAAAA==.Charløu:BAAALAADCggIDwAAAA==.Chaseros:BAAALAADCgcIBwAAAA==.Chastartex:BAAALAAECgYIBAAAAA==.Cheepyx:BAAALAAECgMIAwAAAA==.Chimérique:BAAALAADCggICQABLAAECggIIwAKANchAA==.Chonch:BAAALAAECgMIAwAAAA==.Chovito:BAAALAADCgcIBwAAAA==.Chrisouh:BAAALAADCgUIBQABLAAECgYIEQAIAAAAAA==.Chrisseuh:BAAALAAECgYIEQAAAA==.Chrris:BAAALAADCggIDAABLAAECgYIEQAIAAAAAA==.Chubo:BAAALAADCggICAAAAA==.Chuy:BAAALAAFFAIIBAAAAA==.',Ci='Cilia:BAAALAADCgUIBQAAAA==.Cindêr:BAABLAAECoEaAAIBAAgIghLmUwC1AQABAAgIghLmUwC1AQAAAA==.Circë:BAAALAAECggIDwAAAA==.Citrohhnelle:BAABLAAECoEdAAIJAAcIahm1JwAbAgAJAAcIahm1JwAbAgAAAA==.',Cl='Classcheater:BAAALAADCgUIBQAAAA==.',Cm='Cmbrzx:BAAALAAECgMIAwAAAA==.Cmbrzzx:BAAALAAECgMIAwAAAA==.',Co='Corliss:BAABLAAECoEZAAIPAAcIjx6iRgA6AgAPAAcIjx6iRgA6AgAAAA==.',Cp='Cpamöa:BAAALAAECgMIBAAAAA==.',Cr='Crakou:BAAALAAECgYIEwAAAA==.',Cy='Cyrène:BAAALAADCggICAAAAA==.',['Cé']='Célïa:BAAALAADCgcIBwABLAAFFAMICQAUALQUAA==.',['Cø']='Cøøkïe:BAABLAAECoEeAAIVAAgIERI9QAD8AQAVAAgIERI9QAD8AQAAAA==.',Da='Daddyrexgodx:BAAALAAECggIEwAAAA==.Daphaladriel:BAAALAAECgUICQAAAA==.Daphnisse:BAAALAAECgIIBQAAAA==.Darkfayette:BAAALAADCggIDwABLAAECggIFQAWAHgfAA==.Darkflitch:BAAALAAECgYIDAAAAA==.Darksmarties:BAAALAAECgcIDwAAAA==.Darkvika:BAAALAAECgYIDAAAAA==.Darween:BAAALAADCgQIBAAAAA==.',Dd='Ddoshs:BAAALAAECggIAgAAAA==.',De='Deathsmarty:BAAALAAECggIDQAAAA==.Deathwiing:BAAALAADCgcIBwAAAA==.Deceiver:BAACLAAFFIEFAAIDAAMITwz7AADNAAADAAMITwz7AADNAAAsAAQKgR4AAgMACAirHzYCANUCAAMACAirHzYCANUCAAAA.Demaciaa:BAAALAAECgMICQAAAA==.Demona:BAAALAADCgQIBAAAAA==.Demotria:BAAALAADCgUIBgAAAA==.Demøniä:BAAALAADCgYIBgAAAA==.Denethan:BAACLAAFFIEGAAIPAAIIoRlnIACrAAAPAAIIoRlnIACrAAAsAAQKgRgAAg8ACAgbHyggAM8CAA8ACAgbHyggAM8CAAAA.Derrierevous:BAAALAAECggIDAAAAA==.',Di='Dingqt:BAACLAAFFIERAAIJAAUITxhFBQDFAQAJAAUITxhFBQDFAQAsAAQKgS8AAgkACAhZJUQEAFcDAAkACAhZJUQEAFcDAAAA.Diplodocus:BAABLAAECoEUAAITAAYITxK/VwB8AQATAAYITxK/VwB8AQAAAA==.',Dj='Djowcow:BAABLAAECoEgAAIBAAcIyBRzWQCmAQABAAcIyBRzWQCmAQAAAA==.Djð:BAAALAADCgYIBgAAAA==.Djðthyr:BAAALAAECgYIDQAAAA==.',Dk='Dkleria:BAAALAAECgIIAwAAAA==.Dkpitj:BAAALAADCggICAAAAA==.Dkrag:BAAALAAECgUICQAAAA==.',Dm='Dmo:BAAALAADCgcICQAAAA==.Dmöne:BAAALAADCggIHAAAAA==.',Do='Doduh:BAAALAAECgQIBgAAAA==.Doshaburiten:BAAALAAECgQIBgAAAA==.',Dr='Draconnare:BAAALAAECgMIAwAAAA==.Draculus:BAAALAADCggIDgAAAA==.Dradine:BAABLAAECoEcAAIHAAYIexgfOgCaAQAHAAYIexgfOgCaAQAAAA==.Drakhtar:BAAALAAECgYIBgAAAA==.Drfayett:BAAALAAECgMIBAABLAAECggIFQAWAHgfAA==.Drfayette:BAABLAAECoEVAAMWAAgIeB9pBACzAgAWAAcI2SFpBACzAgAGAAcIfhSBFQDZAQAAAA==.Drhighy:BAAALAADCgcIBwAAAA==.Drizztt:BAAALAAECgYIEQAAAA==.Drooks:BAAALAAECggIDwAAAA==.Druidesse:BAAALAADCgcIDAAAAA==.Druidotem:BAABLAAECoEUAAITAAcIOxAqSAC0AQATAAcIOxAqSAC0AQAAAA==.Drääkk:BAAALAADCgcIBwAAAA==.Drøøks:BAAALAAECgcIEwAAAA==.',Dw='Dwartz:BAABLAAECoEXAAMXAAYIVhzJCwD7AQAXAAYIVhzJCwD7AQAVAAEIqgdZ0QAsAAAAAA==.',['Dé']='Désespoir:BAABLAAECoEXAAICAAYIPRjvQQCoAQACAAYIPRjvQQCoAQAAAA==.',['Dï']='Dïxdeux:BAAALAAFFAIIBAAAAA==.',['Dü']='Dürotan:BAAALAADCgQIBAAAAA==.',Eb='Ebrial:BAAALAADCggIEwAAAA==.',Ec='Echtelyon:BAAALAAECgYIDwABLAAECgYIFwACAD0YAA==.Eclairage:BAACLAAFFIEFAAIBAAIIRh01HACtAAABAAIIRh01HACtAAAsAAQKgRwAAgEACAgmG4kiAGUCAAEACAgmG4kiAGUCAAAA.',Ed='Edôtensei:BAABLAAECoEcAAIYAAgIYRBsIwDcAQAYAAgIYRBsIwDcAQAAAA==.',Ef='Efeiremm:BAABLAAECoEfAAIMAAcIPRtlTgAIAgAMAAcIPRtlTgAIAgAAAA==.',Ek='Ekï:BAAALAADCgcIBwABLAADCggIBQAIAAAAAA==.',El='Elethael:BAAALAAECgYIBwAAAA==.Elfagstorm:BAAALAADCgYICAAAAA==.Elfiine:BAAALAADCggIEwAAAA==.Elicanna:BAAALAADCgcIBwAAAA==.Ellyshã:BAABLAAECoEUAAICAAYI9hnGPQC6AQACAAYI9hnGPQC6AQAAAA==.Elrandrir:BAACLAAFFIEGAAIPAAIIxCU/EQDkAAAPAAIIxCU/EQDkAAAsAAQKgScAAg8ACAgaJvMDAHUDAA8ACAgaJvMDAHUDAAAA.Elunara:BAABLAAECoEgAAIZAAgIphguLgBXAgAZAAgIphguLgBXAgAAAA==.',En='Enaliia:BAAALAADCgIIAgAAAA==.Enallya:BAAALAADCggICAAAAA==.Encoulix:BAAALAADCggICAAAAA==.Ennalya:BAAALAAFFAIIAgAAAA==.Enwik:BAAALAADCggICQAAAA==.',Eq='Equiroxx:BAAALAADCggIDgAAAA==.',Er='Eragosa:BAAALAADCgUIBAAAAA==.Erato:BAAALAADCgUIBQAAAA==.Erissa:BAAALAAECgYIDwAAAA==.',Es='Eskk:BAAALAADCgYICgAAAA==.Eskä:BAAALAADCgYICAAAAA==.',Et='Ethernamøus:BAAALAADCggICQAAAA==.Etpafelhunt:BAAALAAECgUICAAAAA==.',Eu='Eurimar:BAAALAAECgMIBAABLAAECggIGAACAHMPAA==.Eurïpïde:BAAALAAECgYIEQAAAA==.',Ev='Evíl:BAAALAADCggICAABLAAECggIIAAVANkiAA==.',Ex='Exödê:BAACLAAFFIEGAAITAAIIZR0uFQC2AAATAAIIZR0uFQC2AAAsAAQKgRgAAhMABgjKINUuACYCABMABgjKINUuACYCAAAA.',Ey='Eyeshield:BAAALAAECgYIEgAAAA==.',['Eä']='Eärendil:BAABLAAECoEcAAIRAAgI7RCwagCmAQARAAgI7RCwagCmAQAAAA==.',Fa='Faitapriére:BAAALAADCggIDwAAAA==.Fak:BAAALAAECgYIDQAAAA==.Falleris:BAAALAADCgIIAgAAAA==.Fayadrake:BAAALAAECgYICQABLAAECggIFQAWAHgfAA==.Fayett:BAAALAADCggICAABLAAECggIFQAWAHgfAA==.',Fe='Fedréa:BAAALAAECgcIDgAAAA==.Feef:BAAALAAECgEIAQAAAA==.',Fi='Finae:BAAALAAECggIDwAAAA==.',Fl='Flannelle:BAAALAAECgUIBQAAAA==.Flokinette:BAAALAADCgYICgAAAA==.Fluffy:BAAALAAECgQIBAAAAA==.Flêau:BAABLAAECoEYAAMNAAYIExnyKQC8AQANAAYIExnyKQC8AQAaAAUInRCOKQAQAQAAAA==.Flëau:BAAALAAECgMIBgAAAA==.',Fn='Fnrx:BAAALAAECgcIEQAAAA==.',Fo='Force:BAAALAADCgYIBQAAAA==.Forzeur:BAAALAAECgYIEQAAAA==.Foxydoll:BAAALAADCggIHAAAAA==.',Fr='Freija:BAAALAADCgMIAwAAAA==.Frizea:BAAALAADCggIDQAAAA==.Frm:BAAALAADCggICgAAAA==.Frolix:BAAALAADCggIFQAAAA==.Froufroune:BAAALAADCggIDgAAAA==.Fruiconfix:BAAALAADCggICAAAAA==.',Fu='Fuse:BAAALAADCggICAAAAA==.',['Fé']='Féedesbosses:BAAALAADCgcIDgAAAA==.',Ga='Gaabriel:BAAALAAECgIIAgAAAA==.Galados:BAAALAAECgMIBgAAAA==.Galbathorix:BAAALAAECggICQAAAA==.Gamesh:BAABLAAECoEYAAIOAAcIkhUiFwCrAQAOAAcIkhUiFwCrAQAAAA==.',Gi='Gildabush:BAAALAADCggIEAAAAA==.Gildarak:BAAALAADCgYIBQAAAA==.Gildarnak:BAAALAAECgYIEQAAAA==.Gildaràk:BAAALAAECgIIAgAAAA==.Gildàrak:BAABLAAECoEYAAMTAAYIuhM1UwCLAQATAAYIuhM1UwCLAQABAAYIfQwMpQDzAAAAAA==.Gilgalãd:BAABLAAECoEjAAMbAAgI0hhuFgAPAgAbAAgI0hhuFgAPAgAPAAMIgQOtJgFVAAAAAA==.Girlzy:BAABLAAECoEmAAMcAAgItRirDAD4AQAcAAcICxmrDAD4AQABAAcIKBZ3UQC8AQAAAA==.Girlzÿ:BAAALAADCgIIAgAAAA==.Gizak:BAAALAAECgYIDwABLAAFFAIIBgAdAGwcAA==.',Gl='Glawie:BAAALAAECgIIAgAAAA==.Glitchwiz:BAAALAAECgYIBgAAAA==.Gluo:BAABLAAECoEYAAIDAAcIoAy8EgBFAQADAAcIoAy8EgBFAQAAAA==.',Gn='Gnomax:BAAALAAECgcICwAAAA==.',Go='Gokuwastaken:BAABLAAECoEXAAISAAcIVh8WGACMAgASAAcIVh8WGACMAgABLAAFFAYIGAAMADEeAA==.Gorache:BAAALAADCgYIBgAAAA==.Gordoz:BAAALAAECgUIBgAAAA==.Goruk:BAAALAAECgYICQAAAA==.Goyav:BAAALAAECgEIAQAAAA==.',Gr='Gravâtrix:BAABLAAECoEkAAIHAAgIayGAGQBnAgAHAAgIayGAGQBnAgAAAA==.Grosgnon:BAAALAAECgcIBwAAAA==.Grümpy:BAAALAADCggIGAAAAA==.',['Gâ']='Gârgâ:BAAALAADCgYICwAAAA==.',['Gê']='Gênessys:BAAALAAECgMIBgAAAA==.',Ha='Habaday:BAAALAAECggIDAAAAA==.Hagator:BAAALAADCggICAAAAA==.Hailee:BAAALAADCggIFAAAAA==.Hamesh:BAAALAAECgMIAwAAAA==.Haramis:BAAALAADCgcIDgAAAA==.Haunty:BAABLAAECoElAAIeAAgIKB9lBwDIAgAeAAgIKB9lBwDIAgAAAA==.Hawi:BAAALAAECgEIAQAAAA==.',He='Healocu:BAABLAAECoEWAAMTAAYIAx97SQCvAQATAAUIcR97SQCvAQABAAQIaw67wAC/AAAAAA==.Henei:BAAALAAECgcIEwAAAA==.Heàlleur:BAAALAADCggIEgAAAA==.Heîmdall:BAABLAAECoEdAAIfAAcIBgo1QQAuAQAfAAcIBgo1QQAuAQAAAA==.',Hi='Hindir:BAAALAADCgIIAgAAAA==.',Ho='Hokayd:BAAALAAECgYICQAAAA==.Holydabe:BAAALAAECggICAAAAA==.Holylumos:BAAALAAECgYICQABLAAFFAEIAQAIAAAAAA==.Horfela:BAAALAADCgEIAQAAAA==.Horrorshow:BAACLAAFFIEIAAIdAAIICRyACACzAAAdAAIICRyACACzAAAsAAQKgRcAAh0ACAjfGrMNAHwCAB0ACAjfGrMNAHwCAAAA.Hoxah:BAACLAAFFIEOAAIMAAUIiyAGBQADAgAMAAUIiyAGBQADAgAsAAQKgS0AAwwACAiKJR4HAFYDAAwACAh7JR4HAFYDAB4ACAigIFUIALICAAAA.Hoyakö:BAAALAAFFAIIAgABLAAFFAYIBwAHACEgAA==.',Hu='Huntìs:BAAALAADCgYIBgAAAA==.Huribu:BAAALAADCggICwABLAAECgYIGAATALoTAA==.',['Hé']='Héré:BAABLAAECoEXAAMQAAgIAhj7EwBJAgAQAAgIAhj7EwBJAgAgAAUI1RNNKgAVAQAAAA==.',['Hë']='Hëttaggèr:BAAALAAECggICAAAAA==.',['Hî']='Hîri:BAAALAADCgcIBwABLAAECggIFQACAHgkAA==.',['Hø']='Høllypow:BAAALAAECgYIBgABLAAECggIJQAeACgfAA==.Høpes:BAAALAADCggIDgAAAA==.',Ib='Ibò:BAAALAAECgUICgAAAA==.',Ic='Icavex:BAAALAAECgYICAAAAA==.',Id='Idrjiä:BAAALAADCggIDwABLAAECggIBAAIAAAAAA==.',Il='Ilynn:BAAALAAECgYIDwAAAA==.',Im='Imnotfiredup:BAAALAADCgcIBwABLAAFFAQIDAAeACwGAA==.',In='Inagua:BAAALAAECgEIAQAAAA==.',Is='Ishbala:BAAALAAECgYIBgAAAA==.',Jb='Jb:BAAALAADCgYIBgAAAA==.',Je='Jeanmichaman:BAAALAADCggICwABLAAECgYIEQAIAAAAAA==.Jeanmikifear:BAAALAAECgYIEQAAAA==.Jemjem:BAABLAAECoEgAAIBAAgIbgrJhAA3AQABAAgIbgrJhAA3AQAAAA==.',Jh='Jhezabelle:BAAALAAECgIIAgAAAA==.Jhih:BAAALAADCggIGAAAAA==.',Ji='Jinav:BAAALAAECgMIAwAAAA==.',Jo='Jordän:BAAALAAECgYIEQAAAA==.',Jr='Jrz:BAAALAADCggIDAAAAA==.',Ju='Juhyô:BAAALAADCgMIAwAAAA==.Juicybolt:BAAALAAECgQIBgAAAA==.Juicymixy:BAAALAAECgMIAwAAAA==.',Jz='Jzr:BAAALAADCgYIDAAAAA==.',['Jâ']='Jâsmïne:BAAALAADCgMIAwAAAA==.',['Jö']='Jölyne:BAAALAAECggIEwAAAA==.Jösuke:BAAALAAECgYIDQAAAA==.',Ka='Kaane:BAAALAAECgcIDQAAAA==.Kadéra:BAABLAAECoEWAAIbAAYISxl5IQCtAQAbAAYISxl5IQCtAQAAAA==.Kaelhyne:BAABLAAECoEmAAIbAAgIoBGQIAC1AQAbAAgIoBGQIAC1AQAAAA==.Kagou:BAAALAADCgcIBwABLAAFFAUIEgAgAC4fAA==.Kahba:BAAALAAECgcIDAAAAA==.Kahki:BAAALAADCgcICQAAAA==.Kaihn:BAAALAADCggIDQAAAA==.Kame:BAAALAAECgYIBgAAAA==.Karashy:BAAALAADCggIDgAAAA==.Karàba:BAAALAAECgMIBwAAAA==.Kasugo:BAAALAADCgYIBgAAAA==.Katkar:BAACLAAFFIELAAIYAAMIPxUPBADnAAAYAAMIPxUPBADnAAAsAAQKgRwAAhgACAhcIUYIAPcCABgACAhcIUYIAPcCAAAA.Kazari:BAAALAAECgYICQAAAA==.',Ke='Keepdk:BAAALAAECggIBQAAAA==.Keeppal:BAAALAAECgIIAgAAAA==.Keepwar:BAAALAAECgYIDAAAAA==.Keize:BAABLAAECoEeAAMhAAgIGxqeBAB+AgAhAAgIGxqeBAB+AgARAAYI3w2wqQAkAQAAAA==.Kenseidrifto:BAAALAAECgMIAwAAAA==.Kepplar:BAAALAADCgYIBgAAAA==.Kesla:BAACLAAFFIEVAAMBAAYImhjWAQAUAgABAAYImhjWAQAUAgATAAEIigXKKQBQAAAsAAQKgTYAAwEACAhRJpMBAGADAAEACAhRJpMBAGADABMABwiNGn0yABMCAAAA.',Kh='Khayrwyn:BAAALAAECgIIAgAAAA==.Khâlî:BAAALAADCgYICwAAAA==.',Ki='Kiho:BAAALAAECgYIBgABLAAFFAIIBgAHAHYTAA==.Kijo:BAAALAADCgUIBQABLAAFFAIIBgAHAHYTAA==.Kilkeny:BAAALAADCggIDQAAAA==.Killyu:BAABLAAECoEqAAIPAAgIPSBgGwDpAgAPAAgIPSBgGwDpAgAAAA==.Kinbew:BAABLAAECoEWAAIWAAYIYA/mFQA0AQAWAAYIYA/mFQA0AQABLAAECgcIIwARADgbAA==.Kinboa:BAABLAAECoEjAAIRAAcIOBshSQD9AQARAAcIOBshSQD9AQAAAA==.Kirlepanda:BAAALAADCggIEwAAAA==.Kiro:BAACLAAFFIEGAAMHAAIIdhNuFQCQAAAHAAIIdhNuFQCQAAAFAAII2gvQJACDAAAsAAQKgSgAAwcACAhgHOIXAHYCAAcACAhgHOIXAHYCAAUABQgWCLyHAL0AAAAA.Kironash:BAAALAADCgcIBwAAAA==.',Kl='Klarté:BAABLAAECoEjAAIQAAgIwxgPEgBhAgAQAAgIwxgPEgBhAgAAAA==.Klimz:BAAALAADCgEIAQAAAA==.Klinnlad:BAAALAAECggIDQAAAA==.Klyshadow:BAABLAAECoEXAAIJAAYIdBHwSgBjAQAJAAYIdBHwSgBjAQAAAA==.Klysham:BAAALAAECgcIEAAAAA==.',Ko='Korleus:BAAALAAECgYICwAAAA==.Korlita:BAAALAADCgcIBwAAAA==.Kornyc:BAAALAADCgEIAQAAAA==.Korpiklaanï:BAAALAAECggIEAAAAA==.',Kr='Kralizek:BAAALAAECgYIDgAAAA==.Krastio:BAAALAAECgYICQAAAA==.Krazilec:BAAALAADCggICAAAAA==.Krokmoû:BAAALAAECgMIBAAAAA==.Kruxx:BAACLAAFFIEIAAIKAAIIEiHTDgC1AAAKAAIIEiHTDgC1AAAsAAQKgTEAAgoACAigI2QFAC4DAAoACAigI2QFAC4DAAAA.Krís:BAAALAAECgYIBgAAAA==.',Ks='Kstør:BAAALAAECgYIDwAAAA==.',Kv='Kvl:BAAALAAECgEIAQAAAA==.',Ky='Kyaàry:BAAALAAECgYIBwAAAA==.Kyerra:BAAALAAECgQIBwAAAA==.Kyerrae:BAAALAAECgEIAQAAAA==.Kyerrah:BAAALAAECgMIAwAAAA==.Kysmyass:BAAALAAECgUIBAABLAAECgUICAAIAAAAAA==.',['Kâ']='Kâlthèra:BAAALAAECggICAAAAA==.',['Ké']='Kéria:BAAALAADCggIFQAAAA==.',['Kê']='Kêêpstrong:BAAALAADCgUIBQAAAA==.',['Kø']='Kørax:BAAALAAECgcIDQAAAA==.Køsmø:BAAALAADCggICQAAAA==.',La='Laflechette:BAAALAAECgQIBwAAAA==.Lanerdow:BAABLAAECoElAAMNAAgIJR6JDgCnAgANAAgIxh2JDgCnAgAaAAQINxr1JAA7AQAAAA==.Lanerknife:BAABLAAECoEZAAMNAAgIDBpEGgAvAgANAAcIiRpEGgAvAgAaAAQIiRJpLADyAAAAAA==.Latorpille:BAAALAADCgEIAQAAAA==.',Le='Ledoyen:BAAALAAFFAEIAQAAAA==.Leilleiwel:BAAALAAECgYIEQAAAA==.Lexidam:BAAALAADCgIIAgAAAA==.',Li='Lightniñg:BAAALAAECgYICAAAAA==.Lilylou:BAAALAADCgUIBQAAAA==.',Ll='Lleiwel:BAAALAADCgYIBgAAAA==.',Lo='Logana:BAAALAADCggICgAAAA==.Lostuam:BAAALAADCgYIBgAAAA==.',Lu='Lucee:BAAALAADCgEIAQAAAA==.Lulw:BAABLAAECoEVAAIhAAcIGyHUAwCgAgAhAAcIGyHUAwCgAgAAAA==.',Lw='Lwi:BAAALAAECgYIDAAAAA==.',Ly='Lycal:BAAALAAECgcIEAAAAA==.',['Lî']='Lîsta:BAAALAADCgUIBQAAAA==.',['Lï']='Lïght:BAACLAAFFIETAAIiAAUIoR7hAgDkAQAiAAUIoR7hAgDkAQAsAAQKgSgAAiIACAhtJjkAAIQDACIACAhtJjkAAIQDAAAA.',['Lû']='Lûlû:BAACLAAFFIEJAAMUAAMItBQrBQAEAQAUAAMItBQrBQAEAQAjAAEI3QSoagA8AAAsAAQKgSgAAxQACAg0GEwQADoCABQACAibFUwQADoCACMABwgXDd2yAGUBAAAA.',Ma='Madarat:BAABLAAECoEjAAIbAAcImhRIKAB4AQAbAAcImhRIKAB4AQAAAA==.Mafouam:BAAALAAECgcIEQAAAA==.Magmaslayer:BAAALAADCgMIAwAAAA==.Makaz:BAAALAAECgcIDgABLAAECggIGgAPAG4bAA==.Malyka:BAAALAAECgEIAQAAAA==.Malìfiko:BAAALAAECgIIAgAAAA==.Mamimi:BAAALAAECgYIDQAAAA==.Mangtmor:BAAALAADCgUIBQAAAA==.Manoû:BAAALAAECgEIAQAAAA==.Marvellus:BAAALAADCggIDgAAAA==.Maryjones:BAAALAADCgUIBQAAAA==.Matsükö:BAACLAAFFIEHAAISAAQIkxEjCQAbAQASAAQIkxEjCQAbAQAsAAQKgSkAAxIACAgmIxoLAAADABIACAgmIxoLAAADABEABQiyFi+bAEEBAAAA.Maximus:BAAALAAECgIIAwABLAAECggIHAAjAFIfAA==.Maximusse:BAABLAAECoEcAAIjAAgIUh94HwDRAgAjAAgIUh94HwDRAgAAAA==.Mayuyuyu:BAAALAAECgMIBAAAAA==.Mazikheen:BAAALAAECgcIEwAAAA==.Maîtrenain:BAAALAAECgYIBgABLAAFFAIICAAKABIhAA==.Maïline:BAABLAAECoEmAAIBAAgIxxizLAA3AgABAAgIxxizLAA3AgAAAA==.',Me='Mehealplz:BAAALAAFFAIIAgABLAAFFAUIDQAZAP8VAA==.Memnøk:BAAALAAECgYIDgAAAA==.Meytah:BAAALAAECgcIEAAAAA==.Mezzø:BAAALAAECgcIEwAAAA==.Mezzøtte:BAAALAADCggIEAABLAAECgcIEwAIAAAAAA==.',Mi='Michkael:BAAALAADCggIJQAAAA==.Midthunder:BAAALAAECgYICAAAAA==.Mightyure:BAABLAAECoEgAAITAAgICBoXIAB9AgATAAgICBoXIAB9AgAAAA==.Miiriit:BAAALAADCgYIBgAAAA==.Miirit:BAAALAADCgcIDwAAAA==.Mimisikuu:BAACLAAFFIEKAAIRAAIIbh/3HQCnAAARAAIIbh/3HQCnAAAsAAQKgRoAAhEACAhHJMcMABkDABEACAhHJMcMABkDAAAA.Mimo:BAAALAAECggIDwAAAA==.',Mo='Moghiro:BAABLAAFFIEHAAMHAAYIISB/AgD/AQAHAAUIyiJ/AgD/AQAFAAEIqxVSMQBWAAAAAA==.Moitrà:BAABLAAECoEUAAIUAAcIvSOSDABxAgAUAAcIvSOSDABxAgAAAA==.Mojos:BAABLAAECoEYAAIFAAYITAoLcgD7AAAFAAYITAoLcgD7AAAAAA==.Mokø:BAAALAADCgcIBwABLAAECgYIEQAIAAAAAA==.Mongrobou:BAAALAADCgcIBwAAAA==.Mopotojo:BAAALAAECgEIAQAAAA==.Mopwasbetter:BAACLAAFFIEYAAMMAAYIMR4JAgBiAgAMAAYIMR4JAgBiAgAeAAUIiRNZAQB+AQAsAAQKgSoAAwwACAhFJkUCAH8DAAwACAhFJkUCAH8DAB4AAQjBIoVKAGQAAAAA.Moutchouxe:BAAALAADCggICAAAAA==.',Mu='Munzeria:BAAALAAECgcIDgAAAA==.Mursaat:BAABLAAECoElAAIXAAgIkAShHwDYAAAXAAgIkAShHwDYAAAAAA==.',My='Myoangelo:BAAALAADCggIFAAAAA==.',['Mã']='Mãnimal:BAAALAAECgEIAgAAAA==.',['Mä']='Mälphas:BAAALAAECggICAAAAA==.Mänd:BAAALAADCggICQAAAA==.Mändrayne:BAAALAAECggIDgAAAA==.',['Mé']='Mégabit:BAAALAADCggICAAAAA==.Mélancolie:BAAALAADCgYICAAAAA==.',['Mò']='Mòrphé:BAAALAADCggIEQAAAA==.',['Mó']='Mónory:BAABLAAECoEeAAIjAAgIACVNCQBGAwAjAAgIACVNCQBGAwAAAA==.',['Mø']='Mølly:BAACLAAFFIELAAIMAAMIlw5TFADmAAAMAAMIlw5TFADmAAAsAAQKgSUAAgwACAiYHJI1AFwCAAwACAiYHJI1AFwCAAAA.',Na='Naasty:BAAALAADCgUICAAAAA==.Nachtjäger:BAAALAADCgYIBgAAAA==.Naimpureté:BAABLAAECoEXAAIbAAcIfhS9IgCiAQAbAAcIfhS9IgCiAQAAAA==.Namy:BAAALAAECgEIAQAAAA==.Narmina:BAAALAAECgcIBwAAAA==.Narween:BAABLAAECoEZAAMJAAYIGAsbVgAxAQAJAAYIGAsbVgAxAQADAAYIKQraGgDfAAAAAA==.Nastoumë:BAAALAAECggIDgAAAA==.Naâbo:BAAALAADCggIEAAAAA==.',Nc='Ncr:BAAALAADCgcIBwAAAA==.',Ne='Neawo:BAAALAADCggICQAAAA==.Neiflheim:BAAALAADCgcIBwABLAAFFAUIEQAJAE8YAA==.Nerzh:BAAALAADCgYIBgABLAAECgMIAwAIAAAAAA==.Nessa:BAABLAAECoEaAAIBAAcIShBtcQBlAQABAAcIShBtcQBlAQAAAA==.Nevïk:BAAALAADCgcIBwAAAA==.Newhoo:BAAALAADCgIIAgAAAA==.',Ni='Nijika:BAABLAAECoEjAAIhAAgInyTlAABQAwAhAAgInyTlAABQAwAAAA==.Nikto:BAAALAAECgMIAwAAAA==.Nilomim:BAAALAADCgMIAwAAAA==.Ninou:BAAALAAECgUIBQAAAA==.Nixara:BAAALAADCggIGgAAAA==.',No='Nobù:BAAALAADCgcIBwAAAA==.Nonope:BAAALAAECgcIBwAAAA==.Noodlle:BAAALAAECgEIAQAAAA==.Noonoope:BAAALAADCggICQAAAA==.Notowa:BAABLAAECoElAAIFAAgI2x4VDwC+AgAFAAgI2x4VDwC+AgAAAA==.',Nu='Nuagée:BAABLAAECoEYAAMWAAYIoRUsEgBuAQAWAAYIoRUsEgBuAQAGAAMIagXRNQB6AAAAAA==.Nueve:BAAALAAECgYIDwAAAA==.Null:BAABLAAECoEcAAIKAAYI1glbPQAoAQAKAAYI1glbPQAoAQAAAA==.',Ny='Nymue:BAAALAAECgYIDgAAAA==.Nyxara:BAAALAADCgcIEQAAAA==.Nyxarïa:BAAALAADCgcIDwAAAA==.',['Nà']='Nàvÿ:BAAALAADCgMIAwAAAA==.',['Nä']='Nämîe:BAAALAAECggICQABLAAFFAEIAQAIAAAAAA==.Nämï:BAAALAAECgUIBgAAAA==.',['Né']='Nélizé:BAAALAAECgYIDAAAAA==.',Od='Odín:BAAALAADCggICAAAAA==.',Oe='Oena:BAAALAADCgIIAgAAAA==.Oestrogene:BAAALAAECgEIAQAAAA==.',Oi='Oichi:BAAALAADCgYIBgAAAA==.Oigen:BAAALAADCgcICAAAAA==.',Ol='Olivers:BAAALAADCgIIAgAAAA==.',Om='Ombrastraza:BAAALAADCggIGAAAAA==.',On='Onepunchfox:BAAALAADCgYICQAAAA==.',Or='Orionfrost:BAABLAAECoEaAAIYAAcI4SIvDAC4AgAYAAcI4SIvDAC4AgAAAA==.Orzo:BAAALAADCggICAAAAA==.',Ou='Ouistisinge:BAACLAAFFIEGAAISAAYIgBQVAwDfAQASAAYIgBQVAwDfAQAsAAQKgRsAAxIABwi4IJEaAHgCABIABwi4IJEaAHgCABEAAQiWE/EMATUAAAAA.',Oz='Ozérixya:BAABLAAECoEZAAIYAAcI9hlmGwAVAgAYAAcI9hlmGwAVAgAAAA==.',['Oé']='Oén:BAAALAAECgYIBgAAAA==.',Pa='Paffouu:BAAALAADCggIBAAAAA==.Painmoisi:BAAALAAECgMIBgAAAA==.Palabaf:BAAALAAECgEIAQABLAAECggIHgAJABUaAA==.Palabatéou:BAAALAAECggICAAAAA==.Palounete:BAAALAAECgYIEAAAAA==.Palâdin:BAAALAADCggIFwAAAA==.Pastagaa:BAAALAAECgMIAwAAAA==.Patecatl:BAAALAAECgYICQAAAA==.Pattefolle:BAAALAADCgYIBgAAAA==.',Pe='Pecktina:BAAALAADCgQIBAAAAA==.Pepejeans:BAAALAAECggICAAAAA==.Petboul:BAAALAAECgUICAAAAA==.',Ph='Pharamond:BAAALAADCggICAAAAA==.Phillip:BAAALAAECgMIAwABLAAFFAIIBgAPAMQlAA==.Phïnax:BAAALAADCgIIAgAAAA==.',Pi='Pidakor:BAAALAADCgQIBAAAAA==.Pignouff:BAAALAAECgYICQAAAA==.',Pl='Placebð:BAAALAAECgYIDwAAAA==.Pluvieuse:BAAALAADCgcIBwABLAAECgYIGAAWAKEVAA==.',Pn='Pnzrknst:BAAALAAECggIEwAAAA==.',Po='Pokniovitch:BAAALAADCggIHAAAAA==.',Pr='Prèsan:BAAALAAECggIDgAAAA==.Prøtek:BAABLAAECoEXAAIRAAgIwB3XHQCuAgARAAgIwB3XHQCuAgAAAA==.',Pu='Punishêr:BAAALAAECgMIBgAAAA==.Purifikatiøn:BAAALAADCggICAAAAA==.Puritania:BAAALAAECgMIAwAAAA==.',['Pä']='Pästaga:BAAALAAECgMIBAAAAA==.',['Pé']='Pépé:BAAALAADCgUIBQAAAA==.Pépégém:BAAALAAECgYIEAAAAA==.Pérédur:BAABLAAECoEXAAIPAAgIVhucLwCJAgAPAAgIVhucLwCJAgAAAA==.',Qr='Qroh:BAABLAAECoEbAAITAAcI4iLEGQCsAgATAAcI4iLEGQCsAgAAAA==.',Qu='Quality:BAAALAAECgIIAwAAAA==.Quentîn:BAAALAADCggIFAAAAA==.Quetrax:BAAALAAECgYICwAAAA==.Quitue:BAAALAAECgIIAwAAAA==.',Ra='Raikana:BAAALAAECgYIBgAAAA==.Railana:BAAALAADCggICAABLAAECgYIBgAIAAAAAA==.Rapotipomort:BAACLAAFFIELAAIjAAMIIhELGQDlAAAjAAMIIhELGQDlAAAsAAQKgRwABCMACAh2GeJwANwBACMACAiYF+JwANwBAA4ABQgaGtgaAHwBABQAAQhRFh5RAEAAAAEsAAUUAwgMAAoAFhwA.Rapotipécail:BAACLAAFFIEMAAIKAAMIFhz3CQADAQAKAAMIFhz3CQADAQAsAAQKgRcAAgoACAiDHewUAGcCAAoACAiDHewUAGcCAAAA.Rasmussen:BAAALAADCggICgAAAA==.Rastakwere:BAAALAADCgIIAgAAAA==.Razoi:BAAALAADCgcIBwAAAA==.Razoir:BAAALAAECgcIDgABLAAECggIGgAkAP0gAA==.Razoïr:BAABLAAECoEaAAIkAAgI/SBIDABpAgAkAAgI/SBIDABpAgAAAA==.Raö:BAAALAADCgQIBAABLAAECgcIEwAIAAAAAA==.',Re='Recountsama:BAAALAAECgYIEwAAAA==.Redangel:BAAALAADCggICAAAAA==.Reesa:BAACLAAFFIEGAAIRAAIIEBU2JgCTAAARAAIIEBU2JgCTAAAsAAQKgRgAAhEACAjAGxQpAHMCABEACAjAGxQpAHMCAAAA.Relnis:BAAALAAECgMIBAAAAA==.Remorse:BAABLAAECoEkAAIRAAgINBa9QwAOAgARAAgINBa9QwAOAgAAAA==.',Rh='Rhaedrim:BAAALAAECggIDQAAAA==.',Ri='Rispedk:BAABLAAECoEWAAMjAAcIJx9kRABGAgAjAAcIJx9kRABGAgAOAAQIthZPKwDOAAAAAA==.Rispetotem:BAAALAADCgcIBwAAAA==.Rispewar:BAAALAADCggICAAAAA==.',Rn='Rney:BAABLAAECoErAAMSAAcIKxrrKAASAgASAAcIKBrrKAASAgARAAQIRA3w1QC1AAAAAA==.',Ro='Rombiere:BAAALAADCgYIBgAAAA==.Romero:BAAALAADCgMIAwAAAA==.Rosemarie:BAAALAADCggICAAAAA==.Roucasse:BAAALAADCgYICAAAAA==.Roumaindbois:BAAALAAECgUIBQAAAA==.',Ru='Ruddy:BAAALAAECggIDgAAAA==.Rugrud:BAAALAAECgMIBAAAAA==.Rumxus:BAABLAAECoEoAAIVAAgIgB8+GADTAgAVAAgIgB8+GADTAgAAAA==.Ruskov:BAABLAAECoEYAAMVAAgI1RfWOAAaAgAVAAgISxfWOAAaAgAXAAUIag/aGwAMAQAAAA==.',Sa='Salacity:BAAALAAECgIIAgAAAA==.Salyä:BAABLAAECoEdAAICAAgI/RBIOADUAQACAAgI/RBIOADUAQAAAA==.Samoth:BAAALAADCgQIAwAAAA==.Saturneko:BAAALAADCggIEAAAAA==.Sawsix:BAABLAAECoEkAAINAAgIDxr6EACMAgANAAgIDxr6EACMAgAAAA==.',Sc='Scyna:BAAALAAECgYIBgAAAA==.',Se='Seiyah:BAAALAADCgcIBwAAAA==.Seraphita:BAAALAAECgUICQAAAA==.',Sh='Shadowvoid:BAAALAADCgcIBwAAAA==.Shadøwhimø:BAAALAAECgMIBQAAAA==.Sharinga:BAAALAAECgQICQAAAA==.Shaïne:BAAALAADCggICAAAAA==.Shenhe:BAAALAADCggIIwAAAA==.Sheyana:BAAALAADCgYIBgABLAAECggIGQAMAHIiAA==.Shindiara:BAABLAAECoEfAAIlAAYI2xr9VADgAQAlAAYI2xr9VADgAQAAAA==.Shiroyoru:BAAALAADCggIDAAAAA==.Shiso:BAAALAAECgcIBwAAAA==.Shonurb:BAAALAADCgcIBwABLAADCggIBQAIAAAAAA==.Shounevok:BAAALAADCggICAAAAA==.Shoux:BAABLAAECoEfAAIKAAcIBSLiDgCvAgAKAAcIBSLiDgCvAgAAAA==.Shoxx:BAAALAAECgMIBAAAAA==.Shux:BAAALAAECgYICQABLAAECgcIHwAKAAUiAA==.Shïdori:BAAALAADCggICAAAAA==.',Si='Sigyn:BAAALAADCggICAAAAA==.',Sm='Smartiez:BAAALAAECggIDwAAAA==.',Sn='Sneakyz:BAAALAADCgcIDAAAAA==.Snoffgit:BAAALAAECgMIAwAAAA==.',So='Sonepi:BAAALAADCgYIDwAAAA==.Soulblaka:BAAALAADCgQIAgAAAA==.Soultaker:BAABLAAECoEgAAIYAAgIpyJJBQAsAwAYAAgIpyJJBQAsAwAAAA==.Sourïcette:BAAALAAECgUIBQABLAAFFAMICwAMAJcOAA==.Soze:BAAALAAECgYIEQAAAA==.',Sp='Spikø:BAAALAAECgYICgAAAA==.Spizzis:BAABLAAECoEbAAMfAAgIXxYIGQAyAgAfAAgIXxYIGQAyAgAVAAEIDgeI0AAuAAAAAA==.Spookies:BAAALAAECgYIDgAAAA==.Sprîtz:BAAALAAECgQIBAAAAA==.Spyni:BAACLAAFFIELAAMLAAMIRx7fAgARAQALAAMIRx7fAgARAQAKAAII3xLQEgCVAAAsAAQKgSYAAwsACAi/I9EBAOgCAAsACAiDI9EBAOgCAAoACAh4HYAOALMCAAAA.Spyrò:BAAALAAECgYICwAAAA==.',Sq='Sqll:BAAALAAECgYIBgAAAA==.Squallm:BAAALAAECgUICgAAAA==.',St='Stelløu:BAAALAAECgUIBgAAAA==.Stoormywar:BAAALAAECggICwABLAAFFAQIDAAeACwGAA==.Stormy:BAACLAAFFIEMAAMeAAQILAZWBADMAAAeAAQILAZWBADMAAAMAAEIJAKaRgA6AAAsAAQKgR4AAgwACAhVHLczAGMCAAwACAhVHLczAGMCAAAA.Stormêttê:BAAALAAECgUICAABLAAFFAQIDAAeACwGAA==.Stürling:BAAALAAECgYICgAAAA==.',Su='Sucetteu:BAAALAADCgQIBAAAAA==.Sucram:BAAALAAECgYIDQAAAA==.',Sw='Swwarleyy:BAAALAADCgUIBQAAAA==.',Sy='Sylrieth:BAAALAAECgYICgAAAA==.Syyn:BAABLAAECoEVAAIRAAcIuR1UPQAjAgARAAcIuR1UPQAjAgAAAA==.',['Sø']='Sønsøn:BAAALAADCgcIBwAAAA==.',['Sû']='Sûcram:BAABLAAECoEgAAIMAAYIdSTCMQBrAgAMAAYIdSTCMQBrAgAAAA==.',Ta='Taiitwiist:BAAALAADCggIDAAAAA==.Takashy:BAACLAAFFIESAAIgAAUILh9uAgDaAQAgAAUILh9uAgDaAQAsAAQKgScAAiAACAgnJjABAFwDACAACAgnJjABAFwDAAAA.Tarma:BAAALAADCgEIAQAAAA==.Tatoutinitié:BAAALAADCgMIAwAAAA==.',Tc='Tchangw:BAAALAAECgYIDAAAAA==.',Te='Telliok:BAAALAADCgEIAQAAAA==.Telracs:BAAALAADCggIDwAAAA==.Telsyn:BAABLAAECoEVAAIhAAYInw86DwCBAQAhAAYInw86DwCBAQAAAA==.Tempfired:BAAALAADCggIEAABLAAECgYIDAAIAAAAAA==.Tempfirek:BAAALAAECgYIDAAAAA==.Tempfirel:BAAALAADCgcIDAABLAAECgYIDAAIAAAAAA==.Tenderness:BAAALAADCggIBwAAAA==.Tenedrions:BAAALAAECgYIDgAAAA==.Teuilteuil:BAAALAAECgYIBgAAAA==.',Th='Thae:BAAALAADCggIEAABLAAECggIDQAIAAAAAA==.Thautank:BAAALAADCgMIBAAAAA==.Thridek:BAABLAAECoEbAAIcAAgI5hz9BQCdAgAcAAgI5hz9BQCdAgAAAA==.Thuldus:BAAALAADCggICQAAAA==.Thunda:BAACLAAFFIEKAAIBAAIInCJZFADLAAABAAIInCJZFADLAAAsAAQKgSIAAgEACAgsIDYOAN0CAAEACAgsIDYOAN0CAAAA.Thyr:BAAALAADCggICAAAAA==.',Ti='Tifa:BAAALAAECggIBAAAAA==.Tikita:BAAALAADCgcICQAAAA==.',To='Tooropmakta:BAAALAAECgIIAgAAAA==.Tooropmaktou:BAAALAAECgcICwAAAA==.Torniaule:BAAALAADCgcIBwAAAA==.Totorn:BAAALAADCgIIAgAAAA==.Tourbïløl:BAAALAAECggICAAAAA==.Tovac:BAAALAADCgYICwAAAA==.Toxyk:BAAALAADCgYIAQAAAA==.',Tr='Trintellix:BAAALAADCgcIBwAAAA==.Triple:BAAALAADCggIFAAAAA==.Trouzun:BAAALAAECgYICQAAAA==.',Ts='Tsukubai:BAAALAADCggIDQAAAA==.',Tu='Tuckor:BAAALAAECgYICgAAAA==.Tulistéuncon:BAAALAADCgYIBgAAAA==.',['Tâ']='Tâll:BAAALAADCgcIBgAAAA==.',['Té']='Ténébrius:BAAALAADCggIEAABLAAECggIDAAIAAAAAA==.Téylaa:BAAALAAECgMIBgAAAA==.',['Tï']='Tïara:BAAALAADCgQIBAAAAA==.',['Tö']='Töketsu:BAAALAAECgMIBQAAAA==.',['Tø']='Tøorx:BAAALAADCggIHwAAAA==.',Ul='Uldreiyn:BAAALAAECggICAAAAA==.',Un='Unbroken:BAAALAAECgcIDQAAAA==.Unsainted:BAAALAADCgMIAwAAAA==.',Ut='Utarnia:BAAALAADCggICAAAAA==.Utaw:BAAALAAECgYIBgAAAA==.',Va='Valkiel:BAAALAADCggIEAAAAA==.Valmia:BAAALAAECgYIDQAAAA==.Valtharo:BAABLAAECoEfAAIcAAgIqSSWAQA6AwAcAAgIqSSWAQA6AwAAAA==.Vandal:BAAALAADCgYICAAAAA==.Vanpcow:BAAALAAECgMIBAABLAAECggIJAAjAJAaAA==.Vanpirus:BAABLAAECoEkAAIjAAgIkBqjNAB5AgAjAAgIkBqjNAB5AgAAAA==.Varoth:BAABLAAECoEZAAIVAAcI6BtJMwAxAgAVAAcI6BtJMwAxAgAAAA==.Vax:BAAALAADCggICAAAAA==.',Vl='Vladimørt:BAAALAADCggICAAAAA==.',Vo='Vodom:BAAALAAECgEIAQAAAA==.Voltrogue:BAAALAAECgYIEgAAAA==.Voltunholy:BAABLAAECoEbAAIjAAgIgyPyDQAsAwAjAAgIgyPyDQAsAwAAAA==.Vorhaks:BAAALAAECgYICQAAAA==.',Vr='Vrokis:BAAALAAECgYIBgAAAA==.',Vu='Vulpix:BAACLAAFFIEVAAIVAAYIqBcyAwApAgAVAAYIqBcyAwApAgAsAAQKgTkAAhUACAhzJZQHAE0DABUACAhzJZQHAE0DAAAA.',Vy='Vyrta:BAAALAAECgcIEgAAAA==.',['Vâ']='Vâyranna:BAAALAAECgIIAgAAAA==.',['Vë']='Vëlty:BAAALAADCgcIBwAAAA==.',['Vï']='Vïcinois:BAAALAAECgUIBwAAAA==.Vïnitia:BAAALAAFFAEIAQAAAA==.',Wa='Waifu:BAAALAAFFAIIAgAAAA==.Warrox:BAAALAAECgEIAgAAAA==.Wasteal:BAAALAADCggIDQAAAA==.',We='Weelow:BAAALAADCgcIBwAAAA==.Westindïes:BAABLAAECoEjAAIjAAgIBiOlDQAtAwAjAAgIBiOlDQAtAwAAAA==.',Wi='Wiesenthal:BAAALAADCgcIDQAAAA==.Wildstorms:BAAALAAECgcIBwAAAA==.',Wo='Wofînia:BAAALAADCggIEgAAAA==.Wonzie:BAAALAADCgYICwAAAA==.',['Wà']='Wàtù:BAACLAAFFIEFAAIeAAMINSPqAQA6AQAeAAMINSPqAQA6AQAsAAQKgSYAAh4ACAi/JXUBAGYDAB4ACAi/JXUBAGYDAAAA.',Xa='Xaariel:BAAALAADCggIHgAAAA==.',Xe='Xehanort:BAAALAAECgYICQAAAA==.Xemon:BAAALAADCgcIBwAAAA==.',Ya='Yatendouji:BAAALAADCgYIBgAAAA==.',Ye='Yelevoker:BAAALAADCggIFAAAAA==.Yenelo:BAABLAAECoEfAAMBAAgIIxLLUQC7AQABAAgIIxLLUQC7AQATAAIIOAkCmwBlAAAAAA==.',Yo='Yotzlol:BAABLAAECoEfAAIRAAgI+CJsDQAUAwARAAgI+CJsDQAUAwAAAA==.',Ys='Ysthale:BAAALAAECgQIBQAAAA==.Ysé:BAABLAAECoEVAAMCAAYIshPjUwBhAQACAAYIOhPjUwBhAQADAAEIzxR+LwA9AAAAAA==.',Yu='Yugitø:BAAALAADCgcIDAAAAA==.Yumeda:BAABLAAECoEZAAILAAYINhQ9CgCDAQALAAYINhQ9CgCDAQAAAA==.',Yv='Yvar:BAAALAADCgYIBgAAAA==.',Yz='Yzaker:BAAALAADCggIDwAAAA==.Yzanami:BAAALAAECgYICAAAAA==.',['Yé']='Yéliia:BAAALAAECgMIAwABLAAECgcIEgAIAAAAAA==.',Za='Zakmi:BAAALAAECgIIAgAAAA==.Zalene:BAAALAADCgQIBgAAAA==.Zartrons:BAABLAAECoEcAAIPAAgIaiQcCQBQAwAPAAgIaiQcCQBQAwAAAA==.Zayone:BAAALAAFFAIIAgAAAA==.',Zb='Zbiboo:BAAALAADCggIDQAAAA==.',Ze='Zelieek:BAAALAAECgEIAQAAAA==.Zenesprit:BAAALAAECgYIDwAAAA==.Zephiris:BAAALAAECgUIBQAAAA==.',Zh='Zhoka:BAABLAAECoEYAAMWAAgIISMaAgAiAwAWAAgIISMaAgAiAwAGAAYI0BrHGwCTAQABLAAECggIHgAZAHcbAA==.Zhokah:BAABLAAECoEbAAIYAAYImhwUIADyAQAYAAYImhwUIADyAQABLAAECggIHgAZAHcbAA==.Zhøka:BAAALAADCggICAABLAAECggIHgAZAHcbAA==.',Zi='Zids:BAAALAADCggICAAAAA==.Zink:BAAALAADCgMIAQAAAA==.',Zo='Zobois:BAACLAAFFIEUAAIPAAYIoRUWAgAeAgAPAAYIoRUWAgAeAgAsAAQKgSUAAg8ACAiKJGkQACQDAA8ACAiKJGkQACQDAAAA.Zohka:BAABLAAECoEeAAMZAAgIdxsfNgAxAgAZAAgIPRYfNgAxAgAdAAMIoCAySQAjAQAAAA==.Zokha:BAAALAADCgYIBgABLAAECggIHgAZAHcbAA==.Zolpanique:BAAALAADCgMIAwAAAA==.Zoubilou:BAAALAADCgYICwAAAA==.',Zu='Zumo:BAAALAADCggIHgAAAA==.Zupapa:BAABLAAECoEXAAMYAAcIUxIlLACnAQAYAAcIjhElLACnAQAlAAQI+QtHsADGAAAAAA==.Zupatem:BAAALAAECgUIBQABLAAECggIFwAYAFMSAA==.',['Æn']='Ænora:BAAALAADCgcIBwAAAA==.',['Él']='Élisya:BAAALAADCgcIBgAAAA==.Élysia:BAAALAADCgcICgAAAA==.',['Ðr']='Ðrøøks:BAAALAAECggIDgAAAA==.',['Ôn']='Ônurb:BAAALAADCggIBQAAAA==.',['Øm']='Ømëga:BAAALAADCggICQAAAA==.',['ße']='ßenihime:BAABLAAECoEfAAIJAAgIchTWKAAUAgAJAAgIchTWKAAUAgAAAA==.',['ßé']='ßéziers:BAAALAAECgYIBwAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end