local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Shaman-Restoration','Monk-Mistweaver','Druid-Restoration','Hunter-Marksmanship','Mage-Arcane','Warrior-Protection','DeathKnight-Frost','Paladin-Retribution','Warlock-Destruction','Warlock-Demonology','Unknown-Unknown','Hunter-BeastMastery','Druid-Guardian','DeathKnight-Blood','Shaman-Elemental','Warrior-Fury','Warrior-Arms','Paladin-Protection','Evoker-Devastation','Paladin-Holy','Priest-Holy','Priest-Shadow','Evoker-Augmentation','DemonHunter-Havoc','DemonHunter-Vengeance','Druid-Feral','Rogue-Assassination','Shaman-Enhancement','Monk-Windwalker','Evoker-Preservation','Warlock-Affliction','DeathKnight-Unholy','Druid-Balance','Hunter-Survival','Rogue-Subtlety','Rogue-Outlaw','Mage-Frost','Monk-Brewmaster','Priest-Discipline',}; local provider = {region='EU',realm='Alexstrasza',name='EU',type='weekly',zone=44,date='2025-09-24',data={Aa='Aaleea:BAAALAADCgYICAAAAA==.',Ad='Aderia:BAAALAAECgUICwAAAA==.Adlia:BAAALAADCgIIAgAAAA==.',Ag='Agelicia:BAAALAAECgYIEgAAAA==.Aglaea:BAAALAADCggICAABLAAECgcIFgABAAAUAA==.Agona:BAAALAAECgYICAABLAAECggIFwACAD4YAA==.Agreal:BAAALAAECgYIDQAAAA==.',Ak='Akial:BAAALAADCgcIBwAAAA==.Akimo:BAAALAADCggIEgAAAA==.',Al='Alayne:BAABLAAECoEgAAIDAAcIFBchMwDiAQADAAcIFBchMwDiAQAAAA==.Albédó:BAAALAADCgMIAwAAAA==.Aldorasx:BAAALAAFFAIIAgAAAA==.Alduin:BAACLAAFFIEHAAIEAAIIlR4eEwCwAAAEAAIIlR4eEwCwAAAsAAQKgSgAAgQACAhtI80GACsDAAQACAhtI80GACsDAAAA.Aleastes:BAAALAADCggIFQAAAA==.Alenari:BAAALAADCgcIDQAAAA==.Alnitak:BAABLAAECoEnAAIDAAgIbBTeMQDoAQADAAgIbBTeMQDoAQAAAA==.Alrachi:BAAALAADCgQIBAAAAA==.',Am='Amalya:BAAALAAECgYIBgAAAA==.Amaterasu:BAABLAAECoElAAIBAAcIVCCCIgBoAgABAAcIVCCCIgBoAgAAAA==.Amber:BAABLAAECoEjAAIFAAcIAxFIbQCeAQAFAAcIAxFIbQCeAQAAAA==.Amunrah:BAAALAADCgUIBAAAAA==.Amylèé:BAAALAAECggICAAAAA==.',An='Ancksuamun:BAAALAAECgYIEgAAAA==.Anckzunamun:BAAALAADCggICAABLAAECgcIGAABAKIYAA==.Ansbald:BAAALAADCggIDwAAAA==.',Ap='Apoll:BAAALAADCggICgAAAA==.',Aq='Aqisoq:BAAALAADCgMIAwAAAA==.',Ar='Arachwen:BAAALAAECgcIDQABLAAECgcIIQAGAJMhAA==.Araggor:BAAALAADCgMIBQAAAA==.Are:BAAALAADCgcIBwAAAA==.Aredhél:BAAALAADCggIBwAAAA==.Armalyte:BAAALAAECgYIEgAAAA==.Arthyx:BAAALAAECggIDQAAAA==.',As='Asaron:BAAALAAECgMIBQAAAA==.Askalante:BAABLAAECoEYAAIHAAgIwAzDiQCwAQAHAAgIwAzDiQCwAQAAAA==.',At='Atbest:BAAALAAECgMICAAAAA==.Atheenos:BAABLAAECoEZAAIIAAYIxyCOUQAfAgAIAAYIxyCOUQAfAgAAAA==.Athlantica:BAAALAAECggIEwAAAA==.',Au='Auerhahn:BAAALAADCgMIAgAAAA==.Aurinkaa:BAABLAAECoEZAAIIAAcI7Rd7ZQDwAQAIAAcI7Rd7ZQDwAQAAAA==.',Av='Avake:BAAALAADCgYIDAAAAA==.',Ba='Bacardî:BAAALAAECgYIBgAAAA==.Balendor:BAABLAAECoEbAAIIAAcIRR6KNQB0AgAIAAcIRR6KNQB0AgAAAA==.Balin:BAAALAADCgcIEgAAAA==.Balu:BAAALAAECgMIAwAAAA==.Bambula:BAAALAAECgEIAQAAAA==.Baumhirte:BAAALAADCgcIBwAAAA==.',Be='Belit:BAAALAADCggIDQAAAA==.Belmonk:BAAALAADCgcIDAABLAAECggIKQAJABseAA==.Belnas:BAABLAAECoEpAAMJAAgIGx5lIwCVAgAJAAgIGx5lIwCVAgAKAAIIKRhwbwB/AAAAAA==.Belzzebub:BAAALAAECgYICQAAAA==.Beówólf:BAAALAAECgQICwAAAA==.',Bh='Bheldur:BAABLAAECoEZAAIIAAcI4As0mwCHAQAIAAcI4As0mwCHAQAAAA==.',Bi='Bingchilling:BAAALAAECgYICAAAAA==.Bingchillíng:BAABLAAFFIEGAAIDAAIIBQ1BJQCEAAADAAIIBQ1BJQCEAAAAAA==.',Bl='Blackhack:BAAALAADCggIDgABLAAECgYICQALAAAAAA==.Blackvamp:BAAALAADCggICAAAAA==.Blaire:BAABLAAECoEeAAMEAAgI4yEXDgDmAgAEAAgIkSEXDgDmAgAMAAYI8BsqYADFAQAAAA==.Blûemoon:BAAALAAECgMICAAAAA==.',Bo='Boderrush:BAAALAADCgcIFAAAAA==.Bohnenblüte:BAABLAAECoEUAAINAAcIExT/EACJAQANAAcIExT/EACJAQAAAA==.Boombe:BAAALAADCgYIBgAAAA==.Borgosch:BAABLAAECoEhAAIGAAcIkyGQEQCCAgAGAAcIkyGQEQCCAgAAAA==.',Br='Bramgar:BAAALAAECggICAAAAA==.Brangäne:BAAALAAECgYIDwAAAA==.Bratyydk:BAABLAAECoEaAAIOAAcIDxzVEAANAgAOAAcIDxzVEAANAgAAAA==.Breezer:BAAALAADCgIIAgAAAA==.Breitwieder:BAAALAAECgQIEAAAAA==.Brotinator:BAAALAADCgYIBgABLAAECggIEgALAAAAAA==.Brummbart:BAACLAAFFIENAAIPAAYI+RCwBwC0AQAPAAYI+RCwBwC0AQAsAAQKgRgAAg8ACAgaG/wqAEACAA8ACAgaG/wqAEACAAAA.Brutan:BAAALAAECgYIEAAAAA==.',Bu='Bulldor:BAAALAAECgUIBwAAAA==.Bulwa:BAAALAADCgEIAQAAAA==.Bumblotaurus:BAAALAAECggICgAAAA==.',['Bö']='Böse:BAACLAAFFIENAAIQAAQIvwzvCwAzAQAQAAQIvwzvCwAzAQAsAAQKgRwAAxAACAhBGcoyADoCABAACAhBGcoyADoCABEABAhKCrcjAKwAAAAA.',Ca='Caldera:BAAALAADCgUIBQABLAAECgcIHAASAEATAA==.Cama:BAAALAAECgMIAwAAAA==.Camaeel:BAABLAAECoEoAAIIAAgI9BqDMQCEAgAIAAgI9BqDMQCEAgAAAA==.Captainkomo:BAAALAAECgYICQAAAA==.Capybará:BAABLAAECoEfAAITAAgIIxJqIQDxAQATAAgIIxJqIQDxAQAAAA==.Caradarac:BAABLAAECoEcAAIFAAgIxxE0UAD0AQAFAAgIxxE0UAD0AQAAAA==.Castarwoman:BAAALAAECgcIDQAAAA==.Castel:BAAALAADCggIEAAAAA==.',Ce='Celeborn:BAAALAADCggICAABLAAFFAMIDQAQADUZAA==.Celi:BAAALAADCgYIAgAAAA==.Cella:BAAALAAECgYIEwAAAA==.Celly:BAAALAADCggIFQABLAAECgYIDwALAAAAAA==.Certania:BAAALAAECgEIAQAAAA==.',Ch='Chaoswing:BAAALAAECggICAAAAA==.Chaplin:BAAALAADCggIFwAAAA==.Chawis:BAAALAAECgQIBAAAAA==.Cheax:BAAALAADCgYIBgAAAA==.Chezaron:BAAALAAECgQIDQAAAA==.Chihirte:BAAALAADCgcIDQAAAA==.Chîno:BAAALAADCggICAAAAA==.',Cl='Clairgrubê:BAAALAADCgcIBwAAAA==.',Co='Corason:BAAALAADCggIEAAAAA==.Cornholiø:BAAALAAECgYIDwAAAA==.Corpsecaller:BAAALAADCgcIBwAAAA==.Cowgomoo:BAAALAADCggICAAAAA==.Cowgummi:BAAALAADCggIGAAAAA==.',Cr='Crashshooter:BAAALAAECgYIEQAAAA==.Creon:BAABLAAECoEUAAIUAAYI+xS4LwB/AQAUAAYI+xS4LwB/AQAAAA==.Critbummbang:BAAALAADCgYIBgAAAA==.',Cu='Curley:BAABLAAECoEiAAIBAAgIFR2yHwB0AgABAAgIFR2yHwB0AgAAAA==.',['Cà']='Càrryu:BAACLAAFFIEJAAIVAAII9CbFDwDqAAAVAAII9CbFDwDqAAAsAAQKgSYAAxUACAjfJWcDAFMDABUACAjfJWcDAFMDABYABwg5GWkmACcCAAAA.',['Có']='Cónf:BAAALAAECgIIAgAAAA==.Cóòkie:BAAALAAECgQICAAAAA==.',Da='Dajin:BAABLAAECoEbAAIMAAYIBRwrYgDAAQAMAAYIBRwrYgDAAQAAAA==.Danity:BAAALAADCgUIBQAAAA==.Darkangle:BAAALAADCgcIDQAAAA==.Daroo:BAABLAAECoEjAAMMAAYIwCAUUQDtAQAMAAYIwCAUUQDtAQAEAAII6Qg5pABHAAAAAA==.Daríus:BAAALAAECgYIBwAAAA==.Dazurak:BAAALAADCgEIAQAAAA==.',Dd='Ddarkevel:BAACLAAFFIEGAAIXAAMIFBRvAwD2AAAXAAMIFBRvAwD2AAAsAAQKgSQAAxcACAg9HKQEAFECABcACAg9HKQEAFECABMABwiADlo1AGABAAAA.',De='Deadlypotato:BAAALAADCggIFwAAAA==.Deefax:BAAALAAECgIIAgAAAA==.Defqona:BAAALAAECgIIAgAAAA==.Dementor:BAAALAAECgQIBAAAAA==.Demo:BAABLAAECoErAAIYAAgIwRt1RQAoAgAYAAgIwRt1RQAoAgAAAA==.Demonperson:BAAALAAECggICAABLAAFFAMIDQAZAOoYAA==.Deplete:BAAALAAECgEIAQAAAA==.Derokan:BAABLAAECoEkAAMWAAgINSDGHABvAgAWAAgINSDGHABvAgAVAAEIUA1xogA3AAAAAA==.Desperadôs:BAAALAADCggIEQAAAA==.',Di='Dialol:BAAALAAECgYIDAAAAA==.Divesion:BAAALAADCgYIDAAAAA==.Diânâ:BAAALAAECgQIBwAAAA==.',Do='Dojoo:BAAALAAECgYIBgAAAA==.Donkkiller:BAAALAAECggIBgAAAA==.',Dr='Dragoneel:BAAALAAECgYICQABLAAECgcIGgALAAAAAQ==.Dragonine:BAAALAAECgcIEAAAAA==.Dragtor:BAABLAAECoEfAAITAAcIaxbXJADVAQATAAcIaxbXJADVAQAAAA==.Draki:BAAALAAECgYIEQAAAA==.Drhino:BAAALAADCgYIBgAAAA==.Droish:BAABLAAECoEYAAIBAAYIQRg5XgCeAQABAAYIQRg5XgCeAQAAAA==.Drops:BAABLAAECoEiAAMNAAcIqR8MCwD7AQANAAcIqR8MCwD7AQAaAAcIowaFKgD/AAABLAAECggICAALAAAAAA==.Drudlinde:BAAALAADCgEIAQAAAA==.Druidikux:BAAALAADCgcIDgAAAA==.Druídera:BAAALAADCgQIBAAAAA==.Drächerlich:BAAALAAECgQIBAAAAA==.',Du='Durzin:BAAALAAECggICAAAAA==.Dustinhunt:BAAALAADCggICAAAAA==.',['Dá']='Dárkness:BAACLAAFFIEFAAMVAAIIhhNbIgCUAAAVAAIIhhNbIgCUAAAWAAEIcRW8IQBPAAAsAAQKgSUAAxUABwhOHEIqACACABUABwhOHEIqACACABYABwh3GbEqAA0CAAAA.',Ec='Eclipsê:BAAALAAECgMIAwABLAAECggIFAAbAKAYAA==.',Ed='Edineu:BAAALAAECgYIEgAAAA==.Eduardpipi:BAABLAAECoEXAAMVAAYIaCHIKAAnAgAVAAYIaCHIKAAnAgAWAAEIchwEgQBUAAAAAA==.',El='Eladrake:BAAALAADCgcICwAAAA==.Eld:BAAALAADCgcIFAAAAA==.Eldahir:BAABLAAECoEVAAMaAAcIXhbYFwDAAQAaAAcIXhbYFwDAAQADAAYIYxTGUABoAQAAAA==.Elfrida:BAAALAADCggIDwAAAA==.Elling:BAABLAAECoEfAAIaAAcIkxviEQAMAgAaAAcIkxviEQAMAgAAAA==.Elna:BAAALAADCgMIBAAAAA==.Elrôs:BAAALAAECgcIEgAAAA==.',Em='Emilein:BAAALAAECgQICwAAAA==.Emptymage:BAAALAADCgQIBAAAAA==.',Er='Erbiene:BAAALAADCgcIBwAAAA==.Erdala:BAABLAAECoEXAAIcAAcIfCIpBgCbAgAcAAcIfCIpBgCbAgAAAA==.Erdbert:BAABLAAECoEaAAIBAAgIwRTJSADaAQABAAgIwRTJSADaAQAAAA==.Erdling:BAAALAAECgMIAwAAAA==.Erdnuckel:BAAALAAECgcIDgAAAA==.Erdnupsi:BAAALAAECgYIBgABLAAECgcIDgALAAAAAA==.Erik:BAABLAAECoEnAAIIAAgIKwlt0AAnAQAIAAgIKwlt0AAnAQAAAA==.Erina:BAAALAAECgYIBgAAAA==.',Es='Escand:BAAALAADCgUIBQAAAA==.',Eu='Eurybia:BAABLAAECoEfAAIdAAcI4h1eFABIAgAdAAcI4h1eFABIAgAAAA==.',Ew='Ewoker:BAABLAAECoEgAAMTAAgIihlPFQBmAgATAAgIihlPFQBmAgAeAAcIGAg4IwAOAQAAAA==.',Ex='Executie:BAAALAAECgIIAwAAAA==.Exios:BAAALAADCgIIAgAAAA==.',Ey='Eyebeamkid:BAAALAADCgUIBQAAAA==.',Fa='Fahy:BAAALAAECgcIEgAAAA==.Falamira:BAAALAAECgYICgAAAA==.Faneromeni:BAABLAAECoEcAAIIAAcIAxSWbgDcAQAIAAcIAxSWbgDcAQAAAA==.Fantanix:BAAALAADCgUIBQAAAA==.Faziclap:BAAALAAECggIDwAAAA==.Fazihuntahh:BAAALAADCgcIBwAAAA==.',Fe='Fenriswolff:BAABLAAECoEkAAISAAcIPR2CEgA9AgASAAcIPR2CEgA9AgAAAA==.',Fi='Filron:BAAALAAECgUICAAAAA==.Findalí:BAAALAADCggICAAAAA==.Fipya:BAAALAAECgYICgAAAA==.',Fl='Flidhais:BAAALAADCgMIAwAAAA==.Flippie:BAAALAADCgUIBQAAAA==.Fluchbobby:BAAALAADCggICAABLAADCggIGgALAAAAAA==.Flummí:BAAALAADCgUIBQAAAA==.',Fr='Frijda:BAABLAAECoEVAAIPAAYIpQnFbQA4AQAPAAYIpQnFbQA4AQABLAAECggIHQAWAFQXAA==.Frostîtude:BAAALAADCgUIBAAAAA==.Frín:BAAALAADCggICAAAAA==.Frów:BAAALAADCgcIBwAAAA==.',Fu='Fujiisk:BAABLAAECoEWAAIdAAcIMBj6HQDhAQAdAAcIMBj6HQDhAQAAAA==.',['Fä']='Färón:BAAALAAECgQIDgAAAA==.Färôn:BAAALAADCgcIBwAAAA==.',['Fö']='Föö:BAAALAADCggIDgAAAA==.',['Fø']='Førbes:BAABLAAECoEcAAIQAAcIfiHgHwCkAgAQAAcIfiHgHwCkAgAAAA==.',Ga='Galarak:BAAALAADCgcIAwAAAA==.Gallico:BAABLAAECoEZAAIDAAYIayBJJQAoAgADAAYIayBJJQAoAgAAAA==.Gasuna:BAABLAAECoEfAAICAAcInwpbKQAhAQACAAcInwpbKQAhAQAAAA==.',Ge='Geesina:BAAALAAECgYIBgAAAA==.',Gi='Giftrose:BAACLAAFFIEGAAIBAAIIgwNmSQBcAAABAAIIgwNmSQBcAAAsAAQKgSoAAgEACAh9ErdQAMMBAAEACAh9ErdQAMMBAAAA.',Gl='Glondo:BAABLAAECoEaAAMPAAcIIxTZQwDKAQAPAAcIIxTZQwDKAQABAAcIQQbW0wCiAAAAAA==.',Gn='Gnomlie:BAABLAAECoEfAAIQAAgI5Rw+IwCOAgAQAAgI5Rw+IwCOAgAAAA==.Gnomliehood:BAAALAAECgMIBQABLAAECggIHwAQAOUcAA==.',Go='Goldelf:BAAALAADCggICAAAAA==.Gomli:BAABLAAECoEXAAIBAAcIRB2BLgA0AgABAAcIRB2BLgA0AgAAAA==.Gorkaorka:BAABLAAECoEmAAIMAAgI7COpEAABAwAMAAgI7COpEAABAwAAAA==.Gossanor:BAAALAAECgQIBgAAAA==.Gozu:BAABLAAECoEWAAIbAAcIrg/jKQC/AQAbAAcIrg/jKQC/AQAAAA==.',Gr='Grano:BAAALAAECggICQAAAA==.Greefãx:BAABLAAECoEpAAMMAAgIiSKTFgDdAgAMAAgIiSKTFgDdAgAEAAEIHhmvqwA2AAAAAA==.Grimhorn:BAAALAADCggIDgAAAA==.Groka:BAABLAAECoEmAAIQAAgIQiGhGQDOAgAQAAgIQiGhGQDOAgAAAA==.Grood:BAABLAAECoElAAMfAAcIIBLuFwAqAQAJAAcIIBIyXQClAQAfAAYIRQfuFwAqAQAAAA==.Grâul:BAAALAADCgcIBwAAAA==.',Gu='Guccibird:BAAALAADCgIIAgAAAA==.Guccigesicht:BAAALAAECgYIBgAAAA==.Guenji:BAAALAAECgIIBAABLAAECgYIEAALAAAAAA==.Gutwúrz:BAABLAAECoEbAAIGAAgIKRUmIAD8AQAGAAgIKRUmIAD8AQAAAA==.',Gw='Gwenyth:BAAALAAECgIIAgAAAA==.',['Gî']='Gîlgamesh:BAAALAAECgcICwABLAAECggIIwALAAAAAQ==.',['Gü']='Günterheal:BAAALAAECgYIBgAAAA==.',Ha='Hallie:BAAALAADCgcIDQAAAA==.Hanime:BAAALAAECggIEwAAAA==.Happyaua:BAAALAADCggIEgAAAA==.Hardwing:BAAALAAECgIIBQAAAA==.Hargorina:BAAALAADCgUIBgAAAA==.Harmy:BAAALAAECgUIEQAAAA==.Hartley:BAAALAAECggIAQAAAA==.Haskeér:BAAALAAECgYIDgAAAA==.Hasuolos:BAAALAAECgIIAgAAAA==.Hawaron:BAAALAAECgYIBgABLAAECgcIIgAgAAsgAA==.Haìley:BAABLAAECoEaAAMhAAgIHhy6FQCQAgAhAAgIHhy6FQCQAgANAAIIMgAAAAAAAAAAAA==.',He='Healwoo:BAAALAADCggICgABLAAECgQIBQALAAAAAA==.Hellami:BAAALAADCgEIAQAAAA==.',Hi='Hinjjaa:BAAALAAECgIIAgAAAA==.Hinotamâ:BAABLAAECoEcAAMKAAcIqhNJLACgAQAJAAcIIBDAXACmAQAKAAcIQg9JLACgAQAAAA==.Hinrich:BAAALAAECggIDgAAAA==.',Hj='Hjaldrig:BAABLAAECoEdAAIQAAcIHR4ALwBMAgAQAAcIHR4ALwBMAgAAAA==.',Ho='Hofiaimedyou:BAAALAADCgYIBgAAAA==.Hofiisblind:BAAALAADCgYIBgAAAA==.Holymayo:BAAALAADCggICAABLAAFFAMICgAhAO8ZAA==.Holypaly:BAAALAADCgcIBwAAAA==.Hordak:BAAALAADCggIEQAAAA==.Hoyo:BAAALAAECgYIDAAAAA==.',['Hæ']='Hæntai:BAAALAADCgIIAgAAAA==.',['Hé']='Hérá:BAABLAAECoEvAAIVAAgIVSQiCQARAwAVAAgIVSQiCQARAwAAAA==.',['Hö']='Höllschlag:BAAALAAECgIIAgAAAA==.',Ic='Icecloud:BAAALAADCgcIBwAAAA==.',Id='Idç:BAAALAADCgIIAgAAAA==.',Il='Iluvbobz:BAABLAAECoEaAAIBAAcISx1DMQAqAgABAAcISx1DMQAqAgAAAA==.',Im='Imbric:BAAALAADCggIEAAAAA==.Imhotêp:BAABLAAECoEVAAMMAAgIEhqdUwDmAQAMAAcIgx2dUwDmAQAiAAEIAQLIIgAHAAABLAAFFAUIDgAgAMITAA==.Imhôtep:BAABLAAECoEVAAIJAAgI3Rd/LABkAgAJAAgI3Rd/LABkAgABLAAFFAUIDgAgAMITAA==.Immorí:BAAALAADCgcIDgABLAADCggIDQALAAAAAA==.',In='Inaevar:BAACLAAFFIESAAIWAAYIbBStAwAFAgAWAAYIbBStAwAFAgAsAAQKgSgAAhYACAhFJFMGAD8DABYACAhFJFMGAD8DAAAA.Induriel:BAAALAAECgYIEAAAAA==.Inférno:BAAALAAECgIIAgAAAA==.',Ir='Irdenerwoo:BAABLAAECoEUAAIJAAcIYBkjPwAOAgAJAAcIYBkjPwAOAgAAAA==.Irrefix:BAABLAAECoEXAAIUAAcIpxNjKACrAQAUAAcIpxNjKACrAQAAAA==.',Is='Isabélla:BAAALAADCgcIBQAAAA==.Islanzadi:BAACLAAFFIEIAAIhAAMIxQ4/DQDIAAAhAAMIxQ4/DQDIAAAsAAQKgTEAAiEACAgmIVwPANQCACEACAgmIVwPANQCAAAA.Islanzhadi:BAABLAAECoEcAAMBAAcIPRphQwDrAQABAAcIPRphQwDrAQAPAAQIAAduiADAAAAAAA==.',Iv='Ivenhow:BAABLAAECoErAAIIAAgITyNKIADRAgAIAAgITyNKIADRAgAAAA==.',Ja='Jackrum:BAAALAAECgcIDQAAAA==.Jarnunvösk:BAAALAADCggIDQABLAAFFAMICAAhAMUOAA==.',Je='Jenjen:BAAALAADCggIEAAAAA==.Jennika:BAACLAAFFIEKAAMjAAMIEghHCADSAAAjAAMIEghHCADSAAAkAAII/gCGBQBMAAAsAAQKgS8ABCMACAiRGxEKAHgCACMACAhIGhEKAHgCACQACAhqFy4GAC8CABsAAQiGB0FkADoAAAAA.Jenora:BAABLAAECoEaAAIbAAYInRiuKQDAAQAbAAYInRiuKQDAAQAAAA==.Jetrascha:BAAALAAECgYIEwAAAA==.',Ji='Jigger:BAAALAADCggIDQAAAA==.',Jo='Johhn:BAABLAAECoEUAAIVAAYIHQStegDfAAAVAAYIHQStegDfAAAAAA==.Jolorika:BAAALAAECgYIDwAAAA==.Joschie:BAAALAAECgcIEwAAAA==.',Jr='Jrz:BAABLAAECoEZAAIVAAYIHQgXcAAFAQAVAAYIHQgXcAAFAQAAAA==.',Ju='Jupîter:BAAALAAECgIIAgAAAA==.',Jx='Jxlxxnh:BAAALAADCgEIAQABLAADCgcICAALAAAAAA==.',['Jä']='Jägashy:BAAALAADCgUIBQAAAA==.',Ka='Kafina:BAAALAAECgYIBgAAAA==.Kaiht:BAABLAAECoEXAAIeAAcIFRM0FgCjAQAeAAcIFRM0FgCjAQAAAA==.Kalashnikôv:BAAALAAECggICAAAAA==.Kaldori:BAAALAAECgYIEwAAAA==.Kaletia:BAAALAADCgcIBwAAAA==.Kampfbolzen:BAAALAADCggICQAAAA==.Kaneda:BAABLAAECoEeAAIdAAcIDRe5HADsAQAdAAcIDRe5HADsAQAAAA==.Kany:BAAALAAECggIDgAAAA==.Kaos:BAABLAAECoEYAAIDAAgIZA+fRACWAQADAAgIZA+fRACWAQAAAA==.Karendavid:BAAALAAECgMIBAAAAA==.Karldrogu:BAAALAADCgcIBwAAAA==.Kasteil:BAAALAADCggICAAAAA==.',Ke='Kennstermnet:BAAALAAECgIIAgAAAA==.Kennstermnid:BAAALAAECgIIAgAAAA==.Kennstermnit:BAAALAADCgYIBgAAAA==.',Kh='Khami:BAABLAAECoEWAAIWAAcI3BXhLwDvAQAWAAcI3BXhLwDvAQAAAA==.',Ki='Kialandies:BAAALAADCgcICgAAAA==.Kibori:BAABLAAECoEnAAITAAgIzA/0JQDMAQATAAgIzA/0JQDMAQAAAA==.',Kn='Knarr:BAABLAAECoEZAAMQAAcIsRIXVAC9AQAQAAcITRIXVAC9AQAGAAQIZQ15WQDAAAAAAA==.Knarrenonkel:BAAALAADCggIGgAAAA==.Knigge:BAABLAAECoEXAAIMAAgIXCCbJwCAAgAMAAgIXCCbJwCAAgABLAAFFAIICAAPAPEUAA==.Kniggecode:BAACLAAFFIEGAAIJAAIIlBF2LACYAAAJAAIIlBF2LACYAAAsAAQKgRUAAgkACAjoF9gtAF4CAAkACAjoF9gtAF4CAAEsAAUUAggIAA8A8RQA.Kniggonaut:BAACLAAFFIEIAAIPAAII8RQ8HACbAAAPAAII8RQ8HACbAAAsAAQKgRgAAg8ACAjCG5opAEgCAA8ACAjCG5opAEgCAAAA.Knightsabre:BAAALAAECgQIBgAAAA==.',Ko='Kobi:BAAALAADCgcIBwAAAA==.Kobì:BAAALAAECgMIBgAAAA==.Kojo:BAAALAAECgIIAgAAAA==.',Kp='Kpipo:BAAALAAECgQIEAAAAA==.',Kr='Kriegen:BAAALAAECgEIAQAAAA==.Kriegeruel:BAAALAADCggICAABLAAECggIFQAlAJwfAA==.Kritoss:BAAALAAFFAIIAgAAAA==.Krolas:BAABLAAECoEWAAIMAAcIpAsYngBDAQAMAAcIpAsYngBDAQAAAA==.Krolya:BAABLAAECoEUAAIHAAcImRJeigCuAQAHAAcImRJeigCuAQAAAA==.Kryostase:BAAALAADCgcIDQAAAA==.',Ku='Kumos:BAAALAADCgYICwAAAA==.Kuniglunde:BAABLAAECoEYAAIBAAgIyx1hGACdAgABAAgIyx1hGACdAgAAAA==.Kurj:BAABLAAECoEWAAIbAAcIlgsJMgCOAQAbAAcIlgsJMgCOAQAAAA==.Kurô:BAABLAAECoETAAIaAAgIISCJBQD0AgAaAAgIISCJBQD0AgAAAA==.',Ky='Kyleigh:BAAALAAECgYIEgABLAAECggIJgAPAG4gAA==.Kyora:BAAALAADCggIMAAAAA==.',La='Lacri:BAAALAAECgMIAwAAAA==.Lagavulin:BAAALAAECggICwAAAA==.Lahrom:BAAALAADCggIDwAAAA==.Laiel:BAAALAAECgMIBQAAAA==.Langoriâ:BAAALAAECgIIAgAAAA==.Larania:BAABLAAECoEYAAIBAAcIohhXdABkAQABAAcIohhXdABkAQAAAA==.',Le='Leandra:BAABLAAECoEcAAIDAAcI7BkBLgD8AQADAAcI7BkBLgD8AQAAAA==.Leviathan:BAABLAAECoEUAAIQAAgI4yNGCABJAwAQAAgI4yNGCABJAwAAAA==.',Li='Lichthirte:BAABLAAECoEhAAIIAAcIGSDzOABoAgAIAAcIGSDzOABoAgAAAA==.Liezzy:BAABLAAECoElAAIVAAgITxkAIABcAgAVAAgITxkAIABcAgAAAA==.Lilith:BAAALAAECgMIBgABLAAECgcIHAABAD0aAA==.',Lo='Lockutus:BAAALAAECggICwAAAA==.Lockè:BAAALAAECggIAQAAAA==.Lonlyheart:BAAALAAECgMICAAAAA==.Louboutin:BAAALAAECggIDAAAAA==.Louisa:BAABLAAECoElAAIfAAgI7BUHBwBAAgAfAAgI7BUHBwBAAgAAAA==.',Lu='Luluchen:BAABLAAECoEWAAMEAAYIPQuxZwAKAQAEAAYIPQuxZwAKAQAMAAEICgE6KAEQAAAAAA==.Lululicious:BAABLAAECoEXAAMEAAgIghy+GwBxAgAEAAgIghy+GwBxAgAMAAMIcQh++gBoAAAAAA==.Luzifêr:BAAALAAECgcIDgABLAAFFAUIDgAgAMITAA==.',Ly='Lydara:BAAALAAECgQIEAAAAA==.Lydith:BAABLAAECoEXAAIMAAgIsBaFSQACAgAMAAgIsBaFSQACAgAAAA==.Lynquay:BAAALAADCgMIAwAAAA==.Lyoama:BAAALAAECgMIAwAAAA==.Lysannaja:BAAALAADCgcIBwAAAA==.Lyyn:BAAALAAECggICgAAAA==.',['Lé']='Léándrâ:BAAALAAECgMIBQAAAA==.',Ma='Madrikor:BAAALAAECgYIBgAAAA==.Maeenae:BAAALAAECgYIDAAAAA==.Maerlon:BAAALAAECgMIBQABLAAECgcIFQAaAF4WAA==.Malgorzata:BAAALAAECgIIAgAAAA==.Malvdred:BAAALAADCgcIBwAAAA==.Malvi:BAABLAAECoEkAAMdAAcIZh7nFABCAgAdAAcIZh7nFABCAgAmAAcIewoXJQAxAQAAAA==.Malwi:BAAALAADCgcIEQAAAA==.Mangoh:BAAALAADCgUIBQAAAA==.Maraseed:BAABLAAECoEfAAIVAAcIeCIHFgCgAgAVAAcIeCIHFgCgAgAAAA==.Marfa:BAAALAADCgEIAQAAAA==.Markuss:BAAALAAECgMIBAAAAA==.Mattilde:BAABLAAECoEZAAIKAAYIiAmAQABJAQAKAAYIiAmAQABJAQAAAA==.Mayopumpapum:BAACLAAFFIEKAAIhAAMI7xlnCQAGAQAhAAMI7xlnCQAGAQAsAAQKgSgAAiEACAi9I/MGADUDACEACAi9I/MGADUDAAAA.',Mb='Mb:BAAALAADCgIIAgAAAA==.',Me='Meera:BAAALAADCgIIAgAAAA==.Meg:BAAALAADCgcIFAAAAA==.Melahunter:BAAALAAECggICAAAAA==.Melampous:BAAALAAECggIBgAAAA==.Melapriest:BAAALAADCggICAAAAA==.Melirella:BAABLAAECoEXAAIJAAYILAj7jAAkAQAJAAYILAj7jAAkAQAAAA==.Mellchior:BAAALAADCgcIEgAAAA==.Melíandra:BAABLAAECoEYAAIJAAcIzQ1EZQCNAQAJAAcIzQ1EZQCNAQAAAA==.Memyselfandi:BAAALAAECgIIAgABLAAECgcIDgALAAAAAA==.Menaxita:BAAALAADCgcIBwAAAA==.Menaxxi:BAAALAAECgYICwAAAA==.Menoxito:BAABLAAECoEhAAMhAAgI5ROxJwADAgAhAAgI5ROxJwADAgADAAEIRAAkzAACAAAAAA==.Menáxi:BAAALAAECgYIBgAAAA==.Meracus:BAABLAAECoEmAAIeAAgILg+PFQCrAQAeAAgILg+PFQCrAQAAAA==.Meyina:BAAALAAECgMIAwAAAA==.Meîmei:BAAALAADCgMIAQAAAA==.',Mh='Mhs:BAAALAADCgYIBgAAAA==.',Mi='Miesmûschel:BAAALAADCgcIDgAAAA==.Mihodh:BAABLAAECoEcAAIZAAcI2iE2CQCkAgAZAAcI2iE2CQCkAgAAAA==.Mihodk:BAAALAAECgIIAgAAAA==.Mirabeladin:BAAALAADCggIEwAAAA==.Misseia:BAABLAAECoEbAAIBAAgINCAFEQDMAgABAAgINCAFEQDMAgAAAA==.Misstjara:BAAALAAECgYICQAAAA==.Missyuki:BAAALAADCgIIAgAAAA==.',Mo='Monsieurfoox:BAAALAAECgcICwAAAA==.Morkan:BAAALAAECgQICQAAAA==.Mosh:BAAALAAECgIIAgAAAA==.',Mu='Mugén:BAAALAAECgYIEwAAAA==.Mukuro:BAAALAADCggIEAAAAA==.Muzzarella:BAAALAADCgQIBAAAAA==.',['Mâ']='Mâdmartigan:BAAALAAECgIIBQAAAA==.Mâldânîus:BAAALAAECggIEgAAAA==.Mâlefic:BAAALAAECgYIEwAAAA==.Mângo:BAABLAAECoEcAAIFAAgIvyJwFAD6AgAFAAgIvyJwFAD6AgAAAA==.',['Mî']='Mîho:BAAALAADCggICAAAAA==.',Na='Nacotic:BAAALAAECggIEwAAAA==.Nacoya:BAAALAAECgcICgAAAA==.Nagulander:BAAALAAECgUICwAAAA==.Nallum:BAAALAAECgQICgAAAA==.Namînê:BAAALAAECgUIBQAAAA==.Nandoriel:BAABLAAECoEZAAINAAcIwiWuAgAGAwANAAcIwiWuAgAGAwAAAA==.Nanyala:BAAALAAECgMICAAAAA==.Nastya:BAAALAADCgMIAwAAAA==.',Ne='Necessaryevl:BAABLAAECoEmAAIZAAgIhBf6FwDUAQAZAAgIhBf6FwDUAQAAAA==.Nerevar:BAABLAAECoEhAAIhAAgISCENDwDXAgAhAAgISCENDwDXAgAAAA==.',Ni='Nijusan:BAABLAAECoEaAAIlAAcIExkoGwAcAgAlAAcIExkoGwAcAgAAAA==.',No='Notarzt:BAAALAADCgIIAwABLAAECggIEwALAAAAAA==.Noxera:BAAALAAECgYIEAAAAA==.',['Nâ']='Nâmîne:BAABLAAECoEjAAImAAcIVh+lCwB4AgAmAAcIVh+lCwB4AgAAAA==.',Ob='Obsidia:BAAALAAECgEIAQAAAA==.',Oc='Octaniaa:BAAALAAECgYIDAAAAA==.',Oh='Ohhermann:BAABLAAECoEdAAIWAAgIVBeKIABRAgAWAAgIVBeKIABRAgAAAA==.Ohmén:BAAALAAECgMICgAAAA==.',Ol='Olalo:BAAALAADCggIEAAAAA==.',On='Onkeltotem:BAABLAAECoEpAAMBAAcI5BkfQQDzAQABAAcI5BkfQQDzAQAPAAcIABX3RgC+AQAAAA==.',Pa='Palabum:BAAALAAECggICAAAAA==.Paladinwoo:BAAALAAECgQIBQAAAA==.Palladon:BAAALAAECgYIDwAAAA==.Papungo:BAABLAAECoEiAAIWAAgIcB3gEwC6AgAWAAgIcB3gEwC6AgAAAA==.',Pe='Percivâl:BAAALAAECggICAAAAA==.',Ph='Phatne:BAAALAADCgEIAQAAAA==.Phíola:BAABLAAECoEcAAIFAAgI/hjhNgBRAgAFAAgI/hjhNgBRAgAAAA==.',Pl='Plisanator:BAAALAADCgEIAQAAAA==.',Pr='Primse:BAAALAADCgMIAwAAAA==.Prowin:BAAALAADCggIGgAAAA==.Prüsselliese:BAAALAADCgQIBAAAAA==.',Py='Pyrella:BAAALAADCggICAAAAA==.',['Pá']='Pán:BAABLAAECoEfAAIDAAgI3RiIJAArAgADAAgI3RiIJAArAgAAAA==.',['Pî']='Pîkû:BAAALAADCgIIAgAAAA==.Pînot:BAABLAAECoEoAAIVAAcIxCSTDwDVAgAVAAcIxCSTDwDVAgAAAA==.',['Pö']='Pöserpube:BAAALAAECgUIBgAAAA==.',Qw='Qwed:BAABLAAECoEaAAIlAAgInQ0vLACqAQAlAAgInQ0vLACqAQAAAA==.',Ra='Ragosh:BAABLAAECoEZAAIDAAcI7hFgSQCDAQADAAcI7hFgSQCDAQAAAA==.Raika:BAAALAADCggIGAAAAA==.Raisu:BAAALAAECgQIBAAAAA==.Ramini:BAAALAADCggIEQAAAA==.Rangandi:BAABLAAECoEUAAIJAAYI9Rq/TADaAQAJAAYI9Rq/TADaAQABLAAECggIIQAhAEghAA==.Rasiok:BAAALAADCggIAQAAAA==.Ratatosk:BAAALAAECgEIAQAAAA==.Raíz:BAAALAADCgQIBAABLAAECgYIEwALAAAAAA==.',Re='Reflex:BAAALAAECgcIEQAAAA==.Rekz:BAABLAAECoEYAAIHAAYIjRE+ugBeAQAHAAYIjRE+ugBeAQAAAA==.Renemusprime:BAAALAAECgIIAgAAAA==.Renfi:BAAALAADCgcIAQAAAA==.Renna:BAAALAADCggICAAAAA==.Reorx:BAABLAAECoEWAAIIAAgIagV05AD8AAAIAAgIagV05AD8AAAAAA==.',Ri='Riö:BAAALAADCggICAAAAA==.',Ro='Rombosch:BAAALAADCgcIFAAAAA==.Rorey:BAAALAADCgcIBwAAAA==.Roy:BAABLAAECoEbAAIaAAcIgQmYIQBbAQAaAAcIgQmYIQBbAQAAAA==.',Ru='Rufuss:BAAALAAECggIDQAAAA==.',Ry='Rygor:BAAALAADCggIFAAAAA==.',['Rà']='Ràven:BAAALAAECgYIEgAAAA==.',['Râ']='Râgnarôk:BAAALAAECggIEAABLAAECggIEgALAAAAAA==.',['Rè']='Rèbécca:BAAALAAECgYIBgAAAA==.',['Rí']='Ríccardø:BAAALAAECgEIAQAAAA==.',Sa='Saintnephis:BAAALAADCgUIBwAAAA==.Salzbaron:BAAALAAECgEIAgAAAA==.Samaryl:BAABLAAECoEVAAIWAAgIMRc5OwCxAQAWAAgIMRc5OwCxAQAAAA==.Samyrá:BAABLAAECoEUAAIVAAYITBEqXABFAQAVAAYITBEqXABFAQAAAA==.Sanndur:BAABLAAECoEcAAISAAcIQBP7JACXAQASAAcIQBP7JACXAQAAAA==.Saphiira:BAAALAAECgYICAAAAA==.Sauerstøff:BAABLAAECoEgAAIhAAgIdA6UNwCtAQAhAAgIdA6UNwCtAQAAAA==.Saxen:BAAALAAECgEIAQABLAAECgcIHAASAEATAA==.Saÿa:BAAALAADCggICAABLAAECgUICwALAAAAAA==.',Sc='Schabraty:BAAALAAECgQIBAAAAA==.Schamikel:BAAALAADCgMIAwABLAAECgcIEgALAAAAAA==.Schauni:BAAALAADCgcIFAAAAA==.Schein:BAAALAAECgMIDgAAAA==.Schenlongo:BAAALAADCggICwAAAA==.Schmôggi:BAAALAADCggICQAAAA==.Schüppi:BAACLAAFFIENAAIQAAMINRlIEAAAAQAQAAMINRlIEAAAAQAsAAQKgSwAAhAACAg7JIIKADkDABAACAg7JIIKADkDAAAA.Schüppidk:BAAALAADCgYIBgABLAAFFAMIDQAQADUZAA==.',Se='Seahawk:BAAALAADCgUIBQAAAA==.Sealgaire:BAAALAAECgYIDwAAAA==.Sean:BAABLAAECoEUAAInAAgIaBsoBAB7AgAnAAgIaBsoBAB7AgAAAA==.Sedryn:BAAALAAECgYIEgAAAA==.Seishu:BAAALAAECgcIDgAAAA==.Senestri:BAAALAADCgYIBgAAAA==.Serafira:BAAALAAECgIIAgAAAA==.Serrás:BAAALAAECgYIDQAAAA==.Seshas:BAABLAAECoEYAAIVAAcI7Q3EUQBrAQAVAAcI7Q3EUQBrAQAAAA==.',Sh='Shaaní:BAAALAAECgEIAQAAAA==.Shadowbeast:BAAALAAECgYIEAAAAA==.Shadowlight:BAAALAAECgYIEgAAAA==.Shadowpilz:BAAALAAECgYIDgAAAA==.Shalara:BAABLAAECoEbAAIWAAgIWh/OFwCYAgAWAAgIWh/OFwCYAgABLAAECggIEwAaACEgAA==.Sharendra:BAAALAAECgIIAwAAAA==.Shaýla:BAAALAADCggIDgAAAA==.Sheenpala:BAABLAAECoEqAAIIAAgIKh5cRwA8AgAIAAgIKh5cRwA8AgAAAA==.Sheriva:BAAALAAECgQIBQAAAA==.Shiris:BAAALAADCgUIBwAAAA==.Shizam:BAAALAADCggIFgAAAA==.Shmebulock:BAAALAADCggICAAAAA==.Shushuna:BAAALAAECggICAAAAA==.Shádow:BAAALAAECgYIDQAAAA==.',Si='Sidonía:BAABLAAECoEUAAIJAAcIGg7NaQCBAQAJAAcIGg7NaQCBAQAAAA==.Silverclaw:BAAALAADCggIIAAAAA==.Silvereyes:BAAALAAECgYICAAAAA==.Sixshido:BAAALAADCggIDgAAAA==.',Sk='Skarb:BAAALAADCggICAAAAA==.Skarbo:BAAALAADCgUIBQAAAA==.Skofnar:BAAALAAECgEIAQABLAAECggIEwAaACEgAA==.Skon:BAAALAADCgEIAQAAAA==.Skylar:BAAALAADCggICAAAAA==.Skylarr:BAAALAAECggIEAAAAA==.Skyra:BAAALAADCggIEAAAAA==.Skár:BAABLAAECoEiAAMBAAgIbBraJgBUAgABAAgIbBraJgBUAgAPAAIIHQ6vlwB7AAAAAA==.',Sm='Smogii:BAACLAAFFIEGAAIFAAII8h+WIgC/AAAFAAII8h+WIgC/AAAsAAQKgSYAAgUACAiFJP0RAAgDAAUACAiFJP0RAAgDAAAA.',Sn='Sniezka:BAAALAAECgUIDgAAAA==.Snowie:BAAALAADCggIBQAAAA==.Snowtrasza:BAAALAAECgcICAAAAA==.Snâg:BAAALAAECgUIBQABLAAECggIKQAJABseAA==.',So='Socram:BAAALAAECgIIBQAAAA==.Sonnenritter:BAAALAAECgYIBwAAAA==.Sonofnature:BAAALAAECgcIDQAAAA==.',Sp='Spinatstrudl:BAAALAADCggIEAAAAA==.',Ss='Ssick:BAAALAAECgEIAQAAAA==.',St='Stahlbárt:BAAALAAECggIBgAAAA==.Stamos:BAAALAAECgYIEAAAAA==.Steelwarrior:BAAALAAECgcIGgAAAQ==.Stonegurd:BAAALAADCggICAAAAA==.Stormdragon:BAAALAAECgQIEAAAAA==.Stormranger:BAAALAAFFAIIAgAAAA==.Stroke:BAAALAADCgEIAQAAAA==.',Su='Sulamith:BAAALAADCgQIBAAAAA==.Sundiego:BAAALAADCgIIAgAAAA==.',Sy='Sydba:BAAALAADCggIDwAAAA==.Sydrina:BAAALAADCgYIBgABLAAECgcIGgAPACMUAA==.Sylvestere:BAAALAADCggIDQAAAA==.Sylêr:BAAALAAECggIEAAAAA==.',['Sà']='Sàmirá:BAAALAAECgYIBgAAAA==.',['Sì']='Sìxtynine:BAAALAADCgcIDQABLAAECgcIHwABAF4fAA==.',['Só']='Sóngoku:BAAALAAECgcICAABLAAFFAIICQAVAPQmAA==.',Ta='Taloe:BAAALAAECgYIBgAAAA==.Tatsue:BAAALAAECgcIDgAAAA==.Tavlin:BAABLAAECoEUAAInAAgIKxRSCQDvAQAnAAgIKxRSCQDvAQAAAA==.',Te='Teeshâ:BAAALAAECgQIBwAAAA==.Tenten:BAABLAAECoErAAIbAAgIFQ8VJQDeAQAbAAgIFQ8VJQDeAQAAAA==.Terenna:BAAALAAECgMIAwABLAAECgcIIQAGAJMhAA==.Teth:BAABLAAECoEcAAIMAAcIvSMWGgDJAgAMAAcIvSMWGgDJAgAAAA==.',Th='Thallim:BAAALAAECgQIEAAAAA==.Tharnak:BAAALAADCgYIEQAAAA==.Thebigbait:BAAALAADCggICAABLAAECggIFQAlAJwfAA==.Thebigmage:BAABLAAECoEVAAMlAAgInB+ZCwDGAgAlAAgInB+ZCwDGAgAFAAIIoBYlygByAAAAAA==.Thorbadin:BAAALAAECggICgAAAA==.Thorodos:BAAALAAECgEIAQAAAA==.Thrahell:BAAALAAECggIEAAAAA==.Thranduril:BAAALAADCgcIBwAAAA==.Thrunk:BAAALAADCgMIAwAAAA==.Thunderpi:BAAALAAECgcIBwAAAA==.Thyran:BAAALAAECgIIAgABLAAECggIEwALAAAAAA==.Théséus:BAAALAADCggIEAABLAAECgcIGgALAAAAAQ==.Thúnder:BAACLAAFFIELAAMPAAMI2RZGDwD7AAAPAAMI2RZGDwD7AAABAAMIyB7JHwClAAAsAAQKgSgAAw8ACAhzH9YTAN0CAA8ACAhzH9YTAN0CAAEAAgiUDAAAAAAAAAAA.',Ti='Tiwalun:BAABLAAECoEXAAIaAAcIKw5RHACQAQAaAAcIKw5RHACQAQAAAA==.',To='Tohrim:BAAALAADCggICAABLAAECggIKAAIAPQaAA==.Toki:BAAALAAECgMIAwAAAA==.Toph:BAABLAAECoEmAAIPAAgIbiCLDgAJAwAPAAgIbiCLDgAJAwAAAA==.Torihl:BAAALAAECgYIDAAAAA==.Tortilla:BAAALAADCgYIBgAAAA==.Totemhirte:BAAALAADCggIDwAAAA==.Toukâ:BAAALAADCgIIAgABLAAECggIEwAaACEgAA==.',Tr='Traumjägér:BAAALAAECgMIBAAAAA==.Trollvader:BAAALAAECgYIBgAAAA==.',Tu='Tuladra:BAAALAAECgYIEgABLAAECggIEwALAAAAAA==.Turá:BAAALAADCggICAAAAA==.',Ty='Tyrosa:BAABLAAECoEoAAIMAAgIrRsQNQBIAgAMAAgIrRsQNQBIAgAAAA==.',['Tâ']='Tâmâr:BAAALAAECgYIBgAAAA==.',Un='Unberechenba:BAAALAADCgcIBwAAAA==.',Va='Valareen:BAAALAADCggICgABLAAECggIEgALAAAAAA==.Valenzi:BAAALAAECggICAAAAA==.Valeryias:BAAALAADCgcIBAABLAAECggIEwAaACEgAA==.Valkstaff:BAAALAAECgEIAQAAAA==.Valtiel:BAAALAAECgYIDwAAAA==.Vanhexing:BAAALAAECgEIAQAAAA==.Vanyas:BAABLAAECoEYAAIPAAYIZA9WZgBSAQAPAAYIZA9WZgBSAQAAAA==.Vardâ:BAAALAAECgcIEAAAAA==.Varionz:BAAALAAECgYICgAAAA==.Vaxall:BAAALAADCggICAAAAA==.',Ve='Veanwe:BAAALAAECgMIBgAAAA==.Velicia:BAABLAAECoEXAAICAAgIPhhnEAA8AgACAAgIPhhnEAA8AgAAAA==.Vertrienne:BAABLAAECoEfAAMNAAcItRMkDwCqAQANAAcItRMkDwCqAQAaAAcI2wogIABpAQAAAA==.',Vi='Vinario:BAAALAAECgcIEwAAAA==.Vinishka:BAAALAAECgYIBgAAAA==.',Vo='Voidaria:BAACLAAFFIEJAAIWAAQIRBLtCQA0AQAWAAQIRBLtCQA0AQAsAAQKgSYAAhYACAhhIpoKABQDABYACAhhIpoKABQDAAAA.',Vr='Vrezael:BAAALAAECgYICQAAAA==.',Wa='Wabraty:BAAALAAECgYICQAAAA==.',We='Weazelz:BAAALAADCgUIBQAAAA==.Weiji:BAAALAAECgEIAQAAAA==.Weltenbrand:BAAALAADCgcICAAAAA==.Westcóast:BAAALAAECgUIBgABLAAFFAIICQAVAPQmAA==.',Wi='Wise:BAAALAADCggIDAABLAAFFAQIDQAQAL8MAA==.',Wo='Woomanak:BAAALAADCgQIBQAAAA==.',Xa='Xafira:BAAALAAECgcIEwAAAA==.',Xh='Xhavien:BAACLAAFFIELAAMJAAMI1hpUFgAGAQAJAAMI6BhUFgAGAQAfAAIILxCeBgBFAAAsAAQKgSYABAkACAgiJa0XAN4CAAkACAgAIq0XAN4CAB8ABwhXFL4PAJgBAAoAAQjCDnWGADoAAAAA.',Xs='Xsythia:BAAALAAECgMIAwAAAA==.',['Xâ']='Xândo:BAACLAAFFIEOAAMgAAUIwhO+AQBzAQAgAAQImhi+AQBzAQAHAAQIcQnZEgAYAQAsAAQKgSAAAyAACAhzItYHAMoCACAACAjgIdYHAMoCAAcACAgBHXk0AHwCAAAA.',['Xî']='Xîon:BAAALAAECgYIBgAAAA==.',Ye='Yeji:BAAALAADCggICAAAAA==.Yesco:BAAALAAECggICAAAAA==.',Ym='Ymo:BAAALAADCgUIBQAAAA==.',Yo='Yodâ:BAABLAAECoEXAAIdAAcIoRdBHADxAQAdAAcIoRdBHADxAQAAAA==.Yoru:BAAALAADCggICgAAAA==.Youarefacked:BAAALAADCggIEAAAAA==.Youkaii:BAAALAAECggIEwAAAA==.',Yu='Yuji:BAAALAADCggIKAAAAA==.Yunarí:BAABLAAECoEZAAMNAAYIxBcSEgB4AQANAAYIeRcSEgB4AQAaAAMIVAxgNQCGAAAAAA==.Yuvii:BAAALAAECgQIDQAAAA==.',Za='Zaps:BAABLAAECoEbAAIWAAcI2Bt4JAA1AgAWAAcI2Bt4JAA1AgAAAA==.',Ze='Zeghra:BAAALAADCgcIBwAAAA==.Zenon:BAAALAAECggIIwAAAQ==.Zetka:BAAALAAFFAIIAgABLAAECgcIBwALAAAAAA==.Zexíon:BAAALAAECgMIBQAAAA==.',Zi='Zirani:BAABLAAECoEWAAIgAAcI9gl8JAB/AQAgAAcI9gl8JAB/AQAAAA==.',Zo='Zodormi:BAAALAADCggIDQABLAAECgMIBQALAAAAAA==.Zookie:BAAALAAECggIEwAAAA==.Zorgul:BAABLAAECoEqAAIBAAgIchywIgBnAgABAAgIchywIgBnAgAAAA==.',Zu='Zunat:BAAALAAECgcIEwAAAA==.Zurî:BAAALAADCgMIAwAAAA==.',Zw='Zwergicus:BAAALAAECgcIDQAAAA==.',Zy='Zynoa:BAAALAADCggICAABLAAECggIKgABAHIcAA==.',['Zî']='Zînîmînî:BAAALAAECgYIBwAAAA==.',['Ân']='Ândorâ:BAAALAADCgcIEgAAAA==.',['Âs']='Âsaron:BAAALAAECgYIDAAAAA==.',['Ät']='Ätrux:BAAALAAECgYICQABLAAECgcIGgAPACMUAA==.',['Ìs']='Ìsha:BAAALAADCgcIBwABLAAECggILgAbALISAA==.',['Ín']='Íní:BAAALAADCgMIAwAAAA==.',['Ða']='Ðanaja:BAAALAAECgYIDAABLAAECggIJQAJADYhAA==.Ðarcja:BAABLAAECoElAAIJAAgINiGxEQADAwAJAAgINiGxEQADAwAAAA==.',['Ði']='Ðiane:BAAALAADCggICAABLAAECggIJQAJADYhAA==.',['Ðr']='Ðr:BAAALAAECggICAAAAA==.Ðrops:BAAALAADCggICAABLAAECggICAALAAAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end