local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Druid-Restoration','Paladin-Retribution','Priest-Shadow','Warrior-Protection','Warrior-Fury','Evoker-Devastation','Paladin-Protection','DemonHunter-Havoc','Evoker-Augmentation','Evoker-Preservation','Shaman-Restoration','Mage-Arcane','Druid-Balance','Mage-Fire','DeathKnight-Frost','DeathKnight-Unholy','Hunter-BeastMastery','Shaman-Enhancement','Warlock-Destruction','Warlock-Demonology','Warlock-Affliction','Paladin-Holy','Unknown-Unknown','Hunter-Marksmanship','Priest-Holy','DemonHunter-Vengeance','Monk-Brewmaster','Monk-Windwalker','Rogue-Subtlety','Rogue-Assassination','Shaman-Elemental','Warrior-Arms','Druid-Feral','Mage-Frost','Monk-Mistweaver','Priest-Discipline','Druid-Guardian','Hunter-Survival',}; local provider = {region='EU',realm="Al'Akir",name='EU',type='weekly',zone=44,date='2025-09-22',data={Ab='Abba:BAAALAAECgYIDAABLAAFFAIIBgABAEAPAA==.Aboli:BAAALAAECgYIDAABLAAECggIKwACAPYgAA==.',Ae='Aedric:BAAALAADCgcIBwAAAA==.Aerioth:BAABLAAECoEjAAIDAAgItiOmBgA5AwADAAgItiOmBgA5AwAAAA==.Aeronia:BAAALAADCggIDQAAAA==.Aeter:BAAALAAECgYIDgAAAA==.',Ag='Agro:BAABLAAECoEkAAMEAAgIbhlZFwBAAgAEAAgIbhlZFwBAAgAFAAMIjAocqgCUAAAAAA==.Agtar:BAAALAAECgMIAwAAAA==.',Ai='Aimarn:BAAALAAECgMIAwAAAA==.Aithusa:BAABLAAECoEYAAIGAAgIvxMDIwDdAQAGAAgIvxMDIwDdAQAAAA==.',Al='Alaeddine:BAAALAAECgYIDQAAAA==.Alaira:BAAALAADCggIDwAAAA==.Alakiros:BAAALAAECggIEAAAAA==.Alexandru:BAABLAAECoEWAAIHAAYIRRrRKABuAQAHAAYIRRrRKABuAQABLAAECgcIHAAIAKwWAA==.Alienation:BAAALAAFFAIIAwAAAA==.Allure:BAAALAADCggICAAAAA==.Also:BAAALAAECgUIBQAAAA==.Altchland:BAABLAAECoEWAAQJAAgIHCVNAwCQAgAJAAcIMyVNAwCQAgAGAAIIrBuPUAB0AAAKAAEIARQQNQBAAAABLAAFFAcIGAAJALMfAA==.',Am='Amatimees:BAAALAADCgUIBQAAAA==.Ami:BAAALAAECgYIDgAAAA==.Amoral:BAAALAAECgQICAAAAA==.',An='Anri:BAAALAADCgcIAwAAAA==.Antipriest:BAABLAAECoEnAAIDAAgIkxg2HQBmAgADAAgIkxg2HQBmAgAAAA==.',Ap='Aproxx:BAABLAAECoEXAAILAAcI1RhKQADuAQALAAcI1RhKQADuAQAAAA==.',Ar='Arataya:BAABLAAECoEeAAIMAAgIIxh8NQBQAgAMAAgIIxh8NQBQAgAAAA==.Arcane:BAABLAAECoEWAAIMAAYIPQwVhABZAQAMAAYIPQwVhABZAQABLAAFFAIIBQANAPEOAA==.Arcturos:BAAALAADCgYIBgAAAA==.Arienton:BAAALAADCgEIAQAAAA==.Arthuria:BAAALAADCggICAAAAA==.Artémis:BAAALAADCgcIFAAAAA==.',As='Asheka:BAABLAAECoEbAAILAAgIoxoBJwBMAgALAAgIoxoBJwBMAgABLAAFFAUIDQABAJcZAA==.Ashena:BAAALAAECggICAAAAA==.Asholog:BAAALAAECgYICQAAAA==.Asoko:BAABLAAECoEbAAMMAAgIRSDqHADHAgAMAAgIoh/qHADHAgAOAAEIxBudGABLAAAAAA==.Astrae:BAAALAADCgcIBwAAAA==.Astrality:BAAALAADCgYIBgAAAA==.Astri:BAAALAAECgMIBQAAAA==.Astrois:BAABLAAECoEZAAIIAAcI8h63OQBJAgAIAAcI8h63OQBJAgAAAA==.',At='Atadina:BAAALAAECgYICAAAAA==.Atix:BAAALAADCgMIAwAAAA==.Attenbruh:BAABLAAECoEiAAMNAAgI6CGLCwD4AgANAAgI6CGLCwD4AgABAAIIcQdgqgBLAAAAAA==.',Au='Aurash:BAABLAAECoEWAAIIAAYImRLbjwBvAQAIAAYImRLbjwBvAQAAAA==.Aurielle:BAABLAAECoEjAAICAAgIRCG1HwDPAgACAAgIRCG1HwDPAgAAAA==.Auryx:BAAALAAECgUIBwAAAA==.',Az='Azerite:BAAALAADCggIEwAAAA==.',Ba='Baelpow:BAAALAADCgYIBgAAAA==.Bagz:BAAALAAECgYIDwAAAA==.Balanciaga:BAAALAADCgMIAwAAAA==.Baldruid:BAAALAAECggIDwAAAA==.Balerion:BAAALAADCggIEAAAAA==.Bananino:BAAALAADCgcICAAAAA==.Baraddûr:BAABLAAECoEXAAMPAAgI7BbcRQA/AgAPAAgI7BbcRQA/AgAQAAYICg16KABbAQAAAA==.Barasha:BAABLAAECoEbAAIRAAgIrSONFADjAgARAAgIrSONFADjAgAAAA==.Bartuk:BAAALAAECgMIAwAAAA==.',Be='Beastmanaids:BAAALAADCgcIGAAAAA==.Beibe:BAAALAAECgcICgAAAA==.Bernié:BAAALAADCgYIDQAAAA==.Berserknight:BAAALAADCgYIBgAAAA==.',Bi='Bibon:BAACLAAFFIEFAAISAAIIlw5cBQCWAAASAAIIlw5cBQCWAAAsAAQKgSIAAhIACAgtHfMEALoCABIACAgtHfMEALoCAAAA.Bigmilk:BAAALAAECgcICgAAAA==.Billyboi:BAABLAAECoElAAQTAAgIMRY+OQAfAgATAAgIfBQ+OQAfAgAUAAcI1hDvLACaAQAVAAEIsQSkOgA6AAAAAA==.Bish:BAAALAADCggIDgAAAA==.',Bj='Björntjäder:BAAALAAECgUICQAAAA==.',Bl='Blacklist:BAAALAAECggICAAAAA==.Blackmaira:BAABLAAECoEgAAMCAAgI6h6tIQDFAgACAAgI6h6tIQDFAgAWAAYIRB9NHQDzAQAAAA==.Bloodbringer:BAABLAAECoElAAIPAAgISRtlNwBtAgAPAAgISRtlNwBtAgAAAA==.Bloodclot:BAAALAADCggIEAAAAA==.',Bo='Boes:BAAALAADCgYIBgABLAAECgYICgAXAAAAAA==.Bow:BAAALAADCggIDwABLAAFFAIIBQANAPEOAA==.',Br='Brekke:BAAALAADCgYIBgAAAA==.Brucey:BAAALAADCggIDQAAAA==.Bruckshot:BAABLAAECoEUAAIYAAgIzBYUKwADAgAYAAgIzBYUKwADAgAAAA==.Brutosaur:BAAALAAECgIIAgAAAA==.',Bu='Bubblez:BAAALAADCggIGwAAAA==.Bubumoo:BAABLAAECoEaAAILAAgIEAoYiwAlAQALAAgIEAoYiwAlAQAAAA==.Buburiza:BAAALAAECgcICwAAAA==.Bukanyrtomy:BAAALAADCggIDgAAAA==.Bumboo:BAAALAAECggIEQAAAA==.Burstshot:BAABLAAECoEpAAMRAAgIwiUHAgB3AwARAAgIoSUHAgB3AwAYAAcIwCNzEgC7AgAAAA==.',['Bå']='Båsedgôd:BAAALAAECgYIDgABLAAFFAIIBgABAEAPAA==.',['Bö']='Böe:BAAALAADCgcIBwAAAA==.Bösartigkeit:BAAALAAECgUIBQABLAAFFAYIEgAPAMIgAA==.',Ca='Calioo:BAAALAADCgcIBwAAAA==.Callithyia:BAACLAAFFIEIAAIZAAIIOBR7HgCYAAAZAAIIOBR7HgCYAAAsAAQKgR0AAxkACAg1GPkjAD0CABkACAg1GPkjAD0CAAMAAQh9FR+DAEAAAAEsAAUUAwgHAAEA/xQA.Cardigan:BAABLAAECoEZAAIaAAcI0BDjIgBcAQAaAAcI0BDjIgBcAQAAAA==.Carnagewar:BAAALAAECgEIAQAAAA==.',Ce='Cellstorm:BAAALAADCgYIAwAAAA==.',Ch='Chafe:BAAALAADCgcIBwAAAA==.Chewawa:BAAALAADCggIFQAAAA==.Chillybill:BAABLAAECoEdAAMPAAcIxhmkWAAOAgAPAAcIxhmkWAAOAgAQAAMITghBRgB3AAAAAA==.Chocchip:BAAALAADCggICAAAAA==.Choyleefut:BAABLAAECoEhAAMbAAgIOhxSDQBSAgAbAAgIehtSDQBSAgAcAAIIrhHESgB5AAAAAA==.',Ci='Ciaran:BAAALAAECgMIBgAAAA==.',Cl='Clapped:BAAALAADCgIIAgAAAA==.Clavar:BAAALAADCgcIEAAAAA==.Clerichealzz:BAAALAADCggIDQABLAAECggIJAACAKAaAA==.Clownz:BAAALAAECggIAgAAAA==.',Co='Coldplayed:BAAALAAECgcICwAAAA==.Coldpot:BAAALAADCgcIBwAAAA==.Commandor:BAAALAAECgcIDQAAAA==.Coolkdruid:BAAALAADCgcIBwAAAA==.Coolkpaladin:BAABLAAECoEnAAIWAAgIyxTzGwD9AQAWAAgIyxTzGwD9AQAAAA==.Coolkshaman:BAAALAADCgEIAQAAAA==.Costhares:BAABLAAECoEaAAMRAAgIQxk1MQBNAgARAAgI8hg1MQBNAgAYAAcILQ24UwBJAQAAAA==.',Cr='Crackpot:BAAALAAECgcIEQAAAA==.Crankypants:BAAALAAECgYIDAAAAA==.Creapp:BAABLAAECoEVAAMdAAYIdhofGACnAQAdAAYIXxgfGACnAQAeAAQIlxc6QwAfAQAAAA==.Critcobain:BAABLAAECoEgAAIRAAgInh4IIwCMAgARAAgInh4IIwCMAgAAAA==.Crogis:BAAALAAECgcIBwAAAA==.Crypta:BAAALAAECgYICAAAAA==.Crystalwhite:BAAALAADCgYIBgAAAA==.',Cu='Cue:BAACLAAFFIEbAAMfAAcIfxxoAgA6AgAfAAYIrR1oAgA6AgALAAIIDQgzIQCaAAAsAAQKgTkAAh8ACAifJtkAAJEDAB8ACAifJtkAAJEDAAAA.',Da='Dageda:BAABLAAECoEbAAILAAYIiyBiLgAuAgALAAYIiyBiLgAuAgAAAA==.Dalahad:BAAALAAECgIIAgAAAA==.Daruni:BAABLAAECoEiAAINAAgImyIMCgALAwANAAgImyIMCgALAwAAAA==.Davidasayag:BAAALAADCggIEwAAAA==.Daydreaming:BAACLAAFFIENAAIFAAQI0xVfCQBfAQAFAAQI0xVfCQBfAQAsAAQKgSQAAwUACAiGIkAUAOsCAAUACAiGIkAUAOsCACAAAQj+JQwpAHAAAAAA.Daydréam:BAAALAAECgYICQABLAAFFAQIDQAFANMVAA==.',De='Deathsword:BAAALAAECgYIDgAAAA==.Decedatu:BAAALAAECgQICwAAAA==.Dedgame:BAAALAAECgUICQAAAA==.Deelchev:BAAALAADCggICAAAAA==.Degenerate:BAAALAAECgQIBwABLAAFFAEIAQAXAAAAAA==.Deith:BAAALAAECgMIAwAAAA==.Deler:BAAALAADCgYICwABLAAECggIIgAGAKEaAA==.Demonhaze:BAAALAAECgYIDwAAAA==.Demoniks:BAAALAADCgQIBAAAAA==.Demoralized:BAAALAADCggICAAAAA==.Denoysius:BAAALAAECgYICgAAAA==.Dentibus:BAAALAAECgQIBAABLAAECggIJgATAJAdAA==.Dentimonk:BAAALAAECgYICAABLAAECggIJgATAJAdAA==.',Dh='Dharkan:BAAALAAECgcIBwABLAAECggIFQAEAPokAA==.Dhsurfer:BAABLAAECoEcAAIaAAcICg8GJgBDAQAaAAcICg8GJgBDAQAAAA==.',Di='Dianabol:BAAALAADCgIIAgAAAA==.Diletta:BAABLAAECoEYAAMUAAgIcRV3FQAsAgAUAAgIcRV3FQAsAgATAAEIdgwfzgBAAAAAAA==.Dimageter:BAAALAAECgYIDgABLAAECggIJAAEAG4ZAA==.Diniter:BAAALAADCggICAABLAAECggIJAAEAG4ZAA==.',Do='Doderidder:BAAALAADCgUIBQAAAA==.Doggak:BAAALAADCggIEAAAAA==.Donnydh:BAAALAADCgYIBgABLAAECggIFwALANUYAA==.',Dr='Draakonn:BAAALAADCgEIAQAAAA==.Draext:BAAALAADCgYIBwAAAA==.Dragedisse:BAABLAAECoEmAAIJAAgIwxVPBQAoAgAJAAgIwxVPBQAoAgAAAA==.Dragonaz:BAAALAAECgQIBAAAAA==.Dramalama:BAAALAAECgMIAwABLAAECggIEAAXAAAAAA==.Driadis:BAAALAADCggIDQAAAA==.Dribbling:BAAALAADCgEIAQAAAA==.Droodya:BAAALAAECgYICAAAAA==.Drunkenmastr:BAAALAADCggIDgAAAA==.',Du='Duduu:BAAALAAECgQIBgAAAA==.Duduz:BAAALAADCggIDAAAAA==.Dundul:BAAALAADCgQIBAAAAA==.Dunkarn:BAAALAAECggIBAAAAA==.',Dw='Dwarfpaladin:BAAALAAECgYIDgAAAA==.',['Dä']='Dähl:BAACLAAFFIEPAAIBAAUIgh1pAgDpAQABAAUIgh1pAgDpAQAsAAQKgSQAAgEACAiUHnYRAKYCAAEACAiUHnYRAKYCAAAA.',Ea='Eatdemonz:BAAALAAECgYIEwAAAA==.',Ec='Echo:BAAALAADCgQIBAABLAAFFAIIBgAeAIoeAA==.',Eg='Egiwker:BAAALAADCgYIBgAAAA==.Egiwninho:BAAALAAFFAIIAgAAAA==.Eguotnam:BAABLAAECoEaAAIeAAcIXx70FABfAgAeAAcIXx70FABfAgAAAA==.',El='Eleshook:BAAALAADCggICAAAAA==.Elohim:BAAALAAECgQIBgABLAAECgYICwAXAAAAAA==.Elvspriestly:BAAALAAECgMIAwAAAA==.',Em='Empanado:BAAALAADCggICAAAAA==.',En='Engl:BAAALAADCggIDAAAAA==.Entrei:BAAALAAECgcICgABLAAECggILQATAM0eAA==.',Er='Erotrix:BAAALAADCgEIAQAAAA==.',Ev='Everec:BAABLAAECoElAAMaAAgIvSUcAQBuAwAaAAgIvSUcAQBuAwAIAAYIlRy+WQDmAQAAAA==.',Ex='Exess:BAAALAADCgYIBgABLAADCggICAAXAAAAAA==.Exyl:BAABLAAECoEWAAINAAYInhuaMwC4AQANAAYInhuaMwC4AQAAAA==.',Ey='Eyebeamkek:BAACLAAFFIESAAIaAAUI2xu2AADIAQAaAAUI2xu2AADIAQAsAAQKgSUAAxoACAhSIJcHAL8CABoACAhSIJcHAL8CAAgABAgrEbvPANsAAAAA.',Fa='Falciteyze:BAAALAAECgIIAgAAAA==.Farstrider:BAAALAADCgYICAAAAA==.Fasu:BAAALAADCggIEAAAAA==.Fatherdollan:BAAALAADCgcICgAAAA==.Fatnerd:BAABLAAECoEUAAMaAAcIzyE5EgARAgAIAAcIQR7/OwBAAgAaAAYIsSE5EgARAgABLAAFFAEIAQAXAAAAAA==.Fatrider:BAAALAAECgYIDAABLAAFFAIIBAAXAAAAAA==.Fazer:BAABLAAECoEZAAMBAAgI6g8VPACxAQABAAgI6g8VPACxAQAhAAcI3hKMGQCnAQAAAA==.',Fe='Femtrei:BAABLAAECoEtAAITAAgIzR4CGgDKAgATAAgIzR4CGgDKAgAAAA==.Fenrahel:BAAALAAECgUIBwABLAAECgYIDwAXAAAAAA==.Fereydun:BAABLAAECoErAAMCAAgI9iAgHADiAgACAAgIhCAgHADiAgAHAAIIfx4ARgCnAAAAAA==.',Fi='Firefliestwo:BAAALAADCgYIBgAAAA==.',Fl='Flannagan:BAAALAAECgIIAgAAAA==.Flaye:BAABLAAECoEtAAIDAAgIbh9ZDwDhAgADAAgIbh9ZDwDhAgAAAA==.Fleecoshammy:BAAALAADCgQIBAABLAADCgcIDgAXAAAAAA==.Floonz:BAACLAAFFIEJAAIMAAQIbAxMEQA0AQAMAAQIbAxMEQA0AQAsAAQKgRUAAwwACAiIGGNEABUCAAwACAiIGGNEABUCACIAAwhdC7plAIQAAAAA.Flowdark:BAACLAAFFIEIAAMUAAII9RpMCQCuAAAUAAII1BlMCQCuAAATAAIIqBRlJwCcAAAsAAQKgSQAAxMACAgLIG4cALoCABMACAiQHW4cALoCABQABwhMGxsUADkCAAEsAAQKCAgtABMAKRkA.',Fo='Fongar:BAABLAAECoEaAAIPAAgITBH2cgDVAQAPAAgITBH2cgDVAQAAAA==.',Fr='Frayon:BAAALAADCgcICAAAAA==.Friede:BAAALAAECgMIAgAAAA==.Frommage:BAAALAAECgMIAgAAAA==.',Fu='Fuldtopper:BAAALAAECgMIAwABLAAFFAMICAADAOgQAA==.',Ga='Galae:BAAALAAECgYICQAAAA==.Garuk:BAAALAADCgYIBwAAAA==.Gathos:BAABLAAECoEpAAIRAAgINxyLLwBUAgARAAgINxyLLwBUAgAAAA==.Gaurondal:BAABLAAECoEqAAINAAgIZRkNHABOAgANAAgIZRkNHABOAgAAAA==.',Gh='Ghaka:BAAALAADCgQIBAAAAA==.Ghosteye:BAAALAADCgQIAwABLAAECggIKAAYAIwOAA==.Ghostheart:BAAALAADCggICAAAAA==.Ghosti:BAAALAAECgYICQAAAA==.',Gi='Gitalot:BAAALAAECgYICgAAAA==.',Gj='Gj:BAAALAAECgYIDAAAAA==.',Gl='Glaiverush:BAAALAAECgYIDwAAAA==.',Go='Gobblar:BAAALAAECgYIBgAAAA==.Goblinus:BAAALAADCggICAAAAA==.Goetia:BAABLAAECoEoAAIPAAgIShyzMQCBAgAPAAgIShyzMQCBAgAAAA==.Goldyman:BAAALAAECggICAAAAA==.Gordul:BAABLAAECoEsAAIMAAgI6hpMLgBwAgAMAAgI6hpMLgBwAgAAAA==.Gorebringer:BAAALAADCgIIAgAAAA==.',Gr='Grau:BAABLAAECoEUAAMCAAcILhibZgDnAQACAAcILhibZgDnAQAWAAYI8xvDJwCnAQAAAA==.Grav:BAAALAAECgcIDwAAAA==.Greenfred:BAABLAAECoEgAAIYAAgIYBb8JQAiAgAYAAgIYBb8JQAiAgAAAA==.Greenganji:BAAALAADCggIGgAAAA==.Greenrabit:BAAALAADCgcIBwABLAAECgYIEQAXAAAAAA==.Greensham:BAAALAADCggIDAAAAA==.Grislik:BAABLAAECoEUAAIEAAgIOhSjIwDZAQAEAAgIOhSjIwDZAQAAAA==.Grokshall:BAAALAAECgIIAgAAAA==.Grotekoe:BAAALAAECgIIAgAAAA==.',Gu='Gugu:BAAALAAECgYIEwAAAA==.Gurthquake:BAABLAAECoEfAAIfAAgImBc7JgBTAgAfAAgImBc7JgBTAgAAAA==.',['Gö']='Göy:BAAALAAFFAIIBAAAAA==.',Ha='Hammadin:BAAALAAECgEIAgAAAA==.Hammonology:BAAALAADCgYICAABLAAECgEIAgAXAAAAAA==.Hanken:BAAALAADCgMIAwAAAA==.Harmónia:BAAALAADCgUIBwAAAA==.Harsenfefer:BAAALAADCggIFAABLAAECgUIBQAXAAAAAA==.Haxx:BAAALAAECgcIEAAAAA==.',He='Healatron:BAAALAAECgYIDAAAAA==.Hexluthor:BAAALAAECgQIBQAAAA==.',Hi='Hitnrun:BAAALAAECgcIDwAAAA==.Hitraw:BAAALAAECgYIEgAAAA==.',Ho='Holdmyfel:BAAALAADCgcIDQAAAA==.Holyshook:BAAALAADCgQIBAAAAA==.Hotshot:BAAALAADCggIFwAAAA==.',Hu='Hubnester:BAEALAADCggIFAABLAAECgYIFAAZANYZAA==.Hulle:BAAALAAECgUIBwABLAAECggIHwASAD0aAA==.Hullé:BAABLAAECoEfAAMSAAgIPRp8BwBvAgASAAgIKhp8BwBvAgAfAAMI5ByAdwABAQAAAA==.Huntarion:BAAALAAECgYIBgAAAA==.',Hy='Hyberion:BAABLAAECoEfAAIaAAgIHhO3GADEAQAaAAgIHhO3GADEAQAAAA==.',Ib='Ibighealu:BAAALAADCggICAABLAAECggIIgAWAE0kAA==.',Il='Ilens:BAAALAAECgcIEgAAAA==.Ilsinho:BAAALAAECgcIDAAAAA==.',In='Incendia:BAAALAADCgYIBgABLAAECggIIwACAEQhAA==.Inir:BAAALAAECgYIEwAAAA==.',Ir='Irith:BAAALAADCggIBwAAAA==.',It='Itzadamn:BAAALAADCgIIAgAAAA==.',Iv='Ivoire:BAABLAAECoEpAAIZAAgI2SBgDgDcAgAZAAgI2SBgDgDcAgAAAA==.Ivytotem:BAAALAAECgcIBwAAAA==.',Iz='Izah:BAEBLAAECoEUAAIZAAYI1hnLOwDAAQAZAAYI1hnLOwDAAQAAAA==.',Ja='Jaderra:BAAALAAECgUIBQAAAA==.Jahika:BAAALAAECgQICQAAAA==.Jahimees:BAAALAADCgcICwABLAAECgQICQAXAAAAAA==.Jailbaít:BAAALAAECgYIDwAAAA==.Jarazim:BAAALAADCggIEAAAAA==.Jargh:BAAALAAECgcIBwAAAA==.Jarizard:BAAALAAECgYICQAAAA==.Jarnis:BAABLAAECoEnAAIfAAgIhxoyIgBsAgAfAAgIhxoyIgBsAgAAAA==.Jarnlock:BAAALAADCggICAAAAA==.Jawst:BAAALAAECgYIBgAAAA==.',Je='Jebako:BAAALAAECgQIBgAAAA==.Jeev:BAAALAADCgMIAwAAAA==.Jemm:BAAALAADCggICAAAAA==.Jepicast:BAAALAAECgYICQAAAA==.Jepismash:BAAALAAECggICQAAAA==.',Ji='Jimmsy:BAAALAADCgYIBgAAAA==.Jindal:BAAALAADCggICAAAAA==.',Jo='Joejoe:BAACLAAFFIEPAAMPAAUIbB0jBgDdAQAPAAUIbB0jBgDdAQAQAAEISxGWEgBhAAAsAAQKgR4AAg8ACAjSIo0aAOcCAA8ACAjSIo0aAOcCAAAA.Jokeer:BAAALAAECgQIBAAAAA==.Jorga:BAAALAAECgYIBgAAAA==.',Ju='Judochop:BAAALAADCggIDgAAAA==.',Ka='Kaabulian:BAAALAAECgcIEwAAAA==.Kagul:BAAALAADCgYIBgABLAAECggIIgANAOghAA==.Kaiserr:BAAALAAECgEIAQAAAA==.Kale:BAABLAAECoEWAAILAAcIixgFPwDyAQALAAcIixgFPwDyAQAAAA==.Kalw:BAAALAADCgcIDAABLAAECgYIFwARAD0OAA==.Kanerva:BAAALAADCggICAAAAA==.Karshee:BAAALAADCgEIAQAAAA==.Katrena:BAAALAAECgYIEQAAAA==.Kattipulli:BAAALAADCggICwABLAAECgYIBgAXAAAAAA==.Kazidh:BAABLAAECoEnAAMaAAgI6h7SCwBsAgAaAAcIJCHSCwBsAgAIAAgI5xYVRAAkAgAAAA==.',Ke='Kehzuface:BAAALAAECgMIAwABLAAECgcICQAXAAAAAA==.Kepumies:BAABLAAECoEbAAIIAAcINRI0cACwAQAIAAcINRI0cACwAQAAAA==.',Kh='Kheldurin:BAAALAAECgYIDAAAAA==.Kho:BAACLAAFFIEHAAIfAAMI1grWEQDYAAAfAAMI1grWEQDYAAAsAAQKgSMAAh8ACAgfHx4SAOYCAB8ACAgfHx4SAOYCAAAA.Khomeyni:BAAALAADCgYIBAAAAA==.',Ki='Killakan:BAAALAADCgMIAwAAAA==.Killerd:BAAALAAECggIDwAAAA==.Kiserore:BAAALAADCgQIBQABLAADCgcIBwAXAAAAAA==.Kisiel:BAAALAADCggICAABLAAECgYIDgAXAAAAAA==.Kiyanne:BAABLAAECoEfAAIKAAgIohG9EgDMAQAKAAgIohG9EgDMAQAAAA==.',Ko='Kobean:BAAALAAECgYICAAAAA==.Kolinia:BAAALAADCggIFQAAAA==.Korack:BAAALAADCgIIAgABLAAECggIGAAUAHEVAA==.',Kr='Kraya:BAAALAAECgMICAAAAA==.Krazzy:BAAALAAECggICAAAAA==.Kritos:BAAALAADCgYICwABLAAECggIHwASAD0aAA==.Krittós:BAAALAADCggICAABLAAECggIHwASAD0aAA==.Kritós:BAAALAAECgYICwABLAAECggIHwASAD0aAA==.Kruxi:BAAALAADCggIGwAAAA==.',Ks='Ks:BAAALAAECggIEgAAAA==.',La='Laillea:BAAALAADCggIEQAAAA==.Lamoralin:BAAALAAECgYIDAAAAA==.Landoo:BAAALAAECggIDQAAAA==.Laskur:BAAALAAECggICgAAAA==.Laurentius:BAABLAAECoEcAAICAAgIuxOKWQAFAgACAAgIuxOKWQAFAgAAAA==.',Le='Lemsip:BAAALAADCgcIBwAAAA==.Levanrätinä:BAAALAADCgYIBgAAAA==.Leylani:BAAALAAECggICAAAAA==.',Li='Libertiy:BAAALAAECgMIAgAAAA==.Lichuu:BAAALAAECggICAAAAA==.Lickmethin:BAAALAADCgcIFwAAAA==.Lihapulla:BAAALAAECgcIBwAAAA==.Lillo:BAAALAADCgcICAABLAAFFAIIBgAZAAocAA==.Lizamo:BAAALAAECgYIBgAAAA==.',Lo='Locing:BAAALAAECgYICQAAAA==.Lockeddown:BAAALAADCgcIBwABLAAFFAMICgAMAF8bAA==.Lokumka:BAABLAAFFIEGAAIcAAIIeRXfCgCgAAAcAAIIeRXfCgCgAAABLAAFFAIIDAAMALElAA==.Longshot:BAAALAADCgcICwAAAA==.Losikuhari:BAAALAAECgYICgAAAA==.Loskedeath:BAAALAADCgYICQAAAA==.Loskedemon:BAAALAADCggIGAAAAA==.Loskedragon:BAAALAADCggIKQAAAA==.Loskemonk:BAAALAADCggIGwAAAA==.Loskepaladin:BAAALAAECgUIBQAAAA==.Loskepriest:BAAALAADCggIIwAAAA==.Loskewarrior:BAAALAADCggIFgAAAA==.',Lu='Lucillius:BAAALAADCgYICAAAAA==.Lumen:BAABLAAECoEgAAMHAAgIBSPfCgCZAgAHAAgIoyHfCgCZAgACAAcInBpLQgBFAgAAAA==.Lumevo:BAAALAADCgYIBwABLAAECgYIDQAXAAAAAA==.Lumsha:BAAALAAECgYIDQAAAA==.Lustre:BAAALAADCgQIBAAAAA==.',['Lö']='Lökö:BAABLAAECoEdAAILAAgI8hInVQCvAQALAAgI8hInVQCvAQAAAA==.',Ma='Magesty:BAAALAADCgUIBQAAAA==.Magetar:BAAALAAECgYICQAAAA==.Mageymcmage:BAAALAAECggIEgAAAA==.Majuri:BAAALAAECgMIAwAAAA==.Makemani:BAABLAAECoEcAAMfAAYIbRuLPADgAQAfAAYIbRuLPADgAQALAAMIuwIO8QBXAAAAAA==.Makqti:BAAALAADCggIGAAAAA==.Maltinus:BAAALAAECgIIAwABLAAECgUICQAXAAAAAA==.Mandemon:BAAALAAECggIEAAAAA==.Mart:BAAALAADCgcICgAAAA==.Marzu:BAAALAAECggIDwAAAA==.Matthew:BAAALAADCggICAABLAAECgYIBgAXAAAAAA==.Mautaw:BAAALAAECgMIAwAAAA==.',Mc='Mcluvin:BAAALAADCgUIBQAAAA==.',Me='Megamagus:BAAALAAECgIIAgABLAAECgcIDQAXAAAAAA==.Mementomori:BAAALAADCggIDgAAAA==.Merijntje:BAAALAAECgYICgAAAA==.Mess:BAAALAAFFAIIAgAAAA==.Meza:BAAALAADCggIDQAAAA==.',Mi='Mi:BAABLAAECoEVAAIjAAcISRR5GwCiAQAjAAcISRR5GwCiAQABLAAFFAIIBgAZAAocAA==.Mindrenderi:BAABLAAECoEYAAIIAAgITg//WwDgAQAIAAgITg//WwDgAQAAAA==.Minute:BAAALAAECggIEAABLAAECgYICQAXAAAAAA==.',Mo='Monsun:BAAALAADCgUIBQAAAA==.Mooney:BAABLAAECoEfAAIRAAgIJBhXQgAOAgARAAgIJBhXQgAOAgAAAA==.Moosmöse:BAAALAAECggIEAAAAA==.Moremats:BAAALAAECgMIBgAAAA==.',Mu='Munkkitimo:BAAALAAECgcIBwAAAA==.Mupsik:BAAALAAECgMIAwAAAA==.Murus:BAAALAAECgEIAQAAAA==.',My='Mymo:BAAALAADCggICAAAAA==.Mythicdungo:BAAALAAECgUIBwAAAA==.',['Má']='Máttyb:BAABLAAECoEkAAICAAgIoBpoPQBTAgACAAgIoBpoPQBTAgAAAA==.',['Mú']='Múhamme:BAAALAAECgUICwAAAA==.',Na='Nala:BAAALAADCggIDQAAAA==.Nappitsu:BAAALAADCggICAAAAA==.',Ne='Neerah:BAAALAADCggICAAAAA==.Nellá:BAAALAAFFAEIAQAAAA==.Neulovim:BAAALAAECggIDQAAAA==.Newcowwhodis:BAAALAAECgMIBQAAAA==.',Nh='Nhixni:BAAALAADCggICAAAAA==.',Ni='Niktos:BAABLAAECoElAAITAAgIxiJKDgAYAwATAAgIxiJKDgAYAwAAAA==.Nirith:BAABLAAECoEaAAQZAAcIORepMAD3AQAZAAcIORepMAD3AQAkAAIIwAxDKQBaAAADAAEITAq1hQA5AAAAAA==.Nisse:BAABLAAECoEmAAIcAAgInBgyFQA5AgAcAAgInBgyFQA5AgAAAA==.',No='Nohealrolfer:BAAALAADCgUIBQAAAA==.Norskie:BAAALAAECggIDgAAAA==.Notcowwhodis:BAAALAADCgUIBQAAAA==.Notholtz:BAAALAAFFAIIBAAAAA==.Notsmuel:BAABLAAECoEiAAIWAAgITSSHAQBFAwAWAAgITSSHAQBFAwAAAA==.',Nu='Nuggetman:BAAALAAFFAIIAgAAAA==.Nuppuz:BAAALAAECgMIAwAAAA==.Nurofen:BAABLAAECoEWAAICAAgI2xlcPQBTAgACAAgI2xlcPQBTAgAAAA==.',Ny='Nyxariel:BAAALAAFFAIIAgAAAA==.',Od='Odimm:BAABLAAECoEcAAIYAAgIbyFDEwC0AgAYAAgIbyFDEwC0AgAAAA==.Odium:BAAALAAECgUIBgAAAA==.',Oj='Ojha:BAAALAADCggICAAAAA==.',Ol='Oldar:BAAALAAECgYIEAABLAAECggIHAAYAG8hAA==.Olidh:BAAALAAECgcIDgAAAA==.',Om='Omegadon:BAAALAADCggIIgAAAA==.Omegashenron:BAAALAAECgMIBAAAAA==.Omnath:BAAALAAECgMIBwAAAA==.',On='Onaturlig:BAAALAAECggIAwAAAA==.Onepoundfish:BAAALAAECggIEAAAAA==.Onex:BAAALAAECggIAgAAAA==.',Or='Ortri:BAAALAAECgQICwAAAA==.',Os='Ossium:BAABLAAECoEgAAIPAAgI6QqchgCuAQAPAAgI6QqchgCuAQAAAA==.',Ot='Ottanah:BAAALAADCggIHAAAAA==.',Ou='Ouchmybones:BAAALAAECgQIBAAAAA==.',Ov='Ovenmaker:BAAALAAECgMIAwAAAA==.',Ow='Owuo:BAAALAAECggIBQAAAA==.',Pa='Pahatonnalli:BAAALAAECgQIBAABLAAECgYIBgAXAAAAAA==.Palatard:BAABLAAECoEdAAMCAAgIQRM3XwD3AQACAAgIUxI3XwD3AQAHAAEIAxXNWgA2AAAAAA==.Panne:BAAALAADCgYIBgAAAA==.Parvatí:BAACLAAFFIEIAAIYAAIIGxpGFQCeAAAYAAIIGxpGFQCeAAAsAAQKgRsAAhgABgj/ID0jADQCABgABgj/ID0jADQCAAAA.Pasiive:BAABLAAECoEiAAIEAAgItBfrGQAoAgAEAAgItBfrGQAoAgAAAA==.Passiive:BAAALAAECgYIBwAAAA==.Pavok:BAAALAAECgYIBwAAAA==.Paxen:BAAALAADCggICAAAAA==.',Pe='Peavy:BAAALAADCggICAABLAAECggIIwAjALsVAA==.Pertimonk:BAAALAAECgEIAQAAAA==.',Ph='Pheonyx:BAACLAAFFIEHAAIMAAIIBRbNLACdAAAMAAIIBRbNLACdAAAsAAQKgSAAAwwACAgnH60kAJ8CAAwACAgnH60kAJ8CACIAAwgLDRllAIcAAAAA.Phruity:BAABLAAECoEjAAIlAAgIFxyLBQCEAgAlAAgIFxyLBQCEAgAAAA==.Phyrexa:BAAALAADCggIEQAAAA==.',Pi='Pistachio:BAAALAADCgYIBQAAAA==.',Pl='Ploxi:BAABLAAECoEYAAIFAAgIzA7oSADXAQAFAAgIzA7oSADXAQAAAA==.',Po='Polikala:BAAALAAECgIIAgAAAA==.Ponga:BAAALAADCggICQAAAA==.Porkloin:BAAALAADCggICQAAAA==.Porni:BAAALAAECgMIAwAAAA==.Postponed:BAAALAAFFAIIBAAAAA==.Pow:BAAALAADCggIDQABLAAECggIIgAWAE0kAA==.',Pr='Proo:BAABLAAECoEXAAIRAAYIPQ7xmAA+AQARAAYIPQ7xmAA+AQAAAA==.Prínce:BAAALAADCgEIAQAAAA==.',Pu='Putamandown:BAAALAADCgMIAwAAAA==.Puupi:BAAALAAECgIIAgAAAA==.',Py='Pyroblaast:BAAALAAECgYIBgAAAA==.',Qa='Qain:BAAALAAECgYIBgAAAA==.',Qu='Qudshu:BAABLAAECoEdAAIIAAgIMiNMGQDkAgAIAAgIMiNMGQDkAgAAAA==.Queltals:BAAALAAECggIBgAAAA==.Quzzi:BAAALAAECgIIBAAAAA==.',Ra='Raijdow:BAAALAADCggICAAAAA==.Raketta:BAAALAAECgYIBgAAAA==.Rakuraido:BAAALAAECgQICAAAAA==.Rass:BAAALAAECgYIBgABLAAECggIFAAYAMwWAA==.Rastagangsta:BAAALAADCggIDgAAAA==.Ratmilk:BAAALAADCggICAAAAA==.Rawmeat:BAAALAADCggIDQAAAA==.',Re='Rees:BAAALAADCggICQABLAAFFAIIBgAZAAocAA==.Regicide:BAAALAAECggIBAAAAA==.Relin:BAAALAADCggICAAAAA==.Reptilicus:BAAALAADCggICAAAAA==.Retribúsön:BAAALAAECgUIDwAAAA==.Revive:BAAALAADCggICAAAAA==.',Rg='Rgnarok:BAAALAADCgMIAwAAAA==.',Rh='Rhapidfire:BAABLAAECoEbAAIYAAcI8hv+JgAcAgAYAAcI8hv+JgAcAgAAAA==.',Ri='Ririth:BAABLAAECoEsAAMTAAgIRBuYIwCNAgATAAgIRBuYIwCNAgAVAAYInBJAEQCCAQAAAA==.Rissler:BAACLAAFFIEPAAMRAAUIgx62BgCYAQARAAUIqRu2BgCYAQAYAAUIPhhwBQCEAQAsAAQKgRsAAhgACAiVJIAJAA4DABgACAiVJIAJAA4DAAAA.Ristoreipääs:BAAALAADCgQIBAABLAAECgYIBgAXAAAAAA==.',Ro='Rockwood:BAAALAADCggIDgAAAA==.Rootnrun:BAAALAADCgcIDgABLAAECgYIDQAXAAAAAA==.Rosalindaé:BAAALAAECgEIAQAAAA==.Rosalíndae:BAAALAADCgYIBgAAAA==.Rotjoch:BAAALAAECgcIDgAAAA==.Roubignol:BAAALAADCgEIAgAAAA==.',Sa='Sacredhebrew:BAAALAADCggIEQAAAA==.Saintkigun:BAAALAADCgMIAwAAAA==.Saintperky:BAABLAAECoEfAAIHAAgIvxkqEABPAgAHAAgIvxkqEABPAgAAAA==.Saketzu:BAABLAAECoEaAAIiAAgImBIVIgDiAQAiAAgImBIVIgDiAQAAAA==.Saladlord:BAAALAAFFAEIAQAAAA==.Salmonsnake:BAAALAADCggICAAAAA==.Samaâr:BAAALAADCggICAAAAA==.Samáar:BAABLAAECoEiAAIWAAgIcQfFNABZAQAWAAgIcQfFNABZAQAAAA==.Sapaca:BAAALAADCgYIBgAAAA==.Sargonakos:BAAALAAECgMIAgAAAA==.Sarkhan:BAAALAADCggICAABLAAECggIFQAEAPokAA==.Sarkhani:BAAALAADCggICAABLAAECggIFQAEAPokAA==.Sarthas:BAAALAAECggIEQABLAAECggIFQAEAPokAA==.Sattuma:BAAALAADCggICAAAAA==.Savulohi:BAAALAAECgYIBgAAAA==.Sayya:BAAALAADCgQIBAAAAA==.',Sc='Scalebro:BAAALAADCgQIBAAAAA==.Scarab:BAABLAAECoEsAAMmAAgIQB0tAwC7AgAmAAcIviAtAwC7AgAYAAcIdRMSPQCkAQAAAA==.',Se='Sec:BAAALAADCgcIBwAAAA==.Sen:BAAALAADCggICQAAAA==.Seraph:BAAALAAECggIDgABLAAECggIEgAXAAAAAA==.Serv:BAAALAADCggICAAAAA==.Servhunter:BAAALAAECgQIBAAAAA==.Seräph:BAAALAAECggIBgABLAAECggIEgAXAAAAAA==.',Sh='Shadowmender:BAAALAAECgYICwABLAAECggIKAAYAIwOAA==.Shadowwizard:BAAALAAECgcICwAAAA==.Shagara:BAAALAADCggICAABLAAECggIIQAIAG0XAA==.Shalur:BAAALAAECgYIBgAAAA==.Shamantix:BAAALAAECgcIDQAAAA==.Shamoonyh:BAAALAADCgYIAgAAAA==.Shatman:BAAALAAECgcIDQAAAA==.Shatmando:BAAALAAECgMIAwABLAAECgcIDQAXAAAAAA==.Shbrorr:BAAALAAECgQICwAAAA==.Shbrro:BAAALAADCgEIAQAAAA==.Shbrror:BAAALAAECgcICwAAAA==.Sheedah:BAAALAADCgcIBwABLAAECgUICQAXAAAAAA==.Sheepster:BAAALAADCggIEgAAAA==.Shelana:BAAALAAECgMIBwAAAA==.Shephiroth:BAAALAADCggIEgAAAA==.Shimira:BAAALAAFFAEIAQAAAA==.Sho:BAAALAADCggIEwABLAAFFAIIBgAZAAocAA==.Shozan:BAAALAAECgYICgABLAAECggIIAAHAAUjAA==.Shycera:BAAALAAECgMIAwABLAAECgcIGwATAGIeAA==.Shòóteçh:BAAALAAECgMIAgABLAAECggIIAAHAAUjAA==.',Si='Sickness:BAAALAAECggICwAAAA==.Siibbz:BAAALAADCgYIBgAAAA==.Siinister:BAABLAAECoEeAAIPAAgIrRKzYQD6AQAPAAgIrRKzYQD6AQAAAA==.Sikkz:BAAALAADCgcIBwABLAADCggICwAXAAAAAA==.Sineøchka:BAACLAAFFIEMAAIMAAIIsSV2HQDSAAAMAAIIsSV2HQDSAAAsAAQKgRUAAgwABghiJB46AD0CAAwABghiJB46AD0CAAAA.Sistaboss:BAACLAAFFIEFAAINAAII8Q5vFACSAAANAAII8Q5vFACSAAAsAAQKgR0AAg0ABwgGHGUiAB0CAA0ABwgGHGUiAB0CAAAA.',Sl='Slafsmorsan:BAAALAAECggIDgAAAA==.Slugg:BAABLAAECoEmAAIDAAgIoRvwFgCaAgADAAgIoRvwFgCaAgAAAA==.Slugtoad:BAAALAADCgMIAwAAAA==.Sluxinator:BAAALAAECgMIBwAAAA==.',Sm='Smexarn:BAAALAADCggICgAAAA==.Smexi:BAAALAADCggICgAAAA==.Smuel:BAAALAADCgIIAgABLAAECggIIgAWAE0kAA==.Smueleo:BAAALAADCggIDgABLAAECggIIgAWAE0kAA==.Smusker:BAAALAAECgMIBQAAAA==.Smärsken:BAABLAAECoEaAAIZAAgIfQwfRACbAQAZAAgIfQwfRACbAQAAAA==.',Sn='Snakestick:BAAALAAECgYIDAAAAA==.Sneakywe:BAAALAAECgUICQABLAAECggIBgAXAAAAAA==.',So='Somlog:BAAALAAECgQIBwAAAA==.Sonder:BAACLAAFFIEGAAIZAAIIChxpGgChAAAZAAIIChxpGgChAAAsAAQKgR8AAhkACAiNIOkNAOECABkACAiNIOkNAOECAAAA.Soraká:BAACLAAFFIEHAAILAAIISxiGJACRAAALAAIISxiGJACRAAAsAAQKgSIAAgsACAiVGu0mAE0CAAsACAiVGu0mAE0CAAAA.',Sp='Speedtroll:BAAALAADCggICAAAAA==.Sponk:BAABLAAECoEUAAIZAAYILhoSOgDIAQAZAAYILhoSOgDIAQAAAA==.',Sq='Squidgame:BAAALAAECgcIDQAAAA==.',St='Stankelkang:BAAALAAECgUIBQAAAA==.Stankylegz:BAAALAADCgEIAQAAAA==.Starbloom:BAAALAAECgYICQAAAA==.Stickyshot:BAAALAAECgYICAAAAA==.Stronkenmonk:BAAALAAECgMIAwAAAA==.Stryde:BAAALAADCggICAAAAA==.',Su='Summer:BAAALAAECgQIBAABLAAFFAIIBgAZAAocAA==.Supertom:BAABLAAECoEfAAILAAgIdBpsIwBdAgALAAgIdBpsIwBdAgAAAA==.Surnud:BAAALAAECgYIDAABLAAECggICgAXAAAAAA==.Surv:BAABLAAECoEjAAMRAAgIXx0tHQCuAgARAAcIviAtHQCuAgAYAAcIihINQgCPAQAAAA==.',Sy='Synjin:BAABLAAECoEfAAIfAAgIPyC7EQDqAgAfAAgIPyC7EQDqAgAAAA==.',Sz='Szaman:BAAALAAECgUIBQAAAA==.Szefandus:BAAALAADCgcIBwAAAA==.',['Sá']='Sárkhan:BAAALAAECgMIAwABLAAECggIFQAEAPokAA==.',['Sù']='Sùnzì:BAAALAAECgMICAAAAA==.',Ta='Tadi:BAAALAADCggIDwAAAA==.Taikajimi:BAAALAADCggICAAAAA==.Talaram:BAAALAADCgcIDgAAAA==.Tamran:BAAALAADCgEIAQAAAA==.Tanker:BAAALAADCgEIAQABLAADCgYIBgAXAAAAAA==.Tauro:BAABLAAECoEgAAMEAAgICiLZBwAAAwAEAAgICiLZBwAAAwAgAAIILw8gJgCLAAAAAA==.Taytaytay:BAAALAAECggIDwAAAA==.',Te='Tekis:BAAALAADCgYIBgAAAA==.Teyna:BAAALAADCgUIBQAAAA==.',Th='Tharan:BAAALAAECgYIEwAAAA==.Thelaria:BAAALAADCggIGQAAAA==.Thrumi:BAAALAAECggICgAAAA==.Thunderbul:BAABLAAECoEhAAMNAAcInBqkIAApAgANAAcInBqkIAApAgABAAQIYBlgbQADAQAAAA==.Thunderdemon:BAAALAAFFAIIAgAAAA==.Thûrim:BAAALAADCgYIBQAAAA==.',Ti='Timoni:BAABLAAECoEtAAIWAAgIXR7gBwDQAgAWAAgIXR7gBwDQAgAAAA==.Tinaly:BAAALAAECgIIAwAAAA==.',Tk='Tkk:BAAALAADCggICwAAAA==.',Tl='Tlock:BAAALAADCgcIBwAAAA==.Tlorem:BAABLAAECoElAAIBAAgIGxl8GgBhAgABAAgIGxl8GgBhAgAAAA==.',To='Tonkadin:BAABLAAECoEgAAIWAAcIkR+NDgB8AgAWAAcIkR+NDgB8AgAAAA==.Toutos:BAAALAAECgMIBgAAAA==.',Tr='Trulli:BAAALAAECgUICQAAAA==.Trôûî:BAAALAADCgMIAwAAAA==.',Tu='Tuatua:BAAALAADCgUIBQAAAA==.Tuck:BAABLAAECoEjAAIjAAgIuxXoEgAPAgAjAAgIuxXoEgAPAgAAAA==.Tullinkutina:BAAALAADCggIEAAAAA==.Turbob:BAAALAADCgYICgABLAAECggIIAAPAOkKAA==.Turskidan:BAAALAADCggIFgAAAA==.Tusinenkurri:BAAALAAECgYIBgAAAA==.',Tw='Twochainz:BAAALAAECgUIBQABLAAFFAIIBgABAEAPAA==.',Ty='Tyrra:BAAALAADCgcIBwAAAA==.',Ug='Ug:BAAALAAECgcIEQAAAA==.',Um='Umommon:BAAALAADCgcIDQAAAA==.',Un='Unchiufester:BAAALAAECgcIBwAAAA==.Undeadnoname:BAAALAAECggIAgAAAA==.Unknowndrago:BAAALAADCgIIAgAAAA==.',Uw='Uwuwubby:BAAALAAECgMIBAAAAA==.',Va='Valorite:BAAALAADCggICAABLAAECggIJAAFAIMjAA==.Valthor:BAABLAAECoEkAAMFAAgIgyMvCgA4AwAFAAgIgyMvCgA4AwAEAAMInxSjWgCoAAAAAA==.Valtura:BAABLAAECoEaAAIBAAcIASFsEwCVAgABAAcIASFsEwCVAgAAAA==.Vannos:BAABLAAECoEdAAMNAAgIKCRTBgA7AwANAAgIKCRTBgA7AwAhAAEIVAZzQQAlAAAAAA==.Varthdader:BAAALAADCggIFAAAAA==.Vasitanku:BAAALAADCgIIAgAAAA==.Vaílen:BAAALAADCggICAABLAAECggIGAASAIMUAA==.',Vc='Vcrina:BAABLAAECoEgAAMRAAgIyB+jFADjAgARAAgIyB+jFADjAgAYAAgIzxJiMwDTAQAAAA==.',Ve='Velanne:BAAALAADCggIDwAAAA==.Velarasilent:BAAALAAECgQIBwAAAA==.Venacavus:BAAALAAECgEIAQAAAA==.Venisia:BAAALAAECgcIBwAAAA==.Verihirvitys:BAAALAADCggICwAAAA==.Vestra:BAAALAAECgcIDQAAAA==.',Vi='Vilkey:BAACLAAFFIEJAAIYAAQIqCKnBQB9AQAYAAQIqCKnBQB9AQAsAAQKgR8AAhgACAjEJZ4FADcDABgACAjEJZ4FADcDAAEsAAUUBwgaABMACCIA.Vindicta:BAAALAADCgcICQAAAA==.Vindictus:BAAALAADCgcIBwAAAA==.Viruke:BAABLAAECoEZAAIZAAcINx2LIwA/AgAZAAcINx2LIwA/AgAAAA==.Vivaldi:BAAALAAECgYIBgABLAAECggIIgANAOghAA==.',Vo='Vocann:BAAALAAECggICAAAAA==.Voljinx:BAACLAAFFIEFAAIMAAIIlQ/tNwCQAAAMAAIIlQ/tNwCQAAAsAAQKgSYAAwwACAhTHUQuAHACAAwACAhTHUQuAHACACIABgidDcNLAA0BAAAA.Volscale:BAAALAAECggICAABLAAFFAIIBQAMAJUPAA==.Volseer:BAAALAAECggIBgAAAA==.Volzen:BAAALAAECggICAABLAAFFAIIBQAMAJUPAA==.Voodozarak:BAAALAAECgUIBgAAAA==.',Vr='Vr:BAAALAAECgQIAgABLAAECggIGAAGAL8TAA==.',Vy='Vyffel:BAAALAAECgYIDwAAAA==.Vylrea:BAAALAADCggICAAAAA==.',['Vå']='Vårtmuttan:BAABLAAECoEdAAICAAcIuB0hPQBUAgACAAcIuB0hPQBUAgAAAA==.',Wa='Wabshaman:BAABLAAECoEWAAISAAcIayDaBwBjAgASAAcIayDaBwBjAgAAAA==.',Wh='Whacko:BAAALAAECgcIEAAAAA==.Whitepaw:BAAALAAECgYIDAABLAAECggIKAAYAIwOAA==.',Wi='Windforce:BAAALAADCgMIAwAAAA==.Witwicky:BAAALAADCggICAABLAADCggICAAXAAAAAA==.Wizor:BAAALAAECgYIEQAAAA==.',Wj='Wjurt:BAAALAAECggIBgAAAA==.',Wl='Wlok:BAAALAAECgYICgABLAAECgYIFwARAD0OAA==.',Wu='Wupwup:BAAALAAECggIBwAAAA==.',Xi='Xirod:BAABLAAECoEbAAITAAcIYh6dJwB2AgATAAcIYh6dJwB2AgAAAA==.Xista:BAAALAADCgYIBgAAAA==.',Xm='Xmagnificent:BAAALAAECgQICAAAAA==.',['Xé']='Xéale:BAAALAAECgYIBgABLAAFFAMIBwATABUaAA==.',Ye='Yeezzus:BAAALAADCgcIBwAAAA==.Yespappi:BAAALAAECgMIAwABLAAFFAIICAATALojAA==.',Yi='Yiddies:BAAALAAECgEIAQABLAAFFAIIBgABAEAPAA==.',Yu='Yunalessca:BAABLAAECoEYAAIZAAgIDQ6MQACrAQAZAAgIDQ6MQACrAQAAAA==.',Za='Zama:BAAALAADCggIDwAAAA==.Zapi:BAACLAAFFIEGAAILAAIIlR1iHACpAAALAAIIlR1iHACpAAAsAAQKgRYAAgsABwiLG/42AA4CAAsABwiLG/42AA4CAAAA.Zardrok:BAAALAAECgcIBwAAAA==.Zarkhan:BAABLAAECoEVAAIEAAgI+iTTAwBEAwAEAAgI+iTTAwBEAwAAAA==.Zarod:BAABLAAECoEkAAISAAgIgCP8AgD+AgASAAgIgCP8AgD+AgAAAA==.Zath:BAAALAAECgYIEQAAAA==.Zayusha:BAAALAADCggICAAAAA==.',Ze='Zedar:BAAALAADCggICwABLAAECggICgAXAAAAAA==.Zedarz:BAAALAADCgUIBQABLAAECggICgAXAAAAAA==.Zedmoon:BAAALAAECgYIDgABLAAECggICgAXAAAAAA==.Zedshammy:BAAALAADCgEIAQABLAAECggICgAXAAAAAA==.',Zh='Zharkan:BAAALAAECgcIBwABLAAECggIFQAEAPokAA==.',Zi='Zikao:BAAALAAECgQIEQAAAA==.',Zl='Zlatizlatev:BAAALAADCgYIAwABLAAECgIIAgAXAAAAAA==.',Zo='Zozomatcha:BAAALAADCgcICAAAAA==.',Zu='Zum:BAAALAAECgUIBQAAAA==.',['Zé']='Zéd:BAAALAAECgYICQAAAA==.',['Èa']='Èarthen:BAABLAAECoEoAAIYAAgIjA4LSAB2AQAYAAgIjA4LSAB2AQAAAA==.',['Éo']='Éowyn:BAABLAAECoEdAAIBAAgIZwrFVABPAQABAAgIZwrFVABPAQAAAA==.',['Ín']='Ínternet:BAAALAADCggIDAAAAA==.',['Óp']='Ópe:BAABLAAECoEaAAIRAAgIexm7NQA7AgARAAgIexm7NQA7AgAAAA==.',['Ög']='Ögö:BAAALAADCgcIDQAAAA==.',['Ök']='Ökö:BAAALAAECgMIAwAAAA==.',['Öl']='Ölö:BAAALAAECgYIEwAAAA==.',['Úr']='Úranus:BAAALAAECggICAAAAA==.',['ßa']='ßallz:BAABLAAECoEdAAMBAAcIzh+KGQBnAgABAAcIzh+KGQBnAgANAAUI6BGYVgAYAQAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end