local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Mage-Arcane','Mage-Frost','Druid-Feral','Paladin-Holy','Paladin-Retribution','Shaman-Elemental','Mage-Fire','Warrior-Protection','Evoker-Devastation','Druid-Restoration','Druid-Guardian','Priest-Shadow','DemonHunter-Havoc','Unknown-Unknown','Paladin-Protection','DeathKnight-Unholy','DeathKnight-Blood','Monk-Windwalker','Monk-Mistweaver','Warlock-Destruction','Warlock-Demonology','Warlock-Affliction','DemonHunter-Vengeance','Shaman-Restoration','Priest-Holy','Warrior-Fury','DeathKnight-Frost','Hunter-BeastMastery','Hunter-Marksmanship','Hunter-Survival',}; local provider = {region='EU',realm='Draenor',name='EU',type='subscribers',zone=44,date='2025-09-06',data={Ai='Airigal:BAEBLAAECoEcAAMBAAgI7SGgCgAOAwg5DAAABABfADsMAAAEAF4AOgwAAAQAXQA8DAAABABYADIMAAAEAF8APQwAAAQAYgA+DAAAAwBFAD8MAAABADsAAQAICG0hoAoADgMIOQwAAAMAXwA7DAAAAwBeADoMAAADAF0APAwAAAMAWAAyDAAAAwBfAD0MAAADAFcAPgwAAAMARQA/DAAAAQA7AAIABghuH/AdAKMBBjkMAAABAEcAOwwAAAEAVgA6DAAAAQBGADwMAAABAEEAMgwAAAEAWgA9DAAAAQBiAAAA.',Ar='Arramii:BAEBLAAECoEXAAIDAAgIaR58BgCKAgg5DAAAAwBbADsMAAADAF0AOgwAAAMARwA8DAAAAwBNADIMAAADAEcAPQwAAAMAWAA+DAAAAwBVAD8MAAACACwAAwAICGkefAYAigIIOQwAAAMAWwA7DAAAAwBdADoMAAADAEcAPAwAAAMATQAyDAAAAwBHAD0MAAADAFgAPgwAAAMAVQA/DAAAAgAsAAAA.Aruthas:BAEBLAAECoEaAAMEAAgIEiV6AABZAwg5DAAABABiADsMAAAEAFoAOgwAAAMAYgA8DAAABABiADIMAAAEAGAAPQwAAAQAYgA+DAAAAgBiAD8MAAABAE8ABAAICBIlegAAWQMIOQwAAAMAYgA7DAAAAwBaADoMAAACAGIAPAwAAAIAYgAyDAAAAwBgAD0MAAADAGIAPgwAAAIAYgA/DAAAAQBPAAUABggSDu1zADMBBjkMAAABADkAOwwAAAEAAQA6DAAAAQATADwMAAACAC4AMgwAAAEAJAA9DAAAAQA3AAAA.',As='Asythe:BAECLAAFFIEGAAIGAAMIVxC+BgD3AAM5DAAAAQAlADsMAAACABwAOgwAAAMAOwAGAAMIVxC+BgD3AAM5DAAAAQAlADsMAAACABwAOgwAAAMAOwAsAAQKgRUAAgYACAh4HvcRAJYCAAYACAh4HvcRAJYCAAAA.',At='Aterno:BAECLAAFFIEKAAIBAAQIrhWUBABbAQQ5DAAAAwA9ADsMAAADAEQAOgwAAAMAPQA8DAAAAQAfAAEABAiuFZQEAFsBBDkMAAADAD0AOwwAAAMARAA6DAAAAwA9ADwMAAABAB8ALAAECoEfAAMBAAgIcyNXCwAHAwABAAgIcyNXCwAHAwAHAAEI2B04DwBYAAAAAA==.',Ba='Baldalpha:BAEALAAFFAIIAgABLAAFFAMICQAIAJQcAA==.',Bl='Blinkondeez:BAEALAADCggICQAAAA==.',Bn='Bnoce:BAEBLAAECoEbAAIJAAcIXCNUCQDFAgc5DAAABABeADsMAAAEAFoAOgwAAAQAWQA8DAAABABdADIMAAAEAF8APQwAAAQAVgA+DAAAAwBSAAkABwhcI1QJAMUCBzkMAAAEAF4AOwwAAAQAWgA6DAAABABZADwMAAAEAF0AMgwAAAQAXwA9DAAABABWAD4MAAADAFIAAAA=.',['Bø']='Børissha:BAEALAAECggICAAAAA==.',Ca='Carydru:BAEBLAAECoEXAAMKAAcIzSHvCQCeAgc5DAAABABQADsMAAAEAFsAOgwAAAQAXwA8DAAAAwBGADIMAAADAFYAPQwAAAMAYwA+DAAAAgBSAAoABwjNIe8JAJ4CBzkMAAACAFAAOwwAAAIAWwA6DAAAAgBfADwMAAACAEYAMgwAAAMAVgA9DAAAAwBjAD4MAAACAFIACwAECGsdTQsAQgEEOQwAAAIAXQA7DAAAAgBRADoMAAACACcAPAwAAAEAVgAAAA==.',Ce='Cealian:BAEBLAAECoEWAAIMAAgI0RWCHgACAgg5DAAAAwBCADsMAAADAFMAOgwAAAMAMgA8DAAAAwA8ADIMAAADADEAPQwAAAMATgA+DAAAAwAsAD8MAAABAAwADAAICNEVgh4AAgIIOQwAAAMAQgA7DAAAAwBTADoMAAADADIAPAwAAAMAPAAyDAAAAwAxAD0MAAADAE4APgwAAAMALAA/DAAAAQAMAAAA.',Ci='Cianohd:BAEALAAFFAIIAwAAAQ==.Cif:BAEALAAFFAYIDgAAAQ==.',Co='Coeles:BAEALAADCgYIBgABLAAECggIIwANAJIjAA==.',['Cì']='Cìan:BAEALAAECgcICQABLAAFFAIIAwAOAAAAAA==.',De='Deadnowred:BAEALAAECgEIAQABLAAFFAMICQAIAJQcAA==.Deetailpal:BAECLAAFFIEIAAIPAAMIqQ1EAwDFAAM5DAAAAwAzADsMAAACAAoAOgwAAAMAKgAPAAMIqQ1EAwDFAAM5DAAAAwAzADsMAAACAAoAOgwAAAMAKgAsAAQKgSAAAg8ACAjwHlgFALwCAA8ACAjwHlgFALwCAAAA.Deymerah:BAEALAADCgUIBQAAAA==.',Do='Dottyton:BAEALAADCgEIAQABLAAFFAQICQADAD4aAA==.',Dr='Dragonjizz:BAEALAADCgcIBwABLAAFFAQICgANABEmAA==.Draugrr:BAEBLAAECoEjAAINAAgIkiO/BgA9Awg5DAAABQBjADsMAAAFAGMAOgwAAAUAWQA8DAAABQBUADIMAAAEAFEAPQwAAAQAXwA+DAAABABVAD8MAAADAFwADQAICJIjvwYAPQMIOQwAAAUAYwA7DAAABQBjADoMAAAFAFkAPAwAAAUAVAAyDAAABABRAD0MAAAEAF8APgwAAAQAVQA/DAAAAwBcAAAA.',Du='Dumbassdh:BAEALAAECggIDgABLAAFFAEIAQAOAAAAAA==.Dumbassdk:BAEBLAAECoEYAAMQAAgItiLqAgAKAwg5DAAAAwBdADsMAAADAF8AOgwAAAMAXwA8DAAAAwBPADIMAAADAF8APQwAAAMAVwA+DAAAAwBUAD8MAAADAFAAEQAICP8hZwIAKQMIOQwAAAEAWgA7DAAAAQBfADoMAAABAF8APAwAAAEATAAyDAAAAQBfAD0MAAABAFcAPgwAAAEAUQA/DAAAAQBKABAACAjLIeoCAAoDCDkMAAACAF0AOwwAAAIAWgA6DAAAAgBdADwMAAACAE8AMgwAAAIAXgA9DAAAAgBKAD4MAAACAFQAPwwAAAIAUAABLAAFFAEIAQAOAAAAAA==.',Ei='Eithest:BAEBLAAECoEbAAMSAAgISxz4BwCsAgg5DAAABABbADsMAAAEAFsAOgwAAAQAXQA8DAAABABPADIMAAAEAE8APQwAAAQAPwA+DAAAAgA3AD8MAAABABgAEgAICEsc+AcArAIIOQwAAAQAWwA7DAAABABbADoMAAAEAF0APAwAAAQATwAyDAAAAwBPAD0MAAAEAD8APgwAAAIANwA/DAAAAQAYABMAAQhOBMU0ACYAATIMAAABAAsAAAA=.',El='Elejul:BAEALAAECgYIDAABLAAFFAIIBAAOAAAAAA==.',Es='Esdos:BAEALAAECgYIDAABLAAFFAMIBgAGAFcQAA==.',Fa='Fademeirl:BAEALAADCgUIBQAAAA==.Fastwarlock:BAEBLAAECoEdAAQUAAgIhyIGBwAfAwg5DAAABABdADsMAAAEAFwAOgwAAAQAYgA8DAAABABTADIMAAAEAFUAPQwAAAQAWQA+DAAAAwBYAD8MAAACAEwAFAAICIciBgcAHwMIOQwAAAMAXQA7DAAAAwBcADoMAAADAGIAPAwAAAMAUwAyDAAAAwBVAD0MAAADAFkAPgwAAAMAWAA/DAAAAgBMABUABQhVFfAxADQBBTkMAAABAFQAOwwAAAEARQA6DAAAAQAIADwMAAABAEYAPQwAAAEAJwAWAAEIwRO6LABNAAEyDAAAAQAyAAAA.',Fe='Fearlesspala:BAEALAADCggICwABLAAECgYIFAAXAPQkAA==.Fearlessprot:BAEALAADCggICAABLAAECgYIFAAXAPQkAA==.Fearlessveng:BAEBLAAECoEUAAIXAAYI9CTKBgB0AgY5DAAABABgADsMAAAEAGEAOgwAAAMAXgA8DAAAAwBfADIMAAAEAFoAPQwAAAIAXAAXAAYI9CTKBgB0AgY5DAAABABgADsMAAAEAGEAOgwAAAMAXgA8DAAAAwBfADIMAAAEAFoAPQwAAAIAXAAAAA==.Felmonky:BAEALAAECgcIBwABLAAECgcIEgAOAAAAAA==.Feltroc:BAEALAAECgcIEgAAAA==.',Fo='Foggyphil:BAEBLAAECoEWAAITAAcI1R98BwCIAgc5DAAABABiADsMAAADAFkAOgwAAAQAWQA8DAAAAwBdADIMAAADAEoAPQwAAAMAXQA+DAAAAgAgABMABwjVH3wHAIgCBzkMAAAEAGIAOwwAAAMAWQA6DAAABABZADwMAAADAF0AMgwAAAMASgA9DAAAAwBdAD4MAAACACAAAAA=.',Fr='Framdir:BAEALAADCgEIAQABLAADCggICgAOAAAAAA==.Framwar:BAEALAADCggICgAAAA==.Frozelma:BAEALAAECgQIBAAAAA==.Frèyjá:BAEALAAECgYICAABLAAFFAIIBQAFAHkWAA==.',Ga='Gamzele:BAEALAAFFAIIAgABLAAFFAMIBQAJADUhAA==.Gamzrage:BAEALAADCggICAABLAAFFAMIBQAJADUhAA==.Gamzrat:BAEBLAAECoEWAAMUAAgIGRbUKQDrAQg5DAAAAwA7ADsMAAADADcAOgwAAAMARQA8DAAAAwBGADIMAAADADwAPQwAAAMAKAA+DAAAAgAiAD8MAAACAD0AFAAHCJAU1CkA6wEHOQwAAAIAOwA7DAAAAgA3ADwMAAACAEYAMgwAAAMAPAA9DAAAAQAoAD4MAAABABMAPwwAAAIAPQAVAAYIAxCUIQCRAQY5DAAAAQAxADsMAAABADIAOgwAAAMARQA8DAAAAQAbAD0MAAACAA4APgwAAAEAIgABLAAFFAMIBQAJADUhAA==.Gaumgz:BAECLAAFFIEFAAIJAAMINSGDAwAqAQM5DAAAAgBUADsMAAABAFkAOgwAAAIAUAAJAAMINSGDAwAqAQM5DAAAAgBUADsMAAABAFkAOgwAAAIAUAAsAAQKgR8AAgkACAiiJAACAFYDAAkACAiiJAACAFYDAAAA.',Gr='Grimmalf:BAEALAAECgMIBAABLAAFFAMICQAYAFIiAA==.Grippyton:BAEALAADCggICAABLAAFFAQICQADAD4aAA==.',Ha='Happyton:BAECLAAFFIEJAAIDAAQIPhqxAAByAQQ5DAAAAwBMADsMAAACADkAOgwAAAIALAA8DAAAAgBaAAMABAg+GrEAAHIBBDkMAAADAEwAOwwAAAIAOQA6DAAAAgAsADwMAAACAFoALAAECoEYAAMDAAgIayCyAwDpAgADAAgIayCyAwDpAgALAAIIEBHjFgBoAAAAAA==.',He='Heeimdall:BAEALAADCggIEAABLAAECggIIwANAJIjAA==.',Ho='Hodevine:BAECLAAFFIEJAAIYAAMIUiKgAgAvAQM5DAAAAwBYADsMAAADAE4AOgwAAAMAYQAYAAMIUiKgAgAvAQM5DAAAAwBYADsMAAADAE4AOgwAAAMAYQAsAAQKgSAAAxgACAj1JVkBAEoDABgACAj1JVkBAEoDAAYACAjTGm4RAJwCAAAA.Hollieta:BAEALAAECgIIAgAAAA==.',['Hä']='Häkoom:BAEALAADCggIGAAAAA==.Häkoöm:BAEALAADCgcIBwABLAADCggIGAAOAAAAAA==.',Ig='Ignorepainal:BAECLAAFFIEJAAIIAAMIlBy8AgADAQM5DAAAAwBIADsMAAADAE0AOgwAAAMARQAIAAMIlBy8AgADAQM5DAAAAwBIADsMAAADAE0AOgwAAAMARQAsAAQKgRgAAggACAgTIf4EAO4CAAgACAgTIf4EAO4CAAAA.',In='Indifrost:BAEALAAECgYIBgAAAA==.Indirid:BAEALAADCggIFgABLAAECgYIBgAOAAAAAA==.Invokeblob:BAEALAAECgYICgABLAAFFAMICQAIAJQcAA==.',It='Itadorí:BAEBLAAECoEeAAIGAAgIkx25DgC+Agg5DAAABABWADsMAAAEAFgAOgwAAAQAWwA8DAAABABMADIMAAAEAEIAPQwAAAQAVQA+DAAAAwBAAD8MAAADAC0ABgAICJMduQ4AvgIIOQwAAAQAVgA7DAAABABYADoMAAAEAFsAPAwAAAQATAAyDAAABABCAD0MAAAEAFUAPgwAAAMAQAA/DAAAAwAtAAAA.',Ix='Ix:BAEBLAAECoEUAAIJAAcImh/JDACLAgc5DAAABABNADsMAAAEAFcAOgwAAAQAXAA8DAAAAgBbADIMAAACAFsAPQwAAAIANAA+DAAAAgBIAAkABwiaH8kMAIsCBzkMAAAEAE0AOwwAAAQAVwA6DAAABABcADwMAAACAFsAMgwAAAIAWwA9DAAAAgA0AD4MAAACAEgAAAA=.',Ja='Jaimeey:BAEBLAAECoEgAAMXAAgIOCSpAQA5Awg5DAAABABiADsMAAAEAGAAOgwAAAQAYQA8DAAABABgADIMAAAEAFgAPQwAAAQAWgA+DAAABQBgAD8MAAADAEwAFwAICGEjqQEAOQMIOQwAAAEAYgA7DAAAAQBgADoMAAABAFAAPAwAAAEAYAAyDAAAAQBYAD0MAAABAFoAPgwAAAEAYAA/DAAAAgBMAA0ACAjpHkcWAKwCCDkMAAADAGIAOwwAAAMAVAA6DAAAAwBhADwMAAADAEkAMgwAAAMAVQA9DAAAAwBVAD4MAAAEAEMAPwwAAAEAKQAAAA==.',Je='Jekkot:BAECLAAFFIEGAAIZAAMIgCPdAgA+AQM5DAAAAgBeADsMAAACAFYAOgwAAAIAWwAZAAMIgCPdAgA+AQM5DAAAAgBeADsMAAACAFYAOgwAAAIAWwAsAAQKgSEAAhkACAgSINsJAMwCABkACAgSINsJAMwCAAAA.Jekkotdruid:BAEALAADCggIDwABLAAFFAMIBgAZAIAjAA==.Jesterdisc:BAEALAAECggIEgABLAAECggIIwANAJIjAA==.Jeywl:BAEALAADCgcIBwABLAAECggIFgAaAAEhAA==.Jeywr:BAEBLAAECoEWAAIaAAgIASGmEACvAgg5DAAAAwBaADsMAAADAFoAOgwAAAMAUgA8DAAAAwBJADIMAAADAF0APQwAAAMAXAA+DAAAAgBQAD8MAAACAEgAGgAICAEhphAArwIIOQwAAAMAWgA7DAAAAwBaADoMAAADAFIAPAwAAAMASQAyDAAAAwBdAD0MAAADAFwAPgwAAAIAUAA/DAAAAgBIAAAA.',Kh='Khymss:BAEALAADCgcIBwAAAA==.',Kj='Kjordlack:BAEALAADCgcICgAAAA==.',Kr='Kriptas:BAEALAAECgcIDAABLAAFFAUIDgAJAEscAA==.',Mo='Modsognir:BAEBLAAECoEUAAIGAAgIdSFRCAARAwg5DAAAAwBeADsMAAADAF4AOgwAAAMASAA8DAAAAwBdADIMAAACAEsAPQwAAAIAYAA+DAAAAgBPAD8MAAACAE8ABgAICHUhUQgAEQMIOQwAAAMAXgA7DAAAAwBeADoMAAADAEgAPAwAAAMAXQAyDAAAAgBLAD0MAAACAGAAPgwAAAIATwA/DAAAAgBPAAAA.Monksad:BAEALAAECgQIBgABLAAECggIIAAXADgkAA==.',Ni='Nightpixxi:BAEALAADCgcIBwAAAA==.',Oa='Oagol:BAEALAAECgYICAABLAAECggIHAAZAO8kAA==.',Oi='Oithest:BAEALAADCggIDgABLAAECggIGwASAEscAA==.',Os='Osmodeus:BAEALAADCgUIBQABLAAECggIHAABAO0hAA==.',Pa='Paceem:BAEALAADCggIDwABLAAECggIIwANAJIjAA==.Panion:BAEALAADCggIBwAAAA==.',Pe='Pestilenciaa:BAEALAAECggICAABLAAECggIIwANAJIjAA==.',Ph='Philpo:BAEALAADCggIDwABLAAECgcIFgATANUfAA==.Phry:BAEALAAECgcIFwAAAQ==.Phílídan:BAEALAADCggICAABLAAECgcIFgATANUfAA==.',Pi='Piantus:BAEALAADCgcIBwABLAAFFAIIBQABABwbAA==.',Pr='Profana:BAEALAADCggIEQABLAAECggIIwANAJIjAA==.Promidr:BAEALAAECggICAAAAA==.Prophetam:BAEALAAECggICwABLAAECggIIwANAJIjAA==.Pryde:BAECLAAFFIEKAAIbAAQIHx1YAgCAAQQ5DAAAAwBYADsMAAACAEMAOgwAAAMASwA8DAAAAgBCABsABAgfHVgCAIABBDkMAAADAFgAOwwAAAIAQwA6DAAAAwBLADwMAAACAEIALAAECoEfAAIbAAgIJSWsBABHAwAbAAgIJSWsBABHAwAAAA==.',Ra='Rabobrew:BAEALAAECggIEAABLAAECggIHwAIAMciAA==.Raboclap:BAEBLAAECoEfAAIIAAgIxyIeAwAlAwg5DAAABQBiADsMAAAFAF8AOgwAAAUAWAA8DAAABABVADIMAAAEAF0APQwAAAQAXwA+DAAAAwBgAD8MAAABADkACAAICMciHgMAJQMIOQwAAAUAYgA7DAAABQBfADoMAAAFAFgAPAwAAAQAVQAyDAAABABdAD0MAAAEAF8APgwAAAMAYAA/DAAAAQA5AAAA.Rabodh:BAEALAADCggIEAABLAAECggIHwAIAMciAA==.Radleed:BAECLAAFFIEGAAIcAAMI6SExAgA0AQM5DAAAAgBQADsMAAACAFEAOgwAAAIAYgAcAAMI6SExAgA0AQM5DAAAAgBQADsMAAACAFEAOgwAAAIAYgAsAAQKgRUAAhwACAjqJHEDAE4DABwACAjqJHEDAE4DAAAA.Rashiido:BAEALAAECgYIEwAAAA==.',Re='Reeikeen:BAEALAADCggICAABLAAECggIHQAPAFAmAA==.Reiken:BAEBLAAECoEdAAIPAAgIUCZ4AACEAwg5DAAABABiADsMAAAEAGIAOgwAAAQAYwA8DAAABABhADIMAAAEAGMAPQwAAAQAXwA+DAAAAwBiAD8MAAACAGEADwAICFAmeAAAhAMIOQwAAAQAYgA7DAAABABiADoMAAAEAGMAPAwAAAQAYQAyDAAABABjAD0MAAAEAF8APgwAAAMAYgA/DAAAAgBhAAAA.',Ro='Rosallyne:BAEALAADCggICAABLAAFFAUIDgAJAEscAA==.Rosallynee:BAECLAAFFIEOAAIJAAUISxxQAQDqAQU5DAAABABeADsMAAADAFAAOgwAAAMAUQA8DAAAAgAyAD0MAAACADcACQAFCEscUAEA6gEFOQwAAAQAXgA7DAAAAwBQADoMAAADAFEAPAwAAAIAMgA9DAAAAgA3ACwABAqBFwACCQAICAUlUgQAIgMACQAICAUlUgQAIgMAAAA=.',Ru='Rubm:BAEALAAECgYIBwABLAAFFAMIBQAaALcVAA==.Rubzim:BAEALAAECgQIAgABLAAFFAMIBQAaALcVAA==.Rubziw:BAEBLAAFFIEFAAIaAAMItxXSBgABAQM5DAAAAQAHADsMAAACAFUAOgwAAAIASQAaAAMItxXSBgABAQM5DAAAAQAHADsMAAACAFUAOgwAAAIASQAAAA==.',Sa='Savagecharge:BAECLAAFFIEQAAIIAAYIqBS7AAD5AQY5DAAABABQADsMAAADADwAOgwAAAQAPwA8DAAAAgA0ADIMAAABAAAAPQwAAAIAOwAIAAYIqBS7AAD5AQY5DAAABABQADsMAAADADwAOgwAAAQAPwA8DAAAAgA0ADIMAAABAAAAPQwAAAIAOwAsAAQKgRgAAggACAhcHosJAIMCAAgACAhcHosJAIMCAAAA.Savagecurse:BAEALAAECgcIDQABLAAFFAYIEAAIAKgUAA==.Savagefu:BAEALAAECggIDAABLAAFFAYIEAAIAKgUAA==.Savagerune:BAEALAAECgIIAwABLAAFFAYIEAAIAKgUAA==.',Se='Sethasdh:BAEALAAECgYIEgABLAAFFAEIAQAOAAAAAA==.Sethasdn:BAEALAAFFAEIAQAAAA==.Sethash:BAEALAADCggIEQABLAAFFAEIAQAOAAAAAA==.Sethasmf:BAEBLAAECoEgAAIQAAgI8iLSAQAyAwg5DAAABABXADsMAAAEAF8AOgwAAAQAWAA8DAAABABgADIMAAAEAF8APQwAAAQAUQA+DAAABABVAD8MAAAEAFYAEAAICPIi0gEAMgMIOQwAAAQAVwA7DAAABABfADoMAAAEAFgAPAwAAAQAYAAyDAAABABfAD0MAAAEAFEAPgwAAAQAVQA/DAAABABWAAEsAAUUAQgBAA4AAAAA.Sethasthree:BAEBLAAECoEcAAMQAAgI5CLMAgANAwg5DAAABABfADsMAAAEAFoAOgwAAAQAWQA8DAAABABeADIMAAADAGAAPQwAAAMAQwA+DAAAAwBbAD8MAAADAFkAEAAICOQizAIADQMIOQwAAAMAXwA7DAAAAwBaADoMAAADAFkAPAwAAAMAXgAyDAAAAwBgAD0MAAADAEMAPgwAAAMAWwA/DAAAAwBZABEABAieF+obAM4ABDkMAAABAEUAOwwAAAEAPAA6DAAAAQAxADwMAAABAD0AASwABRQBCAEADgAAAAA=.Sethastwo:BAEBLAAECoEcAAMRAAgIciJfAgAsAwg5DAAABABZADsMAAAEAF8AOgwAAAQAWQA8DAAABABbADIMAAADAGAAPQwAAAMAVQA+DAAAAwBQAD8MAAADAEwAEQAICHIiXwIALAMIOQwAAAMAWQA7DAAAAwBfADoMAAADAFkAPAwAAAMAWwAyDAAAAgBgAD0MAAACAFUAPgwAAAIAUAA/DAAAAgBMABAACAjRFzcLADgCCDkMAAABAD8AOwwAAAEATAA6DAAAAQA2ADwMAAABAFMAMgwAAAEAQgA9DAAAAQAnAD4MAAABADAAPwwAAAEANwABLAAFFAEIAQAOAAAAAA==.Sethasuwu:BAEALAADCggIEAABLAAFFAEIAQAOAAAAAA==.Sethasw:BAEALAAECggICAABLAAFFAEIAQAOAAAAAA==.Sethaszug:BAEALAAECggICAABLAAFFAEIAQAOAAAAAA==.',Sg='Sgthappy:BAEALAADCggICAABLAAFFAQICQADAD4aAA==.',Sh='Shamspriest:BAEALAAFFAMIAwAAAA==.Sharapriest:BAEBLAAECoEcAAIZAAgI7yQLAwA2Awg5DAAABABjADsMAAAEAGEAOgwAAAQAWgA8DAAABABgADIMAAAEAGAAPQwAAAMAUQA+DAAAAwBhAD8MAAACAGEAGQAICO8kCwMANgMIOQwAAAQAYwA7DAAABABhADoMAAAEAFoAPAwAAAQAYAAyDAAABABgAD0MAAADAFEAPgwAAAMAYQA/DAAAAgBhAAAA.Sharaqui:BAEALAAECgEIAQABLAAECggIHAAZAO8kAA==.',Sk='Skoobs:BAEALAADCgEIAQAAAA==.',So='Sorfospriest:BAEALAADCgQIBAAAAA==.',Sp='Sparkáh:BAEBLAAECoEoAAQUAAgIkhvyEwCUAgg5DAAABwBaADsMAAAHAFgAOgwAAAYAWQA8DAAABgBDADIMAAAHAE8APQwAAAQASwA+DAAAAgAvAD8MAAABABgAFAAICJAZ8hMAlAIIOQwAAAQAUgA7DAAABABRADoMAAAEAFkAPAwAAAQAQwAyDAAABQBPAD0MAAABADEAPgwAAAIALwA/DAAAAQAYABYABQjnEOoQAFUBBTkMAAABACgAOwwAAAEALQA6DAAAAgAuADwMAAACABEAMgwAAAIAQQAVAAMILyF3OgACAQM5DAAAAgBaADsMAAACAFgAPQwAAAMASwAAAA==.',Sq='Squirtwars:BAEALAAECggICAABLAAFFAMICQAIAJQcAA==.',St='Stonebraid:BAECLAAFFIEFAAMFAAIIeRY6DgCrAAI5DAAAAwBOADoMAAACACQABQACCHkWOg4AqwACOQwAAAIATgA6DAAAAgAkAAQAAQgMAkoOAEUAATkMAAABAAUALAAECoEgAAIFAAgIWiSHBgBDAwAFAAgIWiSHBgBDAwAAAA==.',Sw='Swalen:BAEBLAAECoEfAAIZAAgITyN8AwAuAwg5DAAABABhADsMAAAEAGIAOgwAAAQAVwA8DAAABABeADIMAAAEAFEAPQwAAAQAXQA+DAAABABeAD8MAAADAEsAGQAICE8jfAMALgMIOQwAAAQAYQA7DAAABABiADoMAAAEAFcAPAwAAAQAXgAyDAAABABRAD0MAAAEAF0APgwAAAQAXgA/DAAAAwBLAAAA.',Sy='Systemdh:BAEALAAECgQIBAABLAAECggIEwAOAAAAAA==.Systemonk:BAEALAAECggIEwAAAA==.Systemsham:BAEALAAECgYIBgABLAAECggIEwAOAAAAAA==.',['Sï']='Sïncrêst:BAEBLAAECoEaAAIcAAgIECOgBQAvAwg5DAAAAwBjADsMAAAEAGIAOgwAAAQAYwA8DAAAAwBWADIMAAAEAFkAPQwAAAQAXQA+DAAAAwBRAD8MAAABAEUAHAAICBAjoAUALwMIOQwAAAMAYwA7DAAABABiADoMAAAEAGMAPAwAAAMAVgAyDAAABABZAD0MAAAEAF0APgwAAAMAUQA/DAAAAQBFAAAA.',Ta='Talulah:BAEALAAECgIIAgABLAAECggIJgAdAMMmAA==.',Te='Tembski:BAEALAADCgcIBwABLAAFFAUICwAeAAceAA==.Temski:BAECLAAFFIELAAIeAAUIBx4HAAAYAgU5DAAAAwBgADsMAAADAFIAOgwAAAMAWwA8DAAAAQBGAD0MAAABACoAHgAFCAceBwAAGAIFOQwAAAMAYAA7DAAAAwBSADoMAAADAFsAPAwAAAEARgA9DAAAAQAqACwABAqBIAAEHgAICEMmFQAAkQMAHgAICEMmFQAAkQMAHQAFCH0TykcA7wAAHAABCDEm44UAZAAAAAA=.Temskilok:BAEALAAFFAIIBAABLAAFFAUICwAeAAceAA==.Temskiw:BAEALAADCgcIDQABLAAFFAUICwAeAAceAA==.',Th='Thagerian:BAEALAADCgcICAAAAA==.Thicra:BAEBLAAECoEaAAQUAAgIGiNJEQCuAgg5DAAABABiADsMAAAEAF8AOgwAAAQAXgA8DAAAAwBUADIMAAADAFsAPQwAAAMAVAA+DAAAAwBaAD8MAAACAE4AFAAICLYdSREArgIIOQwAAAEACAA7DAAAAQBPADoMAAACAFoAPAwAAAEAVAAyDAAAAgBbAD0MAAACAFQAPgwAAAMAWgA/DAAAAgBOABYABgjUG0oHAAsCBjkMAAADAGIAOwwAAAMAXwA6DAAAAQAnADwMAAACAD4AMgwAAAEAOgA9DAAAAQBJABUAAQjQJHZZAGQAAToMAAABAF4AAAA=.Thîñgêÿ:BAECLAAFFIEFAAIcAAMIOBZuAwAPAQM5DAAAAgAfADsMAAABACoAOgwAAAIAYAAcAAMIOBZuAwAPAQM5DAAAAgAfADsMAAABACoAOgwAAAIAYAAsAAQKgR8AAhwACAgFI0wEAEEDABwACAgFI0wEAEEDAAAA.',['Tá']='Tálulah:BAEBLAAECoEmAAMdAAgIwyYsAACMAwg5DAAABQBjADsMAAAGAGMAOgwAAAcAYwA8DAAABABhADIMAAAEAGMAPQwAAAQAYwA+DAAAAgBjAD8MAAAGAGMAHQAICMMmLAAAjAMIOQwAAAUAYwA7DAAABQBjADoMAAAGAGMAPAwAAAQAYQAyDAAAAwBjAD0MAAAEAGMAPgwAAAIAYwA/DAAAAwBjABwABAjMF1xdABEBBDsMAAABADEAOgwAAAEAJQAyDAAAAQA6AD8MAAADAGEAAAA=.',Ul='Ulwen:BAEALAAECgYIBgABLAAECggIHwAZAE8jAA==.',Ut='Utlagatus:BAEALAADCggICAABLAAECggIIwANAJIjAA==.',Ve='Veepz:BAEALAADCggIFwABLAAECggIGAAYAI8VAA==.Vehirion:BAEALAADCgcIBwABLAAECgcIFAAdAAEaAA==.Vehiron:BAEBLAAECoEUAAMdAAcIARonIADhAQc5DAAAAwBVADsMAAADAFEAOgwAAAMAVwA8DAAAAwA0ADIMAAADAEAAPQwAAAMARwA+DAAAAgAXAB0ABwidFycgAOEBBzkMAAADAFUAOwwAAAMAUQA6DAAAAgBXADwMAAACADQAMgwAAAEAFQA9DAAAAwBHAD4MAAACABcAHAADCLYRNXAAtwADOgwAAAEAPgA8DAAAAQAIADIMAAACAEAAAAA=.Veodh:BAEALAADCgYIBgABLAAECggIGAAYAI8VAA==.Veotem:BAEBLAAECoEYAAIYAAgIjxW+JQDzAQg5DAAABABQADsMAAAEAEoAOgwAAAQAKgA8DAAAAwAaADIMAAADACMAPQwAAAMAQwA+DAAAAgA2AD8MAAABADwAGAAICI8VviUA8wEIOQwAAAQAUAA7DAAABABKADoMAAAEACoAPAwAAAMAGgAyDAAAAwAjAD0MAAADAEMAPgwAAAIANgA/DAAAAQA8AAAA.',Vo='Voodiw:BAECLAAFFIEKAAIUAAQINhv2AwB4AQQ5DAAAAwA/ADsMAAADAEAAOgwAAAMAQgA8DAAAAQBUABQABAg2G/YDAHgBBDkMAAADAD8AOwwAAAMAQAA6DAAAAwBCADwMAAABAFQALAAECoEfAAMUAAgIZyStBAA9AwAUAAgIZyStBAA9AwAVAAMIbxkoRgC/AAAAAA==.',Xa='Xarenara:BAEALAAECgUIBQABLAAFFAIIBQABABwbAA==.',Xe='Xerkbeam:BAECLAAFFIEKAAINAAQIESb6AQDGAQQ5DAAABABjADsMAAADAGMAOgwAAAIAYQA8DAAAAQBdAA0ABAgRJvoBAMYBBDkMAAAEAGMAOwwAAAMAYwA6DAAAAgBhADwMAAABAF0ALAAECoEYAAINAAgIyiYyAQCCAwANAAgIyiYyAQCCAwAAAA==.Xerkbeaz:BAEALAADCgEIAQABLAAFFAQICgANABEmAA==.Xerkpal:BAEALAADCggIEAABLAAFFAQICgANABEmAA==.',Xi='Xiage:BAECLAAFFIEFAAIBAAIIHBt2EAC4AAI5DAAAAwBbADoMAAACAC8AAQACCBwbdhAAuAACOQwAAAMAWwA6DAAAAgAvACwABAqBHgADAQAICLwjlgcAKQMAAQAICLwjlgcAKQMABwABCI4cYBEARwAAAAA=.Xiarrog:BAEALAAECggIDgABLAAFFAIIBQABABwbAA==.Xippii:BAEALAAECgYIDAABLAAECgYIBgAOAAAAAA==.',Xy='Xylek:BAEALAAECgQICQAAAA==.',['Xì']='Xìppì:BAEALAAECggIDwABLAAECgYIBgAOAAAAAA==.',['Às']='Àsbéth:BAEBLAAECoEXAAMUAAcIKRxZNQCoAQc5DAAABABXADsMAAAEAEgAOgwAAAUAWgA8DAAAAwBFADIMAAADAC8APQwAAAIARwA+DAAAAgBBABQABgjJF1k1AKgBBjkMAAABACgAOwwAAAIARgA8DAAAAwBFADIMAAADAC8APQwAAAIARwA+DAAAAgBBABUAAwidIPk7APkAAzkMAAADAFcAOwwAAAIASAA6DAAABQBaAAEsAAQKCAgEAA4AAAAA.',['Ãd']='Ãdãm:BAEALAAECgYIDAABLAAECggIGwASAEscAA==.',['Äs']='Äsbëth:BAEALAAECggIBAAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end