local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Paladin-Retribution','Druid-Guardian','Monk-Mistweaver','DemonHunter-Havoc','DeathKnight-Frost','DeathKnight-Unholy','Priest-Holy','Unknown-Unknown','Warlock-Destruction','Mage-Arcane','Evoker-Augmentation','Warlock-Demonology','Druid-Balance','DeathKnight-Blood','Warrior-Fury','Warrior-Protection','Shaman-Restoration','Warlock-Affliction','Druid-Feral','Druid-Restoration','Priest-Shadow','Priest-Discipline','Mage-Frost','Paladin-Holy','Rogue-Assassination','Hunter-BeastMastery','Paladin-Protection','Monk-Windwalker','Rogue-Outlaw','Rogue-Subtlety','Shaman-Enhancement','Warrior-Arms','Evoker-Preservation','Evoker-Devastation','Hunter-Marksmanship','Hunter-Survival','Shaman-Elemental','DemonHunter-Vengeance','Mage-Fire',}; local provider = {region='EU',realm='DerRatvonDalaran',name='EU',type='weekly',zone=44,date='2025-09-24',data={Aa='Aaliyah:BAABLAAECoEWAAIBAAYINxe+lQCRAQABAAYINxe+lQCRAQAAAA==.',Ab='Abraxana:BAAALAAECgIIAgAAAA==.',Ac='Achale:BAABLAAECoEiAAICAAgI3BaDCQAcAgACAAgI3BaDCQAcAgAAAA==.Acharon:BAAALAAECggICQABLAAFFAUIEgADABEeAA==.',Ad='Adamanda:BAAALAAECgEIAQAAAA==.Adanos:BAAALAAECgYIDwABLAAFFAUIFgAEALAfAA==.',Ae='Aentenmann:BAAALAAECggIEwAAAA==.',Ag='Agnodh:BAAALAADCgMIAQAAAA==.Agnodk:BAABLAAECoElAAMFAAgIERrZVQAaAgAFAAgIERrZVQAaAgAGAAEIPRDFUQBAAAAAAA==.Agrawain:BAAALAADCgcIJAAAAA==.',Ai='Aiuma:BAABLAAECoEUAAIHAAYIqhKxUgBoAQAHAAYIqhKxUgBoAQAAAA==.',Ak='Akaruii:BAACLAAFFIEMAAIBAAUIShmlBwB6AQABAAUIShmlBwB6AQAsAAQKgTEAAgEACAhNJuMCAH4DAAEACAhNJuMCAH4DAAAA.',Al='Albaeblod:BAAALAADCggIBwABLAADCggICAAIAAAAAA==.Aldatha:BAAALAADCggICAABLAAECggIHwAJAD8TAA==.Alibu:BAAALAADCggICAAAAA==.Alira:BAABLAAECoEUAAIKAAYIiQnxkQA6AQAKAAYIiQnxkQA6AQABLAAECgYIFwALAAQPAA==.Allysera:BAAALAADCggIGAAAAA==.Alpamaja:BAAALAADCggIDQAAAA==.Alythess:BAAALAADCggIDQAAAA==.',Am='Amadena:BAAALAAECgcICAABLAAECggIIAAMALAfAA==.Amandine:BAAALAADCgcIBwAAAA==.Amazeroth:BAAALAADCggICAABLAAECggIIAAMALAfAA==.Amelinde:BAAALAAECggICgAAAA==.Amesha:BAACLAAFFIENAAINAAUIgSB8AwDfAQANAAUIgSB8AwDfAQAsAAQKgScAAg0ACAhQJjACAHQDAA0ACAhQJjACAHQDAAAA.Amnur:BAAALAADCgcIFgAAAA==.',An='Anjíne:BAAALAADCgcIDQAAAA==.Annadoria:BAAALAADCggIDwABLAAECgEIAQAIAAAAAA==.Annemore:BAAALAAECggICAAAAA==.Anthorina:BAAALAADCgMIAwAAAA==.Anýdk:BAAALAAECggIDwAAAA==.',Ar='Arava:BAABLAAECoEfAAIJAAgIPxObVgC5AQAJAAgIPxObVgC5AQAAAA==.Arctic:BAABLAAECoEfAAMFAAgIaCHuGQDtAgAFAAgITSHuGQDtAgAOAAIISSHOMgCIAAAAAA==.Argaal:BAABLAAECoEcAAIMAAgIxxTmFAA1AgAMAAgIxxTmFAA1AgAAAA==.Ariafeedyone:BAACLAAFFIEJAAIEAAMIWREAFQDmAAAEAAMIWREAFQDmAAAsAAQKgTAAAgQACAgwJOIQABoDAAQACAgwJOIQABoDAAAA.',As='Ascarda:BAAALAAECggICQAAAA==.Asfaloth:BAABLAAECoEgAAMMAAgIsB9bBQD8AgAMAAgIlR9bBQD8AgAJAAgIyBYAAAAAAAAAAA==.Asimov:BAAALAAECgYIDAAAAA==.',At='Atair:BAABLAAECoEtAAIEAAgINB5dJgCkAgAEAAgINB5dJgCkAgAAAA==.Atairis:BAAALAADCgcIJAAAAA==.Athavar:BAAALAAECgYICQABLAAECggIIgAEAEscAA==.Athavarion:BAABLAAECoEiAAIEAAgISxzwLACEAgAEAAgISxzwLACEAgAAAA==.',Au='Aurisaria:BAAALAADCggICAAAAA==.Auwibald:BAAALAAECgMIBQAAAA==.',Av='Averiel:BAAALAADCgQIAwABLAAECggILwAKAF4VAA==.',Ay='Ayûmî:BAABLAAECoEaAAMPAAcIRR4gLABaAgAPAAcIRR4gLABaAgAQAAEILA5BeAA1AAAAAA==.',Az='Azogh:BAACLAAFFIEHAAIRAAMINQ/jFwDAAAARAAMINQ/jFwDAAAAsAAQKgScAAhEACAhzGPY0ABwCABEACAhzGPY0ABwCAAAA.',Ba='Babidi:BAABLAAECoEUAAMMAAYILiFrHwDoAQAMAAUINSFrHwDoAQASAAEIDyFuLwBjAAAAAA==.Baegrim:BAAALAADCgcIBwAAAA==.Bartolz:BAAALAAECggIDgAAAA==.Batidá:BAAALAADCgMIAwAAAA==.Baumwollauge:BAAALAAECgYIDAAAAA==.',Be='Beliar:BAACLAAFFIEWAAIEAAUIsB9hBgDoAQAEAAUIsB9hBgDoAQAsAAQKgTAAAgQACAgjJbcFAGEDAAQACAgjJbcFAGEDAAAA.Bernoo:BAAALAAECgIIAgABLAAECggIFAABAAEIAA==.',Bi='Biggerbär:BAABLAAECoEUAAITAAgIZQlpHgB6AQATAAgIZQlpHgB6AQAAAA==.Bilba:BAABLAAECoEbAAIJAAcIsxrOOgAhAgAJAAcIsxrOOgAhAgABLAAECgYIBgAIAAAAAA==.',Bl='Blacksuny:BAAALAAECgcIEwAAAA==.Blackwood:BAAALAAECggICAAAAA==.Blechberd:BAABLAAECoEbAAIBAAcINgxLuQBSAQABAAcINgxLuQBSAQAAAA==.Bloodryan:BAABLAAECoEXAAMQAAcIBB7sNQBwAQAPAAcIiR1aYQCVAQAQAAYIHhbsNQBwAQAAAA==.Blueberry:BAAALAAECgIIAwAAAA==.Bluppjin:BAAALAADCggIEAAAAA==.',Bo='Bondrewd:BAAALAAECgQIBAABLAAECgcIHgARAIkfAA==.Borkaar:BAABLAAECoEYAAINAAgINxJeLADnAQANAAgINxJeLADnAQAAAA==.Borìto:BAAALAAECgYIDAAAAA==.',Br='Bragma:BAABLAAECoEgAAIJAAcIwB9UKQB0AgAJAAcIwB9UKQB0AgAAAA==.Braven:BAAALAADCggIDwAAAA==.Brod:BAAALAAECggIEAABLAAFFAUIDAAKAMsRAA==.Brooklyn:BAABLAAECoEnAAIBAAgInB43NQB2AgABAAgInB43NQB2AgAAAA==.Brödle:BAACLAAFFIEMAAIKAAUIyxESDQCrAQAKAAUIyxESDQCrAQAsAAQKgSsAAgoACAiAIXIUAPoCAAoACAiAIXIUAPoCAAAA.',['Bâ']='Bâstêt:BAAALAADCggIDwAAAA==.',['Bú']='Búwús:BAAALAADCggIEAAAAA==.',Ca='Calanon:BAAALAAECgYIDAAAAA==.Candora:BAAALAADCggICAAAAA==.Caradhras:BAAALAAECgQIBAAAAA==.Carstenstâhl:BAAALAADCgcIBwAAAA==.Carto:BAAALAADCgMIAwAAAA==.Castelia:BAAALAAECgUIBgAAAA==.',Ch='Champloo:BAAALAAECgEIAQAAAA==.Chantoria:BAAALAAECgYIDQAAAA==.Chintao:BAAALAADCgQIBAAAAA==.Chrytha:BAABLAAECoEmAAIPAAgIChLgUQDDAQAPAAgIChLgUQDDAQAAAA==.Chíllee:BAAALAAECgEIAgAAAA==.',Ci='Cinammon:BAAALAAECggIEQAAAA==.Ciêc:BAAALAAECggICgAAAA==.',Co='Cobalt:BAAALAADCgYIBgAAAA==.Comyn:BAACLAAFFIEQAAIUAAUIEBoWBACyAQAUAAUIEBoWBACyAQAsAAQKgSkAAw0ACAjNF5YpAPcBAA0ABwioFpYpAPcBABQACAh8EvQ2ANABAAAA.Cosara:BAAALAADCggICAAAAA==.Cowmanbebop:BAABLAAECoEiAAIRAAgIDBqZKgBFAgARAAgIDBqZKgBFAgAAAA==.',Cr='Crabby:BAAALAAECggIEwAAAA==.Crascha:BAAALAADCgQIBAAAAA==.Crytøs:BAABLAAECoEnAAQHAAcInB+nHgBlAgAHAAcInB+nHgBlAgAVAAEIvx2xggBMAAAWAAEI6ASVNQArAAAAAA==.',Cu='Cupcakekiss:BAAALAADCggICAAAAA==.Curcuma:BAAALAADCgIIAgAAAA==.Curilia:BAAALAADCgcIHQAAAA==.Custermato:BAAALAAECgIIAgAAAA==.',Cy='Cyrell:BAABLAAECoEZAAIKAAYI0wjImgAfAQAKAAYI0wjImgAfAQAAAA==.',['Câ']='Câstîel:BAAALAADCgEIAQAAAA==.',Da='Daffney:BAAALAADCgMIAwAAAA==.Daimyo:BAAALAADCgEIAQAAAA==.Dakhathkiam:BAAALAADCgYICQAAAA==.Danyaela:BAAALAAECgYIDwAAAA==.Darkdefs:BAAALAADCggICAABLAAFFAYICgAVAOQYAA==.Darkko:BAAALAAECgEIAQAAAA==.Darkroxx:BAAALAAECgcIDwAAAA==.',De='Deamhana:BAAALAAECgIIAgAAAA==.Deanerys:BAAALAAECgcIEwAAAA==.Dearmama:BAAALAADCggICAAAAA==.Deffs:BAAALAAECggICAABLAAFFAYICgAVAOQYAA==.Defs:BAACLAAFFIEKAAIVAAYI5BhGAwAVAgAVAAYI5BhGAwAVAgAsAAQKgSsAAxUACAjQJZUBAH8DABUACAjQJZUBAH8DAAcAAwhICD2QAIAAAAAA.Defsmage:BAAALAAECgYIBQABLAAFFAYICgAVAOQYAA==.Delilia:BAAALAAECggICAAAAA==.Desha:BAAALAADCgcIBwAAAA==.',Di='Diliilari:BAAALAADCgMIAwABLAAECgYIDAAIAAAAAA==.Dinguskhan:BAAALAAECgYICQAAAA==.Dixon:BAAALAADCggIEQAAAA==.',Dj='Djinnseel:BAAALAADCgQIBAAAAA==.',Dk='Dkdefs:BAAALAADCggIEAABLAAFFAYICgAVAOQYAA==.',Do='Dosenbieer:BAAALAAECgIIBAAAAA==.Dougí:BAAALAADCgUIBQAAAA==.',Dr='Dragali:BAABLAAECoEfAAIXAAgITCQbAwBUAwAXAAgITCQbAwBUAwAAAA==.Draggo:BAABLAAECoEmAAMYAAcIbCUXBwDgAgAYAAcIbCUXBwDgAgABAAEInhlfLQFRAAABLAAECggIKgABAM0iAA==.Dragnoss:BAAALAADCgMIAwAAAA==.Draladin:BAAALAAECggIBwABLAAECggIHwAXAEwkAA==.Drayani:BAAALAADCggIHwAAAA==.Driest:BAAALAAECgEIAQABLAAECggIHwAXAEwkAA==.',Du='Dungard:BAAALAAECgEIAQAAAA==.',Dy='Dysporia:BAAALAADCggIEAAAAA==.',['Dé']='Défs:BAAALAAECgYICgABLAAFFAYICgAVAOQYAA==.',Ea='Earawen:BAAALAADCggICAABLAAECggICgAIAAAAAA==.',Ed='Eddan:BAAALAADCggIJgAAAA==.Edelbart:BAAALAADCggICgAAAA==.',Ef='Efvarim:BAAALAADCggIDAAAAA==.',El='Elemant:BAAALAADCggIDgAAAA==.Elmø:BAAALAAECgYICwAAAA==.Elohim:BAACLAAFFIELAAIBAAQIyRAGCQBNAQABAAQIyRAGCQBNAQAsAAQKgRcAAgEACAjwH48zAH0CAAEACAjwH48zAH0CAAAA.Elunara:BAAALAADCgUIAwAAAA==.Elusera:BAAALAADCggIDgAAAA==.',Em='Emeliso:BAAALAADCgcICwAAAA==.Emkystone:BAAALAADCggICAAAAA==.',En='Enji:BAAALAAECgMIBgAAAA==.Entagor:BAAALAADCgIIAgAAAA==.',Ep='Epidemiç:BAAALAAECgYIDAAAAA==.',Es='Eshkiya:BAAALAADCgMIAwAAAA==.',Et='Etiennê:BAAALAAECgQIBwAAAA==.',Ev='Eveleen:BAABLAAECoEfAAIZAAgI/Am8KgC5AQAZAAgI/Am8KgC5AQAAAA==.Evlat:BAAALAAECggICAAAAA==.',Ex='Excon:BAAALAAECgEIAgAAAA==.',Fa='Faer:BAAALAADCggICAABLAAECggIHwAXAEwkAA==.Fangnix:BAABLAAECoEcAAIaAAYIIRFPmQBMAQAaAAYIIRFPmQBMAQAAAA==.Fatbutdead:BAACLAAFFIERAAMGAAUIPSL4AgA0AQAGAAMI3CL4AgA0AQAFAAIITiFOIADHAAAsAAQKgSQAAwYACAiHJLIJAKUCAAYABwi8JLIJAKUCAAUABgj4HUSPAKYBAAAA.Faylen:BAAALAADCggICAABLAAECggIGgAaAAcSAA==.',Fe='Felladriel:BAAALAAECgEIAQAAAA==.Felyscha:BAAALAADCggIFQABLAAECgMIAwAIAAAAAA==.Ferg:BAAALAADCgcIDwAAAA==.',Fi='Fija:BAAALAADCgcIDAABLAAECgcIFwAXAKEJAA==.Finlay:BAABLAAECoEjAAIPAAgIhBm1KQBoAgAPAAgIhBm1KQBoAgAAAA==.Firebee:BAAALAAECgcIBQAAAA==.Firefox:BAAALAADCgEIAQAAAA==.',Fj='Fjoelnir:BAABLAAECoEaAAIaAAgIBxLHagCsAQAaAAgIBxLHagCsAQAAAA==.',Fl='Flavy:BAAALAAECggICAAAAA==.Flickamentis:BAAALAADCggICAAAAA==.',Fr='Fredl:BAAALAADCggICAABLAAECggIMwAaAAoPAA==.Frjálsál:BAAALAADCggICAAAAA==.Frungrolosch:BAACLAAFFIEWAAIOAAUIBA4KBABaAQAOAAUIBA4KBABaAQAsAAQKgS8AAg4ACAjYGj4NAE0CAA4ACAjYGj4NAE0CAAAA.',Fu='Fuchûr:BAAALAAECgYIDwAAAA==.Fumio:BAACLAAFFIETAAIYAAUIaB1fAwDYAQAYAAUIaB1fAwDYAQAsAAQKgScAAhgACAjzJBkBAFYDABgACAjzJBkBAFYDAAAA.Funnylady:BAAALAAECgcIBwAAAA==.Futzi:BAABLAAECoEhAAIPAAgIKhHnRgDpAQAPAAgIKhHnRgDpAQAAAA==.',Ga='Gaiane:BAAALAAECgMIBwAAAA==.Gallowos:BAABLAAECoEcAAICAAYI8hSVFABOAQACAAYI8hSVFABOAQAAAA==.Gammelbert:BAABLAAECoEcAAIXAAYI5BGjOQBlAQAXAAYI5BGjOQBlAQAAAA==.Ganda:BAAALAADCggIFAABLAAECggIHwAFAGghAA==.Gandrosh:BAABLAAECoEXAAIZAAcIgBRNIwDrAQAZAAcIgBRNIwDrAQAAAA==.',Ge='Gepo:BAABLAAECoEeAAIDAAgI0h+ABwDUAgADAAgI0h+ABwDUAgAAAA==.Gesu:BAAALAAECgcIDgAAAA==.',Gl='Globoss:BAACLAAFFIEWAAIbAAUIPB+PAQDWAQAbAAUIPB+PAQDWAQAsAAQKgS8AAhsACAgKJCEDAEYDABsACAgKJCEDAEYDAAAA.',Go='Gottom:BAACLAAFFIEUAAMMAAUItyA0AgAPAQAJAAMICCLpEwAhAQAMAAMICBg0AgAPAQAsAAQKgS8ABAwACAg6JYoSAEsCAAwABggaI4oSAEsCAAkABggaHgk9ABcCABIABAiVHN0TAF8BAAAA.',Gr='Graland:BAAALAADCggIDAAAAA==.Grantolph:BAAALAADCggICwAAAA==.Grider:BAACLAAFFIEQAAIaAAUIzBMxCgBlAQAaAAUIzBMxCgBlAQAsAAQKgS8AAhoACAhyIpcTAO8CABoACAhyIpcTAO8CAAAA.Grillwurst:BAAALAAECgcIBwABLAAFFAUIDgAcAFwgAA==.Grimzahn:BAAALAADCggICgAAAA==.Grobian:BAAALAADCggICAAAAA==.Grosus:BAAALAAECggIEAAAAA==.Grînch:BAAALAADCgIIAgAAAA==.',Gt='Gtmr:BAAALAADCggIEAAAAA==.',Gu='Gurano:BAAALAAECgQIBAABLAAECggIHwAFAGghAA==.',['Gü']='Gülo:BAAALAAECgEIAQAAAA==.',Ha='Halcyon:BAAALAAECgMIBwAAAA==.Haotsuy:BAAALAAECgQIBAAAAA==.Harmony:BAAALAADCggIDQAAAA==.',He='Heihachi:BAAALAADCgYIBgABLAAFFAYIEwARAEMXAA==.Hemie:BAABLAAECoEeAAIPAAgIXQvlVwCxAQAPAAgIXQvlVwCxAQAAAA==.Hephestes:BAAALAADCggIDQAAAA==.Hereisjohni:BAAALAAECgEIAQAAAA==.Hexerdefs:BAAALAAECgYIDAABLAAFFAYICgAVAOQYAA==.',Hi='Highlerin:BAAALAADCgIIAgABLAADCgcICAAIAAAAAA==.Himiiko:BAABLAAECoEXAAIdAAcIaQ+FCgCyAQAdAAcIaQ+FCgCyAQAAAA==.Hirú:BAAALAAECgYIBgABLAAECggIHwAFAGghAA==.',Ho='Holysalt:BAABLAAECoEoAAMBAAgIhBbdbADgAQABAAcIABjdbADgAQAbAAgIfw0/MgA6AQAAAA==.Homebrew:BAAALAADCggICAAAAA==.Homelander:BAAALAAECggICwAAAA==.Hornstar:BAAALAAECgUIBwAAAA==.Horstilein:BAAALAADCggIEQABLAAECggIHwAFAGghAA==.Hotshots:BAAALAAECgMIAwAAAA==.',Hy='Hypnos:BAAALAAECgUIBQAAAA==.Hyrah:BAABLAAECoEfAAIVAAgI/wn6PgCfAQAVAAgI/wn6PgCfAQAAAA==.',['Hé']='Hékathe:BAAALAAECgYIEAAAAA==.',['Hê']='Hêrmês:BAAALAADCggIDAAAAA==.',Ib='Iberia:BAAALAADCggIBwAAAA==.',Ic='Ichika:BAABLAAECoEWAAIcAAgIkhjoEwBNAgAcAAgIkhjoEwBNAgAAAA==.',Ik='Iklatschdi:BAABLAAECoEYAAIEAAYIsgmF1gDbAAAEAAYIsgmF1gDbAAAAAA==.Ikto:BAAALAAECggIDwAAAA==.',Il='Illecebra:BAAALAAECgMIBQAAAA==.Illiá:BAAALAAECgYICAAAAA==.Ilyne:BAAALAADCggIDwAAAA==.',Im='Implinella:BAAALAAECgYIEgABLAAFFAUIFgAEALAfAA==.',In='Inobaff:BAAALAAECgYIEQAAAA==.',Io='Ionnain:BAAALAADCggICAAAAA==.',Ir='Iradiel:BAAALAAECgYICQAAAA==.',Is='Isabellâ:BAAALAADCggIEAABLAAECggIHwARAJMiAA==.Isen:BAACLAAFFIEOAAINAAUI5h5MAwDlAQANAAUI5h5MAwDlAQAsAAQKgSgAAg0ACAjnJNEEAE8DAA0ACAjnJNEEAE8DAAAA.Islanzadî:BAAALAAECgEIAQABLAAECgYIFgABADcXAA==.Istná:BAABLAAECoEmAAINAAgIEBYhLwDXAQANAAgIEBYhLwDXAQAAAA==.Iszan:BAAALAADCgYIBgAAAA==.Iszangralson:BAAALAADCgEIAQAAAA==.',Iy='Iyonaya:BAABLAAECoEWAAMeAAYINBc2GQCjAQAeAAYI+BY2GQCjAQAZAAMIchWHTgDLAAAAAA==.',Iz='Izza:BAAALAADCggIFAABLAAECggIHwAFAGghAA==.',Ja='Jamela:BAAALAADCggICAAAAA==.Jania:BAAALAAECggIDwAAAA==.Jastos:BAACLAAFFIEJAAIPAAUIOxDVCACgAQAPAAUIOxDVCACgAQAsAAQKgSUAAg8ACAg+IYYXANwCAA8ACAg+IYYXANwCAAAA.',Je='Jeki:BAAALAADCgYIBgAAAA==.Jericco:BAAALAADCgYIBgAAAA==.',Ji='Jiltanith:BAAALAADCgcIGwAAAA==.Jinxs:BAAALAAECgQIBAAAAA==.',Jo='Johnyrebel:BAAALAAECgYIBwAAAA==.Joolaran:BAAALAADCgcIIwAAAA==.',['Jâ']='Jâckysparrøw:BAAALAADCggIHwAAAA==.',['Jû']='Jûpîtêr:BAAALAAECggICAAAAA==.',Ka='Kahmoz:BAACLAAFFIEQAAIfAAUIUgvDAQArAQAfAAUIUgvDAQArAQAsAAQKgS8AAh8ACAg7ILMDAOcCAB8ACAg7ILMDAOcCAAAA.Kaisar:BAAALAADCgcIDQAAAA==.Kalithon:BAABLAAECoEjAAQQAAgIUiWgAgBdAwAQAAgIUiWgAgBdAwAgAAUI8xXTFQBfAQAPAAIIpxZ6tACIAAAAAA==.Kandusa:BAABLAAECoEbAAMHAAYI8hrkPQC8AQAHAAYI0RnkPQC8AQAWAAMIFRTuHgC5AAAAAA==.Kanzana:BAAALAADCgcIEAAAAA==.Karadràs:BAAALAADCgYIBgAAAA==.Kardesch:BAAALAAECggICAAAAA==.Kariná:BAAALAAECggICAAAAA==.Karía:BAAALAADCgcIHQAAAA==.Kasap:BAABLAAECoEfAAIaAAgIkxLvcQCbAQAaAAgIkxLvcQCbAQAAAA==.Katlynn:BAAALAADCggICQAAAA==.Kayonara:BAAALAAECgQIBAABLAAECggIHwAZAA4dAA==.Kayonik:BAABLAAECoEfAAIZAAgIDh39CwDHAgAZAAgIDh39CwDHAgAAAA==.Kayowaid:BAAALAAECgUICgABLAAECggIHwAZAA4dAA==.',Ke='Kedal:BAAALAADCgcICAAAAA==.Keishara:BAAALAADCggICAABLAAECgYIFgABADcXAA==.Kelaroth:BAAALAAECggICgABLAAECggIJwARAIclAA==.Keleron:BAAALAADCgIIAgAAAA==.Kendrani:BAAALAADCgcIDQAAAA==.Kerae:BAACLAAFFIEOAAIcAAUIXCA/AQAWAgAcAAUIXCA/AQAWAgAsAAQKgR0AAhwACAh4JDIEADwDABwACAh4JDIEADwDAAAA.Kernchen:BAAALAAECgMIBQAAAA==.Keshia:BAAALAAECgcIDwAAAA==.Keóna:BAAALAAECgYIEwAAAA==.',Kh='Khurt:BAAALAADCgEIAQAAAA==.Khyria:BAAALAAECgYICwAAAA==.Khêstrel:BAABLAAECoEmAAIhAAgI4RA2HABZAQAhAAgI4RA2HABZAQAAAA==.',Ki='Kinania:BAAALAAECgQIBAAAAA==.Kiralka:BAAALAADCgEIAQAAAA==.Kissmyairs:BAAALAADCggICAAAAA==.',Kn='Knalli:BAACLAAFFIEQAAIXAAUI+B7cAADdAQAXAAUI+B7cAADdAQAsAAQKgS8AAhcACAjJJTUCAGcDABcACAjJJTUCAGcDAAAA.Knirykas:BAABLAAECoEjAAIRAAgIeg9iaACDAQARAAgIeg9iaACDAQAAAA==.Knálli:BAAALAAECgYICwABLAAFFAUIEAAXAPgeAA==.',Kr='Krampe:BAAALAAECgcIBwAAAA==.Krystel:BAAALAAECgMIAwAAAA==.Krüger:BAAALAAECgMIBAAAAA==.',Ku='Kupfì:BAABLAAECoEkAAMhAAcI2RknDwAPAgAhAAcI2RknDwAPAgAiAAQIdAv/RwDWAAAAAA==.Kupfí:BAAALAAECgYIBgABLAAECgcIJAAhANkZAA==.',Kv='Kvelthar:BAABLAAECoEvAAIKAAgIXhWkSQAKAgAKAAgIXhWkSQAKAgAAAA==.',Ky='Kyrina:BAAALAADCgYIDAAAAA==.',La='Lacriluna:BAAALAAECgUIBwAAAA==.Lakida:BAAALAAECgYIAgAAAA==.Lasarif:BAABLAAECoEeAAMNAAgIqhQYMwDCAQANAAgIqhQYMwDCAQAUAAEIZwOByAASAAAAAA==.Laydie:BAAALAADCggIEQAAAA==.',Le='Leafmetender:BAAALAAECgYIBgABLAAECggIJwAWAKMOAA==.Learose:BAAALAAECgcIEQAAAA==.Leboo:BAABLAAECoEhAAMaAAgIHxTxVQDgAQAaAAgIHxTxVQDgAQAjAAIIuQ7RnABZAAAAAA==.Leebo:BAAALAAECgMIAwAAAA==.Leoníê:BAAALAADCggIDQAAAA==.Letsgoevo:BAACLAAFFIEFAAIhAAIIFA9yDgCMAAAhAAIIFA9yDgCMAAAsAAQKgRgAAiEACAjRGuwIAIECACEACAjRGuwIAIECAAAA.',Li='Lightmodiah:BAAALAADCggICAAAAA==.Lightshot:BAAALAADCggIDQAAAA==.Lilofin:BAAALAADCggIDwAAAA==.Lingpigg:BAAALAADCgUIBQAAAA==.Litago:BAAALAAECgIIAgABLAAECggIHwAFAGghAA==.Littlefun:BAAALAAECgYIEwAAAA==.',Lo='Lokíí:BAAALAAECgMIAwAAAA==.Loras:BAAALAAECgEIAQAAAA==.Lorendana:BAAALAADCgEIAQAAAA==.Lothlórien:BAAALAAECgEIAgAAAA==.Loulâ:BAAALAADCgEIAQABLAAECgYIDAAIAAAAAA==.',Lu='Lulusha:BAAALAAECggICAAAAA==.Luminara:BAAALAADCggICAABLAAECgYIDQAIAAAAAA==.Lunicor:BAABLAAECoEXAAIXAAgIpB4WCwDPAgAXAAgIpB4WCwDPAgAAAA==.Luná:BAAALAADCgYIBgAAAA==.',Ly='Lywyna:BAABLAAECoEfAAQUAAgIchsoGAB4AgAUAAgIchsoGAB4AgANAAcIlx+nGwBZAgACAAYIOBLWFABLAQAAAA==.Lyzea:BAACLAAFFIEPAAMJAAUIrxB5DwBtAQAJAAUIDg15DwBtAQASAAII2RYAAAAAAAAsAAQKgS8AAxIACAhBJcAAAF8DABIACAjuJMAAAF8DAAkABgibHJBEAPkBAAAA.',Ma='Mahoaga:BAAALAAECggICAAAAA==.Malakaï:BAAALAAECggICAAAAA==.Malnea:BAAALAAECgYIBgAAAA==.Mamata:BAABLAAECoEfAAISAAgISBaHBgBPAgASAAgISBaHBgBPAgAAAA==.Mammon:BAABLAAECoEcAAIgAAYIVhGvFgBUAQAgAAYIVhGvFgBUAQAAAA==.Mandragòr:BAAALAADCgcIDQAAAA==.Maniac:BAACLAAFFIEVAAINAAUIciSRAgABAgANAAUIciSRAgABAgAsAAQKgSwAAg0ACAjuJSgCAHUDAA0ACAjuJSgCAHUDAAAA.Maniacpriest:BAAALAAECgcIBwAAAA==.Marrie:BAAALAAECgMIAwAAAA==.Maveen:BAABLAAECoEnAAMWAAgIow7mFAAqAQAHAAgIow5OPwC2AQAWAAcIiArmFAAqAQAAAA==.',Mc='Mcpeanuts:BAAALAAECgYIBgABLAAECggIJAADAG4QAA==.',Me='Meallá:BAAALAADCgcIBwABLAAECggIGgAaAAcSAA==.Meeri:BAAALAADCgcICwAAAA==.Meilena:BAAALAAECgMIBQAAAA==.Meliandora:BAABLAAECoEVAAIUAAYIUBuSNgDSAQAUAAYIUBuSNgDSAQAAAA==.Meraxes:BAAALAADCggICAABLAAECggIHwARAJMiAA==.Merlinboo:BAABLAAECoEbAAIRAAgINBCWYgCTAQARAAgINBCWYgCTAQAAAA==.Merrix:BAAALAAECgIIBAAAAA==.Mestori:BAAALAADCggICAAAAA==.',Mi='Micouddii:BAAALAADCggICAAAAA==.Mikana:BAAALAAECggICwAAAA==.Milò:BAAALAADCggIDwABLAAECgcIHwAJALYeAA==.Minervà:BAAALAADCgIIAgAAAA==.Mirya:BAAALAADCgYIBgAAAA==.Mirácúlix:BAABLAAECoEaAAMNAAgIdwqXQwB0AQANAAgIdwqXQwB0AQAUAAUIzAN/mACQAAAAAA==.',Mo='Monkdefs:BAAALAADCggIGQABLAAFFAYICgAVAOQYAA==.Morohid:BAABLAAECoEeAAIjAAcIMxjsMwDWAQAjAAcIMxjsMwDWAQAAAA==.Mortai:BAAALAAECgMIBgAAAA==.',Mu='Murakvonriva:BAACLAAFFIEFAAIFAAII5hjSOQCZAAAFAAII5hjSOQCZAAAsAAQKgRgAAgUABwj/H6BGAEMCAAUABwj/H6BGAEMCAAEsAAUUBQgWAAQAsB8A.Musashi:BAABLAAECoEaAAIjAAcIrxyNJQAqAgAjAAcIrxyNJQAqAgAAAA==.',My='Myka:BAABLAAECoEjAAIaAAgIQRrXRwAIAgAaAAgIQRrXRwAIAgAAAA==.Mystiqu:BAABLAAECoEYAAIXAAgI1AQrTgAJAQAXAAgI1AQrTgAJAQAAAA==.Mystíco:BAAALAADCggICAAAAA==.',['Má']='Máliá:BAABLAAECoEeAAIRAAgI1wzbdwBbAQARAAgI1wzbdwBbAQAAAA==.',['Mê']='Mêersalz:BAAALAADCgIIAgABLAAECggIKAABAIQWAA==.',['Mî']='Mîlo:BAABLAAECoEfAAQJAAcIth4AKgBxAgAJAAcIth4AKgBxAgAMAAIIBxeXagCTAAASAAEIVQwDOABCAAAAAA==.',Na='Naela:BAABLAAECoEfAAIjAAgIlhiHJQAqAgAjAAgIlhiHJQAqAgAAAA==.Natsuku:BAAALAAECgEIAQAAAA==.Natturana:BAAALAADCggICAAAAA==.Nazguhl:BAAALAAECgUIBQAAAA==.',Ne='Necturne:BAAALAADCgIIAgAAAA==.Nefrateti:BAABLAAECoEiAAIaAAgI7RQ5XQDNAQAaAAgI7RQ5XQDNAQAAAA==.Nemantica:BAAALAADCggIGQAAAA==.Neoboomer:BAABLAAECoEbAAMNAAgIGBHeSwBPAQANAAYIoQ/eSwBPAQAUAAgIwwZMZwAfAQABLAAFFAYIGAADAC0ZAA==.Netharia:BAABLAAECoEZAAIhAAYIOhGGIAAqAQAhAAYIOhGGIAAqAQAAAA==.',Ni='Nicpark:BAAALAADCgcIBwABLAAECggICAAIAAAAAA==.Niemand:BAAALAAECgcIEwAAAA==.Nirrti:BAABLAAECoEVAAIVAAgIxgo4VQA7AQAVAAgIxgo4VQA7AQAAAA==.Nitara:BAAALAAECggIBgAAAA==.',No='Nocterra:BAABLAAECoEZAAITAAgIug6HGgCiAQATAAgIug6HGgCiAQAAAA==.Noggenfogger:BAAALAADCgMIAwAAAA==.Norara:BAAALAAECgYICwAAAA==.Nordesch:BAABLAAECoEZAAIEAAYIGg1FqwBCAQAEAAYIGg1FqwBCAQABLAAECgcIFwAXAKEJAA==.Norgar:BAAALAADCggICwABLAAECgYIEgAIAAAAAA==.Noturpal:BAAALAAECggIDwAAAA==.Novathanos:BAAALAAECgYIBgABLAAECggIJAADAG4QAA==.Nove:BAABLAAECoEgAAMXAAgIaiDKFgBDAgAKAAgI6hqyMQBoAgAXAAYIOSPKFgBDAgAAAA==.',Nu='Nudle:BAAALAAECgYIDQAAAA==.Numpsi:BAABLAAECoEqAAIfAAgIhAhLFAB6AQAfAAgIhAhLFAB6AQAAAA==.Nunnelly:BAAALAADCgcIBwAAAA==.',Ny='Nyxris:BAAALAADCggICAAAAA==.',['Né']='Nék:BAAALAAECgYIEQAAAA==.',Od='Oduhr:BAAALAADCggIDAAAAA==.',Oe='Oeo:BAAALAADCgQIBAAAAA==.',Ok='Okara:BAAALAAECggICwAAAA==.',On='Onìshi:BAABLAAECoEVAAIkAAYI/hp8CgDcAQAkAAYI/hp8CgDcAQAAAA==.',Or='Orackel:BAABLAAECoEwAAIBAAgICiJpHADlAgABAAgICiJpHADlAgAAAA==.Orcer:BAAALAAECggIDQAAAA==.Orâge:BAABLAAECoEXAAIRAAcIhAf3rADpAAARAAcIhAf3rADpAAAAAA==.',Ov='Over:BAABLAAECoEUAAIVAAcIyg/DPQClAQAVAAcIyg/DPQClAQAAAA==.',Pa='Paline:BAAALAAECgYIDgABLAAECggIHwAJAD8TAA==.Pattadin:BAABLAAECoEeAAIBAAgIiRv9MQCCAgABAAgIiRv9MQCCAgAAAA==.',Pe='Pennschieter:BAAALAAECgMIAwAAAA==.Pentagrimm:BAAALAAECgYIBgAAAA==.',Pi='Pimkiê:BAAALAAECgYICAAAAA==.Pisdez:BAAALAAECggIEgAAAA==.',Pl='Pleitegeier:BAAALAAECgMIAwAAAA==.',Po='Poipoi:BAAALAAECggIBgABLAAECggIHwAFAGghAA==.Polaurus:BAAALAAECgYIEQAAAA==.',Pr='Procblood:BAAALAADCgYIBgABLAAECggICAAIAAAAAA==.',Py='Pydocar:BAAALAAECggIEgAAAA==.Pydoria:BAAALAAECgYIDAAAAA==.',['Pá']='Pálóc:BAAALAADCgEIAQAAAA==.',Qa='Qagsalber:BAAALAADCgUIBQAAAA==.',Qu='Quazzle:BAABLAAECoEXAAIXAAcIoQnqOgBgAQAXAAcIoQnqOgBgAQAAAA==.',Ra='Radiate:BAABLAAECoEUAAIYAAYIhA+JOQBGAQAYAAYIhA+JOQBGAQAAAA==.Raeve:BAAALAAECgYICwAAAA==.Ragebullet:BAABLAAECoEoAAMgAAgIpBR3CgAZAgAgAAgIpBR3CgAZAgAPAAgIQw07VAC8AQAAAA==.Raindancer:BAAALAADCgQIBAAAAA==.Ramadon:BAAALAAECgYIEgAAAA==.Rasil:BAAALAADCggIEAAAAA==.',Re='Redbrother:BAAALAADCggIDQAAAA==.Reeperli:BAAALAADCggICAAAAA==.Remor:BAACLAAFFIETAAMlAAUInRd2BwC4AQAlAAUInRd2BwC4AQARAAIILQgAAAAAAAAsAAQKgSoAAyUACAiUINYQAPYCACUACAiUINYQAPYCABEABQgTD72tAOgAAAAA.Restokupfi:BAAALAADCggICAABLAAECgcIJAAhANkZAA==.Resù:BAAALAADCgcIDQABLAADCggIFwAIAAAAAA==.Resú:BAAALAAECgYIDgABLAADCggIFwAIAAAAAA==.Revoni:BAAALAADCggICgAAAA==.',Rh='Rhababar:BAAALAAECgEIAQAAAA==.Rhainiakassa:BAAALAAECgYIBgAAAA==.Rhainiakdk:BAAALAAECgEIAQAAAA==.Rhainiakdrac:BAAALAADCgQIBAAAAA==.Rhainiaksham:BAAALAADCggICAAAAA==.',Ri='Risar:BAAALAADCggICAAAAA==.',Ro='Robhud:BAAALAADCgYIDAABLAAECgcIEAAIAAAAAA==.Rommili:BAABLAAECoEfAAIRAAgIkyJhCgD9AgARAAgIkyJhCgD9AgAAAA==.Rommilii:BAAALAAECggICAABLAAECggIHwARAJMiAA==.Rommiroar:BAAALAADCggIEAAAAA==.Rootcare:BAAALAAECgYIBwAAAA==.Rosafee:BAAALAADCggICAAAAA==.Rosi:BAAALAAECgEIAQAAAA==.Roxx:BAAALAADCggIFQAAAA==.',Ru='Rumburag:BAAALAADCgEIAQAAAA==.',['Rè']='Rèdich:BAAALAADCggIDAAAAA==.Rèsu:BAAALAADCggIFwAAAA==.',['Ré']='Rénnâ:BAAALAAECggICQAAAA==.',['Rì']='Rìo:BAAALAAECgcIDQAAAA==.',['Rî']='Rîthara:BAABLAAECoEWAAImAAgIACA1BwDRAgAmAAgIACA1BwDRAgAAAA==.',['Rò']='Ròka:BAAALAAECgEIAQAAAA==.',Sa='Sahin:BAAALAADCggICAAAAA==.Sambus:BAAALAAECgYIDQAAAA==.Sanjir:BAAALAAECgcIBwAAAA==.Sarahangel:BAABLAAECoEcAAIVAAYIBxlpOwCxAQAVAAYIBxlpOwCxAQAAAA==.Sarcora:BAAALAADCggICAAAAA==.Sarlinaria:BAABLAAECoEiAAMXAAgIORHUIwDdAQAXAAgIORHUIwDdAQAKAAEIBwbh5wAjAAAAAA==.Sassy:BAAALAAECgUIBwABLAAECgYICQAIAAAAAA==.Sasur:BAABLAAECoEXAAIJAAYISQUWmQABAQAJAAYISQUWmQABAQAAAA==.Sator:BAAALAADCggICAAAAA==.Savo:BAABLAAECoEzAAMaAAgICg9vgAB9AQAaAAgICg9vgAB9AQAjAAEIvwYAAAAAAAAAAA==.Savook:BAAALAAECggICgABLAAECggIMwAaAAoPAA==.',Sc='Schadrack:BAAALAADCgYIDAAAAA==.Schamanni:BAAALAAECgEIAQAAAA==.Schampignon:BAAALAADCggICAAAAA==.Schwonklsham:BAABLAAECoEeAAIRAAcIiR8lKQBKAgARAAcIiR8lKQBKAgAAAA==.',Se='Senhor:BAAALAADCggICAABLAAECgUIBwAIAAAAAA==.Servas:BAABLAAECoEmAAMPAAgIhBpdLwBKAgAPAAgIhBpdLwBKAgAQAAcI4A82NwBpAQAAAA==.',Sh='Shaci:BAAALAADCgcIBwABLAAECgcIEQAIAAAAAA==.Shadowspawn:BAAALAAECggICgAAAA==.Shadowtoast:BAAALAADCggIDwABLAAECggIHwAFAGghAA==.Shaps:BAAALAAECgMIAwAAAA==.Shatara:BAAALAAECgYIDgABLAAFFAUIFgAEALAfAA==.Shedovv:BAABLAAECoErAAIEAAgINyGrJACsAgAEAAgINyGrJACsAgAAAA==.Shenlyen:BAAALAAECgMIBwAAAA==.Shieki:BAACLAAFFIEQAAIKAAUI8hnWCwC8AQAKAAUI8hnWCwC8AQAsAAQKgRkAAwoACAjTISYnAJoCAAoACAjTISYnAJoCACcAAQixH5kXAFkAAAAA.Shinlu:BAAALAAECggICgAAAA==.Shoopz:BAAALAAECgYICQAAAA==.Shurá:BAAALAADCggIDAAAAA==.Shyrinu:BAACLAAFFIENAAIZAAUIxB0PAQD+AQAZAAUIxB0PAQD+AQAsAAQKgRsAAhkACAgZIpAHAP8CABkACAgZIpAHAP8CAAAA.Shývana:BAAALAAECgIIBAAAAA==.',Si='Sillahz:BAAALAADCggIEAAAAA==.Sindra:BAAALAADCggICAAAAA==.Sixerfit:BAAALAADCggICAAAAA==.',Sk='Skjaldansari:BAAALAADCggICAABLAADCggICAAIAAAAAA==.Skulard:BAAALAAECgcIEwAAAA==.Skullion:BAAALAADCgEIAQABLAAECgYIEQAIAAAAAA==.',So='Sohafee:BAAALAADCggIEQAAAA==.Sori:BAAALAADCgcIHQAAAA==.',Ss='Ssenx:BAACLAAFFIEOAAMjAAUImhOkBQCNAQAjAAUIzhGkBQCNAQAaAAQIuxSgDAAyAQAsAAQKgS0AAyMACAgnJsYHACIDACMACAjEJMYHACIDABoACAgmJqAMAB0DAAAA.',St='Steve:BAAALAAECggICQAAAA==.Storchi:BAABLAAECoEjAAIKAAgIGiGmGQDdAgAKAAgIGiGmGQDdAgAAAA==.Styrja:BAACLAAFFIEKAAIdAAMIRQrbAQDaAAAdAAMIRQrbAQDaAAAsAAQKgSEAAh0ACAjgGQQEAI0CAB0ACAjgGQQEAI0CAAAA.Stôrm:BAABLAAECoEfAAIlAAgIoxpDJABnAgAlAAgIoxpDJABnAgAAAA==.',Su='Sunfighter:BAAALAADCgcIBwAAAA==.',Sw='Swiftblâde:BAABLAAECoEcAAIgAAcIphKbDgDKAQAgAAcIphKbDgDKAQAAAA==.',Sy='Sydri:BAAALAADCggICQAAAA==.Sylaell:BAABLAAECoEcAAINAAcILRngKQD1AQANAAcILRngKQD1AQAAAA==.Synagogia:BAAALAADCgcIDAABLAAECgcIHwAEANMZAA==.Syola:BAAALAAECggIDAABLAAFFAUIEgADABEeAA==.Syrma:BAABLAAECoEUAAQVAAYIqwzbXQARAQAVAAUI2wzbXQARAQAHAAYI4wIQfwDNAAAWAAQILATrIwCLAAAAAA==.Syrâx:BAABLAAECoEXAAILAAYIBA8PDABaAQALAAYIBA8PDABaAQAAAA==.',['Sê']='Sêras:BAAALAAECgcIDQAAAA==.',['Sû']='Sûlphûr:BAAALAADCggICAAAAA==.',Ta='Ta:BAAALAAECggICAAAAA==.Tabatha:BAAALAADCggIDwAAAA==.Tabyja:BAAALAADCgUIBQABLAAECgMIAwAIAAAAAA==.Talandra:BAABLAAECoEWAAMFAAcIhhJujwClAQAFAAcInBBujwClAQAOAAQI9w/OLgCxAAAAAA==.Taledos:BAAALAAECgMIBwAAAA==.Tanja:BAAALAADCggIDwAAAA==.Taonid:BAABLAAECoEqAAITAAgIcxVSFgDSAQATAAgIcxVSFgDSAQAAAA==.Tarquin:BAAALAAECgYIEwAAAA==.',Te='Tegra:BAABLAAECoEdAAIaAAcI+QzkkQBaAQAaAAcI+QzkkQBaAQAAAA==.Teldarat:BAAALAAECgMIBwAAAA==.Telnas:BAAALAAECgYICQAAAA==.',Th='Thandralos:BAAALAADCggICAAAAA==.Thanía:BAABLAAECoEgAAIhAAgIpBTREgDSAQAhAAgIpBTREgDSAQAAAA==.Thorog:BAAALAADCgcICgAAAA==.Thorám:BAABLAAECoEUAAIBAAYIAQjt1wAXAQABAAYIAQjt1wAXAQAAAA==.Thyborøn:BAABLAAECoEZAAIFAAgIhgKwFgGiAAAFAAgIhgKwFgGiAAAAAA==.',Ti='Timbelzwick:BAACLAAFFIESAAIDAAUIER57AgDdAQADAAUIER57AgDdAQAsAAQKgR8AAgMACAidIxUEABUDAAMACAidIxUEABUDAAAA.',To='Tocdh:BAABLAAECoEhAAImAAgImCSKAgBGAwAmAAgImCSKAgBGAwAAAA==.Toddy:BAAALAADCggICAAAAA==.Tolonos:BAABLAAECoEnAAIRAAgIhyWGDADsAgARAAgIhyWGDADsAgAAAA==.Torion:BAAALAAECggICAAAAA==.Totdefs:BAAALAAECgcIEAABLAAFFAYICgAVAOQYAA==.Totemtimmy:BAEALAAFFAUIDAAAAQ==.Toxsick:BAAALAAECgYIBwAAAA==.',Tr='Tramorin:BAAALAAECggICAAAAA==.Tristias:BAAALAAECgYIDgAAAA==.Trueno:BAABLAAECoEjAAMlAAgI3xhbLwAoAgAlAAgI3hRbLwAoAgAfAAcIIxYfDgDhAQAAAA==.',Tu='Tulpilein:BAAALAAECgYIDAAAAA==.Turco:BAAALAADCggIFwAAAA==.',Tw='Twyni:BAAALAAECgYIEQABLAAFFAIIAgAIAAAAAA==.',Ty='Tyrelle:BAAALAADCggIBwAAAA==.Tyride:BAABLAAECoEXAAIJAAYI7AZrkQAYAQAJAAYI7AZrkQAYAQAAAA==.Tysaleh:BAAALAAECgYIBgAAAA==.Tytós:BAAALAADCgcIJAAAAA==.',['Tá']='Tárus:BAACLAAFFIEOAAIPAAUIJA0LCwBKAQAPAAUIJA0LCwBKAQAsAAQKgS8AAg8ACAj2INEUAO0CAA8ACAj2INEUAO0CAAAA.',Uk='Ukio:BAABLAAECoEaAAIaAAcIihC0igBoAQAaAAcIihC0igBoAQAAAA==.',Ul='Ulinda:BAABLAAECoEoAAMYAAgIbhr8EABnAgAYAAgIbhr8EABnAgABAAIIQxhqDAGXAAAAAA==.',Us='Uschì:BAAALAAECgEIAQAAAA==.',Va='Vaalzari:BAABLAAECoEhAAIOAAgI5CHODQBBAgAOAAgI5CHODQBBAgAAAA==.Valuney:BAAALAAECgIIBAAAAA==.Vandul:BAAALAAECgYIBgAAAA==.Vanen:BAABLAAECoEcAAIjAAcI/wxyUgBTAQAjAAcI/wxyUgBTAQAAAA==.',Ve='Ver:BAAALAADCggIFwABLAAECggICgAIAAAAAA==.Versuhl:BAAALAAECgQIDAAAAA==.',Vi='Videl:BAABLAAECoEeAAIVAAgIsR6VEQDQAgAVAAgIsR6VEQDQAgAAAA==.Vilitch:BAABLAAECoEYAAIJAAYIERjvXACmAQAJAAYIERjvXACmAQAAAA==.Viori:BAABLAAECoEYAAIHAAgILB3rEgC4AgAHAAgILB3rEgC4AgAAAA==.Viscyria:BAABLAAECoEpAAMVAAgINxxRJAA2AgAVAAgINxxRJAA2AgAHAAII9gnyqAAoAAAAAA==.',Vo='Voss:BAACLAAFFIEMAAIEAAUI7A0gCgCPAQAEAAUI7A0gCgCPAQAsAAQKgSUAAgQACAhGIG4dANICAAQACAhGIG4dANICAAAA.',Vu='Vuggi:BAAALAADCgMIBQAAAA==.',Vy='Vyrdris:BAABLAAECoEXAAImAAYIhRDOLAAcAQAmAAYIhRDOLAAcAQAAAA==.',['Væ']='Vænøm:BAAALAAECgQIBAAAAA==.',Wa='Waardefs:BAAALAADCggICAAAAA==.Waidmann:BAAALAAECgYIEgAAAA==.War:BAAALAAFFAIIAgAAAA==.Warklon:BAAALAADCggIDAAAAA==.',Wr='Wrendom:BAAALAAECgYIEQAAAA==.Wrenn:BAABLAAECoEoAAIjAAgImh+tDwDZAgAjAAgImh+tDwDZAgAAAA==.',Wu='Wulerde:BAAALAADCgYIBgAAAA==.Wulfram:BAAALAAECgUIBQAAAA==.',['Wí']='Wícked:BAAALAADCgYICQAAAA==.',Xa='Xamana:BAAALAAECgUIBwABLAAECgcIEAAIAAAAAA==.',Xy='Xyleng:BAAALAADCggIDwAAAA==.',Ya='Yaven:BAAALAAECgMIBwAAAA==.',Yi='Yiaro:BAABLAAECoEVAAIFAAgI4wy9jgCmAQAFAAgI4wy9jgCmAQAAAA==.',Yo='Yolanthe:BAAALAAECgQIBAAAAA==.',Ys='Ysren:BAAALAADCgcIEQAAAA==.',Yu='Yulea:BAAALAADCgEIAQAAAA==.Yuna:BAACLAAFFIEPAAIZAAUI6hqUAQDdAQAZAAUI6hqUAQDdAQAsAAQKgScAAhkACAgjIw8GABUDABkACAgjIw8GABUDAAAA.Yunâlesca:BAAALAADCgYIBgAAAA==.Yuul:BAAALAAECgcIEQAAAA==.',Za='Zarathos:BAAALAADCgcIBwAAAA==.',Ze='Zelarrin:BAAALAADCgcIIgAAAA==.Zeydra:BAAALAADCgcIGgAAAA==.',Zi='Zizjajim:BAAALAAECgYICQAAAA==.',Zu='Zuly:BAAALAADCgcICQABLAAECgcIEgAIAAAAAA==.Zulyo:BAAALAAECgYIAgABLAAECgcIEgAIAAAAAA==.',Zw='Zwielicht:BAAALAAECgYIEQAAAA==.',Zy='Zylaas:BAAALAAECgYIBwAAAA==.',['Ân']='Ânyone:BAAALAAECgcIEQAAAA==.',['Æo']='Æonia:BAABLAAECoEjAAIiAAgI/hgAFgBfAgAiAAgI/hgAFgBfAgAAAA==.',['Êl']='Êllinar:BAACLAAFFIEaAAIBAAYI4xsFBADnAQABAAYI4xsFBADnAQAsAAQKgTgAAgEACAi1Jt4AAJUDAAEACAi1Jt4AAJUDAAAA.',['Ód']='Ódién:BAAALAAECggICQAAAA==.',['Øw']='Øwen:BAABLAAECoEVAAIQAAgI+QChfQAmAAAQAAgI+QChfQAmAAAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end