local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'DemonHunter-Havoc','Paladin-Retribution','Paladin-Holy','Priest-Holy','Monk-Windwalker','Unknown-Unknown','Mage-Frost','Warrior-Fury','Priest-Shadow','Priest-Discipline','Hunter-Marksmanship','DeathKnight-Unholy','Mage-Fire','Hunter-BeastMastery','Hunter-Survival','Mage-Arcane','Rogue-Subtlety','Monk-Mistweaver','Warlock-Destruction','Warlock-Demonology','Warlock-Affliction','Druid-Balance','Rogue-Assassination','Druid-Restoration','DeathKnight-Frost','Druid-Guardian','Paladin-Protection','Monk-Brewmaster','Evoker-Preservation','DeathKnight-Blood','Warrior-Arms','Druid-Feral',}; local provider = {region='EU',realm='TarrenMill',name='EU',type='subscribers',zone=44,date='2025-09-06',data={Ab='Abondalakaka:BAEALAAECgEIAQAAAA==.',Ai='Aidanio:BAEBLAAECoEYAAIBAAgIuR3YGgCHAgg5DAAAAwBZADsMAAADAFsAOgwAAAMARAA8DAAAAwBDADIMAAADAD0APQwAAAMAUQA+DAAAAwBMAD8MAAADAEcAAQAICLkd2BoAhwIIOQwAAAMAWQA7DAAAAwBbADoMAAADAEQAPAwAAAMAQwAyDAAAAwA9AD0MAAADAFEAPgwAAAMATAA/DAAAAwBHAAAA.',Am='Amkart:BAECLAAFFIEFAAICAAMI0iQdAgBKAQM5DAAAAQBcADsMAAACAGMAOgwAAAIAWgACAAMI0iQdAgBKAQM5DAAAAQBcADsMAAACAGMAOgwAAAIAWgAsAAQKgSAAAwIACAinJbwBAHwDAAIACAinJbwBAHwDAAMAAwiGJIQoACsBAAAA.',Au='Auraylia:BAECLAAFFIEHAAIEAAMIhhJVBgADAQM5DAAAAwAxADsMAAACACYAOgwAAAIANQAEAAMIhhJVBgADAQM5DAAAAwAxADsMAAACACYAOgwAAAIANQAsAAQKgR8AAgQACAhCIGkIAN8CAAQACAhCIGkIAN8CAAAA.Auriestab:BAEALAAECgYIDQAAAA==.Auroralis:BAEALAAECgUICAABLAAFFAMIBwAEAIYSAA==.',Av='Avernus:BAEALAAECgYIEQAAAA==.',Ba='Babybobbin:BAEALAAECggICAABLAAFFAMICAAFANAfAA==.Backbone:BAEALAAECgYIDAAAAA==.Ballripper:BAEALAAECggIDwAAAA==.Baovtuberfan:BAEALAADCggIDwABLAAECgUIBQAGAAAAAA==.Bassiouni:BAEALAAECgcIBwABLAAECggIDwAGAAAAAA==.',Be='Beebeedk:BAEALAADCggIDwABLAAECgYIDAAGAAAAAA==.',Bh='Bhadgar:BAECLAAFFIEGAAIHAAMIJCZRAABYAQM5DAAAAwBiADsMAAABAGEAOgwAAAIAYAAHAAMIJCZRAABYAQM5DAAAAwBiADsMAAABAGEAOgwAAAIAYAAsAAQKgR8AAgcACAj2JgkAAKkDAAcACAj2JgkAAKkDAAAA.',Bi='Bivnyk:BAEBLAAECoEbAAIIAAgIOCIoBwAjAwg5DAAABABeADsMAAAEAFEAOgwAAAQAYgA8DAAABABWADIMAAADAEYAPQwAAAMAYQA+DAAAAwBbAD8MAAACAE8ACAAICDgiKAcAIwMIOQwAAAQAXgA7DAAABABRADoMAAAEAGIAPAwAAAQAVgAyDAAAAwBGAD0MAAADAGEAPgwAAAMAWwA/DAAAAgBPAAAA.',Bl='Blurnklöd:BAECLAAFFIEIAAIEAAMInyIlAwA3AQM5DAAAAwBiADsMAAACAFEAOgwAAAMAVQAEAAMInyIlAwA3AQM5DAAAAwBiADsMAAACAFEAOgwAAAMAVQAsAAQKgRwABAQACAigH9QIANkCAAQACAigH9QIANkCAAkABghjIZ8VAFgCAAoAAQhrCZIjADIAAAAA.',Bo='Bobbindh:BAEALAAFFAIIBAABLAAFFAMICAAFANAfAA==.Bobbinlock:BAEALAAECgMIAwABLAAFFAMICAAFANAfAA==.Bobbinn:BAEALAAECggIDgABLAAFFAMICAAFANAfAA==.Bobbinww:BAECLAAFFIEIAAIFAAMI0B/BAQAoAQM5DAAAAwBRADsMAAACAEIAOgwAAAMAXwAFAAMI0B/BAQAoAQM5DAAAAwBRADsMAAACAEIAOgwAAAMAXwAsAAQKgRkAAgUACAjUIB0FAPYCAAUACAjUIB0FAPYCAAAA.Bombsxd:BAEALAAECgYICQABLAAFFAUICQALACchAA==.',Br='Brutlörg:BAEALAAECgYICgABLAAFFAMICAAEAJ8iAA==.',Bu='Budaika:BAEBLAAECoEeAAIMAAgIICWsAABrAwg5DAAABABjADsMAAAEAGMAOgwAAAQAYwA8DAAABABbADIMAAAEAGEAPQwAAAQAYAA+DAAAAwBaAD8MAAADAFQADAAICCAlrAAAawMIOQwAAAQAYwA7DAAABABjADoMAAAEAGMAPAwAAAQAWwAyDAAABABhAD0MAAAEAGAAPgwAAAMAWgA/DAAAAwBUAAAA.',Ca='Catgrafe:BAEALAADCggICAABLAAFFAMICAAEAJ8iAA==.',Ch='Chaoticqt:BAEALAAECgMIAwABLAAECgYIEQAGAAAAAA==.Chrisknight:BAEALAADCgcIBwABLAAECggIHQANAPYlAA==.',Ci='Cirall:BAECLAAFFIEJAAQLAAQIJyHFAQCUAQQ5DAAAAgBeADsMAAACAFgAOgwAAAMAWwA8DAAAAgBAAAsABAh8IMUBAJQBBDkMAAABAF4AOwwAAAEAUQA6DAAAAQBbADwMAAABAEAADgADCHofsAIAJAEDOwwAAAEAWAA6DAAAAQBYADwMAAABAEAADwACCI8QfQEArQACOQwAAAEANAA6DAAAAQAgACwABAqBFwADDgAHCJkmfQoA8QIADgAHCJkmfQoA8QIACwACCNsld0oA3wAAAAA=.Cirolla:BAEALAAECgQIBwABLAAFFAUICQALACchAA==.',Cl='Clackyclacky:BAEALAAECgIIAgABLAAFFAMIBQAQAN8NAA==.Clackydh:BAEALAAECgYIBQABLAAFFAMIBQAQAN8NAA==.Clackymage:BAECLAAFFIEFAAIQAAMI3w1yCwDvAAM5DAAAAgA0ADsMAAABABIAOgwAAAIAJAAQAAMI3w1yCwDvAAM5DAAAAgA0ADsMAAABABIAOgwAAAIAJAAsAAQKgSAAAxAACAihIdMTAMECABAACAg7INMTAMECAAcAAQgfH8FQAFgAAAAA.Clickyclacky:BAEALAAECgYICwABLAAFFAMIBQAQAN8NAA==.',Cr='Crábbie:BAEALAADCggICAABLAAFFAMIBgARAIkSAA==.Crábby:BAECLAAFFIEGAAIRAAMIiRIsAgD2AAM5DAAAAgBBADsMAAACABAAOgwAAAIAPAARAAMIiRIsAgD2AAM5DAAAAgBBADsMAAACABAAOgwAAAIAPAAsAAQKgR4AAhEACAhMIl4CAPcCABEACAhMIl4CAPcCAAAA.',Da='Daddyor:BAECLAAFFIEGAAIBAAII0hx8DQCwAAI5DAAAAwBQADoMAAADAEIAAQACCNIcfA0AsAACOQwAAAMAUAA6DAAAAwBCACwABAqBHAACAQAICJ4iLgsAEAMAAQAICJ4iLgsAEAMAAAA=.Dajnlock:BAEALAAFFAIIAgAAAA==.',De='Deathlic:BAEALAADCgYIBgABLAAECggIIAABALQfAA==.Demontrick:BAEALAADCggICAABLAAECggIEAAGAAAAAA==.',Do='Dodgerblue:BAEALAAECgQIBwABLAAFFAMIBQACANIkAA==.Dotstep:BAEALAAECgYICAAAAA==.',Dr='Drazor:BAEBLAAECoEdAAINAAgI9iUuAABuAwg5DAAABABfADsMAAAEAGEAOgwAAAQAYAA8DAAABABhADIMAAAEAGMAPQwAAAQAXwA+DAAAAwBiAD8MAAACAGAADQAICPYlLgAAbgMIOQwAAAQAXwA7DAAABABhADoMAAAEAGAAPAwAAAQAYQAyDAAABABjAD0MAAAEAF8APgwAAAMAYgA/DAAAAgBgAAAA.Drazormag:BAEALAAFFAIIAgABLAAECggIHQANAPYlAA==.Drazormage:BAEALAAECgYIBgABLAAECggIHQANAPYlAA==.',El='Elyvya:BAEBLAAECoEUAAMHAAcI1RiOFAD5AQc5DAAAAwBIADsMAAADAEYAOgwAAAMAPQA8DAAAAwBLADIMAAAEAE0APQwAAAMARQA+DAAAAQASAAcABwjVGI4UAPkBBzkMAAACAEgAOwwAAAMARgA6DAAAAwA9ADwMAAADAEsAMgwAAAQATQA9DAAAAwBFAD4MAAABABIAEAABCFQBR6IADQABOQwAAAEAAwAAAA==.',Em='Emdeevy:BAEBLAAECoEgAAIBAAgItB+vDwDmAgg5DAAABgBhADsMAAAGAGEAOgwAAAUAVQA8DAAAAwBIADIMAAADAFkAPQwAAAQAXgA+DAAAAgAhAD8MAAADAE4AAQAICLQfrw8A5gIIOQwAAAYAYQA7DAAABgBhADoMAAAFAFUAPAwAAAMASAAyDAAAAwBZAD0MAAAEAF4APgwAAAIAIQA/DAAAAwBOAAAA.Emdeevÿ:BAEBLAAECoEVAAIBAAcIMiGiGgCIAgc5DAAABABgADsMAAADAF4AOgwAAAMATgA8DAAAAwA/ADIMAAADAFoAPQwAAAIAXwA+DAAAAwBMAAEABwgyIaIaAIgCBzkMAAAEAGAAOwwAAAMAXgA6DAAAAwBOADwMAAADAD8AMgwAAAMAWgA9DAAAAgBfAD4MAAADAEwAASwABAoICCAAAQC0HwA=.',Es='Esskitty:BAEALAAECgMIBQABLAAECgYIBgAGAAAAAA==.',Fl='Flyinge:BAEALAADCggIEAABLAAFFAMIBgALAK8UAA==.',Gr='Grafe:BAEBLAAECoEZAAISAAgI4iS/AABfAwg5DAAABABfADsMAAAEAGEAOgwAAAQAYAA8DAAAAwBiADIMAAADAF8APQwAAAMAXwA+DAAAAgBdAD8MAAACAFEAEgAICOIkvwAAXwMIOQwAAAQAXwA7DAAABABhADoMAAAEAGAAPAwAAAMAYgAyDAAAAwBfAD0MAAADAF8APgwAAAIAXQA/DAAAAgBRAAEsAAUUAwgIAAQAnyIA.Grimlockout:BAEALAAECggIBgABLAAECggIBgAGAAAAAA==.',Ha='Hannibaly:BAECLAAFFIEKAAMLAAQIjBw/AgBkAQQ5DAAAAQAvADsMAAADADYAOgwAAAQAXgA8DAAAAgBfAAsABAiMHD8CAGQBBDkMAAABAC8AOwwAAAMANgA6DAAAAwBeADwMAAACAF8ADgABCBkBwRYAMwABOgwAAAEAAgAsAAQKgRsAAgsACAiOJPkFAAwDAAsACAiOJPkFAAwDAAAA.',Ja='Jazzylockton:BAECLAAFFIEFAAMTAAIIWhmnDQC3AAI5DAAAAwBWADoMAAACACsAEwACCFoZpw0AtwACOQwAAAIAVgA6DAAAAQArABQAAgiFCUILAJcAAjkMAAABAAoAOgwAAAEAJgAsAAQKgRcABBQACAgsIXQSAP8BABQABgiDH3QSAP8BABMAAwgOHNVbAPoAABUAAQjBIHQpAFoAAAAA.Jazzywizard:BAEALAAECgYIBgABLAAFFAIIBQATAFoZAA==.',Jc='Jcbdruid:BAECLAAFFIEGAAIWAAMIahvSAgAaAQM5DAAAAwBcADsMAAABAEMAOgwAAAIAMgAWAAMIahvSAgAaAQM5DAAAAwBcADsMAAABAEMAOgwAAAIAMgAsAAQKgR0AAhYACAgWJgoBAHsDABYACAgWJgoBAHsDAAAA.',Jh='Jhonitwo:BAEALAAECgYIDwAAAA==.',Ju='Justwaitm:BAEALAAECgYIBgAAAA==.',Kc='Kcx:BAEALAAECgYIBgABLAAFFAUIDAAXAPoYAA==.',Ke='Kelebrindal:BAECLAAFFIEIAAIWAAMI2iNMAgAuAQM5DAAAAwBgADsMAAACAF8AOgwAAAMAUwAWAAMI2iNMAgAuAQM5DAAAAwBgADsMAAACAF8AOgwAAAMAUwAsAAQKgR4AAxYACAgIJocBAG8DABYACAgIJocBAG8DABgAAwirG0RYALAAAAAA.Kelehunter:BAEALAADCggICAABLAAFFAMICAAWANojAA==.Ketanji:BAEALAAECgYIDwAAAA==.',Kf='Kfcdk:BAEALAADCgIIAgABLAAFFAUIDAAXAPoYAA==.Kfcw:BAEALAAFFAIIAwABLAAFFAUIDAAXAPoYAA==.',Ki='Kizúma:BAEALAADCggIEAAAAA==.',Km='Kmae:BAEALAADCggICAABLAAECggIFAAJAKcWAA==.',Kr='Krakón:BAEALAAFFAIIAgAAAA==.',Kx='Kxb:BAEALAADCggICAABLAAFFAUIDAAXAPoYAA==.Kxf:BAECLAAFFIEMAAMXAAUI+hhYAADsAQU5DAAABABhADsMAAACAFkAOgwAAAEAHgA8DAAAAwApAD0MAAACADsAFwAFCNAWWAAA7AEFOQwAAAQAYQA7DAAAAgBZADoMAAABAB4APAwAAAEADgA9DAAAAQA7ABEAAggxD5QDALIAAjwMAAACACkAPQwAAAEAIwAsAAQKgRwAAxcACAg+JWEEABQDABcACAhLIWEEABQDABEABAhOJJwNAKIBAAAA.Kxo:BAEBLAAECoEXAAMXAAgIpB/qCADGAgg5DAAAAwBeADsMAAADAF4AOgwAAAMARwA8DAAAAwBcADIMAAADAFwAPQwAAAMAVQA+DAAAAwA9AD8MAAACADkAFwAICEMe6ggAxgIIOQwAAAMAXgA7DAAAAwBeADoMAAACAEcAPAwAAAMAXAAyDAAAAgBAAD0MAAADAFUAPgwAAAMAPQA/DAAAAgA5ABEAAginFZwfAJQAAjoMAAABABIAMgwAAAEAXAABLAAFFAUIDAAXAPoYAA==.',Li='Lizzydkante:BAEALAADCggICAABLAAFFAIIBgAZAPoXAA==.',Lu='Lumicast:BAEALAAECggIEAAAAA==.',Ma='Magnitizese:BAEALAAECggIEAAAAA==.Manicepisode:BAEALAADCggICAAAAA==.',Me='Meeresbarrel:BAEALAAECggIEgAAAA==.Meeresflask:BAEALAAECggIDQABLAAECggIEgAGAAAAAA==.Meeresmana:BAEALAAECggIDgABLAAECggIEgAGAAAAAA==.Meeresrestin:BAEALAAECggICAABLAAECggIEgAGAAAAAA==.Meeresup:BAEALAAECgEIAQABLAAECggIEgAGAAAAAA==.Meerés:BAEALAAECgEIAQABLAAECggIEgAGAAAAAA==.Meéres:BAEALAAECggICAABLAAECggIEgAGAAAAAA==.',Mi='Misuz:BAEALAAECgIIAwAAAA==.',Mo='Monitrees:BAEALAADCggICgABLAAFFAMIBQACANIkAA==.Monkmansteve:BAEALAAECgMIBAABLAAECgYIDQAGAAAAAA==.Moowalker:BAECLAAFFIEJAAIYAAQIkAtWAgAvAQQ5DAAAAwA8ADsMAAADABcAOgwAAAIABAA9DAAAAQAeABgABAiQC1YCAC8BBDkMAAADADwAOwwAAAMAFwA6DAAAAgAEAD0MAAABAB4ALAAECoEZAAMYAAgIRQ9IKwCMAQAYAAgIRQ9IKwCMAQAaAAIIugH7GgA0AAAAAA==.Mowser:BAEALAAECgYIEQABLAAFFAYIDgAWAHYhAA==.Mowsffs:BAECLAAFFIEOAAIWAAYIdiEoAABoAgY5DAAAAgBVADsMAAADAFwAOgwAAAQAXAA8DAAAAgBeADIMAAABADsAPQwAAAIAWQAWAAYIdiEoAABoAgY5DAAAAgBVADsMAAADAFwAOgwAAAQAXAA8DAAAAgBeADIMAAABADsAPQwAAAIAWQAsAAQKgSAAAhYACAjRJikAAJwDABYACAjRJikAAJwDAAAA.',['Mã']='Mãedestifler:BAECLAAFFIEHAAIQAAMIvyXfBABPAQM5DAAAAwBeADsMAAACAGAAOgwAAAIAYwAQAAMIvyXfBABPAQM5DAAAAwBeADsMAAACAGAAOgwAAAIAYwAsAAQKgR8AAxAACAj5JQgKABMDABAACAj5JQgKABMDAA0ABQhMIs4DAO8BAAAA.',['Mò']='Mòr:BAEALAAECggICwAAAA==.',Na='Nalkros:BAEALAADCgEIAQABLAADCggIFQAGAAAAAA==.Naytha:BAEALAAECgYIDAABLAAFFAMICAAXAJ4ZAA==.',Ne='Neebelwerfer:BAECLAAFFIELAAIRAAUIsyRWAAAhAgU5DAAAAwBfADsMAAADAF8AOgwAAAIAYwA8DAAAAgBdAD0MAAABAFUAEQAFCLMkVgAAIQIFOQwAAAMAXwA7DAAAAwBfADoMAAACAGMAPAwAAAIAXQA9DAAAAQBVACwABAqBIAACEQAICM0mCwAAmwMAEQAICM0mCwAAmwMAAAA=.',Ni='Niirubrew:BAEALAAECggICgABLAAFFAQIBgABANQYAA==.Niirudh:BAECLAAFFIEGAAIBAAQI1BjGAgB8AQQ5DAAAAgBeADsMAAABAEwAOgwAAAIAQQA9DAAAAQARAAEABAjUGMYCAHwBBDkMAAACAF4AOwwAAAEATAA6DAAAAgBBAD0MAAABABEALAAECoEbAAIBAAgI5CXGAgBqAwABAAgI5CXGAgBqAwAAAA==.Ninefive:BAEALAAFFAIIBAAAAA==.Nirty:BAECLAAFFIEIAAIXAAMInhlrAwAbAQM5DAAAAgBUADsMAAADAC4AOgwAAAMAQQAXAAMInhlrAwAbAQM5DAAAAgBUADsMAAADAC4AOgwAAAMAQQAsAAQKgRgAAhcACAj6JNcBAEgDABcACAj6JNcBAEgDAAAA.',Nn='Nnoggielock:BAEALAAECgQIBAAAAA==.',No='Nobot:BAEALAAFFAIIAgAAAA==.Norfrendfc:BAEALAAECgIIAgABLAAECgUIBQAGAAAAAA==.Notdeathwing:BAEALAADCggICAABLAAECggIDwAGAAAAAA==.',Nu='Nullbot:BAECLAAFFIEPAAMEAAUIkhnnAQByAQU5DAAABABaADsMAAADADYAOgwAAAQAWwA8DAAAAgA0AD0MAAACACYABAAECM4a5wEAcgEEOQwAAAQAWgA7DAAAAwA2ADoMAAAEAFsAPQwAAAIAJgAJAAEIwAa9EgBRAAE8DAAAAgARACwABAqBGgACBAAICEAb0g8AhgIABAAICEAb0g8AhgIAASwABRQCCAIABgAAAAA=.',Oa='Oatlaw:BAEALAAFFAUIBAAAAA==.Oatlymonk:BAEALAAECggICAABLAAFFAUIBAAGAAAAAA==.',Of='Offheal:BAEALAAECgYIDwABLAAECggIDwAGAAAAAA==.',Pa='Palleriino:BAEALAADCgcIBwABLAADCggIFQAGAAAAAA==.',Pe='Pedroksi:BAEALAADCggIFQAAAA==.Petahatesme:BAEALAADCgcIBwABLAAECgUIBQAGAAAAAA==.',Po='Pokapoka:BAECLAAFFIERAAICAAYIoCIYAAB2AgY5DAAABABgADsMAAADAFIAOgwAAAQAVwA8DAAAAgBVADIMAAACAFcAPQwAAAIAWwACAAYIoCIYAAB2AgY5DAAABABgADsMAAADAFIAOgwAAAQAVwA8DAAAAgBVADIMAAACAFcAPQwAAAIAWwAsAAQKgRgAAgIACAhNJtcDAGEDAAIACAhNJtcDAGEDAAAA.',Pr='Priestinus:BAECLAAFFIEPAAIEAAUIfhkDAQDHAQU5DAAABABLADsMAAADAE8AOgwAAAQAWwA8DAAAAgASAD0MAAACADwABAAFCH4ZAwEAxwEFOQwAAAQASwA7DAAAAwBPADoMAAAEAFsAPAwAAAIAEgA9DAAAAgA8ACwABAqBHwACBAAICBImaQAAgAMABAAICBImaQAAgAMAAAA=.Primevoker:BAEALAAECgcIEgAAAA==.',Py='Pyroblasta:BAEBLAAECoEbAAMQAAgIJBwlHwBtAgg5DAAAAwBdADsMAAAEAFoAOgwAAAQAWQA8DAAABABQADIMAAAEACUAPQwAAAQAUQA+DAAAAwA6AD8MAAABAC0AEAAICIcbJR8AbQIIOQwAAAMAXQA7DAAABABaADoMAAAEAFkAPAwAAAQAUAAyDAAAAwAZAD0MAAAEAFEAPgwAAAMAOgA/DAAAAQAtAA0AAQjGDpUTADwAATIMAAABACUAAAA=.',Ra='Raveres:BAEALAAECggIBgABLAAFFAQICgALAIwcAA==.',Sa='Sadb:BAECLAAFFIEJAAQVAAUIchRyAADNAAU5DAAAAgAiADsMAAADACkAOgwAAAIALQA8DAAAAQBJAD0MAAABAEMAFQACCJMbcgAAzQACPAwAAAEASQA9DAAAAQBDABMAAgi5DgQTAKIAAjkMAAACACIAOwwAAAMAKQAUAAEInxGjEgBTAAE6DAAAAgAtACwABAqBIAAEFQAICLglMQAAhgMAFQAICLglMQAAhgMAEwAHCCcieRMAmQIAFAAECNMVkDoAAQEAAAA=.Sadbu:BAEALAAFFAIIAgABLAAFFAUICQAVAHIUAA==.',Sc='Scambot:BAEALAAECgYIDAABLAAFFAIIAgAGAAAAAA==.Schnittmage:BAEALAADCgYIBgABLAAECgcIFgAWAAUgAA==.Sctioneighte:BAEALAADCgQIBAABLAAFFAMIBQACANIkAA==.',Sh='Shadowcrasha:BAEALAADCggIEAABLAAECggIGwAQACQcAA==.Shadowtheone:BAEALAAECgYIDAABLAAECggIHgAMACAlAA==.Shalfudeath:BAEALAAECgcIDQABLAAFFAIIAgAGAAAAAQ==.Shalfumeta:BAEALAAFFAIIAgAAAQ==.Shalfuscars:BAEALAAECgcIBgABLAAFFAIIAgAGAAAAAQ==.Shalfuwinter:BAEALAAECgcIDQABLAAFFAIIAgAGAAAAAQ==.Shalfuwrath:BAEALAAECgYICAABLAAFFAIIAgAGAAAAAQ==.Shalfuyoutou:BAEALAAECgYIBgABLAAFFAIIAgAGAAAAAQ==.Sharelia:BAECLAAFFIEMAAIbAAUILxSeAACXAQU5DAAAAwBHADsMAAADADAAOgwAAAMANwA8DAAAAgBIAD0MAAABAAoAGwAFCC8UngAAlwEFOQwAAAMARwA7DAAAAwAwADoMAAADADcAPAwAAAIASAA9DAAAAQAKACwABAqBIgACGwAICA0jewIAKwMAGwAICA0jewIAKwMAAAA=.',Sl='Slottiebrew:BAEBLAAECoEWAAIcAAgIwh2NBgCTAgg5DAAAAwBaADsMAAADAFgAOgwAAAMARAA8DAAAAwAoADIMAAADAE0APQwAAAMAXAA+DAAAAgBcAD8MAAACADoAHAAICMIdjQYAkwIIOQwAAAMAWgA7DAAAAwBYADoMAAADAEQAPAwAAAMAKAAyDAAAAwBNAD0MAAADAFwAPgwAAAIAXAA/DAAAAgA6AAAA.Slottieclap:BAEALAAECgYIDAABLAAECggIFgAcAMIdAA==.',Sm='Smukex:BAEALAAECgcIDwAAAA==.',Sn='Snoozing:BAECLAAFFIEPAAIdAAYIjw/EAAD3AQY5DAAABAAtADsMAAADAEwAOgwAAAMAIAA8DAAAAgASADIMAAABABAAPQwAAAIAMQAdAAYIjw/EAAD3AQY5DAAABAAtADsMAAADAEwAOgwAAAMAIAA8DAAAAgASADIMAAABABAAPQwAAAIAMQAsAAQKgRwAAh0ACAgJGbUMALkBAB0ACAgJGbUMALkBAAAA.',So='Soobaroo:BAECLAAFFIEGAAITAAMIzAzICQDzAAM5DAAAAgAWADsMAAACAB0AOgwAAAIALgATAAMIzAzICQDzAAM5DAAAAgAWADsMAAACAB0AOgwAAAIALgAsAAQKgR4ABBMACAjJII8KAPYCABMACAjJII8KAPYCABUABgg7GdkJANABABQAAQiXHpxcAFMAAAAA.',St='Stregonardo:BAECLAAFFIEGAAMTAAMIFB3dDQC1AAM5DAAAAgBKADsMAAACADsAOgwAAAIAWQATAAIIMRrdDQC1AAI5DAAAAgBKADsMAAACADsAFAABCNwi4g0AaAABOgwAAAIAWQAsAAQKgRYAAxMACAilI6MHABgDABMACAjLIqMHABgDABUABgjEIIgFADcCAAAA.Streifer:BAEALAAECgMIAwAAAA==.',Ta='Tankreroll:BAEALAAECggIBgAAAA==.Tasdruid:BAEALAAECgYIBgABLAAFFAMIBQAeAIAXAA==.Tasmiina:BAECLAAFFIEFAAMDAAIIPBhkBwC0AAI5DAAAAwBRADoMAAACACsAAwACCDwYZAcAtAACOQwAAAEAUQA6DAAAAQArABsAAgi+HRsEAK0AAjkMAAACAFoAOgwAAAEAPQAsAAQKgRYAAhsACAiqJTwBAGADABsACAiqJTwBAGADAAEsAAUUAwgFAB4AgBcA.Tassdk:BAEBLAAFFIEFAAIeAAMIgBcYAgD6AAM5DAAAAQAnADsMAAACAD8AOgwAAAIATAAeAAMIgBcYAgD6AAM5DAAAAQAnADsMAAACAD8AOgwAAAIATAAAAA==.Tastank:BAEALAAECgYICgABLAAFFAMIBQAeAIAXAA==.Taswarrtwo:BAEALAADCggICAABLAAFFAMIBQAeAIAXAA==.',Th='Thiccgrafe:BAEALAAECgEIAQABLAAFFAMICAAEAJ8iAA==.',Ti='Tikita:BAEALAAECgYIBgAAAA==.',To='Toffpriest:BAEALAAECggIDwAAAA==.Tomikage:BAECLAAFFIEJAAIJAAUI9RHQAQCuAQU5DAAAAgAqADsMAAADACMAOgwAAAIAOQA8DAAAAQAkAD0MAAABADoACQAFCPUR0AEArgEFOQwAAAIAKgA7DAAAAwAjADoMAAACADkAPAwAAAEAJAA9DAAAAQA6ACwABAqBGAACCQAICIckrQQANwMACQAICIckrQQANwMAAAA=.Tomiroku:BAEALAADCggIDwABLAAFFAUICQAJAPURAA==.',Tr='Trapninja:BAEALAAECgIIAgABLAAFFAMIBgAIAAEiAA==.Trapraijin:BAECLAAFFIEGAAMIAAMIASK9AwAyAQM5DAAAAgBbADsMAAABAE4AOgwAAAMAWgAIAAMImSG9AwAyAQM5DAAAAQBYADsMAAABAE4AOgwAAAIAWgAfAAIIlxlGAQCtAAI5DAAAAQBbADoMAAABACcALAAECoEgAAIIAAgISSZIAQB3AwAIAAgISSZIAQB3AwAAAA==.Trbo:BAEALAADCggICAABLAAECggIBgAGAAAAAA==.Trbofister:BAEALAAECgYIEwABLAAECggIBgAGAAAAAA==.',Tu='Turbobozo:BAEALAAECggIBgAAAA==.',Ty='Tyraxxis:BAEALAAECgMIBgAAAA==.',['Tì']='Tìst:BAECLAAFFIEFAAICAAMIOBlHAwAhAQM5DAAAAgBfADsMAAABAAwAOgwAAAIAVgACAAMIOBlHAwAhAQM5DAAAAgBfADsMAAABAAwAOgwAAAIAVgAsAAQKgR0AAgIACAg4JlIBAIQDAAIACAg4JlIBAIQDAAAA.',Va='Varedï:BAEALAADCggICAABLAAFFAMICAAWANojAA==.',Ve='Vermaelion:BAEALAADCgQIBQABLAAECgYIFQAgANQWAA==.Vermhealion:BAEBLAAECoEVAAIgAAYI1Bb9DwC5AQY5DAAABABSADsMAAAEAEUAOgwAAAQAPQA8DAAAAwAgADIMAAAEAB8APQwAAAIASAAgAAYI1Bb9DwC5AQY5DAAABABSADsMAAAEAEUAOgwAAAQAPQA8DAAAAwAgADIMAAAEAB8APQwAAAIASAAAAA==.Vermilión:BAEALAADCgMIAwABLAAECgYIFQAgANQWAA==.Verykeggable:BAEALAAECgUIBQAAAA==.',We='Weemagey:BAEALAAECgcIEAAAAA==.',Ye='Yesmommy:BAEALAAECgYIEQAAAA==.',Yu='Yuzulime:BAEALAAECgIIAgABLAAECgcIDwAGAAAAAA==.',Za='Zambrop:BAEBLAAECoEUAAIJAAgIpxYyGQAyAgg5DAAAAwBEADsMAAADAFMAOgwAAAMAOwA8DAAAAwBNADIMAAADADkAPQwAAAMAQAA+DAAAAQAiAD8MAAABABMACQAICKcWMhkAMgIIOQwAAAMARAA7DAAAAwBTADoMAAADADsAPAwAAAMATQAyDAAAAwA5AD0MAAADAEAAPgwAAAEAIgA/DAAAAQATAAAA.',['Ál']='Álicé:BAEALAAECgIIAgAAAA==.',['Ín']='Ínge:BAECLAAFFIEGAAILAAMIrxRsBgDYAAM5DAAAAgBCADsMAAACACcAOgwAAAIANQALAAMIrxRsBgDYAAM5DAAAAgBCADsMAAACACcAOgwAAAIANQAsAAQKgRgAAgsACAhAIXoLAL4CAAsACAhAIXoLAL4CAAAA.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end