local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Unknown-Unknown','Monk-Brewmaster','Rogue-Subtlety','DemonHunter-Havoc','Hunter-BeastMastery','Mage-Arcane','Mage-Fire','Mage-Frost','Rogue-Assassination','Druid-Guardian','Warrior-Protection','Warlock-Destruction','Monk-Windwalker','DeathKnight-Frost','DeathKnight-Blood','DeathKnight-Unholy','Hunter-Marksmanship','Warrior-Fury','Priest-Holy','Priest-Shadow','Paladin-Retribution','Druid-Restoration','Paladin-Holy','Warlock-Demonology','Warlock-Affliction','Evoker-Preservation','Monk-Mistweaver','Rogue-Outlaw','Shaman-Elemental','Paladin-Protection','Druid-Balance','Shaman-Restoration',}; local provider = {region='EU',realm='Silvermoon',name='EU',type='subscribers',zone=44,date='2025-09-25',data={Ac='Acedc:BAEALAAECgYIDAABLAAECgUIBgABAAAAAA==.Acemnk:BAECLAAFFIEXAAICAAcItx+VAACcAgc5DAAABQBfADsMAAAEAF0AOgwAAAUAWgA8DAAAAwBRADIMAAACAFwAPQwAAAMAVQA+DAAAAQAdAAIABwi3H5UAAJwCBzkMAAAFAF8AOwwAAAQAXQA6DAAABQBaADwMAAADAFEAMgwAAAIAXAA9DAAAAwBVAD4MAAABAB0ALAAECoEgAAICAAgIBibnAQBcAwACAAgIBibnAQBcAwABLAAECgUIBgABAAAAAA==.Acepally:BAEALAAECgUIBgAAAA==.',Ad='Adrian:BAEALAADCgYIDAABLAAECgYIFQADAAcfAA==.',Ai='Aindra:BAEALAADCggICAABLAAECgMIBgABAAAAAA==.',Al='Albinioz:BAEBLAAECoEVAAIEAAYIOhv0WQDzAQY5DAAABQAiADsMAAAFAEwAOgwAAAQATAA8DAAAAgBNADIMAAAEAFEAPQwAAAEARwAEAAYIOhv0WQDzAQY5DAAABQAiADsMAAAFAEwAOgwAAAQATAA8DAAAAgBNADIMAAAEAFEAPQwAAAEARwABLAAECggIIQADALgeAA==.',Am='Amarèya:BAEALAADCggIDwABLAAECgcIIwAFAIIZAA==.',Ar='Aryella:BAECLAAFFIEaAAQGAAgIriDTAACzAgg5DAAABQBjADsMAAADAGQAOgwAAAUAWwA8DAAABAAvADIMAAADAFgAPQwAAAQAZAA+DAAAAQBGAD8MAAABAEcABgAHCPYc0wAAswIHOQwAAAMAYwA7DAAAAQAlADoMAAACAFsAPAwAAAMALwA9DAAAAgBjAD4MAAABAEYAPwwAAAEARwAHAAYIAyBEAAA7AgY5DAAAAgBhADsMAAABAGQAOgwAAAMAVgA8DAAAAQASADIMAAADAFgAPQwAAAIAZAAIAAEIKSLeFQBUAAE7DAAAAQBXACwABAqBIwAEBwAICOcmSwAAdgMABwAICN4mSwAAdgMABgAHCJUmESUApgIACAAGCNoffjIAjgEAAAA=.Arythreella:BAECLAAFFIEHAAIGAAMIVh50GAAHAQM5DAAAAwBVADsMAAABADQAOgwAAAMAXwAGAAMIVh50GAAHAQM5DAAAAwBVADsMAAABADQAOgwAAAMAXwAsAAQKgRYABAYACAh7JQcTAAMDAAYACAh7JQcTAAMDAAgABgigHk44AHEBAAcAAQixInQYAFYAAAEsAAUUCAgaAAYAriAA.Arytwoella:BAECLAAFFIEGAAIGAAIIah5tIwDCAAI5DAAAAwBfADoMAAADADwABgACCGoebSMAwgACOQwAAAMAXwA6DAAAAwA8ACwABAqBHwADBgAICNojqhcA6QIABgAICG4jqhcA6QIACAAICJceihQAXgIAASwABRQICBoABgCuIAA=.',Ba='Babamagûs:BAEBLAAFFIEKAAIGAAIIjyP4IgDEAAI5DAAABQBdADoMAAAFAFgABgACCI8j+CIAxAACOQwAAAUAXQA6DAAABQBYAAEsAAUUBwgaAAkA1R0A.',Ca='Cairnsy:BAECLAAFFIEcAAIKAAYIrRk6AAAbAgY5DAAABgBOADsMAAAFAEsAOgwAAAYAVQA8DAAABABWADIMAAADABYAPQwAAAQALgAKAAYIrRk6AAAbAgY5DAAABgBOADsMAAAFAEsAOgwAAAYAVQA8DAAABABWADIMAAADABYAPQwAAAQALgAsAAQKgRwAAgoACAhEJO0BADIDAAoACAhEJO0BADIDAAAA.Cairnsywar:BAECLAAFFIEFAAILAAMImgpcDAC5AAM5DAAAAgAcADsMAAABABgAOgwAAAIAHAALAAMImgpcDAC5AAM5DAAAAgAcADsMAAABABgAOgwAAAIAHAAsAAQKgSMAAgsACAjOHTYPAKECAAsACAjOHTYPAKECAAEsAAUUBggcAAoArRkA.',Ce='Celarandili:BAEBLAAECoEcAAIMAAgIzRgRJgCLAgg5DAAABQBaADsMAAAEAEIAOgwAAAQAWQA8DAAABABIADIMAAAEAFoAPQwAAAQARgA+DAAAAQAOAD8MAAACAAwADAAICM0YESYAiwIIOQwAAAUAWgA7DAAABABCADoMAAAEAFkAPAwAAAQASAAyDAAABABaAD0MAAAEAEYAPgwAAAEADgA/DAAAAgAMAAEsAAUUAwgOAA0ATB0A.',Ch='Churo:BAECLAAFFIEGAAIGAAIIsRrQLgChAAI5DAAAAwBRADoMAAADADcABgACCLEa0C4AoQACOQwAAAMAUQA6DAAAAwA3ACwABAqBIQACBgAICHYgpR4AxQIABgAICHYgpR4AxQIAAAA=.',Ci='Cifboomy:BAEALAAECgEIAQABLAAFFAYIEwABAAAAAQ==.Cifhilis:BAEALAAECgIIAgABLAAFFAYIEwABAAAAAQ==.',Cl='Clarkinus:BAEBLAAECoEiAAQOAAgIdxvZPwBcAgg5DAAABQBFADsMAAAFAE8AOgwAAAQASgA8DAAABABUADIMAAAGAEAAPQwAAAcAYwA+DAAAAgAwAD8MAAABACoADgAICCca2T8AXAIIOQwAAAIARQA7DAAAAgBDADoMAAACAEoAPAwAAAMAVAAyDAAABQBAAD0MAAADAFQAPgwAAAEAMAA/DAAAAQAqAA8ABwigFvQaAIkBBzkMAAABAEIAOwwAAAEAQAA6DAAAAQA1ADwMAAABAEoAMgwAAAEAJwA9DAAAAQA9AD4MAAABACwAEAAECPwbaDcA9wAEOQwAAAIAQAA7DAAAAgBPADoMAAABACsAPQwAAAMAYwAAAA==.Clarklock:BAEALAADCggICAABLAAECggIIgAOAHcbAA==.',Cr='Crawenn:BAEBLAAECoEdAAIRAAcI8yIvFACyAgc5DAAABQBiADsMAAAFAF0AOgwAAAUAYwA8DAAABQBeADIMAAAEAFMAPQwAAAQASgA+DAAAAQBTABEABwjzIi8UALICBzkMAAAFAGIAOwwAAAUAXQA6DAAABQBjADwMAAAFAF4AMgwAAAQAUwA9DAAABABKAD4MAAABAFMAAAA=.Croxxie:BAEBLAAECoEUAAISAAgILyLFDQAjAwg5DAAABABgADsMAAADAGIAOgwAAAQAVQA8DAAAAwBZADIMAAACAFgAPQwAAAIASgA+DAAAAQBZAD8MAAABAE0AEgAICC8ixQ0AIwMIOQwAAAQAYAA7DAAAAwBiADoMAAAEAFUAPAwAAAMAWQAyDAAAAgBYAD0MAAACAEoAPgwAAAEAWQA/DAAAAQBNAAEsAAQKCAgjAAgAECYA.Crw:BAEBLAAECoEWAAMTAAcIKx4/LQAUAgc5DAAABQBfADsMAAAEAFoAOgwAAAMAUgA8DAAAAwA/ADIMAAADAEUAPQwAAAMAVAA+DAAAAQA2ABMABwgrHj8tABQCBzkMAAAEAF8AOwwAAAQAWgA6DAAAAwBSADwMAAADAD8AMgwAAAMARQA9DAAAAwBUAD4MAAABADYAFAABCBMC/ZYADwABOQwAAAEABQABLAAECgcIHQARAPMiAA==.',De='Deathhit:BAEALAAECgYIEgABLAAFFAQIDwAKAB0VAA==.',Di='Dimaethorwen:BAEALAAECgYIDAABLAAFFAMICgALAAQWAA==.',Do='Domarelius:BAEALAADCggIDwABLAAECggIFwAVAPMdAA==.Domariel:BAEALAAECggIEQABLAAECggIFwAVAPMdAA==.Domatheus:BAEBLAAECoEXAAIVAAgI8x3EKQCqAgg5DAAAAwBXADsMAAADAFMAOgwAAAMAVwA8DAAAAwAzADIMAAADAEoAPQwAAAMAYAA+DAAAAwBGAD8MAAACADwAFQAICPMdxCkAqgIIOQwAAAMAVwA7DAAAAwBTADoMAAADAFcAPAwAAAMAMwAyDAAAAwBKAD0MAAADAGAAPgwAAAMARgA/DAAAAgA8AAAA.Domvahkiin:BAEALAAECggICAABLAAECggIFwAVAPMdAA==.Domvein:BAEALAAECggIEAABLAAECggIFwAVAPMdAA==.',Ep='Ephoker:BAEALAAECggIEAABLAAFFAYIFAAWALcdAA==.',Er='Eraticartist:BAEBLAAECoElAAIFAAgIxh8ZGQDSAgg5DAAABQBaADsMAAAFAFgAOgwAAAQATgA8DAAABABjADIMAAAFAFQAPQwAAAUAVAA+DAAABQBaAD8MAAAEACIABQAICMYfGRkA0gIIOQwAAAUAWgA7DAAABQBYADoMAAAEAE4APAwAAAQAYwAyDAAABQBUAD0MAAAFAFQAPgwAAAUAWgA/DAAABAAiAAAA.Erñest:BAEALAAFFAYIAgAAAA==.',Ex='Exalez:BAEBLAAECoEXAAIXAAYIdR8OHAAHAgY5DAAABABbADsMAAAEAGAAOgwAAAUAXgA8DAAABAA6ADIMAAAEAFAAPQwAAAIAPAAXAAYIdR8OHAAHAgY5DAAABABbADsMAAAEAGAAOgwAAAUAXgA8DAAABAA6ADIMAAAEAFAAPQwAAAIAPAABLAAFFAIIBgAHAIAfAA==.Exaltarion:BAEALAAECggIEwAAAA==.',Fe='Fearzok:BAEBLAAECoEnAAIFAAgI6h5yOABCAgg5DAAABQBhADsMAAAFAFwAOgwAAAUARQA8DAAABgBUADIMAAAFAFoAPQwAAAUAXAA+DAAABQA6AD8MAAADAC8ABQAICOoecjgAQgIIOQwAAAUAYQA7DAAABQBcADoMAAAFAEUAPAwAAAYAVAAyDAAABQBaAD0MAAAFAFwAPgwAAAUAOgA/DAAAAwAvAAAA.Feliea:BAECLAAFFIEGAAIYAAIIKyVIBADWAAI5DAAAAwBhADoMAAADAFwAGAACCCslSAQA1gACOQwAAAMAYQA6DAAAAwBcACwABAqBMAACGAAICIAmNgAAlQMAGAAICIAmNgAAlQMAAAA=.',Fi='Fikru:BAEALAADCggIDwABLAAFFAUIFwAYAMkdAA==.Fikrus:BAECLAAFFIEIAAMUAAIIaAonHACFAAI5DAAABAAZADoMAAAEABsAFAACCGgKJxwAhQACOQwAAAQAGQA6DAAAAwAbABMAAQheAKU5AC0AAToMAAABAAAALAAECoEXAAIUAAgI9BQZJgAuAgAUAAgI9BQZJgAuAgABLAAFFAUIFwAYAMkdAA==.Fikrux:BAECLAAFFIEXAAMYAAUIyR0xAAD7AQU5DAAABgBcADsMAAAFAEUAOgwAAAYAYwA8DAAABABFAD0MAAACADEAGAAFCMkdMQAA+wEFOQwAAAQAXAA7DAAAAwBFADoMAAAEAGMAPAwAAAQARQA9DAAAAgAxAAwAAwiJGBMXAAUBAzkMAAACAEkAOwwAAAIAFQA6DAAAAgBdACwABAqBLAAEGAAICJ0kQQUABAMAGAAICFYkQQUABAMADAAICD4gpBYA5wIAGQABCPUSCDsAOwAAAAA=.',Ge='Genshinwaifu:BAEALAADCgcIBwABLAAFFAYIGAAOALceAA==.',Gh='Ghuzzi:BAEALAADCgEIAQABLAAECgYIFQADAAcfAA==.Ghuzzuk:BAEALAAECgEIAQABLAAECgYIFQADAAcfAA==.',Gr='Grimfrost:BAECLAAFFIEKAAIOAAIIBCPfJwC2AAI5DAAABQBXADoMAAAFAFsADgACCAQj3ycAtgACOQwAAAUAVwA6DAAABQBbACwABAqBFQACDgAHCAAkxUEAVgIADgAHCAAkxUEAVgIAASwABRQHCBoACQDVHQA=.',Hu='Huntingnips:BAEBLAAECoEYAAIFAAgILiEYGgDNAgg5DAAABABaADsMAAAEAFQAOgwAAAQAYQA8DAAAAwA/ADIMAAADAE4APQwAAAMAXAA+DAAAAgBVAD8MAAABAFYABQAICC4hGBoAzQIIOQwAAAQAWgA7DAAABABUADoMAAAEAGEAPAwAAAMAPwAyDAAAAwBOAD0MAAADAFwAPgwAAAIAVQA/DAAAAQBWAAAA.',Hy='Hypersgr:BAEALAAFFAIIBAABLAAFFAcIGgAJANUdAA==.',Id='Idéfíx:BAECLAAFFIEGAAMFAAII1iBAIgClAAI5DAAAAwBbADoMAAADAEwABQACCOQcQCIApQACOQwAAAIAWwA6DAAAAgA4ABEAAgjvE6gbAIsAAjkMAAABABkAOgwAAAEATAAsAAQKgR8AAwUACAgiIhAWAOMCAAUACAgiIhAWAOMCABEABgjZH9kqAAwCAAAA.',Ik='Ikubrew:BAEALAAECgMIAwABLAAFFAYIEwAaANofAA==.Ikud:BAEALAAECgQIBAABLAAFFAYIEwAaANofAA==.Ikupres:BAECLAAFFIETAAIaAAYI2h81AQBDAgY5DAAABABjADsMAAADAEcAOgwAAAQATAA8DAAAAwBaADIMAAACAFcAPQwAAAMAQAAaAAYI2h81AQBDAgY5DAAABABjADsMAAADAEcAOgwAAAQATAA8DAAAAwBaADIMAAACAFcAPQwAAAMAQAAsAAQKgSUAAhoACAjrJOYAAF0DABoACAjrJOYAAF0DAAAA.',Jo='Johnbarnes:BAEBLAAECoEVAAMDAAYIBx9mGgCeAQY5DAAAAwBUADsMAAADAEkAOgwAAAMAVgA8DAAAAwA9ADIMAAADAF4APQwAAAYATQADAAUIyxxmGgCeAQU5DAAAAgBUADsMAAACAEgAOgwAAAMAVgA8DAAAAgAwAD0MAAAFAE0ACQAFCNkWXTwAVgEFOQwAAAEAEQA7DAAAAQBJADwMAAABAD0AMgwAAAMAXgA9DAAAAQAtAAAA.',Ka='Kantema:BAEALAAECgcICAABLAAFFAQIDAAbAL8iAA==.Kasvius:BAEBLAAECoEjAAIFAAcIghnlWgDbAQc5DAAABgBPADsMAAAGAFEAOgwAAAYAVQA8DAAABQA0ADIMAAAFACoAPQwAAAUAOAA+DAAAAgA7AAUABwiCGeVaANsBBzkMAAAGAE8AOwwAAAYAUQA6DAAABgBVADwMAAAFADQAMgwAAAUAKgA9DAAABQA4AD4MAAACADsAAAA=.Kayes:BAECLAAFFIEJAAMGAAMIBBnxGgD4AAM5DAAAAgBBADsMAAADADMAOgwAAAQASwAGAAMIqBjxGgD4AAM5DAAAAQA+ADsMAAABADMAOgwAAAQASwAHAAIIRBQdBACfAAI5DAAAAQBBADsMAAACACYALAAECoEpAAMGAAgIqSPEEgAFAwAGAAgIqSPEEgAFAwAHAAEIeBuFHAA+AAAAAA==.',Le='Leopshaman:BAEALAAECgEIAQABLAAECgYIBgABAAAAAA==.Lesserafim:BAEBLAAECoEVAAMYAAgIihjaHgDtAQg5DAAABQBSADsMAAADAFoAOgwAAAEAEwA8DAAAAwBFADIMAAADAF8APQwAAAQAWwA+DAAAAQAJAD8MAAABACoAGAAICBMS2h4A7QEIOQwAAAMAPwA7DAAAAgA3ADoMAAABABMAPAwAAAEAKAAyDAAAAQBJAD0MAAABAEEAPgwAAAEACQA/DAAAAQAqAAwABQikIdFLAOUBBTkMAAACAFIAOwwAAAEAWgA8DAAAAgBFADIMAAACAF8APQwAAAMAWwABLAAFFAYIGAAOALceAA==.',Li='Lishà:BAEALAAECgYIEAABLAAFFAIIBgAYACslAA==.',Lu='Luminasta:BAEALAADCggICAAAAA==.',['Lé']='Lépaladino:BAEALAAECgcIBwABLAAECggIIgAOAHcbAA==.',Ma='Maximusjy:BAECLAAFFIEJAAIcAAMIwCb8AABWAQM5DAAABABkADsMAAABAGEAOgwAAAQAZAAcAAMIwCb8AABWAQM5DAAABABkADsMAAABAGEAOgwAAAQAZAAsAAQKgSkAAhwACAjuJgUAAKcDABwACAjuJgUAAKcDAAAA.Maximuszeng:BAEALAAECgYIBgABLAAFFAMICQAcAMAmAA==.',Mi='Misfosster:BAECLAAFFIERAAIDAAUIZiY7AQBFAgU5DAAABABjADsMAAAEAGMAOgwAAAMAYgA8DAAAAwBfAD0MAAADAGMAAwAFCGYmOwEARQIFOQwAAAQAYwA7DAAABABjADoMAAADAGIAPAwAAAMAXwA9DAAAAwBjACwABAqBMgACAwAICOcmIQAAlQMAAwAICOcmIQAAlQMAAAA=.Mistoutfire:BAEALAADCgYICQABLAAECgYIFQADAAcfAA==.',Mu='Murçi:BAEALAAECgYIBwABLAAECgcIEgABAAAAAA==.',Ne='Neonswi:BAEALAADCggICQABLAAFFAMICgALAAQWAA==.Neonswift:BAECLAAFFIEKAAILAAMIBBbtEACVAAM5DAAABQA0ADsMAAABACoAOgwAAAQASgALAAMIBBbtEACVAAM5DAAABQA0ADsMAAABACoAOgwAAAQASgAsAAQKgSwAAgsACAjaHn8NALgCAAsACAjaHn8NALgCAAAA.',No='Nomorehappie:BAEALAAECggICAABLAAECggIEgABAAAAAA==.',Nx='Nxdruid:BAEALAAFFAIIBAABLAAFFAgIEAAdAMEdAA==.',Ny='Nyrimage:BAEALAADCgQIBAABLAAECgYIBgABAAAAAA==.',['Nè']='Nèonmonk:BAEALAAECgYIDgABLAAFFAMICgALAAQWAA==.',Oa='Oatlywarrior:BAEBLAAFFIELAAISAAYIpRKFBAAPAgY5DAAAAgA5ADsMAAACACAAOgwAAAIAUQA8DAAAAgAxADIMAAACACEAPQwAAAEAHwASAAYIpRKFBAAPAgY5DAAAAgA5ADsMAAACACAAOgwAAAIAUQA8DAAAAgAxADIMAAACACEAPQwAAAEAHwABLAAECggIFAARAMsmAA==.',Pa='Paidnfull:BAEALAADCgIIAgABLAAFFAYIFAAWALcdAA==.Pandalily:BAEBLAAECoEUAAIRAAgIXRMpMwDdAQg5DAAAAwAsADsMAAADAEoAOgwAAAMAWgA8DAAAAwA2ADIMAAADAEUAPQwAAAMAHwA+DAAAAQATAD8MAAABAAwAEQAICF0TKTMA3QEIOQwAAAMALAA7DAAAAwBKADoMAAADAFoAPAwAAAMANgAyDAAAAwBFAD0MAAADAB8APgwAAAEAEwA/DAAAAQAMAAEsAAUUBQgUAB0AYyMA.Pandyhunti:BAEALAAECgYIBgAAAA==.Pawjobs:BAEBLAAECoEWAAIEAAgIlhxmOABbAgg5DAAABABNADsMAAADAFYAOgwAAAMAUAA8DAAAAwBQADIMAAADAGAAPQwAAAMAUgA+DAAAAQAeAD8MAAACADIABAAICJYcZjgAWwIIOQwAAAQATQA7DAAAAwBWADoMAAADAFAAPAwAAAMAUAAyDAAAAwBgAD0MAAADAFIAPgwAAAEAHgA/DAAAAgAyAAAA.',Pe='Pedroobvious:BAEBLAAECoErAAMeAAgI4x5xCADWAgg5DAAABwBWADsMAAAHAFwAOgwAAAYAUwA8DAAABgBaADIMAAAGAFsAPQwAAAYARgA+DAAAAwA8AD8MAAACADkAHgAICOMecQgA1gIIOQwAAAYAVgA7DAAABgBcADoMAAAFAFMAPAwAAAUAWgAyDAAABQBbAD0MAAAFAEYAPgwAAAMAPAA/DAAAAgA5ABUABgiUEnGmAHoBBjkMAAABAB4AOwwAAAEALQA6DAAAAQA3ADwMAAABACcAMgwAAAEANQA9DAAAAQA9AAAA.',Ph='Phodrood:BAECLAAFFIEUAAIWAAYItx1aAQAxAgY5DAAABQBeADsMAAAEAFsAOgwAAAUAWgA8DAAAAgAbADIMAAABAEsAPQwAAAMATAAWAAYItx1aAQAxAgY5DAAABQBeADsMAAAEAFsAOgwAAAUAWgA8DAAAAgAbADIMAAABAEsAPQwAAAMATAAsAAQKgSIAAxYACAhjIhYLAOsCABYACAhjIhYLAOsCAB8AAQjcINeEAFsAAAAA.Phomage:BAECLAAFFIERAAIGAAUIix55CQDfAQU5DAAABQBiADsMAAAEAEQAOgwAAAUAVwA8DAAAAgAyAD0MAAABAFUABgAFCIseeQkA3wEFOQwAAAUAYgA7DAAABABEADoMAAAFAFcAPAwAAAIAMgA9DAAAAQBVACwABAqBGwACBgAICEAjAx4AyAIABgAICEAjAx4AyAIAASwABRQGCBQAFgC3HQA=.Phomonk:BAEBLAAECoEZAAMCAAgIDiJCBQALAwg5DAAABABSADsMAAAEAFMAOgwAAAMAYAA8DAAAAwBYADIMAAAFAGEAPQwAAAMAUwA+DAAAAgBOAD8MAAABAFYAAgAICA4iQgUACwMIOQwAAAMAUgA7DAAAAwBTADoMAAADAGAAPAwAAAMAWAAyDAAABABhAD0MAAADAFMAPgwAAAIATgA/DAAAAQBWABsAAwieG6oxAOYAAzkMAAABAE8AOwwAAAEAUwAyDAAAAQAwAAEsAAUUBggUABYAtx0A.Phoshaman:BAEALAAECggICgABLAAFFAYIFAAWALcdAA==.Phowarrior:BAEALAAECggIDQABLAAFFAYIFAAWALcdAA==.',Pl='Plingplang:BAECLAAFFIEPAAIKAAQIHRX/AAAhAQQ5DAAABQBFADsMAAAEAC0AOgwAAAUASAA8DAAAAQAcAAoABAgdFf8AACEBBDkMAAAFAEUAOwwAAAQALQA6DAAABQBIADwMAAABABwALAAECoE2AAIKAAgIHCE3AwDyAgAKAAgIHCE3AwDyAgAAAA==.',Pr='Protecka:BAEALAAECgYICAABLAAFFAUIBgAfANkKAA==.',Re='Returnunit:BAEBLAAECoEjAAIGAAgIpBbFQAAtAgg5DAAABgBLADsMAAAGAEkAOgwAAAYANgA8DAAABQA2ADIMAAAFAFEAPQwAAAQASAA+DAAAAgAKAD8MAAABACoABgAICKQWxUAALQIIOQwAAAYASwA7DAAABgBJADoMAAAGADYAPAwAAAUANgAyDAAABQBRAD0MAAAEAEgAPgwAAAIACgA/DAAAAQAqAAAA.',Ry='Ryaa:BAEBLAAFFIEFAAICAAQIHgdQBwAHAQQ7DAAAAQAVADoMAAABAA0APAwAAAIAIAA9DAAAAQAFAAIABAgeB1AHAAcBBDsMAAABABUAOgwAAAEADQA8DAAAAgAgAD0MAAABAAUAASwABRQHCBIACwAxDwA=.Ryii:BAECLAAFFIESAAILAAcIMQ8EAgAOAgc5DAAABABLADsMAAADAEoAOgwAAAQASQA8DAAAAgAQADIMAAADAA0APQwAAAEACQA+DAAAAQAJAAsABwgxDwQCAA4CBzkMAAAEAEsAOwwAAAMASgA6DAAABABJADwMAAACABAAMgwAAAMADQA9DAAAAQAJAD4MAAABAAkALAAECoEdAAILAAgI2SIOFgBZAgALAAgI2SIOFgBZAgAAAA==.Ryrn:BAEALAAECgYIBgABLAAFFAcIEgALADEPAA==.',Sa='Sar:BAECLAAFFIEXAAIFAAYIwiIzAQBcAgY5DAAABQBhADsMAAAEAD0AOgwAAAQAYAA8DAAABABbADIMAAACAFkAPQwAAAQAYQAFAAYIwiIzAQBcAgY5DAAABQBhADsMAAAEAD0AOgwAAAQAYAA8DAAABABbADIMAAACAFkAPQwAAAQAYQAsAAQKgSkAAwUACAi4JTYMACMDAAUACAi4JTYMACMDABEABQiWGJpVAEkBAAAA.',Sh='Shamenkink:BAEBLAAECoEUAAIgAAgIZhGXVQC6AQg5DAAABAA1ADsMAAAEACsAOgwAAAIANgA8DAAAAgAPADIMAAADAEsAPQwAAAMAVgA+DAAAAQAJAD8MAAABABIAIAAICGYRl1UAugEIOQwAAAQANQA7DAAABAArADoMAAACADYAPAwAAAIADwAyDAAAAwBLAD0MAAADAFYAPgwAAAEACQA/DAAAAQASAAEsAAQKCAgjAAYApBYA.',Sk='Skoria:BAEALAAECgYICwABLAAECgYIDAABAAAAAA==.',St='Steelsdk:BAEALAAECggIBwABLAAECgYIBAABAAAAAA==.Steelshunter:BAEBLAAECoEYAAIFAAgIkxZWUgDxAQg5DAAAAwBQADsMAAADACwAOgwAAAMALQA8DAAAAwBQADIMAAADAFcAPQwAAAMAPQA+DAAAAwAzAD8MAAADAAsABQAICJMWVlIA8QEIOQwAAAMAUAA7DAAAAwAsADoMAAADAC0APAwAAAMAUAAyDAAAAwBXAD0MAAADAD0APgwAAAMAMwA/DAAAAwALAAEsAAQKBggEAAEAAAAA.Steelspally:BAEALAAECgYIBAAAAA==.',Su='Sulxan:BAEALAAECgYIDAAAAA==.Sunkala:BAEALAADCggIEwABLAAECgYIFQADAAcfAA==.',Sy='Sythene:BAEALAADCggICAABLAAFFAUIFAAdAGMjAA==.',Ta='Tankydh:BAEALAADCgUIBQABLAAECggIIwAGAKQWAA==.',Th='Thrapalina:BAEALAAECggIEgAAAA==.Thraps:BAEALAAECggICAABLAAECggIEgABAAAAAA==.',Ti='Tinyboxes:BAECLAAFFIENAAMdAAUIEQueCgBoAQU5DAAABQA5ADsMAAACABkAOgwAAAQAOAA8DAAAAQABAD0MAAABAAEAHQAFCBELngoAaAEFOQwAAAQAOQA7DAAAAgAZADoMAAADADgAPAwAAAEAAQA9DAAAAQABACAAAgiIBKxIAGMAAjkMAAABAAkAOgwAAAEADQAsAAQKgTAAAx0ACAijHdsaAKwCAB0ACAijHdsaAKwCACAAAQiIJGvzAGkAAAAA.Tinymeta:BAEALAADCgcIBwABLAAFFAUIDQAdABELAA==.Tinymoonboot:BAEALAADCgQIBAABLAAFFAUIDQAdABELAA==.Tinynoodles:BAEALAAECgYIDAABLAAFFAUIDQAdABELAA==.',To='Toizimi:BAEALAAECggICwABLAAECggIIwAGAKQWAA==.Toxhunter:BAEALAAECgcIDgAAAA==.',Tr='Trekuplanni:BAEALAADCgQIBAABLAAECgYIBgABAAAAAA==.Troopcsd:BAEBLAAECoExAAMGAAgIfCWiBABhAwg5DAAABgBiADsMAAAGAGAAOgwAAAYAYwA8DAAABgBfADIMAAAGAFUAPQwAAAYAYQA+DAAABgBgAD8MAAAHAGEABgAICHwlogQAYQMIOQwAAAUAYgA7DAAABQBgADoMAAAFAGMAPAwAAAUAXwAyDAAABQBVAD0MAAAEAGEAPgwAAAUAYAA/DAAABwBhAAgABwiiEW03AHQBBzkMAAABAEwAOwwAAAEAFAA6DAAAAQAlADwMAAABAEAAMgwAAAEAIwA9DAAAAgBDAD4MAAABAA4AAAA=.Troopdh:BAEALAADCgEIAQABLAAECggIMQAGAHwlAA==.',Ui='Uithest:BAEALAAECgYIDQABLAAFFAIIBgANAAIZAA==.',Un='Underwonderr:BAECLAAFFIEYAAIGAAYIcyNDAQCMAgY5DAAABQBiADsMAAADAGIAOgwAAAYAYAA8DAAABABjADIMAAACAEYAPQwAAAQAUQAGAAYIcyNDAQCMAgY5DAAABQBiADsMAAADAGIAOgwAAAYAYAA8DAAABABjADIMAAACAEYAPQwAAAQAUQAsAAQKgXIAAgYACAjTJqYAAJADAAYACAjTJqYAAJADAAAA.',Ur='Urunïi:BAEBLAAECoEjAAMNAAcI7BssFABQAgc5DAAABwBfADsMAAAIAEoAOgwAAAcATwA8DAAABQBAADIMAAADADQAPQwAAAMAWgA+DAAAAgAsAA0ABwjsGywUAFACBzkMAAAGAF8AOwwAAAcASgA6DAAABgBPADwMAAAFAEAAMgwAAAMANAA9DAAAAwBaAD4MAAACACwAAgADCLgMazoAbAADOQwAAAEAHAA7DAAAAQAjADoMAAABACEAAAA=.',Vi='Virrek:BAEBLAAECoEhAAMDAAgIuB79BQDYAgg5DAAABgBRADsMAAAEAF0AOgwAAAQASwA8DAAABgBTADIMAAAFAFoAPQwAAAQATwA+DAAAAwBSAD8MAAABACsAAwAICLAe/QUA2AIIOQwAAAIAUAA7DAAAAQBdADoMAAACAEsAPAwAAAYAUwAyDAAAAwBaAD0MAAACAE8APgwAAAMAUgA/DAAAAQArAAkABQjAFb0/AEIBBTkMAAAEAFEAOwwAAAMAQQA6DAAAAgA5ADIMAAACAC0APQwAAAIAHAAAAA==.Virrell:BAEALAAECgYICQABLAAECggIIQADALgeAA==.',['Vë']='Vënømbloom:BAECLAAFFIEaAAMJAAcI1R12AABLAgc5DAAABQBeADsMAAAEAGMAOgwAAAUAXQA8DAAAAwBHADIMAAAEAFEAPQwAAAQAMgA+DAAAAQAqAAMABwjfGqMAAJACBzkMAAACAFQAOwwAAAEAYAA6DAAAAwBZADwMAAACACQAMgwAAAEAUQA9DAAAAQAyAD4MAAABACoACQAGCIcedgAASwIGOQwAAAMAXgA7DAAAAwBjADoMAAACAF0APAwAAAEARwAyDAAAAwBIAD0MAAADACQALAAECoEqAAMJAAgIHyYJAgBaAwAJAAgI1CUJAgBaAwADAAcIqiPyBgDAAgAAAA==.',['Vî']='Vîfon:BAEALAAECgYICQABLAAECgcIHQARAPMiAA==.',Wa='Waidur:BAECLAAFFIENAAMgAAUIcxUBCwAqAQU5DAAABAA7ADsMAAADACsAOgwAAAQASgA8DAAAAQBIAD0MAAABABgAIAAECLMTAQsAKgEEOQwAAAQAOwA7DAAAAwArADoMAAAEAEoAPQwAAAEAGAAdAAEIOwGILgBCAAE8DAAAAQADACwABAqBLQADIAAICOcljwEAYgMAIAAICOcljwEAYgMAHQAHCDUZbjkA/QEAASwABRQHCBAAIAAnCQA=.',Wh='Whupwhup:BAEALAAECgcIBwAAAA==.',Wi='Windslasher:BAECLAAFFIEHAAIJAAIIshQ8EQCpAAI5DAAABAAvADoMAAADADoACQACCLIUPBEAqQACOQwAAAQALwA6DAAAAwA6ACwABAqBKwACCQAICPcgxAYADAMACQAICPcgxAYADAMAAAA=.',['Xâ']='Xârk:BAEALAAFFAEIAQAAAA==.',Ye='Yealuneve:BAECLAAFFIEOAAIWAAUIERG3BQB7AQU5DAAAAwAqADsMAAAEADoAOgwAAAMAVQA8DAAAAgAQAD0MAAACAA8AFgAFCBERtwUAewEFOQwAAAMAKgA7DAAABAA6ADoMAAADAFUAPAwAAAIAEAA9DAAAAgAPACwABAqBIAACFgAICIcj4AMAQAMAFgAICIcj4AMAQAMAAAA=.',Zt='Ztil:BAECLAAFFIEKAAIFAAMI5iCDEAAKAQM5DAAABABfADsMAAACAEYAOgwAAAQAVgAFAAMI5iCDEAAKAQM5DAAABABfADsMAAACAEYAOgwAAAQAVgAsAAQKgSgAAgUACAiEJY8KAC4DAAUACAiEJY8KAC4DAAAA.',Zy='Zydruid:BAEALAAFFAIIAgABLAAFFAYIHAABAAAAAA==.Zyevoker:BAEALAADCgEIAQABLAAFFAYIHAABAAAAAA==.Zyknight:BAEALAAFFAIIAgABLAAFFAYIHAABAAAAAA==.Zymage:BAEALAAECgMIAwABLAAFFAYIHAABAAAAAA==.Zythene:BAECLAAFFIEUAAIdAAUIYyMGBAATAgU5DAAABgBjADsMAAAFAGAAOgwAAAYAYAA8DAAAAgBJAD0MAAABAFYAHQAFCGMjBgQAEwIFOQwAAAYAYwA7DAAABQBgADoMAAAGAGAAPAwAAAIASQA9DAAAAQBWACwABAqBLAACHQAICBImrwIAeQMAHQAICBImrwIAeQMAAAA=.Zywarrior:BAEALAAFFAIIAgABLAAFFAYIHAABAAAAAA==.',['År']='Årk:BAEBLAAECoEmAAIUAAcINiODEgDLAgc5DAAABgBhADsMAAAGAF8AOgwAAAYAYQA8DAAABgBKADIMAAAGAEwAPQwAAAUAYQA+DAAAAwBbABQABwg2I4MSAMsCBzkMAAAGAGEAOwwAAAYAXwA6DAAABgBhADwMAAAGAEoAMgwAAAYATAA9DAAABQBhAD4MAAADAFsAASwABRQBCAEAAQAAAAA=.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end