local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Unknown-Unknown','Paladin-Retribution','Druid-Feral','Druid-Balance','Hunter-Marksmanship','Hunter-Survival','Hunter-BeastMastery','Shaman-Restoration','Mage-Arcane','Mage-Frost','DemonHunter-Havoc','Shaman-Elemental','Warrior-Arms','Warrior-Fury','Monk-Mistweaver','Monk-Windwalker','DeathKnight-Frost','DeathKnight-Blood','DemonHunter-Vengeance','Warlock-Demonology','Mage-Fire','Druid-Restoration','Warlock-Destruction','Druid-Guardian','Warrior-Protection','Paladin-Holy','Warlock-Affliction','Rogue-Assassination','Priest-Shadow','Priest-Holy','Monk-Brewmaster','Priest-Discipline','Evoker-Devastation','Paladin-Protection','DeathKnight-Unholy','Evoker-Augmentation','Evoker-Preservation',}; local provider = {region='EU',realm='Ambossar',name='EU',type='weekly',zone=44,date='2025-09-24',data={Ab='Abgenagter:BAAALAADCggIDQAAAA==.',Ad='Adios:BAAALAADCggICAAAAA==.',Ae='Aeryius:BAAALAADCggICAAAAA==.',Af='Afkbank:BAAALAADCgYIBgAAAA==.',Al='Alarich:BAAALAAECgQICgAAAA==.Albundy:BAAALAAECgQIEAAAAA==.Aldurian:BAAALAAECggICAAAAA==.Altiar:BAAALAADCggICAABLAAECggIDwABAAAAAA==.Alystaire:BAAALAAECgYIDQAAAA==.',Ar='Aranuk:BAAALAADCgYIBgAAAA==.Areli:BAAALAADCggICwAAAA==.Ariamus:BAABLAAECoEkAAICAAgI4haSTgAoAgACAAgI4haSTgAoAgAAAA==.Ariseá:BAAALAADCgcIBwABLAAECggIGQADAC8OAA==.Arisá:BAABLAAECoEZAAMDAAgILw6PGAC4AQADAAgILw6PGAC4AQAEAAMIewSzhwBIAAAAAA==.Arkarius:BAAALAADCgUIBQAAAA==.Arki:BAABLAAECoEfAAQFAAgI0SHiCQANAwAFAAgIfiHiCQANAwAGAAcIKBwrBgBJAgAHAAEIbBwCFwEzAAAAAA==.Arkinow:BAAALAADCggIDAABLAAECggIHwAFANEhAA==.Aryn:BAABLAAECoEvAAIIAAgIDyJUDADuAgAIAAgIDyJUDADuAgAAAA==.',As='Ashesia:BAAALAADCgYIBgAAAA==.Asiya:BAAALAADCgUIBQAAAA==.Asrima:BAAALAAECgYIBwABLAAECggIGQADAC8OAA==.Asunrah:BAAALAAECgMIBQABLAAECgcIGgAEAAQTAA==.',At='Athandriel:BAABLAAECoEYAAMJAAYIaQ0PhwBaAQAJAAYIQg0PhwBaAQAKAAQIVAoeWADVAAAAAA==.Attacke:BAAALAAECgMIBAAAAA==.',Au='Audery:BAAALAADCgIIAgABLAAECggIGQADAC8OAA==.Auffeglogge:BAAALAADCggICAAAAA==.Aurion:BAAALAADCgIIAgABLAAECgEIAQABAAAAAA==.',Av='Averis:BAAALAADCgIIAQABLAAECggIGQADAC8OAA==.',Ay='Ay:BAAALAADCggICwAAAA==.',Ba='Backbonê:BAAALAADCggICAAAAA==.Baleran:BAABLAAECoEeAAILAAgIpBG5dQCtAQALAAgIpBG5dQCtAQAAAA==.Banjí:BAAALAADCgcIBwAAAA==.',Be='Beashiny:BAAALAAECgQIBgAAAA==.Beastly:BAAALAADCgYIDAAAAA==.Belakora:BAAALAAECgMIBQAAAA==.Benril:BAAALAADCggIDwAAAA==.Berrenike:BAABLAAECoEZAAILAAcI2xapWwDpAQALAAcI2xapWwDpAQAAAA==.',Bi='Bigbluedress:BAAALAAECgMIAwAAAA==.Biohrasha:BAABLAAFFIEFAAIHAAUImA11CgBeAQAHAAUImA11CgBeAQAAAA==.Bishoop:BAAALAAECgYICgAAAA==.',Bl='Blattschuss:BAAALAADCgQIBAAAAA==.Blina:BAAALAAECgYIBgABLAAECggIJgAIAIkkAA==.Blitzipeng:BAAALAAECgIIAwAAAA==.Blixix:BAABLAAECoE3AAMIAAgIeB3+GgCOAgAIAAgIeB3+GgCOAgAMAAEIjQLxtwAWAAAAAA==.Bloodhunt:BAAALAAECgIIAgABLAAECgcIDAABAAAAAA==.Bloodyroots:BAABLAAECoEWAAMNAAYIhRWbFQBhAQANAAUIahabFQBhAQAOAAEIDRE/0QA2AAAAAA==.Bluecollar:BAAALAADCgcIDgAAAA==.',Bo='Boazn:BAACLAAFFIEVAAIPAAUINCOmAQAKAgAPAAUINCOmAQAKAgAsAAQKgTQAAw8ACAglJNACADMDAA8ACAglJNACADMDABAAAQj8F+xUAEkAAAAA.Bobbý:BAAALAAECgIIAgAAAA==.Bogenbetti:BAACLAAFFIEGAAIFAAIIPR3mEwCrAAAFAAIIPR3mEwCrAAAsAAQKgS8AAgUACAhUJCoGADIDAAUACAhUJCoGADIDAAAA.Bolanor:BAAALAADCgMIAwAAAA==.Bolgour:BAAALAADCggIGQAAAA==.Bollwerko:BAAALAAECgEIAQAAAA==.Bowzer:BAACLAAFFIEIAAIOAAIIsxc5IACiAAAOAAIIsxc5IACiAAAsAAQKgSIAAg4ACAjeHkkaAMoCAA4ACAjeHkkaAMoCAAAA.',Br='Brainstrain:BAAALAADCgYIBgAAAA==.Brewzlee:BAAALAADCggICwABLAAECggIHwAFANEhAA==.Brusti:BAAALAADCgMIAwAAAA==.',Bu='Bugrash:BAACLAAFFIEJAAIRAAMIbBwzGADxAAARAAMIbBwzGADxAAAsAAQKgS0AAhEACAgeJHkLADkDABEACAgeJHkLADkDAAAA.Bull:BAAALAAECgMIBAABLAAECgQIEAABAAAAAA==.Burtrakar:BAAALAADCgYIBgAAAA==.',['Bä']='Bärböl:BAAALAADCgUIBQAAAA==.',Ca='Caesarius:BAAALAAECgcICwAAAQ==.Candyflip:BAAALAAECgQIBQABLAAECgcIDgABAAAAAA==.Candytank:BAAALAADCgcIBwAAAA==.Carag:BAAALAADCggIDwABLAAECgcIDAABAAAAAA==.Carrion:BAAALAAECggIAQAAAA==.Carølin:BAAALAAECggICAABLAAECggIIQAQADQeAA==.Cassiopeya:BAAALAAECgMIBAAAAA==.',Ch='Chia:BAABLAAFFIEHAAIPAAMIswopCQDPAAAPAAMIswopCQDPAAAAAA==.Chrischop:BAABLAAECoEmAAMIAAgI9RssJwBSAgAIAAgI9RssJwBSAgAMAAcI8RWwPwDbAQAAAA==.',Ci='Ciddia:BAAALAAECgEIAQAAAA==.',Cl='Clementine:BAAALAADCgMIBQAAAA==.Clêo:BAAALAAECgYICQAAAA==.',Co='Comealotinu:BAABLAAECoEYAAICAAYIRRjyfgC7AQACAAYIRRjyfgC7AQABLAAFFAIIBgAHAHQeAA==.Convallaria:BAAALAAECgcIEgAAAA==.Copd:BAAALAAECgYIBgAAAA==.Cowbust:BAACLAAFFIEVAAIJAAUI/iI2BgACAgAJAAUI/iI2BgACAgAsAAQKgTAAAgkACAicJkwBAIUDAAkACAicJkwBAIUDAAAA.Cowded:BAACLAAFFIEFAAIRAAII4iHRIwC8AAARAAII4iHRIwC8AAAsAAQKgSMAAxEABwgxJUQtAJcCABEABwhjJEQtAJcCABIABwjCIf4JAJECAAEsAAUUBQgVAAkA/iIA.Cowsneak:BAAALAAECgYICAABLAAFFAUIFQAJAP4iAA==.',Cu='Cubidan:BAACLAAFFIESAAITAAQIlSRCAQCUAQATAAQIlSRCAQCUAQAsAAQKgTUAAhMACAiXJtYAAHgDABMACAiXJtYAAHgDAAAA.Cubrior:BAAALAAFFAIIAgABLAAFFAQIEgATAJUkAA==.',Cy='Cylaris:BAAALAAECgcIEQAAAA==.Cyril:BAAALAADCggICAABLAAECggIJQAJAKYaAA==.Cysî:BAAALAAECgMICAAAAA==.',Da='Dahnyr:BAAALAAECggIDwAAAA==.Dalin:BAAALAAECgYICQAAAA==.Danielboone:BAABLAAECoEcAAIHAAcIeAtMlABVAQAHAAcIeAtMlABVAQAAAA==.Darkbiscuit:BAEBLAAECoEvAAISAAgI7CARBgDtAgASAAgI7CARBgDtAgAAAA==.',De='Deadlyne:BAAALAADCgYICQAAAA==.Deadoxygen:BAABLAAECoEZAAIRAAgItR0KJgC2AgARAAgItR0KJgC2AgAAAA==.Deamonheart:BAABLAAECoEcAAIUAAYI9RlgIwDQAQAUAAYI9RlgIwDQAQAAAA==.Deathreaperr:BAAALAADCgMIAwAAAA==.Decido:BAAALAAECggIEgAAAA==.Dekandra:BAAALAAECgEIAQAAAA==.Demontar:BAABLAAECoEcAAIKAAgIPBlwGgAiAgAKAAgIPBlwGgAiAgAAAA==.Denariss:BAAALAADCgMIAwAAAA==.Derhelle:BAAALAAECgYIDQAAAA==.Derschamane:BAABLAAECoEdAAIIAAcIgRWbWACtAQAIAAcIgRWbWACtAQAAAA==.',Di='Dirinal:BAAALAADCggIGQAAAA==.',Dk='Dkfemale:BAAALAAECgcIBwAAAA==.',Dm='Dmage:BAAALAAECgIIAgABLAAFFAcIFgAJAOciAA==.',Do='Dotdotgoose:BAAALAADCgYIBgAAAA==.',Dr='Drale:BAACLAAFFIERAAMHAAUI3BA2CwBMAQAHAAUI3BA2CwBMAQAFAAIIZgmsJQBwAAAsAAQKgS4AAwcACAilIPwYAM8CAAcACAilIPwYAM8CAAUACAgvDO9aADQBAAAA.Dranava:BAAALAAECgMIBQAAAA==.Draven:BAACLAAFFIEWAAMJAAcI5yJrAQB/AgAJAAYInyJrAQB/AgAVAAEIlyQXBgBkAAAsAAQKgRsAAgkACAguI1AiALACAAkACAguI1AiALACAAAA.Dravin:BAAALAAFFAIIAgABLAAFFAcIFgAJAOciAA==.Drvn:BAAALAAECgYIEQABLAAFFAcIFgAJAOciAA==.',Du='Duergar:BAAALAADCggICAAAAA==.Duesentrieb:BAABLAAECoEWAAIKAAYInR4eGwAcAgAKAAYInR4eGwAcAgAAAA==.Dulles:BAAALAAECggICAAAAA==.Duncanidaho:BAABLAAECoEYAAIWAAcIWRzXIgA1AgAWAAcIWRzXIgA1AgAAAA==.',Dw='Dwalîn:BAABLAAECoEdAAICAAgItw80cwDTAQACAAgItw80cwDTAQAAAA==.',['Dá']='Dárkhuntér:BAABLAAECoEkAAIHAAgIBRjXUgDoAQAHAAgIBRjXUgDoAQAAAA==.',['Dä']='Dämone:BAAALAADCgIIAgAAAA==.Dämonenhenry:BAAALAADCggICAABLAAECggIHQACAJMbAA==.',['Dò']='Dòc:BAAALAAECgMIBwAAAA==.',Ea='Easer:BAAALAAECgYIEgAAAA==.Eax:BAAALAADCggICAAAAA==.',Ed='Ediurdso:BAAALAAECgMIBQAAAA==.',Eg='Egelsamen:BAAALAAECggIDAAAAA==.',El='Elandragon:BAAALAAECgYICQAAAA==.Eldorinos:BAAALAADCggIDQAAAA==.Elkabone:BAAALAADCggIJgAAAA==.Eludril:BAAALAADCggIDwAAAA==.Eluenak:BAAALAAECgIIAgAAAA==.',Er='Erle:BAACLAAFFIETAAIEAAUIPBwjBQCmAQAEAAUIPBwjBQCmAQAsAAQKgTYAAwQACAiFJm4BAIADAAQACAiFJm4BAIADAAMAAgjOF4E1AIQAAAAA.Erletwo:BAAALAADCggICAABLAAFFAUIEwAEADwcAA==.',Et='Etto:BAAALAADCgEIAQAAAA==.',Ex='Extremeglue:BAAALAADCgIIAgAAAA==.Exudoss:BAABLAAECoElAAIDAAgInRV/EQASAgADAAgInRV/EQASAgAAAA==.Exùs:BAAALAAECgYIDgAAAA==.',Fa='Fabielle:BAAALAAECgYIEQAAAA==.Faddy:BAAALAADCgcIAwAAAA==.Fakepriest:BAAALAAECgIIAgAAAA==.Fanila:BAAALAAECgEIAQAAAA==.Faves:BAAALAAECgYIBwAAAA==.Faxies:BAAALAAECgUIBwAAAA==.',Fe='Fesylie:BAAALAAECgYIEQABLAAECggIGQADAC8OAA==.Fetteelfe:BAAALAADCgYIBgAAAA==.',Fi='Filipendula:BAAALAADCggICAABLAAECggILwAXAFoKAA==.Finkelstein:BAAALAAECgIIAgAAAA==.Fiña:BAAALAADCgcIBwAAAA==.',Fl='Flagdru:BAAALAADCgUIBQAAAA==.Flauschsen:BAAALAAECgcIDgAAAA==.Flocko:BAAALAAECgQIDQAAAA==.Flodo:BAAALAAECgYICwAAAA==.',Fo='Foxydudu:BAABLAAECoEVAAIYAAcIsRE6EQCFAQAYAAcIsRE6EQCFAQAAAA==.Foxyhunt:BAAALAAECgEIAQAAAA==.Foxylove:BAAALAADCggICAAAAA==.',Fr='Frosttitude:BAABLAAECoEVAAMKAAgIehfASwAWAQAJAAgIDRS1hgBaAQAKAAYI0BDASwAWAQAAAA==.Frozenshadow:BAABLAAECoEhAAIRAAgIMiKLGAD0AgARAAgIMiKLGAD0AgAAAA==.',Fu='Furrygirl:BAAALAAECgYIBgAAAA==.Futoeki:BAAALAAECgMIBwAAAA==.',['Fâ']='Fâlk:BAAALAADCggICAAAAA==.',['Fî']='Fîzzîe:BAACLAAFFIEPAAIRAAUIUhpiDgBKAQARAAUIUhpiDgBKAQAsAAQKgS0AAhEACAhyImUWAP8CABEACAhyImUWAP8CAAAA.',Ga='Gabaria:BAAALAAECgEIAQAAAA==.Galadhon:BAABLAAECoEXAAIEAAYIcQy/VAArAQAEAAYIcQy/VAArAQAAAA==.Gambler:BAAALAAECggIDwAAAA==.',Ge='Geràlt:BAAALAAECgEIAQABLAAECgcIGwAZABQaAA==.',Gi='Giemlie:BAAALAAECgIIAgAAAA==.Gigachad:BAAALAAFFAIIBAAAAA==.Gilbert:BAACLAAFFIEHAAMJAAMIsyA1FgAQAQAJAAMIsyA1FgAQAQAVAAEI0RXLCQBJAAAsAAQKgRsABAoACAhnJZENAKkCAAoABwiLJJENAKkCAAkACAjXJBIlAKMCABUAAQiAHTAbAEIAAAAA.',Gl='Gladiator:BAABLAAECoEgAAIOAAYIRCLdMQA/AgAOAAYIRCLdMQA/AgABLAAFFAQICwAOACQWAA==.',Gn='Gnichneda:BAABLAAECoEVAAIIAAYIbBNJfgBMAQAIAAYIbBNJfgBMAQAAAA==.',Go='Gobihunt:BAABLAAECoEoAAIHAAgISCCtHwCpAgAHAAgISCCtHwCpAgAAAA==.Gobiwarr:BAAALAAECgYIEgAAAA==.Goff:BAAALAAECgQIBwABLAAECggICAABAAAAAA==.Gojo:BAAALAAECgYICQABLAAECggIJAAHAAUYAA==.Goodi:BAABLAAECoEwAAIZAAgIgBW+KQC5AQAZAAgIgBW+KQC5AQAAAA==.Goodnìght:BAAALAADCgMIAwAAAA==.',Gr='Grambarias:BAAALAAECgMIAwABLAAECggIGwAaAAkTAA==.Granaria:BAACLAAFFIEMAAMXAAMIDxHEGwDiAAAXAAMIHg7EGwDiAAAbAAII/BXJAgCfAAAsAAQKgTIABBsACAiZJHgBADADABsACAgrI3gBADADABcACAhmHxUaAM8CABQAAQi1Cq+LAC8AAAAA.Grimmbelbart:BAAALAADCgUIBQAAAA==.Grimz:BAACLAAFFIEGAAIcAAII1BzQDgCyAAAcAAII1BzQDgCyAAAsAAQKgSIAAhwACAgHIP4JAN4CABwACAgHIP4JAN4CAAAA.Grindela:BAACLAAFFIEVAAMdAAUIliHJBwCDAQAdAAQIgSPJBwCDAQAeAAQIDhUKCwAoAQAsAAQKgTYAAx0ACAgjJXIDAGIDAB0ACAgjJXIDAGIDAB4AAQjqGMCdAEsAAAAA.Grisimdor:BAAALAAECgYIDAAAAA==.Grufty:BAAALAADCggIDgAAAA==.Grumthor:BAABLAAECoEUAAIRAAcIkwgZxwBJAQARAAcIkwgZxwBJAQAAAA==.',Gu='Guldån:BAAALAAECggICAAAAA==.Gulrodan:BAAALAADCggICAAAAA==.Gustl:BAAALAADCggICAAAAA==.',Ha='Habidutl:BAAALAAECgYIDQAAAA==.Hakkun:BAAALAADCgcIBwAAAA==.Hammading:BAAALAAECgcIDAAAAA==.Hammerfalle:BAAALAADCggIBAAAAA==.Hammerheil:BAAALAADCgcIBwAAAA==.Hammerjaga:BAAALAADCgcIDwAAAA==.Hammerlucife:BAAALAADCgQIBAAAAA==.Hammershadow:BAAALAADCgUIBAAAAA==.Hammertot:BAAALAADCgYIBgAAAA==.Hannamontana:BAAALAADCgMIAwABLAAECggIHwAFANEhAA==.Harmléss:BAAALAAECgQIEAAAAA==.Havarie:BAABLAAECoEhAAIIAAgIGBpiKQBJAgAIAAgIGBpiKQBJAgAAAA==.',He='Heilaggro:BAAALAAECgMIAwAAAA==.Hellkitty:BAAALAAECgEIAQAAAA==.Hephaisto:BAABLAAECoEcAAMUAAYIJhNZMgCDAQAUAAYI1RJZMgCDAQAXAAYIXg1GgQBEAQAAAA==.Heptâ:BAABLAAECoEgAAMIAAgI8BX0SwDRAQAIAAgI8BX0SwDRAQAMAAYI0g19aABLAQAAAA==.Herania:BAAALAADCgEIAQAAAA==.Hexerhenry:BAAALAADCggICAABLAAECggIHQACAJMbAA==.Hexîna:BAAALAADCggICAAAAA==.',Hi='Hiina:BAAALAADCgMIBAAAAA==.Hildá:BAABLAAECoEVAAMKAAYI5RQqMwCFAQAKAAYI5RQqMwCFAQAJAAYI1gbhnAAZAQAAAA==.',Hu='Hunterguntz:BAABLAAECoEaAAIFAAYIcA85YwAYAQAFAAYIcA85YwAYAQAAAA==.Huntschi:BAABLAAECoEdAAIHAAcIPSFGIQCgAgAHAAcIPSFGIQCgAgABLAAECgcIBwABAAAAAA==.',['Hé']='Héxmi:BAAALAAECgYIBgAAAA==.',Id='Idrael:BAABLAAECoElAAIJAAgIphpxMABtAgAJAAgIphpxMABtAgAAAA==.',In='Infinichi:BAABLAAECoEhAAMQAAgINB4xDQCnAgAQAAgINB4xDQCnAgAfAAII2BNQOAB3AAAAAA==.Infiniti:BAAALAADCgYIBgAAAA==.',Ir='Ironhand:BAAALAADCggIDwAAAA==.',Is='Iscilia:BAAALAAECggICgAAAA==.',It='Itspriestora:BAAALAADCggIDgAAAA==.',Iv='Ivaine:BAACLAAFFIEIAAIeAAMIMAJ7GwCiAAAeAAMIMAJ7GwCiAAAsAAQKgTAAAh4ACAhDEp42AN8BAB4ACAhDEp42AN8BAAAA.',['Iø']='Iø:BAAALAADCggICAAAAA==.',Ja='Jackguny:BAAALAAECgYIDAAAAA==.Jairo:BAAALAADCggICgAAAA==.Jaladriel:BAAALAADCgYIBgAAAA==.Januszz:BAAALAAECgEIAQAAAA==.Jaro:BAAALAADCgMIAwAAAA==.Jaron:BAAALAADCgEIAQAAAA==.',Ji='Jidran:BAABLAAECoEtAAILAAgILhvWNABjAgALAAgILhvWNABjAgAAAA==.Jigu:BAAALAADCggICAAAAA==.',Jo='Jobcenter:BAAALAAECgcIDQABLAAFFAMIBwARAKQYAA==.Johnsnow:BAAALAAECgMIAwAAAA==.',Ju='Julì:BAAALAAECgMIAwAAAA==.',['Já']='Járwen:BAABLAAECoEVAAIVAAYIvRMICQCVAQAVAAYIvRMICQCVAQAAAA==.',['Jê']='Jêtîxd:BAABLAAECoEcAAIIAAgIHhmxNQAaAgAIAAgIHhmxNQAaAgAAAA==.',['Jó']='Jóons:BAAALAADCgEIAQAAAA==.',Ka='Kaitosan:BAAALAADCgQIBAABLAAECggIFQAKAHoXAA==.Kartman:BAAALAADCgQIBAAAAA==.Katon:BAAALAAECggICQABLAAFFAcIFQAdAD0bAA==.',Ke='Kevinsan:BAAALAADCggIDwAAAA==.',Ki='Kiaron:BAAALAADCggICAAAAA==.Kidomaru:BAAALAADCgYICgAAAA==.Killarer:BAAALAADCgYIBgAAAA==.Killermix:BAAALAADCgcICAAAAA==.Killmaschien:BAAALAADCgUIBQAAAA==.Killroar:BAAALAAECgMIBQAAAA==.Kitahna:BAAALAAECggIDgAAAA==.',Kn='Knarfie:BAAALAAECgUIBgAAAA==.Knockalex:BAAALAAECggICAAAAA==.Knotzen:BAAALAADCgUIBQAAAA==.Knôchenjônny:BAAALAAECggICAAAAA==.',Kr='Kriegerhenry:BAAALAADCggICAABLAAECggIHQACAJMbAA==.Kristalli:BAAALAAECgIIAgAAAA==.Kristallina:BAAALAADCggIFQAAAA==.Kroft:BAAALAAECgYIEgAAAA==.Krònós:BAAALAADCggICAAAAA==.',Ku='Kuri:BAAALAAECggICAAAAA==.',Kv='Kvóthe:BAAALAADCggICQAAAA==.',Ky='Kylmää:BAABLAAECoEdAAIYAAcIpBwOCAA/AgAYAAcIpBwOCAA/AgAAAA==.',['Kå']='Kågen:BAAALAADCggIHgAAAA==.',La='Laloona:BAABLAAECoEaAAIEAAcIBBP0OQChAQAEAAcIBBP0OQChAQAAAA==.Lardo:BAAALAADCggICwAAAA==.Lardonian:BAAALAAECgYIDAAAAA==.Larkra:BAAALAAECgUICAAAAA==.Lary:BAAALAAECgQIBQAAAA==.Latexhunter:BAAALAAECggICAAAAA==.Lausepelz:BAABLAAECoEWAAIWAAYI7Q8+XABBAQAWAAYI7Q8+XABBAQAAAA==.',Le='Leddi:BAAALAADCggICAAAAA==.Legionz:BAAALAAECgQICAABLAAECggIHwAFANEhAA==.Lenie:BAAALAADCgYIBgAAAA==.Leoniê:BAABLAAECoEvAAIHAAgIIw+EfACFAQAHAAgIIw+EfACFAQAAAA==.Leuchtrakete:BAAALAADCgMIAwAAAA==.Lex:BAAALAAECgQIBwAAAA==.',Li='Lich:BAAALAADCgMIAwABLAAECggIIgAFAMwdAA==.Lickmybowbow:BAAALAAECggICwAAAA==.Lighthaven:BAEALAADCggICAABLAAECggILwASAOwgAA==.Likeless:BAAALAAECgYIEQAAAA==.Littlemiss:BAAALAADCggICAAAAA==.Liuna:BAABLAAECoEbAAMYAAYIvRawEQB+AQAYAAYIvRawEQB+AQAWAAYIIBXdUQBkAQAAAA==.',Lo='Lormox:BAAALAAECgQIBAAAAA==.Loun:BAABLAAECoEWAAMCAAgIIhoPRQBCAgACAAgIIhoPRQBCAgAaAAIIcxJHXQBpAAAAAA==.Lovenna:BAAALAAECgYICAAAAA==.',Lu='Lugh:BAAALAADCgYIBgAAAA==.Lukês:BAAALAAECgUICAAAAA==.Lutano:BAAALAAECgQIBAAAAA==.Lutáno:BAABLAAECoEgAAMKAAcIFBUbJgDPAQAKAAcIFBUbJgDPAQAJAAIIFAWd3AA7AAAAAA==.Luzífer:BAAALAAECggIBgAAAA==.',Ly='Lynxarosia:BAAALAAECgQIEAAAAA==.Lyriska:BAAALAADCggIJgAAAA==.Lyzian:BAAALAAECgYICwAAAA==.',['Lè']='Lèddi:BAABLAAECoEaAAILAAgIzRN6UQAEAgALAAgIzRN6UQAEAgAAAA==.',['Lø']='Løstbølt:BAAALAADCggICAAAAA==.Løstlock:BAABLAAECoEYAAQUAAgIXBvAKQCtAQAXAAcIrBYdVADBAQAUAAcIIRnAKQCtAQAbAAEI+Q5+OgA8AAAAAA==.Løstlonewulf:BAAALAADCggIDAAAAA==.',['Lú']='Lúxe:BAABLAAECoElAAMIAAcIIQ4lgwBBAQAIAAcIIQ4lgwBBAQAMAAYIVwsAAAAAAAAAAA==.',Ma='Machtlos:BAAALAAECggIDgAAAA==.Machtlôs:BAABLAAECoEVAAIeAAgI9AmVYAA2AQAeAAgI9AmVYAA2AQAAAA==.Maggus:BAAALAAECgUIBQABLAAECggIDQABAAAAAA==.Magierhenry:BAAALAADCggIDwABLAAECggIHQACAJMbAA==.Magnison:BAABLAAECoEaAAICAAcIbBbHdwDKAQACAAcIbBbHdwDKAQAAAA==.Malnor:BAAALAAECgYICgAAAA==.Malthus:BAAALAAECgcICQAAAA==.Mankerayder:BAAALAADCgcIBwAAAA==.Manoloo:BAAALAAECggIDQAAAA==.Marcog:BAAALAADCgYIBgABLAAECgYIFQAIAGwTAA==.Marina:BAAALAAECgEIAQAAAA==.Marodan:BAABLAAECoEvAAIFAAgIeiSOBgAuAwAFAAgIeiSOBgAuAwAAAA==.Marone:BAACLAAFFIENAAMHAAQIQB4iEAADAQAHAAMIUiEiEAADAQAFAAQI0RgAAAAAAAAsAAQKgTYAAwcACAihJUEJADYDAAcACAheJUEJADYDAAUACAhvIgAAAAAAAAAA.Marsh:BAAALAADCgEIAQAAAA==.Matarama:BAAALAADCggIFAAAAA==.Matero:BAABLAAECoEeAAIRAAgICxckXwAFAgARAAgICxckXwAFAgABLAAECggIHAAHALocAA==.Maxdhmage:BAAALAAFFAMIBwAAAQ==.Mazus:BAAALAADCgcIFAAAAA==.',Me='Mejinn:BAAALAADCgcIBwAAAA==.Melaria:BAAALAAECgMIBgAAAA==.Meng:BAABLAAECoEYAAIQAAcINhsNFgA0AgAQAAcINhsNFgA0AgAAAA==.Metuin:BAAALAAECgMIBgABLAAECggIHAAIAB4ZAA==.Mexxy:BAAALAAECgYICgAAAA==.',Mi='Michhi:BAAALAADCggICAAAAA==.Miniwuscht:BAABLAAECoEUAAMdAAYIoBGFRACFAQAdAAYIoBGFRACFAQAgAAYIqxAvEgBTAQAAAA==.Mioûn:BAAALAAECgYIBgABLAAECgYIDwABAAAAAA==.',Mo='Moguay:BAAALAAECgEIAQAAAA==.Moint:BAAALAAECgQIBAABLAAFFAIIBgAFAD0dAA==.Moktaran:BAAALAADCggIEAAAAA==.Monial:BAAALAAECgIIAgAAAA==.Moniànà:BAAALAAECgQIEAAAAA==.Moonz:BAACLAAFFIEOAAILAAUIqhejBwDMAQALAAUIqhejBwDMAQAsAAQKgSMAAgsACAiSJNALADkDAAsACAiSJNALADkDAAAA.Moosauge:BAAALAAECggICAAAAA==.Moranír:BAABLAAECoEeAAILAAcIgxYTZQDSAQALAAcIgxYTZQDSAQAAAA==.Moriaty:BAAALAAECgMIAwAAAA==.Morla:BAAALAAECgYIBgAAAA==.Moronia:BAAALAAECgUICQABLAAECggINwAIAHgdAA==.Moírá:BAAALAADCgYIBgAAAA==.',Mu='Mubarak:BAABLAAECoEkAAIOAAYIcBUpYQCWAQAOAAYIcBUpYQCWAQAAAA==.Mucky:BAAALAAECggICAAAAA==.Mundgeruch:BAABLAAECoEcAAIhAAgInhO8HQATAgAhAAgInhO8HQATAgABLAAFFAMIBwARAKQYAA==.Muri:BAAALAAECgQIBAAAAA==.',My='Myrkva:BAAALAADCggICAAAAA==.',['Mé']='Méphîtó:BAAALAADCgcIBwABLAAECgcIGgAEAAQTAA==.',['Mì']='Mìchi:BAAALAAECggIEAAAAA==.Mìkasa:BAAALAADCgIIAgAAAA==.',['Mü']='Müdejo:BAAALAADCggIEgAAAA==.',Na='Nabilu:BAACLAAFFIEGAAIHAAIITROoKgCRAAAHAAIITROoKgCRAAAsAAQKgTEAAgcACAhOIa0bAMACAAcACAhOIa0bAMACAAAA.Nalâ:BAAALAADCggICAAAAA==.',Ne='Neferty:BAAALAADCgcIBwAAAA==.Nehiro:BAAALAAECgcIDgAAAA==.Neldion:BAAALAADCgIIAgAAAA==.Nemesìs:BAABLAAECoEVAAIEAAYICA3mUgAyAQAEAAYICA3mUgAyAQAAAA==.Nesua:BAAALAADCgcIEwAAAA==.Neve:BAAALAAECgEIAQAAAA==.Nevillé:BAAALAADCggICAAAAA==.Nexodia:BAAALAAECgYIBQAAAA==.',Ni='Niass:BAAALAAECggIBQAAAA==.Nielpferd:BAAALAADCgcICAAAAA==.Niessa:BAAALAAECgUIBQAAAA==.Nikkix:BAAALAAECggICAAAAA==.Nirviena:BAAALAADCggIHgAAAA==.',No='Nochba:BAAALAADCggICAAAAA==.Nofroghoon:BAAALAADCggICAAAAA==.Nofxy:BAACLAAFFIEGAAIHAAIIdB4VJwCWAAAHAAIIdB4VJwCWAAAsAAQKgRwAAgcABwiqItwpAHYCAAcABwiqItwpAHYCAAAA.Nootis:BAAALAAECggICAAAAA==.Norytton:BAAALAAECgYIBgAAAA==.',Nu='Nudelbeißer:BAAALAADCgcIBwABLAAECggIFQAKAHoXAA==.',Ny='Nygna:BAAALAAECgYIBgABLAAFFAYIFgAhAHcjAA==.Nyxiaza:BAAALAAECgYICAABLAAECggIBgABAAAAAA==.',['Nô']='Nôdónn:BAAALAADCggIDgAAAA==.Nôx:BAABLAAECoEZAAILAAcIFhbucAC3AQALAAcIFhbucAC3AQAAAA==.',Ob='Obmar:BAAALAADCggICAAAAA==.',Oh='Ohrschloch:BAABLAAECoEiAAIcAAcIWhXSJgDTAQAcAAcIWhXSJgDTAQAAAA==.',Ok='Oktaris:BAACLAAFFIEFAAIgAAII/SPmAADWAAAgAAII/SPmAADWAAAsAAQKgSkAAyAACAh+Iy0BACIDACAACAh+Iy0BACIDAB0ABgh6CelXAC4BAAAA.',Ol='Oldshadow:BAAALAADCggIFQAAAA==.',Oo='Oodin:BAAALAADCgcIGQABLAAFFAQICwAOACQWAA==.',Op='Opapit:BAAALAADCgIIAgAAAA==.',Or='Orcan:BAAALAADCggICAAAAA==.',Ox='Oxia:BAABLAAECoEcAAIYAAYIthKmFQBAAQAYAAYIthKmFQBAAQAAAA==.',Oz='Ozzburn:BAAALAAECgMIBAABLAAECgQIEAABAAAAAA==.',Pa='Painge:BAAALAADCgMIBAAAAA==.Palahenry:BAABLAAECoEdAAICAAgIkxvVOQBlAgACAAgIkxvVOQBlAgAAAA==.Palakadabra:BAAALAAECgYIDwAAAA==.Palakazam:BAACLAAFFIEFAAICAAMIBxaPIQCsAAACAAMIBxaPIQCsAAAsAAQKgRgAAwIACAhVHuNRAB8CAAIABwh8GuNRAB8CACIABQjLH/kdANABAAAA.Pardus:BAAALAAECgIIAgAAAA==.Paulporter:BAAALAADCggIHgAAAA==.Paunchy:BAAALAAECgMIBQAAAA==.',Pe='Peena:BAAALAAECgUIDQAAAA==.Pentor:BAAALAAECgIIAgAAAA==.Peria:BAABLAAECoEvAAIYAAgIiiSxAQA6AwAYAAgIiiSxAQA6AwAAAA==.Petawawa:BAAALAADCggIFAAAAA==.Pewpewbrrbrr:BAAALAADCgYIBgABLAAECggIHwAFANEhAA==.Pexl:BAAALAADCggICAAAAA==.',Ph='Phénomenom:BAACLAAFFIEKAAIRAAQIWyEmEwAWAQARAAQIWyEmEwAWAQAsAAQKgSwAAhEACAjcIt0LADcDABEACAjcIt0LADcDAAAA.',Pi='Pinu:BAABLAAECoEcAAIHAAYIQRcBjwBgAQAHAAYIQRcBjwBgAQAAAA==.',Po='Polychron:BAAALAAECgMIAwAAAA==.Poorhomie:BAACLAAFFIEIAAIJAAIIvCDtIADIAAAJAAIIvCDtIADIAAAsAAQKgScAAgkACAhsJFkJADwDAAkACAhsJFkJADwDAAAA.Poweroflight:BAAALAADCggICAAAAA==.',Pr='Prachnan:BAAALAADCggIAQAAAA==.Praystation:BAAALAADCggICAAAAA==.Pree:BAAALAADCggICAAAAA==.Preesthenry:BAAALAAECgEIAQABLAAECggIHQACAJMbAA==.Pridimor:BAAALAADCgYIBgABLAAECggIHAAKADwZAA==.Proxipriest:BAAALAADCgcIDQAAAA==.',Pu='Puschy:BAAALAADCgcIDgAAAA==.',Qu='Quent:BAAALAADCggICAAAAA==.Quéendemón:BAAALAAECgYIDAAAAA==.',Ra='Raassiieerrt:BAACLAAFFIEGAAIOAAIIgRTgIgCdAAAOAAIIgRTgIgCdAAAsAAQKgRgAAg4ACAhHGzApAGsCAA4ACAhHGzApAGsCAAEsAAUUAggGAAwAbg8A.Raedan:BAABLAAECoEcAAIHAAgIuhzUKAB6AgAHAAgIuhzUKAB6AgAAAA==.Raiden:BAABLAAECoEwAAIjAAgIniOVBQD1AgAjAAgIniOVBQD1AgAAAA==.Ranyr:BAAALAAECggICQAAAA==.Rassiert:BAAALAAFFAMIAwAAAA==.Rassiieerrt:BAACLAAFFIEGAAIKAAII8xsjCQCkAAAKAAII8xsjCQCkAAAsAAQKgRwAAgoACAiOGUIWAEgCAAoACAiOGUIWAEgCAAEsAAUUAggGAAwAbg8A.Rassiieerrtt:BAACLAAFFIEGAAIMAAIIbg9EHgCWAAAMAAIIbg9EHgCWAAAsAAQKgSIAAgwACAiFFPQ4APkBAAwACAiFFPQ4APkBAAAA.Rasziel:BAABLAAECoEvAAIcAAgIGRRlHwAGAgAcAAgIGRRlHwAGAgAAAA==.Ravangatanga:BAAALAADCgYIGQAAAA==.Raxor:BAAALAADCgcIBwAAAA==.',Re='Rebilli:BAAALAAECggIBwAAAA==.Redfírefox:BAAALAAECgIIAgAAAA==.Rehexi:BAAALAAECggIEAAAAA==.Reilbaer:BAAALAAECgYIBgAAAA==.Rejäger:BAAALAAECggICAAAAA==.Remmi:BAAALAAECgMICgAAAA==.Revoker:BAAALAAECggIEQABLAAFFAUIFQAdAJYhAA==.Rexl:BAAALAADCgcIFAABLAADCggICAABAAAAAA==.',Ri='Rilthaien:BAAALAADCgEIAQAAAA==.',Ro='Romeo:BAAALAAECgYIBwAAAA==.Royalhaze:BAABLAAECoEoAAQJAAgIBBxSKgCKAgAJAAgIPxtSKgCKAgAKAAMIWB66VgDcAAAVAAIIjAnRGABOAAABLAAECggIHwAFANEhAA==.',Ru='Rukhmar:BAAALAAECgYIBgAAAA==.Runningsteel:BAAALAADCggICAAAAA==.',Ry='Ryl:BAAALAADCgcIDgAAAA==.',['Rè']='Rèva:BAAALAAECgIIAgAAAA==.',['Ré']='Récoba:BAAALAADCgUIBQAAAA==.',['Rê']='Rêinsch:BAAALAADCggIEwAAAA==.',Sa='Sagoib:BAAALAADCgYIBgAAAA==.Saishi:BAAALAAECgMIAwAAAA==.Salázar:BAAALAADCgIIAgAAAA==.Samant:BAAALAAECggICAAAAA==.Saneheal:BAAALAAECgEIAQABLAAECgIIAgABAAAAAA==.Satanyus:BAAALAAECgIIBAAAAA==.',Sc='Scenario:BAAALAADCgMIAwAAAA==.Schamanie:BAAALAADCgQIBAAAAA==.Schandel:BAAALAAECggIEQAAAA==.Schlumpfee:BAAALAAECgcIBwAAAA==.Schubi:BAAALAADCggIFQAAAA==.Schámin:BAAALAADCgcICQAAAA==.',Se='Sengelbengel:BAAALAADCggICAABLAAFFAMICwAXAKkRAA==.Senndy:BAAALAAECgYIDAAAAA==.',Sh='Shadöw:BAAALAAECggICAABLAAECggIIgAFAMwdAA==.Shamehenry:BAAALAAECgYIBgABLAAECggIHQACAJMbAA==.Shampagne:BAAALAAECgQIBAABLAAECgcIGwAZABQaAA==.Sherezâde:BAAALAADCgcIBwAAAA==.Shinaru:BAAALAAECgEIAQAAAA==.Showfear:BAAALAAECgYIBgAAAA==.Showgamer:BAAALAAECgcIEQAAAA==.Shây:BAABLAAECoE3AAMMAAgIExZqNQAJAgAMAAgIExZqNQAJAgAIAAgIUhM9UADEAQAAAA==.Shócker:BAABLAAECoEfAAIXAAgIgg2iUADNAQAXAAgIgg2iUADNAQAAAA==.',Si='Sigung:BAABLAAECoEaAAMdAAgI9Q37PACpAQAdAAgI9Q37PACpAQAeAAIIMQrRmgBVAAAAAA==.Silvera:BAAALAAECgMIBgAAAA==.Sinoa:BAAALAADCggICAAAAA==.Sinthrael:BAAALAAECgYIDgABLAAFFAYIFgAhAHcjAA==.',Sk='Skeletór:BAABLAAECoEWAAIOAAcIYQ8NXQChAQAOAAcIYQ8NXQChAQAAAA==.Skylah:BAAALAAECgYIAgAAAA==.Skádí:BAAALAADCgEIAQAAAA==.',Sl='Sloth:BAAALAAECgYIDwAAAA==.Slumlius:BAABLAAECoEcAAIMAAcICx6AIwBsAgAMAAcICx6AIwBsAgAAAA==.Slôw:BAAALAAECgIIAgAAAA==.',Sn='Snîbbelz:BAAALAAECgYICwABLAAFFAMIBwABAAAAAA==.',So='Soranaja:BAABLAAECoEvAAMWAAgIYSLGCwDhAgAWAAgIYSLGCwDhAgAEAAUImAZdbAC4AAAAAA==.Sorbaratina:BAAALAADCggIFwABLAAECgQIEAABAAAAAA==.',Sp='Spikê:BAAALAAECgYIBgAAAA==.Spitzi:BAAALAAECgYIBgAAAA==.',Sr='Srames:BAACLAAFFIENAAIZAAUIcx65AgDaAQAZAAUIcx65AgDaAQAsAAQKgSgAAhkACAjDJXoCAGADABkACAjDJXoCAGADAAAA.',St='Stefbêrt:BAAALAAECggICAAAAA==.Sternenstaub:BAAALAAECgMIAwAAAA==.Stinki:BAAALAADCggICQAAAA==.Stoarm:BAAALAADCgYIDQAAAA==.Strawman:BAABLAAECoEWAAIOAAgI3xYKMwA5AgAOAAgI3xYKMwA5AgAAAA==.Stêfbert:BAAALAAECgcIEgAAAA==.Stêfbêrt:BAAALAAECggIBAAAAA==.',Su='Sucan:BAAALAADCggICgAAAA==.Supasleyajin:BAAALAAECgYIBgAAAA==.Surrenity:BAABLAAECoEYAAMaAAcIXxJ4LQCLAQAaAAcIXxJ4LQCLAQACAAEInwH8TwEUAAAAAA==.Susma:BAAALAADCgYIAQAAAA==.',Sy='Syana:BAAALAADCgIIAgAAAA==.Syleene:BAACLAAFFIEQAAIIAAUI7xpNBADCAQAIAAUI7xpNBADCAQAsAAQKgS0AAggACAgQJdACAE0DAAgACAgQJdACAE0DAAAA.Syreeza:BAACLAAFFIEKAAIWAAMIGB1tCQALAQAWAAMIGB1tCQALAQAsAAQKgSAAAhYACAijJXEIAAIDABYACAijJXEIAAIDAAEsAAUUBQgQAAgA7xoA.Syrun:BAAALAAECgYIEgABLAAFFAUIEAAIAO8aAA==.',['Sâ']='Sâia:BAAALAAECgYICQAAAA==.',['Sé']='Séance:BAACLAAFFIEYAAIMAAcITCNrAADlAgAMAAcITCNrAADlAgAsAAQKgS0AAgwACAiiJvsAAJADAAwACAiiJvsAAJADAAAA.',['Sý']='Sýlvâna:BAAALAAECgYICgAAAA==.',Ta='Tabaluca:BAAALAAECgUIBQAAAA==.Tagträumer:BAAALAADCgcIBwAAAA==.Tahwor:BAAALAAECggICAAAAA==.Tamtamta:BAABLAAECoEgAAICAAgInRiAXwD9AQACAAgInRiAXwD9AQAAAA==.Tasuim:BAAALAADCgYIBgAAAA==.Taton:BAAALAAECgYIDQABLAAECggIJgAKAGwXAA==.',Te='Teeckanne:BAAALAADCgYIBgAAAA==.Teldiatide:BAABLAAECoEZAAIIAAcInCS9FQCsAgAIAAcInCS9FQCsAgAAAA==.Teldiatree:BAAALAADCgUIBQAAAA==.Tengen:BAAALAADCgcIBwABLAAECggIJAAOAHAVAA==.Terinak:BAABLAAECoEbAAQaAAgICROJJQC+AQAaAAcIrhOJJQC+AQACAAYIBhPcvQBKAQAiAAQIkQ5PSgCfAAAAAA==.',Th='Theelement:BAABLAAECoEYAAIMAAgI5RoZIACBAgAMAAgI5RoZIACBAgAAAA==.Thylania:BAAALAADCggICAAAAA==.',Ti='Tiffzy:BAAALAAECgYIBgAAAA==.Tisoo:BAABLAAECoEVAAIOAAgIPgsVewBNAQAOAAgIPgsVewBNAQAAAA==.Tisôrân:BAAALAAECgIIAwABLAAECggIFQAOAD4LAA==.',To='Tobiichi:BAAALAADCggICAAAAA==.Todie:BAAALAAECggIDQAAAA==.Todo:BAAALAADCgYIBgAAAA==.Toffees:BAAALAAECgUIBQAAAA==.Tohranus:BAAALAAECgIIAgAAAA==.Tokrahexe:BAABLAAECoEjAAIXAAYIxg+6fwBHAQAXAAYIxg+6fwBHAQAAAA==.Tolbes:BAAALAADCggICAAAAA==.Touros:BAAALAADCgcICwAAAA==.',Tr='Trag:BAAALAAECggICAAAAA==.Trivion:BAABLAAECoEUAAIaAAcI1AhaOgBBAQAaAAcI1AhaOgBBAQAAAA==.Troros:BAAALAAECgMIAwAAAA==.Trulli:BAABLAAECoEcAAIaAAYI+x5PJgC5AQAaAAYI+x5PJgC5AQAAAA==.Tràxéx:BAAALAADCgcIDQABLAAECgcICAABAAAAAA==.Träumchen:BAABLAAECoEmAAMXAAgI9x+GHgCyAgAXAAgI9x+GHgCyAgAbAAgI3Q4jCwDmAQAAAA==.Trôublemâker:BAABLAAECoEgAAMiAAcIRBqfFwAIAgAiAAcIhBmfFwAIAgACAAYI5hU9sQBgAQABLAAECgcIGgAEAAQTAA==.',Ts='Tscholle:BAACLAAFFIEVAAISAAUIWBoDAwCoAQASAAUIWBoDAwCoAQAsAAQKgTAAAhIACAhMJLwCAEUDABIACAhMJLwCAEUDAAAA.Tschopao:BAAALAADCggICAAAAA==.',Tu='Tubbii:BAAALAAECggIDwAAAA==.Tubfrost:BAAALAAECgMIAwAAAA==.Tuetrix:BAAALAADCggIDAAAAA==.',Tw='Twiix:BAAALAADCggICAAAAA==.',['Tâ']='Târya:BAAALAADCgMIBAAAAA==.',['Tó']='Tórras:BAABLAAECoEeAAMaAAgIZCIRCwCpAgAaAAcIaiMRCwCpAgACAAQICQyyAAG0AAAAAA==.',['Tü']='Tüvnord:BAAALAADCgMIBQABLAAECggIJAAOAHAVAA==.',Va='Valarion:BAAALAAECggIBQAAAA==.Vaquer:BAAALAAECgYICgABLAAECgYIDwABAAAAAA==.',Ve='Venues:BAAALAADCgYIBgABLAAECgMIBgABAAAAAA==.Verformt:BAAALAADCgcIBwABLAAFFAMIBwARAKQYAA==.',Vi='Victori:BAAALAAECgMIBAAAAA==.Villas:BAAALAADCggICAAAAA==.',Vo='Vollid:BAABLAAECoEXAAIZAAgINCKNBgAZAwAZAAgINCKNBgAZAwABLAAFFAUIFQAdAJYhAA==.Vollverwesen:BAACLAAFFIEHAAIRAAMIpBjTFAAIAQARAAMIpBjTFAAIAQAsAAQKgRoAAhEACAilHV4/AFkCABEACAilHV4/AFkCAAAA.',['Vé']='Véntu:BAACLAAFFIEFAAILAAIIRR5IOwCGAAALAAIIRR5IOwCGAAAsAAQKgSEAAgsACAi0Hy0kAK8CAAsACAi0Hy0kAK8CAAAA.',Wa='Walburgis:BAAALAADCggIDwAAAA==.Walturion:BAABLAAECoEUAAMjAAgIKQ32IgCLAQAjAAcIuQz2IgCLAQARAAUIFwqP+QDoAAAAAA==.Wandaja:BAABLAAECoEWAAIWAAYIqhQETQB2AQAWAAYIqhQETQB2AQAAAA==.',Wh='Whitebelt:BAACLAAFFIEJAAIQAAUIbxYyBABUAQAQAAUIbxYyBABUAQAsAAQKgTQAAhAACAjZIxoGABwDABAACAjZIxoGABwDAAAA.Whitelizard:BAAALAADCgcIDQAAAA==.Whîtêlizard:BAAALAADCgYIBgAAAA==.',Wi='Wildbumser:BAAALAAECgYICwAAAA==.Wilnari:BAAALAAECgYIEAAAAA==.',Xa='Xauld:BAAALAADCgUIBQAAAA==.',Xo='Xornan:BAAALAADCgYICwAAAA==.',Xy='Xyrene:BAACLAAFFIEMAAITAAQI2iQVAQCuAQATAAQI2iQVAQCuAQAsAAQKgScAAhMACAhoJtcAAHgDABMACAhoJtcAAHgDAAEsAAUUBQgNABkAcx4A.',Yi='Yiikez:BAACLAAFFIEGAAILAAIIghzwHwCqAAALAAIIghzwHwCqAAAsAAQKgSkAAgsACAhzIIUYAO4CAAsACAhzIIUYAO4CAAAA.Yikezdh:BAACLAAFFIEGAAILAAIIZxUvJQCgAAALAAIIZxUvJQCgAAAsAAQKgRsAAgsACAibHjIdANMCAAsACAibHjIdANMCAAEsAAUUAggGAAsAghwA.',Ym='Ymir:BAAALAADCgYIBgAAAA==.',Yo='Yodue:BAAALAAECgYIDAAAAA==.Yore:BAABLAAECoEoAAIdAAgIcyCPDQD5AgAdAAgIcyCPDQD5AgAAAA==.Yorkzy:BAACLAAFFIESAAMkAAQIPSPsAQCTAQAkAAQIHSPsAQCTAQAhAAQIzR5RGgBiAAAsAAQKgTUABCQACAjsJg0AAJUDACQACAixJg0AAJUDACUABghGE/0cAFABACEACAjKJgAAAAAAAAAA.',Yu='Yunney:BAABLAAECoEVAAIeAAgIExHONgDeAQAeAAgIExHONgDeAQAAAA==.',Yv='Yvi:BAAALAAECgYIBgAAAA==.',Za='Zaerox:BAABLAAECoEXAAIEAAcIayI2FgCLAgAEAAcIayI2FgCLAgAAAA==.Zagnadin:BAAALAADCgQIBAAAAA==.Zauberponny:BAABLAAECoEWAAICAAYIYyFkTwAmAgACAAYIYyFkTwAmAgAAAA==.Zawala:BAAALAADCggIIgAAAA==.',Ze='Zeraphine:BAACLAAFFIELAAIMAAMIxRkFDwD+AAAMAAMIxRkFDwD+AAAsAAQKgSYAAwwACAheJFkJADYDAAwACAheJFkJADYDAAgABAjfDAnWAJ4AAAAA.Zeuu:BAAALAADCgUIBQAAAA==.',Zu='Zuano:BAAALAAECgYICQAAAA==.',Zy='Zypia:BAAALAAECggIEAAAAA==.',['Æa']='Æasy:BAAALAAECggICAAAAA==.',['Æó']='Æón:BAAALAAECgcICgAAAA==.',['Éx']='Éx:BAAALAAECgUIBwAAAA==.',['Ôo']='Ôopsie:BAAALAAECggIDgAAAA==.',['Ös']='Ösiman:BAAALAADCggICAAAAA==.',['Øs']='Øskar:BAAALAAECggICAABLAAECggIIQAQADQeAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end