local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Warlock-Destruction','Priest-Holy','Shaman-Restoration','Mage-Arcane','Unknown-Unknown','DeathKnight-Frost','Druid-Restoration','Paladin-Protection','Warlock-Demonology','Warlock-Affliction','Paladin-Holy','Mage-Fire','Druid-Feral','Hunter-BeastMastery','DeathKnight-Unholy','Priest-Shadow','Warrior-Fury','DemonHunter-Havoc','Paladin-Retribution','Hunter-Marksmanship','Evoker-Preservation','Hunter-Survival','Monk-Windwalker','Druid-Balance','Shaman-Enhancement','DeathKnight-Blood','Warrior-Protection','DemonHunter-Vengeance','Shaman-Elemental','Monk-Mistweaver','Rogue-Assassination','Monk-Brewmaster','Mage-Frost','Druid-Guardian','Warrior-Arms','Rogue-Outlaw',}; local provider = {region='EU',realm='Taerar',name='EU',type='weekly',zone=44,date='2025-09-24',data={Ad='Adela:BAAALAADCggIJgABLAAFFAUIEgABAC0WAA==.',Ag='Agira:BAABLAAECoEVAAICAAcIWBSVPADCAQACAAcIWBSVPADCAQAAAA==.',Ah='Ahsoka:BAACLAAFFIEFAAIDAAIIVg3mNgB1AAADAAIIVg3mNgB1AAAsAAQKgSgAAgMACAjNG4EvADACAAMACAjNG4EvADACAAAA.',Al='Alanihfanboi:BAACLAAFFIEGAAIEAAIIJxynKQCmAAAEAAIIJxynKQCmAAAsAAQKgRUAAgQACAhhG1U+ADMCAAQACAhhG1U+ADMCAAEsAAUUBwgaAAEA5R8A.Ally:BAAALAAECgYIBgABLAAECgcIDgAFAAAAAA==.Alukard:BAABLAAECoEWAAIGAAYIUgU87wD/AAAGAAYIUgU87wD/AAAAAA==.Alurya:BAAALAAFFAIIAgABLAAFFAQIBgAHABMPAA==.',Am='Amali:BAAALAADCgMIAwABLAAECggIHwAIANQaAA==.',An='Ankerscham:BAAALAADCggIEQAAAA==.Anoubis:BAACLAAFFIEJAAMBAAMIAhyZIgCsAAABAAIISBqZIgCsAAAJAAEIdh/OGgBfAAAsAAQKgR0ABAkACAipIM0XAB0CAAkABgh+IM0XAB0CAAEABggNHiZBAAYCAAoAAwjiFSwgAMsAAAAA.Antheaa:BAAALAAECgcIEwAAAA==.',Aq='Aquamarin:BAAALAADCgEIAQAAAA==.Aquené:BAAALAAECgcIBwAAAA==.',Ar='Artiè:BAAALAAECgMIBQAAAA==.Artâîos:BAAALAAECggICwAAAA==.Arés:BAAALAAFFAIIAgABLAAFFAMICQABAAIcAA==.',As='Asa:BAACLAAFFIEHAAILAAMIcwtdCwDbAAALAAMIcwtdCwDbAAAsAAQKgS0AAgsACAg0GrMUAEECAAsACAg0GrMUAEECAAAA.Asche:BAAALAAECgYIBgAAAA==.Aseyna:BAAALAAECgcIDgABLAAFFAQIBgAHABMPAA==.Ashokar:BAAALAAECgIIAwAAAA==.Aszaera:BAABLAAECoEcAAMEAAgI4BnnLgB1AgAEAAgI4BnnLgB1AgAMAAcIqg4wCACwAQAAAA==.',Aw='Awi:BAABLAAECoEeAAINAAYIJBaKGgCiAQANAAYIJBaKGgCiAQAAAA==.',Ax='Axero:BAAALAADCgcIBwAAAA==.',Az='Azelia:BAAALAAECgUICwABLAAFFAMIBwALAGUSAA==.Azeoríth:BAABLAAECoEhAAIOAAgIzBBYYADFAQAOAAgIzBBYYADFAQAAAA==.Azthara:BAAALAAECggICAAAAA==.',Ba='Babyyodah:BAAALAAFFAIIBAAAAA==.Ballermann:BAAALAADCgYIBgAAAA==.Bangbang:BAAALAAECgcICAAAAA==.Banosh:BAAALAAECggIBwAAAA==.Batushka:BAAALAADCggIHAAAAA==.',Be='Beatmymeat:BAABLAAECoEcAAMPAAgI0BeoEwAXAgAPAAgI0BeoEwAXAgAGAAIIgQSKOgFZAAABLAAFFAgIJgAQADYmAA==.Beifahrer:BAAALAADCgcIBwAAAA==.Belaal:BAAALAADCggICAAAAA==.Bertha:BAAALAADCggICAAAAA==.',Bi='Bibedibu:BAAALAADCgcIBwAAAA==.',Bl='Blakkii:BAACLAAFFIEUAAIRAAcIbBgEAQCHAgARAAcIbBgEAQCHAgAsAAQKgSMAAhEACAiaJgEFAGMDABEACAiaJgEFAGMDAAAA.Blakkiidh:BAACLAAFFIEIAAISAAIIgCLaGQDAAAASAAIIgCLaGQDAAAAsAAQKgRoAAhIACAgxIqcVAP8CABIACAgxIqcVAP8CAAEsAAUUBwgUABEAbBgA.Bloomtales:BAAALAAECgEIAQAAAA==.Bloódymáry:BAAALAADCgIIAQAAAA==.Bluebärry:BAAALAAECgYICgABLAAECgYIDAAFAAAAAA==.',Bo='Bohm:BAAALAADCggICAAAAA==.Bonetobewild:BAAALAAECgYIBgABLAAECggIIgAIAGogAA==.Bonk:BAAALAAECgYIBgAAAA==.Boran:BAAALAADCggIEAAAAA==.',Br='Bradwarden:BAAALAAECgYICQAAAA==.Bretterbube:BAAALAAECgMIAwABLAAFFAcIGgAQAMckAA==.Brewmaster:BAAALAADCgcIBwAAAA==.Broberto:BAAALAAECgYICwABLAAFFAMICgACACIbAA==.Bronathan:BAAALAAECgYIEAABLAAFFAMICgACACIbAA==.Brosita:BAAALAADCgUIBQABLAAFFAMICgACACIbAA==.Brunhílde:BAAALAAECggIEAAAAA==.',Bu='Burle:BAAALAAECgYIEwAAAA==.',Ca='Caesario:BAABLAAECoEUAAIOAAYIJwibugAKAQAOAAYIJwibugAKAQAAAA==.Calamitas:BAACLAAFFIEVAAITAAYIqSADAQBkAgATAAYIqSADAQBkAgAsAAQKgR4AAhMACAhDJkIFAGoDABMACAhDJkIFAGoDAAAA.Cameron:BAAALAAECgYICwAAAA==.Catman:BAAALAAECgYIBwAAAA==.',Ce='Century:BAAALAAECgYIBgAAAA==.Cezar:BAABLAAECoEYAAIUAAcItRxBJgAlAgAUAAcItRxBJgAlAgAAAA==.',Ch='Chain:BAABLAAECoEUAAIBAAgIXQgMdQBjAQABAAgIXQgMdQBjAQABLAAFFAIIBgABANMYAA==.Chaintales:BAAALAAECggICAABLAAFFAYIEAAHAP8aAA==.Channingtotm:BAAALAAECgIIAgABLAAECgYIBgAFAAAAAA==.Chaozstraza:BAACLAAFFIELAAIVAAMInCBHBgAbAQAVAAMInCBHBgAbAQAsAAQKgRQAAhUACAgXHvAGAKkCABUACAgXHvAGAKkCAAEsAAUUBwgbABUA1xsA.Choanne:BAAALAAECgcIDgABLAAECggIHQABAFMcAA==.',Ci='Ci:BAABLAAECoEZAAIWAAgI2SJ4AQAnAwAWAAgI2SJ4AQAnAwABLAAFFAIIBgAXANQhAA==.Cinni:BAABLAAECoEcAAIYAAcI3hdfMwDBAQAYAAcI3hdfMwDBAQAAAA==.',Cl='Clarity:BAAALAAECgEIAQAAAA==.Cloryne:BAAALAADCgcIDgAAAA==.',Cr='Crescentia:BAAALAADCgcIDgAAAA==.',['Cé']='Cénturio:BAABLAAECoEXAAIRAAcI4A6cYQCVAQARAAcI4A6cYQCVAQAAAA==.',Da='Dalli:BAAALAAECggICAABLAAFFAMIBwAZAKAHAA==.Dallisham:BAACLAAFFIEHAAIZAAMIoAcZAwDaAAAZAAMIoAcZAwDaAAAsAAQKgR8AAhkABwhrIl0GAJYCABkABwhrIl0GAJYCAAAA.Darior:BAAALAADCggIHgABLAAECggIJAAaAGcXAA==.',De='Deamion:BAAALAAECgYIDwAAAA==.Deeprumay:BAAALAAECgcIEQAAAA==.Deichen:BAACLAAFFIEMAAIbAAMI1xWMCADlAAAbAAMI1xWMCADlAAAsAAQKgS4AAhsACAhxIg4GACEDABsACAhxIg4GACEDAAAA.Dekarumay:BAAALAAECgYIBgAAAA==.Deltopia:BAAALAAECgcICgAAAA==.Devilinside:BAAALAADCggIDgABLAAECgYIDgAFAAAAAA==.Devilknight:BAAALAAECgQIBgABLAAFFAMICwAcABkVAA==.Devkev:BAAALAADCgYIBgAAAA==.Devourdragon:BAAALAAECgIIBQAAAA==.Dexor:BAAALAAFFAEIAQAAAQ==.Dexoui:BAAALAAECgUIBQABLAAFFAEIAQAFAAAAAA==.',Dh='Dhracyr:BAAALAAECgcICwAAAA==.',Di='Dilemma:BAAALAADCggIEAAAAA==.Disc:BAAALAAECgMIAwAAAA==.Divineles:BAAALAADCgEIAQAAAA==.Divinetales:BAABLAAFFIELAAILAAUIyCKFAQAuAgALAAUIyCKFAQAuAgAAAA==.',Do='Dotti:BAAALAADCggIIAAAAA==.',Dr='Dracthyrke:BAAALAAFFAIIAgAAAA==.Dreamerzz:BAAALAAECgYIBgABLAAFFAYICwAEAAMYAA==.',Dy='Dys:BAAALAAECgQICgAAAA==.Dysteria:BAAALAAECgIIAgABLAAECgQICgAFAAAAAA==.',Ec='Eclipsis:BAAALAADCgYIBgABLAAECggIIAATACofAA==.',El='Elemegon:BAABLAAECoEZAAIdAAgI/B0mGAC7AgAdAAgI/B0mGAC7AgABLAAFFAIIBAAFAAAAAA==.Elexys:BAAALAAECgIIAgAAAA==.Elianor:BAAALAADCgQIBAABLAADCgcIBwAFAAAAAA==.Elly:BAAALAAECgcIDgAAAA==.Elunariya:BAAALAAECgQIBwAAAA==.',En='Ende:BAACLAAFFIEPAAMdAAYIIBWbBgDKAQAdAAUIohebBgDKAQADAAEIhwAmUQA2AAAsAAQKgR8AAh0ACAh0JQoJADkDAB0ACAh0JQoJADkDAAAA.Endworld:BAACLAAFFIEHAAMYAAMIMBH2CgDrAAAYAAMIMBH2CgDrAAANAAIIIRCqCQCaAAAsAAQKgRkAAxgACAgTHMwjABwCABgACAgTHMwjABwCAA0AAQjZEVA+AD0AAAEsAAUUBggPAB0AIBUA.Enternameplx:BAABLAAECoEnAAIDAAgIoCbwAABwAwADAAgIoCbwAABwAwAAAA==.',Er='Error:BAAALAADCgMIAwABLAAECgUICAAFAAAAAA==.',Ex='Exeqt:BAABLAAFFIEFAAIRAAII1B6zGACxAAARAAII1B6zGACxAAAAAA==.',Fa='Failalot:BAAALAAECggICAABLAAECggIHwAIANQaAA==.Failerella:BAABLAAECoEjAAIBAAcI6xbORAD4AQABAAcI6xbORAD4AQAAAA==.Falria:BAABLAAECoEZAAISAAYI3hcgggCTAQASAAYI3hcgggCTAQAAAA==.Favera:BAAALAAECgYIBwAAAA==.',Fe='Feljunkie:BAACLAAFFIEGAAISAAIIxB0NJAChAAASAAIIxB0NJAChAAAsAAQKgS0AAhIACAg7JW8PACIDABIACAg7JW8PACIDAAAA.Felora:BAAALAAECgIIAgAAAA==.',Fi='Fineshyt:BAAALAADCgEIAQAAAA==.',Fl='Floria:BAAALAAECgQIBwAAAA==.Fluffns:BAAALAAECgEIAQAAAA==.',Fo='Foxyroxx:BAAALAAECggIDQAAAA==.',Fr='Freaqqz:BAAALAAFFAIIAgAAAA==.Freyja:BAAALAAECggICAAAAA==.',Fu='Fullmute:BAAALAAECgMIAwAAAA==.Futter:BAACLAAFFIEXAAIdAAcItyNlAADoAgAdAAcItyNlAADoAgAsAAQKgSAAAh0ACAjdJmkBAIkDAB0ACAjdJmkBAIkDAAAA.Futterkaboom:BAACLAAFFIEIAAIYAAII0hy5EACkAAAYAAII0hy5EACkAAAsAAQKgRkAAhgACAgtGlsZAG0CABgACAgtGlsZAG0CAAAA.',['Fí']='Fíght:BAABLAAECoEkAAIaAAgIZxcLEwDpAQAaAAgIZxcLEwDpAQAAAA==.',Ga='Garzok:BAABLAAECoEZAAMJAAcI5CAmEQBYAgAJAAYIXSImEQBYAgABAAIIfhiiuwCJAAAAAA==.',Ge='Gefailix:BAAALAADCggICQAAAA==.Gesuchristie:BAABLAAECoEXAAMBAAgIaB/dFwDcAgABAAgIaB/dFwDcAgAJAAUIgAe8YgC0AAAAAA==.',Gh='Gharex:BAACLAAFFIESAAMOAAcIzSGvAQA+AgAOAAYI1x+vAQA+AgAUAAUIwyCMAwDUAQAsAAQKgR0AAxQACAhsJi0GADIDABQACAgFJi0GADIDAA4ABAgKJTRpALABAAAA.',Gi='Gigachad:BAACLAAFFIEGAAIIAAIIjxqoCgCbAAAIAAIIjxqoCgCbAAAsAAQKgSAAAggACAi0IOMHAN4CAAgACAi0IOMHAN4CAAAA.Giggasebb:BAACLAAFFIEaAAIeAAcILBasAABZAgAeAAcILBasAABZAgAsAAQKgR8AAh4ACAj6IwAEABYDAB4ACAj6IwAEABYDAAAA.',Go='Goresoul:BAAALAAECgYIEAABLAAFFAQIDgAFAAAAAA==.Gorgooth:BAAALAAFFAIIBAAAAA==.Gorthax:BAAALAAECgYIEwABLAAFFAMICAAdABQLAA==.Gorynn:BAAALAAFFAQIDgAAAQ==.Gotta:BAAALAADCgcIDQAAAA==.',Gr='Grafgrinder:BAAALAAECgQIAwAAAA==.',Gy='Gyros:BAAALAAECgYIBgAAAA==.',He='Heilerheilen:BAAALAAFFAIIAgAAAA==.Hellidan:BAAALAADCgYIBgAAAA==.',Hi='Hinna:BAABLAAECoEfAAICAAgIsByXFgCcAgACAAgIsByXFgCcAgAAAA==.',Ho='Hogenkobold:BAAALAAECgMIAwAAAA==.Holydevil:BAABLAAECoEiAAMIAAgIaiB+BwDmAgAIAAgIaiB+BwDmAgATAAEIbBG+OAE+AAAAAA==.Holymacaroni:BAAALAADCggICAAAAA==.Holymilk:BAAALAAECgcIDgAAAA==.Hopplahasi:BAACLAAFFIEaAAMBAAcI5R8NAQCzAgABAAcI5R8NAQCzAgAJAAIIWBWdDwCeAAAsAAQKgR4ABAEACAgTJS8MACoDAAEACAgTJS8MACoDAAoABAiDHLMXAC0BAAkAAQgrHQl+AEoAAAAA.',Hu='Huhn:BAAALAAECgMIAwAAAA==.',Hy='Hypatia:BAABLAAECoEbAAMHAAYIihJUWgBHAQAHAAYIihJUWgBHAQAYAAYIiRBPVAAsAQAAAA==.',['Hâ']='Hâvock:BAAALAAECgYIEQAAAA==.',['Hö']='Hörnie:BAAALAADCgcIBwAAAA==.',['Hü']='Hüftschuss:BAAALAAECggICAABLAAECggIHwAIANQaAA==.',Ik='Ikkebinrogue:BAABLAAECoEZAAIfAAgIvRKEJADiAQAfAAgIvRKEJADiAQAAAA==.Iksdehqt:BAACLAAFFIEHAAIfAAQIiBEwBQBWAQAfAAQIiBEwBQBWAQAsAAQKgSMAAh8ACAgTHvEOAKUCAB8ACAgTHvEOAKUCAAAA.',Il='Ilyzia:BAACLAAFFIEHAAILAAMIZRKTCQDxAAALAAMIZRKTCQDxAAAsAAQKgSIAAwsACAhJFAUcAAMCAAsACAhJFAUcAAMCABMACAjKEzt1AM8BAAAA.',Im='Imi:BAAALAAECggICAAAAA==.',In='Ingtar:BAAALAAECggIEAAAAA==.Intox:BAACLAAFFIETAAIdAAUIwRfGBwCyAQAdAAUIwRfGBwCyAQAsAAQKgSAAAh0ACAh4JCUKAC8DAB0ACAh4JCUKAC8DAAAA.',Iw='Iwy:BAABLAAECoEjAAIDAAgIQBERXwCcAQADAAgIQBERXwCcAQAAAA==.',Ji='Ji:BAAALAAECgIIAgABLAAECgMIAwAFAAAAAA==.Jiuna:BAAALAAECgYIDwAAAA==.',Ju='Juvenile:BAAALAADCgcIEwABLAAECgcIGAAUALUcAA==.',['Já']='Jáy:BAAALAAECgYIEgAAAA==.',Ka='Kaidou:BAAALAADCggIBwAAAA==.Kaleshmal:BAABLAAECoEpAAIYAAcITCBjGQBtAgAYAAcITCBjGQBtAgAAAA==.Karabela:BAAALAAECgYICgAAAA==.Kazzek:BAABLAAECoEhAAIGAAcI0xLijwClAQAGAAcI0xLijwClAQABLAAFFAMICAARAN0XAA==.',Ke='Kefiin:BAAALAAECgMIBgAAAA==.Kelari:BAABLAAECoEeAAIGAAgISSPKGgDpAgAGAAgISSPKGgDpAgABLAAFFAMICAAdABQLAA==.',Kh='Khazixx:BAAALAAECgYICgAAAA==.',Ki='Kibatachi:BAAALAADCggICAABLAAECgUICAAFAAAAAA==.Kimberlyhart:BAABLAAECoEfAAMIAAgI1BqaFQAdAgAIAAgITBqaFQAdAgATAAgIGRB3iwCkAQAAAA==.',Kl='Kloppiwhoppi:BAAALAADCgcIBwAAAA==.',Ko='Kobe:BAACLAAFFIEKAAIDAAIImiRiEgDXAAADAAIImiRiEgDXAAAsAAQKgRYAAgMACAiKH3YeAHsCAAMACAiKH3YeAHsCAAAA.Koda:BAAALAADCggIEAABLAAFFAIIAgAFAAAAAA==.Konterbîer:BAAALAADCgIIAgAAAA==.',Kr='Kranichkarl:BAAALAAECggIBQAAAA==.Krigsbroel:BAAALAAECgYIDwABLAAECggIKAAEAIUfAA==.Kripper:BAAALAADCggICAABLAAFFAIIAgAFAAAAAA==.Kruthor:BAAALAAECgQIBAAAAA==.Kräutereuter:BAABLAAECoEfAAIYAAgIYiWKBQBGAwAYAAgIYiWKBQBGAwABLAAFFAcIGgAQAMckAA==.',Ku='Kubo:BAABLAAECoEWAAMgAAcIrBZuGQCsAQAgAAcIDRRuGQCsAQAXAAYIGxcuKACOAQABLAAFFAMICAAdABQLAA==.',Ky='Kyson:BAACLAAFFIEWAAIIAAcI4Bs8AACJAgAIAAcI4Bs8AACJAgAsAAQKgRcAAggACAjwIIQLAJcCAAgACAjwIIQLAJcCAAAA.Kysu:BAAALAADCgcIBwAAAA==.Kyula:BAAALAAECgIIAgABLAAFFAQIBgAHABMPAA==.',La='Lago:BAAALAAECggICAAAAA==.Lakota:BAAALAAECgYIEAAAAA==.',Le='Leodragnos:BAAALAAECgcIBwABLAAECggICAAFAAAAAA==.Leonardru:BAAALAAECgMIAwABLAAECggICAAFAAAAAA==.',Li='Libero:BAABLAAECoEfAAIPAAgIGxNpEQAwAgAPAAgIGxNpEQAwAgAAAA==.Lileth:BAAALAAECggIEgAAAA==.Lilethhunter:BAAALAAECggIDgABLAAECggIEgAFAAAAAA==.Liliana:BAAALAAECggIDgAAAA==.Linniah:BAAALAAECgYIDgAAAA==.',Lo='Lockdown:BAAALAAECgYIDAAAAA==.Loctly:BAAALAADCggIGwAAAA==.Loráná:BAAALAAECgYIDAAAAA==.',Lu='Lucîfer:BAAALAAECgcIDwAAAA==.Lukevoked:BAAALAAECgQIBwAAAA==.Lumiron:BAAALAAECgYIEAAAAA==.Lunaréth:BAAALAAECgIIAgAAAA==.Lunera:BAAALAAECgIIAwABLAAECgcIDgAFAAAAAA==.Lutzzy:BAAALAAECgIIAgABLAAFFAIIBgAXAIUUAA==.Luzifér:BAAALAAECgMIBAABLAAFFAIIBgASAMQdAA==.Luzinde:BAABLAAECoEpAAIOAAgISB0oKQB5AgAOAAgISB0oKQB5AgAAAA==.',Ly='Lykarì:BAAALAADCgQICAABLAAECggIEgAFAAAAAA==.Lykarî:BAAALAAECggIEgAAAA==.Lyl:BAAALAAFFAIIBAAAAA==.Lynarìah:BAAALAAECggICQABLAAFFAIIBAAFAAAAAA==.Lynthara:BAAALAAECgYIDQAAAA==.Lyrai:BAAALAADCgcIBwABLAAECgYIEAAFAAAAAA==.Lysara:BAAALAADCgYICQABLAAFFAMICAAdABQLAA==.',['Lí']='Líleth:BAAALAAECgYICgABLAAECggIEgAFAAAAAA==.',['Lý']='Lýnariah:BAAALAAFFAIIAgABLAAFFAIIBAAFAAAAAA==.',Ma='Maelwen:BAAALAADCggICgABLAAECggIGQAhAKcdAA==.Maey:BAAALAAECgYIDwAAAA==.Magodestroyo:BAACLAAFFIEFAAIEAAIIpiQNIADOAAAEAAIIpiQNIADOAAAsAAQKgScAAgQACAiaJa4FAFkDAAQACAiaJa4FAFkDAAAA.Maniayaya:BAAALAADCgEIAQABLAAFFAcIGAABAOAbAA==.Maniuwu:BAACLAAFFIEYAAMBAAcI4Bs8AgB5AgABAAcIeRo8AgB5AgAJAAIIuSK2CACyAAAsAAQKgR8ABAEACAigJmEjAJUCAAEABghRJmEjAJUCAAkABQizJgEbAAQCAAoAAwh1ICkbAAUBAAAA.Marieparie:BAAALAAECggICAAAAA==.Matiebal:BAAALAAECgQIBAAAAA==.Maxitrov:BAAALAADCgYIBgAAAA==.',Me='Melchid:BAAALAADCggICAAAAA==.Melissa:BAAALAAECgUIBQAAAA==.Mellie:BAAALAAECgYIBgAAAA==.Melrinor:BAAALAAECgYIEQAAAA==.Messalina:BAABLAAECoEeAAMDAAgIvyGGDwDWAgADAAgIvyGGDwDWAgAdAAQISxOofwDtAAAAAA==.Mexro:BAAALAADCgYIBgAAAA==.',Mi='Milkaa:BAAALAADCggICAAAAA==.Miniclap:BAAALAAECgMIAwABLAAFFAIIBAAFAAAAAA==.Minxibinxi:BAABLAAECoElAAIEAAgI+hwAKgCMAgAEAAgI+hwAKgCMAgAAAA==.Mirezr:BAABLAAECoEUAAIfAAgIwhVXGwApAgAfAAgIwhVXGwApAgAAAA==.Mirezw:BAACLAAFFIEIAAIRAAMImR5yDAArAQARAAMImR5yDAArAQAsAAQKgR0AAhEACAgPJigMAC0DABEACAgPJigMAC0DAAAA.Mirion:BAAALAAECgcIBwABLAAECggIHgADAL8hAA==.Mistdevil:BAAALAADCggICAAAAA==.',Mo='Mojo:BAAALAADCggIDgAAAA==.Moodoo:BAACLAAFFIEIAAIEAAIINB7TKACoAAAEAAIINB7TKACoAAAsAAQKgRsAAgQACAh0IEAdAMoCAAQACAh0IEAdAMoCAAAA.Moodoodh:BAAALAADCgYIBgABLAAFFAIICAAEADQeAA==.Moodoodruid:BAAALAADCgQIBAABLAAFFAIICAAEADQeAA==.Moodoohunt:BAAALAAECgYIBgABLAAFFAIICAAEADQeAA==.Moodoolock:BAAALAAECgYIEgABLAAFFAIICAAEADQeAA==.Morgenkaffee:BAAALAAECgMIBgAAAA==.',Mu='Mumble:BAAALAADCggICAABLAAECgYIDAAFAAAAAA==.',My='Myanis:BAACLAAFFIEIAAIYAAIITRahFQCSAAAYAAIITRahFQCSAAAsAAQKgRwAAxgACAgoIswQAMQCABgACAgoIswQAMQCAAcAAQi4Cqi7AC4AAAAA.Myrea:BAAALAADCgYIBgABLAAFFAQIBgAHABMPAA==.Myrmidon:BAAALAADCgYIAwAAAA==.Mythmaster:BAACLAAFFIEaAAILAAcIzCUbAAAGAwALAAcIzCUbAAAGAwAsAAQKgR8AAgsACAj8IuwGAOICAAsACAj8IuwGAOICAAAA.',['Má']='Máelwen:BAAALAADCggICAABLAAECggIGQAhAKcdAA==.',['Mî']='Mîrano:BAAALAADCgUIBgAAAA==.',Na='Nairu:BAAALAAECgIIAQAAAA==.Naoe:BAAALAADCgYIBgAAAA==.Nayru:BAAALAAECgEIAQAAAA==.',Ne='Nehemia:BAABLAAECoEWAAIOAAYI6hDgmgBJAQAOAAYI6hDgmgBJAQAAAA==.Nekrogrunz:BAAALAADCgcIBwABLAAECggIHwAIANQaAA==.Nelima:BAAALAAECgMIAwAAAA==.Nerien:BAAALAADCgYIBgAAAA==.Newgate:BAAALAADCggICAAAAA==.',Ni='Nightmaree:BAAALAADCgcICwAAAA==.Niicetotem:BAAALAAECgIIAgAAAA==.',No='Nomaam:BAAALAAECgYICQAAAA==.',Nu='Nukemage:BAACLAAFFIEVAAMEAAcIsiDLAgBMAgAEAAYIHyHLAgBMAgAMAAEIIR6yBgBZAAAsAAQKgSAAAgQACAjBJlMHAEwDAAQACAjBJlMHAEwDAAAA.',Ny='Nyxaris:BAAALAADCggIEAABLAAFFAMIBgAcAFobAA==.',['Né']='Nécron:BAAALAADCgcICAAAAA==.',On='Onwu:BAACLAAFFIELAAIEAAYIAxjJCwC8AQAEAAYIAxjJCwC8AQAsAAQKgSIAAgQACAhcJAQUAP0CAAQACAhcJAQUAP0CAAAA.',Os='Osrango:BAAALAADCggICAAAAA==.',Ot='Otis:BAAALAADCggIDgAAAA==.',Pa='Paisho:BAAALAAECgcIBwAAAA==.Paper:BAAALAAECggIDgABLAAECggIBwAFAAAAAA==.Parasoma:BAABLAAECoEUAAIQAAcIAB93IABRAgAQAAcIAB93IABRAgAAAA==.Pastinake:BAABLAAECoEbAAIIAAYI6xA1NAAuAQAIAAYI6xA1NAAuAQAAAA==.Pawpatrol:BAAALAADCggICAAAAA==.',Pe='Peevi:BAAALAADCggICAAAAA==.Penumbra:BAAALAAECgYIDAAAAA==.Peppa:BAAALAAECgIIAgABLAAECgMIAwAFAAAAAA==.Percitotem:BAABLAAECoEcAAIdAAgIJCSrBwBGAwAdAAgIJCSrBwBGAwAAAA==.',Ph='Phail:BAAALAAECggIBwAAAA==.',Pi='Pi:BAAALAAECggIBAAAAA==.',Pl='Plink:BAAALAAFFAIIAgAAAA==.Plüschfeder:BAAALAADCgcIBwAAAA==.',Po='Poggerhontas:BAACLAAFFIEWAAMUAAcIFR6rAQAYAgAUAAYIzB+rAQAYAgAOAAIIMxQIIgCgAAAsAAQKgRsAAxQACAg9I/0UAKoCABQACAi1If0UAKoCAA4ABAjmI0ZwAJ8BAAAA.Poipoipoi:BAACLAAFFIEmAAMQAAgINiYEAAB8AwAQAAgINiYEAAB8AwACAAEI3AgXNgBBAAAsAAQKgSAAAhAACAjmJgpPAFUBABAACAjmJgpPAFUBAAAA.Pompom:BAABLAAECoEnAAIgAAgIVBWoGQCpAQAgAAgIVBWoGQCpAQABLAAECggIEgAFAAAAAA==.Portales:BAAALAADCggICAABLAAFFAYIEAAHAP8aAA==.Powermage:BAACLAAFFIEGAAIEAAIIdRdXLgCgAAAEAAIIdRdXLgCgAAAsAAQKgSQAAgQACAh6HqsaANcCAAQACAh6HqsaANcCAAAA.Pownyryda:BAAALAADCgIIAgAAAA==.',Pr='Prahios:BAAALAAECgYIDwAAAA==.',Pu='Pu:BAAALAAECgYIBgAAAA==.Pupa:BAAALAAECgMIAwAAAA==.Purity:BAACLAAFFIEKAAICAAMIlBnmDQD8AAACAAMIlBnmDQD8AAAsAAQKgR8AAgIACAhoHR8eAGkCAAIACAhoHR8eAGkCAAAA.',['Pô']='Pô:BAAALAAECgYICAAAAA==.',Qu='Quaderzucker:BAAALAADCgUIBQAAAA==.Quyncmepls:BAACLAAFFIEIAAIWAAIIIh3VAQC9AAAWAAIIIh3VAQC9AAAsAAQKgSYAAhYACAjTHkgDALoCABYACAjTHkgDALoCAAEsAAUUBQgVAA8A7yMA.',Ra='Radix:BAABLAAECoEmAAIBAAgI8ROkPQAUAgABAAgI8ROkPQAUAgAAAA==.',Rd='Rdruidezclap:BAAALAAFFAIIAgABLAAFFAcIGgALAMwlAA==.',Re='Redrum:BAAALAAECgcIDwABLAAECggIJQARAMAkAA==.Rey:BAAALAAECgYICQAAAA==.',Rh='Rhya:BAAALAAECgUICQAAAA==.',Ri='Risoabi:BAAALAADCggIDQABLAAFFAMIBwAYAK4dAA==.Risodh:BAAALAADCggIDQABLAAFFAMIBwAYAK4dAA==.Risodragon:BAAALAAECgcIBwABLAAFFAMIBwAYAK4dAA==.Risopala:BAAALAAECgMIAwABLAAFFAMIBwAYAK4dAA==.',Ro='Rockz:BAABLAAECoElAAIRAAgIwCRXBgBYAwARAAgIwCRXBgBYAwAAAA==.Rosalii:BAAALAADCggIFgAAAA==.',Ru='Rushi:BAAALAADCggICAAAAA==.Ruvina:BAAALAADCggIGAAAAA==.',['Rí']='Ríger:BAAALAADCgcIBwAAAA==.',['Rö']='Röllmeister:BAACLAAFFIEGAAIXAAIIhRQaDQCUAAAXAAIIhRQaDQCUAAAsAAQKgRgAAhcACAguGVsSAGICABcACAguGVsSAGICAAAA.',Sa='Sable:BAAALAADCgYICQABLAAECgYIEgAFAAAAAA==.Sadge:BAAALAAECgcIBwAAAA==.Sagâ:BAAALAAECgYIBgAAAA==.Sanya:BAAALAAECgYIDAAAAA==.',Sc='Schamatzie:BAAALAAECgcIDAAAAA==.Schimmelkäse:BAABLAAECoEdAAQBAAgIUxwTIwCXAgABAAgIMRwTIwCXAgAJAAUIygvKTgANAQAKAAIILA6+LQBsAAAAAA==.Schlafanzug:BAAALAADCggICAAAAA==.Schmatzie:BAABLAAECoEYAAMHAAcIJxSxRgCNAQAHAAYI6xaxRgCNAQAYAAUI6gzJYgDrAAAAAA==.Schwarrie:BAAALAADCggIDgAAAA==.',Se='Seb:BAAALAADCggIDgAAAA==.Sebbqq:BAACLAAFFIEZAAIQAAcIBhYHAQCEAgAQAAcIBhYHAQCEAgAsAAQKgSAAAhAACAitJSwGAEEDABAACAitJSwGAEEDAAAA.Sevíra:BAAALAAECgcIBwAAAA==.',Sh='Shabbab:BAAALAADCgcIEgAAAA==.Shaddâr:BAABLAAECoEcAAIhAAcIDyWxCADzAgAhAAcIDyWxCADzAgAAAA==.Shade:BAAALAAECgYIBgAAAA==.Shadin:BAAALAADCggIDAABLAAECgYIEAAFAAAAAA==.Shadowlulqt:BAACLAAFFIEGAAICAAIIsCLMGACvAAACAAIIsCLMGACvAAAsAAQKgRQAAwIACAhnHNUmADECAAIACAhnHNUmADECABAABAg/HptXADABAAEsAAUUBwgaAAsAzCUA.Shaggy:BAAALAAECgYIBgABLAAFFAYIFQACADIiAA==.Sheeraz:BAAALAAECgYIBgAAAA==.Shindorie:BAAALAAECgYIDAAAAA==.Shinokishi:BAAALAAECggICgABLAAFFAIIBAAFAAAAAA==.Shiver:BAAALAAECgYIEgAAAA==.Shizu:BAABLAAECoENAAIhAAcIEiCEDwCPAgAhAAcIEiCEDwCPAgABLAAFFAMICQABAAIcAA==.Shortilla:BAAALAADCggICAAAAA==.Shykitten:BAABLAAECoEZAAMhAAgIpx3kEQBzAgAhAAgIpx3kEQBzAgAEAAEIWAhQ4gAwAAAAAA==.',Si='Siari:BAAALAAECggICAAAAA==.Sin:BAAALAAECggICAAAAA==.',Sm='Smallo:BAACLAAFFIEFAAIOAAIImRf9JwCUAAAOAAIImRf9JwCUAAAsAAQKgSgAAw4ACAh/IL4dALQCAA4ACAh/IL4dALQCABQAAQimHXamAEIAAAAA.Smalloschami:BAAALAAECgcIBwAAAA==.',Sn='Snaptrap:BAAALAADCggICAAAAA==.',So='Soda:BAAALAADCgYIBgAAAA==.Solion:BAAALAADCgQIBAAAAA==.',Sp='Spekuhlatius:BAAALAAECgYIEgAAAA==.Springinkerl:BAAALAADCggICAABLAAECggIHwAIANQaAA==.Spritziges:BAAALAAFFAIIBAAAAA==.',St='Stearoid:BAAALAAECgIIAgAAAA==.Stevebruder:BAACLAAFFIEKAAMCAAMIIhv3CwAYAQACAAMIIhv3CwAYAQAQAAII5ByzEgCrAAAsAAQKgSUAAwIACAgsJS8EAEgDAAIACAgsJS8EAEgDABAACAhpHBcXAJ4CAAAA.',Su='Sukkubus:BAAALAAECgIIAgAAAA==.Sultan:BAAALAAECgYIEQAAAA==.Supername:BAABLAAECoEXAAIGAAgIQhvBTQAvAgAGAAgIQhvBTQAvAgAAAA==.',Sv='Svenes:BAAALAAECggIDQAAAA==.Svens:BAAALAAECggIDwAAAA==.',['Sî']='Sîlenceroguê:BAAALAADCgcIBwAAAA==.',Ta='Talai:BAACLAAFFIEMAAMHAAYIZBWgAwDDAQAHAAUIaxmgAwDDAQAYAAEIWQCEIgAvAAAsAAQKgR4AAgcACAjYIIoKAO0CAAcACAjYIIoKAO0CAAAA.Talaib:BAACLAAFFIERAAICAAUITRiABADPAQACAAUITRiABADPAQAsAAQKgRsAAgIACAiRIDcRAMcCAAIACAiRIDcRAMcCAAAA.Tandris:BAAALAAECgYIEAAAAA==.Tanyrra:BAAALAADCgcICwAAAA==.Tarica:BAAALAAFFAIIAgAAAA==.Tarii:BAABLAAECoEkAAIiAAgIkyIzAgAgAwAiAAgIkyIzAgAgAwAAAA==.Tasatulos:BAAALAADCggICAABLAAFFAMICAARAN0XAA==.',Te='Telira:BAABLAAECoEgAAITAAgIKh8cKACsAgATAAgIKh8cKACsAgAAAA==.Telrok:BAAALAAECgYIDAAAAA==.Temlin:BAAALAAECgQICQABLAAECgUICAAFAAAAAA==.Terellia:BAAALAADCgQIBAAAAA==.Teshka:BAAALAADCgcIBwABLAAECggIJAAaAGcXAA==.Tess:BAAALAAECggIAQAAAA==.Testeros:BAAALAAECggICAAAAA==.Teuton:BAAALAAECgcIDwAAAA==.',Th='Thalinor:BAABLAAECoEVAAMLAAYIqR18HwDoAQALAAYIqR18HwDoAQAIAAEICxTGXAA8AAABLAAFFAMICAAdABQLAA==.Theodar:BAAALAAECgYIDQAAAA==.Thulu:BAACLAAFFIEVAAMPAAUI7yNWAAAPAgAPAAUI7yNWAAAPAgAGAAUI2hg7CgChAQAsAAQKgRoAAw8ACAh/JRsNAGwCAA8ABgikJRsNAGwCAAYABwgiJP9QACcCAAAA.',Ti='Tiata:BAACLAAFFIEGAAIHAAQIEw9VCAAeAQAHAAQIEw9VCAAeAQAsAAQKgSYAAxgACAjUIU4SALQCABgABwhSIU4SALQCAAcACAhYEQ1CAKABAAAA.',To='Toasbi:BAAALAADCgYIAwAAAA==.Todie:BAABLAAECoE2AAITAAgINyXgBwBZAwATAAgINyXgBwBZAwAAAA==.Tohrú:BAAALAAECgcIDAAAAA==.Tokki:BAAALAADCggIDgAAAA==.Totemtommy:BAAALAAECgQIBgAAAA==.Totenkill:BAAALAADCgYIBgAAAA==.',Tr='Treffsicher:BAABLAAECoE0AAIOAAgIdRGEbgCjAQAOAAgIdRGEbgCjAQAAAA==.',Ts='Tschigerillo:BAACLAAFFIEIAAIjAAIIVSDAAQDBAAAjAAIIVSDAAQDBAAAsAAQKgRsAAiMACAiTHjgEAMoCACMACAiTHjgEAMoCAAEsAAUUBwgZABAABhYA.',Tv='Tvknòchèn:BAAALAAECggIEQAAAA==.',Ty='Tyyrael:BAAALAAECgYICgABLAAECgYICgAFAAAAAA==.',['Tì']='Tìra:BAABLAAECoEXAAIXAAgIXhtUDwCJAgAXAAgIXhtUDwCJAgAAAA==.',Un='Unterhemd:BAAALAADCgcIBwAAAA==.',Va='Vaeliz:BAABLAAECoEUAAIHAAQIsx5qWgBGAQAHAAQIsx5qWgBGAQAAAA==.Vaeniel:BAAALAAECgYIBgAAAA==.Valma:BAAALAAECgQIDwAAAA==.Vampirherz:BAAALAAFFAIIAgAAAA==.',Ve='Verathiell:BAAALAAECgYICQABLAAECgYICgAFAAAAAA==.Verflucht:BAAALAAECgUIBQAAAA==.Verrottete:BAAALAAFFAMIAwABLAAFFAcIIQASAIEjAA==.Vesrin:BAAALAAFFAEIAQAAAA==.',Vi='Violyna:BAAALAAECgYIDAAAAA==.Vivace:BAAALAAECgcIDgAAAA==.',Vo='Voidlady:BAAALAADCgYIBgAAAA==.Volltroll:BAAALAADCgcIDgAAAA==.',Vu='Vulperaa:BAAALAADCgYIBgABLAAECgcIBwAFAAAAAA==.',['Ví']='Víolett:BAABLAAECoEkAAMHAAgIlBtjFgCEAgAHAAgIlBtjFgCEAgAYAAYIPgyWZwDRAAAAAA==.',Wi='Windspiel:BAACLAAFFIEIAAICAAMIrQwjEgDcAAACAAMIrQwjEgDcAAAsAAQKgTIAAgIACAiDHnASALwCAAIACAiDHnASALwCAAAA.Wintherr:BAAALAAECgIIAgAAAA==.',Wo='Wolverknight:BAACLAAFFIEaAAIQAAcIxyRgAADmAgAQAAcIxyRgAADmAgAsAAQKgRkAAhAACAivJQkIAC0DABAACAivJQkIAC0DAAAA.Woses:BAAALAAFFAIIBAAAAA==.',Xa='Xaayah:BAAALAADCggICAABLAAECgYICgAFAAAAAA==.Xarul:BAAALAAECgMIAwAAAA==.',Xe='Xeo:BAAALAADCgIIAgAAAA==.',Xh='Xhandril:BAAALAAECgcIEQAAAA==.',Xo='Xoljun:BAAALAAECgYIBgAAAA==.',Xu='Xuu:BAAALAAECgYIDAAAAQ==.',Xy='Xylestia:BAAALAAECgcIBwAAAA==.',Ya='Yadana:BAAALAAECgMIAwAAAA==.',Ye='Yeji:BAAALAADCgYIBwAAAA==.',Yi='Yin:BAACLAAFFIEIAAIEAAIIKhmyPACPAAAEAAIIKhmyPACPAAAsAAQKgR8AAgQABwjsH2sjAKsCAAQABwjsH2sjAKsCAAAA.',Ys='Ysaria:BAAALAAECggIEwAAAA==.',Yu='Yunasneak:BAABLAAFFIEOAAIfAAUIkRevAQDZAQAfAAUIkRevAQDZAQABLAAFFAcIFgASAPQYAA==.Yunawar:BAABLAAFFIELAAIRAAUIAhGFCACqAQARAAUIAhGFCACqAQABLAAFFAcIFgASAPQYAA==.',Yv='Yvenne:BAAALAAECggICwABLAAFFAUIEgABAC0WAA==.',Za='Zaia:BAABLAAECoEVAAIGAAgIkBT+eQDNAQAGAAgIkBT+eQDNAQABLAAFFAMIBwALAGUSAA==.Zarona:BAAALAADCggIIAAAAA==.Zasha:BAAALAADCgYICgABLAAECggIJAAaAGcXAA==.',Ze='Zeratul:BAAALAADCgYIBgAAAA==.Zeronos:BAABLAAECoEVAAMkAAcIYRPrCADZAQAkAAcIYRPrCADZAQAfAAEIQg1VYwA+AAAAAA==.Zerrac:BAAALAAECggICAAAAA==.Zeyzan:BAAALAAECgQIBAAAAA==.',Zi='Ziehrandor:BAACLAAFFIEKAAIaAAYI9RGTAgDFAQAaAAYI9RGTAgDFAQAsAAQKgRUAAhoACAisG4sMAFsCABoACAisG4sMAFsCAAAA.Zirkuskanone:BAABLAAECoEbAAIBAAgIpBd8NAA8AgABAAgIpBd8NAA8AgAAAA==.Zix:BAAALAAECgUIBQAAAA==.',Zo='Zomboss:BAAALAAECgIIBAAAAA==.',Zu='Zulsaframano:BAABLAAECoEeAAMSAAgINhCKbgC8AQASAAgIvQ+KbgC8AQAcAAMIqw0cRgCCAAAAAA==.',Zw='Zwombie:BAAALAAECgEIAQAAAA==.Zwoses:BAACLAAFFIEIAAIUAAMI1h5dCQAcAQAUAAMI1h5dCQAcAQAsAAQKgSsAAhQACAi3JP0CAFcDABQACAi3JP0CAFcDAAAA.',Zx='Zx:BAAALAADCgMIAwABLAAFFAcIGAAgAD4XAA==.',Zy='Zyko:BAAALAAECgUICAAAAA==.Zynthoaa:BAABLAAECoEoAAIEAAgIhR8tHADQAgAEAAgIhR8tHADQAgAAAA==.Zypsilon:BAAALAAECggICAAAAA==.Zyx:BAABLAAECoEiAAMDAAgIfBoeKABOAgADAAcINh4eKABOAgAdAAEIZQD7ugAGAAAAAA==.',['Às']='Àshara:BAAALAADCgYIBgABLAAECggIGQAhAKcdAA==.',['Æz']='Æzrael:BAAALAADCgIIAgAAAA==.',['Ín']='Ínnos:BAABLAAECoEXAAIIAAYIRxKhMQA+AQAIAAYIRxKhMQA+AQAAAA==.',['Ød']='Ødin:BAAALAAECgYIBgABLAAFFAMICQABAAIcAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end