local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Unknown-Unknown','Shaman-Elemental','Evoker-Preservation','Evoker-Augmentation','Evoker-Devastation','Mage-Arcane','Mage-Frost','Priest-Holy','Priest-Shadow','Warrior-Protection','Paladin-Retribution','Priest-Discipline','Hunter-BeastMastery','Druid-Feral','Monk-Brewmaster','Monk-Windwalker','Paladin-Holy','Warlock-Demonology','DeathKnight-Frost','DeathKnight-Blood','Shaman-Restoration','Druid-Guardian','DeathKnight-Unholy','Warrior-Fury','Warlock-Destruction','Shaman-Enhancement','Rogue-Subtlety','Rogue-Assassination','Hunter-Marksmanship','DemonHunter-Havoc','Druid-Balance','Druid-Restoration','Paladin-Protection','Monk-Mistweaver','Warlock-Affliction','Hunter-Survival','Warrior-Arms',}; local provider = {region='EU',realm='Kilrogg',name='EU',type='weekly',zone=44,date='2025-09-22',data={Aa='Aapjé:BAAALAADCgIIAgAAAA==.',Ae='Aerowynn:BAAALAADCggIDQABLAAECgUICwABAAAAAA==.Aesha:BAAALAADCggIGwAAAA==.Aestas:BAACLAAFFIEJAAICAAMIQhW+DgD1AAACAAMIQhW+DgD1AAAsAAQKgSoAAgIACAhdIwoKAC0DAAIACAhdIwoKAC0DAAAA.Aeína:BAAALAAECgUIBQAAAA==.',Ag='Agamur:BAAALAAECgYICQAAAA==.',Ak='Akio:BAAALAADCggIBAAAAA==.Akxu:BAAALAADCggIGwAAAA==.',Al='Alchydragon:BAACLAAFFIEPAAMDAAUImRyYAwCfAQADAAQIlB+YAwCfAQAEAAEIBgNFBwBLAAAsAAQKgSUABAQACAj+IKkCALMCAAQABwgxIqkCALMCAAMACAi+H10GALICAAUABggoHYYkANEBAAAA.Alderhey:BAAALAADCggIGwAAAA==.Alexandría:BAAALAAECgcIDwAAAA==.Algysmiter:BAAALAAECgMIAwAAAA==.Alisia:BAABLAAECoEWAAMGAAcIGxVZVADhAQAGAAcIGxVZVADhAQAHAAEILQj0fgAwAAABLAAECggIIAACAHsaAA==.Alphaxsara:BAAALAAECgEIAQAAAA==.Alt:BAAALAAECggIEgAAAA==.',Am='Ambergold:BAAALAADCgIIAQAAAA==.Amberiron:BAAALAADCgcIDgAAAA==.',An='Angelsspy:BAABLAAECoEeAAIIAAgI2RYVJQA2AgAIAAgI2RYVJQA2AgAAAA==.Angrymanny:BAAALAAFFAIIBAAAAA==.Anoia:BAAALAADCgYIBgABLAAECggIEwABAAAAAA==.Anunnak:BAABLAAECoEWAAIJAAgIoRkeGACQAgAJAAgIoRkeGACQAgAAAA==.',Ap='Apollyon:BAAALAAECggIEAAAAA==.',Ar='Ardarathyn:BAAALAADCgIIAgAAAA==.Aredhel:BAAALAADCgcIBwAAAA==.Argessos:BAAALAADCggICAABLAAECggIJAAKADwcAA==.Arkar:BAAALAAECgQIBAAAAA==.Arthuría:BAAALAAECggIEAABLAAECggIGwAGAIQZAA==.Artog:BAABLAAECoEaAAILAAgIQSDwHADdAgALAAgIQSDwHADdAgAAAA==.Arzira:BAABLAAECoEeAAMJAAgIXCQFDQD6AgAJAAcIZyUFDQD6AgAMAAEIYB3RKQBXAAAAAA==.',As='Astynaxx:BAAALAAECgEIAQAAAA==.',Aw='Awwawawaa:BAAALAADCggICgAAAA==.',Ba='Baas:BAABLAAECoEaAAINAAcIawzJgwBpAQANAAcIawzJgwBpAQAAAA==.Baeldh:BAAALAAECgUICgAAAA==.Barbaboris:BAAALAADCggICAAAAA==.Barbapapa:BAAALAADCggIFgABLAAECggIGgAOAIcdAA==.Bargush:BAAALAADCggIGwAAAA==.',Be='Bearrelroll:BAABLAAECoEcAAMPAAgI/Rt6CwB2AgAPAAgI/Rt6CwB2AgAQAAEISxuNVAA+AAAAAA==.Beduinne:BAAALAAECgYIBgAAAA==.Beelzeboss:BAAALAADCgMIAwAAAA==.Beeple:BAAALAADCgcIDgAAAA==.Beerbear:BAAALAADCgEIAQABLAAECggIGgAOAIcdAA==.Belenus:BAAALAADCggICAAAAA==.Beltane:BAAALAAECggIEAAAAA==.Bennythedog:BAAALAAECggIEAAAAA==.Beovar:BAAALAADCggICAAAAA==.',Bh='Bholadin:BAAALAADCgcIBwAAAA==.',Bi='Bigslappah:BAABLAAECoEVAAIRAAgI2BKHHQDxAQARAAgI2BKHHQDxAQAAAA==.Biscuit:BAAALAADCgQIBAABLAAECggIFwASAAkOAA==.',Bl='Blackgte:BAAALAAECgEIAQAAAA==.Blasphemysin:BAAALAADCggICAAAAA==.Blinder:BAAALAAECgIIAgAAAA==.Blindnotdeaf:BAAALAAECgEIAQAAAA==.Bloodypluto:BAACLAAFFIEIAAMTAAIIkyFeIAC9AAATAAIIkyFeIAC9AAAUAAEIWgvfDwA/AAAsAAQKgRoAAhMACAjEJNEGAFYDABMACAjEJNEGAFYDAAEsAAUUAggKABUAbiMA.Bloodyshamy:BAAALAAECgYIBwABLAAECggIHAATAPMTAA==.Bluedevils:BAAALAAECgIIAgAAAA==.',Bo='Boijlemus:BAAALAAECgQICAABLAAFFAUICwANACUMAA==.',Br='Bramm:BAAALAADCggIGgAAAA==.',Bu='Bumbi:BAAALAAECgYIDAAAAA==.Burningtusk:BAAALAAECgYIEwAAAA==.Burrata:BAAALAADCgcIBwABLAAECgcIHAAWAOEgAA==.',['Bä']='Bästipräst:BAAALAADCgUIBQAAAA==.',['Bé']='Béren:BAAALAADCggIDwAAAA==.',['Bú']='Búnny:BAAALAAECgIIAgAAAA==.',Ca='Calidore:BAAALAAECgEIAgAAAA==.Camembert:BAAALAADCggICAABLAAECgcIHAAWAOEgAA==.Canofkimchi:BAAALAAECgYIDQABLAAFFAMICQATAMQgAA==.Canofundeath:BAACLAAFFIEJAAMTAAMIxCCUDwAkAQATAAMI9R+UDwAkAQAXAAEIZyJLEwBdAAAsAAQKgTcAAxMACAi7Jb4EAGYDABMACAi7Jb4EAGYDABcABQgWIS8dALUBAAAA.Carnius:BAACLAAFFIEKAAIYAAMI1RbmEADwAAAYAAMI1RbmEADwAAAsAAQKgSoAAhgACAg2IY8UAOkCABgACAg2IY8UAOkCAAAA.Casseopeia:BAAALAADCgcIBwAAAA==.Casty:BAAALAAECgcIDgAAAA==.Cataloko:BAABLAAECoEWAAMZAAcI+QasfQBEAQAZAAcI+QasfQBEAQASAAMIhgGffQBFAAAAAA==.Catmaddead:BAAALAAECgMIBQAAAA==.Catzhin:BAAALAAECgIIAgAAAA==.',Ce='Cervisia:BAAALAAECgEIAQAAAA==.',Ch='Chaosdemon:BAAALAADCgYIBgABLAAECgUICgABAAAAAA==.Chaosdev:BAAALAADCgcICAAAAA==.Chelinka:BAAALAADCggICAAAAA==.Chinpettum:BAACLAAFFIEKAAILAAMILBwTCwAUAQALAAMILBwTCwAUAQAsAAQKgSwAAgsACAgSJXkLAEADAAsACAgSJXkLAEADAAAA.Chipps:BAAALAAECgIIAgAAAA==.Chockbolt:BAAALAADCgcIDgAAAA==.Chrysophylax:BAAALAADCgYIBgAAAA==.Chuckleflux:BAAALAADCgYIBgAAAA==.',Ci='Ciganka:BAAALAADCggICAAAAA==.',Co='Colin:BAAALAAECgYIEwAAAA==.Consensus:BAAALAADCggIAgAAAA==.Convictura:BAAALAADCgUIBQABLAAECggIFQARANgSAA==.Core:BAAALAADCggIDgAAAA==.',Cr='Crazyunicorn:BAAALAADCggICAABLAADCggIEAABAAAAAA==.Credeex:BAAALAAECggIEAAAAA==.Cruul:BAABLAAECoEUAAIaAAYIDgePGAAkAQAaAAYIDgePGAAkAQAAAA==.Cry:BAAALAAECggIAwAAAA==.Cryptic:BAAALAADCggIDwAAAA==.Cryptum:BAABLAAECoEaAAIUAAcIbhFuHABkAQAUAAcIbhFuHABkAQAAAA==.',Da='Daarlinfa:BAEALAADCggICAABLAAECggIDwABAAAAAA==.Daenarr:BAABLAAECoEaAAIFAAcIcg4WLACYAQAFAAcIcg4WLACYAQAAAA==.Dak:BAABLAAECoEbAAIQAAcIOBqLGAATAgAQAAcIOBqLGAATAgAAAA==.Daka:BAAALAADCggICAAAAA==.Darekamadore:BAABLAAECoEhAAIOAAgIzBg0DQBQAgAOAAgIzBg0DQBQAgAAAA==.Darkangle:BAAALAAECgEIAQAAAA==.Darkirón:BAAALAADCggIGwAAAA==.Darkpríést:BAAALAADCgcIBwAAAA==.Darkro:BAAALAAECggIEQAAAA==.Dazba:BAABLAAECoEVAAMbAAcI/w0xHQB4AQAbAAcIYQwxHQB4AQAcAAYIjgvsOgBWAQAAAA==.',De='Deathshotee:BAABLAAECoEbAAMdAAgIFR4jEwC1AgAdAAgIFR4jEwC1AgANAAEICh84/ABJAAAAAA==.Deathshotz:BAAALAAECgYIBgABLAAECgYIBgABAAAAAA==.Deemose:BAAALAADCggIEgAAAA==.Deleted:BAAALAADCgEIAQAAAA==.Deliriouscat:BAAALAAFFAIIAgAAAA==.Demonikel:BAABLAAECoEUAAIZAAcIZQVShgAsAQAZAAcIZQVShgAsAQAAAA==.Demonishida:BAAALAAECgYIBgAAAA==.Demonià:BAABLAAECoEhAAIeAAgIeCE7FAACAwAeAAgIeCE7FAACAwAAAA==.Desmo:BAAALAADCggIEgAAAA==.Destructo:BAAALAADCgcIBAAAAA==.Devs:BAAALAAECgYIDQAAAA==.',Di='Diaboloz:BAABLAAECoEkAAIeAAgIAiMQEAAbAwAeAAgIAiMQEAAbAwAAAA==.Dicolfenac:BAACLAAFFIESAAILAAUImhn4AwDYAQALAAUImhn4AwDYAQAsAAQKgS0AAgsACAheJlQBAI4DAAsACAheJlQBAI4DAAAA.Digitalmage:BAAALAAECggICAAAAA==.Digitalsiner:BAAALAAECggICAAAAA==.',Do='Dogshi:BAABLAAECoEYAAIQAAcIzBH4JQCYAQAQAAcIzBH4JQCYAQAAAA==.Donmakaveli:BAAALAAECgYIBgAAAA==.Doomscale:BAAALAADCgUIBQAAAA==.',Dr='Dracken:BAABLAAECoEkAAIKAAgIPBz1EACCAgAKAAgIPBz1EACCAgAAAA==.Dragonnio:BAAALAADCggIEAAAAA==.Dribblee:BAAALAAECgQIBAAAAA==.Drinkers:BAAALAADCggICAAAAA==.Dritte:BAAALAADCggICAAAAA==.Drkzippy:BAAALAAECgYIDQAAAA==.Drutheid:BAAALAADCgUIBQAAAA==.',Du='Dunedain:BAABLAAECoEXAAIeAAgI3hCzVgDuAQAeAAgI3hCzVgDuAQAAAA==.Durup:BAAALAAECgMIBgABLAAECggIJgAQAFQcAA==.Duryp:BAAALAADCggIEgABLAAECggIJgAQAFQcAA==.',Dw='Dwen:BAAALAADCgcIBwAAAA==.',Dy='Dylla:BAAALAAECggICgAAAA==.',['Dö']='Dödsängeln:BAAALAAECgQIBgAAAA==.',Ec='Eclipsis:BAAALAADCggICAAAAA==.',Ed='Edgarous:BAAALAADCggICAAAAA==.',El='Elaryn:BAAALAADCgYIBgAAAA==.Elicka:BAAALAAECgIIAgAAAA==.Elithandrea:BAEALAADCggICAABLAAECggIDwABAAAAAA==.Ellienne:BAAALAAECgUIBQAAAA==.Elondai:BAAALAADCggICAAAAA==.Elylaya:BAAALAADCggIDwAAAA==.',Em='Emeraldz:BAAALAADCggICwAAAA==.Emlaiah:BAAALAAECgcIDQAAAA==.Emmilly:BAAALAADCgIIAgABLAAFFAIICgAVAG4jAA==.Emriana:BAABLAAECoEZAAIGAAcIshFZWgDOAQAGAAcIshFZWgDOAQAAAA==.',Er='Erîs:BAAALAAECgYIBgABLAAFFAUIDwAVAMUTAA==.',Et='Eternaldraco:BAAALAAECgUICgAAAA==.',Ev='Evelynne:BAAALAAECgIIAgAAAA==.Evince:BAABLAAECoEXAAIIAAgIthSGKwATAgAIAAgIthSGKwATAgAAAA==.',Fa='Faction:BAAALAADCgcICQAAAA==.Faldri:BAABLAAECoElAAITAAgIjhKSZwDsAQATAAgIjhKSZwDsAQAAAA==.Farferifromp:BAAALAADCgIIAgAAAA==.Farlie:BAAALAAECgcIBwAAAA==.Faromier:BAAALAAECgcICwABLAAFFAIIBgAUANYVAA==.Fartconjurer:BAAALAADCggIDwABLAAECgcIGwAGADQgAA==.',Fe='Feero:BAAALAADCgYIBgAAAA==.Felam:BAAALAAFFAIIAgAAAA==.Feldiir:BAAALAAECgYIEAAAAA==.Fenrîr:BAAALAADCggIEQAAAA==.',Fi='Figuras:BAAALAAECggICAABLAAECggIJAAKADwcAA==.Fizzlock:BAABLAAECoEXAAIHAAcIPRtdGQAlAgAHAAcIPRtdGQAlAgAAAA==.',Fj='Fjærlokt:BAACLAAFFIELAAMNAAUIJQwqDgAEAQANAAQI+g4qDgAEAQAdAAIIwgERJgBoAAAsAAQKgSAAAw0ACAi9HHYxAEwCAA0ACAgsG3YxAEwCAB0ABwgeGuk4ALkBAAAA.',Fl='Flameofpast:BAABLAAECoEcAAIUAAcI3A6jHQBWAQAUAAcI3A6jHQBWAQAAAA==.Flar:BAAALAADCggICAAAAA==.Flaxxiz:BAACLAAFFIEKAAILAAIIlR6SHQCuAAALAAIIlR6SHQCuAAAsAAQKgSUAAgsACAgeH305AGACAAsACAgeH305AGACAAAA.Floorkiki:BAAALAADCggICQAAAA==.',Fr='Frazyl:BAAALAAECgYICgAAAA==.Freezepop:BAAALAAECgYIEwAAAA==.Frozenpea:BAABLAAECoEaAAMGAAcIgxCgaQChAQAGAAcIAw6gaQChAQAHAAYIPg42QgA7AQAAAA==.',Fu='Fufuro:BAAALAAECgYIBgABLAAECgUICwABAAAAAA==.Furri:BAAALAADCgYIBgAAAA==.',Ga='Gabbyjay:BAAALAADCgQIBAAAAA==.Gaiaa:BAAALAADCggICAAAAA==.Gatamephydi:BAAALAADCgYICAAAAA==.Gazuz:BAAALAAECgUIBgAAAA==.',Ge='Genormica:BAAALAAECgIIBAABLAAECggIGwAeAOkfAA==.Georgino:BAACLAAFFIEIAAIGAAIIHhahKwCfAAAGAAIIHhahKwCfAAAsAAQKgSkAAgYACAjLIhILAC4DAAYACAjLIhILAC4DAAAA.',Gi='Gilbért:BAABLAAECoEbAAIGAAgIhBn6NwBFAgAGAAgIhBn6NwBFAgAAAA==.Gimmedat:BAAALAAECgEIAQAAAA==.',Gl='Glendracthyr:BAAALAADCgQIBAAAAA==.Glenlock:BAAALAADCggIFQAAAA==.Glissov:BAABLAAECoEWAAILAAgI4gi+rQBdAQALAAgI4gi+rQBdAQAAAA==.Glycera:BAABLAAECoEWAAITAAgIuBJKZQDxAQATAAgIuBJKZQDxAQAAAA==.',Gn='Gnomega:BAAALAADCgcIDAAAAA==.',Go='Goedemorgen:BAABLAAECoEeAAIYAAcIxB28JgBwAgAYAAcIxB28JgBwAgAAAA==.Gonzo:BAAALAADCgIIAgAAAA==.',Gr='Grevän:BAAALAAECgQICgABLAAECgYIBgABAAAAAA==.Grimlaar:BAAALAAECggICQAAAA==.Grombrindal:BAAALAADCggIDQABLAAECgEIAQABAAAAAA==.Grunit:BAABLAAECoEUAAIYAAcI+QyHYACLAQAYAAcI+QyHYACLAQAAAA==.',Gu='Guffman:BAABLAAECoEbAAIGAAcINCDFJQCaAgAGAAcINCDFJQCaAgAAAA==.Gumielock:BAAALAAECgUIBgAAAA==.',Gz='Gzus:BAAALAAECgcIEgAAAA==.',['Gá']='Gándal:BAAALAADCggICAAAAA==.',['Gì']='Gìblet:BAABLAAECoEgAAQfAAgIHxVmJgADAgAfAAgIHxVmJgADAgAgAAQI1AjDkACZAAAWAAEIoAHLLwAXAAAAAA==.',['Gí']='Gílan:BAAALAAECgQIBAABLAAECggIGwAGAIQZAA==.',Ha='Haborym:BAAALAAECgYIBgABLAAECggIIgAZAHEYAA==.Hairydragon:BAAALAAECgYIBgAAAA==.Hanaki:BAAALAADCgUIBQAAAA==.Hardwork:BAAALAAECgYICwABLAAECgYIEwABAAAAAA==.Hauktuah:BAAALAADCggIEAAAAA==.Hayfire:BAACLAAFFIEVAAIhAAYI/CQwAACSAgAhAAYI/CQwAACSAgAsAAQKgS8AAiEACAjxJhMAAKQDACEACAjxJhMAAKQDAAAA.Hazaio:BAABLAAECoEcAAMhAAgIXh2VCQCyAgAhAAgIXh2VCQCyAgALAAIIzgUAHQFgAAAAAA==.',He='Healz:BAAALAAECgIIAgAAAA==.Heikè:BAAALAADCgMIBQAAAA==.Hellspeaker:BAABLAAECoEXAAIeAAgINCFyEwAHAwAeAAgINCFyEwAHAwAAAA==.Herbadurb:BAAALAADCgIIAgAAAA==.',Ho='Holiestgoat:BAAALAAECgcIEgAAAA==.Holynoodle:BAABLAAECoEdAAIIAAYI1BITVQBZAQAIAAYI1BITVQBZAQABLAAFFAMICQANAJMjAA==.Holynoodles:BAAALAADCggIAQAAAA==.Honeyzapper:BAAALAAECgYIBgAAAA==.Hopsaké:BAAALAAECgYICwAAAA==.',Hu='Huanglong:BAAALAADCggIDAAAAA==.Huna:BAAALAAECgMIBAABLAAECgcIDQABAAAAAA==.Hunnah:BAAALAADCggICAABLAAECggILAAVAGMlAA==.',Hy='Hyoro:BAAALAAECgQICQAAAA==.',Ic='Icezje:BAAALAADCgEIAQAAAA==.',Ih='Ihealyoustfu:BAAALAADCggICQAAAA==.',Il='Ilmr:BAAALAADCggIGgAAAA==.Ilonius:BAABLAAECoEZAAILAAcIvBwtOgBeAgALAAcIvBwtOgBeAgAAAA==.',Im='Impassive:BAAALAADCgIIAgAAAA==.',In='Inkki:BAABLAAECoEaAAIOAAgIhx3VBwC5AgAOAAgIhx3VBwC5AgAAAA==.',Iq='Iqrugoc:BAACLAAFFIESAAMIAAYIhhCMAgD6AQAIAAYIhhCMAgD6AQAMAAIIfw2DAgCDAAAsAAQKgScAAwgACAiSIEsLAPkCAAgACAiSIEsLAPkCAAwACAjeFcEGACICAAAA.',Ir='Ironward:BAAALAADCgcIBwAAAA==.',Is='Isekaied:BAAALAADCggICAAAAA==.',It='Itouchbutts:BAABLAAECoEaAAIHAAcIRwb3QwAzAQAHAAcIRwb3QwAzAQAAAA==.',Iy='Iyona:BAAALAAECgEIAQAAAA==.',Ja='Jacla:BAAALAAECggICAAAAA==.Janisa:BAAALAADCgYIBgAAAA==.Jaxom:BAABLAAECoEYAAITAAgITA8fgwC1AQATAAgITA8fgwC1AQAAAA==.Jaybear:BAAALAAECgEIAQAAAA==.',Je='Jelsen:BAAALAADCgMIAwAAAA==.',Ji='Jinori:BAACLAAFFIEUAAIiAAYIEA83AgDcAQAiAAYIEA83AgDcAQAsAAQKgS8AAiIACAh0HkEIAMACACIACAh0HkEIAMACAAAA.',Ka='Kadae:BAABLAAECoEgAAIJAAgIBA22NwC9AQAJAAgIBA22NwC9AQAAAA==.Kadatonic:BAAALAAECgYIDQAAAA==.Kaelira:BAAALAADCggIDAAAAA==.Kairó:BAAALAAECgYIAgAAAA==.Kak:BAAALAAECgYIBgAAAA==.Kalaris:BAABLAAECoEUAAIeAAYItRTicwCoAQAeAAYItRTicwCoAQAAAA==.Kaljanalle:BAAALAADCggICAABLAAECgcIGQALAJkXAA==.Karidk:BAAALAAECgUIBQAAAA==.Karlito:BAAALAAECgEIAQAAAA==.Karlorg:BAAALAADCggICAAAAA==.Kastalia:BAAALAADCgYIDAAAAA==.Kat:BAAALAAECgcIEQAAAA==.Katzen:BAAALAAECgYIDQAAAA==.',Ke='Keaton:BAAALAADCgIIAQAAAA==.Keatonn:BAABLAAECoEhAAITAAYILBzpYgD3AQATAAYILBzpYgD3AQAAAA==.Kelpy:BAAALAAECgQICAAAAA==.Ketaminee:BAAALAAECgYIDAAAAA==.Ketaya:BAAALAADCggICAAAAA==.',Ki='Kiingslayeer:BAAALAADCggICAAAAA==.Killthemoon:BAAALAAFFAIIBAABLAAFFAIICgAVAG4jAA==.Kinich:BAAALAADCgMIAwABLAAECggIJgAQAFQcAA==.Kittslayer:BAAALAADCgIIAgABLAAFFAUIDgAiAPQdAA==.',Kn='Knugwup:BAAALAAECgcICwAAAA==.',Ko='Kochanie:BAAALAAECgYIEwAAAA==.Korphite:BAAALAADCgMIAwAAAA==.Kovok:BAAALAADCggICAAAAA==.',Ku='Kungfupanda:BAAALAADCggICAABLAAECgMIBQABAAAAAA==.Kurecutie:BAACLAAFFIEGAAMjAAIILh+eAQC8AAAjAAIILh+eAQC8AAAZAAEInhZ6OwBTAAAsAAQKgR0AAyMACAhvJN4AAFoDACMACAhvJN4AAFoDABkABAgMDM6dAOAAAAAA.Kurenai:BAAALAADCggICAAAAA==.Kurrewix:BAAALAADCgEIAQAAAA==.',Ky='Kysho:BAAALAADCgUIBQABLAADCgcIBQABAAAAAA==.',['Ká']='Kátzchén:BAAALAADCggICAAAAA==.',La='Laivinë:BAAALAAECgEIAQAAAA==.Laskenblock:BAAALAADCgUIBgAAAA==.Laskendog:BAAALAAECgYICAAAAA==.Layza:BAAALAADCggIDgAAAA==.Lazer:BAAALAADCggICAAAAA==.Lazoroth:BAEBLAAECoEfAAIGAAgIBhNKSQAFAgAGAAgIBhNKSQAFAgAAAA==.',Le='Leasha:BAAALAADCggIFQAAAA==.Lefa:BAABLAAECoEdAAIgAAgItRepLAD5AQAgAAgItRepLAD5AQAAAA==.Leisheng:BAAALAADCggIGwAAAA==.Lelani:BAAALAAECgYIBgABLAAECggICwABAAAAAA==.Lemonhazé:BAAALAAECgYIDgABLAAECgYIEwABAAAAAA==.Leopardhajen:BAAALAADCggICAAAAA==.Leorian:BAAALAADCgYICAAAAA==.Lerrix:BAAALAAFFAIIAgABLAAFFAIICgALAJUeAA==.Lesare:BAAALAADCgEIAQAAAA==.Levyn:BAAALAAECgIIAgAAAA==.Leyani:BAAALAADCggIEAAAAA==.',Li='Lidlridl:BAAALAADCggICAAAAA==.Lightknight:BAABLAAECoEZAAMRAAgILRHKKAChAQARAAcIBRPKKAChAQALAAIIOwMLQgEiAAAAAA==.Lilagony:BAAALAADCgYIBgAAAA==.Lillhuntz:BAAALAAECggIBQAAAA==.Lilskywlock:BAAALAADCgYIBgAAAA==.',Lo='Loaf:BAAALAAECgcIBgAAAA==.Lockielok:BAAALAADCggIFgAAAA==.Logari:BAAALAAECgIIAgAAAA==.Loudness:BAAALAADCgYIBgAAAA==.',Lu='Luciian:BAAALAADCgcIGwABLAAECgYIEAABAAAAAA==.Lumaron:BAAALAADCgcIBwABLAAECgEIAQABAAAAAA==.Lumineira:BAABLAAECoEZAAIQAAgI3RSdFwAcAgAQAAgI3RSdFwAcAgAAAA==.',['Lï']='Lï:BAABLAAECoEmAAMQAAgIVBzaDgCKAgAQAAgI/BvaDgCKAgAPAAcIlRrBEQALAgAAAA==.',['Lú']='Lúisa:BAAALAADCgUIAwAAAA==.',Ma='Maaza:BAAALAAECgYIBgABLAAFFAIICgALAJUeAA==.Mabs:BAAALAAFFAMIAwAAAA==.Magenex:BAAALAAECggIEQAAAA==.Magnox:BAACLAAFFIEFAAIGAAIIKhg5LQCdAAAGAAIIKhg5LQCdAAAsAAQKgSQAAwYACAjKIwQbANECAAYACAiiIAQbANECAAcABwj+IYkVAEgCAAEsAAQKCAgIAAEAAAAA.Magtoral:BAAALAAECgIIAgAAAA==.Mahboi:BAAALAADCgYICwAAAA==.Maime:BAAALAADCggIDgAAAA==.Majic:BAABLAAECoEVAAIHAAgICx/eCwC6AgAHAAgICx/eCwC6AgAAAA==.Malftruistic:BAAALAADCgUIBQABLAADCggICAABAAAAAA==.Manapause:BAAALAADCgEIAQAAAA==.Manight:BAAALAAECgQIBwAAAA==.Mardoosh:BAAALAAECgYIDAAAAA==.Maryboppins:BAAALAADCggICQAAAA==.Maxiepriest:BAABLAAECoEgAAIJAAgIchpIGACOAgAJAAgIchpIGACOAgAAAA==.Maxierogue:BAAALAAECgYICgABLAAECggIIAAJAHIaAA==.Maxillectomy:BAAALAAECggICAAAAA==.',Me='Mechanix:BAACLAAFFIEKAAIYAAUIqw7dBwCeAQAYAAUIqw7dBwCeAQAsAAQKgSEAAhgACAjFIo8SAPcCABgACAjFIo8SAPcCAAAA.Meena:BAABLAAECoEYAAINAAcIzAlPkwBKAQANAAcIzAlPkwBKAQAAAA==.Megadeeps:BAAALAADCgQIBAAAAA==.Megafuming:BAAALAADCgIIAwAAAA==.Mercurie:BAABLAAECoEVAAIWAAYIuxx2CwDnAQAWAAYIuxx2CwDnAQAAAA==.Metalbenji:BAABLAAECoEaAAIYAAcItxMATADMAQAYAAcItxMATADMAQAAAA==.Methone:BAAALAADCgcIBwABLAAFFAUIEQAfAGIcAA==.',Mi='Mickyy:BAAALAAECgIIAgAAAA==.Mildred:BAAALAAECgIIAwAAAA==.Mildredd:BAAALAAECgcIDAAAAA==.Minibanana:BAAALAADCgEIAQAAAA==.Missis:BAABLAAECoEgAAIVAAgIDwjgjQAfAQAVAAgIDwjgjQAfAQAAAA==.Mitoxan:BAAALAADCggICAAAAA==.',Mm='Mmarko:BAABLAAECoEoAAIYAAgINwv1VQCrAQAYAAgINwv1VQCrAQAAAA==.',Mo='Moghedien:BAAALAAECgMIBgAAAA==.Moltenjo:BAAALAAECgYIDgAAAA==.Mommymamba:BAAALAAECggICAAAAA==.Monkdral:BAACLAAFFIERAAIiAAYItQvJAgC+AQAiAAYItQvJAgC+AQAsAAQKgS4AAiIACAirG8MMAG0CACIACAirG8MMAG0CAAAA.Monkmagic:BAAALAAECgIIAgAAAA==.Monster:BAAALAAECggIDAAAAA==.Moobies:BAAALAADCggICAAAAA==.Moonswift:BAAALAADCggIDwAAAA==.Morketá:BAABLAAECoEUAAIdAAgIkBy+FQCdAgAdAAgIkBy+FQCdAgAAAA==.Motivation:BAAALAAECgUICgAAAA==.',Mu='Mudmud:BAAALAAECggICAAAAA==.Mudneck:BAAALAADCgIIAgAAAA==.Muffins:BAAALAAECgcIDgAAAA==.Munkenmogens:BAAALAAECgMIAwAAAA==.',My='Myllanis:BAAALAAECgYIDAAAAA==.Mynthara:BAAALAADCggIGgAAAA==.',['Má']='Máge:BAAALAADCggICAAAAA==.',['Mæ']='Mæ:BAABLAAECoEkAAIZAAgITRccLwBPAgAZAAgITRccLwBPAgAAAA==.',['Mè']='Mètalbenji:BAAALAAECgYIDAAAAA==.',Na='Naak:BAAALAAECgYICAABLAAECggIGgAOAIcdAA==.Nalia:BAAALAAECgYIBgABLAAECgYICwABAAAAAA==.Naraaka:BAAALAAECgEIAQAAAA==.Natti:BAAALAAECgYICwAAAA==.',Ne='Neenae:BAABLAAECoEbAAINAAYI/QpRpQAlAQANAAYI/QpRpQAlAQAAAA==.Nes:BAACLAAFFIETAAMYAAcIwRxPAQBxAgAYAAYITyBPAQBxAgAKAAEIbgfUHgBHAAAsAAQKgRoAAhgACAgMJZYOABYDABgACAgMJZYOABYDAAAA.Nevermyfault:BAAALAADCgUIBQAAAA==.',Ni='Nicdead:BAABLAAECoEXAAIYAAgI9QI1nQDFAAAYAAgI9QI1nQDFAAAAAA==.Niff:BAAALAAECgIIAgAAAA==.Nilfilleniun:BAAALAADCgYIBgAAAA==.Ninjagrisen:BAAALAAECgYICwAAAA==.',No='Nofoxgiven:BAABLAAECoEZAAIQAAcIvxx7EwBMAgAQAAcIvxx7EwBMAgAAAA==.Nohunter:BAAALAAECgYIDAAAAA==.',Nu='Nulleria:BAAALAAECgYIDwABLAAECgcIGQAGALIRAA==.',Ny='Nyayu:BAAALAADCgMIBAABLAAFFAMICQACAEIVAA==.Nylariel:BAAALAADCggICAAAAA==.Nymera:BAABLAAECoEaAAIOAAcIkAk/JgAiAQAOAAcIkAk/JgAiAQAAAA==.',['Nò']='Nòx:BAAALAAECgYIDQAAAA==.',['Nø']='Nøgen:BAABLAAECoEVAAIfAAYI+B1tMADIAQAfAAYI+B1tMADIAQAAAA==.',Oc='Octobryn:BAAALAADCggICAAAAA==.',Od='Oda:BAAALAAECgIIAgABLAAFFAMIBQALADgIAA==.',On='Onionrings:BAAALAAECgYIBgABLAAECgYIEwABAAAAAA==.',Os='Osíris:BAAALAAECgMIAwAAAA==.',Ov='Ov:BAAALAADCgEIAQAAAA==.Overkill:BAAALAADCggIDgAAAA==.',Oz='Ozia:BAAALAAECgYIBgABLAAECggIJgAQAFQcAA==.',Pa='Painfullyobv:BAAALAAECgYIBQAAAA==.Pakz:BAAALAADCgcIDgAAAA==.Paladash:BAAALAAECggICAAAAA==.Palight:BAAALAAECgQIBwAAAA==.Parme:BAAALAADCgcIDQAAAA==.Parmesan:BAABLAAECoEcAAMWAAcI4SCVBQCDAgAWAAcI4SCVBQCDAgAOAAMIcA2kMwCIAAAAAA==.Parranoia:BAAALAAECggIEwAAAA==.Pathøgen:BAAALAADCggICAAAAA==.',Pe='Persephoné:BAABLAAECoEgAAITAAcIYBJnegDGAQATAAcIYBJnegDGAQAAAA==.Perôna:BAAALAAECgEIAQAAAA==.',Ph='Philoctetes:BAAALAAECgYIBgABLAAFFAIICAAGAB4WAA==.',Pi='Pinkiepie:BAAALAAECgYIDQAAAA==.Pippz:BAAALAAECgYIBgAAAA==.Pipz:BAAALAAECggICAAAAA==.Pipzz:BAAALAADCgEIAQAAAA==.Pityek:BAAALAADCggICwAAAA==.',Po='Poef:BAAALAADCggICAABLAAECgIIAgABAAAAAA==.',Pr='Prillan:BAAALAAECggIDAAAAA==.Protein:BAABLAAECoEaAAMfAAgIhyHSDQDfAgAfAAgIhyHSDQDfAgAWAAEIaxFlKwA0AAAAAA==.Pruttknugen:BAAALAADCggICQAAAA==.',Ps='Pstav:BAAALAAECgcIDQAAAA==.',Pu='Puffins:BAAALAAECgYIBgABLAAECgcIDgABAAAAAA==.',['Pø']='Pøh:BAABLAAECoEjAAIMAAgI+B4tAgDUAgAMAAgI+B4tAgDUAgAAAA==.',Qp='Qpu:BAAALAADCgQIBAAAAA==.',Qu='Quirine:BAAALAADCggICgAAAA==.',Ra='Racular:BAABLAAECoEiAAMZAAgIcRhyNAA1AgAZAAgIOBhyNAA1AgAjAAIIwRDZKQCAAAAAAA==.Radience:BAAALAADCgYIBgAAAA==.Raeldan:BAAALAADCggICQAAAA==.Ragenoodle:BAAALAAECgIIAgABLAAFFAMICQANAJMjAA==.Ragi:BAAALAAECgYIEwAAAA==.Ragrura:BAAALAAECgUIBQAAAA==.Rammhammer:BAAALAAECgYIDwAAAA==.Rastabution:BAABLAAECoEWAAILAAgInRV/UQAZAgALAAgInRV/UQAZAgAAAA==.Ratters:BAAALAADCggIDQAAAA==.Raybanz:BAABLAAECoEaAAMgAAgI7hhkIAA7AgAgAAgI7hhkIAA7AgAfAAQIlg6MZwDCAAAAAA==.',Re='Reckless:BAAALAADCgEIAQAAAA==.Reghar:BAAALAAECgQIBAAAAA==.',Rh='Rhyme:BAAALAADCgIIAgAAAA==.',Ri='Rickarus:BAABLAAECoEgAAIYAAcI3xC+VACvAQAYAAcI3xC+VACvAQAAAA==.Rikati:BAAALAAECgQIBAAAAA==.Risingsun:BAAALAADCggICAAAAA==.',Ro='Roomie:BAAALAADCggIDwAAAA==.Royal:BAAALAAECgQIBAAAAA==.',Ru='Ruhbuhguh:BAAALAADCggICgAAAA==.',Ry='Rybin:BAABLAAECoEWAAIkAAYIWiJABgA/AgAkAAYIWiJABgA/AgABLAAECggIGgAOAIcdAA==.Ryän:BAAALAAECgYIDAAAAA==.Ryé:BAAALAAECgcIEQAAAA==.',Sa='Saabina:BAAALAADCgYIBgABLAAECgQIBQABAAAAAA==.Sakil:BAAALAADCggICgAAAA==.Salenia:BAABLAAECoEgAAIWAAcIIyHyBACXAgAWAAcIIyHyBACXAgAAAA==.Santéz:BAAALAADCgYIBAAAAA==.Sarafin:BAAALAAECgQIBAAAAA==.Sarria:BAAALAADCggICAAAAA==.Sasha:BAACLAAFFIEHAAIOAAMIlw6zBADtAAAOAAMIlw6zBADtAAAsAAQKgRsAAg4ACAiQGVELAHQCAA4ACAiQGVELAHQCAAAA.Satanzdagger:BAAALAADCgcICwAAAA==.Satanzlight:BAAALAAECgYIDgAAAA==.Saváge:BAAALAAECgIIAgAAAA==.Saítama:BAAALAADCggIFgABLAAECgcIFgADANkTAA==.',Sc='Scaris:BAAALAADCgQIAgAAAA==.Scubadiver:BAAALAAECgcIEwAAAA==.Scyaliecyn:BAAALAAECgcIDQAAAA==.',Se='Seak:BAAALAADCgcIBwAAAA==.Seen:BAAALAAECgMIAwAAAA==.Seggar:BAACLAAFFIEFAAILAAMIOAjMEQDYAAALAAMIOAjMEQDYAAAsAAQKgSkAAgsACAi7HfwvAIQCAAsACAi7HfwvAIQCAAAA.Selina:BAAALAAECgQIBAAAAA==.Senbonzakurä:BAAALAAECgEIAQAAAA==.Sennah:BAAALAADCgEIAQAAAA==.Sephorus:BAAALAADCggIDgAAAA==.Seps:BAAALAADCgcIBwABLAAECggIFwABAAAAAQ==.Serama:BAAALAADCgcIFAABLAAECggIIgAZAHEYAA==.Sesp:BAAALAAECggIFwAAAQ==.',Sh='Shadowness:BAAALAAECggICAAAAA==.Shadowordpwn:BAAALAADCggICAAAAA==.Shadowruns:BAAALAADCgcIDwAAAA==.Shallot:BAAALAAECggICgAAAA==.Shambear:BAABLAAECoEdAAIVAAcIpQ79egBKAQAVAAcIpQ79egBKAQAAAA==.Shambles:BAAALAAECgMIAwABLAAECgQIBQABAAAAAA==.Shameltoe:BAAALAAECggICAAAAA==.Shammylou:BAAALAADCggICgAAAA==.Shamonrah:BAABLAAECoEfAAIeAAgIvBA+ZADLAQAeAAgIvBA+ZADLAQAAAA==.Shamtastics:BAAALAAECgEIAQAAAA==.Shaq:BAAALAAECgYICwAAAA==.Shaqaso:BAAALAADCgQIBAABLAAECgYICwABAAAAAA==.Sheitposter:BAAALAAECgEIAQAAAA==.Shepvader:BAAALAAECggICAAAAA==.Shibbs:BAAALAAECgQIBAAAAA==.Shinden:BAABLAAECoEUAAIYAAcI/hjKPgD9AQAYAAcI/hjKPgD9AQAAAA==.Shinycow:BAAALAADCggIDgAAAA==.Shotan:BAAALAADCgMIAwAAAA==.Shuwanawana:BAAALAADCgcIAgAAAA==.',Si='Sickheart:BAAALAAECgYIAwABLAAECgYIEwABAAAAAA==.Sidékick:BAAALAAECgcIBAAAAA==.Sindrion:BAAALAADCgMIBgAAAA==.Singh:BAACLAAFFIEGAAMUAAII1hVUCQCSAAAUAAII1hVUCQCSAAATAAIIyQc2YABPAAAsAAQKgSEAAxMACAhTG75CAEgCABMACAiOGb5CAEgCABQABQjMHDMXAKYBAAAA.',Sk='Skytte:BAAALAADCgYICAAAAA==.Skyé:BAAALAADCggICAAAAA==.Skåningen:BAAALAAECgcICQAAAA==.Skýr:BAAALAADCggIDwAAAA==.',Sl='Slepil:BAAALAAECgYIEAAAAA==.Slurk:BAAALAADCgUIBQAAAA==.Slurkx:BAAALAAECgMIBAAAAA==.',Sm='Smitta:BAAALAADCgYIBwABLAAFFAMICgAOAPQgAA==.',Sn='Sneakysimo:BAAALAADCgQIBAABLAAECggIIQAPAOoZAA==.Snegkulak:BAAALAADCgUIDAAAAA==.Snoak:BAAALAADCgYIBgAAAA==.Snyltgäst:BAAALAAECgIIAgAAAA==.',So='Somnissette:BAAALAAECgEIAQAAAA==.Soulmaim:BAAALAADCgcICAAAAA==.',Sp='Sparx:BAAALAAECgYIDwAAAA==.Spatts:BAAALAAECgIIAgAAAA==.Spinoff:BAAALAAECggICwAAAA==.Spliffy:BAAALAAECgMIAwAAAA==.Spoxangel:BAAALAADCggIHQAAAA==.Sprucer:BAAALAADCgcIBwAAAA==.Spyrò:BAAALAADCgUIAwAAAA==.',St='Starcatcher:BAABLAAECoEgAAILAAcIKhlNWgADAgALAAcIKhlNWgADAgAAAA==.Statskinsky:BAAALAAECgQIBAAAAA==.Stofs:BAACLAAFFIEIAAIcAAII0BCVEwCcAAAcAAII0BCVEwCcAAAsAAQKgRcAAhwACAgeGVIVAFsCABwACAgeGVIVAFsCAAAA.Stolkolight:BAAALAAECgcIEgAAAA==.Strahil:BAAALAAECgUICgAAAA==.Stratus:BAAALAADCggIEAAAAA==.Strife:BAABLAAECoEXAAIHAAgIHh6iCgDOAgAHAAgIHh6iCgDOAgAAAA==.Stripemage:BAAALAADCggICAABLAAFFAYIFQAKAI4kAA==.Stripesham:BAAALAADCgcIBwABLAAFFAYIFQAKAI4kAA==.Stripewarr:BAACLAAFFIEVAAIKAAYIjiSGAACUAgAKAAYIjiSGAACUAgAsAAQKgS8AAgoACAjTJjcAAJkDAAoACAjTJjcAAJkDAAAA.',Su='Suzy:BAAALAAECgcIDQAAAA==.',Sw='Swambodi:BAABLAAECoEbAAIWAAcIdx+BBgBkAgAWAAcIdx+BBgBkAgAAAA==.Swish:BAAALAADCgIIAwAAAA==.',Sy='Sylvann:BAAALAAECggICAAAAA==.Syri:BAAALAAECgEIAQAAAA==.Syrisus:BAAALAAECgcIEwAAAA==.',['Sí']='Sínatra:BAABLAAECoEiAAIZAAgICROVPwAEAgAZAAgICROVPwAEAgAAAA==.',Ta='Taendir:BAAALAADCggICwABLAAECgYIBgABAAAAAA==.Taigaplox:BAAALAADCggIDgAAAA==.',Te='Tearocks:BAABLAAECoEaAAIjAAcIMht8BgBOAgAjAAcIMht8BgBOAgAAAA==.Tedric:BAABLAAECoEZAAIRAAcIkBg2GwADAgARAAcIkBg2GwADAgAAAA==.Teleport:BAAALAAECggICAAAAA==.Teniza:BAAALAADCggIDgAAAA==.Terix:BAAALAADCggICAABLAAECggIMQAYAAYgAA==.Terrain:BAAALAADCgcICAAAAA==.Terrock:BAAALAADCgMIAwAAAA==.',Th='Thanatoss:BAABLAAECoEeAAIJAAgIQSHcCwAEAwAJAAgIQSHcCwAEAwAAAA==.Theophanie:BAAALAAECgUICAAAAA==.Theopriest:BAAALAAECgYIDAABLAAFFAIIBgATADIcAA==.Theorcbear:BAAALAAECgMIAwAAAA==.Theronna:BAAALAADCggIEAAAAA==.Thonk:BAABLAAECoEgAAINAAcIGSZIEgDxAgANAAcIGSZIEgDxAgAAAA==.Thorassin:BAAALAADCggICAABLAAECggIJAAKADwcAA==.Thruxx:BAABLAAECoExAAMYAAgIBiBSFwDXAgAYAAgIBiBSFwDXAgAlAAQIIRW5HgDgAAAAAA==.Thug:BAAALAAECgYIBgAAAA==.Thugdruid:BAAALAAECgYIBQAAAA==.Thunderkaern:BAEBLAAECoEVAAMCAAcI1Q9vSgCnAQACAAcI1Q9vSgCnAQAVAAUINQcSzQCiAAABLAAECggIDwABAAAAAA==.Thyvalae:BAAALAADCgYIBgABLAAECgYIFQAWALscAA==.',Ti='Tiantar:BAAALAADCgQIBAAAAA==.Tidespeaker:BAAALAADCggIFgAAAA==.Tinytornado:BAABLAAECoEbAAIPAAcIThreEQAKAgAPAAcIThreEQAKAgAAAA==.Titchevo:BAAALAAECgMIAwABLAAECggIHAAiADMbAA==.Titchi:BAABLAAECoEcAAQiAAgIMxthDgBUAgAiAAgIMxthDgBUAgAPAAEIrAJ1QwAZAAAQAAEI7gI1XQAYAAAAAA==.Tix:BAAALAAECgYICwABLAAECggICAABAAAAAA==.',To='Tonsilitus:BAAALAAECgUICQAAAA==.Totemmaker:BAAALAAECgYIBgAAAA==.Totemtwister:BAAALAADCggICAAAAA==.Totemystik:BAAALAAECgcIBwAAAA==.Towel:BAACLAAFFIENAAMgAAUIABqQCAAKAQAgAAQIpRmQCAAKAQAfAAEI5ghOHQBOAAAsAAQKgS4AAyAACAhwJUkCAFQDACAACAhwJUkCAFQDAA4AAQgkG+o7AEEAAAAA.',Tr='Tranzbi:BAAALAADCggIDwAAAA==.Trillé:BAAALAAFFAIIAgAAAA==.Trixibell:BAAALAADCgcIGQAAAA==.Trsaa:BAAALAADCgcIEwABLAAECggIJgAQAFQcAA==.',Ts='Tsuyu:BAAALAAECgMIAwAAAA==.',Tu='Tudz:BAAALAADCgcIBgABLAAFFAIICgALAJUeAA==.Tuospala:BAABLAAECoEZAAMLAAcImRfUZADrAQALAAcImRfUZADrAQARAAYI4hhEJQC4AQAAAA==.Tuossham:BAAALAADCggIFwABLAAECgcIGQALAJkXAA==.Turnusol:BAAALAAECgMIBQAAAA==.Tussa:BAABLAAECoEbAAMIAAgIWRr1GACGAgAIAAgIWRr1GACGAgAMAAIIFAxLKgBVAAAAAA==.',Ty='Tyraèl:BAAALAADCggIFAAAAA==.Tyristrum:BAABLAAECoEVAAILAAgIfByyLwCFAgALAAgIfByyLwCFAgAAAA==.',['Tî']='Tîb:BAAALAADCgcIBwAAAA==.',['Tï']='Tïb:BAAALAADCgQIBAAAAA==.',Uj='Ujnek:BAAALAAECgIIAgAAAA==.',Un='Undralord:BAABLAAECoEVAAISAAgI+BZgEwA/AgASAAgI+BZgEwA/AgAAAA==.',Va='Valkia:BAAALAADCggIEAAAAA==.Valpo:BAAALAADCggICAAAAA==.Valshina:BAEALAAECggIDwAAAA==.Vambran:BAAALAAECgYICgAAAA==.Vammp:BAAALAAECggIDAAAAA==.Vampz:BAAALAADCggICAAAAA==.Varigros:BAAALAAECgYIEAAAAA==.Vasilievena:BAAALAAECgcIDgAAAA==.Vaughn:BAAALAADCggIDAAAAA==.',Ve='Veejayvee:BAAALAAECgUICQAAAA==.Velarina:BAEALAADCgIIAgABLAAECggIDwABAAAAAA==.',Vi='Vics:BAAALAADCgcIBwABLAAECgcIGgANAGsMAA==.Viktora:BAAALAADCggIDgABLAAECgYIFQAWALscAA==.Vilulina:BAAALAAECgYIBgABLAAECggICwABAAAAAA==.Vitskägg:BAAALAAECgIIAgAAAA==.Vizari:BAABLAAECoEXAAIKAAcI2yE4DQCwAgAKAAcI2yE4DQCwAgAAAA==.',Vo='Voltaic:BAAALAADCgIIAgAAAA==.Voltariis:BAAALAADCggICAAAAA==.Voltarin:BAABLAAECoEeAAIgAAgI8RpVFgB+AgAgAAgI8RpVFgB+AgAAAA==.Vorrell:BAAALAAECgIIAgAAAA==.',Vu='Vuldr:BAABLAAECoEVAAINAAgIIBiXPwAXAgANAAgIIBiXPwAXAgAAAA==.Vulxie:BAAALAAECgYIEgAAAA==.',['Và']='Vàrgas:BAAALAAECgUIBQAAAA==.',Wa='Walee:BAAALAAECgYIDQAAAA==.',Wh='Whiteengel:BAAALAAECgMIAwABLAAECggIJAAZAE0XAA==.',Wi='Wickedwanda:BAAALAAECgYIBgAAAA==.Wiifi:BAACLAAFFIEKAAIVAAIIbiN4FADGAAAVAAIIbiN4FADGAAAsAAQKgRkAAxUABgjCHQo6AAMCABUABgjCHQo6AAMCAAIABgjaFE5dAGYBAAAA.Willyorthumb:BAABLAAECoEWAAIDAAcI2ROOFACyAQADAAcI2ROOFACyAQAAAA==.Wintu:BAAALAADCgIIAgAAAA==.',Wo='Words:BAAALAADCgcIBwAAAA==.',Wr='Wrenn:BAABLAAECoEUAAIgAAYIBg8zZAAfAQAgAAYIBg8zZAAfAQAAAA==.',Wu='Wukkést:BAABLAAECoEhAAIeAAgIDRBkXADfAQAeAAgIDRBkXADfAQAAAA==.',['Wì']='Wìl:BAABLAAECoEfAAMNAAcI1iLBIwCIAgANAAcI1iLBIwCIAgAdAAMI9Q7HhwCOAAAAAA==.',Xa='Xaltherion:BAAALAADCggICwAAAA==.',Xe='Xerr:BAACLAAFFIEJAAIJAAMI3RUXDQDsAAAJAAMI3RUXDQDsAAAsAAQKgScAAgkACAiYIDEOAO0CAAkACAiYIDEOAO0CAAAA.',Xi='Ximia:BAAALAADCggICAAAAA==.',Ya='Yaesera:BAAALAAECggICAAAAA==.Yardeen:BAAALAADCgQIBAABLAADCggIDgABAAAAAA==.Yazoo:BAAALAADCggIDgAAAA==.',Ye='Yeahal:BAAALAAECgIIBAABLAAECgUIBQABAAAAAA==.',Ym='Ymir:BAAALAAECgIIAwAAAA==.',Yo='Yoyulun:BAAALAAECgEIAQAAAA==.',Za='Zandid:BAABLAAECoEZAAMOAAcIXRlWEgACAgAOAAcIrRhWEgACAgAfAAYIPgkhXAD+AAAAAA==.Zantara:BAAALAAECgIIAgAAAA==.Zardul:BAAALAADCgYIBgABLAAFFAMICgAYANUWAA==.Zaryndra:BAAALAAECgIIAgAAAA==.',Ze='Zeadora:BAAALAAECgMIBQAAAA==.Zeci:BAAALAAECgYIBwAAAA==.Zele:BAAALAADCggICwAAAA==.Zelà:BAAALAADCggIEAAAAA==.Zempí:BAAALAAECgMIAwAAAA==.',Zi='Zipzip:BAAALAAECgcIEwAAAA==.',Zo='Zokual:BAABLAAECoEjAAIgAAgIfhlqJAAkAgAgAAgIfhlqJAAkAgAAAA==.Zonden:BAAALAAECgcIBwAAAA==.Zondina:BAAALAAECggICQAAAA==.Zoomíe:BAAALAAECggIDwAAAA==.Zorinn:BAAALAAECgYIDgAAAA==.',Zp='Zpindel:BAAALAADCgcIDAAAAA==.',Zu='Zubeia:BAAALAADCggIDwAAAA==.',Zv='Zvezda:BAAALAADCggICAAAAA==.Zvezdica:BAABLAAECoEXAAIGAAYIuBXkbQCVAQAGAAYIuBXkbQCVAQAAAA==.',['Ât']='Âthena:BAAALAAECgEIAQAAAA==.',['Äp']='Äppeljuice:BAAALAADCgYIBgAAAA==.',['Æn']='Ænema:BAABLAAECoEkAAIGAAgI9BQ2QAAlAgAGAAgI9BQ2QAAlAgAAAA==.',['Ðr']='Ðrá:BAAALAAECgYIDwAAAA==.',['Öm']='Ömu:BAAALAADCggICAABLAAECggIJAAKADwcAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end