local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Evoker-Preservation','Warrior-Protection','Druid-Feral','Druid-Restoration','DemonHunter-Havoc','Paladin-Retribution','Monk-Brewmaster','Priest-Holy','Priest-Shadow','Priest-Discipline','Evoker-Devastation','Warlock-Demonology','Druid-Balance','Shaman-Enhancement','Warrior-Fury','Paladin-Protection','Mage-Arcane','Warlock-Destruction','DeathKnight-Unholy','Rogue-Outlaw','DeathKnight-Frost','Monk-Mistweaver','Monk-Windwalker','Evoker-Augmentation','Unknown-Unknown','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Restoration','DemonHunter-Vengeance','Rogue-Subtlety','Rogue-Assassination','DeathKnight-Blood','Shaman-Elemental','Mage-Frost','Warrior-Arms','Warlock-Affliction','Paladin-Holy','Druid-Guardian','Hunter-Survival',}; local provider = {region='EU',realm='Nagrand',name='EU',type='weekly',zone=44,date='2025-09-22',data={Ad='Adam:BAAALAAECgIIAgAAAA==.Adrassal:BAABLAAECoEXAAIBAAgIvRyzBwCVAgABAAgIvRyzBwCVAgAAAA==.Adryhlia:BAAALAAECgYIBgAAAA==.',Ae='Aegon:BAAALAAFFAIIAgAAAA==.',Ag='Agnicia:BAAALAAECggIDQAAAA==.Aguir:BAAALAAECgcIDAAAAA==.Aguiri:BAAALAAECgcIDQAAAA==.',Ai='Aisw:BAABLAAECoEeAAICAAcI3ApcPwAzAQACAAcI3ApcPwAzAQAAAA==.',Al='Alagion:BAAALAADCgcIBwAAAA==.Alashar:BAABLAAECoEhAAIDAAcInB61CwBsAgADAAcInB61CwBsAgAAAA==.Alassahr:BAACLAAFFIEIAAIEAAIIuSNSDgDOAAAEAAIIuSNSDgDOAAAsAAQKgSQAAgQACAi6IVUKAOoCAAQACAi6IVUKAOoCAAAA.Althaea:BAAALAAECgYIBgAAAA==.',Am='Amidamaru:BAABLAAECoEUAAIFAAgIdQ/IXgDZAQAFAAgIdQ/IXgDZAQAAAA==.',An='Andorai:BAAALAADCgIIAgAAAA==.Andothar:BAAALAADCgcICwAAAA==.Angeryman:BAAALAAECggIEwAAAA==.Angrycat:BAAALAADCggIHwABLAAECgcIGgAGAPsbAA==.Angrymonk:BAAALAADCggIHwABLAAECgcIGgAGAPsbAA==.Angryxp:BAAALAADCggIEAABLAAECgcIGgAGAPsbAA==.Anillusión:BAAALAAECggIEAABLAAECggIFQAHAK4OAA==.Anossa:BAACLAAFFIEIAAIIAAMIvxCiDwDlAAAIAAMIvxCiDwDlAAAsAAQKgSgABAgACAh8IRgOAN8CAAgACAh8IRgOAN8CAAkABgiUGXszANMBAAoAAQgXES4xADIAAAAA.Antonios:BAABLAAECoEYAAILAAcIDA9RKwCdAQALAAcIDA9RKwCdAQAAAA==.',Ar='Araknae:BAAALAADCgEIAQABLAAECgcIFQAMAN8bAA==.Ardisee:BAAALAADCggICQAAAA==.Argentus:BAAALAAECggICgAAAA==.Ariely:BAAALAADCgYIBgAAAA==.Arkenstone:BAAALAADCgEIAQAAAA==.Arleigh:BAAALAADCgQIBAAAAA==.Arowin:BAAALAADCgUIBQAAAA==.Arysa:BAABLAAECoEVAAINAAYIzBFERQBjAQANAAYIzBFERQBjAQAAAA==.',As='Asnac:BAAALAADCgIIAgAAAA==.Astonz:BAAALAAECgMIAwAAAA==.',At='Athlon:BAAALAADCggICAAAAA==.Athoman:BAABLAAECoEYAAIGAAgInhj7PABVAgAGAAgInhj7PABVAgAAAA==.Atlas:BAAALAAECggIDQABLAAFFAIICAAOADgQAA==.',Av='Avacado:BAAALAAECgEIAQAAAA==.Avaer:BAAALAADCggIEAABLAAFFAMICQAGAHMkAA==.Avaleth:BAAALAADCgcIBwABLAAECggIHgAPAEUhAA==.',Aw='Awsomeinc:BAAALAADCggICAAAAA==.Awsomepreist:BAAALAADCgIIAgAAAA==.',Ay='Ayari:BAAALAAECgYIDAABLAAFFAYIGwAQAMsgAA==.',Az='Azaeyl:BAABLAAECoEVAAIRAAgIkxChUADsAQARAAgIkxChUADsAQAAAA==.Azhagu:BAAALAAECgMIAwABLAAECgcIFQAMAN8bAA==.Azlan:BAAALAADCggIJwAAAA==.Azurik:BAAALAADCgYICQAAAA==.',Ba='Bananaface:BAAALAADCgQIBAAAAA==.Battlemaster:BAABLAAFFIEFAAMMAAMIPAi2FACLAAAMAAIIvgi2FACLAAASAAEIOQdNPABQAAAAAA==.Bawface:BAAALAAECgcIDwAAAA==.Bayok:BAAALAADCgYIBgAAAA==.Bazim:BAAALAAECgcIDwAAAA==.Bazrabbitz:BAAALAADCgYIBgAAAA==.',Be='Bemon:BAAALAAECgcIEwAAAA==.Bemons:BAAALAAECggIEAAAAA==.Benga:BAAALAAECgUIBQAAAA==.Beorin:BAAALAAECgEIAQAAAA==.',Bi='Bigjuicy:BAAALAADCgUIBQAAAA==.Bigtoe:BAAALAAECgUIBwAAAA==.',Bl='Bloodcrazy:BAABLAAECoEaAAITAAcISxJZGADfAQATAAcISxJZGADfAQAAAA==.Bloodninja:BAAALAAECgUIBQAAAA==.Blurredsight:BAABLAAECoEbAAIPAAgI7A8KRgDhAQAPAAgI7A8KRgDhAQAAAA==.',Bo='Boldric:BAABLAAECoEcAAIUAAgIohkuBACAAgAUAAgIohkuBACAAgAAAA==.Borkblomst:BAAALAAECggICAAAAA==.Botini:BAAALAAECgYICAAAAA==.',Br='Brewbash:BAAALAADCggIBQAAAA==.Bridget:BAAALAAECggIAwAAAA==.Briggle:BAAALAADCgcIBwAAAA==.Broxic:BAAALAADCggICAAAAA==.Broxxoli:BAAALAAECgUIBQAAAA==.Brykar:BAAALAADCggIEAABLAAFFAMIBQAVAAkMAA==.',Bt='Btray:BAAALAADCgYIBgAAAA==.',Bu='Budhi:BAAALAADCgcIBwAAAA==.Buffalosadie:BAAALAAECggIDAAAAA==.Buffblzer:BAAALAADCgUIBQAAAA==.Bumblebean:BAAALAADCgcIEgAAAA==.',Ca='Cabbagegirl:BAABLAAECoEcAAMWAAgIPw4iHwB5AQAWAAgIPw4iHwB5AQAXAAYIoQk6PQDvAAAAAA==.Cabus:BAACLAAFFIETAAQYAAYIoxsWAQDcAQAYAAUImiAWAQDcAQALAAUIbxAjBgB8AQABAAEIWQA3FAAzAAAsAAQKgTwABBgACAhUJhEAAJIDABgACAhPJhEAAJIDAAsACAiyJIsGABsDAAEABgiQIF0MADcCAAAA.Cacophony:BAAALAADCgYIFwABLAADCgcIDQAZAAAAAA==.Cadal:BAAALAAECgEIAQAAAA==.Caddie:BAAALAADCggICwAAAA==.Camaron:BAABLAAECoEYAAIIAAcIBAmtWgBFAQAIAAcIBAmtWgBFAQAAAA==.Cashhunter:BAABLAAECoEbAAIaAAcIPBZbYgC0AQAaAAcIPBZbYgC0AQAAAA==.Cassalanter:BAAALAAECgMIAwABLAAECgYIBgAZAAAAAA==.Castraaza:BAAALAAECgcICgAAAA==.Caulïflower:BAAALAADCggICAAAAA==.',Ce='Cerpx:BAAALAAECgQIBAAAAA==.',Ch='Chikenplain:BAAALAAECgYIDgAAAA==.Chiraku:BAABLAAECoEZAAIbAAcImxnlKAAQAgAbAAcImxnlKAAQAgAAAA==.Chrissen:BAAALAAECggIEQAAAA==.Chubbpain:BAAALAAECgcIDgAAAA==.',Co='Coleb:BAAALAAECgYIBgABLAAECggIJgAcAGcfAA==.Combustanut:BAAALAAECgIIAgABLAAECggIJgAVAIMfAA==.Contrac:BAAALAADCggICwAAAA==.Controler:BAABLAAECoEZAAIMAAcI8Af1OABlAQAMAAcI8Af1OABlAQAAAA==.Corvaen:BAAALAADCggIDwABLAAFFAMICQAGAHMkAA==.Cowdwarf:BAAALAAECgcIDgAAAA==.',Cr='Crowe:BAAALAAECgcIDwAAAA==.Crucaebena:BAABLAAECoEjAAIWAAgIdhoVDQBoAgAWAAgIdhoVDQBoAgAAAA==.Cry:BAAALAAECgUIBQAAAA==.Cryó:BAAALAADCggIEAAAAA==.',Da='Dalriena:BAABLAAECoEUAAIJAAgIBR1bEwC6AgAJAAgIBR1bEwC6AgAAAA==.Darah:BAAALAADCggIDQAAAA==.Darkoo:BAAALAAECgcICwAAAA==.Darkreggie:BAABLAAECoEYAAMdAAgIdhsuDABoAgAdAAgINhsuDABoAgAFAAcI3g/ahQCDAQAAAA==.Darkself:BAAALAAECgEIAQAAAA==.Darksight:BAAALAADCgcIBwAAAA==.Darkthunders:BAAALAAECgIIAwABLAAECgcIFgAGAEcTAA==.Darkzör:BAACLAAFFIEKAAISAAQIfxfvDQBuAQASAAQIfxfvDQBuAQAsAAQKgSMAAhIACAhhIgARAAQDABIACAhhIgARAAQDAAAA.Darthur:BAAALAAECgYICgAAAA==.Dash:BAACLAAFFIEGAAMeAAIIhxvOEQBcAAAeAAEIPh7OEQBcAAAfAAEI0BjMGQBVAAAsAAQKgSgAAx8ACAjwIZ0WAE8CAB8ABwhXG50WAE8CAB4ABQhKHXUXAK8BAAAA.',De='Deadlycookie:BAABLAAECoEPAAIVAAgIfQ7DhACyAQAVAAgIfQ7DhACyAQAAAA==.Deathawaits:BAABLAAECoEgAAMVAAgIlh1UdwDMAQAVAAcIrh1UdwDMAQATAAUIrRgAKgBQAQAAAA==.Deathhere:BAABLAAECoEZAAIaAAcITwo8lABIAQAaAAcITwo8lABIAQAAAA==.Deathlysmoke:BAAALAADCgMIAwAAAA==.Deathmace:BAAALAAECggICAAAAA==.Deathrazer:BAAALAADCgYIBgAAAA==.Deathspells:BAAALAAECggICAAAAA==.Deathsythe:BAAALAAECgYIDgAAAA==.Debs:BAABLAAECoEZAAIWAAcIzRCmHwB0AQAWAAcIzRCmHwB0AQAAAA==.Dedleg:BAABLAAECoEmAAIVAAgIgx8nIwC+AgAVAAgIgx8nIwC+AgAAAA==.Deidran:BAAALAAECgQIBAABLAAECggIJAAgABkiAA==.Deliriarick:BAAALAAECgUIBgAAAA==.Delkim:BAAALAADCggICAAAAA==.Deltroth:BAAALAAECgYIDQAAAA==.Demerzel:BAAALAAECggIDwAAAA==.Demonbaz:BAAALAADCggIDgAAAA==.Demonkapa:BAAALAAECgcIDgAAAA==.Demonlady:BAAALAADCggICQAAAA==.Demonwish:BAAALAADCgIIBAAAAA==.Desalona:BAAALAADCggICAAAAA==.Desmodus:BAABLAAECoEVAAMMAAcI3xsiEgBLAgAMAAcIeRsiEgBLAgASAAMImBi6nwDZAAAAAA==.Dettolwipes:BAAALAAECgQIBgAAAA==.Devoratrix:BAABLAAECoEfAAISAAYIOhAUdABcAQASAAYIOhAUdABcAQAAAA==.Dewar:BAAALAADCgIIAgAAAA==.',Di='Dingleberri:BAAALAAECgIIAgAAAA==.Dirtbocks:BAAALAADCggICAAAAA==.Distracted:BAAALAADCgQIBAABLAAECgcIHAAhAIUbAA==.Distressed:BAAALAADCggIEAABLAAECgcIHAAhAIUbAA==.Distrusted:BAABLAAECoEcAAIhAAcIhRuvLQApAgAhAAcIhRuvLQApAgAAAA==.',Dm='Dmn:BAABLAAECoEYAAIIAAcITQekXwAzAQAIAAcITQekXwAzAQAAAA==.',Dr='Dracdeeznuts:BAAALAADCgcIBwABLAAECggIJgAVAIMfAA==.Dracolock:BAAALAADCgcIEQAAAA==.Dragorax:BAAALAADCgEIAQAAAA==.Drogons:BAAALAADCgIIAgAAAA==.Drunkenfurry:BAABLAAECoEVAAQHAAgIrg7DHQBwAQAHAAcIuRDDHQBwAQAXAAgIAAP5RACpAAAWAAIIoAPFRwAlAAAAAA==.',Du='Dulla:BAAALAAECgMIBAAAAA==.',['Dá']='Dánte:BAAALAADCgcIDAAAAA==.',['Dé']='Déáth:BAAALAAECgIIAgAAAA==.',Ea='Earthlyfury:BAAALAADCgMIAwAAAA==.',Eb='Eben:BAABLAAECoEVAAIVAAcIVxMoqwBuAQAVAAcIVxMoqwBuAQAAAA==.',Ef='Efmeinthea:BAAALAADCgYICQAAAA==.',Ek='Ekoh:BAAALAAECgIIAwAAAA==.',El='Elanio:BAAALAAECggIEgAAAA==.Elaniodk:BAAALAAECggIEAAAAA==.Elema:BAABLAAECoEZAAIRAAcIEhKRagCfAQARAAcIEhKRagCfAQABLAAFFAUIDQAXANMUAA==.Elevenfour:BAABLAAECoEaAAIfAAgIohJEGgAuAgAfAAgIohJEGgAuAgAAAA==.Eligia:BAAALAADCggICAAAAA==.Elive:BAAALAAECggIEAABLAAFFAgIFgAeABAbAA==.Ellington:BAAALAAECgIIAgAAAA==.Elphabar:BAAALAADCggIDwAAAA==.Elsuck:BAAALAAECgIIAgAAAA==.Elvin:BAAALAAECggIDAAAAA==.Elyino:BAAALAAECggIDQAAAA==.Elysara:BAAALAAECgIIAgAAAA==.',En='Enhich:BAAALAADCgEIAQAAAA==.',Ep='Ephe:BAAALAADCgEIAQAAAA==.',Es='Eske:BAAALAAECgIIAgAAAA==.',Ev='Evilhunt:BAAALAAECgcICgABLAAECggIGAAdAHYbAA==.Evilpriest:BAAALAAECgQIBQABLAAECggIGAAdAHYbAA==.Evokaz:BAAALAAECgYICgAAAA==.Evokyrrh:BAAALAADCggIDQAAAA==.',Ex='Exalto:BAAALAADCggIIAAAAA==.',Fa='Fad:BAABLAAECoEjAAIPAAgIbxZqNQAkAgAPAAgIbxZqNQAkAgAAAA==.Faracane:BAAALAADCggIDwAAAA==.Fartingonyou:BAACLAAFFIEJAAIRAAIIZx0MJACwAAARAAIIZx0MJACwAAAsAAQKgSgAAhEACAiQI6wMACUDABEACAiQI6wMACUDAAAA.',Fe='Felonious:BAAALAADCgUIBQAAAA==.Feyadjin:BAAALAAECgcIDQAAAA==.',Fi='Filty:BAABLAAECoEiAAIcAAgIlxR+RQDdAQAcAAgIlxR+RQDdAQAAAA==.Fimbultyr:BAABLAAECoETAAIiAAgIex4hDAC3AgAiAAgIex4hDAC3AgAAAA==.',Fl='Florhavelin:BAAALAAECggIEQAAAA==.Flyingaround:BAAALAAECgYIBgABLAAFFAMIBgAWAKEKAA==.',Fo='Foeror:BAAALAAECgIIAgAAAA==.Folwin:BAAALAADCgMIAwAAAA==.Foxhy:BAAALAAECgIIAwAAAA==.Foxymaz:BAABLAAECoEZAAIaAAcIvgx5hgBkAQAaAAcIvgx5hgBkAQAAAA==.',Fr='Freindy:BAAALAAECgIIAgAAAA==.Frieren:BAABLAAECoEUAAIiAAgIkA+6JgDEAQAiAAgIkA+6JgDEAQAAAA==.Frostchamp:BAAALAAECgIIAQAAAA==.Frostos:BAAALAAECgYIEgAAAA==.',Fu='Furlie:BAAALAAECgMIBgAAAA==.Furryming:BAAALAADCggICAAAAA==.',['Fë']='Fëdedyr:BAAALAADCggIEgAAAA==.',Ga='Gardyn:BAACLAAFFIEGAAIJAAII5R3HEgCiAAAJAAII5R3HEgCiAAAsAAQKgSIAAgkACAimI+gIACIDAAkACAimI+gIACIDAAAA.Garstang:BAAALAAECgIIAgABLAAFFAYIEwAYAKMbAA==.',Ge='Gethope:BAAALAAECgYIDwABLAAFFAQICgASAH8XAA==.',Gh='Ghaddaffi:BAAALAAECgIIBgAAAA==.',Gi='Giddly:BAAALAAECgQIBAAAAA==.',Gl='Glass:BAAALAADCgcIBwAAAA==.Glide:BAAALAAFFAIIAgABLAAECggIJwACAP4iAA==.',Gn='Gnarss:BAABLAAECoEXAAIEAAgIXBynEgCbAgAEAAgIXBynEgCbAgAAAA==.',Go='Goldenballs:BAAALAAECgcIEAAAAA==.Gorian:BAABLAAECoEZAAMXAAgIyBgLFABHAgAXAAgIyBgLFABHAgAHAAUIIBVjKAAIAQAAAA==.Goronmalares:BAABLAAECoEZAAIIAAcI5g6hTwBuAQAIAAcI5g6hTwBuAQAAAA==.Gortan:BAAALAADCgYIBgAAAA==.Gorwen:BAAALAAECgYIDAAAAA==.Gowithit:BAAALAAECgUICgABLAAECggIEAAZAAAAAA==.',Gr='Graohl:BAAALAAECgQIBgABLAAFFAMIBwAdAMcfAA==.Gravastar:BAAALAAECgYIBwAAAA==.Greenranger:BAAALAAECgcICwAAAA==.Greenwish:BAAALAADCggIEwAAAA==.Griglosh:BAABLAAECoEVAAIPAAcIqBuIMgAxAgAPAAcIqBuIMgAxAgAAAA==.Grimbo:BAAALAAECgYICgAAAA==.Grimhoof:BAAALAAECgcICQAAAA==.Grimnoir:BAAALAADCgUIBgAAAA==.Gristea:BAAALAAFFAIIAgAAAA==.Grizzlyadamz:BAAALAAECggICwAAAA==.Grysti:BAABLAAECoEiAAICAAgIdhrBFgBFAgACAAgIdhrBFgBFAgAAAA==.Gráhl:BAAALAAECgIIAgABLAAFFAMIBwAdAMcfAA==.Gráhll:BAAALAAECgcIEAABLAAFFAMIBwAdAMcfAA==.Grísty:BAAALAAECgcIDAAAAA==.',Gu='Gulpan:BAABLAAECoEcAAISAAcI8RCuVwCuAQASAAcI8RCuVwCuAQAAAA==.',Gw='Gwynevere:BAABLAAECoEYAAIiAAcIMyHxDQCdAgAiAAcIMyHxDQCdAgAAAA==.',Gy='Gyardos:BAABLAAECoErAAIHAAgIRxmeEQANAgAHAAgIRxmeEQANAgAAAA==.',Ha='Hallowhunt:BAAALAAECgcIDQABLAAFFAMICQATAIYcAA==.Hallów:BAACLAAFFIEJAAQTAAMIhhwBBgDdAAATAAIIHCUBBgDdAAAgAAIICxZ2CQCQAAAVAAEIWgt+XwBSAAAsAAQKgRkAAhMACAgCIk0EAAwDABMACAgCIk0EAAwDAAAA.Halycon:BAAALAAECgQIBAABLAAECggIHwASAJoeAA==.Hamburger:BAAALAADCggICAAAAA==.Harnessa:BAAALAADCgEIAQAAAA==.Hazian:BAABLAAECoEYAAMCAAcIdhRFMwB1AQACAAcIdhRFMwB1AQAPAAIIXg3esgB1AAAAAA==.',He='Headshotter:BAAALAADCgYIBgAAAA==.Healyhemmo:BAAALAADCggIEwAAAA==.Heckster:BAAALAAECgIIAgAAAA==.Heldigt:BAAALAAFFAIIAgAAAA==.',Hi='Hickle:BAAALAAECgUICQAAAA==.Hikee:BAAALAAECgEIAQABLAAECggIFQALAOEJAA==.Hikeedevo:BAABLAAECoEVAAILAAgI4Qn+KwCZAQALAAgI4Qn+KwCZAQAAAA==.Hilly:BAAALAADCgMIAwAAAA==.',Ho='Homlessasian:BAAALAAECgYIBgABLAAECgYICAAZAAAAAA==.Hottubshed:BAAALAADCggICAAAAA==.',Hu='Huntardinho:BAAALAAECgEIAQAAAA==.Huntardx:BAACLAAFFIELAAIbAAMIaiQ9BwA+AQAbAAMIaiQ9BwA+AQAsAAQKgSgAAhsACAhRJrgAAIADABsACAhRJrgAAIADAAAA.Hurr:BAABLAAECoEZAAIFAAcIpSIlHwDDAgAFAAcIpSIlHwDDAgAAAA==.',Hy='Hydroxide:BAAALAADCgYIBgAAAA==.',Ib='Ibuprofen:BAAALAAECgQIBQAAAA==.',Id='Idomagic:BAAALAAECgQIBwAAAA==.',Ig='Ige:BAAALAAECgYIBgAAAA==.',Ik='Ikabod:BAABLAAECoEXAAMMAAgIXxy1DACFAgAMAAgIXxy1DACFAgASAAUIKQ/KkAANAQAAAA==.',Il='Illiduh:BAAALAAECgIIBQAAAA==.Illmercius:BAAALAADCgEIAQAAAA==.',Im='Imagfu:BAAALAADCgYIBgABLAAECgcIDwAZAAAAAA==.',Io='Iova:BAAALAADCgcIDQABLAAFFAQIBgAIAOoTAA==.',Ir='Irina:BAAALAAECggIEgAAAA==.',Is='Isukki:BAAALAAECggIBwAAAA==.',Ja='Jafka:BAAALAADCggICAABLAAECggIKQAXADglAA==.Janko:BAABLAAECoEeAAIjAAcIgQgkFwBGAQAjAAcIgQgkFwBGAQAAAA==.Janra:BAAALAAECgcIEwAAAA==.Jantharas:BAAALAAECgMIAwAAAA==.Jatra:BAAALAAECgIIAwAAAA==.',Je='Jejoba:BAACLAAFFIEJAAIPAAIIfCEXFQC8AAAPAAIIfCEXFQC8AAAsAAQKgSQAAg8ACAgzJD4JAD8DAA8ACAgzJD4JAD8DAAAA.Jeph:BAAALAAECgUIBQAAAA==.Jexie:BAAALAADCgYIBgAAAA==.Jezzilla:BAABLAAECoEcAAINAAcIWRLiPgCAAQANAAcIWRLiPgCAAQAAAA==.',Jg='Jgglybeard:BAAALAADCggIDgAAAA==.',Ji='Jiraip:BAAALAAECgUICAAAAA==.Jirais:BAAALAADCgUIBgAAAA==.',Jo='Jordín:BAAALAAECggIDgABLAAFFAIIBgAJAOUdAA==.',Jr='Jrc:BAAALAAECgEIAQAAAA==.',Ju='Juppinn:BAAALAAECgYICAAAAA==.Justine:BAAALAADCgEIAQAAAA==.',Ka='Kaeyl:BAAALAADCggIDgABLAAECggIFQARAJMQAA==.Karage:BAAALAAECgYIDwAAAA==.Karatea:BAAALAAECgYICAAAAA==.Karlak:BAABLAAECoEbAAIcAAgIhg3ccABiAQAcAAgIhg3ccABiAQAAAA==.Katete:BAABLAAECoEaAAIIAAcIVhLmRACYAQAIAAcIVhLmRACYAQAAAA==.',Ke='Kegfist:BAAALAADCggIEAAAAQ==.Keldorai:BAAALAAECgYICAAAAA==.Kenza:BAABLAAECoElAAMEAAgItCR7AwBAAwAEAAgItCR7AwBAAwANAAEI4woPjwAsAAAAAA==.Kerwin:BAABLAAECoEeAAIPAAgIRSHFEgD2AgAPAAgIRSHFEgD2AgAAAA==.',Kh='Khamsin:BAAALAAECggIEQAAAA==.',Ki='Killerdwarfi:BAACLAAFFIEGAAIMAAMIpCPFAABKAQAMAAMIpCPFAABKAQAsAAQKgS0ABAwACAgwJswAAHkDAAwACAgwJswAAHkDABIAAgi+EGO3AIQAACQAAQicEUo2AEUAAAAA.Kimnadine:BAAALAADCggICAAAAA==.',Kl='Klopuu:BAABLAAECoEXAAIEAAcIqhwOIAA9AgAEAAcIqhwOIAA9AgAAAA==.',Ko='Kobaydwarf:BAABLAAECoEZAAIaAAcINR8ULQBeAgAaAAcINR8ULQBeAgAAAA==.Kobaymage:BAAALAADCggICAAAAA==.Koevoet:BAAALAAECgMIAwAAAA==.Koii:BAAALAADCggICAABLAAECgcIFQAMAN8bAA==.Kolgan:BAABLAAECoEbAAMQAAgIYiLzBAAWAwAQAAgIYiLzBAAWAwAlAAMIEBUIUQCuAAAAAA==.Koutsojohn:BAAALAAECgMIBgAAAA==.',Kr='Kraghse:BAAALAADCgMIAwAAAA==.Kronös:BAAALAAECggICAAAAA==.',Ku='Kum:BAAALAAFFAEIAgAAAA==.',Ky='Kyphi:BAAALAADCgUICAAAAA==.Kyrill:BAAALAAECgYICwAAAA==.',['Kí']='Kíllumínatí:BAAALAAECgIIAgAAAA==.',La='Lateksii:BAAALAADCggICAAAAA==.Lav:BAAALAAECgYICgAAAA==.Layluu:BAAALAADCgYIBgAAAA==.Lazeil:BAAALAAECgYICAAAAA==.Lazymage:BAABLAAECoEUAAMiAAgIoByvFwA1AgAiAAgIoByvFwA1AgARAAEISgN15AAbAAAAAA==.Lazywar:BAAALAAECgUIBwABLAAECggIFAAiAKAcAA==.',Ld='Lddr:BAACLAAFFIENAAIGAAYI1xwyAQBEAgAGAAYI1xwyAQBEAgAsAAQKgScAAgYACAgiJjcEAHEDAAYACAgiJjcEAHEDAAAA.',Le='Ledia:BAAALAAECgMIAwAAAA==.Legitqp:BAACLAAFFIEIAAIRAAII3xC+MQCYAAARAAII3xC+MQCYAAAsAAQKgSUAAhEACAjDGmorAH4CABEACAjDGmorAH4CAAAA.Leluelf:BAABLAAECoEYAAINAAcIXwnVSwBFAQANAAcIXwnVSwBFAQAAAA==.Leluhunter:BAAALAADCgcIBwAAAA==.Leviáthan:BAAALAAECgcIBwABLAAECgcIEgAZAAAAAA==.',Li='Lickmycrít:BAAALAAECgYICAAAAA==.Lifedrain:BAAALAAECggICAAAAA==.Lightbane:BAAALAADCgcIBwAAAA==.Lightdarkie:BAABLAAECoEWAAMGAAcIRxPwdgDEAQAGAAcIRxPwdgDEAQAQAAEI6QecXgAoAAAAAA==.Lightningsky:BAAALAAECgYIDAAAAA==.Lilei:BAAALAADCgUIBQAAAA==.Lineu:BAABLAAFFIELAAIEAAYIyArBAwCpAQAEAAYIyArBAwCpAQAAAA==.Linnae:BAABLAAECoEgAAQJAAgILhmmOgCuAQAJAAcIsRemOgCuAQAIAAgIOw1FRACbAQAKAAQILA3fHADEAAAAAA==.',Lo='Lockley:BAAALAADCgcIBwAAAA==.Lokaron:BAAALAADCggICAAAAA==.Lopac:BAAALAAECgcIEAAAAA==.Lorewalkerpø:BAAALAAECgYIDAAAAA==.Lorhas:BAABLAAECoEmAAIcAAgIZx9gFwCdAgAcAAgIZx9gFwCdAgAAAA==.Lorna:BAAALAAECgEIAQABLAAECggIHgAPAEUhAA==.Lozknight:BAABLAAECoEkAAIgAAgIGSJ9BQD1AgAgAAgIGSJ9BQD1AgAAAA==.',Lu='Luciferion:BAAALAAECgYICwAAAA==.Lucyfer:BAAALAADCgYIDAAAAA==.',Ly='Lynnepanda:BAAALAADCgcIDAAAAA==.Lysandria:BAAALAADCgYIDAAAAA==.Lysteriax:BAAALAADCgEIAQAAAA==.Lyza:BAABLAAECoEhAAMbAAgIvhiXIABGAgAbAAgIvhiXIABGAgAaAAMIFAut5AB9AAAAAA==.',['Là']='Làvelý:BAAALAAECgIIAgAAAA==.',Ma='Mad:BAAALAADCgUIBQAAAA==.Maeri:BAAALAADCggIFgAAAA==.Mafmuts:BAAALAAECgEIAQABLAAECggIHAAWAD8OAA==.Magill:BAAALAAECgYIBgAAAA==.Mahamatra:BAAALAADCggICAAAAA==.Mamsbeauty:BAABLAAECoEYAAIaAAcIrA1IhQBmAQAaAAcIrA1IhQBmAQAAAA==.Margarett:BAAALAAECgYIBgABLAAFFAMICAALAHkJAA==.Marilith:BAAALAADCggIGQAAAA==.Markfallen:BAAALAADCgUIBQAAAA==.Math:BAABLAAECoEUAAMQAAYILB4wGQDwAQAQAAYILB4wGQDwAQAGAAYIVArtwQA3AQAAAA==.',Me='Medyza:BAAALAAECgYIEwAAAA==.Melampus:BAAALAAECgIIBAAAAA==.Meleager:BAAALAAECgIIAwAAAA==.Merliandra:BAAALAAECggIEwAAAA==.Merranderr:BAABLAAECoEVAAISAAgIqhLESQDdAQASAAgIqhLESQDdAQAAAA==.Merraveth:BAAALAADCggICAAAAA==.Metalhooves:BAAALAADCgUIBQAAAA==.',Mi='Mightysloth:BAABLAAECoEfAAIaAAgIXCV2CQAwAwAaAAgIXCV2CQAwAwAAAA==.Mikanni:BAABLAAECoEbAAIRAAgIfR0vLQB1AgARAAgIfR0vLQB1AgAAAA==.Milojin:BAAALAAECgcIEAAAAA==.Miloladin:BAAALAADCggIFgABLAAECgcIEAAZAAAAAA==.Mishi:BAAALAADCgIIAgAAAA==.Missflame:BAAALAAECggICAAAAA==.Mistpirit:BAABLAAECoEbAAIXAAgI+hNZGQALAgAXAAgI+hNZGQALAgAAAA==.',Mo='Moo:BAACLAAFFIEZAAIQAAYIASRAAAB+AgAQAAYIASRAAAB+AgAsAAQKgTQAAhAACAjOJiYAAJ0DABAACAjOJiYAAJ0DAAAA.Mooglo:BAACLAAFFIEFAAIlAAIIQw0FFACUAAAlAAIIQw0FFACUAAAsAAQKgSUAAiUACAiFGfMWACcCACUACAiFGfMWACcCAAAA.Moonowl:BAAALAAECgIIAwAAAA==.Moonshift:BAAALAAECgYIBgAAAA==.Moonwolf:BAAALAAECgIIAgAAAA==.Moradine:BAAALAAECgYIDAABLAAECggIFQAmAA0iAA==.Morilith:BAABLAAECoEdAAIFAAcIwxNhawC7AQAFAAcIwxNhawC7AQAAAA==.Morningstar:BAAALAAECgYIDwAAAA==.Morphfang:BAABLAAECoEXAAQEAAcIkBY0MwDZAQAEAAcIkBY0MwDZAQANAAcI3w+wOgCUAQADAAEIOgPZQgAaAAAAAA==.Mosheh:BAABLAAECoEWAAIcAAgINxS/VwCoAQAcAAgINxS/VwCoAQAAAA==.Motto:BAAALAAECgYIEgAAAA==.Moxzin:BAAALAAECgMIAwAAAA==.',Mu='Mudder:BAAALAADCggIDgAAAA==.Muddles:BAABLAAECoEZAAImAAcI2w3dEwBNAQAmAAcI2w3dEwBNAQAAAA==.Mudlock:BAAALAAECgcIEAAAAA==.Multiruss:BAAALAAECgUIBQAAAA==.',My='Mystfall:BAACLAAFFIEMAAIaAAUIHxAGCAB5AQAaAAUIHxAGCAB5AQAsAAQKgS4AAhoACAjSIS8aAMACABoACAjSIS8aAMACAAAA.',['Mö']='Möonhunter:BAAALAADCgcIBwAAAA==.',Ne='Nephes:BAAALAAECgQIBQAAAA==.Nerishanna:BAAALAAECgEIAQAAAA==.Newstrand:BAAALAAECgEIAQAAAA==.Nexen:BAAALAADCgcIEAAAAA==.',Ni='Nightfrozen:BAAALAAECgUIBQABLAAECgcIFgAGAEcTAA==.Niranu:BAAALAAECgUICQAAAA==.Niridami:BAABLAAECoEiAAIGAAgIIB2PLACTAgAGAAgIIB2PLACTAgAAAA==.Nishva:BAAALAADCgcIBwABLAAECgYIFAAQACweAA==.Nitze:BAAALAAECgIIAgAAAA==.',No='Nodri:BAAALAAECgEIAQAAAA==.Norzhyl:BAAALAADCggIGQAAAA==.Notsoawsome:BAABLAAECoEaAAIaAAgILxHMYwCxAQAaAAgILxHMYwCxAQAAAA==.',Nu='Nudgess:BAABLAAECoEgAAIWAAcIaRKwHQCJAQAWAAcIaRKwHQCJAQAAAA==.Nutelia:BAAALAADCgcIEgAAAA==.',Oc='Oculeth:BAAALAADCgEIAQAAAA==.',Oi='Oiche:BAAALAADCgYIBgAAAA==.',Ol='Olidh:BAAALAAECgQIBAAAAA==.',On='Oneladylike:BAAALAADCggICAAAAA==.Onenightstab:BAACLAAFFIELAAMfAAMIlxj3CQD4AAAfAAMIkxX3CQD4AAAeAAEIHgomFgBBAAAsAAQKgTMAAx4ACAgeIJwRAPMBAB8ABgjSH4YaACwCAB4ABggJHZwRAPMBAAAA.Onias:BAAALAAECgIIAwAAAA==.Onitaiji:BAAALAAECgEIAQAAAA==.Onlyhots:BAAALAAECgMIAgABLAAFFAMICAALAHkJAA==.',Or='Orangessham:BAAALAAECgYIBgAAAA==.Orclander:BAAALAAECgMIAwAAAA==.Orcrizz:BAAALAADCgYIDAAAAA==.Oromer:BAACLAAFFIEGAAIGAAIIMBtgHQCuAAAGAAIIMBtgHQCuAAAsAAQKgSgAAgYACAifJI4IAFMDAAYACAifJI4IAFMDAAAA.Oromiz:BAAALAAECgYIEgABLAAFFAIIBgAGADAbAA==.',Oz='Ozamudazai:BAAALAADCggIEAABLAADCggIEAAZAAAAAA==.',Pa='Painkilla:BAAALAAECgUIBQAAAA==.Palacetamol:BAAALAAECgcICgAAAA==.Palanes:BAAALAADCgIIAgAAAA==.Paluman:BAABLAAECoEYAAIQAAcI/B3DEQA9AgAQAAcI/B3DEQA9AgAAAA==.Pandamoneum:BAAALAAECgUIBQAAAA==.Pandamonioom:BAAALAAECgYICAABLAAECgcIEAAZAAAAAA==.Pandelement:BAAALAAECgMIAwAAAA==.Paterson:BAAALAAECgQIAwABLAAECggIFQAVAFcTAA==.Pats:BAABLAAECoEdAAMRAAcIUhOwWADTAQARAAcIUhOwWADTAQAiAAIIUgVvdQBHAAABLAAECggIFQAVAFcTAA==.Patso:BAABLAAECoEXAAMbAAgIJA7qYQAXAQAaAAcIngxUlgBEAQAbAAgIzgnqYQAXAQAAAA==.Patts:BAAALAADCggIDwABLAAECggIFQAVAFcTAA==.Paxsor:BAAALAADCgMIAgAAAA==.Païnkïller:BAAALAADCgQIBAAAAA==.',Pe='Pergamon:BAAALAADCgcIBwAAAA==.Pestilënce:BAACLAAFFIEFAAIVAAIIliC/IwC0AAAVAAIIliC/IwC0AAAsAAQKgSsAAhUACAgQIg0PACUDABUACAgQIg0PACUDAAEsAAUUAwgIAAsAeQkA.Pete:BAACLAAFFIEFAAIhAAMI6ASTFAC2AAAhAAMI6ASTFAC2AAAsAAQKgRgAAiEACAiHF/wiAGcCACEACAiHF/wiAGcCAAAA.Pewsquared:BAAALAAECgMIAwAAAA==.',Ph='Pheea:BAAALAADCggIEAAAAA==.Phôebe:BAAALAAECgMIAwAAAA==.',Pi='Pijltje:BAAALAAECgcIBwAAAA==.',Po='Popeslapme:BAAALAAECggICAABLAAFFAMICAALAHkJAA==.Popiku:BAAALAADCggICAAAAA==.Posof:BAACLAAFFIEIAAIOAAIIOBBKBQCYAAAOAAIIOBBKBQCYAAAsAAQKgSQAAg4ACAgEG4AGAIwCAA4ACAgEG4AGAIwCAAAA.',Pu='Punchnkick:BAAALAAECgQIAgAAAA==.',Py='Pyranna:BAAALAADCgYICAAAAA==.',['Pá']='Párzival:BAAALAAECggIAwAAAA==.',Qs='Qsq:BAAALAADCgcIBwAAAA==.',Qu='Qudeda:BAABLAAECoEgAAQIAAcIJxK/RACZAQAIAAcIJxK/RACZAQAJAAQIvA97YQDxAAAKAAMIUgeLKQBYAAAAAA==.',Ra='Radopinecone:BAAALAAECgYIDAAAAA==.Rakas:BAAALAAECggIDAABLAAECggIHQAFAAUhAA==.Ravensoul:BAABLAAECoEdAAIDAAgIcxYjDQBRAgADAAgIcxYjDQBRAgAAAA==.Rayaan:BAAALAADCggICAAAAA==.Razna:BAABLAAECoEdAAINAAcIfCDbFQCHAgANAAcIfCDbFQCHAgAAAA==.',Re='Redleg:BAAALAAECgcIEgABLAAECggIJgAVAIMfAA==.Regilio:BAAALAADCggICAABLAAECggIGAAdAHYbAA==.Relcloud:BAAALAAECgYIBgAAAA==.Renadriel:BAABLAAECoEbAAIlAAcIfw3LNwBGAQAlAAcIfw3LNwBGAQAAAA==.Repayment:BAAALAAECgcIDQAAAA==.Revienor:BAAALAADCggIDQAAAA==.',Ri='Rianna:BAAALAADCgcICAAAAA==.Rikai:BAAALAAECgcIDAAAAA==.Rikky:BAACLAAFFIEUAAINAAYI7x/RAABZAgANAAYI7x/RAABZAgAsAAQKgS8AAg0ACAiFJsQAAIsDAA0ACAiFJsQAAIsDAAAA.Rishep:BAAALAADCggIDQAAAA==.',Ro='Rognesh:BAAALAAECgYIDwAAAA==.Rollinger:BAAALAADCggICAAAAA==.',Ru='Rumia:BAAALAAECgcIEwAAAA==.Ruza:BAAALAAECgQIBAAAAA==.',Sa='Salita:BAAALAADCggIHAAAAA==.Salmanrushdi:BAAALAADCgcICQAAAA==.Salém:BAAALAAECgYIEgAAAA==.Sanatoré:BAAALAAECgIIBAAAAA==.Sanning:BAAALAAECgYIBgAAAA==.Sardothien:BAAALAAECgMIAwAAAA==.Sausage:BAAALAAECgYIEgABLAAFFAMIBQAEAHIMAA==.',Se='Senzapiombo:BAAALAADCgIIAgAAAA==.Sephiroo:BAAALAADCgcIBwAAAA==.Serf:BAAALAADCgcIBwAAAA==.Serpentt:BAAALAADCgIIAgAAAA==.Sevensausage:BAAALAAECgUIBQABLAAFFAUIDwAhABQPAA==.',Sh='Shabagooba:BAAALAADCggICAAAAA==.Shame:BAAALAADCgIIAgAAAA==.Shark:BAABLAAECoEeAAIPAAgIaiG/EAAFAwAPAAgIaiG/EAAFAwAAAA==.Sharkownz:BAAALAADCggICAABLAAECggIHgAPAGohAA==.Shatterlyn:BAAALAADCggIEAAAAA==.Shaðd:BAAALAAECgUICQABLAAFFAMICQASALwWAA==.Shaðð:BAACLAAFFIEJAAMSAAMIvBbWIgCkAAASAAII8hLWIgCkAAAMAAEITh5NGgBbAAAsAAQKgSUABAwACAigGx8VAC8CABIACAgXGF0wAEgCAAwACAgwGR8VAC8CACQAAQj4ENw1AEYAAAAA.Shiftpala:BAACLAAFFIEGAAIQAAIIyBcWCwCSAAAQAAIIyBcWCwCSAAAsAAQKgScAAhAACAhJIJsGAPACABAACAhJIJsGAPACAAAA.Shinkawa:BAAALAADCgcIBwAAAA==.Shoggun:BAABLAAECoEUAAIPAAgIohsIHgCnAgAPAAgIohsIHgCnAgABLAAFFAMICAALAHkJAA==.Sháx:BAACLAAFFIEFAAIVAAIIBySFGwDQAAAVAAIIBySFGwDQAAAsAAQKgSUAAhUACAhXIz8ZAO0CABUACAhXIz8ZAO0CAAAA.',Si='Siemano:BAABLAAECoEUAAINAAYIVxAtSABVAQANAAYIVxAtSABVAQAAAA==.Sigyn:BAABLAAECoEfAAInAAgIhA4CCQD3AQAnAAgIhA4CCQD3AQAAAA==.Silmaril:BAABLAAECoEVAAIlAAgI2xdIFQA2AgAlAAgI2xdIFQA2AgAAAA==.Sinic:BAAALAADCggIBwAAAA==.Sionuazel:BAAALAADCgIIAgAAAA==.',Sk='Skallepär:BAAALAADCggICAAAAA==.Skinkefeen:BAAALAAECgEIAQAAAA==.Skrude:BAAALAAECgIIAgABLAAECgYICQAZAAAAAA==.Skyeblue:BAAALAAECgYIDAAAAA==.Skyggepræst:BAAALAAECggICAAAAA==.',Sl='Slaan:BAABLAAECoEhAAMXAAgI0Bt/DwCBAgAXAAgI0Bt/DwCBAgAWAAQIDQk3OQCXAAAAAA==.Slobbo:BAAALAADCggICAABLAADCggIEAAZAAAAAQ==.Slubz:BAAALAAECgcICQAAAA==.',Sn='Snuv:BAABLAAECoElAAISAAgI1yTABgBRAwASAAgI1yTABgBRAwAAAA==.',So='Socarim:BAAALAADCgUIBQAAAA==.Soluna:BAAALAAECgQIBAABLAAECgcIEwAZAAAAAA==.Sonnyy:BAAALAAECgYIDQAAAA==.Soshinoki:BAAALAAECgIIAgAAAA==.Soulstalker:BAAALAAECgUIBQABLAAECgcIFwAEAJAWAA==.',Sq='Sqezz:BAAALAADCgEIAQAAAA==.',St='Stabdonna:BAAALAAECgcIDAAAAA==.Starie:BAAALAAECggIDgAAAA==.Starsurge:BAABLAAECoEXAAINAAgIaR5EEgCuAgANAAgIaR5EEgCuAgAAAA==.Stillsong:BAAALAAECgcIBQAAAA==.',Su='Sufix:BAAALAAECgIIAgAAAA==.Sukia:BAAALAADCgcICgAAAA==.',Sy='Sylarel:BAAALAAECgIIAgAAAA==.Sync:BAAALAADCgcIDAAAAA==.',['Sá']='Sátan:BAAALAADCgMIAwAAAA==.Sáyne:BAAALAAECgEIAQAAAA==.',['Sä']='Säphira:BAAALAADCgcIBwAAAA==.',Ta='Taelorea:BAACLAAFFIEFAAIVAAMICQy6GgDUAAAVAAMICQy6GgDUAAAsAAQKgS0AAhUACAjHHWArAJoCABUACAjHHWArAJoCAAAA.Takeidi:BAAALAADCggIDwABLAAECgcIFwAIAN8QAA==.Takeily:BAABLAAECoEXAAIIAAcI3xAPRwCQAQAIAAcI3xAPRwCQAQAAAA==.Takeimo:BAAALAADCggIDgABLAAECgcIFwAIAN8QAA==.Tal:BAAALAADCggICAAAAA==.Tamagotchi:BAAALAAECgIIAgAAAA==.Tank:BAAALAADCggICAABLAAFFAYIGQAQAAEkAA==.Tatsuya:BAAALAADCgcICgAAAA==.Taunt:BAAALAAECgYIBgAAAA==.',Te='Teamtek:BAACLAAFFIERAAIhAAUIXBHTBgC3AQAhAAUIXBHTBgC3AQAsAAQKgS8AAiEACAg/Iy0IAD8DACEACAg/Iy0IAD8DAAAA.Teeti:BAAALAAECgYIBgAAAA==.Tehenhuain:BAAALAADCgYIAwAAAA==.Tellos:BAAALAADCggIDgABLAAECgYIEgAZAAAAAA==.Temutai:BAAALAADCgYIBgAAAA==.Temutank:BAAALAAECggIDQAAAA==.Tenegor:BAAALAADCgcIDgAAAA==.Tezz:BAAALAADCggIDAAAAA==.Teí:BAAALAAECggICAAAAA==.',Th='Thaelion:BAAALAADCggIEwAAAA==.Tharlin:BAAALAAECgIIAwAAAA==.Thefezz:BAAALAAECgcICwAAAA==.Thegreyorion:BAAALAAECgIIAgAAAA==.Thelin:BAAALAADCgcIBwAAAA==.Themoonlight:BAAALAAECgYIBgAAAA==.Theomet:BAAALAADCggIDQAAAA==.Thepurifier:BAAALAAECgMIAwAAAA==.Theqila:BAACLAAFFIEGAAIIAAQI6hMHDAAHAQAIAAQI6hMHDAAHAQAsAAQKgSMAAggACAgyH1cOAN0CAAgACAgyH1cOAN0CAAAA.Therighteous:BAAALAADCgcICwAAAA==.Thevelen:BAAALAAECgcIDQAAAA==.Thorale:BAAALAAECgUICAAAAA==.Thundérshade:BAACLAAFFIEPAAIJAAUIpB3lAwDsAQAJAAUIpB3lAwDsAQAsAAQKgSkAAgkACAheJj0BAIMDAAkACAheJj0BAIMDAAAA.Thylathras:BAAALAAECgEIAQAAAA==.Thyne:BAAALAAECgUIBQABLAAECggIFAAJAAUdAA==.Thégrínch:BAAALAADCgYIDAAAAA==.',Ti='Tinyclap:BAAALAAECgYIBwABLAAECggIJgAVAIMfAA==.Tiriiron:BAAALAADCgUIBwAAAA==.',To='Toadslapper:BAAALAADCggIDgABLAAFFAMIBgAWAKEKAA==.Toblock:BAABLAAECoEXAAIMAAcI0APiRgArAQAMAAcI0APiRgArAQAAAA==.Toes:BAAALAADCggIDQAAAA==.Tohono:BAAALAADCgYIBgABLAAECgQIBAAZAAAAAA==.',Tr='Treesamay:BAAALAAECgIIAgAAAA==.Triage:BAABLAAECoEdAAMEAAgIbhK7QQCZAQAEAAcIfhS7QQCZAQANAAEIEQScmAANAAAAAA==.Trol:BAABLAAECoEXAAIhAAgICgh0UACRAQAhAAgICgh0UACRAQAAAA==.Trollbear:BAAALAADCggIBgAAAA==.Tríxy:BAAALAADCggICAAAAA==.',Ts='Tsantuuro:BAAALAAECgYIEAAAAA==.',Tu='Tubez:BAAALAAECgYIDwAAAA==.Tupio:BAAALAAECgcICwAAAA==.',Ty='Tygootjuh:BAAALAAECgQIAQAAAA==.Tyrrax:BAAALAAECgUIBQAAAA==.Tyrtael:BAACLAAFFIEKAAIaAAMIaBxkEADqAAAaAAMIaBxkEADqAAAsAAQKgS0AAhoACAiwI2kTAOoCABoACAiwI2kTAOoCAAAA.Tyrtaele:BAAALAADCggIGAAAAA==.',Un='Unbearabull:BAABLAAECoEYAAIEAAgI/g0vSAB/AQAEAAgI/g0vSAB/AQAAAA==.Unforgiven:BAAALAADCggICAAAAA==.',Ur='Uriel:BAAALAADCggICAAAAA==.',Va='Vaarsanarius:BAAALAADCgcIDgABLAAECgcIEAAZAAAAAA==.Vaduum:BAAALAADCggICAAAAA==.Vaelerise:BAAALAADCgcIBwABLAADCggICAAZAAAAAA==.Valerous:BAAALAAECgYIEgAAAA==.Valinory:BAAALAAECgIIAgAAAA==.Valleydust:BAAALAADCgUIBQAAAA==.Valleyfury:BAAALAADCgYIBwAAAA==.Valleyhunt:BAAALAAECgcIEwAAAA==.Valleymist:BAAALAAECgMIAwAAAA==.Valleymoon:BAABLAAECoEZAAIEAAcIfyB1GQBnAgAEAAcIfyB1GQBnAgAAAA==.Valvari:BAABLAAECoEiAAMJAAgIdxPoKgAEAgAJAAgIdxPoKgAEAgAIAAMInA3RhgCaAAAAAA==.Vandris:BAAALAAECgEIAQABLAAECggIHgAPAEUhAA==.Vaolen:BAAALAADCgYIBgABLAAECggIHgAPAEUhAA==.',Ve='Veiria:BAAALAAECgEIAQAAAA==.Vek:BAAALAADCgUICgAAAA==.Verekore:BAAALAADCgcIBwAAAA==.Verity:BAAALAAECgIIAwAAAA==.Veyrix:BAAALAADCggIDgAAAA==.',Vi='Videogames:BAAALAAECgMIAwAAAA==.Vikingness:BAAALAAECgcIEwAAAA==.Viollet:BAABLAAECoEbAAMIAAgIfhHCNADiAQAIAAgIfhHCNADiAQAJAAMIGAREewBhAAAAAA==.Virus:BAAALAADCggIEAAAAA==.Visaen:BAACLAAFFIEJAAIGAAMIcyS4CAA8AQAGAAMIcyS4CAA8AQAsAAQKgS0AAwYACAjPJSsEAHIDAAYACAjPJSsEAHIDABAABgi6IX8kAJABAAAA.',Vo='Voiddemon:BAAALAADCgYICgAAAA==.Voidfade:BAAALAADCggICAAAAA==.Voidpriesty:BAAALAADCgcICwAAAA==.Voidstar:BAAALAAECgYICwABLAAECggIJQAEALQkAA==.Vorp:BAABLAAECoEjAAMHAAgISiO8BwDLAgAHAAgI9yC8BwDLAgAXAAgIHhV8FgApAgAAAA==.Voídz:BAAALAADCgQIBAAAAA==.',['Ví']='Víóla:BAABLAAECoEXAAIiAAcIOBUaJQDPAQAiAAcIOBUaJQDPAQAAAA==.',Wa='Warbut:BAAALAADCgIIAgAAAA==.Wargeft:BAAALAADCgYIBgAAAA==.Warlockywoo:BAABLAAECoEbAAISAAgIdhvDIgCSAgASAAgIdhvDIgCSAgAAAA==.Warton:BAAALAAECgMIAwABLAAFFAYIEwAYAKMbAA==.',Wi='Wildi:BAAALAAECgYIEAAAAA==.Winghunter:BAAALAADCgEIAQAAAA==.Wintertooth:BAABLAAECoEYAAIDAAcIOBpzEAAdAgADAAcIOBpzEAAdAgAAAA==.Wipp:BAAALAAECgYIEgAAAA==.',Wo='Wombleshed:BAABLAAECoEYAAIHAAcIKSKDCAC5AgAHAAcIKSKDCAC5AgAAAA==.',Wt='Wtbname:BAAALAAECgcIDAAAAA==.',Xa='Xaabrak:BAAALAADCggICwAAAA==.Xaben:BAAALAAECgYIEQAAAA==.Xabriel:BAAALAAECgcIEwAAAA==.',Xe='Xendris:BAAALAAECgEIAQAAAA==.',Xi='Xisuka:BAABLAAECoEUAAIhAAgIzRSkMwAKAgAhAAgIzRSkMwAKAgABLAAFFAIIBgAGADAbAA==.',Xy='Xylor:BAAALAAFFAIIAgAAAQ==.Xylordh:BAAALAADCggICAABLAAFFAIIAgAZAAAAAA==.Xylorsh:BAAALAAECgYIBgABLAAFFAIIAgAZAAAAAQ==.Xyo:BAAALAAECgEIAQABLAAECgcIEwAZAAAAAA==.Xyothene:BAAALAADCggIEQABLAAECgcIEwAZAAAAAA==.',Ya='Yajasu:BAAALAADCggICAAAAA==.',Ye='Yea:BAAALAAECgMIBAAAAA==.Yesusjupp:BAAALAAECgEIAQABLAAECgYICAAZAAAAAA==.',Yo='Yora:BAABLAAECoEaAAIaAAcIjAdCswAGAQAaAAcIjAdCswAGAQAAAA==.',Yu='Yubabazeniba:BAACLAAFFIEPAAIaAAUIzCT+AgD5AQAaAAUIzCT+AgD5AQAsAAQKgS0AAhoACAi5JowBAH8DABoACAi5JowBAH8DAAAA.',Za='Zaijko:BAAALAAECgYICwAAAA==.Zanav:BAAALAADCgQIBAABLAAFFAIIBgAJAAUQAA==.Zarartan:BAAALAADCgYIDAAAAA==.Zaravos:BAABLAAECoEdAAIFAAgIBSFcGgDdAgAFAAgIBSFcGgDdAgAAAA==.Zarry:BAAALAAECggIBwAAAA==.',Ze='Zerotoniaa:BAACLAAFFIEIAAIJAAIIoRLqFgCSAAAJAAIIoRLqFgCSAAAsAAQKgSIAAgkACAjGIVwMAAADAAkACAjGIVwMAAADAAAA.',Zh='Zharelyn:BAAALAAECgcIEgAAAA==.',Zi='Zicklewick:BAAALAADCggIEAAAAA==.Zixex:BAAALAADCgYIDQAAAA==.Ziyala:BAABLAAECoEYAAIcAAcINBBscABkAQAcAAcINBBscABkAQAAAA==.',Zy='Zynadin:BAAALAAECgQIBAAAAA==.',['Áu']='Áura:BAAALAAECgMIAQAAAA==.',['Ðr']='Ðrafi:BAAALAAECgIIAgABLAAECgYICwAZAAAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end