local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Priest-Shadow','Warrior-Fury','Paladin-Retribution','Paladin-Protection','Mage-Frost','Mage-Arcane','DemonHunter-Havoc','Monk-Mistweaver','Unknown-Unknown','Hunter-Marksmanship','Druid-Guardian','Warlock-Destruction','Warlock-Demonology','Warlock-Affliction','DeathKnight-Unholy','Priest-Holy','Rogue-Subtlety','Rogue-Assassination','Paladin-Holy','DemonHunter-Vengeance','Druid-Balance','Shaman-Elemental','Evoker-Augmentation','Evoker-Devastation','DeathKnight-Blood','Shaman-Enhancement','Monk-Brewmaster','Shaman-Restoration','Priest-Discipline','Druid-Feral','Druid-Restoration','DeathKnight-Frost','Hunter-BeastMastery','Warrior-Protection','Warrior-Arms','Evoker-Preservation','Monk-Windwalker',}; local provider = {region='EU',realm='Dentarg',name='EU',type='weekly',zone=44,date='2025-09-06',data={Ab='Able:BAAALAAECgcIDQAAAA==.Abraham:BAABLAAECoEWAAIBAAgImRuyEQCFAgABAAgImRuyEQCFAgAAAA==.Abuse:BAAALAAECggICAAAAA==.',Ae='Aelinel:BAAALAAECgcIEQAAAA==.Aetril:BAAALAAECggICAAAAA==.',Ag='Aglaron:BAAALAAECgYIEQAAAA==.Agnar:BAABLAAECoEXAAICAAgIjRq0EwCLAgACAAgIjRq0EwCLAgAAAA==.',Ai='Ailos:BAABLAAECoEVAAMDAAgIPSXeAgBsAwADAAgIHyXeAgBsAwAEAAcI7yELCwArAgAAAA==.Ainaaen:BAAALAADCggICwAAAA==.Airima:BAAALAAECgcICwAAAA==.Aisuky:BAABLAAECoEeAAMFAAgI5yW+AAB7AwAFAAgI5yW+AAB7AwAGAAIIGRrafgCcAAAAAA==.',Aj='Ajishi:BAAALAADCggIEAAAAA==.',Ak='Akayal:BAAALAAFFAIIAgAAAA==.Akelana:BAAALAADCgcIBwAAAA==.',Al='Alethril:BAAALAADCgcICAAAAA==.Alfi:BAACLAAFFIEGAAIHAAMITg3kCADpAAAHAAMITg3kCADpAAAsAAQKgR0AAgcACAjxGighAFkCAAcACAjxGighAFkCAAAA.Alicebrallis:BAACLAAFFIEFAAIIAAMIcBKyAwD3AAAIAAMIcBKyAwD3AAAsAAQKgRsAAggACAiiIIIDAPUCAAgACAiiIIIDAPUCAAAA.Aliceprallis:BAAALAAECgcIDgABLAAFFAMIBQAIAHASAA==.Alioker:BAAALAAECgUIBQABLAAFFAMIBQAIAHASAA==.Alireza:BAAALAADCggIEAABLAAFFAIIAgAJAAAAAA==.Allamenethil:BAAALAAECgQIBAAAAA==.Alolicoce:BAAALAAECgYIBgAAAA==.Altairius:BAAALAADCggIFQAAAA==.Althala:BAAALAAECgIIAgAAAA==.Althara:BAECLAAFFIEGAAIBAAIIbhCDDgCQAAABAAIIbhCDDgCQAAAsAAQKgR0AAgEACAiJGWIVAFsCAAEACAiJGWIVAFsCAAAA.Altirium:BAAALAADCgMIAwAAAA==.',Am='Amasha:BAAALAADCgcIBwAAAA==.Amelior:BAAALAADCgQIBAAAAA==.Amon:BAAALAAECgcIEwAAAA==.',An='Angrykitten:BAAALAAECggIEAAAAA==.Anillusion:BAAALAAECgMIBgAAAA==.Anitamaxvin:BAAALAAECgEIAQAAAA==.Ankou:BAAALAAECgcIEQAAAA==.Anogros:BAAALAADCgcIBAAAAA==.Anoka:BAAALAAECgMIAwAAAA==.Anvl:BAAALAADCggICAAAAA==.Anx:BAABLAAECoEUAAIKAAcILCbUBQAOAwAKAAcILCbUBQAOAwAAAA==.Anyl:BAAALAAECgYIDgAAAA==.',Ap='Apocalypcys:BAAALAAECgMIBgAAAA==.',Ar='Aradhunt:BAAALAAFFAIIAwAAAA==.Araspatreon:BAAALAADCgMIAwAAAA==.Arathun:BAAALAAECgMIAwAAAA==.Arcy:BAAALAAECgYIBgAAAA==.Aristáeus:BAABLAAECoEXAAILAAgInxv1AgByAgALAAgInxv1AgByAgABLAAFFAMIAwAJAAAAAA==.Arlena:BAABLAAECoEeAAQMAAgImiLiBwAVAwAMAAgIYSHiBwAVAwANAAYIISLLEAAPAgAOAAEIUB9qKgBUAAAAAA==.Artful:BAAALAAECgcIDAAAAA==.',As='Ashragosa:BAAALAAECgMIBgAAAA==.Ashthar:BAAALAAECggIDQAAAA==.',At='Atena:BAAALAAECggICgAAAA==.Atrnim:BAABLAAECoEbAAIPAAgIDhg0CAByAgAPAAgIDhg0CAByAgAAAA==.',Au='Aurelia:BAAALAADCggICQABLAAECgcIFwAIAHAcAA==.Auroth:BAACLAAFFIEIAAIMAAMI3x7wBgAVAQAMAAMI3x7wBgAVAQAsAAQKgRgAAgwACAjKJd8DAEsDAAwACAjKJd8DAEsDAAAA.',Ay='Ayauhteotl:BAAALAAECgMIBQAAAA==.',Az='Azadori:BAAALAAECgYIBgABLAAECggIFQAMAO8bAA==.',Ba='Babar:BAAALAAECgYIDgAAAA==.Babydragon:BAAALAAECgIIAgAAAA==.Balunor:BAABLAAECoEXAAMDAAcINxQiRQDEAQADAAcINxQiRQDEAQAEAAMIcAcHMQBkAAAAAA==.Banelock:BAABLAAECoEUAAIMAAgIOiA5FQCIAgAMAAgIOiA5FQCIAgAAAA==.',Be='Belanor:BAAALAAECgYIEQAAAA==.Bellgare:BAABLAAECoEbAAIDAAgIUhsmIABoAgADAAgIUhsmIABoAgAAAA==.Benchmark:BAAALAAECgIIAwAAAA==.Beop:BAAALAAECgcIDAAAAA==.Bethie:BAAALAAECgYIDgAAAA==.',Bi='Bichii:BAAALAAFFAIIBAAAAA==.Biggan:BAAALAAECgEIAQAAAA==.',Bl='Bleezebub:BAABLAAECoEWAAMBAAgIFBpmFQBaAgABAAgIFBpmFQBaAgAQAAYImQWbTAAJAQAAAA==.Blockhead:BAAALAAFFAIIAwAAAA==.Blurpi:BAABLAAECoEYAAMRAAgILx6NAwDCAgARAAgIyxyNAwDCAgASAAYI4xyjHADXAQAAAA==.',Bo='Bodegamats:BAAALAAECggIEwABLAAECggIHwATACUmAA==.',Br='Brainrot:BAAALAAECgQIBAABLAAECgYIBgAJAAAAAA==.Bremsespor:BAAALAAECggICAABLAAECggIEAAJAAAAAA==.Brewschi:BAAALAAECgMIAwAAAA==.Brockski:BAAALAAECgUIDQAAAA==.',Bu='Buckman:BAABLAAECoEcAAMNAAgIASRmCgBaAgANAAYIzCNmCgBaAgAMAAYIJSDCHgA4AgAAAA==.',Ca='Calliope:BAAALAAECgYICgAAAA==.Calmuri:BAABLAAECoEWAAMHAAgIzR52EwDFAgAHAAgIzR52EwDFAgAUAAEIiQ0bPQAlAAAAAA==.Cancera:BAAALAAECgIIAwAAAA==.Cataclysm:BAAALAAECgMIAwAAAA==.Catnip:BAAALAADCgUIBQAAAA==.Caveman:BAAALAADCgcIBwAAAA==.',Cd='Cdotb:BAAALAAECgQIBAABLAAECggIHAANAAEkAA==.',Ce='Celish:BAABLAAECoEcAAIVAAgIOCJsBwABAwAVAAgIOCJsBwABAwAAAA==.Celu:BAAALAAECgcIDAAAAA==.',Ch='Chaintrain:BAAALAAECgcIEQAAAA==.Chaospuss:BAAALAADCgcIBwAAAA==.Cheriza:BAAALAADCgcIBwAAAA==.Chesha:BAAALAAECgYIEQAAAA==.Chipsoman:BAAALAAECggIEgAAAA==.Chokomilkgtl:BAAALAAFFAIIBAAAAA==.Chokomilky:BAAALAAFFAIIAgABLAAFFAIIBAAJAAAAAA==.Choryrth:BAAALAAECgYIBgAAAA==.Chuckjr:BAAALAAECgcIDgABLAAECgcIGgAQAKkcAA==.',Ci='Cips:BAAALAADCggICAAAAA==.',Ck='Ckwarlock:BAAALAAECgQIBAAAAA==.',Cl='Clearclaw:BAAALAAECgYIDAAAAA==.Clenchy:BAAALAADCggIEAAAAA==.Clownii:BAAALAAECgYIBgABLAAFFAIIBAAJAAAAAA==.',Co='Cocoo:BAABLAAECoEZAAQMAAcIhg4PRABjAQAMAAYI8hAPRABjAQAOAAIImQjYIwCCAAANAAcIhwFmWgBfAAAAAA==.Cocóö:BAAALAAECggICAABLAAECggIGQAMAIYOAA==.Condk:BAAALAAECgIIAgAAAA==.Connie:BAAALAADCgUIBQAAAA==.Coolrunningz:BAAALAADCggIEAAAAA==.Copacon:BAAALAAECgUIBAAAAA==.Corvarpally:BAAALAAECggIEQAAAA==.',Cr='Cras:BAAALAAECggICAAAAA==.Crc:BAAALAAECggICAAAAA==.Crema:BAAALAADCggIFwAAAA==.Cremx:BAAALAAECgcIDQAAAA==.Critias:BAACLAAFFIEHAAIWAAMIyR9RBAAgAQAWAAMIyR9RBAAgAQAsAAQKgRsAAhYACAhHIp0KAPUCABYACAhHIp0KAPUCAAAA.Cronk:BAAALAAECggIAQABLAAECggIFwACAI0aAA==.Crushed:BAAALAAECgIIAgAAAA==.',Cy='Cyppress:BAAALAAECggIDAAAAA==.',Da='Danielp:BAABLAAECoEfAAIKAAgIdiMgBAAoAwAKAAgIdiMgBAAoAwAAAA==.Dargo:BAAALAAECgMIBwAAAA==.Darthtraya:BAAALAAECgMIAwAAAA==.Darthviv:BAAALAADCgQIBAAAAA==.Dashagh:BAAALAAECgUIBQABLAAFFAIIAgAJAAAAAA==.Dasko:BAACLAAFFIEGAAMMAAMI0hJwDwCuAAAMAAIIIhFwDwCuAAANAAEIMRZnEQBWAAAsAAQKgR8ABAwACAijIJ4KAPUCAAwACAj9H54KAPUCAA4ACAieEPQFAC4CAA0AAQipGDFfAEkAAAAA.Dawntitan:BAAALAAECgYIBQAAAA==.Dazir:BAACLAAFFIEJAAIBAAQIlhXNAgBRAQABAAQIlhXNAgBRAQAsAAQKgR8AAgEACAhbIjYHAA8DAAEACAhbIjYHAA8DAAAA.',Db='Dbology:BAACLAAFFIEGAAIMAAMIMRYdCAAHAQAMAAMIMRYdCAAHAQAsAAQKgScABAwACAhSJqMAAIUDAAwACAhPJqMAAIUDAA0ABAiuIWItAE4BAA4AAwgtHWUVABABAAAA.',De='Deadpal:BAAALAADCggICAAAAA==.Deathanddk:BAAALAADCggIHAAAAA==.Deathspacito:BAAALAADCgYIBgABLAAECgYIFwAKABAdAA==.Deathz:BAAALAAECgYICgAAAA==.Deception:BAAALAADCggICQAAAA==.Deekoottaja:BAAALAADCgYIBgABLAAECgYIDQAJAAAAAA==.Deiwos:BAAALAAFFAEIAQAAAA==.Dekio:BAAALAAECgcIEgAAAA==.Deklork:BAAALAAECgQICgAAAA==.Dellory:BAAALAAECgcIDQAAAA==.Demono:BAAALAADCgYIBgAAAA==.Derz:BAACLAAFFIEGAAMMAAMIch2tBgAZAQAMAAMIWxytBgAZAQANAAIIyBp7BQCzAAAsAAQKgRQABA0ACAh6JEYEAM8CAA0ABwhvJEYEAM8CAAwAAwghIKdWABMBAA4AAQgFEgktAEwAAAAA.Destamo:BAACLAAFFIEHAAIMAAMIkBLVCAAAAQAMAAMIkBLVCAAAAQAsAAQKgR4AAwwACAilIlYHABsDAAwACAilIlYHABsDAA0AAQiSDaBgAEYAAAAA.Destrorage:BAAALAADCgcICQAAAA==.Deviur:BAAALAAECgYIEwAAAA==.Dexipline:BAAALAADCggICAAAAA==.',Di='Diamon:BAAALAADCggICAAAAA==.Dimensius:BAAALAADCggICAAAAA==.Dimmuborgir:BAAALAADCggIDwAAAA==.Dirtyhordé:BAAALAAECggIAgAAAA==.Dismarum:BAAALAADCgEIAQAAAA==.Dissonance:BAABLAAECoEgAAIHAAgI1CM1BQBNAwAHAAgI1CM1BQBNAwAAAA==.Diva:BAAALAAECggIBwAAAA==.',Dj='Djtwo:BAACLAAFFIEQAAIXAAYIjRM2AAAnAgAXAAYIjRM2AAAnAgAsAAQKgRQAAhgACAgnGSMOAHUCABgACAgnGSMOAHUCAAAA.Djävulsk:BAAALAAECgIIAgAAAA==.Djävulskpal:BAAALAAECgQIBwAAAA==.Djävulskpr:BAAALAADCgcICwAAAA==.',Dk='Dkodin:BAABLAAECoEcAAIKAAgIrSNvBAAkAwAKAAgIrSNvBAAkAwAAAA==.Dktauren:BAAALAADCggICAAAAA==.',Do='Doktordrake:BAAALAADCgEIAQAAAA==.Dolias:BAAALAAECgMIAwAAAA==.Dorotea:BAAALAAECgUIBQAAAA==.',Dr='Dragonaskh:BAAALAAECgQIBAAAAA==.Dragosbatle:BAAALAADCgEIAQAAAA==.Dragussy:BAAALAADCggICAAAAA==.Drdot:BAABLAAECoEdAAQMAAgIryIyBgApAwAMAAgIoCIyBgApAwANAAUIIR4jHgClAQAOAAIIuhkxHgCqAAAAAA==.Dreadscar:BAAALAADCgcIBwAAAA==.Dreamfyre:BAAALAAECgEIAgAAAA==.Droodlox:BAAALAADCggIFgAAAA==.Drt:BAAALAAECgcIBgAAAA==.Druidjakob:BAAALAADCgcIBwABLAAECgcIGgAQAKkcAA==.Druidthicc:BAAALAAECgcIEQAAAA==.',Du='Dualipa:BAAALAAFFAIIAgAAAA==.Duleladica:BAAALAADCgMIAwAAAA==.Dulevoker:BAAALAAECgUICAAAAA==.Dunstan:BAAALAAECgQIBAAAAA==.',Dw='Dwamaca:BAABLAAECoEWAAICAAgIOwzdKQDTAQACAAgIOwzdKQDTAQAAAA==.',['Dé']='Déx:BAAALAAECgUIBQAAAA==.',Eb='Ebash:BAAALAADCgcIBwABLAAECggIHAANAEsWAA==.Ebasher:BAABLAAECoEcAAQNAAgISxa2HACwAQAMAAcI+BJ9MgC3AQANAAYIvhS2HACwAQAOAAMI9wkcHgCrAAAAAA==.',Ed='Edenm:BAAALAAECgUIDgAAAA==.',Ef='Efendija:BAAALAAECgYIEAAAAA==.',Eg='Egwene:BAAALAAFFAIIAgAAAA==.',El='Eliscina:BAAALAAECgEIAQAAAA==.Ellicia:BAAALAAECgYIEQAAAA==.Ellro:BAAALAAECgYIDQAAAA==.Elvie:BAAALAAECgcIEwAAAA==.Elydris:BAAALAAECgYIEQAAAA==.',Em='Emeria:BAACLAAFFIEGAAMFAAIIfSIsAgDPAAAFAAIIfSIsAgDPAAAGAAIIMh+xEAC3AAAsAAQKgR0AAwUACAiNJUgEAAcDAAUABwgzJUgEAAcDAAYABwg7JUscAIECAAAA.Emiwog:BAAALAADCgYIBgAAAA==.',En='Engla:BAABLAAECoEWAAMQAAgIiBcyJgDVAQAQAAcIvBcyJgDVAQABAAYIiAwwPAA0AQAAAA==.',Eq='Equinox:BAAALAAECgcIDwAAAA==.',Er='Erinyes:BAAALAAECgUICAAAAA==.',Et='Ethi:BAABLAAECoEWAAIZAAgILSMBBQCvAgAZAAgILSMBBQCvAgAAAA==.',Eu='Eusebeia:BAACLAAFFIEIAAIQAAMIVQnFBwDtAAAQAAMIVQnFBwDtAAAsAAQKgR0AAhAACAjIG5MNAJ8CABAACAjIG5MNAJ8CAAAA.',Ev='Evei:BAAALAAECgMIAwAAAA==.',Fa='Fabrotratica:BAAALAADCggICQAAAA==.Fafner:BAAALAAECgIIAwAAAA==.Fanine:BAAALAAECgYICwAAAA==.Fartitude:BAACLAAFFIELAAIBAAQIhhtjAgBvAQABAAQIhhtjAgBvAQAsAAQKgSMAAgEACAicJMADAEYDAAEACAicJMADAEYDAAAA.',Fe='Fear:BAAALAADCgUIAgABLAAECgcIDwAJAAAAAA==.Feifei:BAAALAADCgcIBwAAAA==.Fels:BAABLAAECoEcAAIaAAgIsiJMAQAoAwAaAAgIsiJMAQAoAwAAAA==.Feybae:BAAALAADCgcIBwAAAA==.',Fi='Fiirebeard:BAAALAAECgQIBAAAAA==.Filldh:BAAALAAECgEIAQABLAAFFAMIBQAWAOgUAA==.Fingerdamge:BAAALAADCgMIAwAAAA==.Fio:BAAALAADCggICAAAAA==.Fistus:BAAALAADCgUIBQAAAA==.',Fl='Flameboyant:BAAALAAECgYIDgAAAQ==.Fluffybash:BAACLAAFFIEFAAIDAAIIvxa5DgCpAAADAAIIvxa5DgCpAAAsAAQKgR4AAgMACAgII/oLAAwDAAMACAgII/oLAAwDAAAA.Fluffylight:BAAALAADCgYIDQAAAA==.Fluffymon:BAAALAADCggIDgAAAA==.Flêtcher:BAAALAADCgMIAwAAAA==.',Fr='Frabrog:BAAALAADCggIDAAAAA==.Fredrika:BAAALAADCgEIAQABLAAECgUIBQAJAAAAAA==.Freshmcswag:BAAALAADCgcIBwABLAAECgYIDQAJAAAAAA==.Frostbane:BAAALAAECgYIBgAAAA==.Frostberries:BAAALAADCggICAAAAA==.Frysmi:BAAALAADCgYIBgAAAA==.',Fu='Funkyheals:BAAALAADCggICAAAAA==.Furtitude:BAAALAADCggIEAAAAA==.Fuzzoare:BAABLAAECoEVAAIbAAgIMRGYDgDPAQAbAAgIMRGYDgDPAQAAAA==.',Fy='Fyfan:BAABLAAECoEbAAMWAAgIryCJCgD2AgAWAAgIryCJCgD2AgAcAAII/gfvngBMAAAAAA==.Fysia:BAAALAAECgMIBAAAAA==.',['Fî']='Fîll:BAACLAAFFIEFAAIWAAMI6BRaBgD9AAAWAAMI6BRaBgD9AAAsAAQKgSAAAhYACAgwIiEIABQDABYACAgwIiEIABQDAAAA.',['Fû']='Fûzz:BAABLAAFFIEFAAIZAAMIxQ/fAgDZAAAZAAMIxQ/fAgDZAAAAAA==.',Ga='Gabrielf:BAAALAADCgYIBgAAAA==.Gaiah:BAAALAAECgUICwABLAAECgYIDAAJAAAAAA==.Galaktos:BAAALAADCggICAAAAA==.Gamergirläen:BAAALAAECgYIBwAAAA==.Ganjii:BAAALAAECgIIAgAAAA==.Garry:BAAALAADCgYIBgAAAA==.Gavel:BAAALAAECgUIBwAAAA==.',Gh='Ghiscar:BAABLAAECoEdAAIYAAgIqh2aCgCuAgAYAAgIqh2aCgCuAgAAAA==.',Gi='Gigg:BAAALAADCgcIBwAAAA==.Gimlí:BAAALAAECgIIAQAAAA==.Gitzan:BAABLAAECoEeAAITAAgIphMxEwDuAQATAAgIphMxEwDuAQAAAA==.',Go='Goboheal:BAABLAAECoEaAAMQAAcIqRxPHwAFAgAQAAcIeRtPHwAFAgAdAAEIXSOXGwBmAAAAAA==.Goldenmunk:BAAALAAECgYICAABLAAECggIHwATACUmAA==.Gondir:BAAALAAECgEIAgAAAA==.Goodlookin:BAABLAAECoEXAAIHAAgIdSJ4CQAhAwAHAAgIdSJ4CQAhAwAAAA==.',Gr='Grapemachine:BAAALAADCgIIAgAAAA==.Gratiae:BAAALAAECgYICQAAAA==.Greenlît:BAAALAADCgIIAgAAAA==.Grelg:BAAALAAECgEIAQAAAA==.Greyhoof:BAABLAAECoEXAAIeAAgI7grUEACrAQAeAAgI7grUEACrAQAAAA==.Greywarden:BAAALAAECgMIAwAAAA==.Grimshade:BAAALAADCggIDwAAAA==.Grommer:BAACLAAFFIEGAAICAAIISxLMDQCnAAACAAIISxLMDQCnAAAsAAQKgSAAAgIACAj0IBYNANkCAAIACAj0IBYNANkCAAAA.Grunh:BAAALAAECgYIDQAAAA==.Gryphus:BAABLAAECoEUAAICAAcIrBuGGgBGAgACAAcIrBuGGgBGAgAAAA==.',Gu='Gunhild:BAAALAADCgcIBwAAAA==.',Gw='Gwazi:BAAALAAECgQIBgAAAA==.Gwiyn:BAABLAAECoEbAAIQAAgIdhPfKwCyAQAQAAgIdhPfKwCyAQAAAA==.',Ha='Haantaar:BAAALAAECgYICwAAAA==.Hadock:BAAALAADCgcIBwAAAA==.Hakii:BAAALAAECgIIAgAAAA==.Hashkal:BAAALAAECggICAAAAA==.Hasker:BAAALAAECgYIDgAAAA==.Hatedtroll:BAAALAAFFAIIAgAAAA==.Hazewood:BAAALAAECgMIBwAAAA==.',Hd='Hdl:BAAALAAECggIDwAAAA==.',He='Healthvader:BAABLAAECoEcAAIcAAgI+SLoAgAhAwAcAAgI+SLoAgAhAwAAAA==.Hekili:BAAALAAECgUIBwAAAA==.Helavel:BAABLAAECoEYAAIfAAgIMB+GBwDBAgAfAAgIMB+GBwDBAgAAAA==.Hern:BAAALAAECgYIDgAAAA==.Hetty:BAAALAAECgIIAgAAAA==.',Hi='Hidden:BAAALAAECggIDgAAAA==.',Ho='Holymooly:BAAALAADCggICAAAAA==.Hoppu:BAAALAAECgYIEAAAAA==.Horo:BAAALAADCggIEAABLAAECggIGAAfADAfAA==.Hownter:BAAALAAECgMIBQAAAA==.',Hu='Hultan:BAAALAADCggIDQAAAA==.Huntingsoul:BAAALAAECgMIAwABLAAECgMIBAAJAAAAAA==.Huntis:BAAALAADCgEIAQAAAA==.',Hy='Hyperman:BAAALAADCggICAAAAA==.',['Hô']='Hôly:BAAALAAECgYICQABLAAECggIHAAcAPkiAA==.',['Hø']='Hørrîßûll:BAABLAAECoEeAAMMAAgIwyD8BwAUAwAMAAgIwyD8BwAUAwANAAcIWRLzGQDDAQAAAA==.',Ic='Icya:BAAALAAECgIIAgAAAA==.',Il='Illidarka:BAAALAADCgUIAgAAAA==.Illidayum:BAAALAAECgYIBgABLAAFFAIIAwAJAAAAAA==.',In='Incident:BAAALAADCgcIBwAAAA==.',Iy='Iykyk:BAAALAAECgMIAwAAAA==.',Ja='Jahti:BAAALAAECgMIAwAAAA==.Jano:BAAALAADCggIFgAAAA==.Japan:BAAALAAECgYIBgABLAAECgYIBwAJAAAAAA==.Jarekin:BAAALAAECgYICQAAAA==.Jarya:BAABLAAECoEaAAMgAAgIhRdKJABSAgAgAAgIfhZKJABSAgAZAAQIAw+uHADBAAAAAA==.Jawfish:BAAALAAECgcIDQAAAA==.Jayda:BAAALAAECgcIEgAAAA==.',Je='Jebedíah:BAACLAAFFIEFAAISAAMIbx0pAwAgAQASAAMIbx0pAwAgAQAsAAQKgSAAAxIACAiDIq0FAPwCABIACAhyIa0FAPwCABEAAgi3FfIeAJwAAAAA.Jestersjest:BAAALAADCgcIBwAAAA==.Jesterslulzz:BAAALAAECgIIAgAAAA==.',Ji='Jigooner:BAAALAAECgYICAAAAA==.',Jo='Johnnyboy:BAAALAADCgcICwAAAA==.Jokar:BAAALAAECgYIBgAAAA==.Jokardh:BAAALAAECggIEQAAAA==.Jokardk:BAAALAADCgcIBwAAAA==.Jokesz:BAAALAAECgYIDAAAAA==.Joss:BAAALAADCgcIBgAAAA==.',Ju='Judoon:BAAALAAECgMIBwAAAA==.Julianne:BAAALAADCggIDAAAAA==.',['Já']='Jáyda:BAAALAAECgYIDAABLAAECgcIEgAJAAAAAA==.',['Jè']='Jèv:BAAALAAECgEIAQABLAAFFAEIAQAJAAAAAA==.',['Jÿ']='Jÿxÿ:BAAALAAECgIIAQAAAA==.',Ka='Kaballius:BAAALAADCgYIBgAAAA==.Kaeros:BAABLAAECoEWAAIFAAcI1x7iDQBGAgAFAAcI1x7iDQBGAgAAAA==.Kaliri:BAAALAAECgMIAgAAAA==.Kalma:BAAALAADCggICAAAAA==.Kamarina:BAABLAAECoEVAAIgAAcIJg7dUgCVAQAgAAcIJg7dUgCVAQAAAA==.Karohunt:BAAALAAECgYIDwAAAA==.Karopala:BAAALAAECgcIEgAAAA==.Karsten:BAAALAADCgEIAQAAAA==.Kasetrol:BAAALAADCggICAAAAA==.Kazux:BAAALAAECgEIAQAAAA==.Kazzuo:BAABLAAECoEgAAQMAAgIVyJzBgAmAwAMAAgIECJzBgAmAwAOAAcIZhoHBgAsAgANAAMIJBp/PQDxAAAAAA==.',Ke='Kefla:BAAALAAECggIBQAAAA==.Kelazhur:BAAALAAECgIIAgAAAA==.Kenshi:BAAALAADCggICAAAAA==.',Kh='Kharazim:BAAALAAECgYIBwABLAAECggIEQAJAAAAAA==.Khonshu:BAABLAAECoFqAAIZAAgIqCReAQBUAwAZAAgIqCReAQBUAwAAAA==.',Ki='Kia:BAAALAAECgYICwAAAA==.Kie:BAACLAAFFIEPAAIbAAUIuiWIAAAwAgAbAAUIuiWIAAAwAgAsAAQKgRkAAhsACAjHJXIBAFMDABsACAjHJXIBAFMDAAAA.Kihana:BAAALAAECgYICwAAAA==.Kinray:BAAALAAECgYICQAAAA==.Kirune:BAAALAADCggICAABLAAECgYIDAAJAAAAAA==.Kiuna:BAAALAADCggICAAAAA==.',Kl='Klasika:BAAALAAECgMIBgAAAA==.Klorin:BAAALAAECgcIEQAAAA==.Klump:BAAALAAECggICwABLAAECggIIAAMAPcfAA==.',Ko='Koekie:BAAALAAECggIEwAAAA==.Koekiee:BAAALAAFFAEIAQAAAA==.Kokyangwuti:BAAALAADCgYICAAAAA==.Komodotide:BAAALAAECggIDQAAAA==.Kongomats:BAABLAAECoEfAAITAAgIJSY3AABtAwATAAgIJSY3AABtAwAAAA==.Kovan:BAAALAADCggICAABLAAECggIFAAMADogAA==.',Kr='Kra:BAAALAAECgQIBQAAAA==.Krafna:BAAALAADCgUIAgABLAAECgYIEAAJAAAAAA==.Krazik:BAACLAAFFIENAAIWAAUI4Rx4AQDqAQAWAAUI4Rx4AQDqAQAsAAQKgRgAAhYACAipJZACAGYDABYACAipJZACAGYDAAAA.Krazzik:BAAALAAECgcIEAAAAA==.Kripto:BAAALAAECgUIDwAAAA==.',Kw='Kwojn:BAACLAAFFIEGAAIeAAIIGSHHAgC/AAAeAAIIGSHHAgC/AAAsAAQKgRcAAh4ACAj1I8UBADEDAB4ACAj1I8UBADEDAAAA.Kwojnrogue:BAAALAAECgYICAAAAA==.Kwt:BAAALAADCgcIBwAAAA==.',La='Ladrielle:BAAALAADCgYIBgABLAAECggIGAAfADMjAA==.Laetitia:BAAALAAECgIIAgAAAA==.Lagøm:BAACLAAFFIEQAAMVAAYIdhdQAAAqAgAVAAYIGxdQAAAqAgAeAAQIHA/PAABTAQAsAAQKgRkAAhUACAigJBAEAD4DABUACAigJBAEAD4DAAAA.Langbankfan:BAAALAAFFAIIAgAAAA==.Larama:BAAALAADCggICwAAAA==.Lazér:BAAALAAECgYIDAAAAA==.',Le='Lean:BAAALAAECgYICwAAAA==.Leeblanc:BAAALAAECgIIAgAAAA==.Letsgetweird:BAAALAADCggICAABLAAECggIHAAVADgiAA==.Lew:BAAALAAECgYIBwAAAA==.Lezappy:BAAALAAECgMIAwABLAAECggIGgAMANEiAA==.',Lf='Lfbgttgothgf:BAAALAAECgYICQAAAA==.',Li='Lichpai:BAAALAAECgMIAwAAAA==.Licia:BAAALAAECgYIDAAAAA==.Lilbaby:BAAALAAECgYIBgABLAAECggIDQAJAAAAAA==.Lilou:BAAALAAECgYIDwAAAA==.Lingoo:BAAALAAECgYIBgAAAA==.',Lo='Localhost:BAAALAAECgMIAwAAAA==.Lotzibolovan:BAAALAADCgcIDQAAAA==.Lovepaladin:BAAALAAECggICQAAAA==.Lowie:BAAALAAECgYIBgABLAAFFAIIBAAJAAAAAA==.',Lu='Luffylando:BAAALAADCggIDAAAAA==.Luhna:BAAALAAECgEIAQAAAA==.Lunarys:BAABLAAECoEXAAIfAAgIuCJJBQDnAgAfAAgIuCJJBQDnAgAAAA==.Lupercàl:BAAALAAECgYIBgAAAA==.Luu:BAAALAAECgYIBgAAAA==.',['Lâ']='Lâmy:BAAALAAECgQIBAABLAAFFAIIBQADAL8WAA==.',['Ló']='Lócalhóst:BAAALAADCggIDgAAAA==.',Ma='Macteh:BAAALAAECgIIAgAAAA==.Magicballs:BAAALAAECggICAAAAA==.Magika:BAAALAADCgYIEAAAAA==.Magisch:BAAALAADCggICQAAAA==.Makaria:BAAALAAECgYIDwAAAA==.Marg:BAACLAAFFIEIAAIhAAMIyBOaBAD7AAAhAAMIyBOaBAD7AAAsAAQKgSAAAyEACAg4I/wIAAMDACEACAi7IvwIAAMDAAoAAghaGsVUAKUAAAAA.Marlak:BAAALAADCgcIBwAAAA==.Marí:BAAALAAECgMIBQAAAA==.Mattacate:BAACLAAFFIEPAAIiAAYIVyI7AAB1AgAiAAYIVyI7AAB1AgAsAAQKgRgAAiIACAhUJrYAAH0DACIACAhUJrYAAH0DAAAA.Maxssimos:BAAALAADCggIDwAAAA==.',Me='Megaøtario:BAAALAADCggIDgAAAA==.Mellt:BAABLAAECoEUAAINAAcI0RDHFQDjAQANAAcI0RDHFQDjAQAAAA==.Mercay:BAAALAAECggIEAAAAA==.Merfi:BAAALAADCgYIBgAAAA==.',Mi='Miasma:BAAALAAECgMIAwAAAA==.Mieze:BAAALAADCgcICQAAAA==.Mikedh:BAAALAAECgYIBwABLAAFFAUICgARABoWAA==.Mikè:BAACLAAFFIEKAAMRAAUIGhb0AABcAQARAAQI+RL0AABcAQASAAIITB4nBwDAAAAsAAQKgRgAAxIACAgnJs4AAGsDABIACAj7Jc4AAGsDABEABAj1IS0PAIkBAAAA.Miniboom:BAAALAADCggICAAAAA==.Mistchivus:BAAALAADCgcIBwAAAA==.Mitcher:BAAALAAECgYIEgAAAA==.Mitos:BAAALAADCggIDgAAAA==.',Mj='Mjölkfri:BAAALAAECgUICQAAAA==.',Mo='Mogador:BAAALAADCgcIDwAAAA==.Molindk:BAAALAAECgIIAgAAAA==.Mommymilker:BAAALAAECggIEAAAAA==.Monajensen:BAAALAADCgEIAQAAAA==.Moocifer:BAAALAAECgIIAwAAAA==.Moosk:BAAALAAECgEIAgAAAA==.Moperror:BAAALAAECgEIAQAAAA==.Moraco:BAAALAAECgIIAgAAAA==.Mortal:BAACLAAFFIEIAAIHAAMIbx81BQAYAQAHAAMIbx81BQAYAQAsAAQKgR8AAgcACAh7I3MHADYDAAcACAh7I3MHADYDAAAA.Morthurann:BAAALAAECgcIDwAAAA==.',Mu='Mugen:BAAALAAECgMIAwABLAAECggIGQAMAIYOAA==.Muliy:BAAALAAECgcIEQAAAA==.Mushy:BAAALAAECggIEwAAAA==.',Mv='Mvrz:BAAALAAECgUIBQABLAAECgYIEQAJAAAAAA==.',My='Mynt:BAAALAAECggIEAAAAA==.Myrdraal:BAAALAADCgIIAQAAAA==.Mytzmaster:BAAALAADCggICAAAAA==.Mywiddledrac:BAAALAAFFAMIBAAAAA==.Mywiddlepala:BAAALAAECggIDwAAAA==.',['Mà']='Màz:BAACLAAFFIEGAAIVAAMIahYvBAD4AAAVAAMIahYvBAD4AAAsAAQKgRwAAhUACAjKIyEGABcDABUACAjKIyEGABcDAAAA.Màzz:BAAALAAECgMIBwAAAA==.',['Mí']='Míkó:BAABLAAECoEaAAIcAAgIYh7QDACZAgAcAAgIYh7QDACZAgAAAA==.',Na='Nagibatos:BAAALAADCggIEAABLAAECggIHAANAEsWAA==.Nanooq:BAAALAADCggICAAAAA==.',Ne='Neems:BAAALAAFFAQIBAAAAA==.Nelisha:BAAALAADCgcICwAAAA==.Neteriya:BAAALAAECggIEQAAAA==.',Ni='Nightshow:BAAALAADCggICAAAAA==.Nihi:BAAALAAECgIIAgAAAA==.Nikmx:BAAALAAECgcIEQAAAA==.Nires:BAABLAAECoEXAAIIAAcIcBwSCwA5AgAIAAcIcBwSCwA5AgAAAA==.Nizz:BAABLAAECoEXAAIKAAgI9xjEFgA2AgAKAAgI9xjEFgA2AgAAAA==.',Nk='Nkeh:BAAALAAECggIDQAAAA==.',No='Notpochmak:BAABLAAECoEWAAIiAAgIlybDAAB7AwAiAAgIlybDAAB7AwAAAA==.Nownight:BAAALAAECggIBgAAAA==.Nozdørmu:BAABLAAECoEbAAIYAAgIwR37CgCoAgAYAAgIwR37CgCoAgABLAAFFAEIAQAJAAAAAA==.',Nu='Nuck:BAABLAAECoEbAAIgAAgIgR4jGQCYAgAgAAgIgR4jGQCYAgAAAA==.',Ny='Nydarox:BAAALAAFFAEIAQAAAA==.',Nz='Nzall:BAAALAAECgcIDgAAAA==.Nzallranger:BAAALAADCggICAAAAA==.',Oc='Octar:BAABLAAECoEeAAMjAAgIWhs6BABqAgAjAAgIWhs6BABqAgAiAAUI/heHJwAcAQAAAA==.',Ol='Oldham:BAAALAAECgMIBgAAAA==.',Om='Omegazugzug:BAAALAADCgcIBwABLAAECgMIAwAJAAAAAA==.Omik:BAAALAADCgMIAwAAAA==.Omniknight:BAAALAAECggICAABLAAFFAIIAgAJAAAAAA==.',On='Onetwothree:BAAALAADCggIFAAAAA==.',Or='Orpster:BAAALAADCggICAABLAADCggICAAJAAAAAA==.',Os='Oshmotli:BAAALAAECgMIBAAAAA==.',Pa='Paalgej:BAABLAAECoEdAAMDAAgIkiSKBQBPAwADAAgIkiSKBQBPAwATAAUIrBbsJwAwAQAAAA==.Pada:BAAALAADCgIIAgABLAAFFAMIAwAJAAAAAA==.Padantic:BAEBLAAECoEhAAMbAAgIsSGGBADWAgAbAAgIsSGGBADWAgAIAAMIjBIAAAAAAAAAAA==.Padapaint:BAAALAAFFAMIAwAAAA==.Palatinuss:BAAALAADCgMIAwABLAAECgUIBQAJAAAAAA==.Paperplane:BAABLAAECoEWAAMhAAgIaBARLgDbAQAhAAgIxQ8RLgDbAQAKAAMIuBGpVgCbAAAAAA==.',Pe='Pel:BAAALAADCggIEAAAAA==.Persés:BAAALAAFFAMIAwAAAA==.Pestilência:BAAALAADCgEIAQAAAA==.Petrapan:BAAALAAECgYIDAABLAAECggIFgAUAIEbAA==.Pettrea:BAABLAAECoEWAAIUAAgIgRumCgAbAgAUAAgIgRumCgAbAgAAAA==.',Po='Pocba:BAAALAAECgYIAQAAAA==.Pompert:BAABLAAECoEYAAMgAAcI9CLgIABmAgAgAAcIaSHgIABmAgAZAAYIGyChCAA4AgAAAA==.',Pr='Pranker:BAAALAADCggICAABLAAECgcIDAAJAAAAAA==.Protechcow:BAAALAADCgYIBgAAAA==.',Ps='Psychoangel:BAAALAAECggIEwAAAA==.Psychocleric:BAAALAADCgYIBgABLAAECggIEwAJAAAAAA==.Psychofister:BAAALAAECgMIAwABLAAECggIEwAJAAAAAA==.',Pu='Puddy:BAAALAAECggIEAAAAA==.Pukso:BAAALAADCgcIDAAAAA==.',Qa='Qaelthas:BAAALAAECgYIBwAAAA==.',Qe='Qei:BAAALAADCgMIAwAAAA==.',Qo='Qonzu:BAAALAADCgcIEQAAAA==.',Qt='Qtii:BAAALAAECgYIBgABLAAFFAIIBAAJAAAAAA==.',Qu='Quack:BAAALAAFFAIIAgAAAA==.',Ra='Raevi:BAAALAAECgQIBgAAAA==.Ragbolt:BAAALAADCggIFAAAAA==.Ragebar:BAAALAAECgcICgAAAA==.Ragelesstwo:BAAALAAECgEIAQAAAA==.Ragnarwar:BAAALAADCggICAAAAA==.Rainymagi:BAAALAAECgcIDQAAAA==.Rakeera:BAAALAAECggIDQABLAAFFAQICgAKAHIkAA==.Raktos:BAACLAAFFIEGAAIkAAIImQnkBwCPAAAkAAIImQnkBwCPAAAsAAQKgRcAAyQABggBEkMSAE8BACQABggBEkMSAE8BABgAAgiECKY9AGcAAAAA.Rangart:BAAALAAECgcIEQAAAA==.Rathra:BAAALAADCgMIAwAAAA==.Razihel:BAAALAADCgEIAQABLAAECggIGAAfADMjAA==.Razjin:BAAALAADCgIIAgAAAA==.',Re='Rednek:BAAALAAECgcIEAAAAA==.Refie:BAACLAAFFIEKAAIKAAQIciSWAQCnAQAKAAQIciSWAQCnAQAsAAQKgRYAAgoACAhdJsoBAFUDAAoACAhdJsoBAFUDAAAA.Reino:BAAALAADCgYIBwABLAAECgYIDQAJAAAAAA==.Remé:BAAALAAECggIAgABLAAECggIFwACAI0aAA==.Renesanz:BAAALAAECgYIEAAAAA==.Repulse:BAAALAAECgIIBAAAAA==.Reviction:BAAALAAECgYICwAAAA==.',Ri='Rivermane:BAAALAADCgMIAwAAAA==.Rizzrobe:BAAALAAECgYIEQAAAA==.',Ro='Robeu:BAAALAAECgEIAQAAAA==.Roll:BAAALAAECgcIDwAAAA==.Rompsa:BAAALAADCgUIBQAAAA==.Roosevelt:BAAALAAECgEIAQABLAAECgMIBgAJAAAAAA==.',Ru='Rumouro:BAAALAAECgIIAgAAAA==.Ruvic:BAACLAAFFIEHAAIgAAMIhyUdAwBRAQAgAAMIhyUdAwBRAQAsAAQKgRcAAyAACAhwJTcCAGUDACAACAhwJTcCAGUDAA8AAQgIJOA5AFoAAAAA.',['Rë']='Rëne:BAAALAAECggICAABLAAECggIFwACAI0aAA==.',['Rí']='Ría:BAABLAAECoEhAAQIAAgI7CKoAQAzAwAIAAgI7CKoAQAzAwAlAAgIShj/DQAzAgAbAAEIVBWsKwA2AAAAAA==.',Sa='Sabfiend:BAAALAADCggIEwAAAA==.Sacai:BAABLAAECoEgAAMhAAgIhR1tFgB4AgAhAAgIARptFgB4AgAKAAcIzh3yEQBrAgAAAA==.Sanitäter:BAABLAAECoEUAAIQAAcIYhZOJgDUAQAQAAcIYhZOJgDUAQAAAA==.Sarabellum:BAAALAADCgMIAwAAAA==.Saracia:BAAALAADCggICAAAAA==.Sayla:BAAALAAECgcIEAAAAA==.',Sc='Schizophreni:BAAALAADCgEIAgAAAA==.',Se='Secroz:BAAALAADCgIIAgAAAA==.Sekser:BAAALAAECgcIEAAAAA==.Senseikc:BAAALAAECgYIEAAAAA==.Seraina:BAAALAADCgYIBgAAAA==.',Sh='Shadowcore:BAAALAADCggIDAAAAA==.Shadowless:BAAALAAECgYIEAAAAA==.Shadowmourns:BAAALAADCggIDQAAAA==.Shameanos:BAAALAADCggICAAAAA==.Shamworx:BAAALAADCgcIDAAAAA==.Shamyumy:BAAALAADCgcIDgAAAA==.Shangus:BAACLAAFFIEFAAIiAAMItgxCBADPAAAiAAMItgxCBADPAAAsAAQKgRUAAiIACAiFHIUIAJcCACIACAiFHIUIAJcCAAEsAAQKCAgRAAkAAAAA.Sharnt:BAABLAAECoEWAAMYAAcIWxalFwDwAQAYAAcIWxalFwDwAQAkAAUIvQmYGADiAAAAAA==.Shemanatwo:BAAALAAFFAIIAgABLAAFFAMIAwAJAAAAAA==.Shep:BAAALAAECgYICwAAAA==.Shieldmaiden:BAAALAAECgMIAwAAAA==.Shiftmypants:BAABLAAECoEVAAIfAAgIMAVUSAD6AAAfAAgIMAVUSAD6AAAAAA==.Shocker:BAAALAAECgIIAgAAAA==.Shofa:BAAALAADCggICAAAAA==.',Si='Sigmagooner:BAAALAAECggIEQAAAA==.Silmarune:BAAALAAECgYIDAAAAA==.Silvia:BAAALAADCgIIAwAAAA==.Simohd:BAABLAAECoEdAAIYAAgIqiAvBgD9AgAYAAgIqiAvBgD9AgAAAA==.',Sk='Skafiskafnja:BAABLAAECoEUAAIcAAcITBq8IAAOAgAcAAcITBq8IAAOAgAAAA==.Skrol:BAAALAAECgYICAABLAAECgYIEAAJAAAAAA==.Skydominion:BAAALAADCggICAAAAA==.Skyline:BAAALAADCggIFwAAAA==.Skyswing:BAAALAAECgMIAwAAAA==.Skywings:BAAALAAECgcIDgAAAA==.',Sl='Sleeks:BAAALAAECgYICgAAAA==.Sljokica:BAAALAAECgMIAwAAAA==.Slutii:BAAALAAECgYIAgABLAAFFAIIBAAJAAAAAA==.',Sm='Smokethree:BAAALAADCgEIAQAAAA==.',So='Sodpala:BAAALAAECgUICAAAAA==.Soliaa:BAAALAAECgYIBgABLAAECggIFQADAD0lAA==.Somissxam:BAAALAADCgcICwAAAA==.Songoku:BAAALAAECggICAAAAA==.Sonofdevil:BAABLAAECoEWAAIKAAgIEhfMGAAiAgAKAAgIEhfMGAAiAgAAAA==.Sorche:BAAALAAECgMIAwAAAA==.Soupy:BAAALAADCggICAAAAA==.Sourpack:BAAALAADCgIIAgAAAA==.',Sp='Speeder:BAAALAADCgcIBwAAAA==.Spindríft:BAACLAAFFIEHAAICAAMIrRVLBgAJAQACAAMIrRVLBgAJAQAsAAQKgR4AAgIACAi+IxgGADADAAIACAi+IxgGADADAAAA.Spriesty:BAAALAADCgYIBgABLAAECgYIDwAJAAAAAA==.',St='Steffix:BAAALAAECgEIAQAAAA==.Steffski:BAAALAAECggICQAAAA==.Stunlock:BAAALAAECgcIEwAAAA==.Stînger:BAAALAAECgcIEgAAAA==.',Su='Sulizuna:BAAALAAECgYIDAAAAA==.Sunraku:BAAALAAECgYIEQAAAA==.Superman:BAAALAADCggIEAABLAAFFAEIAQAJAAAAAA==.Sussy:BAAALAAECggIAwAAAA==.',Sw='Swingshot:BAABLAAECoEbAAIHAAgI9xRuKgAjAgAHAAgI9xRuKgAjAgAAAA==.Swoksaar:BAAALAADCggIEAABLAAFFAEIAQAJAAAAAA==.',Sy='Synvia:BAAALAADCgYIDAAAAA==.',Ta='Tagrenam:BAAALAAECgMIAwAAAA==.Taisiyå:BAAALAAECgMIBgAAAA==.Tattimies:BAAALAADCgcIBwABLAAECgYIDQAJAAAAAA==.Taylør:BAAALAAECgUIBwAAAA==.',Te='Teaspoon:BAAALAADCggICAAAAA==.Teela:BAAALAAECggICAABLAAECggIGAAfADAfAA==.Teelicht:BAAALAAECggIEAAAAA==.Telexa:BAAALAAECgYIDAAAAA==.Telexw:BAAALAAECgMIBQAAAA==.Telnai:BAAALAADCggICgAAAA==.Tepsi:BAAALAAECgEIAQAAAA==.',Th='Thakusk:BAAALAAECgYIBgABLAAECgcIGgAQAKkcAA==.Thaleras:BAACLAAFFIEFAAIEAAMIDQV5BACkAAAEAAMIDQV5BACkAAAsAAQKgRwAAgQACAj0GS4KAD4CAAQACAj0GS4KAD4CAAAA.Tharnos:BAAALAADCgIIAgAAAA==.Theogpala:BAAALAAECgYICQAAAA==.Thoraka:BAABLAAECoEUAAMKAAYIkxftMABsAQAKAAYIZxTtMABsAQAhAAYIBRD/VAA3AQAAAA==.Thrallkarah:BAABLAAECoEbAAMhAAgIFyOwCgDvAgAhAAgIFyOwCgDvAgAKAAcIfSF6DwCKAgAAAA==.',Ti='Tidefury:BAAALAADCggIEgAAAA==.Tienne:BAAALAAECggICAAAAA==.Timeless:BAAALAAECgYICwAAAA==.Titan:BAAALAADCggICAABLAAECgUIBwAJAAAAAA==.Titanwings:BAAALAADCggICAAAAA==.',To='Tohru:BAAALAADCgEIAQAAAA==.Tongues:BAAALAAECggICAAAAA==.Torp:BAAALAAECgYIBgAAAA==.Totemhated:BAAALAAFFAIIAgABLAAFFAIIAgAJAAAAAA==.',Tr='Transrights:BAAALAAECgYIDAAAAA==.Trapkeeper:BAAALAADCggIFAAAAA==.Trees:BAAALAADCggIDwAAAA==.Tribu:BAAALAADCgcIBwAAAA==.Tricklevodos:BAACLAAFFIEEAAIYAAMIOxapBAAJAQAYAAMIOxapBAAJAQAsAAQKgRsAAhgACAgpJroBAFwDABgACAgpJroBAFwDAAAA.Tripp:BAAALAADCgcIDQAAAA==.Tronxi:BAAALAADCgMIAwAAAA==.Trøbbel:BAAALAADCgIIAgAAAA==.',Tu='Turktrollet:BAAALAADCggIDQAAAA==.',Ty='Tykee:BAABLAAECoEUAAIcAAYIzQsVZgD6AAAcAAYIzQsVZgD6AAAAAA==.Tyrianna:BAAALAADCgEIAQAAAA==.',Tz='Tzaid:BAAALAAECgMIBQAAAA==.',Ul='Ultrawing:BAAALAADCggIEAAAAA==.',Un='Unfrozen:BAAALAAECggIBAAAAA==.',Uu='Uumpaamonk:BAAALAAECgcIDwAAAA==.Uumpaapal:BAAALAADCgMIAwABLAAECgcIDwAJAAAAAA==.Uumpaasumpa:BAAALAADCgQIBAAAAA==.',Va='Valeen:BAAALAAECgIIAgAAAA==.Valeriia:BAAALAADCgEIAQAAAA==.Valestica:BAABLAAECoEdAAIDAAgIlRbTJABKAgADAAgIlRbTJABKAgAAAA==.Vamesan:BAAALAAECgIIAgAAAA==.Vanthirae:BAAALAADCggICAAAAA==.',Ve='Vegapunk:BAAALAADCggIDwABLAAECggIHgATAKYTAA==.Velk:BAABLAAECoEeAAIbAAgI/iNwAgApAwAbAAgI/iNwAgApAwAAAA==.Velka:BAAALAADCgYIBgAAAA==.Venatrixx:BAAALAADCggICAAAAA==.Venzo:BAAALAAECgUIBQAAAA==.Verus:BAABLAAECoEcAAIcAAgImSFOCADOAgAcAAgImSFOCADOAgAAAA==.Veyra:BAABLAAECoEYAAIfAAgIMyNmAgAmAwAfAAgIMyNmAgAmAwAAAA==.',Vi='Vidragula:BAAALAAECgEIAQAAAA==.Villkatis:BAAALAAECgMIBQAAAA==.Vim:BAAALAAECgMIAwABLAAFFAIIBgAFAH0iAA==.Viran:BAAALAAECgMIBAABLAAECgcIEQAJAAAAAA==.',Vo='Vodominik:BAAALAADCgcIDAAAAA==.Voidslayer:BAAALAADCgYIBgAAAA==.Voidsong:BAAALAAECgEIAQAAAA==.Voidweaver:BAAALAADCggIGAABLAAFFAEIAQAJAAAAAA==.Vosrithor:BAAALAADCggICAABLAAECggIFgAKANsgAA==.Vostrayan:BAABLAAECoEWAAIKAAgI2yA4CgDRAgAKAAgI2yA4CgDRAgAAAA==.',Wa='Waifubabex:BAABLAAFFIEGAAIgAAIIbhlIEQCtAAAgAAIIbhlIEQCtAAAAAA==.Warlockdex:BAAALAAECgYICAAAAA==.Warr:BAAALAAECgUIBAAAAA==.Wartix:BAACLAAFFIEHAAICAAMIByG8AwAyAQACAAMIByG8AwAyAQAsAAQKgR8AAgIACAiqJHcDAFMDAAIACAiqJHcDAFMDAAAA.Wartusk:BAAALAAECgMIAwAAAA==.Wazaah:BAABLAAECoEVAAIMAAgI7xv5FwBwAgAMAAgI7xv5FwBwAgAAAA==.',We='Wested:BAAALAADCgYIDAAAAA==.',Wh='Whack:BAAALAAECgYICQAAAA==.',Wi='Wimmie:BAABLAAECoEdAAIhAAgItCOnBAA8AwAhAAgItCOnBAA8AwAAAA==.Wimpy:BAAALAAECggIEAAAAA==.',Ws='Wsá:BAAALAADCggIEAABLAAECggIEgAgAMEkAA==.',Wu='Wutmantel:BAAALAADCgcIDAAAAA==.',Wv='Wv:BAAALAAECgYIBwABLAAECggIEgAgAMEkAA==.Wva:BAAALAADCggICgABLAAECggIEgAgAMEkAA==.Wvä:BAAALAADCggICAABLAAECggIEgAgAMEkAA==.',Wx='Wxa:BAABLAAECoESAAIgAAcIwSTkEwC9AgAgAAcIwSTkEwC9AgAAAA==.',Xe='Xeina:BAAALAAECggICwAAAA==.Xenomorphy:BAAALAADCgYIBgAAAA==.Xep:BAAALAADCgcIBwAAAA==.Xezeon:BAAALAAECgcIDwAAAA==.',Xi='Xipa:BAAALAAECgYIBgAAAA==.',Xu='Xulu:BAAALAADCgcIBwABLAAECggIGAAQAGEgAA==.',Ya='Yalara:BAABLAAECoEbAAMcAAgIZxJULgDHAQAcAAgIZxJULgDHAQAWAAEImguObQA/AAAAAA==.Yavina:BAAALAAECgYIDgAAAA==.',Ye='Yerin:BAAALAADCgYIBgAAAA==.',Yi='Yimza:BAAALAAFFAEIAQAAAA==.',Yu='Yuubari:BAAALAADCgcIDAAAAA==.',Yy='Yy:BAAALAAECggICAAAAA==.',['Yú']='Yúnus:BAABLAAECoEVAAIQAAcIaSFmDgCVAgAQAAcIaSFmDgCVAgAAAA==.',Za='Zackattack:BAAALAADCggICgABLAAECgYIBgAJAAAAAA==.Zaev:BAABLAAECoEXAAIBAAcI+BKLJgDCAQABAAcI+BKLJgDCAQAAAA==.Zaijko:BAAALAADCggICAAAAA==.',Ze='Zeerakshii:BAAALAADCggICAAAAA==.Zennarde:BAAALAADCgcIBwABLAAFFAEIAQAJAAAAAA==.Zephanger:BAAALAAECgMIBgAAAA==.Zerathus:BAAALAADCgYICwAAAA==.Zerofyne:BAAALAAECgUIDQAAAA==.Zexdh:BAAALAAECggIDQAAAA==.Zexmonk:BAAALAAECggICAAAAA==.',Zi='Zimm:BAAALAADCgEIAQAAAA==.Zinara:BAAALAADCgcIBwAAAA==.Zinthos:BAAALAADCgYIBgAAAA==.',Zo='Zooz:BAAALAAECgUIBQAAAA==.Zoz:BAAALAAECgcIDAAAAA==.',Zu='Zulria:BAAALAAECgYIBgAAAA==.',['Zá']='Záck:BAAALAAECgcIDQABLAAECgYIBgAJAAAAAA==.',['Äe']='Äen:BAABLAAECoEgAAMVAAgIZCREAwBMAwAVAAgIZCREAwBMAwAfAAIIyiD3VADAAAAAAA==.',['Æp']='Æpræstefar:BAAALAADCgUIBQAAAA==.',['Öl']='Öl:BAAALAADCgIIAgAAAA==.',['Ös']='Ösarn:BAAALAAECgcIDwAAAA==.',['Øs']='Øsi:BAAALAADCggIDAAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end