local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'DeathKnight-Unholy','DeathKnight-Frost','Druid-Balance','Paladin-Protection','Mage-Arcane','DeathKnight-Blood','Mage-Frost','Paladin-Retribution','Paladin-Holy','Priest-Shadow','Priest-Discipline','Unknown-Unknown','Evoker-Preservation','Warlock-Destruction','Priest-Holy','Druid-Guardian','Monk-Mistweaver','Hunter-BeastMastery','Monk-Windwalker','Warrior-Fury','Evoker-Augmentation','Shaman-Restoration','Shaman-Elemental','DemonHunter-Havoc','DemonHunter-Vengeance','Warrior-Arms','Warlock-Demonology','Hunter-Marksmanship','Evoker-Devastation','Druid-Restoration','Warlock-Affliction','Rogue-Assassination','Rogue-Subtlety','Druid-Feral','Hunter-Survival','Monk-Brewmaster','Warrior-Protection',}; local provider = {region='EU',realm='Auchindoun',name='EU',type='weekly',zone=44,date='2025-09-22',data={Ab='Abezethibou:BAACLAAFFIESAAMBAAUIrRukAADZAQABAAUIrRukAADZAQACAAEI/AbfZgA9AAAsAAQKgSEAAwEACAhPJF8EAAsDAAEACAhPJF8EAAsDAAIAAwiWGFwFAbUAAAAA.Abhor:BAAALAADCgYIBgAAAA==.Aboveyou:BAAALAADCggICAABLAAFFAIICAADAPkYAA==.',Ac='Acchillus:BAAALAADCgcIBwAAAA==.',Ad='Addeshammy:BAAALAADCgIIAgABLAAECggIJQAEALweAA==.Adelard:BAAALAAECgYICwABLAAFFAUIDgAFAFcbAA==.Adernal:BAAALAADCgcIDQAAAA==.',Ae='Aellowyn:BAABLAAECoEfAAMCAAgIoQ+5kACcAQACAAgItA25kACcAQAGAAYIcwtdJQAGAQAAAA==.',Ag='Agrero:BAAALAADCgcIBwAAAA==.',Ah='Ahnfrau:BAABLAAECoEmAAMCAAgIOx6DLACVAgACAAgIkx2DLACVAgAGAAcI0Rc1FwCmAQAAAA==.Ahriman:BAABLAAECoElAAMHAAgI6RvhEAB4AgAHAAgI6RvhEAB4AgAFAAUIVQ/AlwAdAQAAAA==.',Ai='Ainaria:BAAALAAECgYICQAAAA==.',Ak='Akatamaxitos:BAAALAADCgQIBAAAAA==.Akuuru:BAAALAADCgYIBgAAAA==.',Al='Aldamsk:BAAALAADCggICAAAAA==.Alikax:BAAALAAECgYIDwAAAA==.Alleiheim:BAABLAAECoElAAIIAAgInyJ7EgAWAwAIAAgInyJ7EgAWAwAAAA==.Almirona:BAAALAADCgcIBwAAAA==.Alumno:BAABLAAECoEaAAMJAAgIpQkQNgBSAQAJAAgIpQkQNgBSAQAIAAEIlQr2OwEtAAAAAA==.',An='Anarkuid:BAAALAAECgYIBgAAAA==.Andeles:BAAALAADCgcIDAAAAA==.Andreea:BAAALAADCggIEgAAAA==.Aniprimal:BAAALAAECgcIDQAAAA==.Anointing:BAABLAAECoEUAAIKAAgI1xv9FQCiAgAKAAgI1xv9FQCiAgAAAA==.Antifun:BAAALAAECgMIAwAAAA==.',Ao='Aokigahara:BAAALAAECgYIBgAAAA==.',Ap='Apoc:BAAALAADCgUICAAAAA==.',Aq='Aqualock:BAAALAADCggICAAAAA==.',Ar='Arcanaan:BAAALAADCgEIAQAAAA==.Ardeidae:BAAALAADCgYIBgAAAA==.Arff:BAAALAAECgYIEQAAAA==.Arginoth:BAAALAAECgUIBQAAAA==.Arrinita:BAAALAADCggICAAAAA==.',As='Asclepius:BAABLAAECoEaAAMKAAYIABhUOgCvAQAKAAYIABhUOgCvAQALAAIIyQmVKgBTAAABLAAECggICwAMAAAAAA==.Asiet:BAAALAADCggICAAAAA==.Asserborges:BAAALAADCgQIBAAAAA==.',At='Atromitos:BAAALAADCgQIBAAAAA==.',Au='Auroc:BAAALAADCggIDwABLAAECggIFwANAHkZAA==.Auron:BAAALAADCggIGAABLAAECggIFwANAHkZAA==.Autistikos:BAAALAADCggIDQAAAA==.',Ay='Ayene:BAAALAAECgEIAQAAAA==.Aysèn:BAAALAAECgQIBAABLAAECgYICgAMAAAAAA==.',Az='Azacca:BAAALAAECgYIDAAAAA==.Azareth:BAAALAAECgEIAQABLAAECgYICQAMAAAAAA==.Aztharooth:BAABLAAECoEfAAIOAAcIQw3EaAB8AQAOAAcIQw3EaAB8AQAAAA==.Azurael:BAABLAAECoEpAAQKAAgIkSBDHABsAgAKAAcI6yBDHABsAgAPAAYI9hoIPgC2AQALAAYIyxTnDQCOAQAAAA==.',Ba='Bacpelas:BAAALAAFFAIIAgAAAA==.Badbishlily:BAAALAAECgYIBgAAAA==.Badshuvo:BAAALAADCgMIAwAAAA==.Balancy:BAAALAAECgIIAgAAAA==.Balmung:BAABLAAECoEXAAINAAgIeRl7CwBHAgANAAgIeRl7CwBHAgAAAA==.Bamboolic:BAAALAADCggICAAAAA==.Baphometi:BAAALAADCggICQAAAA==.Batbayar:BAAALAADCggICwAAAQ==.',Bb='Bbldrizzy:BAAALAAECgYIBwABLAAFFAQIDQAQAEEUAA==.',Be='Bearhanded:BAABLAAECoEYAAIRAAYIWhiaGwCgAQARAAYIWhiaGwCgAQABLAAECggIGQASAGkXAA==.Beeffcake:BAACLAAFFIEGAAIEAAIIChO7DACHAAAEAAIIChO7DACHAAAsAAQKgTAAAgQACAjVIPYFAP4CAAQACAjVIPYFAP4CAAAA.Beeno:BAAALAADCggICQAAAA==.Begouri:BAAALAAECgYIBgAAAA==.Bendis:BAAALAADCggICAAAAA==.',Bh='Bhenchod:BAACLAAFFIEGAAIIAAIIIhf/IgCnAAAIAAIIIhf/IgCnAAAsAAQKgRgAAggACAgyG6cuAIkCAAgACAgyG6cuAIkCAAAA.',Bi='Biberce:BAABLAAECoEgAAISAAgInhklPQAfAgASAAgInhklPQAfAgAAAA==.Biisch:BAAALAAECggIIQAAAQ==.Bitmin:BAAALAAECgEIAQAAAA==.',Bl='Blacknaat:BAAALAAECgIIAgAAAA==.Blacksunday:BAAALAAECgQIBwAAAA==.Blantak:BAAALAADCgYICwAAAA==.Blayai:BAAALAAECgMIAwAAAA==.Blockongcd:BAABLAAECoEVAAIFAAgI8haFOABDAgAFAAgI8haFOABDAgAAAA==.Bloodsent:BAAALAADCgIIAgAAAA==.Bluebee:BAAALAAECgYIEgAAAA==.Bláin:BAAALAAECgYIDQAAAA==.',Bo='Bobs:BAABLAAECoEdAAMIAAgIDyJ5FgAAAwAIAAgIDyJ5FgAAAwAJAAcI2hScIQDRAQAAAA==.Bodyee:BAAALAADCgcIBwAAAA==.Bodzilla:BAAALAADCggIBAAAAA==.Bomba:BAAALAAECgcIDQAAAA==.Boogie:BAAALAAECgYICQAAAA==.Bowmont:BAAALAADCggICAAAAA==.Boxanne:BAAALAAECgYIBwAAAA==.Boxley:BAAALAAECggIEwAAAA==.',Br='Bronzeird:BAABLAAECoEVAAISAAgI1A5LawCfAQASAAgI1A5LawCfAQAAAA==.Brostrøm:BAABLAAECoEVAAILAAYI2R4iBwAZAgALAAYI2R4iBwAZAgAAAA==.Brutalbacon:BAAALAAECgYIEgAAAA==.Brutalmayo:BAAALAAECgMIAwAAAA==.',Bu='Bubbler:BAAALAADCggICAABLAAFFAUIEgABAK0bAA==.Bumbaclart:BAACLAAFFIEGAAITAAIIawbTDwB+AAATAAIIawbTDwB+AAAsAAQKgRoAAhMACAj7E4glAJsBABMACAj7E4glAJsBAAAA.Burczek:BAAALAADCgIIAgAAAA==.Buuhu:BAACLAAFFIEIAAIUAAMIgBgiDQARAQAUAAMIgBgiDQARAQAsAAQKgR8AAhQACAhLIoQTAPACABQACAhLIoQTAPACAAAA.Buutje:BAACLAAFFIEIAAICAAIIIx/wIgC2AAACAAIIIx/wIgC2AAAsAAQKgSQAAgIACAiWI/APACADAAIACAiWI/APACADAAAA.',['Bä']='Bäbävitaröv:BAAALAAECggIDAAAAA==.',['Bô']='Bômbur:BAAALAADCgIIAwAAAA==.',['Bú']='Búbblegum:BAAALAAECgEIAQABLAAFFAUICgAVAGkUAA==.',Ca='Ca:BAAALAAECgIIAwAAAA==.Cadush:BAACLAAFFIEPAAIUAAUImxzRBQDXAQAUAAUImxzRBQDXAQAsAAQKgS0AAhQACAiPJMEGAFIDABQACAiPJMEGAFIDAAAA.Caelum:BAACLAAFFIEHAAIEAAMI8h7TAwAUAQAEAAMI8h7TAwAUAQAsAAQKgRsAAgQACAjmHP0NAGwCAAQACAjmHP0NAGwCAAAA.Calandriaa:BAAALAADCgYIEQAAAA==.Callisto:BAAALAAECgYIBwABLAAFFAIIBgAPALEiAA==.Camooflage:BAAALAAECggICAAAAA==.Camper:BAAALAADCgcIBwAAAA==.Carlos:BAAALAADCgYIBgAAAA==.Caspari:BAAALAADCggIFQAAAA==.Castillian:BAAALAAECgYIBwAAAA==.Cazia:BAAALAADCgYIBgAAAA==.Cazira:BAABLAAECoEbAAIIAAYIOQX43AD9AAAIAAYIOQX43AD9AAAAAA==.',Ce='Celestrîa:BAAALAAECgMIBwAAAA==.Celots:BAAALAADCgIIAQAAAA==.Cenaria:BAAALAADCgYIBgAAAA==.',Ch='Charizart:BAAALAAECgYICgAAAA==.Charok:BAAALAADCgYIBgABLAADCgcIBwAMAAAAAA==.Chinpokemon:BAACLAAFFIEGAAIWAAIIeA3JMwB1AAAWAAIIeA3JMwB1AAAsAAQKgSYAAxcACAhfDJ9DAMIBABcACAhfDJ9DAMIBABYACAgPDpx4AE8BAAAA.Chocomel:BAAALAAECgYIBgABLAAECgYIDQAMAAAAAA==.Chïps:BAABLAAECoEcAAMPAAcIqh1oHgBhAgAPAAcIqh1oHgBhAgALAAUI1whKGwDVAAAAAA==.',Ci='Ciber:BAAALAAECgIIAgAAAA==.',Cl='Claydavis:BAAALAAECgEIAQABLAAECggIGQASAGkXAA==.',Co='Coulson:BAAALAAECgYIDAAAAA==.Cousin:BAAALAADCggIEAAAAA==.',Cr='Crusto:BAAALAADCggICAAAAA==.Cruz:BAAALAAECgYIDwAAAA==.Cryptoscam:BAAALAADCggIGwAAAA==.',Cu='Cuckman:BAAALAADCggIHwABLAAFFAUIEAAFAPkSAA==.',Cy='Cy:BAABLAAFFIEFAAIWAAIIghrSHQClAAAWAAIIghrSHQClAAABLAAFFAIIBgAPALEiAA==.Cyguli:BAABLAAECoEUAAICAAgIBhsxMwB8AgACAAgIBhsxMwB8AgABLAAECggIKwAYAAAfAA==.Cynothoglys:BAAALAAECgEIAQAAAA==.',Da='Dacos:BAAALAADCgYIBgAAAA==.Dalish:BAABLAAECoEbAAISAAcIQxH3dgCEAQASAAcIQxH3dgCEAQAAAA==.Dalouch:BAAALAAECgUIBwAAAA==.Damae:BAAALAAECgEIAQAAAA==.Danii:BAAALAADCgcIBwAAAA==.Dankbemes:BAAALAAECgcIEwAAAA==.Dariann:BAAALAADCgIIAwAAAA==.Darkbee:BAABLAAECoEoAAITAAgIqRUCFwAjAgATAAgIqRUCFwAjAgAAAA==.',De='Deathanger:BAAALAAECggICAAAAA==.Defcons:BAAALAAECgYICwAAAA==.Demondög:BAAALAADCgQIBAAAAA==.Demonimies:BAABLAAECoESAAMYAAYIDiGMXgDZAQAYAAYIDiGMXgDZAQAZAAYIzBDHKgAhAQAAAA==.Demoninainen:BAAALAAECgYIBgAAAA==.Desepticon:BAABLAAECoEjAAICAAgI0hxQLQCSAgACAAgI0hxQLQCSAgAAAA==.Destromo:BAAALAAECgYIDgAAAA==.Detgodtrug:BAAALAADCgcIBwAAAA==.',Dh='Dhefra:BAAALAADCgYIBgAAAA==.',Di='Dialga:BAAALAADCgcICAAAAA==.Dingodile:BAAALAAECgIIAgAAAA==.Disarmed:BAABLAAECoEQAAIaAAgIIh9vAwDnAgAaAAgIIh9vAwDnAgAAAA==.Divinus:BAACLAAFFIEGAAIPAAIIQyOYEwDKAAAPAAIIQyOYEwDKAAAsAAQKgTIAAw8ACAgVJqoBAG0DAA8ACAgVJqoBAG0DAAoABwifGxcgAE8CAAAA.',Dm='Dmgdmgdmgdmg:BAABLAAECoEcAAMOAAgI7BzmHgCqAgAOAAgI7BzmHgCqAgAbAAMIERUeXwC8AAAAAA==.',Do='Dodor:BAAALAADCggICAAAAA==.Doe:BAAALAADCgcIBwAAAA==.Dom:BAAALAAFFAEIAQAAAA==.Donja:BAAALAAFFAIIAgABLAAFFAMICAAUAIAYAA==.',Dr='Dredex:BAAALAAECgYIDAAAAA==.Drullebror:BAAALAAECggICAAAAA==.Drunkenmonk:BAABLAAECoEVAAITAAcIvAg+MgBAAQATAAcIvAg+MgBAAQAAAA==.Druoc:BAAALAAECggIEgAAAA==.Druthus:BAAALAAECgIIAgAAAA==.Dryath:BAAALAAECggIAQAAAA==.',Ds='Dssod:BAAALAAECggICAAAAA==.',Dt='Dtrix:BAAALAAECgYICwAAAA==.',Du='Dukan:BAABLAAECoEVAAIWAAgIbhcIMQAkAgAWAAgIbhcIMQAkAgAAAA==.Duraps:BAAALAADCgYIBgAAAA==.Duriyel:BAAALAAECgYIBgABLAAECgYIDAAMAAAAAA==.',Dy='Dyck:BAAALAAECggICAAAAA==.',Dz='Dziaduch:BAAALAAECgIIAgAAAA==.',['Dø']='Dødskriger:BAAALAAECgEIAQAAAA==.',El='Elandriana:BAAALAAECgMIAwAAAA==.Eldric:BAAALAADCggIDQAAAA==.Elektraz:BAAALAADCggIEAAAAA==.Elementalls:BAAALAADCgQIBQAAAA==.Elementia:BAAALAADCggICAAAAA==.Ellathil:BAAALAAECgYIEwAAAA==.Elthalas:BAAALAADCgcIBwAAAA==.Elvost:BAABLAAECoEbAAIDAAgIqxwOEgCwAgADAAgIqxwOEgCwAgAAAA==.',Ep='Ephemei:BAAALAAECgcIBwABLAAECggICAAMAAAAAA==.',Er='Erlich:BAABLAAECoEfAAMIAAgIXh3fKgCaAgAIAAgIXh3fKgCaAgAJAAgIbA2uJgCuAQAAAA==.Erphados:BAAALAAECgYICAAAAA==.Erymanthos:BAAALAAECgYIBgAAAA==.',Es='Eskimos:BAAALAADCgcIBwAAAA==.Esrya:BAABLAAECoEaAAIcAAgIZQUOagD8AAAcAAgIZQUOagD8AAAAAA==.',Eu='Eunie:BAACLAAFFIEGAAIPAAIIsSJ5EwDLAAAPAAIIsSJ5EwDLAAAsAAQKgSoAAg8ACAjWJCgEAEcDAA8ACAjWJCgEAEcDAAAA.',Ev='Evilchaos:BAAALAADCggICAAAAA==.Evokussy:BAABLAAECoEWAAQNAAgI3RQMDgAYAgANAAgI3RQMDgAYAgAVAAYIfBXKCwBSAQAdAAQI+wbDSwCeAAAAAA==.Evöker:BAAALAAECgEIAQAAAA==.',Fa='Faitlesy:BAABLAAECoEeAAIDAAgIfiDKDwDJAgADAAgIfiDKDwDJAgAAAA==.Falcone:BAAALAAECggICAAAAA==.Falsorick:BAAALAADCgQIBAAAAA==.Fatboss:BAAALAADCgcIBwAAAA==.Fazzie:BAACLAAFFIEFAAICAAMIkhoUEgANAQACAAMIkhoUEgANAQAsAAQKgRYAAgIACAjdHzkcAN8CAAIACAjdHzkcAN8CAAAA.',Fe='Fear:BAAALAAECgcIBwAAAA==.Feldelphine:BAAALAAECgQIBAAAAA==.',Fi='Fiendall:BAAALAAECgYIDAABLAAECggILQABAFIaAA==.Fiendari:BAAALAAECgYICgABLAAECggILQABAFIaAA==.Fiendisha:BAABLAAECoEtAAMBAAgIUhr2CwB5AgABAAgIUhr2CwB5AgAGAAEI5wQkQAAmAAAAAA==.Fiizzy:BAAALAAECgMIAwABLAAECgYIBwAMAAAAAA==.Finbebiz:BAAALAAECgMIAwAAAA==.Firebread:BAAALAAECgYICQABLAAECgcIHQAGAJcjAA==.Firnae:BAAALAAECgMIBAAAAA==.Fisaar:BAAALAAECgMIBAAAAA==.Fishfryer:BAAALAADCgMIAwABLAAECgUIBQAMAAAAAA==.',Fl='Flage:BAAALAADCgcIBwAAAA==.Flendurs:BAAALAAECgIIAwAAAA==.Flonsky:BAAALAAECggIEAAAAA==.',Fo='Foilir:BAAALAADCggIDwAAAA==.Forestdaddy:BAABLAAECoEZAAIeAAgI4hNJMADnAQAeAAgI4hNJMADnAQAAAA==.',Fr='Fraggiz:BAAALAAECggICAAAAA==.Fristi:BAAALAAECgYIDQAAAA==.Frostiaz:BAAALAADCggIEAAAAA==.',Fu='Furryfrank:BAAALAAECggICAABLAAFFAUICwAPALIPAA==.',Ga='Gael:BAAALAADCgYIBgAAAA==.Gaintrain:BAACLAAFFIEEAAIUAAMIIBCrEADyAAAUAAMIIBCrEADyAAAsAAQKgR8AAhQACAixICMZAMoCABQACAixICMZAMoCAAAA.Galadrielq:BAAALAADCgYIDAAAAA==.Galagond:BAAALAADCgYIBgAAAA==.Gamebred:BAAALAADCgYIBgAAAA==.Gapehòrn:BAAALAADCggIDwAAAA==.Garzhaoel:BAABLAAECoEYAAQOAAgI3iBBGQDPAgAOAAgIgx5BGQDPAgAbAAMIhxr1UwDwAAAfAAII3RiiJgCUAAAAAA==.',Ge='Geoand:BAAALAAECgEIAQAAAA==.Georgemooney:BAAALAAECgEIAQAAAA==.Getitoffme:BAAALAAECgcICgAAAA==.',Gi='Gimlêe:BAABLAAECoEYAAIUAAgIlBziGwC2AgAUAAgIlBziGwC2AgAAAA==.Gipsymagic:BAAALAAECgMIAwAAAA==.Gitt:BAAALAADCgcIDQAAAA==.',Go='Gorethidus:BAAALAADCgYIBgABLAAECgYIDAAMAAAAAA==.Gorgothra:BAAALAADCgcIBwAAAA==.',Gr='Greenléaf:BAAALAAECgQIBAAAAA==.Grevane:BAABLAAECoEgAAIbAAgINgoCMQCGAQAbAAgINgoCMQCGAQAAAA==.Griever:BAAALAADCggIEAAAAA==.',Gu='Guido:BAAALAAECgcIEAAAAA==.Guldgrisen:BAAALAAECgEIAQAAAA==.',Gw='Gwinny:BAAALAADCgcIBwAAAA==.',Gy='Gygax:BAAALAADCgMIAwAAAA==.',Ha='Haagseharrie:BAABLAAECoEUAAISAAYIvhVWeACBAQASAAYIvhVWeACBAQAAAA==.Haeliós:BAAALAAECgYIBgAAAA==.Hair:BAAALAAECggIDQAAAA==.Hairyshooter:BAAALAADCgEIAQABLAAECgcICgAMAAAAAA==.Harrison:BAAALAADCgcIBwAAAA==.Hatchet:BAABLAAECoElAAIUAAgIpAvEaAB0AQAUAAgIpAvEaAB0AQAAAA==.Haude:BAAALAAECgUIBQAAAA==.',He='Hedra:BAAALAAECgYIEAAAAA==.Helsong:BAAALAADCgIIAgABLAAECggIGAAOAN4gAA==.',Hi='Hildurr:BAAALAADCgUIBQAAAA==.',Ho='Holydiva:BAAALAADCggICwAAAA==.Holyeras:BAAALAAECgEIAQABLAAECgIIAgAMAAAAAA==.Holykoli:BAAALAADCggICAABLAAFFAIICAADAPkYAA==.Holyra:BAABLAAECoEcAAIIAAcInRaYYgDwAQAIAAcInRaYYgDwAQAAAA==.Holyshield:BAAALAAECgIIAgAAAA==.Honeybunnie:BAAALAADCgUIBQAAAA==.',Hu='Hulm:BAAALAADCggICAABLAAFFAUIEAAFAPkSAA==.Humppa:BAAALAADCgQIBAAAAA==.Huntdany:BAAALAADCgUIBQABLAAECgIIAgAMAAAAAA==.Hunteror:BAAALAADCggIEAABLAAECgUIDgAMAAAAAA==.Hunterste:BAAALAADCgMIAwAAAA==.',['Hé']='Héllsangel:BAABLAAECoEYAAIeAAYIzBxzMADmAQAeAAYIzBxzMADmAQAAAA==.Hézdrøøn:BAAALAAECgQIBAAAAA==.',Ii='Iiana:BAAALAAECgYIEQAAAA==.',Il='Illemnorh:BAAALAADCgIIAgAAAA==.Illidanas:BAAALAAECgMIBgAAAA==.Illodan:BAAALAADCgcIBgAAAA==.',Im='Imagiination:BAAALAAECgYIEwAAAA==.Iminpain:BAABLAAECoEkAAMgAAgI6x0fDQC1AgAgAAgI6x0fDQC1AgAhAAMIMRYiLwDOAAAAAA==.Imka:BAABLAAECoEXAAIPAAcIRh+1GQCBAgAPAAcIRh+1GQCBAgABLAAECggIDgAMAAAAAA==.Immortalz:BAAALAAECggIEAAAAA==.Impact:BAAALAAECggIEAAAAA==.',In='Indiahna:BAAALAADCgcIBwAAAA==.Inferna:BAAALAADCggIDQABLAAECggIHwAIANwfAA==.Infestant:BAAALAADCgMIAwABLAAECgUIDgAMAAAAAA==.Infliction:BAAALAAECgYIDAAAAA==.Insanity:BAACLAAFFIEPAAIKAAQICCWhBQCyAQAKAAQICCWhBQCyAQAsAAQKgUYAAgoACAiPJTECAHMDAAoACAiPJTECAHMDAAAA.Insanus:BAAALAADCgcIBwAAAA==.Inushi:BAABLAAECoErAAIWAAgIbx7OFACtAgAWAAgIbx7OFACtAgABLAAECggIKwAYAAAfAA==.Invisium:BAABLAAECoEdAAIUAAgItBo/KABnAgAUAAgItBo/KABnAgAAAA==.Invoicer:BAAALAADCggIHgAAAA==.',Ir='Ironbru:BAAALAAECgYIBgAAAA==.Irridar:BAABLAAECoEfAAIYAAgIqhtXKgCJAgAYAAgIqhtXKgCJAgAAAA==.',Iu='Iustitia:BAAALAAECgQIBAAAAA==.',Ja='Jagguu:BAAALAADCgcIDwABLAAECgYIBgAMAAAAAA==.Jakeir:BAAALAADCgYIBgABLAAECgYICAAMAAAAAA==.Jakpala:BAAALAAECgYIBwABLAAECgYICAAMAAAAAA==.Jakunt:BAAALAAECgYICAAAAA==.Jammi:BAABLAAECoEWAAIJAAgIYSCeBQDyAgAJAAgIYSCeBQDyAgAAAA==.Jaysdead:BAAALAAECgIIBAAAAA==.',Je='Jeralt:BAAALAAECgYIBgABLAAFFAIIBgAPALEiAA==.',Ji='Jigsaw:BAAALAADCggIHQABLAAECgcIGAAJACYhAA==.Jilf:BAAALAAECgMIAwABLAAECggIDgAMAAAAAA==.Jilfie:BAAALAAECggIDgAAAA==.Jilfs:BAABLAAECoEXAAIYAAYIWiCIQgApAgAYAAYIWiCIQgApAgABLAAECggIDgAMAAAAAA==.',Jo='Joelgeorge:BAACLAAFFIEGAAMBAAIIgCMlEgBmAAABAAEI/iMlEgBmAAACAAEIAiPpXQBdAAAsAAQKgRkAAwIACAgmIlwbAOICAAIACAiMIFwbAOICAAEABAiYGRcrAEgBAAEsAAUUBggWABIA2SIA.Johnnik:BAAALAADCgcIBwAAAA==.Jollymeroger:BAAALAAFFAIIAgABLAAFFAYIDwASAGUaAA==.Jostivos:BAABLAAECoEZAAISAAgIaRd6RAAHAgASAAgIaRd6RAAHAgAAAA==.',Ju='Justholdthis:BAAALAADCgcIDgAAAA==.Jux:BAAALAADCgUIBQAAAA==.',['Jæ']='Jægarn:BAAALAAECgEIAQAAAA==.',Ka='Kadru:BAAALAAFFAIIAwAAAA==.Kaehl:BAAALAAECgYICwAAAA==.Kaizai:BAAALAAECgYIBgAAAA==.Kantanja:BAAALAAECgUIBQAAAA==.Kanylekalle:BAAALAAECggICAAAAA==.Katctus:BAAALAADCgcIBwAAAA==.Kathrina:BAAALAADCgMIAwAAAA==.Kaziulek:BAAALAADCgcICQAAAA==.Kazuki:BAAALAAECgYICQABLAAFFAUIEAAYADMbAA==.',Ke='Kecteh:BAACLAAFFIEIAAICAAIIoCHBHgDCAAACAAIIoCHBHgDCAAAsAAQKgSkAAgIACAhgJIQKAD4DAAIACAhgJIQKAD4DAAAA.Kedra:BAABLAAECoEYAAIFAAYI7hJscACOAQAFAAYI7hJscACOAQAAAA==.Kenita:BAAALAADCgYIBgAAAA==.Kenty:BAABLAAECoEgAAIfAAgIZRyNAwC2AgAfAAgIZRyNAwC2AgAAAA==.',Kh='Khaluna:BAAALAAECgYICQAAAA==.Khukali:BAAALAAECggICAAAAA==.Khâmul:BAAALAAECgMIBgAAAA==.',Ki='Killghost:BAABLAAECoEgAAIWAAcIyxOpYACPAQAWAAcIyxOpYACPAQAAAA==.Killwill:BAAALAAECggIDgAAAA==.Kitea:BAAALAAECgYIDAAAAA==.',Kn='Knab:BAAALAAECgIIAgABLAAECggIHgAeAOUiAA==.',Ko='Kolinje:BAACLAAFFIEIAAIDAAII+RheEgCYAAADAAII+RheEgCYAAAsAAQKgSoAAgMACAixJGAEAFMDAAMACAixJGAEAFMDAAAA.',Ku='Kurrosh:BAABLAAECoEOAAICAAcIJxbyewDDAQACAAcIJxbyewDDAQAAAA==.Kushrock:BAAALAAECgYIBgAAAA==.Kuzi:BAAALAADCggIIwAAAA==.Kuzisha:BAAALAADCggIDgAAAA==.',Kv='Kvòthe:BAABLAAECoEiAAIYAAgIcA57YgDPAQAYAAgIcA57YgDPAQAAAA==.',['Ké']='Kéno:BAAALAAECggIAQAAAA==.',La='Laguna:BAAALAADCgYIEQABLAAECggIHwAeAGMlAA==.Lakaz:BAAALAADCggIFAAAAA==.Lamindra:BAAALAAECggIEwAAAA==.Lastent:BAABLAAECoEdAAIGAAcIlyM5BwDKAgAGAAcIlyM5BwDKAgAAAA==.Lavsan:BAABLAAECoEdAAIUAAgIDxulKQBeAgAUAAgIDxulKQBeAgAAAA==.',Le='Lelthaes:BAABLAAECoEgAAIiAAgIVhXnDwAlAgAiAAgIVhXnDwAlAgAAAA==.Lethallars:BAAALAAECgUICgAAAA==.',Li='Lightknight:BAAALAAECggIEQAAAA==.Lightwork:BAAALAAECgcIDAAAAA==.Liinx:BAAALAAECgYIBgAAAA==.Lillath:BAAALAADCgcICwAAAA==.Lillea:BAACLAAFFIELAAIeAAMIyCQrBgBCAQAeAAMIyCQrBgBCAQAsAAQKgS8AAx4ACAgwJtsAAHQDAB4ACAgwJtsAAHQDACIABwjHEWUXAMABAAAA.Lilli:BAAALAAECggIAwAAAA==.Lilyth:BAAALAADCggIDwAAAA==.Lionjr:BAAALAAECgUIBQAAAA==.',Ll='Lliane:BAABLAAECoEfAAIIAAgIwxiCQABKAgAIAAgIwxiCQABKAgAAAA==.',Lo='Lokastico:BAAALAADCgUIBQAAAA==.Loker:BAACLAAFFIELAAMEAAIIdiN0BgDHAAAIAAIIIiDpEwDLAAAEAAIIfCJ0BgDHAAAsAAQKgSoAAwQACAidJSICAF4DAAQACAhxJSICAF4DAAgACAg0IE4dANsCAAAA.Lolibomb:BAAALAADCgUIBQAAAA==.Loodakl:BAAALAADCggIDwAAAA==.Loradana:BAAALAAECgEIAQAAAA==.Lortisen:BAAALAAECgUIBwAAAA==.Lotsalight:BAABLAAECoEfAAIIAAgIWh0rNgBsAgAIAAgIWh0rNgBsAgAAAA==.',Lu='Luftey:BAAALAAECgYICAAAAA==.Lumrene:BAAALAADCgIIAgAAAA==.Lussan:BAAALAAECggIBgAAAA==.',Ly='Lyreesa:BAAALAAECgIIAgABLAAECgQIBwAMAAAAAA==.Lythria:BAABLAAECoErAAIYAAgIAB8wHADTAgAYAAgIAB8wHADTAgAAAA==.',Ma='Magiemagie:BAAALAADCgUICQAAAA==.Magios:BAAALAAECgYIDQAAAA==.Maiznieks:BAAALAAECgYICQABLAAFFAUICgACAFMgAA==.Malefìco:BAAALAAECggIEQAAAA==.Malys:BAAALAAECgMIAwABLAAECgcIBwAMAAAAAA==.Marben:BAAALAADCgUIBQAAAA==.Mariahscary:BAAALAAECgEIAQABLAAECgcICgAMAAAAAA==.Marinadomine:BAAALAAECgYIBwAAAA==.Maugar:BAAALAADCgcICAAAAA==.Mayko:BAAALAADCgcIBwAAAA==.',Mc='Mcdodgen:BAAALAAECgEIAQAAAA==.',Me='Melhøna:BAAALAAECgMIBAAAAA==.Melkrek:BAABLAAECoEUAAIJAAcILh+SEABmAgAJAAcILh+SEABmAgAAAA==.Mellerr:BAAALAAECgUICwAAAA==.Membrain:BAABLAAECoEjAAIgAAgI3grWKADBAQAgAAgI3grWKADBAQAAAA==.Merithrâ:BAAALAAECgYIBgAAAA==.Metallicat:BAAALAAECgQIBAAAAA==.Methknyte:BAAALAAECggIBgAAAA==.Mewtwoo:BAAALAAECggIBwABLAAECgcILQAPAEIhAA==.',Mi='Milkhammer:BAABLAAECoEXAAIEAAcIjRtKFgAMAgAEAAcIjRtKFgAMAgAAAA==.Miniglowjob:BAAALAAECgQIEAAAAA==.Mistet:BAACLAAFFIENAAIQAAQIQRTEAAAyAQAQAAQIQRTEAAAyAQAsAAQKgR8AAhAACAhHHqcEAKMCABAACAhHHqcEAKMCAAAA.Mizhadin:BAAALAADCggIDQAAAA==.',Mo='Molybdenum:BAAALAADCgUIBQAAAA==.Momoayase:BAAALAADCgIIAgAAAA==.Mompumper:BAAALAAECgYIBgAAAA==.Moonduck:BAAALAAECgEIAQAAAA==.Moonshroud:BAAALAAECgEIAQAAAA==.Moonstar:BAAALAADCggIDgAAAA==.Morii:BAABLAAECoEVAAIUAAYIehvNTADJAQAUAAYIehvNTADJAQAAAA==.',Mu='Mubeen:BAAALAAECgYICQAAAA==.Murdorer:BAABLAAECoEYAAMcAAgIIRX8JwAVAgAcAAgIIRX8JwAVAgASAAMI3wqo4ACJAAABLAAFFAIICAADAPkYAA==.Murlock:BAAALAADCgMIAwAAAA==.',My='Myrrak:BAAALAADCgIIAgAAAA==.Mysticpete:BAABLAAECoEcAAIFAAgIpCArEwD+AgAFAAgIpCArEwD+AgAAAA==.',Na='Nahsoor:BAAALAADCgMIAwAAAA==.Naturefish:BAAALAAECgUIBQAAAA==.Navleuld:BAAALAAECgcIDgAAAA==.Nayla:BAAALAADCggIHwAAAA==.Nazztwink:BAAALAAECgcIBwABLAAFFAgIIQAFAIUgAA==.',Ne='Neophyte:BAAALAAECggICgAAAA==.Nerä:BAAALAADCggICQAAAA==.Nesyaa:BAAALAAECgYICgAAAA==.Nezarecc:BAACLAAFFIEGAAIOAAIIoRC4KACZAAAOAAIIoRC4KACZAAAsAAQKgSMAAg4ACAiAHhEaAMkCAA4ACAiAHhEaAMkCAAAA.',Ni='Nidanur:BAAALAADCggICAAAAA==.Nightprowler:BAAALAAECgMIBAABLAAECgYICgAMAAAAAA==.Niias:BAAALAADCgMIAwAAAA==.Nilsah:BAAALAAECggIEgAAAA==.Nimrod:BAAALAADCgcICwABLAAECgYIDQAMAAAAAA==.',Nk='Nkaral:BAAALAADCggICAAAAA==.',No='Noexcuses:BAAALAAFFAIIAgABLAAECgYIHAAFAAkfAA==.Nolin:BAAALAAECgIIAgAAAA==.Norby:BAAALAAECggIDgAAAA==.Notarms:BAAALAADCgUIBQABLAAECggIJgACADseAA==.Notinpain:BAAALAADCggICAAAAA==.Nototemz:BAAALAAECgIIAgABLAAECggIFAAUAKYRAA==.',Nu='Nucleus:BAAALAADCggIDwAAAA==.Nuggee:BAAALAADCgcIHAAAAA==.',Ob='Obilivian:BAAALAADCgcIBwAAAA==.Obliivian:BAAALAADCgMIAwAAAA==.Obliviaan:BAAALAAECgYIBgAAAA==.Oblivianetje:BAAALAADCgMIAwAAAA==.Obsydian:BAAALAADCggICQABLAAECgYIFwACAP8YAA==.',Oe='Oepabakkes:BAAALAADCggICAAAAA==.',Oi='Oinx:BAAALAADCggIDwAAAA==.',Ol='Oldalanor:BAAALAAECgYIEgAAAA==.Olluf:BAAALAADCggICAAAAA==.',Oo='Ooz:BAAALAAECgYIDwAAAA==.',Or='Oreó:BAAALAAECgcIEAAAAA==.Orsoeus:BAAALAADCggICAAAAA==.',Ow='Owtism:BAAALAADCgMIAwAAAA==.',Pa='Palahoof:BAABLAAECoEfAAIIAAgI3B9cHADhAgAIAAgI3B9cHADhAgAAAA==.Paldin:BAAALAAECgQICAAAAA==.Papithiccums:BAAALAAECgYICAAAAA==.Parlé:BAABLAAECoEmAAIjAAgIzB0qAwC8AgAjAAgIzB0qAwC8AgAAAA==.Particle:BAABLAAECoEdAAIXAAcIOiP2FQDIAgAXAAcIOiP2FQDIAgAAAA==.Pawkosmosu:BAAALAADCgQIBAAAAA==.',Pe='Perineum:BAABLAAECoEZAAIFAAgIpxjWLwBpAgAFAAgIpxjWLwBpAgABLAAFFAUIEAAFAPkSAA==.',Pi='Pitulica:BAAALAADCggIFQAAAA==.',Po='Pointblanc:BAAALAADCggIGQAAAA==.Polygnomial:BAAALAAECgYIBwAAAA==.',Pr='Prajala:BAABLAAECoEfAAIUAAgI6xq0HwCbAgAUAAgI6xq0HwCbAgAAAA==.Prawnhub:BAAALAAECgYIBwAAAA==.Predatorian:BAAALAAECgYIBwAAAA==.Prospectss:BAABLAAECoEsAAMkAAgIHCMLBQAJAwAkAAgI/CELBQAJAwATAAcIkCPHDACoAgAAAA==.Prïesty:BAABLAAECoEXAAIKAAcI6xWnLwDpAQAKAAcI6xWnLwDpAQAAAA==.',Pu='Pufoshenie:BAAALAAECgIIAgAAAA==.Purkkapallo:BAABLAAECoEUAAIUAAgIphGzPQABAgAUAAgIphGzPQABAgAAAA==.Purpleboii:BAAALAADCgYIBgAAAA==.',['Pá']='Pálm:BAAALAAECgYIBgAAAA==.',Qu='Quill:BAAALAAECgcIDAAAAA==.Quinshi:BAAALAAECgIIAwAAAA==.Quistis:BAABLAAECoEfAAIeAAgIYyVlAQBlAwAeAAgIYyVlAQBlAwAAAA==.',Ra='Raisu:BAAALAAECgMIAwAAAA==.Rakeland:BAACLAAFFIEQAAIFAAUI+RLRCwCmAQAFAAUI+RLRCwCmAQAsAAQKgSkAAgUACAjuISAWAO0CAAUACAjuISAWAO0CAAAA.Rakke:BAABLAAECoEVAAIZAAYIhRQnIgBiAQAZAAYIhRQnIgBiAQABLAAFFAUIEAAFAPkSAA==.Rawked:BAAALAAFFAEIAQAAAA==.Rayalyn:BAAALAAECgMIBgAAAA==.',Re='Realia:BAABLAAECoEmAAIYAAgIjB8fJQCjAgAYAAgIjB8fJQCjAgAAAA==.Refra:BAABLAAECoEvAAIgAAgI2h/ECQDfAgAgAAgI2h/ECQDfAgAAAA==.Rejseholdet:BAAALAADCgcIDwAAAA==.Rengos:BAAALAAECgYIEwAAAA==.',Rf='Rflex:BAACLAAFFIEGAAIcAAIIWhSOGgCJAAAcAAIIWhSOGgCJAAAsAAQKgSQAAxwACAiAG7weAFQCABwACAhrGrweAFQCABIABAgtGE6kACcBAAAA.',Rh='Rhollor:BAAALAAECgYICQAAAA==.',Ri='Rife:BAAALAADCgYICQAAAA==.Rivso:BAAALAADCgQIBAAAAA==.',Ro='Robdobbob:BAABLAAECoEYAAMlAAgI6RZpIADzAQAlAAgItxNpIADzAQAUAAcIGxXFSgDQAQAAAA==.Rockerul:BAAALAADCgcIBwAAAA==.Roflmywaffle:BAAALAADCgMIAwAAAA==.Rood:BAAALAADCgEIAQAAAA==.Royal:BAABLAAECoEaAAIHAAgIlxznCwC6AgAHAAgIlxznCwC6AgAAAA==.',Ru='Ruggi:BAAALAAECgYIEQAAAA==.Runbaby:BAAALAAECgIIAgAAAA==.Runeforged:BAAALAAECgUIDgAAAA==.',Ry='Ryona:BAAALAADCgEIAQAAAA==.',['Rà']='Ràven:BAAALAAECgEIAQAAAA==.',['Rø']='Røcketh:BAAALAADCgIIAgAAAA==.',Sa='Sabtism:BAABLAAECoEhAAIFAAgIPRqPNQBQAgAFAAgIPRqPNQBQAgAAAA==.Sadness:BAAALAAECggIEAAAAA==.Sancta:BAAALAAECgYIDAAAAA==.Sangraal:BAACLAAFFIERAAIIAAUIsyOcAQArAgAIAAUIsyOcAQArAgAsAAQKgTAAAggACAjWJp8AAJoDAAgACAjWJp8AAJoDAAAA.Saragosa:BAAALAAECgcIEgAAAA==.Sarvon:BAAALAADCgYIBwAAAA==.Sathrago:BAAALAAECgUIBQAAAA==.Savaged:BAAALAADCgYIBgABLAAECgcIDwAMAAAAAA==.',Sc='Scabz:BAAALAADCgQIBAAAAA==.Screwnut:BAAALAAECgcICAAAAA==.Scxrm:BAABLAAECoEdAAICAAcI2CFJPgBWAgACAAcI2CFJPgBWAgAAAA==.',Se='Secho:BAAALAAECgYIDwAAAA==.Sempie:BAABLAAFFIEHAAIQAAMIOxR3AQDWAAAQAAMIOxR3AQDWAAAAAA==.Serialhealer:BAAALAAECgYIEgAAAA==.Seriallock:BAAALAADCgYIBgAAAA==.',Sh='Shadowfalcón:BAABLAAECoEeAAISAAgIfhIFXwC9AQASAAgIfhIFXwC9AQAAAA==.Shadowmeld:BAAALAAECgMIBgAAAA==.Shadowvirus:BAAALAAECggICwAAAA==.Shaku:BAAALAAECgQIBAABLAAECggIOwATAA4mAA==.Shaldir:BAAALAADCggIHQABLAAECgYIFAAgAEENAA==.Shanked:BAAALAAECgIIAgAAAA==.Shekah:BAAALAAFFAEIAQAAAA==.Shivadestroy:BAAALAADCggICAAAAA==.Shuvodk:BAABLAAECoEZAAMGAAcIOyAxDABZAgAGAAcIhR8xDABZAgABAAIItxVIQgCTAAAAAA==.Shèrlock:BAACLAAFFIEGAAIOAAIIiyK1HADEAAAOAAIIiyK1HADEAAAsAAQKgSsABA4ACAjeIwAKADcDAA4ACAiiIwAKADcDABsABQjUH+EhANUBAB8AAgiuGwwjAK8AAAAA.',Si='Sicklikenes:BAAALAAECggICAAAAA==.Silverspring:BAAALAADCgcICAABLAAECgcICAAMAAAAAA==.Sindrala:BAAALAAECggIEwABLAAECggIHwAYAKobAA==.',Sj='Sjåman:BAAALAADCgcIDgAAAA==.',Sk='Skräcken:BAAALAADCgcIBwAAAA==.Skáld:BAAALAADCgUIBQAAAA==.Ský:BAAALAAECgYIBgAAAA==.',Sm='Smaky:BAAALAADCgUICgABLAAECgUIDgAMAAAAAA==.',Sn='Snegla:BAAALAADCgQIBAAAAA==.',So='Sockybean:BAAALAAECgIIAgAAAA==.Solibell:BAABLAAECoEnAAIDAAgIlhrLGgBYAgADAAgIlhrLGgBYAgAAAA==.Solmyr:BAAALAADCgcIBwAAAA==.Soulstorm:BAAALAADCggIEAABLAAECggILAAeAI4aAA==.',Sp='Spacecoconut:BAAALAAECggIDwAAAA==.',Sq='Squanch:BAAALAADCggICAAAAA==.Squanchy:BAAALAADCgYIBgABLAADCggICAAMAAAAAA==.',Sr='Srf:BAAALAAECgIIAgAAAA==.',St='Starnote:BAAALAADCggIFQAAAA==.Stax:BAAALAAECgYIBwAAAA==.Steelrose:BAABLAAECoEfAAIIAAgIygk0uABKAQAIAAgIygk0uABKAQAAAA==.Stompus:BAAALAADCgUIBQAAAA==.Stormbloodia:BAAALAADCgcIBwAAAA==.Stormseer:BAAALAADCggICAABLAAECggILAAeAI4aAA==.Stow:BAAALAAECggIEAAAAA==.Stststutter:BAAALAADCgEIAQAAAA==.Stylios:BAAALAADCgMIAwAAAA==.',Su='Subarusushi:BAAALAADCgYIBgAAAA==.Substealth:BAAALAAFFAIIAgAAAA==.Sujiro:BAAALAADCgcIBwAAAA==.Suzu:BAAALAADCggIEAABLAAECggIJwADAJYaAA==.',Sw='Sweatypumpum:BAAALAADCggICAAAAA==.',Sy='Sylfer:BAAALAAECgMIAwAAAA==.',['Sé']='Séxydk:BAAALAAECgYICgAAAA==.Séxyhuntér:BAAALAAECgYIBgAAAA==.Séxyshammy:BAACLAAFFIEGAAIXAAUInBMKBwCyAQAXAAUInBMKBwCyAQAsAAQKgSYAAhcACAh0I/0JAC4DABcACAh0I/0JAC4DAAAA.',['Só']='Sóul:BAAALAADCggIEAAAAA==.',Ta='Taboo:BAAALAAECgUIBQAAAA==.Tailung:BAAALAADCggICAAAAA==.Takku:BAAALAAECgIIAgAAAA==.Tame:BAAALAAECgQIBQABLAAECgYIBgAMAAAAAA==.',Tc='Tchiloa:BAAALAADCgcIBwAAAA==.',Te='Teeqrah:BAAALAAECgcIDwAAAA==.Tenebrous:BAAALAADCgUIBgAAAA==.Tentac:BAAALAADCgUIBQAAAA==.Testudo:BAABLAAECoEVAAMPAAYIOR+mLQAHAgAPAAYIHx6mLQAHAgALAAIIDiMsHQDBAAAAAA==.',Th='Thale:BAAALAADCgEIAQAAAA==.Theevil:BAAALAAECgEIAgAAAA==.Thicbackshot:BAAALAADCgYICAAAAA==.Thiccnsaucy:BAAALAADCgcIBwAAAA==.Thorinn:BAAALAADCgYIBgAAAA==.Thorontur:BAAALAAECgMIAgAAAA==.Threetoe:BAAALAADCggICAABLAAECggICAAMAAAAAA==.Thunderfist:BAAALAAECgMIBAABLAAECggIFQAYAAUPAA==.',Ti='Tiggi:BAAALAAFFAEIAQABLAAFFAUIDwAPAMoXAA==.Tiggye:BAABLAAECoEbAAIPAAYIcx8PKQAgAgAPAAYIcx8PKQAgAgABLAAFFAUIDwAPAMoXAA==.Titancore:BAAALAAECgYICQAAAA==.',Tj='Tjòngejonge:BAAALAAECgYIEwAAAA==.',To='Toffifee:BAAALAAECggIEQAAAA==.Totaltilt:BAAALAADCgUIBQABLAADCggIEAAMAAAAAA==.',Tr='Trainerdirk:BAAALAAECgYIEgAAAA==.Trancè:BAAALAADCgYIBgAAAA==.Trickis:BAAALAAECggIEAAAAA==.Tricksis:BAABLAAECoEmAAISAAgIdyQAEAABAwASAAgIdyQAEAABAwAAAA==.Trippin:BAABLAAECoEaAAIJAAgIXhlLFABAAgAJAAgIXhlLFABAAgAAAA==.Trish:BAAALAAECgUIDgAAAA==.Trockz:BAAALAAECggIDwABLAAECggIKAAUAB8fAA==.Trophybf:BAAALAAECgQICAABLAAFFAUIEAAFAPkSAA==.Truhartt:BAAALAAECgMIAwAAAA==.',Ts='Tsulix:BAAALAAECggICwABLAAFFAUIEQAkAAwIAA==.',Tu='Tuntamage:BAACLAAFFIEGAAIFAAIIkxJzLgCbAAAFAAIIkxJzLgCbAAAsAAQKgSMAAgUACAh3HZokAKACAAUACAh3HZokAKACAAEsAAUUAggIAAMA+RgA.Turnip:BAABLAAECoEcAAIDAAcIDh4OGgBfAgADAAcIDh4OGgBfAgAAAA==.Tuska:BAAALAAECgYIBgABLAAECgcIBwAMAAAAAA==.Tuunta:BAAALAADCgQIBAABLAAFFAIICAADAPkYAA==.',Tw='Twilightbeam:BAABLAAECoEgAAMPAAgIxw+gNgDZAQAPAAgIxw+gNgDZAQAKAAEIIwbJhwA0AAAAAA==.Twìxx:BAABLAAECoElAAMIAAgIUhgKTQAlAgAIAAgIUhgKTQAlAgAEAAQI5A9MPwDVAAAAAA==.',Ty='Tydus:BAAALAAECgYICAABLAAECggIHwAeAGMlAA==.Tygaren:BAAALAADCgcIEAAAAA==.Tygran:BAAALAAECgYICAAAAA==.',Tz='Tzüky:BAAALAAECgYIBgAAAA==.',Ul='Ultrax:BAAALAAECggICAAAAA==.',Un='Unideath:BAAALAAECgYIBgAAAA==.Unimagi:BAABLAAECoEbAAIFAAgItyQmCABDAwAFAAgItyQmCABDAwAAAA==.',Us='Ustári:BAAALAAECgIIAgAAAA==.',Va='Valyran:BAAALAAECgIIAgAAAA==.Vanderguard:BAAALAADCgMIAwAAAA==.Vanesa:BAABLAAECoEnAAIOAAgIJBdWLQBYAgAOAAgIJBdWLQBYAgAAAA==.',Ve='Vektron:BAAALAAECgQIBAAAAA==.Venoms:BAAALAAECgMIAwAAAA==.Verithria:BAAALAADCggICAAAAA==.Vespera:BAAALAAECgYIEgAAAA==.',Vi='Viranty:BAAALAADCgcIBwAAAA==.',Vo='Voidhoe:BAAALAAECgYIDgABLAAECggIJQAHAOkbAA==.Voidlord:BAAALAADCggIIQAAAA==.Voidstalker:BAAALAAECgYIEwAAAA==.Volkar:BAAALAAECgcIBwAAAA==.Voodoodudu:BAABLAAECoEoAAIQAAgI5iTsAABlAwAQAAgI5iTsAABlAwAAAA==.Voodoojuju:BAAALAAECggIDAAAAA==.Voof:BAAALAAECgUIBQAAAA==.',Vt='Vtz:BAAALAAECggIEwAAAA==.',Vu='Vuurvlaag:BAAALAADCgcICAAAAA==.',['Vå']='Våjdälfmage:BAAALAAECgYIBgAAAA==.',Wa='Warchiéf:BAAALAADCggIFwAAAA==.Warnaax:BAAALAADCggIGAABLAAECggIHwAYAKobAA==.Warnarki:BAABLAAECoEcAAIlAAgIrRiUGgAiAgAlAAgIrRiUGgAiAgAAAA==.Wasnar:BAAALAAECgYIEwAAAA==.Wata:BAAALAADCgEIAQAAAA==.Waterboyxd:BAABLAAECoEdAAIIAAgIaBFcmgCAAQAIAAgIaBFcmgCAAQAAAA==.',We='Wees:BAABLAAECoEbAAINAAgI2gtNGACAAQANAAgI2gtNGACAAQAAAA==.',Wh='Whez:BAAALAAECgYIEwABLAAECggIIwAIAAMfAA==.Whumle:BAAALAADCggIDwABLAAECggIHgAlAKYhAA==.',Wi='Wildstorm:BAABLAAECoEsAAMeAAgIjhrBFwBzAgAeAAgIjhrBFwBzAgAQAAEI+ghPLQAmAAAAAA==.',Wo='Wombo:BAABLAAECoEeAAIlAAgIpiG6CQDjAgAlAAgIpiG6CQDjAgAAAA==.',Wr='Wrain:BAAALAAECggIBwAAAA==.',Xa='Xandre:BAAALAAECgYIBgABLAAECggIHgAlAKYhAA==.',Xe='Xeld:BAAALAADCgcIBwAAAA==.Xenodrood:BAAALAAECgMIBAABLAAFFAUIEQAIALMjAA==.Xerathar:BAAALAAECggIDAABLAAFFAQIDwAKAAglAA==.',Ya='Yabas:BAABLAAECoEaAAMXAAgIQAqZTACgAQAXAAgIQAqZTACgAQAWAAYIzheRagBzAQAAAA==.',Ye='Yelunara:BAAALAAECgYIDQAAAA==.',Yi='Yimoo:BAABLAAECoEeAAIFAAgIDhavNwBGAgAFAAgIDhavNwBGAgAAAA==.',Yo='Yoshihoudini:BAAALAADCgQIBAAAAA==.Yoshinoel:BAAALAAECgEIAQAAAA==.Yoshix:BAAALAAECgIIAgAAAA==.',Ys='Yserah:BAABLAAECoEbAAIdAAgIYBhtFgBWAgAdAAgIYBhtFgBWAgAAAA==.Ysèra:BAAALAADCggIGwAAAA==.',Yu='Yuma:BAABLAAECoEfAAIWAAcIDBPnXwCRAQAWAAcIDBPnXwCRAQAAAA==.Yumeth:BAAALAAECgYIEAAAAA==.Yumyam:BAAALAAECgMIAgAAAA==.Yunalesca:BAAALAAECgEIAQAAAA==.',Za='Zaratavex:BAAALAADCgIIAgAAAA==.',Ze='Zealicious:BAABLAAECoEkAAIFAAgIdyMuEwD+AgAFAAgIdyMuEwD+AgAAAA==.Zedomeld:BAAALAAECgYIEwABLAAECggIFAACAOcWAA==.Zellon:BAAALAADCggIFgAAAA==.Zendh:BAABLAAECoEXAAIYAAcI+BZ4XwDXAQAYAAcI+BZ4XwDXAQAAAA==.Zeneve:BAAALAAECgEIAQAAAA==.Zerethia:BAAALAAECgYIDgAAAA==.Zeriza:BAAALAAECgUIBQAAAA==.Zerryx:BAAALAAECgUIBQAAAA==.',Zh='Zhug:BAABLAAECoEXAAMCAAYI/xgzfgC+AQACAAYI/xgzfgC+AQABAAIIQxSuRwBuAAAAAA==.',Zi='Zigeuner:BAAALAADCgcIBwAAAA==.Ziyech:BAAALAAECgYICgAAAA==.',['Ás']='Ása:BAAALAAECgQICwAAAA==.',['Él']='Élmo:BAABLAAECoEgAAIWAAgIOCETDgDcAgAWAAgIOCETDgDcAgAAAA==.',['Ón']='Óni:BAAALAAECgEIAQAAAA==.',['Öh']='Öhbrudar:BAAALAADCgMIAwAAAA==.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end