-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ptBR') -- luacheck: ignore
L["Artwork opacity"] = "Opacidade da arte"
L["Artwork style"] = "Estilo da arte"
L["Button scale"] = "Escala do botão"
L["Hide cooldown text"] = "Esconder texto de recarga"
L["Only show for quests in current zone"] = "Mostrar apenas para missões na zona atual"
L["Only show for tracked quests"] = "Mostrar apenas para missões rastreadas"
L["Tracking distance"] = "Distância de rastreamento"

